syslog-ng/syslog-ng

- lib/cfg-block-generator.c
- lib/cfg-block.c
- modules/appmodel/app-parser-generator.c
- modules/appmodel/tests/test_app_parser_generator.c
There are configuration features, that in the background generates additional configuration. They are pretty cool, but sometimes hard to debug as a user.
A good example is the `system` source, there is a script to print out what is generated emplace of the `system` source: `modules/system-source/system-expand.sh`
The result is going to be the following: (good luck with that)
```
channel {
source {
channel {
source { unix-dgram("/dev/log" so_rcvbuf(8192));
};
rewrite { set("${.unix.pid}" value("PID") condition("${.unix.pid}" ne "")); };
};
file("/dev/kmsg" program-override("kernel") flags(kernel) format(linux-kmsg) keep-timestamp(no));
}; # source
channel {
channel {
parser {
channel {
junction {
};
}
;
channel {
junction {
channel {
parser {  json-parser(prefix('.cim.') marker('@cim:')); …
```
> Decorating generated configuration

- tests/functional/test_python.py
Otherwise it is possible that not every message received (eg.: when
start syslog-ng with 'Fevdt' in control.py).
> test_python: flush before stopping syslog-ng

- doc/man/loggen.1.xml
- tests/loggen/CMakeLists.txt
- tests/loggen/Makefile.am
- tests/loggen/file_reader.c
- tests/loggen/file_reader.h
- tests/loggen/loggen.c
- tests/loggen/loggen_helper.c
- tests/loggen/loggen_helper.h
- tests/loggen/tests/CMakeLists.txt
- tests/loggen/tests/Makefile.am
- tests/loggen/tests/test_loggen_filereader.c
The space in the "File reader" makes hard to call
--help-File reader option. I removed the space.
A further clarification is about error message when
none of the plugins are activated. As a hint it print outs
the most frequently forget option -S
loggen was able to parse BSD (RFC3164) formated loglines
read from file. With this patch loggen is able to parse both RFC3164
and RFC5424 (syslog format).
It also fixes the possible buffer overrun in the old parse_line
function.
The deafult value of --skip-token has been changed to 0
as this is more intuitive as the old value 3. You have to use
the --skip-token option if and only if you want to skip the first N
token of the loglines. Otherwise you shouldn't care this option.
a new unittest has been added to test the file reader's
parser functions. …
> Loggen: improve file reader parse function

- lib/debugger/debugger.c
The debugger runs in its dedicated thread, so we need to initialize it
as a thread so stuff like template function evaluation works, since
it depends on scratch buffers.
> debugger: fix template function evaluation

- lib/early_ack_tracker.c
> early-ack-tracker: do not wakeup source when the ack type is SUSPENDED

- .travis.yml
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/str-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
This patch adds $(base-encode ...) template function, which encodes
the concatenated arguments using base64. No delimiters are added
between strings, so:
$(base64-encode foo bar) would encode "foobar".
Originally contributed by Ferenc Sipos <ferenc.sipos@oneidentity.com>
> Base64 encoding template function

- lib/filter/filter-call.c
- lib/filter/filter-cmp.c
- lib/filter/filter-in-list.c
- lib/filter/filter-netmask.c
- lib/filter/filter-netmask6.c
- lib/filter/filter-pipe.c
- lib/filter/filter-pri.c
- lib/filter/filter-re.c
- lib/filter/filter-tags.c
- lib/logmsg/logmsg.c
- lib/logpipe.h
- lib/logsource.c
- lib/messages.h
- lib/parser/parser-expr.c
- lib/rewrite/rewrite-expr.c
- modules/add-contextual-data/add-contextual-data.c
- modules/csvparser/csvparser.c
- modules/date/date-parser.c
- modules/dbparser/dbparser.c
- modules/geoip/geoip-parser.c
- modules/geoip2/geoip-parser.c
- modules/http/http.c
- modules/json/json-parser.c
- modules/kvformat/kv-parser.c
- modules/map-value-pairs/map-value-pairs.c
- modules/python/python-logparser.c
- modules/snmptrapd-parser/snmptrapd-parser.c
- modules/syslogformat/syslog-parser.c
- modules/tagsparser/tags-parser.c
- modules/xml/xml.c
I think our debug log is flooded, so I've opened this PR to
- make it possible to enable trace messages with the `--trace` or `-t` command line flag, even if syslog-ng was not compiled in debug mode
- move frequent, per-message internal messages to the trace log level.
This won't have any performance implications, because we already have 166 debug messages compared to 10 existing trace messages.
My intention is to make our debug logs manageable in case there are more than 10-20 messages passing through syslog-ng. This way we can ask for debug logs from production environments without generating ~15-50 lines of debug information for each incoming message (15 using a trivial configuration, 50 with a non-trivial one).
But of course, when trace is required, it can be enabled without …
> Use msg_trace() when emitting trace information

- lib/logproto/logproto-framed-client.c
- lib/logproto/logproto-text-client.c
- lib/logproto/logproto.h
- lib/logwriter.c
- lib/transport/transport-tls.c
The `LogQueue` and the `LogProto` has shared knowledge about the messages states.
The `LogQueue` holds the messages(both need processing, and ones in processing), in case of partial message(the whole message was not sent), the `LogProto` knows, which part of the message is sent and not, from the `LogQueue` point of view that partial message is still in progress. Which is fine, as long as we have both the `LogQueue` and the `LogProto`.
Actually we keep the `LogProto` around as long as the connection is alive, when the connection is closed the `LogProto` and the partial state of the message is thrown away.
Base on the above, if there is a partial message, when the connection is closed (by destination), the partial (and correct) state of the actually processed message is gone. That message …
> LogProto partial write

- scl/CMakeLists.txt
- scl/Makefile.am
"Oops!... I Did It Again"
This commit fixes https://github.com/balabit/syslog-ng/pull/2186
where I added a new SCL without adding it to make files. With
this fix the linux-audit SCL is included in the release tgz.
>  scl: add linux-audit() SCL to make files

- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java
Archiving and append are 2 conflicting use cases.
Archiving is for moving closed file to a dir declaring that processing on that file have finished.
If we would allow appending an archived file it would not really be archived.
Originally I suspected a bug when the two options used simultaneously,
however the rename() call from hdfs lib prevents overwriting an existing file.
This patch fixes the current issue of archiving a file once, then using
the original file indefinitely.
> Hdfs: disable archive when append-enabled is configured

- tests/functional/globals.py
Note: I removed all the TLS tests from the func-test (temporarily).
On my machine (Ubuntu Bionic) the func-test just failed with a strange error message:
```##############################################
##############################################
2018-08-21T14:44:23 Testcase start
Error parsing source statement, source plugin pipe not found in test.conf:
3       options { ts_format(iso); chain_hostnames(no); keep_hostname(yes); threaded(yes); };
4
5       source s_int { internal(); };
6       source s_unix { unix-stream("log-stream" flags(expect-hostname) listen-backlog(64)); unix-dgram("log-dgram" flags(expect-hostname));  };
7       source s_inet { tcp(port(35147) listen-backlog(64)); udp(port(35147) so_rcvbuf(131072)); };
8-----> source s_pipe { pipe("log-pipe" …
```
> tests/functional/globals.py: fix module-path generation

- lib/cfg-block.c
- lib/cfg-lex.l
- lib/persist-state.c
- lib/plugin.c
- lib/tlscontext.c
- modules/diskq/qdisk.c
- modules/getent/getent-group.c
- modules/getent/getent-passwd.c
- modules/getent/tfgetent.c
msg_* macros put a NULL at the end of parameter list when call msg_event_suppress_recursions_and_send()
> msg parameters: remove last NULL parameter from msg_ macros

- dbld/images/centos7.dockerfile
Currently we failed to install the latest versions of pip packages in the centos7 image, because epel has an outdated version from pip.
See #2187 for details. (fixes #2187)
> dbld/images/centos7: add pip update to the dockerfile

- lib/tests/test_logthrdestdrv.c
1. The queued counter is decremented before calling `insert()` or `flush()`. Therefore, `queued_messages` is not suitable for conditional waiting in `test_explicit_ack_accept`.
2. `flush()` is called after every `_perform_inserts()` even when the batch size is 0.
Because 3 batch-related test cases check whether the batch size remains the same across retries, `WORKER_INSERT_RESULT_SUCCESS` should be returned from `flush()` in case of an empty batch.
Reproduction: 
```sh
while lib/tests/test_logthrdestdrv --filter "logthrdestdrv/when_batched_*"; do :; done
```
From `_perform_flush`:
>  NOTE: earlier we had a condition on only calling flush() if batch_size is non-zero.  This was removed, as the language bindings that were done  _before_ the batching support in LogThreadedDestDriver relies on …
> Fix threaded destination test cases

- .gitmodules
- .travis.yml
- autogen.sh
- configure.ac
- contrib/Brewfile
- modules/afmongodb/Makefile.am
Fixes #2200 
Follow up for #2052
> Do not ship mongo-c-driver with syslog-ng (remove as submodule)

- dbld/images/artful.dockerfile
- dbld/images/jessie.dockerfile
- dbld/images/required-epel/all.txt
- dbld/images/required-obs/all.txt
- dbld/images/trusty.dockerfile
- dbld/images/xenial.dockerfile
The distribution provided gradle binaries are often not good enough,
either because they are too old or they are buggy.
Use the binary provided by the gradle project.
> dbld: use upstream gradle binaries

- lib/logwriter.c
- modules/affile/affile-dest.c
- modules/afsocket/afinet-dest-failover.c
- modules/afsocket/afsocket-dest.c
Thank you @mitzkia for the finding!
While the timer values are "NONNEGATIVE_INTEGER"s from the config, (so potentially overflowing values are causing config errors), we multiply them (usually with 1000 to get msec from sec) as integers before passing it as long to timespec_add_msec which might cause integer overflow. As a result these timers expires immediatelly as they set.
> logwriter, affile, afsocket: fixing "internal overflow".

- modules/http/http-grammar.ym
- modules/http/http-parser.c
- modules/http/http.c
- modules/http/http.h
This series of patches add body-prefix(), body-suffix() and delimiter() option to the http driver, so that
one case create proper framing around items (formatted by the template specified with body()).
This allows us to post proper JSON encoded arrays as POST payloads, which is required by a number of REST APIs.
I am working on splitting the HTTPDestinationDriver class into a separate Worker and Driver class, which would make it easier to do actual testing in the http destination. Right now, I only did manual tests and it does work and the patches are simple enough. My refactorings are subsequent to this, and it is far from trivial to do bring testing in front of this patch, so please merge this without tests at this point.
Thanks.
> Http framing support for batches

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/cfg.c
- lib/cfg.h
- modules/affile/tests/test_wildcard_source.c
- modules/affile/wildcard-source.c
- modules/affile/wildcard-source.h
- modules/afsocket/afsocket-source.c
Decreasing log_iw_size to a low value could cause performance regression in
syslog-ng, but in some cases in order to reduce the memory consumption, we need
to reduce it to a certain value.
To preserve backward compatibility, a new global option has been introduced to
mitigate this issue. Using min_iw_size_per_connection we can lower that limit
from the previously hard-coded value.
Warning: lowering this value could cause performance degradation.
Signed-off-by: Peter Gyorko <peter.gyorko@balabit.com>
> afsocket: implemented min_iw_size_per_connection global option

- modules/affile/directory-monitor-poll.c
With monitor_method(poll), when a tracked directory is deleted: g_dir_open allocated a
GError structure with the error: No such file or directory. This
must be freed by syslog-ng.
> wildcard-file: poll method directory delete related leak

- packaging/rhel/syslog-ng.spec
Fixes: #2262, by installing gradle manually we do not fulfill the "package requirement" of the specfile.
> syslog-ng.spec: remove gradle from the list of "BuildRequires"

- .travis.yml
- lib/logthrdestdrv.c
- lib/logthrdestdrv.h
- lib/tests/test_logthrdestdrv.c
- modules/http/http-grammar.ym
- modules/http/http.c
- modules/http/http.h
This branch implements the flush-timeout() option for LogThreadedDestDriver, which works very similarly to what we had earlier (e.g. pre syslog-ng 3.3).
Then it makes this option available to the HTTP destination driver. This should fix CPU consumption issues for elasticsearch, such as #2131.
After giving some though whether we should simply use the old option name (e.g. flush-timeout()) or introduce a new one, I've finally concluded on simply using the old one, meaning that it should be brought out of deprecation. But looking at it closely, that deprecation wasn't very successful, in the sense it has not been documented.
This also means that the flush-timeout() and flush-lines() options would be inherited automatically from the global options. This branch implements that as well for the …
> implement flush-timeout() for http

- lib/CMakeLists.txt
- lib/Makefile.am
- lib/logthrsource/CMakeLists.txt
- lib/logthrsource/Makefile.am
- lib/logthrsource/logthrfetcherdrv.c
- lib/logthrsource/logthrfetcherdrv.h
- lib/logthrsource/logthrsourcedrv.c
- lib/logthrsource/logthrsourcedrv.h
- lib/logthrsource/tests/CMakeLists.txt
- lib/logthrsource/tests/Makefile.am
- lib/logthrsource/tests/test_logthrfetcherdrv.c
- lib/logthrsource/tests/test_logthrsourcedrv.c
- tests/copyright/policy
This PR makes it easier to implement log sources that require a dedicated thread.
A dedicated thread is useful when blocking calls have to be used, or when one wants to integrate an external event loop with syslog-ng.
The PR  contains 2 new abstract classes, `LogThreadedSourceDriver` and `LogThreadedFetcherDriver`. They can be used as a base for new threaded sources. 
For example, balabit/syslog-ng#2248.
----
**`LogThreadedSourceDriver`** provides a new thread and a simple interface to forward `LogMessage`s to the next pipeline element. `run()` and `request_exit()` are its main abstract methods. The driver class can be used in two ways:
1. The "blocking API" takes care of the flow control of the source automatically by suspending the thread when the destination queue is full.
2. The …
> Threaded source and fetcher

- lib/cfg-lex.l
- lib/template/compiler.c
- lib/template/tests/test_template.c
- lib/tests/test_lexer.c
This branch allows one to embed newline characters in template function invocation so they become more readable.
for instance, with this patch this specification works:
```
file("whatever" 
template("$(format-json
foo=$FOO
bar=$BAR)\n"));
```
Earlier the embedded NL character was not recognized a separator between the name of the
template function and its arguments.
Also, this patch adds support for escaping the terminating NL character in the input text, making it possible to avoid the NL character in strings, even though they are included in the source text.
For instance:
```
http(headers("Authorization: \
basic abcdeffe"));
```
So even though there's a newline in the input text, it wouldn't be embedded in the resulting string. It's as if it wasn't even there. This convention is used in …
> Add support for whitespace in template fns

- lib/logthrdestdrv.c
I moved some `iv_validate_now` around, added a few `iv_invalidate_now`, but the main root cause was that the function that check if we need to flush expected strictly more time to pass than flush_timeout (> instead of  >=). Although when flush triggered by the timer, in some cases exactly flush_timeout passed, which resulted in skipping the flush and reregistering the same timer in the past, which resulted in an infinite loop.
For more detailed analysis, please check commit messages.
> logthrdestdrv infinite loop with ivykis prior 0.39

- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java
- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsFile.java
- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsOptions.java
- modules/java/native/java-destination.c
- scl/hdfs/plugin.conf
This patchset introduces the `time_reap` option for the `hdfs` destination. The user could simply set this option in seconds after that every file that has not been written since `time_reap` seconds is going to be closed.
(Note: In case of archive is configured it also triggers the archiving mechanism for that file only.)
```
hdfs( ... time_reap(60));
```
The option default value is `0`, which means disable the timeout.
The `java: option set/get key leaked` commit fixes a general java based option leak, every get/set option leaked per call.
Fixes #917
> Hdfs time-reap

- lib/filter/filter-call.c
- lib/filter/filter-expr.h
- lib/filter/filter-op.c
- lib/filter/filter-pipe.c
- lib/filter/filter-re.c
- lib/filter/tests/CMakeLists.txt
- lib/filter/tests/Makefile.am
- lib/filter/tests/test_filter_call.c
- lib/filter/tests/test_filters.c
The `filter` filter could refer to other filter, which is checked during the initialization time instead of configuration parse time. But at this point for some reason syslog-ng only reported as an error message:
`Referenced filter rule not found in filter() expression ...`
The syslog-ng should not start in this case, and this patch solves that.
> Undefined filter reference

- dbld/images/helpers/functions.sh
- dbld/images/required-apt/all.txt
Due to the missing unzip dependency, gradle could not be installed. Then dh_install failed because it missed some jar files. Then dpkg-buildpackage validation failed because not all packages were installed in the dh_install step.
I added the missing unzip dependency.
Also added set -e to functions.sh. Until now those functions could fail silently.
> dbld: fix dbld/rules deb failure

- lib/stats/stats-counter.h
The output of atomic_gssize_get_unsigned is gsize, and output of stats_counter_get is also gsize. Instead of gssize, declare result as gsize matches the unsigned type of the return value.
This fixes an alignment trap on ARMv5 when using with glib-2.56.x.
> Update data type to avoid conversion.

- lib/filter/filter-call.c
The following config would cause stack overflow because of recursive function call:
```
@version: 3.17
source s_inter { internal(); };
filter f { filter(f); };
log { source(s_inter); filter(f); };
```
Edit:
You should start `syslog-ng -F` (without enabling either of those switches: `-d -e -t -v`)
> filter: detect loop

- lib/filter/filter-call.c
In case of skip initialized the `visited` variable was not set back to `FALSE`, which would cause false loop detection if the same `filter` filter would be used twice.
> filter: multiple filter ref incorrect loop detection

- lib/cfg.c
- lib/cfg.h
- lib/control/control-commands.c
- syslog-ng-ctl/syslog-ng-ctl.c
Currently there is no way to tell what configuration syslog-ng has in effect.
Sure the file in the disk can be checked, and most of the time it would be save to assume the active config and the disk content are equal.
This gives an opportunity to both get the content of the top level configuration file and also the preprocessed configuration.
The way it could be queried via `syslog-ng-ctl`:
```
> syslog-ng-ctl 
Syntax: /tmp/install/sbin/syslog-ng-ctl <command> [options]
Possible commands are:
stats                Get syslog-ng statistics in CSV format
...
config               Print current config
```
This prints the top level configuration file:
```
> syslog-ng-ctl config
```
With an option `--preprocess` it prints the preprocessed version of the config:
```
> syslog-ng-ctl config …
```
> syslog-ng-ctl config to print pre-processed configuration

- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- modules/basicfuncs/urlencode.c
This patch adds a new template function: `url-decode`
url-decode can receive arbitrary number of parameters. When multiple parameters are added, each parameters are encoded separately, and simply concatenated.
Example:
```
$(url-decode $MESSAGE)
```
> basicfuncs: url-decode template function

- lib/compat/CMakeLists.txt
- lib/compat/Makefile.am
- lib/compat/un.h
- lib/gsockaddr.c
- lib/gsockaddr.h
It is not required on all platforms to add the size of the
terminating null character (+1) to the value of the `addrlen`
parameter during the `bind` system call. Most platforms has a
built in MACRO to calculate the proper value, called `SUN_LEN`.
SUN_LEN is **not** a POSIX standard, so we use the formula from
the Linux man page if it is not available.
Signed-off-by: Laszlo Szemere <laszlo.szemere@balabit.com>
> lib/gsockaddr.c: modify the unix salen calculation

- lib/logqueue.c
- lib/logqueue.h
- lib/logthrdestdrv.c
- lib/logthrdestdrv.h
- lib/logwriter.c
- lib/stats/stats-cluster.c
- lib/stats/stats-cluster.h
- lib/stats/stats-registry.c
- lib/stats/stats-registry.h
- lib/stats/tests/test_dynamic_ctr_reg.c
- lib/stats/tests/test_stats_cluster.c
- lib/tests/test_logthrdestdrv.c
- modules/afsql/afsql.c
- modules/afsql/afsql.h
Leak:
* start syslog-ng with a simple config
```
@version: 3.17
options {
time_reopen(5);
stats-level(3);
};
source s_file {
file("/tmp/input-logs.txt" log-iw-size(10));
};
destination d_file {
file("/tmp/output-logs.txt");
};
destination d_net {
network("localhost" port(5555) 
);
};
log {
source (s_file);
destination (d_net);
};
```
* reload syslog-ng
Each time a memory-usage counter is written into a variable that is dynamically allocated on the heap and not freeing up (on my machine 8 bytes are leaked for each reload).
> Fix memory leak caused by saving stats counter to persist config

- lib/template/compiler.c
- lib/template/function.h
- lib/template/simple-function.c
- lib/template/simple-function.h
- lib/template/templates.c
- lib/template/templates.h
- lib/template/tests/test_template.c
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/cond-funcs.c
- modules/basicfuncs/context-funcs.c
- modules/basicfuncs/numeric-funcs.c
- modules/basicfuncs/str-funcs.c
- modules/cryptofuncs/cryptofuncs.c
- modules/geoip/tfgeoip.c
- modules/geoip2/tfgeoip.c
- modules/stardate/stardate.c
This patch gets rid off the argument locking in template functions, thereby making the use of the same
template (with template functions) from multiple threads scale.
[Edit by Kokan]
This patch also limits the template function arguments to 64.
> templates: get rid off the args_lock

- modules/appmodel/app-parser-generator.c
Rationale:
* whenever we are sending structured data upstream, this name-value tag grabs the "kind" of application we parsed. This could be used as "sourcetype" in splunk. The same information is also available as a tag, however it is not easy to use that in an output template.
> app-parser: set ${.app.name} to the application identified

- lib/cfg-grammar.y
- lib/value-pairs/cmdline.c
- lib/value-pairs/tests/test_value_pairs.c
- lib/value-pairs/transforms.c
- lib/value-pairs/transforms.h
- lib/value-pairs/value-pairs.c
- modules/json/tests/test_format_json.c
This branch adds a couple of improvements to our value-pairs functionality:
1) adds support for --shift-levels key rewrite method, a bit similar to --shift, but instead of working with characters, it works with dot delimited "levels". --shift-levels 2 drops the prefix up to the second dot in the name of the key. e.g. .iptables.SRC becomes SRC (the initial dot is calculated too).
2) fixes a bug in type hint parsing, in case the hinted template expression contains parenthesis on its own. This is also related to #2286 where we actually make use of literal type hints in connection with $(format-json)
3) it adds a scope named "none" that resets the previously added scopes, making it possible to get rid of automatically added name-value pairs. This is not really changing functionality, however …
> Value pairs improvements

- lib/secret-storage/nondumpable-allocator.c
- modules/getent/getent-group.c
- modules/getent/getent-passwd.c
- modules/getent/getent-protocols.c
- modules/getent/getent-services.c
- tests/loggen/loggen.c
I was compiling syslog-ng on armv7l and I found some warnings, that I intend to fix now. (Probably glong->gint64 change is not arm specific.)
I wanted to add `-Wincompatible-pointer-types` to extra warnings, but 4.8 gcc and clang does not know that warning yet. Though with xenial gcc, I could compile without these warnings.
Besides these, there were  43 instances `warning: cast increases required alignment of target type [-Wcast-align]` that I do not fix for now.
> Fixing some compiler warnings from armv7l

- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- scl/telegram/telegram.conf
TLDR;
- `urlencode` removed. One needs to be used `url-encode`
- Telegram automatically encodes message. Users need not and should not do so anymore.
Both are API breaking changes, introduced not long ago, in 3.16. The earliest (3.18) we fix these, the best.
CC: @czanik the telegram blog will need to be updated.
---
When I introduced telegram and urlencode, the following usecase drove me:
I had a program source that fetches multiline notifications that I wanted to send to telegram. Since program sources do not work well with multiline, so an encoding must be used. Since telegram already needs urlencode, I was thinking that if I already receive messages urlencoded from the program source, then I can just simply pass these to telegram, that solves both the encoding requirement and the …
> telegram, urlencode: api changes

- modules/json/format-json.c
- modules/json/tests/test_format_json.c
This makes it possible to add snippets of literal values into the
json, without being represented as strings.
$(format-json bar=literal($(format-json --subkeys .foo.)))
> json: fix the literal() type hint

- lib/apphook.c
- lib/tests/CMakeLists.txt
- lib/tests/Makefile.am
- lib/tests/test_apphook.c
- modules/affile/affile-dest.c
The PR which introduced the `reopen` also changes the hook behavior optionally, so the user could register a hook that is not removed after it was triggered.
My issue with that solution that the code that triggered a hooks was responsible to decide if all of the triggered hooks should be removed, or kept.
While I think it would be more reasonable for the code that registers to decide if it want the registered hook to be triggered always or just once.
This PR makes all the hook one shoot again, and registers the `reopen` hook, when it was triggered.
> Revert sticky hook option

- lib/host-resolve.c
Pass AI_V4MAPPED | AI_ADDRCONFIG as hints to getaddrinfo() explicitly, which
allows ip-protocol(6) destinations to fall back to ipv4, should the
ipv6 stack not be available or if the server does not have an ipv6 address.
This would allow the user to use either ipv4 or ipv6, depending on the
ipv6 connectivity and the contents of DNS.
See getaddrinfo() manual page for more information.
> Allow ipv4 mapped addresses in ipv6 mode

- modules/syslogformat/syslog-parser-grammar.ym
- modules/syslogformat/syslog-parser.c
The following configuration was not accepted by:
```
parser  { syslog-parser(flags(check-hostname)); };
```
It was not accepted because the lexer has `KW_CHECK_HOSTNAME`, and the logic if something is a keyword or a string is looking up the keyword list. But the flags option expect it to be a string instead of a keyword, therefore the grammer fails.
> syslog-parser: fix unexpected flag check-hostname

- dbld/images/required-apt/xenial.txt
- dbld/images/required-epel/all.txt
- dbld/images/required-pip/xenial.txt
It's better to use them in the image by default instead of apt-get/pip install via kira in every time
> DBLD: Moved all kira deps to images

- modules/python/CMakeLists.txt
- modules/python/Makefile.am
- modules/python/compat/compat-python-v2.c
- modules/python/compat/compat-python-v3.c
- modules/python/compat/compat-python.h
- modules/python/python-dest.c
- modules/python/python-integerpointer.c
- modules/python/python-integerpointer.h
- modules/python/python-logmsg.c
- modules/python/python-logmsg.h
- modules/python/python-logtemplate-options.c
- modules/python/python-logtemplate-options.h
- modules/python/python-logtemplate.c
- modules/python/python-logtemplate.h
- modules/python/python-plugin.c
- modules/python/tests/CMakeLists.txt
- modules/python/tests/Makefile.am
- modules/python/tests/test_python_logmsg.c
- modules/python/tests/test_python_template.c
Fixes: https://github.com/balabit/syslog-ng/issues/2172
This patchset adds support for template formatting in python destination. All necessary parameters are exposed to the user code: LTZ_SEND, LTZ_LOCAL, sequence number, and LogTemplateOptions instance of the destination. This patchset does not support construction of LogTemplateOptions, nor their fields are exposed to the user, only that is generated by the grammar is available to the user. Though such functionality might be useful, and can be added later.
LTZ_SEND, LTZ_LOCAL is exposed in a newly created syslog-ng module. LogTemplateOptions and sequence number is exposed through self (the class, provided by the user).
Examples:
(Don't forget to add `import syslogng`)
* Creating a new LogTemplate object 
```
self.log_template = …
```
> python-destination: template support

- lib/logthrsource/logthrfetcherdrv.c
- lib/logthrsource/logthrfetcherdrv.h
- lib/logthrsource/logthrsourcedrv.c
Source implementations have to implement a funcionality called
"suspend".
This is usually achieved by calling free_to_send(). The source should
stop fetching messages when free_to_send() returns false.
The inverse of this operation is "wakeup", which is coming from the
destination thread, usually implemented using iv_event.
Since the suspend mechanism is based on polling, and wakeup is
event-based, it is possible that the source misses a
free->not_free->free oscillation. In such case, the corresponding wakeup
event must be ignored by the source to prevent an erroneous wakeup.
To ignore those wakeup events, an internal state (suspended flag) might
be enough.
Unfortunately, there is a rare occurrence of thread scheduling, when a
simple flag won't be enough:
0. start state: default IW size …
> logthrsource: fix wakeup

- modules/python/compat/compat-python.h
- modules/python/python-plugin.c
This changes the plugin description, so it includes the python main version (3/2 as of now).
The user could query which version was the python module compiled:
```
syslog-ng --module-registry
...
Module: mod-python
Status: ok
Version: 3.17.2
Core-Revision: 3.17
Description:
The python (python2) module provides Python scripted destination support for syslog-ng.
Plugins:
destination     python
root            python
parser          python
template-func   python
...
```
* Should it include also the minor/patch version of the python ?
Fixes #2336
> python: include python2/3 in plugin description

- lib/apphook.c
- lib/secret-storage/nondumpable-allocator.c
- lib/secret-storage/nondumpable-allocator.h
- lib/secret-storage/tests/test_secret_storage.c
This patchset fixes a problem, when syslog-ng password protected ssl keys with credential storage did not work, if the syslog-ng binary is compiled with centos6, but used on ubuntu precise.
syslog-ng uses MADV_DONTDUMP to avoid writing credentials store data into core dump. Though this feature is available only from kernel 3.4, centos6 team backported this feature with https://access.redhat.com/errata/RHBA-2013:0279.
As a result, if the binary is built with centos6, syslog-ng tries to uses this option. But ubuntu precise has older kernel version 3.2, which does not support this option, so madvise() will return with errno == EINVAL. In the end syslog-ng fails to initialize.
This patch checks if errno == EINVAL is received, and in that case a debug log is written about the case, otherwise …
> MADV_DONTDUMP and portability

- modules/afamqp/CMakeLists.txt
- modules/afamqp/Makefile.am
- modules/afamqp/afamqp-grammar.ym
- modules/afamqp/afamqp-parser.c
- modules/afamqp/afamqp-plugin.c
- modules/afamqp/afamqp.c
- modules/afamqp/afamqp.h
It makes possible to configure the `max_channel` and `frame_size` for amqp destination. Also relays on a default value supplied by rabbitmq project.
Fixes #2340
> amqp configurable max connection and frame size

- lib/gprocess.c
- lib/gprocess.h
- syslog-ng/main.c
If the syslog-ng was running on a system where `CAP_SYSLOG` is not present, it would print to the `stderr` unconditionally a message about fallbacking to `CAP_SYS_ADMIN`.
This prevent that log by default, and moves it into the debug level.
> Message about not supported cap_syslog only at debug level

- modules/afsocket/afinet-dest.c
Added missing libnet_destroy() to afinet.
Signed-off-by: Laszlo Szemere <laszlo.szemere@balabit.com>
> afinet_dest: add missing libnet_context destroy to afinet

- lib/cfg-grammar.y
- lib/logreader.h
- lib/logthrsource/logthrsourcedrv.c
- lib/logthrsource/logthrsourcedrv.h
- modules/examples/sources/threaded-diskq-source/threaded-diskq-source-grammar.ym
- modules/examples/sources/threaded-random-generator/threaded-random-generator-grammar.ym
- modules/python/CMakeLists.txt
- modules/python/Makefile.am
- modules/python/compat/compat-python-v2.c
- modules/python/compat/compat-python-v3.c
- modules/python/compat/compat-python.c
- modules/python/compat/compat-python.h
- modules/python/python-debugger.c
- modules/python/python-dest.c
- modules/python/python-fetcher.c
- modules/python/python-fetcher.h
- modules/python/python-grammar.ym
- modules/python/python-helpers.c
- modules/python/python-helpers.h
- modules/python/python-logmsg.c
- modules/python/python-parser.c
- modules/python/python-plugin.c
- modules/python/python-source.c
- modules/python/python-source.h
- modules/python/tests/CMakeLists.txt
- modules/python/tests/Makefile.am
- modules/python/tests/test_python_logmsg.c
Two types of Python source can be implemented:
- Python `LogSource`:
- You have 2 mandatory operations to implement, `run()` and `request_exit()`.
- You can implement your own event loop, or integrate an external framework's or library's event loop (Kafka consumer, HTTP server, Flask, Twisted engine, etc).
- You can post messages from `run()` using `LogSource::post_message()`.
- Python `LogFetcher`:
- Easier to implement, the event loop and the entire scheduling is done automatically by syslog-ng.
- You can use simple blocking server/client libraries to receive/fetch logs.
- The following operations can be implemented: `open()`, `close()` and `fetch()`.
- A custom Python source implementation must be inherited from `syslogng.LogSource`. Multiple inheritance is allowed, but only for pure …
> Python source

- lib/logthrdestdrv.c
- lib/logthrdestdrv.h
- lib/seqnum.h
- lib/tests/test_logthrdestdrv.c
- modules/afamqp/afamqp.c
- modules/afmongodb/afmongodb.c
- modules/afsmtp/afsmtp.c
- modules/afstomp/afstomp.c
- modules/http/http-grammar.ym
- modules/http/http-parser.c
- modules/http/http.c
- modules/http/http.h
- modules/java/native/java-destination.c
- modules/python/python-dest.c
- modules/redis/redis.c
- modules/riemann/riemann.c
This branch implements multithreaded http destination, that uses the specified number of worker threads to send messages to an upstream HTTP server.
This should drastically improve performance of HTTP based transports, especially if combined with #2289, #2287, #2286
> Http multi threading

- lib/cfg-lex.l
Fixes #2317 (details in the issue).
Also this fixes an other case
```
python {
#}
};
```
> python block skip string check in comments

- lib/control/control-commands.c
- lib/control/control-commands.h
- lib/control/tests/test_control_cmds.c
> Fix license cmd

- lib/logmsg/logmsg.c
- lib/logpipe.h
- lib/logproto/logproto-buffered-server.c
- lib/logproto/logproto-framed-server.c
- lib/transport/logtransport.c
I find the latest messages clutter up debug messages a lot, so move some of the less interesting ones
to msg_trace(), now that we have that.
> Move some messages to trace

- modules/basicfuncs/fname-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
> basicfuncs: fix $(basename) and $(dirname) in the presence of a prefix

- modules/diskq/logqueue-disk-non-reliable.c
- modules/diskq/logqueue-disk-reliable.c
- modules/diskq/logqueue-disk.c
- modules/diskq/logqueue-disk.h
- modules/diskq/qdisk.c
- modules/diskq/qdisk.h
- modules/diskq/tests/test_diskq.c
This patchset addreses the following problems:
For users:
- When diskqueue was read by dqtool cat, syslog-ng tried to truncate the file even though it was opened as readonly, hence an error message was emitted. The code is fixed that syslog-ng will not try to truncate with readonly mode
- Fixed the dumped variables in the error log that is emitted when a truncate was unsuccessful
- Removing a false positive corruption detection error log.
For developers
- When corruption was detected, the error message was missing the write_head variable that is important information from debugging point of view.
- qdisk_init contained a branching based on reliable-non-reliable queue, that I could eliminate (refactor)
- _load_state contained a large chunk of code that was responsible for loading the …
>  non-reliable diskq: fixing a false positive corruption detection

- dbld/rules
- this target is useful when we want to query actual
builder images from CI system
- introduced new BUILDER_IMAGES variable to store
OS images
- extend IMAGES variable with new BUILDER_IMAGES to
not broke old behavior
Signed-off-by: Micek <mitzkia@gmail.com>
> DBLD: Add new target "list-builder-images"

- dbld/images/helpers/dependencies.sh
- this repository is not needed for installing required devshell packages
Signed-off-by: Micek <mitzkia@gmail.com>
> DBLD: Remove "proposed" Ubuntu repository from enable_dbgsyms()

- modules/redis/redis.c
* The redis destination leaked the connection at every reconnect and/or reload.
* Removed the `reconnect` arg, that did not prevent reconnection (it is better to check if the connection is alive)
> Leak redis connection

- modules/afsql/afsql-grammar.ym
- modules/afsql/afsql-parser.c
- modules/afsql/afsql.c
- modules/afsql/afsql.h
This branch converts our afsql driver to use the LogThreadedDestDriver framework, instead of its home-grewn implementation (that has originally been the basis of LogThreadedDestDriver).
This should go in after #2315 because without that some of our stats counters would be missing.
> Afsql threaded dest driver

- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
- modules/afsocket/socket-options-inet.c
- modules/afsocket/socket-options-inet.h
There are some use cases, when the ip address for the interface isn't known,
or there are more ip addresses for one interface
Also, there are some HA architecture, where the master and standby is on the physical network,
The active's ip address is predefined, but when syslog-ng starts it doesn't know that it runs on the master or on the standby.
This patch helps to define the interface instead of ip addresses in these cases
Usage example: s_network{ tcp(port(6666) interface("wlp3s0")) };
Signed-off-by: Juhasz Viktor <juhasz.viktor81@gmail.com>
> AFSocket: Make it possible to set the interface for socket.

- dbld/images/helpers/packages.manifest
- it installs required xsl files
- handy when 'http://docbook.sourceforge.net' is unavailable
> DBLD: Add missing docbook-xsl packages

- modules/http/http.c
Reason:
* when ca-dir() is set but ca-file() is not, AND the default cert file
does not exist, syslog-ng cannot establish the SSL connection
(could be a typical problem when syslog-ng is built on a different distrib)
> http: when ca-file() is not set, unset CURLOPT_CAINFO

- lib/logthrdestdrv.c
There is an eventfd leak in logthrdestdrv, if syslog-ng is compiled with ivykis<=0.38. One eventfd is leaked per reload per threaded destination driver.
Config example:
```
@version: 3.18
log {
destination { http(); };
};
```
```
$ lsof -p `cat ../var/syslog-ng.pid`  | grep -F '[eventfd]'
[...]
syslog-ng 18861 furiel   13u  a_inode               0,13        0     12651 [eventfd]
syslog-ng 18861 furiel   15u  a_inode               0,13        0     12651 [eventfd]
syslog-ng 18861 furiel   16u  a_inode               0,13        0     12651 [eventfd]
syslog-ng 18861 furiel   17u  a_inode               0,13        0     12651 [eventfd]
(these lines continue to grow)
```
The root cause seems a pair of missing iv_unregister event, which is added in this patch.
I bisected the code of ivykis and …
> logthrdestdrv: fixing an eventfd leak with ivykis<=0.38

- lib/logthrdestdrv.c
The messages are ACKed by the `_process_result()` method.
UnACKed messages are move back to the queue to be sent by syslog-ng
later.
Problems the patch fixes in batching mode:
1) when a queue contains unsent items during a stop request, worker
threads are blocked until the batch timer not elapsed
2) when the queue contains items during reload (less then a `batch_lines`), then we perform a flush after the worker thread exits, but as the result was not processed, these messages are never ACKed, so they were moved back to the queue, and could be sent multiple times
> logthrdestdrv: process flush result after worker thread exits

- modules/http/http.c
when ca-dir() is not set, syslog-ng uses the default ca-dir, provided by
CURL (on my machine: /etc/ssl/certs)
> http: do not load certs from default CURL ca-dir

- modules/java-modules/build.gradle
The maven repository url for elasticsearch has changed. For historical reason I updated it first. However the central maven repository for gradle now contains the needed elasticsearch packages, so removed the unnecessary private repo url.
The attention was drew by this issue: #2390
> java-modules, elasticsearch: maven repository link has changed

- .travis.yml
- requirements.txt
- run pytest-fw related make targets from Travis CI
> pytest-fw to travis

- modules/affile/affile-dest.c
There was an invalid read in file destination after a file was
reaped. After reap, the AFFileDestWriter object is freed, but the
owner's lock was accessed through the freed pointer.
> affile: owner lock accessed from a reaped pointer

- modules/http/http-grammar.ym
- modules/http/http-parser.c
- modules/http/http.c
- modules/http/http.h
- scl/telegram/telegram.conf
PR #2410 breaks the Telegram destination.
This patch adds new option to HTTP destination (`enable-default-ca-dir`).
When defaults are enabled and the user does not set the `ca-dir` option,a default ca-dir is used, provided by the CURL library.
When both options are set (`ca-dir` and `enable-default-ca-dir`), of course, `ca-dir` will be used.
> Fix telegram dst default ca dir

- CMakeLists.txt
- Makefile.am
- lib/eventlog/CMakeLists.txt
- lib/eventlog/src/Makefile.am
- lib/eventlog/src/evt_internals.h
- lib/eventlog/src/evtlog.h
- lib/gprocess.h
- lib/logproto/tests/test-text-server.c
- lib/rewrite/tests/test_rewrite.c
- libtest/stopwatch.h
- libtest/testutils.c
- libtest/testutils.h
- modules/afmongodb/tests/test-mongodb-config.c
- modules/dbparser/pdb-load.c
- modules/dbparser/pdbtool/pdbtool.c
- modules/diskq/dqtool.c
- modules/diskq/tests/test_diskq.c
- modules/geoip2/maxminddb-helper.c
This PR fixes #1961.
-Wmissing-format-attribute is the alias for -Wsuggest-attribute=format.
This attribute can be added to any function, which has a format string in its arguments, and possibly additional variable arguments, intended to match with the format string.
When 'format' attribute is added, the compiler checks, whether the format string is valid, and the variable arguments match the format.
After enabling this flag, several functions were shown to be candidates for the format attribute.
As clang and gcc has different syntactic, I made macros for every module, which was affected, with different syntactic for the mentioned compilers.
I wanted to make only one macro, but I did not find the mutual source file for it.
After marking each candidate functions with 'format' attribute, …
> Adding build flag -Wmissing-format-attribute and -Wsuggest-attribute=noreturn

- modules/system-source/system-source.c
FreeBSD has started to use RFC5424 format between applications and syslogd
when using the syslog() API. Allow this use by enabling the syslog-protocol
flag.
> system-source: allow syslog-protocol on unix-dgram() sources

- lib/logsource.c
- lib/messages.c
- lib/messages.h
Problem: when internal source is enabled and trace level set, infinite message is generated in an exponential manner.
There are two independent root cause for this, both of these need to be addressed.
1)
There is a loop detection that was not working, because the order msg_set_context and the triggering messages were swapped. With that change, the `Source side message processing begin` messages are suppressed.
With that `internal() messages are looping back, preventing loop by ...` messages occur, so the detection kicks in, avoiding the infinite loop, but still causing minor inconvenience.
2)
There is a message about window size adjustment, that also triggers a message each time a message arrives into the internal queue. However, the loop detection does not work on this, and should not, …
> internal source + trace level causes message storm

- lib/tlscontext.c
- lib/tlscontext.h
- lib/transport/transport-factory-tls.c
- lib/transport/transport-factory-tls.h
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
- modules/afsocket/transport-mapper-inet.c
- modules/afsocket/transport-mapper-inet.h
Currently syslog-ng does not change the tls compression setting of tls transport. This means the default setting depends on the patch level and compile options of openssl. H̶o̶w̶e̶v̶e̶r̶ ̶t̶h̶e̶ ̶d̶e̶f̶a̶u̶l̶t̶ ̶c̶o̶m̶p̶r̶e̶s̶s̶i̶o̶n̶ ̶s̶e̶t̶t̶i̶n̶g̶ ̶s̶h̶o̶u̶l̶d̶ ̶b̶e̶ ̶d̶i̶s̶a̶b̶l̶e̶d̶ ̶b̶y̶ ̶d̶e̶f̶a̶u̶l̶t̶ ̶t̶o̶ ̶a̶v̶o̶i̶d̶ ̶C̶R̶I̶M̶E̶ ̶v̶u̶l̶n̶e̶r̶a̶b̶i̶l̶i̶t̶y̶.̶ Edit: syslog-ng is not vulnerable to CRIME.
T̶h̶i̶s̶ ̶p̶a̶t̶c̶h̶s̶e̶t̶ ̶e̶x̶p̶l̶i̶c̶i̶t̶e̶l̶y̶ ̶d̶i̶s̶a̶b̶l̶e̶s̶ ̶t̶l̶s̶ ̶c̶o̶m̶p̶r̶e̶s̶s̶i̶o̶n̶ ̶t̶o̶ ̶b̶e̶ ̶s̶u̶r̶e̶.̶
This patchset makes tls compression configurable, with disabled by default.
Note: allow-compress(yes) does not necessarily mean the session will be compressed. It only means endpoints are allowed to choose tls compression during negotiation. For example if …
> tls: disable ssl compression by default

- lib/logproto/logproto-framed-server.c
- lib/logproto/tests/test-framed-server.c
- modules/afsocket/afinet-dest.c
`LW_DETECT_EOF` closes the connection when input is received from a destination socket.
This is only acceptable for one-way protocols. TLS is duplex, so it has to be disabled both in TLS-based streaming and RFC 6587-framed protocols.
I've also fixed an incorrect RFC reference in logproto.
RFC 5428 is about SNMP, I think RFC 6587 is what we've actually implemented (`syslog()`).
https://tools.ietf.org/html/rfc5428
https://tools.ietf.org/html/rfc6587
Fixes #2328
> Fix frequent disconnects of syslog() with TLS

- lib/logreader.c
- lib/logwriter.c
- lib/mainloop-io-worker.c
- lib/mainloop-io-worker.h
- modules/systemd-journal/journal-reader.c
When reload/shutdown is triggered, syslog-ng waits for the ongoing jobs to finish. Specially, a MainLoopIOWorkerJob early returns without scheduling the ivykis task. The problem with the current implementation is that api users call `log_pipe_unref` in the `completion` callback, that is not called in this case, because the ivykis task is not scheduled at all.
To mitigate that, users can specify a destroy function that will be used to `unref` the user_data before returning. Practically the ownership of user_data is given to (shared between the pipe and) MainLoopIOWorkerJob.
Reproduction steps:
Starting the config below with -Fv (verbose is mandatory, must not use -e)
```
@version: 3.18
options{
time-reap(5);
};
destination d_java {
java( ... );
};
log {
source { …
```
> mainloop-worker-io: possible refcount leak during reload/shutdown

- modules/systemd-journal/systemd-journal-parser.h
replaced AFPROG_PARSER_H_INCLUDED by SYSTEMD_JOURNAL_PARSER_H_INCLUDED
> fix include guard in systemd-journal

- lib/cfg-lex.l
- lib/parse-number.c
- lib/parse-number.h
- lib/tests/test_parse_number.c
- modules/basicfuncs/list-funcs.c
- modules/basicfuncs/numeric-funcs.c
- modules/basicfuncs/str-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- modules/getent/getent-group.c
- modules/getent/getent-passwd.c
- modules/getent/getent-protocols.c
- modules/getent/getent-services.c
The #1679 enhanced number parsing, so in configuration a numbers formatted in hexadecimal (`0xFA`) and octal (`07`) could be also interpreted.
But sadly that also broke configuration that try to use `08` numbers like this (not valid octal, but seems like valid), and also in many cases the `010` is not expected to be actually `8`.
The following configuration was accepted by syslog-ng before that patch (3.13)
```
network(port(08));
```
But not after, it says configuration error `08` is not a number.
On the other hand the `$(binary)` function demands those above mentioned formats.
The final solution is:
* The grammar can detect hex, oct, dec; and if a number starts with `0` or `0x`, it must be in the expected format (oct, hex). The `08` is considered invalid in config.
* The template …
> Remove template hex, oct number parse in configuration

- configure.ac
"--with-docbook-dir" option changed to "--with-docbook"
In dbld and in travis the "--with-docbook=" option is used, which does not exist,
therefore we always use the online version.
At first it seems trivial to change travis, dbld, etc to use the actual option,
although the config option name is misleading.
According to `xsltproc` man page, it is a file uses as an XML STYLESHEET.
Therefore I've changed the configure option and not the users of the option.
> configure: fix "--with-docbook*" option usage

- modules/python/python-debugger.c
This PR fixes the macro completion feature of the interactive debugger.
----------
`syslognginternals.py` contains a line to override the Python-side
implementation with the C implementation:
`from _syslogngdbg import *`
This means that the C side has to be published under the `_syslogngdbg`
module.
The `macro.decode()` call is required to be compatible with Python 3.
> python-debugger: fix macro completion

- lib/cfg-block-generator.c
- lib/cfg-block-generator.h
- lib/cfg-lexer.c
The lexer didn't handle generators that were allocated dynamically for every invocation properly.
This patch adds reference counting for CfgBlockGenerators which makes the fix trivial. 
Note, this is not app-parser() related, this is a bug in the core, which app-parser() and potentially confgen triggers.
> Fix app-parser() per reload memory leak

- Mk/lex-rules.am
- configure.ac
Python executable is not a hard dependency, unless someone needs to generate/update the grammar files. This patch delays the error reporting of the missing python executable until that. This makes possible to build syslog-ng from release tarball on a linux distribution without python (like archlinux).
Example execution in an archlinux container:
The warning:
```
checking for python2.0... no
configure: WARNING: Python interpreter is missing.
checking for C compiler vendor... gnu
```
The error:
```
[root@a3ad2aaeba81 build]# touch ../modules/redis/redis-grammar.ym
[root@a3ad2aaeba81 build]# make
Makefile:21760: *** "Python interpreter is required to generate grammar files, but it was not detected during configure".  Stop.
```
Without the touch, make executes successfully:
``` …
```
> autotools: relaxing python dependency requirement 

- tests/loggen/loggen.c
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
Move the parameter count check into plugins.
This allow us to run plugin options which
doesn't need target and port port parameters.
Fixes #2239
> loggen: paramter handling

- .travis.yml
- requirements.txt
With version shipped travis we received:
```
make: *** [pytest-self-check] Error 1
Traceback (most recent call last):
File "/usr/lib/python2.7/runpy.py", line 162, in _run_module_as_main
"__main__", fname, loader, pkg_name)
File "/usr/lib/python2.7/runpy.py", line 72, in _run_code
exec code in run_globals
File "/home/travis/.local/lib/python2.7/site-packages/pytest.py", line 14, in <module>
from _pytest.fixtures import fillfixtures as _fillfuncargs
File "/home/travis/.local/lib/python2.7/site-packages/_pytest/fixtures.py", line 1055, in <module>
@fixture(scope="session")
File "/home/travis/.local/lib/python2.7/site-packages/_pytest/fixtures.py", line 981, in __call__
function = wrap_function_to_error_out_if_called_directly(function, self)
File …
```
> pytest-framework: fix travis failure

- doc/man/syslog-ng.8.xml
Signed-off-by: Laszlo Boszormenyi (GCS) <gcs@debian.org>
> syslog-ng.8.xml: remove unneeded default-modules section

- lib/cfg-parser.c
I would like to write a [flycheck](https://www.flycheck.org/en/latest/) module for syntax checking syslog-ng configuration. For that, I need to find the offending line along with the error message from the output of syslog-ng -s.
The current syntax check printout looks awesome and helps users visually detect the problem quickly. But to find the problem algorithmically it is a little challenging because the error position does not occur explicitely, only implicitely (for example: to find first line number, one needs to look for an arrow). 
```
Error parsing log statement, syntax error, unexpected KW_DESTINATION, expecting ';' in ../etc/tmp.conf:
1       @version: 3.18
2       
3       log {
4         source { stdin(flags(no-parse)); };
5         parser {}
6----->   destination { …
```
> cfg-parser: printing error positions in case of parse failure

- tests/pytest_framework/conftest.py
- tests/pytest_framework/src/setup/testcase.py
- tests/pytest_framework/src/setup/testcase_parameters.py
- tests/pytest_framework/src/setup/tests/test_testcase_parameters.py
- tests/pytest_framework/src/setup/unit_testcase.py
- tests/pytest_framework/src/syslog_ng/console_log_reader.py
- tests/pytest_framework/src/syslog_ng/syslog_ng.py
- tests/pytest_framework/src/syslog_ng/syslog_ng_cli.py
- tests/pytest_framework/src/syslog_ng/syslog_ng_executor.py
- tests/pytest_framework/src/syslog_ng/syslog_ng_paths.py
- tests/pytest_framework/src/syslog_ng/tests/test_syslog_ng_paths.py
This patch set extends SyslogNgCli with core file detection and with --run-with-valgrind fixture.
The --run-with-valgrind fixture enables to run syslog-ng in any functional test behind valgrind. 
In this case on syslog-ng stop in handle_valgrind_log() we can assert on any unexpected behaviour (invalid read).
> PytestPART3: SyslogNgCli updates

- tests/pytest_framework/src/logger/logger.py
- tests/pytest_framework/src/setup/unit_testcase.py
- eliminate duplicated variables and typos
- fix multiple registering of temporary files
- remove closing of PosixPath type of files
> Pytest: Added minor fixes to unittest

- .astylerc
- lib/compat/strcasestr.c
This patch removes the old strcasestr() implementation and replaces it
with the one in NetBSD, which uses the 3 clause BSD license.
> lib/compat: replace strcasestr() implementation

- contrib/systemd/syslog-ng@default
When the pid file location was changed via `--with-pidfile-dir=` control socket was still pointing to `/var/lib/syslog-ng` even if they are using same path definition.
> syslog-ng@default: use pid file location on control socket

- tests/pytest_framework/functional_tests/config_change/test_manipulating_config_between_reload.py
- tests/pytest_framework/functional_tests/logpath/test_flags_catch_all.py
- tests/pytest_framework/functional_tests/logpath/test_flags_fallback.py
- tests/pytest_framework/functional_tests/logpath/test_flags_final.py
- tests/pytest_framework/functional_tests/logpath/test_multiple_embedded_logpaths.py
- tests/pytest_framework/functional_tests/logpath/test_multiple_flags.py
- tests/pytest_framework/functional_tests/source_drivers/file_source/test_acceptance.py
- tests/pytest_framework/src/syslog_ng_config/renderer.py
- tests/pytest_framework/src/syslog_ng_config/statement_group.py
- tests/pytest_framework/src/syslog_ng_config/statements/destinations/destination_driver.py
- tests/pytest_framework/src/syslog_ng_config/statements/filters/filter.py
- tests/pytest_framework/src/syslog_ng_config/statements/logpath/logpath.py
- tests/pytest_framework/src/syslog_ng_config/statements/sources/source_driver.py
- tests/pytest_framework/src/syslog_ng_config/syslog_ng_config.py
There is a little repetitive process in test writing in pytest framework: each driver (for example `FileSource`) must be encapsulated into a `StatementGroup` (for example `source`), prior constructing `LogPath`. If the group is not needed otherwise (one does not want to have multiple drivers in the same group, or update group on the fly), the explicit construction of the intermediate `StatementGroup` is unnecessary.
This patchset features logpath creation without explicitely creating these statement groups.
Note to developers:
I like the idea of having the same api for the group/non-group based construction in `config.create_logpath`, which means the function should branch somehow on the parameter type, that's why I think the `isinstance` part in the last patch is reasonable. At least I …
> pytest_framework: support for implicit groups in config.create_logpath

- lib/filter/filter-re.c
The regex evaluation can change the message itself, by adding
values to its NVTable.
The change can result in reallocating the message's NVTable, if
there is insufficient space for the newly added value.
We do not want this to happen, because we are pointing to a value
of it.
When we reference the NVTable, if it needs more space, it will be
copied, instead of being moved. After we are done using it, we can
unref it, which will result in freeing it, if it was copied during
the evaluation, so memory will not be leaked.
Fixes #2470.
> filter-re: ref/unref NVTable around regex eval

- tests/pytest_framework/src/common/blocking.py
- tests/pytest_framework/src/common/tests/test_blocking.py
- tests/pytest_framework/src/message_reader/message_reader.py
- tests/pytest_framework/src/message_reader/tests/test_message_reader.py
Prior this patch, pytest_framework did not support specifying timeout
as parameter for `wait_until_true`. Instead, a global variable was
responsible for the timeout. The default timeout (10s) was good for
the functional tests, but not for the unit tests, which executed
properly but unnecessarily long. For unit tests this global variable
was changed to 0.1s, which is too small for the functional
tests. Consequently, unit tests and functional tests cannot not be
executed together.
This patch adds timeout parameter for `wait_until_true`, and set the
proper timeout locally for unit tests. Hence unit tests and e2e test
can be executed together.
For example:
```
python3 -m pytest --installdir ../root/ tests/pytest_framework/src tests/pytest_framework/functional_tests
```
The way of …
> pytest_framework: timeout parameter for wait_until_true

- tests/pytest_framework/src/syslog_ng/syslog_ng_cli.py
- tests/pytest_framework/src/syslog_ng_ctl/syslog_ng_ctl.py
- tests/pytest_framework/src/syslog_ng_ctl/syslog_ng_ctl_cli.py
Prior this patchet, the syslog-ng start validation was the following: we relied on `syslog-ng -s` to detect if syslog-ng can be started. After that it waited for the control socket with a 10s timeout. However, when the configuration passes `syslog-ng -s`, the control socket may or may not be created, if there are other kind of errors in configuration that `syslog-ng -s` does not detect. That introduces a 10s delay for detecting failure in those cases.
For that sake, this patch checks if syslog-ng exited unexpectedly besides the control socket check.
This patch also eliminates the `class SyslogNgCtl` (or `/SyslogNgCtlCli`, depending on point of view).
Edit: We decided not to eliminate `SyslogNgCtl` here.
> pytest_framework: faster failure detection for semantically invalid configs

- modules/python/CMakeLists.txt
- modules/python/Makefile.am
- modules/python/python-logger.c
- modules/python/python-logger.h
- modules/python/python-plugin.c
Introduces a logger that can send messages into the `internal()` source, which also respects the syslog-ng log level.
```python
import syslogng
logger = syslogng.Logger()
logger.error("plain text message")
logger.warning("plain text message")
logger.info("plain text message")
logger.debug("plain text message")
logger.trace("plain text message")
```
Question:
* Could syslogng utilize the built-in `logger` class by extending it (creating only a handler for internal source) ?
* Does the apsense of `evt_tag_*` formatting cause significant performance issue? Should it be solved ?
Fixes #1375
> python: internal() source exposed via syslogng.Logger

- lib/logproto/logproto-client.c
- lib/logproto/logproto-client.h
- lib/logproto/logproto-text-client.c
- lib/logreader.c
- lib/logwriter.c
- lib/mainloop-io-worker.c
- lib/mainloop-io-worker.h
- modules/afsocket/afsocket-dest.c
- modules/afsocket/afsocket-dest.h
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
- modules/systemd-journal/journal-reader.c
As discussed, it might be better to give clean `process_in()` function from `LogProtoClient` as currently `flush()` does both directions, which complicates the communication between `LogWriter` and `LogProtoClient`.
This cleanup would make it easier to do `ProtoClient` level I/O communications (handshake, result handling, etc...), and it would make cleaner code in `Proto` and `LogWriter` level.
I also implemented a use of this process_in() function. LogProtoTextClient can drop input, if it is set from the config by `close-on-input` option, in case of AFSocket based destinations.
This can help to continue the PR #1433.
> ProtoClient: provide process_in function to logwriter

- tests/pytest_framework/src/message_reader/message_reader.py
- tests/pytest_framework/src/message_reader/tests/test_message_reader.py
- tests/pytest_framework/src/syslog_ng/console_log_reader.py
Due to invalid state handling in MessageReader buffer and parsing, it was possible not to get all messages if the same reader is used second time.
To trigger, such a read method is needed that fetches data in blocks. In that sense, there is no triggerable bug in the current version of the framework, because the only supported read method is the file read, which reads until eof.
This patch eliminates the state itself, and covers the case with a unittest.
> pytest_framework: invalid state with read all messages

- lib/logthrdestdrv.c
- lib/logthrdestdrv.h
A negative number's modulo will be negative, which in our case pointed to a negative entry of the workers array, causing segfault.
Fixes #2466.
> threaded-dest: Fix integer overflow

- lib/logthrdestdrv.c
- lib/logthrdestdrv.h
- lib/tests/test_logthrdestdrv.c
- modules/afamqp/afamqp.c
- modules/afmongodb/afmongodb.c
- modules/afsmtp/afsmtp.c
- modules/afsql/afsql.c
- modules/afstomp/afstomp.c
- modules/http/http-worker.c
- modules/http/http-worker.h
- modules/http/tests/test_http.c
- modules/java-modules/dummy/src/main/java/org/syslog_ng/DummyTextDestination.java
- modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/ElasticSearchDestination.java
- modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/ElasticSearchDestination.java
- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java
- modules/java-modules/http/src/main/java/org/syslog_ng/http/HTTPDestination.java
- modules/java-modules/kafka/src/main/java/org/syslog_ng/KafkaDestination.java
- modules/java/native/java-destination.c
- modules/java/src/main/java/org/syslog_ng/DummyStructuredDestination.java
- modules/java/src/main/java/org/syslog_ng/DummyTextDestination.java
- modules/java/src/main/java/org/syslog_ng/LogDestination.java
- modules/java/src/main/java/org/syslog_ng/StructuredLogDestination.java
- modules/java/src/main/java/org/syslog_ng/TextLogDestination.java
- modules/python/python-dest.c
- modules/python/sngexample.py
- modules/redis/redis.c
- modules/riemann/riemann-worker.c
I got a valuable comment from @pzoleex that the recently introduced constant names in java and python destinations could be more user friendly.
In an attempt to do so, I did a little renaming on them. Also, the python example is updated.
I also removed the `WORKER_INSERT_RESULT_EXPLICIT_ACK_MGMT`, that could not be used by the bindings this time of writing.
Please review this with in mind that we conclude here, that would be published in the documentation.
> simpler names for WORKER_INSERT_RESULT_T in language bindings

- tests/pytest_framework/conftest.py
- tests/pytest_framework/src/setup/testcase.py
- tests/pytest_framework/src/syslog_ng/syslog_ng.py
- tests/pytest_framework/src/syslog_ng/syslog_ng_cli.py
- tests/pytest_framework/src/syslog_ng_config/renderer.py
- tests/pytest_framework/src/syslog_ng_config/statements/destinations/file_destination.py
- tests/pytest_framework/src/syslog_ng_config/statements/sources/file_source.py
- tests/pytest_framework/src/syslog_ng_config/syslog_ng_config.py
This patchset starts off by making `SyslogNgConfig` independently deployable from `SyslogNg`.
Until now, they depended on a common `SyslogNgPaths` instance, so these two needed to be created at the same time. Thats why the `__registered_instances` database was introduced originally, so that either one is created, the other one is created too, and cached in case it will be queried later. This had the benefit that users do not need to know about the hidden dependency, they could just create a new config, then a syslog_ng instance, without explicitely linking the two together.
After looking into the nature of the dependency, it turned out `SyslogNgConfig` needed only the current `working_directory` from `SyslogNgPaths`, which could be also queried from the testcase parameters. It also needed …
> pytest_framework: eliminating __registered_instances, exposing SyslogNgCtl to user api

- modules/riemann/riemann-grammar.ym
Setting the values of riemann driver calls `log_template_ref`, which must be unref'd after (in the ym file).
Previously it was not unref'd, which caused memory leak every reload, because at `riemann_dd_free()`, the ref counters were 2.
I have seen this behavior in other drivers, too:
afsmtp, http, msg-generator
> riemann: fix ref/unref-ing templates

- tests/collect-cov.sh
Our devshell image is bionic based so make sure our coverage targets
work with the version of lcov that is on bionic.
lcov seems to be changing configuration options quite frequently, but
I think it is enough to work in devshell.
> collect-cov.sh: make coverage should work with lcov in bionic

- modules/riemann/riemann-worker.c
When Riemann receive a message, it sends an acknowledgements to the sending process when the connexion is over TCP (TCP or TLS mode of operation).  Not reading this acknowledgement make these messages fill-in the Recv-Q on the system running syslog-ng.
The `riemann_communicate()` function of riemann-c-client is a wrapper around `riemann_client_send_message_oneshot()` that also reads this acknowledgement if it exist, or mocks it when using UDP.
This patch change the riemann module to rely on `riemann_communicate()` to send events and avoid filling-in the Recv-Q.  Because the function returns a more granular `riemann_message_t`, update the trace message to include these details, and adjust the error detection code accordingly.
Fixes #2521
> Read acknowledgements send by Riemann

- persist-tool/Makefile.am
`persist-tool` was linked to `TEST_LDADD`, which contains `criterion`. This caused problem during deb package generation on debian jessie: the dpkg-buildpackage framework picked criterion as deb package dependency automatically. As a consequence, the resulting deb package could not be installed due to missing criterion package.
Replacing `TEST_LDADD` with the usual dependencies solves the problem.
> persist-tool: remove criterion as dependency

- libtest/Makefile.am
We need this to be able to include the header externally.
> libtest: Adding stopwatch.h into libtest_HEADERS list

- modules/java-modules/common/src/main/java/org/syslog_ng/options/TemplateOption.java
- modules/java/native/java-grammar.ym
- modules/java/proxies/java-template-proxy.c
Fixes: https://github.com/balabit/syslog-ng/issues/1870
As reported in #1870, elasticsearch destination does not support named templates. We concluded in that thread that there is no plan to support for it.
This patchset adds error detection in case someone tries to use named templates, so that the problem does not go undetected.
I added similar detection for java destination too. Interestingly, elasticsearch2 destination did not use the template grammar from java destination, so different implementation was needed there.
The motivation is that we would like to promote `@define` keyword instead of named templates.
> java, elasticsearch2, explicit unsupport for named templates

- lib/cfg-lexer.c
- lib/tests/test_lexer.c
The following is an accepted configuration befor the patch:
```
@version: 3.19
include "scl.conf";
```
Therefore there are the `@include ""` and the one `include "";`.
This patch removes the second include as not used, nor documented.
Signed-off-by: László Várady <laszlo.varady93@gmail.com>
Signed-off-by: Kokan <kokaipeter@gmail.com>
> grammar: remove the pragma less include

- libtest/queue_utils_lib.c
- libtest/queue_utils_lib.h
- modules/diskq/tests/Makefile.am
- modules/diskq/tests/test_diskq.c
- modules/diskq/tests/test_diskq_full.c
- tests/unit/test_logqueue.c
While I checked the disk queue related tests, I had some time to kill so I thought this changes improve the code.
Now the queue util based functions do not depend on `syslogformat` module.
> simplify libtest queue utils

- packaging/debian/syslog-ng-core.install
- scl/CMakeLists.txt
- scl/Makefile.am
- scl/netskope/plugin.conf
> scl: add parser for netskope logs

- lib/block-ref-parser.c
- lib/cfg-block-generator.c
- lib/cfg-block-generator.h
- lib/cfg-block.c
- lib/cfg-lexer.c
- lib/plugin.c
- lib/tests/test_lexer.c
- modules/appmodel/app-parser-generator.c
- modules/appmodel/appmodel-plugin.c
- modules/confgen/confgen-plugin.c
- modules/system-source/system-source.c
This is just an internal refactor, no user visible change.
The `generator` plugins could have parameters such as `system-source( foo(bar) )`. Every `generator` plugin had one grammar/parser that could handle any kind of key-value pair. (such as `foo(bar)`).
This has a few limitation:
* user has to create his own parsing logic inside a c logic, instead of a grammar; which could lead into nice error messages.
* the current grammar/parser is more limited than the grammar that user could provide
This PR brings two change:
* generator plugin could have its own grammar
* it is required from the generator's parser to support `cleanup` function, which should clean after itself (same as for other plugins).
> Own grammar support in generator plugin

- lib/mainloop-worker.c
- lib/mainloop.c
If a new configuration turns out to be invalid (I mean init()-time validation) during reload, the old one has to be restored.
In such case, the new configuration is in a half-initialized state, so it needs to be deinitialized. This must include a step called `main_loop_worker_sync_call()`, where worker threads are requested and waited to be stopped.
> Fix threaded source/destination crash when reverting configuration

- modules/java/src/main/java/org/syslog_ng/LogDestination.java
- modules/python/python-dest.c
- modules/python/sngexample.py
A new possible value added to python, java (as the C lib already has it): `RETRY`.
> python, java destination add already introduced retry

- packaging/rhel/syslog-ng.spec
rpm-packaging: add persist-tool to file list
Update syslog-ng.spec by adding persist-tool to file list.
Fixes https://github.com/balabit/syslog-ng/issues/2560
I just learned from @fekete-robert that I can send a PR without using git :)
> add persist-tool to file list

- modules/examples/sources/msg-generator/msg-generator-grammar.ym
- modules/examples/sources/msg-generator/msg-generator-parser.c
- modules/examples/sources/msg-generator/msg-generator-source-options.h
- modules/examples/sources/msg-generator/msg-generator-source.c
In this patch I added two changes to `example-msg-generator`. With these changes, `example-msg-generator` can be used for testing purposes easier.
- First message is sent immediately: we do not need to wait `freq`. With this, the tests can speed up.
- With the new `num` option, users can limit how many messages should be generated. Zero means infinite messages (this is the default). Positive integer means the maximum number of messages.
Example:
```
source { example-msg-generator(freq(1) num(5)); };
```
> improvements in example-msg-generator

- libtest/queue_utils_lib.c
- libtest/queue_utils_lib.h
- modules/diskq/logqueue-disk-non-reliable.c
- modules/diskq/logqueue-disk-reliable.c
- modules/diskq/logqueue-disk.c
- modules/diskq/qdisk.c
- modules/diskq/qdisk.h
- modules/diskq/tests/CMakeLists.txt
- modules/diskq/tests/Makefile.am
- modules/diskq/tests/test_diskq_truncate.c
On loading exiting disk-queues it was possible that a disk-queue only
contained saved memory queues (e.g. qout, qbacklog) and the disk-buf-size part was empty.
Due to the faulty logic of truncate on load, we could have empty disk-queues with possibly big sizes.
Also, the truncating logic assumed that qout will be the lowest offset among the saved
memory queues, however it is possible that only qbacklog is saved to the disk, which
resulted into a huge, empty disk-queue file.
> Fix non-reliable disk-queue truncating problem on load

- lib/scanner/xml-scanner/tests/test_xml_scanner.c
- lib/scanner/xml-scanner/xml-scanner.c
- modules/geoip2/geoip-parser.c
- modules/geoip2/tests/test_geoip_parser.c
- modules/xml/tests/test_xml_parser.c
- modules/xml/xml.c
Until now, prefix for these parsers were mandatory: it was either the default prefix, or a user-defined.
After this PR, it is possible to set an empty prefix for geoip2 and xml parsers.
```
xml(prefix(""));
geoip2(prefix(""));
```
The resulting nv-pairs would be created without a prefix:
```
name1 = value1
name2 = value2
```
> xml/geoip2: make prefix optional

- .lgtm.yml
- .lgtm/cpp-queries/call-to-gmtime-without-lock.ql
Here's an example of how to use LGTM's custom queries after a discussion here: https://discuss.lgtm.com/t/suppressions-in-c-code/1525/10
If you like the custom query: feel free to merge this so it's automatically run by LGTM.com. If you'd rather not have a custom query: feel fee to close this PR.
> Custom LGTM.com query for detecting uses of gmtime that are not covered by a lock

- CMakeLists.txt
- cmake/add_tests.cmake
This make it possible to configure with a simple option (`sanitizer`) in case of cmake to use the clang address (or any other sanitizer).
https://clang.llvm.org/docs/AddressSanitizer.html
It is connected to the #2178 issue, which has a connected branch with memory issue fixes. I do rebase the current master from time to time, and since the last time (end of December) I got a lot more test failing, so I though I share a simple way to deploy it for others (and make my life easier not to switch, rebase branch).
This is cmake only, as I won't touch autotools before every unit tests passed.
What you actually need to set this up is: clang, cmake an example can be found on the original branch: https://github.com/Kokan/syslog-ng/blob/address-sanatize/.travis.yml#L157
> Cmake clang sanitizer

- tests/python_functional/functional_tests/config_change/test_manipulating_config_between_reload.py
- tests/python_functional/functional_tests/source_drivers/generator_source/test_generator_source.py
- tests/python_functional/src/message_reader/single_line_parser.py
- tests/python_functional/src/message_reader/tests/test_single_line_parser.py
- tests/python_functional/src/syslog_ng_config/renderer.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/destination_driver.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/file_destination.py
- tests/python_functional/src/syslog_ng_config/statements/filters/filter.py
- tests/python_functional/src/syslog_ng_config/statements/sources/file_source.py
- tests/python_functional/src/syslog_ng_config/statements/sources/source_driver.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
This patchset adds initial support for `example-msg-generator` in the light test framework.
For now, only template can be specified. In a followup patch, I plan to support specific message list that is emitted by the generator.
I needed to do a small refactor on the code: prior this patch positional parameters were mandatory in drivers, that I needed to eliminate. 
The patchset contains a minor fix in the `SingleLineParser` code in the test framework.
> light: example-msg-generator support

- lib/template/tests/CMakeLists.txt
- lib/template/tests/test_template_on_error.c
> test_template_on_error: rewrite test cases in criterion

- lib/cfg-lex.l
This patch attempts to resolve #2568 by patching the input stream before the lexer/grammar processes it. This will also open up further avenues to patch the configuration file so that old constructs can be removed from the grammar.
> Add warning on old style include statement

- .travis.yml
- configure.ac
- dbld/images/helpers/packages.manifest
- lib/Makefile.am
Note:
`json-c` has a dist hook, where `doxygen` is used unconditionally:
https://github.com/json-c/json-c/blob/3e81b4abe359c8128bb2b4127f4e8c8c057fb004/Makefile.am#L8-L11
This means `doxygen` has to be installed in order to generate the tarball.
Questions:
- I don't think it is acceptable to depend on `doxygen`. Shouldn't we try to contribute and make it conditional in `json-c`?
Fixes #1204
> Include json-c in the dist tarball

- lib/value-pairs/cmdline.c
- lib/value-pairs/value-pairs.c
- lib/value-pairs/value-pairs.h
- libtest/cr_template.c
- modules/json/tests/test_format_json.c
This new option will allow a template function to skip name-value pairs
that are empty. This used to be the default behavior until unset() was
introduced, since which time we only omit unset name-value pairs.
For example, ElasticSearch needs a transaction description as a JSON
before each record, that can be generated like this:
$(format-json --omit-empty-values index._type=`type` index._index=`index` index._id=`custom_id`)
If $(format-json) would include index._id as an empty string, that would
invalidate the JSON in the eyes of ElasticSearch.
> value-pairs: add an --omit-empty-values option

- lib/value-pairs/CMakeLists.txt
- lib/value-pairs/Makefile.am
- lib/value-pairs/cmdline.c
- lib/value-pairs/internals.h
- lib/value-pairs/value-pairs.c
- lib/value-pairs/value-pairs.h
To make the ValuePairs struct opaque to users, move its definition to
a private header, so that cmdline.c can have access, but still the
rest of the codebase can't.
> value-pairs: move ValuePairs struct declaration to a private header

- lib/stats/tests/test_stats_query.c
This test bug was caught by our macOS Travis job.
The ordering of `stats_query_get()` is undefined, its implementation is based on a hash table.
In case of multiple matching counters, the test case had to be fixed by checking the existence of each counter in an unordered manner.
> test-stats-query: fix unit test

- lib/template/tests/CMakeLists.txt
- lib/template/tests/test_template_compile.c
> test_template_compile: rewrite test cases in criterion

- lib/logthrdestdrv.c
After an invalid configuration is reverted, the `under_termination` flag of the previous driver remained `TRUE`. This results in an inoperable state.
> Fix config revert (threaded destinations)

- lib/timeutils/wallclocktime.c
`Passing 'char **' to parameter of type 'const char **' discards qualifiers in nested pointer types.`
char** can not be converted to const char** implicitly.
This is one of my favorite "riddles" in C, I'm quoting the explanation from [21st Century C](http://shop.oreilly.com/product/0636920033677.do):
> Fix timeutils warning

- lib/cfg-lex.l
This PR
- fixes a buffer overrun
- completes the compatibility by removing the last semicolon
- refactors `patch_include_statement()` to use `strspn`
Please note that multiple statements within one line containing the old include statement won't work anymore (it worked before merging #2550), for example:
```
include "test.conf"; log {};
log {}; include "test.conf";
```
Or multiline include:
```
include
"test.conf"
;
```
> Fix old style include statement compatibility

- .travis.yml
- cmake/Modules/ExternalIVYKIS.cmake
- configure.ac
- lib/CMakeLists.txt
- lib/value-pairs/internals.h
Enables a switch to force GNU99 as the current used C standard is C99.
In case of CMake the GNU99 was already enabled, but warnings were excluded with `-isystem` style include.
> Force C99 with GNU

- scl/elasticsearch/elastic-http.conf
This destination is based on the native http destination of syslog-ng
and uses elasticsearch bulk api (https://www.elastic.co/guide/en/elasticsearch/reference/6.5/docs-bulk.html)
Example:
destination d_elasticsearch_http {
elasticsearch-http(index("my_index")
type("my_type")
url("http://my_elastic_server:9200/_bulk"));
};
Signed-off-by: Zoltan Pallagi <pzoleex@gmail.com>
> Added elasticsearch-http() destination

- lib/str-repr/tests/CMakeLists.txt
- lib/str-repr/tests/test_encode.c
> test_encode: rewrite test cases in criterion

- lib/logmsg/tests/CMakeLists.txt
- lib/logmsg/tests/test_timestamp_serialize.c
> test_timestamp_serialize: rewrite test cases in criterion

- modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/ElasticSearchDestination.java
After https://github.com/balabit/syslog-ng/pull/2509 was merged, the elasticsearch-http() destination should be the recommended destination to forward logs to elasticsearch.
> elasticsearch2: Added deprecation warning

- modules/afamqp/afamqp-grammar.ym
- modules/afamqp/afamqp-parser.c
- modules/afamqp/afamqp.c
- modules/afamqp/afamqp.h
AMQP has support for an 'external' authentication scheme which uses some out-of-band method for authenticating the user. For instance, the user may be identified from the Distinguished Name or Common Name in their client certificate. The method by which the user is identified when using external authentication depends on the server configuration.
Add a new 'auth-method' parameter to the amqp destination configuration which may be set to 'plain' or 'external'. When this parameter is omitted or set to 'plain', the existing behaviour is unchanged. When set to 'external' then external authentication is enabled and the username, if supplied, will be used as the identity, although this is generally not needed and may be omitted.
> afamqp: add support for external authentication

- modules/afamqp/afamqp-parser.c
- modules/afsql/afsql-parser.c
- modules/afstomp/afstomp-parser.c
`log-fifo-size()` comes from the main grammar, from the
`dest_driver_option` and `threaded_dest_driver_option` nonterminal symbols.
> Remove duplicate log-fifo-size() keywords

- contrib/systemd/syslog-ng@default
syslog-ng has multiple configuration files (syslog-ng.conf, scl.conf,
patterndb.d), so they are usually installed under the /etc/syslog-ng
directory.
Signed-off-by: Janos SZIGETVARI
Signed-off-by: László Várady
> contrib: fix default config file location (systemd)

- .travis.yml
- configure.ac
- dbld/rules
- dbld/tarball
- with the hardcoded docbook-path syslog-ng can not find docbook.xsl on
CentOS systems and `make install` will fail
- on this systems docbook.xsl has different installation dir
With this change `configure` can use always the proper docbook.xsl path.
To reproduce the fail, run:
```
$ dbld/rules bootstrap-centos-7 ; export DEFAULT_IMAGE=centos-7 ; dbld/rules make-install
```
docbook.xsl path in supported DBLD images
```
$ declare -a images=("balabit/syslog-ng-debian-buster" "balabit/syslog-ng-debian-stretch" "balabit/syslog-ng-debian-jessie" "balabit/syslog-ng-centos-6" "balabit/syslog-ng-centos-7" "balabit/syslog-ng-ubuntu-trusty" "balabit/syslog-ng-ubuntu-xenial" "balabit/syslog-ng-ubuntu-cosmic" "balabit/syslog-ng-ubuntu-bionic") ; …
```
> Docbook: Search for docbook.xsl in configure

- configure.ac
This partially reverts commit 419b4a5ca8aeab117b43ea30948669b4192fd6a1.
As I mentioned it in #2634:
`AC_ARG_WITH` has only 4 parameters, this is incorrect.
The configure now fails with manpages enabled (using autoconf 2.69 and automake 1.16.1):
```
config.status: error: Something went wrong bootstrapping makefile fragments
for automatic dependency tracking.  Try re-running configure with the
'--disable-dependency-tracking' option to at least be able to build
the package (albeit without support for automatic dependency tracking).
```
In addition, the output of `find /usr/share/{xml,sgml} -path '*/manpages/docbook.xsl'` is not one line for me:
```
/usr/share/xml/docbook/xsl-stylesheets-1.79.2-nons/manpages/docbook.xsl
/usr/share/xml/docbook/xsl-stylesheets-1.79.2/manpages/docbook.xsl
find: …
```
> configure: fix searching for docbook.xsl

- CMakeLists.txt
- configure.ac
- dbld/deb
- dbld/generate-debian-directory
- dbld/generate-rpm-specfile
- dbld/pkg-tarball
- dbld/rpm
- dbld/rules
- dbld/tarball
- scripts/Makefile.am
- scripts/version.sh
The `git describe` is capable to get a much nicer cheap version.
A few things left to do:
> version from git describe

- modules/appmodel/appmodel-grammar.ym
- modules/pseudofile/pseudofile-grammar.ym
See the following example.
```
@version: 3.20
application a[my-apparser] {
rewrite { set("b" value("b") };
};
log {
parser { app-parser(topic(my-apparser)); };
};
```
In this case, the error happens in the `application_options` in the
grammar file (`KW_REWRITE` is not allowed), after we freed `$2` and
`$4`. However, in case of grammar error, lexer frees these tokens
too, hence double free.
As a resolution, the `free` calls are moved to the end of the grammar file.
This way only grammar will free these tokens.
-----
Similarly, with pseudofile:
```
@version: 3.20
log {
destination { pseudofile("/tmp/foo" disk-buffer(a) ); };
};
```
causes crash.
> app-parser, pseudofile: fix crash with grammar error

- lib/tests/test_type_hints.c
- lib/type-hinting.c
- modules/json/format-json.c
- modules/json/tests/test_format_json.c
This is a more comprehensive fix to #2636
> Type hinting should not accept empty values

- modules/afsocket/afinet-dest.c
- modules/afsocket/afinet-dest.h
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
> afinet: add option to set the maximum spoofed datagram size

- modules/python/compat/compat-python-v2.c
- modules/python/compat/compat-python-v3.c
- modules/python/compat/compat-python.h
- modules/python/python-logmsg.c
- modules/python/python-plugin.c
The current `LogMessage.set_timestamp` behaved differently for py2 or py3; and had issue with *aware* datetime.
Fixes:
* py3 use local timezone in case of *naive* datetime
* py2 could not accept *aware* datetime
Also creates a code that is compatible with both py2 and py3 so does not have to be in compat layer.
Example for creating *aware* datetime
```
import datetime
import pytz
datetime.datetime(2019,9,14,12,34,56,tzinfo=pytz.timezone('Asia/Shanghai'))
```
> python: set_timestamp normalization

- lib/stats/stats-query.c
- lib/stats/stats-query.h
- lib/stats/stats.c
Dynamic counters/clusters were freed after they became expired, but they stayed in the `counter_index`, which is used for `get` queries. When we tried to access these freed counters from the index, we got undefined behavior, possibly SEGFAULT.
> stats: deindex pruned counters/clusters

- CMakeLists.txt
- cmake/module_switch.cmake
- dev-utils/plugin_skeleton_creator/plugin_template_CMakeLists.txt
- lib/filter/tests/CMakeLists.txt
- modules/afamqp/CMakeLists.txt
- modules/afsmtp/CMakeLists.txt
- modules/afsql/CMakeLists.txt
- modules/afstomp/CMakeLists.txt
- modules/afstreams/CMakeLists.txt
- modules/afuser/CMakeLists.txt
- modules/appmodel/CMakeLists.txt
- modules/basicfuncs/CMakeLists.txt
- modules/geoip/CMakeLists.txt
- modules/geoip2/CMakeLists.txt
- modules/getent/CMakeLists.txt
- modules/hook-commands/CMakeLists.txt
- modules/http/CMakeLists.txt
- modules/java/CMakeLists.txt
- modules/json/CMakeLists.txt
- modules/map-value-pairs/CMakeLists.txt
- modules/native/CMakeLists.txt
- modules/openbsd/CMakeLists.txt
- modules/pacctformat/CMakeLists.txt
- modules/python/CMakeLists.txt
- modules/redis/CMakeLists.txt
- modules/riemann/CMakeLists.txt
- modules/snmptrapd-parser/CMakeLists.txt
- modules/stardate/CMakeLists.txt
- modules/xml/CMakeLists.txt
- If `-DDISABLE_ALL_MODULES=yes` specified for cmake, all switchable modules are disabled by default. One can still override specific modules by: `-DDISABLE_ALL_MODULES=yes -DENABLE_PYTHON=yes`. The order of definitions do not matter.
- Fixed a bug, when `-DENABLE_IPV6=no` resulted in compile error in a unit test.
- Fixed a bug when json unit tests were still tried to compiled even without json support.
- Removed `-DENABLE_BASICFUNCS`, as it causes compile error in some unit tests, it is not switchable in autotools, and does not have any external dependencies.
> cmake: disable_all_modules support

- lib/logreader.c
- lib/logwriter.c
There is a race condition between scheduled I/O operations in worker threads and closing the idle connections (response/ack_timeout timer).
There is no protection - in afsocket source-driver - to not destroy connections(readers), which have scheduled I/O operation (not like when we reap writers on file dest. side).
The idle timer is not stopped, just when an I/O operation finished and we would like to re-schedule the next action on source side (update_watches() ).
The timer can trigger a connection closing, although there is schedule I/O operation.
Timer should be stopped when we schedule an I/O.
This way we eliminate the race condition between 2 sides.
We do stop I/O polling (see calling log_reader_stop_watches() in log_reader_io_handle_in()), so stopping the idle timer makes sens. …
> logreader/logwriter: fix race condition of idle timer and scheduled I/O job

- modules/dbparser/groupingby.c
This patchset fixes:
- filter expressions of grouping-by were not freed
- init method of the filter expressions were not called
- use after free when reload with a non-closed context
> grouping-by: use after free, memory leak, missing init calls of filters

- modules/afamqp/afamqp.c
During startup: connect was called two times in amqp destination, hence amqp destination built two connections towards the rabbitmq server. One connect was called from thread_init, the other one is called because of worker.connect virtual function:
https://github.com/balabit/syslog-ng/blob/5a03be7255736941a55ed67fb27c6a08c84dd275/modules/afamqp/afamqp.c#L662
and
https://github.com/balabit/syslog-ng/blob/5a03be7255736941a55ed67fb27c6a08c84dd275/modules/afamqp/afamqp.c#L744
Interestingly, this did not cause any particular problem on its own, even valgrind did not show any error. However, if someone wants to [add heartbeat to amqp](https://github.com/balabit/syslog-ng/issues/189) at some point, this would cause a little headache, as the first connection would be terminated due to timeout, as …
> amqp: fixing double connect

- modules/diskq/tests/test_reliable_backlog.c
Criterion runs tests in parallel, however the different testcases use
the same file name for disk queue. Hence the tests run each other's
file. This leads to random failures.
This patch specifies different filename for the different tests, so
that the individual tests would not conflict.
> test_reliable_backlog: fix random failure

- lib/secret-storage/nondumpable-allocator.c
mmap returns -1 instead of NULL in case of error, because in
some (extreme) cases, NULL can be start of a mmapped area. Aligning the
code according to this.
Users of nondumpable-allocator need not be changed. Nondumpable
allocator puts metadata to the front of a page, and returns the memory
area after the metadata. Hence, NULL is never returned after a
successful allocation, so NULL can still be used for error handling.
> nondumpable-allocator: fixing mmap error handling

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/cfg.h
- lib/logproto/logproto-framed-server.c
- lib/logproto/logproto-server.c
- lib/logproto/logproto-server.h
- lib/logproto/tests/test-framed-server.c
Add the `trim-large-messages` option to the logproto-framed-server. (syslog source driver)
Without trimming, the framed server simply drops oversized messages (>log_msg_size) and closes the incoming connection.
With trim-large-messages enabled, framed server will create a log message from the first (`log_msg_size` sized) part of the message, and ignores the rest of it. The communication will continue uniterrupted with the following message.
TODO:
> Trim large messages

- scl/graylog2/plugin.conf
Updated @Gorian work(https://github.com/balabit/syslog-ng/pull/2637) based on @furiel comments (https://github.com/balabit/syslog-ng/pull/2637#discussion_r268035221).
With this modification the `graylog2` can be configured with any transport (`tcp`, `udp`, `tls`, ...).
A `tls` example:
```
graylog2(
transport(tls)
tls(
ca-dir("/etc/ssl/certs")
peer-verify("required-trusted")
)
);
```
> graylog2 support tls, udp

- modules/dbparser/pdb-load.c
There was earlier a memory leak in pattern-db: the rules in patterndb were leaked. This was attempted to be fixed in https://github.com/balabit/syslog-ng/pull/2311. However the fix was incomplete, the last rule was still not be freed.
The problem was in the end element logic: due to the `== 0`, the pdb_rule_unref was called only in case of parse error. Hence rule was never freed at the `</rule>` end element.
This patch reverts https://github.com/balabit/syslog-ng/pull/2311, and fixes the return value problem.
> db-parser: fix memory leak

- modules/diskq/tests/test_diskq.c
The `test_diskq_statistics` could crash under certain conditions.
If the linux ASLR is enabled, and the compiler creates executable
that is position independent(`-fPIC`).
The function pointer could became invalid, in the unit test.
As the Criterion does *fork* and *exec* before executing tests.
Additionally the parameters are created in the *parent*,
and passed down to the *child* process, which - because of ASLR -
possible stores the referenced function in a different address.
This patch does not solves the above issue, but hides this behaviour
with additionally calling the function pointer passed by
via function pointer.
Because of this, a `@PLT` trampoline function is created, which
address is used, that can be made position independent hence
valid after *fork* plus *exec* if compiled …
> Fix unit test with function pointer dereference in case of ASLR, Criterion

- modules/syslogformat/syslog-format.c
With RFC5424, the $MSG payload is optional for the message. In that
case the syslog-parser() bailed out without explicitly setting $MSG to
an empty string.
This works if this is the initial parsing of the message (e.g. right
within the source driver), but doesn't if we are using an explicit
syslog-parser() later on. In that case the $MSG will remain the original
value, potentially the entire raw message, if it was received via
flags(no-parse).
> syslogformat: set $MSG even if the incoming message is empty

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/cfg-parser.h
- modules/appmodel/app-parser-generator.c
New aliases:
* true/false
* enable/disable
* enabled/disabled
Fixes #906.
> cfg-parser: add aliases for yesno

- lib/filter/filter-cmp.c
- lib/filter/tests/test_filters_fop_cmp.c
The `KW_NUM_NE` and `KW_NE` keywords did not set any comparison flag for `fop_cmp_eval()`. It was handled by checking for no flag set (`self->cmp_op == 0`), which is not true in case of `KW_NUM_NE`, because with `KW_NUM_NE` the `FCMP_NUM` flag is set.
After this the `|| self->cmp_op == 0` check is not needed, but we have to make a boolean from `self->cmp_op & FCMP_LT`, which was passively done by having `|| self->cmp_op == 0` after it. I cleaned it up with double negation.
Sample config for reproduction:
```
@version: 3.20
filter f_even { "$(% ${R_SEC} 2)" == "0" };
filter f_odd { "$(% ${R_SEC} 2)" != "0" };
destination d_local {
file("/tmp/ne_test.log");
};
log {
source { example-msg-generator(); };
filter(f_even);
destination(d_local);
};
log {
source { …
```
> filter: Fix "!=" filter

- scripts/version.sh
In case when git is not installed or no tags exist, we should fall back to the VERSION file.
This commit fixes the compilation in environments where git is not available or where `git clone --depth` is used, such as Travis.
> Version generation improvement

- modules/date/date-grammar.ym
- modules/date/date-parser.c
- modules/date/date-parser.h
- modules/date/tests/test_date.c
This patch adds support for flags(guess-timezone) to date-parser() in a similar vein to how
the tcp() driver supports this option.
Example:
```
date-parser(flags(guess-timezone));
```
The rest of the options works just as previously.
> Date parser to support guess timezone

- modules/http/http-worker.c
- modules/riemann/riemann-worker.c
Note: the expedite flush feature is not available in compatibility mode (dests: Java, Python, amqp, mongodb, smtp, sql, stomp, redis).
> Fixup expedite threaded flush at reload

- modules/dbparser/pdb-file.c
- modules/dbparser/pdb-file.h
- modules/dbparser/pdbtool/pdbtool.c
- modules/dbparser/tests/test_patterndb.c
Adds sort option to `pdbtool merge`:
`  -s, --sort                      Sort files during merge (alphabetic order, with files first, directories after)
`
By default the option is not set, and the file sequence is not guaranteed to be sorted.
Fixes #294.
> patterndb: Add sort option to pdbtool merge

- scl/apache/apache.conf
This patch will add support for vhost & port in common & combined apache logs as discussed @ https://github.com/balabit/syslog-ng/issues/2670.  Here is that format -
```
foo.com:443 1.2.3.4 - - [15/Apr/2019:14:30:16 -0400] "GET /bar.html HTTP/2.0" 500 - "https://foo.com/referer.html" "Mozilla/5.0 ..."
```
Below is my use case that I'm using on a test server, using the `${.apache.vhost}` macro to create a directory then logging using combined format -
apache:
```
LogFormat "%v:%p %h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-agent}i\"" vcombined
CustomLog "|/usr/bin/logger -S 65536 -t apache -p info -d -n 127.0.0.1 -P 5141" vcombined
```
syslog-ng:
```
source s_apache_access {
network(ip(127.0.0.1) port(5141) transport(udp) flags(syslog-protocol));
};
destination d_apache_access { …
```
> support for vhost:port in common/combined log formats

- modules/afamqp/afamqp-grammar.ym
- modules/afamqp/afamqp-parser.c
- modules/afamqp/afamqp.c
- modules/afamqp/afamqp.h
Users can provide heartbeat in their configuration, that is negotiated with the server. In case heartbeat is enabled, amqp destination will send heartbeats periodically.
Heartbeat is measured in seconds. Default value is zero.
Example configuration:
```
destination { amqp(vhost("/")
exchange("logs")
body("hello world")
heartbeat(10)
username(guest) password(guest)); };
```
Fixes: https://github.com/balabit/syslog-ng/issues/189
> amqp: heartbeat support

- tests/copyright/check.sh
- tests/copyright/policy
The copyright checker checks for corporate copyright header lines, so it detects when we forget to add them.
This PR extends this validation and accepts "One Identity" as well as "Balabit".
Please note that  the `non-balabit` section of the policy file is for marking units that do not contain corporate copyright lines **deliberately**.
>  copyright: accept "One Identity" in copyright notices

- modules/dbparser/CMakeLists.txt
- modules/dbparser/Makefile.am
- modules/dbparser/dbparser-grammar.ym
- modules/dbparser/dbparser-parser.c
- modules/dbparser/dbparser.c
- modules/dbparser/dbparser.h
- modules/dbparser/patterndb.c
- modules/dbparser/patterndb.h
- modules/dbparser/pdb-lookup-params.c
- modules/dbparser/pdb-lookup-params.h
- modules/dbparser/pdb-ruleset.c
- modules/dbparser/tests/test_patterndb.c
- modules/dbparser/tests/test_patterndb.h
Fixes: https://github.com/balabit/syslog-ng/issues/141
For now, the rule selection in db-parser is based on the `PROGRAM` macro value. This patchset makes this configurable: the selector can be specified by template.
There is a `template` option already available in `db-parser`, which defines the message that is processed by the parser (similarly to any other parsers). To avoid confusion with `program-template`, this patchset adds an alias for it: `message-template`.
There is an interesting feature in db-parser: pattern matching works in `PROGRAM`. It turned out that I do not need to deal with this functionality separately, it automatically worked after my changes. While I was in doubt, I saw that was not covered by a unit test, so I added one. In the example below, you can see an example …
> db-parser: support for program_template

- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/list-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
This branch adds $(explode) and $(implode) template functions. The first one turns a string separated by a specific character into a list, the other turns a list into a string gluing the pieces together with a separator.
Example:
value("MESSAGE", "$1 1 0 $(implode ' ' $(list-slice :-1 $(context-values $MSG)))")
> Add implode and explode template functions

- lib/logreader.c
- lib/logreader.h
- modules/affile/file-reader.c
- modules/afprog/afprog.c
- modules/afsocket/afsocket-source.c
- modules/afstreams/afstreams.c
- modules/openbsd/openbsd-driver.c
This branch eliminates a lot of system calls on the LogReader input handling path, thereby increasing performance, especially if the per-wakeup overheads cannot be amortized over a lot of messages (e.g. it does not help much in case we are running with log-fetch-limit(1000) and sufficient window, but it does if we go to sleep every 10 messages).
The performance change is basically that we don't call  `iv_unregister_fd()` at every input callback, rather we'll only set the interesting poll mask to zero. This removes a number of epoll_ctl/setsockopt calls, whose overhead can be quite visible.
On the other hand this branch also contains a quite significant refactor of the LogReader, by clearing up various internal layers. These changes are:
* "watches": are the set of events that we need wrt. …
> LogReader refactor + performance improvements

- lib/template/templates.c
- lib/template/templates.h
- lib/template/tests/test_template.c
- modules/dbparser/correllation-context.c
- modules/dbparser/correllation-context.h
- modules/dbparser/dbparser-grammar.ym
- modules/dbparser/dbparser-parser.c
- modules/dbparser/groupingby.c
- modules/dbparser/groupingby.h
This patch implements sorting of the elements accumulated into a context.
It is useful when entries are not received in order.
Example:
```
block parser cisco-ise-parser() {
channel {
parser {
csv-parser(columns('1', '2', '3', 'MSG') flags(greedy));
grouping-by(
scope("host")
key("$1")
sort-key("$3")
trigger("$(context-length)" eq "$2")
timeout(5)
aggregate(
inherit-mode(last-message)
value("MESSAGE", "$(if ('$(context-length)' eq '$(+ $2 1)')
'$1 1 0 $(implode \" \" $(list-slice :-1 $(context-values $MSG)))'
'$1 1 0 SYSLOG TRUNCATED $(list-slice :-1 $(context-values $3-$MSG))')")
tags(".cise.joined_message"))
);
};
filter { tags(".cise.joined_message"); };
};
};
```
> groupingby: add sort-key() option

- modules/appmodel/app-parser-generator.c
- modules/appmodel/tests/test_app_parser_generator.c
- modules/system-source/system-source.c
App-parsers usage, including using the "system-unix" topic
introduced in 286e1a64b001f12e6be2b4bf5cccab4b21c2081b.
I think removing an unused code is a good step,
especially that it could cause problems when the first system-unix topic
would be introduced.
Reason:
- app-parser creates a channel, which groups some junctions-channels
- 2 app-parsers following each other therefore means 2 channels, i.e. a log pipe sequence.
If a drop happens in the first part, then it will never reach the second part, i.e. the 2nd app-parser topic.
Conclusion is that we either remove the unused app-parser,
or fix it with an additional junction-channel/if-else.
> system-source: remove unused app-parser

- modules/http/http.c
**NOTE:** This PR has been changed since the last round to allow comma as well as space as a separator.
It is pretty common that we get a list of things via a string argument. For
instance, for Java/Python based destinations that's the only way to
pass a list. An example is the java based kafka driver, where
kafka-bootstrap-servers() is one such attribute.
I recently encountered a case, where someone wanted to use a similar format
to HTTP and was surprised it didn't support this case.
This patch changes the url() parameter, it now supports the following cases:
* url("server1", "server2", "server3"); # commas are optional
* url("server1 server2 server3");        # space separated within a single string
* url("server1,server2,server3");        # comma separated within a single string …
> http: allow URLs to be specified by a space/comma separated string

- lib/ack_tracker.h
- lib/bookmark.h
- lib/late_ack_tracker.c
- lib/logpipe.h
- lib/logreader.c
- lib/logreader.h
- lib/logsource.c
- lib/logsource.h
- modules/affile/file-reader.c
- modules/affile/tests/test_wildcard_file_reader.c
- modules/affile/wildcard-file-reader.c
- modules/affile/wildcard-file-reader.h
- modules/affile/wildcard-source.c
The `window_empty` functionality was used only by `wildcard-file()`, and had an ordering issue (between `iv_event` `unregister()` and `post()`) everywhere else, causing a crash or an infinite loop inside ivykis. 
In order to resolve the crash, `window_empty` and `NC_LAST_MSG_SENT` have been removed from `LogSource`/`LogReader` and something else has been added by @lbudai :
a `LogSource`/`AckTracker`-level functionality that makes it possible to disable bookmark handling when a file is deleted from the disk. Since bookmark information is invalidated after a file is removed, 
saving them is unnecessary.
This functionality allows us to merge 2 events inside wildcard file source (`deleted_file_finished()` can be merged into `deleted_file_eof()`):
`_remove_file_reader()` had to be delayed to a …
> Fix a general source-related crash and enhance wildcard-file()'s bookmark handling

- syslog-ng/main.c
Now the `syslog-ng -d` does not mean `syslog-ng -de` (same goes with `-r` option).
This solves #2730
> Debug mode does not imply stderr

- lib/timeutils/misc.c
- lib/timeutils/misc.h
- syslog-ng/main.c
Currently, the behaviour of syslog-ng regarding timezone changes handling
depends on SYSLOG_NG_HAVE_LOCALTIME_R configuration parameter. If
SYSLOG_NG_HAVE_LOCALTIME_R is set to '1', the timezone is not updated
in run time and vise versa. However, timezone setting is considered as
a costly operation, so it can be not desired to perform it
frequently. One of the wice options is setting the timezone on-demand.
The code sets timezone on config reload event.
> Reset the timezone on config reload event.

- lib/mainloop.c
- lib/stats/stats.c
There is a minor leak in unit tests that this patch intends to fix. Only unit tests are affected. However, every unit test is affected that calls `app_startup`, which is very common. For example `test_filter_call`:
```
==3039== 24 bytes in 1 blocks are still reachable in loss record 9 of 23
==3039==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==3039==    by 0x5A057B8: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==3039==    by 0x5A1C9C2: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==3039==    by 0x59FC3C3: g_list_append (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==3039==    by 0x4E9B8F7: control_register_command (control-commands.c:68)
==3039==    by 0x4EB5FD8: stats_register_control_commands …
```
> stats: fix register control commands leak for unit tests

- lib/apphook.c
- lib/tests/test_apphook.c
A `reopen` after a `reload` could cause infinite loop, as all of the registered `reopen` hook was linked into the list after the current; creating an infinite loop.
> fix infinite loop

- tests/python_functional/.pre-commit-config.yaml
- tests/python_functional/conftest.py
- tests/python_functional/functional_tests/conftest.py
- tests/python_functional/src/conftest.py
- tests/python_functional/src/executors/command_executor.py
- tests/python_functional/src/executors/process_executor.py
- tests/python_functional/src/executors/tests/test_command_executor.py
- tests/python_functional/src/message_reader/tests/test_message_reader.py
- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
- tests/python_functional/src/syslog_ng/syslog_ng_paths.py
- tests/python_functional/src/syslog_ng/tests/test_syslog_ng_paths.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/file_destination.py
- tests/python_functional/src/syslog_ng_config/statements/sources/file_source.py
- tests/python_functional/src/syslog_ng_ctl/syslog_ng_ctl_executor.py
- tests/python_functional/src/testcase_parameters/testcase_parameters.py
reorder-python-imports hook should be updated with an extra command line argument:
```
--application-directories=tests/python_functional/
```
* Apply reorder-python-imports again
* This fix sets where Light is rooted
* Without this reorder-python-imports will set imports in wrong order
> LightAutomation: Update reorder-python-imports hook

- lib/logthrsource/logthrsourcedrv.c
- lib/logthrsource/logthrsourcedrv.h
There was a todo about support position tracking in
logthrsourcedrv. The default value is the same as the original:
early ack tracking is used. However, children can override this in
[child_driver]_new() time using
```
self->super[.super(if inheriting from logthrsourcefetcher)].worker_options.position_tracked = TRUE;
```
> logthrsourcedrv: support position tracking

- lib/template/templates.c
- lib/template/templates.h
- libtest/cr_template.c
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/str-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- modules/basicfuncs/tf-template.c
Extends the $(template) template function to allow dynamic binding, e.g. the name of the template to be invoked coming from a name-value pair, e.g. a template.
Some more details:
```
/*
* $(template <template-name> ...)
*
*   This template function looks up <template-name> in the configuration
*   and uses that format its result.  The template name can either be a
*   static or a dynamic reference.
*
*     * static: means that we perform lookup at configuration read time
*
*     * dynamic: the template name is actually a template (e.g.
*       ${foobar}), its result are taken as the name of the template and
*       that is looked up at runtime.
*
*   Dynamic references are slower, but more flexible.  syslog-ng uses the
*   following algorithm to determine which one to use:
*
*     * …
```
> $(template) dynamic binding

- lib/filter/filter-expr-grammar.ym
- lib/filter/filter-re.c
- lib/filter/filter-re.h
- lib/filter/tests/CMakeLists.txt
- lib/filter/tests/test_filters_common.c
- lib/filter/tests/test_filters_common.h
- lib/filter/tests/test_filters_regexp.c
- lib/rewrite/rewrite-subst.c
- scl/apache/apache.conf
- scl/cisco/plugin.conf
This branch adds support for the template() option for match() expressions, e.g. previously we could only do name-value references like this:
```
match("^foobarregexp" value("HOST"));
```
Now we can also do this:
```
match("^foobarregexp" template("$HOST"));
```
Or even complex template expressions:
```
match("^foobarregexp" template("$HOST|$PROGRAM$PID|$MSG"));
```
The "simple" templates are handled specially so they are as fast as match(value()). This branch also makes use of this feature in the cisco and apache parsers in SCL to show that it can be done.
NOTE: this branch shares two patches with #2701 if either goes in first, the other can be rebased and those two patches skipped.
> Template support in match

- modules/snmp-dest/snmpdest-grammar.ym
- modules/snmp-dest/snmpdest.c
- modules/snmp-dest/snmpdest.h
- modules/snmp-dest/tests/test_snmp_dest.c
* Fix unit test issues:
* `cfg_new_snippet` should be used instead of `cfg_new` in UT
* `log_pipe_init` should not be used before setter methods (as it is not done in syslog-ng normal execution either)
* Some minor refactors
* Removed tailing `NULL` from `msg_` macros (`scripts/rm-extra-msg-sentinel.sh`)
> snmp dest leak template

- contrib/syslog-ng-debun
This function will save ```syslog-ng-ctl config --preprocessed``` output in syslog-ng.conf if syslong-ng is live,
otherwise it will store syslog-ng.conf from disk.
resolves https://github.com/mehul-m-prajapati/gsoc-debun-tool/issues/1
> debun: add acquire_running_syslog_config function

- CMakeLists.txt
- Makefile.am
They will produce error on shift/reduce and reduce/reduce
problems.
Now we can detect these problems in travis,
so problematic PRs will not be merged accidentally.
> Make: enable bison error flags: conflicts-sr/rr

- modules/http/http.c
If less workers are used, then some url targets will not receive messages.
We even warn about this in documentation.
> http: Warn if less workers used than urls

- dbld/images/helpers/pip_packages.manifest
- requirements.txt
- Ligth is not depends anymore on this pip packages
> Light: Remove unused Light dependencies

- lib/timeutils/wallclocktime.c
The conditional assignment to wct->wct_gmtoff was [removed in #2709][1]
because we though that the field previously did not exist in some
circumstances which where not true anymore.  In fact, the macros is here
to help us detect what `timezone` is, since it's not the same on all
platforms:
On Linux, timezone is declared in time.h as:
extern long int timezone;
On FreeBSD, timezone is declared in time.h as:
char *timezone(int zone, int dst);
As a consequence, the assignment on FreeBSD produce a compiler error:
```
CC       lib/timeutils/libsyslog_ng_la-wallclocktime.lo
lib/timeutils/wallclocktime.c:551:37: error: invalid argument type 'char *(*)(int, int)' to unary expression
wct->wct_gmtoff = -(timezone);
^~~~~~~~~~~
1 error generated.
```
Re-add the removed #ifdef to fix the build on …
> Reintroduce test on SYSLOG_NG_HAVE_TIMEZONE

- tests/python_functional/src/syslog_ng/syslog_ng.py
- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
This patch set fixes two related issues in SyslogNg() class
- fixes restart() ordering, started with stop() follows with start()
- do not allow to start same syslog process twice
- testcases are not created
> Light: fix restart ordering

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/logthrsource/logthrfetcherdrv.c
- lib/logthrsource/logthrfetcherdrv.h
- lib/logthrsource/tests/test_logthrfetcherdrv.c
- modules/examples/sources/threaded-diskq-source/threaded-diskq-source-grammar.ym
- modules/python/python-fetcher.c
- modules/python/python-grammar.ym
This patch adds two new constants for `logthrfetcher`:
- `THREADED_FETCH_NO_DATA`
The child can signal the driver that it does not want to provide data for some time. This is very similar to `THREADED_FETCH_ERROR`. The difference is that we do not consider this case as an error, so there is no need to disconnect+reconnect, nor need to emit `msg_error`.
A new option is added to control the time without fetch: `NO_DATA_DELAY`. If not provided, we will reuse `time_reopen`, however users can override this behavior with `no_data_delay()`, and thus handle the two cases independently. The resolution is in seconds.
- `THREADED_FETCH_TRY_AGAIN`
The child can ask the driver to reschedule a fetch without delay. This is the no_delay variant of the `THREADED_FETCH_NO_DATA` above. Child can express …
> logthrfetcher: new constants

- lib/parse-number.c
- lib/parse-number.h
- modules/basicfuncs/CMakeLists.txt
- modules/basicfuncs/Makefile.am
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/numeric-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
This PR is about supporting math expression using floating-point values.  The code is published for review for now, because some decisions might need to be discussed.  I plan to amend the commits to address the issues and comments raised by the syslog-ng community, and remove the `[Do not merge]` tag when I consider the changes to be ready.
Fixes #2734
> Add support for floating point operations

- lib/logproto/logproto-server.h
- lib/logreader.c
- lib/logsource.c
I think it is better to open a dedicated PR for this small change.
> logsource: create AckTracker in log_source_init

- .ctags
- tests/copyright/policy
motivation: sometimes when I forget to remove dbld/install (always...),
then ctags parses dbld/install/{header-files} and I'm finding myself in
a sitation when I don't understand why my changes
a) even compiles at the very first attempt (first, I'm happy, later it
becomes suspicious)
b) don't have any effects... this could be very-very frustrating
> ctags: add ctags config (for excluding dbld...)

- tests/python_functional/conftest.py
- tests/python_functional/functional_tests/conftest.py
- tests/python_functional/src/common/operations.py
- tests/python_functional/src/common/pytest_operations.py
- tests/python_functional/src/conftest.py
- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
- tests/python_functional/src/syslog_ng/syslog_ng_paths.py
- tests/python_functional/src/syslog_ng/tests/test_syslog_ng_paths.py
- tests/python_functional/src/syslog_ng_config/renderer.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/file_destination.py
- tests/python_functional/src/syslog_ng_config/statements/sources/file_source.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
- tests/python_functional/src/syslog_ng_ctl/syslog_ng_ctl_executor.py
- tests/python_functional/src/testcase_parameters/testcase_parameters.py
This PR is based on my #2768 PR.
The patch set of this PR was previously part of my #2723. I have just separated it from there.
I have decided to create smaller separate PRs to move forward Light related PRs faster.
Patch description:
- with initializing working_dir as a global variable we will able to eliminate it from SyslogNgConfig() class.
- with this change SyslogNgConfig() class can be used more easily in Ligth, and opens it for a refactoring
> Light: Remove working dir from SyslogNgConfig dependencies

- modules/dbparser/correllation-key.c
- modules/dbparser/correllation-key.h
- modules/dbparser/groupingby.c
- modules/dbparser/patterndb.c
- modules/dbparser/synthetic-message.c
- modules/dbparser/synthetic-message.h
The `grouping-by` parser holds a lock during it processing a message.
This happens when in the source thread a `grouping-by` is triggered and hold the lock.
The same time the associated timer is triggered in the main thread, which also wants to hold the same lock (but the source thread has it).
In the source thread, in the end of the processing it sends toward the next pipe till it reaches the destination.
Where the destination wants to do some operation  (for details see the issue) in the main thread, so it triggers a task to be done and waits for that to finish.
Here comes the issue, the main thread still executing the triggered timer waiting for the same thread source to leave the lock, which waits the main thread to execute a piece of code.
In truths the `grouping-by` parser does not …
> fix grouping by deadlock

- lib/logwriter.c
I've accidentally closed #2645 with a stale push.
Original author: @kyeongy
> There is a chance with rare timing that a suspended writer tries to
access already freed client, which causes a SEGV.
https://github.com/balabit/syslog-ng/pull/2645#issuecomment-477816858
https://github.com/balabit/syslog-ng/pull/2645#issuecomment-500114948
https://github.com/balabit/syslog-ng/pull/2645#issuecomment-500254227
https://github.com/balabit/syslog-ng/pull/2645#issuecomment-500420282
> logwriter: Avoid null pointer access from suspended writer

- packaging/debian/rules
- packaging/debian/syslog-ng-mod-python.install
- packaging/rhel/syslog-ng.spec
In #2438, syslog-ng Python modules have been moved from `/usr/lib/python2.7/site-packages/` to `/usr/lib/syslog-ng/python`.
> Follow-up Python pylib path change in deb and rpm packaging

- .gitignore
Inspired by https://github.com/balabit/syslog-ng/pull/2784 
well I use the `build` directory to build shame on me, but `ag` could exclude this directory from searching IF it is listed in `.gitignore`
the other `tags` as well
(I know I could create my own ignore file, but well..)
> gitignore: tags file and build directory

- modules/date/date-grammar.ym
- modules/date/date-parser.c
- modules/date/date-parser.h
- modules/date/tests/test_date.c
- scl/cisco/plugin.conf
Thanks to this change, a single date-parser is able to process different date formats, making it easy to catch on when some programs change the way they log information.
Internal variables where renamed from `format` to `formats` to reflect the fact that the variable is now a list of formats, but the public template name has been kept back to avoid breaking existing configuration:
```
date-parser(format(
"%FT%T.%f",
"%F %T,%f",
"%F %T"
));
```
_Suggested by @bazsi in https://github.com/balabit/syslog-ng/pull/2709#issuecomment-489568587_
> Allow passing mutiple formats to date-parser

- lib/cfg-grammar.y
- modules/affile/affile-dest.c
- modules/affile/affile-dest.h
- modules/affile/affile-grammar.ym
- modules/affile/affile-parser.c
Fixing 2 problems with `time-reap()`
The first problem: `time-reap()` can only be set globally, for all destinations.
The second problem: It can not be disabled. We should be able to disable it, if we are sure, that no problematic templating is set for that destination.
Example usage:
```
@version: 3.21
options {
time-reap(2); # global time-reap()
};
source s_input {
example-msg-generator(freq(5));
};
destination d_fifo {
pipe(
"/tmp/test.fifo",
time-reap(0)  # disable time-reap() for this destination
);
};
log {
source(s_input);
destination(d_fifo);
};
```
The PR also introduces a new functionality: If the `pipe()` or `file()` destination's filepath does not have a template, the `time-reap()` is not inherited from the global options, but is disabled, by default. The user can override …
> affile: Add option to disable time-reap()

- tests/commits/check.sh
In my opinion, the following subjects should be accepted:
```
Revert "cfg-parser: add aliases for yesno"
geoip2: extend msg with ip
Light: Remove unused Light dependencies
autotools,cmake: add -Wundef
$(grep): fixed possible segfault on parse errors
elastic-v2: fixed debian packaging
network(): added grammar skeleton and plugin registration
version.sh: unset CDPATH
dbld/images/centos{6,7}: add Python/pip support
```
> Relax commit check

- .travis.yml
- CMakeLists.txt
- Makefile.am
- lib/cfg-lexer.c
- lib/tests/test_type_hints.c
- libtest/testutils.c
- libtest/testutils.h
- modules/afsql/afsql.c
- tests/unit/test_zone.c
The main focus was on `cmake+clang`, sorry `autotools`.
Changes that were to replace/remove a warning was also changed in the `autotools`.
But a few option was removed in case of `clang` as `clang` does not define them, and those were not updated in `autotools` (in case of `autotools` those warnings must be turned on via `--enable-extra-warnings`).
Additionally I also turned on the extra warnings for `cmake+clang` combination.
Note: it seems clang is able to detect issues even if they are hidden via macro usage, while gcc is unable to see such errors (anything written in macros gcc just fine with it).
> update according to clang, gcc diagnostic differences, and fix newly found issues

- modules/dbparser/patterndb.c
After the extraction of `_pattern_db_advance_time_and_flush_expired()` in f5d2335ae3aacb4aeb56cbd5cf6bdc049cb6343a, this lock became unnecessary as `_emit_message()` operates only on `process_params` (per-thread, stack variable), and uses only a readonly field from `self`.
> dbparser: remove unnecessary lock

- lib/eventlog/src/evtstr.c
This issue could be reproduced with using address sanatizer and debug level, with logs longer than the `escaped_buffer` size (128).
> eventlog: flush escaped_buffer when full

- lib/cfg-grammar.y
- modules/redis/redis-grammar.ym
- modules/redis/redis.c
- modules/redis/redis.h
There are some redis commands, which needs more that 3 fields after the command.
This PR allows the user to set any number of parameters to redis's `command()` option.
The first must be a string, the remaining ones can be templates as well.
Example usage:
```
destination d_redis {
redis(
host("127.0.0.1")
port(6379)
command("XADD", "instanceLogged", "*", "message_id", "$HOST")
);
};
```
Fixes #2813
> redis: handle any number of parameters at `command`

- tests/python_functional/functional_tests/logpath/test_flags_catch_all.py
- tests/python_functional/functional_tests/source_drivers/file_source/test_acceptance.py
- tests/python_functional/src/common/network_operations.py
- tests/python_functional/src/message_builder/log_message.py
This PR makes Travis green again.
Travis now has multiple hostnames:
```
127.0.1.1 travis-job-0198b942-d444-4c1f-95e9-84a18577f20d travis-job-0198b942-d444-4c1f-95e9-84a18577f20d ip4-loopback trusty64
127.0.0.1 localhost nettuno travis vagrant travis-job-0198b942-d444-4c1f-95e9-84a18577f20d 
```
In Light, `get_short_hostname()` returns a different hostname than what syslog-ng resolves, making a few non-hostname-related tests fail.
In my opinion, a basic file source acceptance test and a catch-all path test should not use dynamic values, so I changed them to a static hostname and enabled `keep-hostname()`.
I have the same opinion on `LogMessage`. If it has a default value for hostname, it should not be dynamic (should not be dependent of the environment).
Of course, `get_short_hostname()` …
> Light: fix get_short_hostname(), use keep-hostname(yes) for basic tests

- modules/dbparser/radix.c
- modules/dbparser/tests/test_radix.c
`pcre_exec()` did not have enough place to store the offsets in the offset_vector (`matches` variable). I copied the API usage from `logmatcher.c`, which seems to work.
https://www.pcre.org/original/doc/html/pcre_exec.html requires the offset vector's size to be a multiple of 3. `ovecsize     Number of elements in the vector (a multiple of 3)`
Note for the reviewers:
* radix.c is abyssal for me, and I could not really prove to myself, that adding the `matches` array to `RParserPCREState` will not cause a race condition.
Fixes #2793
> radix: fix grouping in pcre

- lib/filter/filter-expr-grammar.ym
- lib/filter/filter-re.c
- lib/filter/filter-re.h
- lib/filter/tests/test_filters_common.c
- lib/logmatcher.c
- lib/logmatcher.h
- lib/rewrite/rewrite-subst.c
- tests/unit/test_matcher.c
pcre/posix support in logmatcher
version | pcre | posix 
------------ | ------------- | -------------
3.6 or below | supported | default
3.14 or above | default | not supported
The removed code handled the case when the configuration was still 3.6, as it sets the default handle to `posix` instead of `pcre`, the called setter function replaces the `posix` with `pcre` as `posix` is no longer supported.
The `GlobalConfig` was passed around just to do the above `pcre`=>`posix`=>`pcre` dance.
> logmatcher: posix not supported, not even for 3.6

- .travis.yml
The autotools find and prints the output of test execution, in case of cmake only the result failed/passed is printed. This PR changes the behaviour, so if a test failed it act as if verbose flag were used, otherwise state passed as before.
Also contains some cleanup, and renaming.
> Travis,cmake: ut verbose if failed

- lib/apphook.c
Recently, in app-startup() the g_cond_new() call preceded g_thread_init() call,
which only causes issues with glib versions older than 2.32, where it is not deprecated.
Fixes #2848
> apphook: fix g_thread_init call order issue with older glibs

- modules/snmp-dest/snmpdest.c
Statictics output fixed: (differences highlighted)
Before: snmp;snmpdest,127.0.0.1,10030;;a;processed;1
After: **dst**.snmp;**d_snmp#0**;snmpdest,127.0.0.1,10030;a;processed;1
> snmp destination: fixing statistics format

- lib/filter/tests/CMakeLists.txt
- lib/filter/tests/Makefile.am
- lib/filter/tests/test_filters_fop.c
Add unit tests to cover OR filters.
note: still left AND filters out since they only differs in their eval functions:
```
return (filter_expr_eval_with_context(self->left, msgs, num_msg)
|| filter_expr_eval_with_context(self->right, msgs, num_msg)) ^ s->comp;
```
vs
```
return (filter_expr_eval_with_context(self->left, msgs, num_msg)
&& filter_expr_eval_with_context(self->right, msgs, num_msg)) ^ s->comp;
```
TODO: the `_compile_standalone_filter` function is copied from an ongoing work on #2833, later it should be transfered into `test_filters_common.c` as a "library" function.
> lib/filter: add unit tests to filter-op

- lib/persist-state.c
- modules/diskq/dqtool.c
Add `relocate` function to `dqtool`.
Fixes #1851
* relocate a single queue file:
```    
bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist /tmp/syslog-ng-00000.rqf
```
* relocate multiple queue files
```
bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist /tmp/syslog-ng-00000.rqf /tmp/syslog-ng-00000.qf
```
* relocate all queue files
```
bin/dqtool relocate --new_path /tmp/dq --persist var/syslog-ng.persist --all
```
> Dqtool relocate diskq

- modules/python/tests/CMakeLists.txt
- modules/python/tests/Makefile.am
- modules/python/tests/test_python_template.c
As part of the work to push #2178 python had the most leak from all of them.
After some investigation it turned out that from syslog-ng point of view the memory management is fine, and in fact the leak is reported because of `pymalloc` (for details check out cpython valgrind guide).
Since python 3.6 it is possible to change the allocator via an environment varialbe (`PYTHONMALLOC`). As of now there is: `pymalloc`, `malloc` and those with a combination of `_debug` suffix.
The guid suggest to use `malloc` for valgrind, and there is no big surprise that it also helps with address sanitizer as well.
This PR suggest to use `malloc_debug` as that also additionally reports issues, I could find one misuse of the `GIL`.
Note: this is not going to have effect on Travis or Kira as they are using …
> python test: use malloc_debug for python unit tests

- lib/cfg.c
- lib/cfg.h
- modules/basicfuncs/cond-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- modules/dbparser/pdb-action.c
- modules/dbparser/pdbtool/pdbtool.c
- modules/dbparser/tests/test_patterndb.c
- modules/dbparser/tests/test_patterndb.h
The problem is described in #2842
This patch:
- allows to parse modules with the keywords from the main_parser.
- calls missing init statements, so filters will work properly.
> Add global context to standalone parsers

- lib/cfg.c
- lib/logmsg/nvhandle-descriptors.c
- lib/logmsg/nvhandle-descriptors.h
- lib/logmsg/nvtable.c
- lib/secret-storage/tests/test_secret_storage.c
The `recv_time_zone` is an actual not UT leak, but well only if configured.
> few small fries leak fixed

- packaging/debian/Makefile.am
- packaging/debian/control
- packaging/debian/syslog-ng-mod-kafka.install
- packaging/debian/syslog-ng-mod-rdkafka.install
This reverts commit 6f252f4b6bb171ae4ff5949e5539dedc7ba5734a.
I'm not sure that we really want to merge them... when someone installs the native mod-rdkafka, I'm sure that this user don't want to install the whole Java ecosystem (and even if this what the users want, then we have to _replace_ the previous mod-rdkafka by mod-kafka). With this patch we 'broke' current installations (mod-rdkafka has version 3.21). 
Of course I'm open to discuss it, but I have a very strong opinion on this question :)
> Revert "packaging/debian: merge rdkafka and kafka modules"

- dbld/build.manifest
The https://github.com/balabit/syslog-ng/pull/2802 broke the `Distro packages` build, due to not properly exclude the `mod-rdkafka`.
> fix distro packages build

- lib/CMakeLists.txt
- lib/Makefile.am
- lib/cfg-grammar.y
- lib/cfg-lexer.h
- lib/cfg-path.c
- lib/cfg-path.h
- lib/cfg.c
- lib/cfg.h
- lib/control/control-server.c
- lib/control/tests/test_control_cmds.c
- lib/mainloop-control.c
- modules/add-contextual-data/add-contextual-data-grammar.ym
- modules/afamqp/afamqp-grammar.ym
- modules/afsocket/afsocket-grammar.ym
- modules/dbparser/dbparser-grammar.ym
- modules/geoip/geoip-parser-grammar.ym
- modules/geoip2/geoip-parser-grammar.ym
- modules/http/http-grammar.ym
- modules/kafka/kafka-grammar.ym
- modules/pseudofile/pseudofile-grammar.ym
- modules/riemann/riemann-grammar.ym
- syslog-ng-ctl/syslog-ng-ctl.c
Hi,
As a part of GSoC, I am doing improvements in debun script.
The main task is to collect all files which are there in syslog-ng configuration.
As of now, in configuration, if there is a file path, we are defining that as type 'string'.
This patch would replace that 'string' type to 'path' type if there is an absolute path.  Also, I have added a check if a file is actually present or not on that absolute path.
Therefore, I can get a list of all files for ```debun script task``` by just doing a single grep on ```cfg-grammar.y```
If we have this type 'path', somebody could build upon an improvement like to offer
browsing functionality in config snipper if it is a directory.
resolves https://github.com/mehul-m-prajapati/gsoc-debun-tool/issues/7
> cfg-grammar: add new path type for files

- lib/cfg.c
The cfg_run_parser_with_main_context uses a cfg_run_parser, that frees the lexer.
Therefore pop-ing from the freed lexer is not okay.
> fix heap usage after free in cfg_run_parser_with_main_context

- lib/cfg-lexer.c
- lib/cfg-lexer.h
- lib/cfg.c
This branch has some refactor and two change:
* the `preprocess-into` accepts `-` and prints the preprocess config into `stdout` (this could be achieved currently with `--preprocess-into=/dev/stdout`)
* read the whole configuration file into memory and run the parser on that
> cfg parsing: read config file into memory + preprocess-into to stdout

- lib/cfg.c
- lib/cfg.h
- lib/plugin.c
- lib/plugin.h
- modules/add-contextual-data/add-contextual-data-filter-selector.c
the primary goal of this PR is this patch:
```
add-contextual-data: fix missing plugins in the filters configuration
It was reported by Mark Bonsack when using add-contextual-data() using the
filters() selector that the secondary configuration file misses all plugins
that the primary one has already loaded.
This patch makes this secondary config use the same set of plugins as the
primary one, eliminating the issue.
```
The branch also contains a plugin refactor (basically just moving code around and renaming stuff to make that uglyness somewhat nicer).
The fix relies on the concept of "subordinate" configurations, which by their definition share some things with the main config, this time the set of plugins available to it. Later, this could potentially be extended, but honestly I hope …
> Add contextual data make filters config plugin aware

- lib/cfg-tree.c
- lib/debugger/debugger.c
- lib/eventlog/src/evtstr.c
- lib/logproto/logproto-buffered-server.c
- lib/tests/test_logqueue.c
- lib/timeutils/conv.c
- libtest/queue_utils_lib.c
- modules/add-contextual-data/add-contextual-data.c
- modules/afsmtp/afsmtp.c
- modules/afsocket/systemd-syslog-source.c
- modules/dbparser/radix.c
- modules/diskq/dqtool.c
- modules/system-source/system-source.c
- persist-tool/add.c
- tests/loggen/file_reader.c
- tests/loggen/loggen.c
These bugs were found by [Infer](https://fbinfer.com/), a static analysis tool.
Most of the issues are harmless, I've sorted the commit list, so they are in order of decreasing severity.
```
83. modules/system-source/system-source.c:195: error: resource acquired by call to `open()` at line 191, column 13 is not released after line 195, column 18.
92. modules/system-source/system-source.c:211: error: resource acquired by call to `open()` at line 207, column 13 is not released after line 211, column 18.
85. persist-tool/add.c:204: error: memory dynamically allocated by call to `g_malloc()` at line 200, column 17 is not reachable after line 204, column 15.
86. persist-tool/add.c:210: error: memory dynamically allocated by call to `g_malloc()` at line 200, column 17 is not reachable after …
```
> Fix minor resource/memory leaks, null pointer dereference

- dbld/rules
- modules/java-modules/Makefile.am
This branch has been split off from #2775 and does the following:
* cleans up gradle argument passing from Makefiles (but not in CMakeLists.txt, help appreciated there)
* enables build-caching (e.g. --build-cache option)
* enables gradle cache-reuse in dbld builds, e.g. the gradle cache dir is stored `/dbld/build/gradle-home`
This speeds up java builds to a point I found them bearable without `--disable-java`, also it speeds up CI builds if the dbld environment is still on the host (e.g. jenkins, but not travis where this is not persisted).
> Dbld gradle caching

- .travis.yml
- tests/commits/check.sh
Moves travis specific code into `.travis.yml` and uses `${TRAVIS_COMMIT_RANGE}` variable configured by travis to specify the commits needs to be tested.
This range contains the commit of the current branch, and commits that are in the upstream (target remote/branch) has and the current branch do not have.
Note: when there is no PR opened just the branch pushed into github, this is empty (and falls back to the script default).
> travis: commit style check use commit range

- lib/template/macros.c
- lib/template/templates.c
- lib/template/templates.h
- lib/template/tests/test_template.c
This has been a dormant branch on my laptop, and I can't really remember what the trigger was to create this branch, but I thought I'd submit it as a PR and possibly find the reason and come up with a decision.
The LOGHOST macro always expanded to the FQDN of the host running
syslog-ng, whereas it is more logical to honour the use-fqdn() setting
like we do with other hostname related operations.
> templates: change the $LOGHOST macro to honour use-fqdn()

- lib/logsource.c
- lib/logsource.h
Fixes: #2893
On 32 bit systems (or non-64 bit systems), syslog-ng could abort during
shutdown.
What was the reason of the abort?
a) in `log_source_set_options` where we set the initial window size
conditionally, the condition was false thus the `full_window_size`
remained 0
b) when `log_source_free` is called during shutdown,
* `_release_dynamic_window` called unconditionally and
*  a dynamic_part is calculated as full_window_size(=0) - init_window_size(=default 100),
so dynamic_part = -100
* window_size is decremented by dynamic_part(-100) and the
`window_size_counter_sub` asserts on old_value >= value, and this
assert failed, so syslog-ng aborted
So the questions are
1) why we did not set initial window size?
2) why old_value was not greater than value?
Answers:
1) the value we get from …
> logsource: add explicit (un)initialized state to WindowSizeCounter

- lib/logreader.c
- lib/logsource.c
To be able to support using simple scratch_buffers_alloc() call for end-users,
scratch-buffers should be marked and reclaimed after each message that is passed through the log path.
For this the best location is on source side, so this happens after every message  (currently mainloop-workers use an explicit_gc call, therefore reclaiming every used scratch-buffers).
The place for doing this should be in LogSource rather then LogReader, as in case the latter, we need to add scratch_buffers_reclaim to every source: internal(), systemd-journal(), python-source(), and all threaded-source drivers as well.
This shows that it's real place is in LogSource::log_source_post().
> logreader,logsource: move scratch-buffer mark and reclaim into LogSource

- lib/logpipe.h
The path_options in case of hard flow control uses the address of local_path_options, that scope ends before the path_options is used in `s->queue(s, msg, path_options)`.
> logpipe: local_path_options use after out of scope

- lib/timeutils/zoneinfo.c
This PR removes assumptions from the zoneinfo parser that are no longer true (based on tzcode 2019b).
Fixes #2819
> Fix zoneinfo parser

- cmake/Makefile.am
- cmake/Modules/FindLIBCAP.cmake
- cmake/Modules/FindLibNet.cmake
- cmake/Modules/FindResolv.cmake
- configure.ac
- lib/CMakeLists.txt
- lib/compat/string.h
- modules/afsocket/CMakeLists.txt
- modules/afsql/CMakeLists.txt
- modules/confgen/tests/Makefile.am
- modules/cryptofuncs/CMakeLists.txt
- tests/loggen/CMakeLists.txt
- tests/loggen/Makefile.am
- tests/loggen/ssl_plugin/CMakeLists.txt
- tests/python_functional/Makefile.am
This branch contains fixes in:
* cmake build mostly detection (from testing build with freebsd)
* autotools tarball creation (missing files)
* build errors in travis-bionic (not yet fully working, but wip: https://github.com/Kokan/syslog-ng/tree/travis-bionic)
> various refactor, build issue fixes

- modules/json/format-json.c
- modules/json/format-json.h
- modules/json/json-plugin.c
- modules/json/tests/test_format_json.c
The current `$(format-json a.b.c=1)` json formatting template function created a nested json:
```json
{
"a": {
"b": {
"c": "1"
}
}
}
```
(withouth the whitespaces)
In some json parsing system cannot handle this nested-json format, as such a *flattened* json (in a sense that the keys are joined together).
With the new function `$(format-flat-json a.b.c=1)` became:
```json
{
"a.b.c": "1"
}
```
In other functionality and options the `$(format-json)` and `$(format-flat-json)` are identical.
Question:
* Is it better to have a new function name instead of a simple switch (`$(format-json --flatten)`) ?
* Should it support other than `.` separator in the keys between levels ?
> add format-flat-json template function

- modules/diskq/logqueue-disk-non-reliable.c
- modules/diskq/logqueue-disk-reliable.c
- modules/diskq/logqueue-disk.c
- modules/diskq/qdisk.c
- modules/diskq/qdisk.h
- modules/diskq/tests/test_diskq.c
- modules/diskq/tests/test_diskq_truncate.c
On 32bit platforms glong is 32bit, therefore we explicitly casted
a signed 64-bit value to a signed 32-bit value, which caused an EINVAL error
on passing a negative value to ftruncate.
> on 32bit platform diskq ftruncate could fail due to size 32/64 interface

- lib/host-id.c
- lib/host-id.h
- lib/logproto/logproto-buffered-server.c
- lib/rcptid.c
- lib/run-id.c
Work in progress. Based on @lbudai's #2862 
The main goal of the PR is to seamlessly convert old persist entries into their newer format.
WIP because: LogProtoBufferedServerState will require additional work, unfortunately we have mixing persist file and persist entry logic.
> Fix persist versions

- tests/python_functional/CMakeLists.txt
- tests/python_functional/Makefile.am
- effects only when using `make pytest-check` and `make pytest-self-check`
For now there is only one option to increase (foreground) log verbosity for Light when running through `make pytest-check` or `make pytest-self-check`. This is `PYTEST_VERBOSE` variable https://github.com/balabit/syslog-ng/blob/a6f3148ccd5b08331b43e217668f2c2c1398211d/tests/python_functional/Makefile.am#L7.
This variable (maybe not the best variable name) can enable to display internal logging records (printed with logger.info(...) or logger.error(...) ) on console. The drawback if this variable is enabled it will used on every testcase so our console will contains "everything".
There can be cases when we only need verbose logs when our tescases are failing. …
> LightVerboseLogOnError: Increase default pytest verbosity on error

- tests/python_functional/.pre-commit-config.yaml
- it was added accidentally
- until we need to support Python v2 we did not profit from it
during the linting process
> LightPreCommitConfig: Remove pyupgrade from hooks

- lib/cfg-lexer.c
- lib/cfg-lexer.h
- lib/cfg.c
- tests/python_functional/functional_tests/config_change/test_backtick_substitution.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
This partially reverts commit 1a20821af0c08c0847293fafa7387d4ef5554aaf, keeping one commit (7573d46df9be58f2c2c13cba4d27fbc7f6a44646), a feature that makes `--preprocess-into=-` use stdout.
Reading the configuration file from a memory buffer can be used to implement multi-pass preprocessing, but the implementation in #2869 is far from complete, it requires additional work and a lot of new tests:
- `YY_INPUT` (used by `_cfg_lexer__create_buffer()`) is currently line-based, and this line-based logic was actively used:
- backtick substitution (broken: #2906):
Entering a `block` flex "start condition" should disable backtick substitution. The start condition has to be detected, it's currently done after each line. This can't easily be fixed when `_cfg_lexer__scan_buffer()` is used. …
> Revert "Merge pull request #2869"

- lib/logmsg/logmsg.c
`log_msg_set_value()` contains the same invalidation logic for the legacy message header.
The same has to be done for `unset()` in order to be consistent.
For example, the legacy message header is used by `LogWriter` if no template is set, and unsetting the `PID` will not remove the `PID` field from the output:
```
rewrite { unset(value("PID")); };
Aug  2 11:11:11 test test[2222]: test
```
```
rewrite { set("" value("PID")); };
Aug  2 11:11:11 test test: test
```
More info: https://serverfault.com/questions/981150/disable-process-id-showing-in-syslog-ng-logs/981212
> Invalidate LEGACY_MSGHDR when PID or PROGRAM is unset

- modules/afsocket/afinet-dest-failover.c
- modules/afsocket/afsocket-dest.c
- modules/afsocket/afsocket-source.c
- modules/afsocket/tests/test-transport-mapper-inet.c
- modules/afsocket/transport-mapper.c
- modules/afsocket/transport-mapper.h
IP multicast detection should to be done on the destination ip,
not the bind ip, as it was erroneously done before.
Fixes #2889
> afinet: fix multicast ip detection

- lib/cfg-lexer-subst.c
- lib/tests/test_cfg_lexer_subst.c
After a quoted character, transitioning into `CLS_WITHIN_STRING` is not
enough, because another quote or "string end" character may follow.
Here is the state machine of `_track_string_state()`, the red lines were missing.
Fixes #2879
> Fix SCL block parameter substitution 

- lib/logthrsource/logthrfetcherdrv.c
- lib/logthrsource/logthrsourcedrv.c
- lib/logthrsource/tests/test_logthrfetcherdrv.c
- lib/logthrsource/tests/test_logthrsourcedrv.c
- modules/python/python-source.c
For example with diskq-source: syslog-ng crashes after a failed reload.
Example: start syslog-ng with the config below, comment out the nonexistent destination, then reload. 
After reload, syslog-ng will crash.
```
@version: 3.23
log {
source { example-diskq-source(file("/tmp/doesnotmatter.bin")); };
};
```
The root cause is that the worker in logthreaded source (and thus logthreaded fetcher) is created during new, but freed during deinit. During reload, syslog-ng calls deinit for all pipes. But if the reload fails, syslog-ng will reinitialize pipes: calling init. In the end, the same worker that was deallocated previously will be used by the source.
Delaying the construction of worker fixes the problem.
> logthrsource/fetcher: crash after failed reload

- modules/affile/affile-source.c
- modules/affile/file-reader.c
- modules/affile/file-reader.h
- modules/affile/logproto-file-reader.c
- modules/affile/logproto-file-reader.h
- modules/affile/tests/test_wildcard_source.c
- modules/affile/wildcard-source.c
This PR
- fixes the multi-line option validation when `wildcard-file()` is used (it was missing),
- adds another validation: `pad-size()` and `multi-line-mode()` are mutually exclusive options.
> Fix wildcard-file() option validation

- dbld/images/centos-7.dockerfile
- dbld/images/debian-buster.dockerfile
- dbld/images/debian-jessie.dockerfile
- dbld/images/debian-stretch.dockerfile
- dbld/images/devshell.dockerfile
- dbld/images/fedora-30.dockerfile
- dbld/images/hooks/build
- dbld/images/ubuntu-bionic.dockerfile
- dbld/images/ubuntu-cosmic.dockerfile
- dbld/images/ubuntu-trusty.dockerfile
- dbld/images/ubuntu-xenial.dockerfile
- dbld/rules
This branch annotates dbld images with the commit ID they were built with and do this both
for locally generated images (e.g. ./dbld/rules image-<whatever>) and dockerhub generated ones.
It also adds a check-image-<whatever> target that rebuilds the image conditionally, e.g. in case the dbld subdirectory has changed since the local copy. This can be used to significantly improve
CI performance if the previous image is still locally available.
> Dbld image caching

- lib/cfg.c
This patch adds a global `@define` to make it easy to locate the default syslogng sysconfdir.
requested by @rfaircloth-splunk
> syslog-ng-sysconfdir define

- dbld/deb
- dbld/functions.sh
This branch adds an explicit check to deb builds that /usr/bin/man is operational. On ubuntu a bug in apparmor may cause the man binary not to work (complaining about a missing .so file), in which case deb builds fail.
The check will display an actionable error message to the user how to fix the issue.
> dbld: warn about /usr/bin/man AppArmor bug if it is biting us

- modules/affile/affile-grammar.ym
- modules/affile/affile-parser.c
- modules/affile/tests/test_wildcard_source.c
- modules/affile/wildcard-source.c
- modules/affile/wildcard-source.h
This PR allows legacy (syslog-ng PE 6-style) configurations for the wildcard file source.
The PR contains unit tests and refactor steps, the actual support for the legacy format is **not more than ~40 lines of well-separated code**.
When using the legacy format, the following warning is shown:
> WARNING: Using wildcard characters in the file() source is deprecated, use wildcard-file() instead. The legacy wildcard file() source can only monitor up to 100 files, use wildcard-file(max-files()) to change this limit.
Examples:
```
file("/var/log/messages*");
file("/mnt/messages?.log" force-directory-polling(yes));
file("/var/log/*" recursive(yes));
```
The persist name and entry format are also compatible with PE 6.
Please do NOT document these options/this syntax.
> Accept legacy wildcard file configurations

- modules/kafka/kafka-dest-worker.c
In case the key() option is not used, we are allocating a g_malloc(1) memory
for every message that never gets freed. Although in small bites, but we
can eventually leak a large amount of memory.
Thanks to the efforts of @jbfuzier we got enough information to
troubleshoot the issue.
This should fix #2929
> kafka: fix a per-message memory leak in kafka destination

- lib/persist-state.c
We encountered an error during development, where one of the drivers
did not save the allocated persist handle, which resulted calling the
persist_state_map_entry with a 0 value.
Calling map_entry with 0 value, will result overwriting the persist file
header.
> persist-state: add g_assert to persist_state_map_entry

- lib/tlscontext.c
- lib/tlscontext.h
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
Inspired by a syslog-ng maillist request:
> Hi,
> I am using TLS over TCP connection to forward my syslog events to a remote server.
> My remote server uses SNI (Server Name Identification) to route connections/events to one of the available backend servers.
> I observe that syslog-ng doesn't send SNI during TLS handshake.
> How can I enable it?
> My configuration is as follows:
```
source s_net { syslog(transport(udp) port(1514)); };
destination d_tcp {
tcp(
"XX.example.net"
port(96)
tls(
peer-verify(required-untrusted)
ca_dir("/etc/syslog-ng/ssl")
key-file("/etc/syslog-ng/ssl/globaltest/XX.example.net.key.pem")
cert-file("/etc/syslog-ng/ssl/globaltest/XX.example.net.cert.pem")
)
);
};
log {
source(s_net);
destination(d_tcp);
};
```
> I want syslog-ng to send XX.example.net as SNI to my …
> tls: add SNI support

- Makefile.am
- cmake/add_tests.cmake
- lib/str-format.c
- lib/str-format.h
- lib/template/macros.c
- lib/tests/test_str_format.c
- lib/timeutils/format.c
- lib/timeutils/format.h
- lib/timeutils/names.h
- lib/timeutils/scan-timestamp.c
- lib/timeutils/tests/test_scan-timestamp.c
- modules/csvparser/tests/test_csvparser_perf.c
- modules/snmptrapd-parser/snmptrapd-header-parser.c
This PR contains the refactoring/performance improvements pieces of #2931 which we can merge independently of the other, where we are waiting for a 3rd party confirmation of the log format.
This branch also contains the exclusion of performance tests in "make check", reducing the time needed to run make check by 25% on my laptop. ~~This is only done for automake, cmake help would be appreciated.~~
> Timeutils refactor and performance improvements

- scl/default-network-drivers/plugin.conf
Allows to passthrough max-connections parameter to the network tcp source.
The default value of 10 connections is very limiting.
> scl/default-network-drivers: add max-connections

- README.md
#2962 There is actually two ways to correct the README.md:
- change the quickstart quide link to https://www.syslog-ng.com/technical-documents/list/syslog-ng-open-source-edition/ so that this link is correct for all future versions (by the way, it would be good to rename quickguide to technical documentation),
- change the quickstart guide link to https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.23/administration-guide/11#TOPIC-1268425 so that it is directly linked to what is expected, however, this must be changed for every new version.
Resolves #2962
> Updated Quickstart link

- CONTRIBUTING.md
- README.md
- lib/str-utils.c
- modules/java/Makefile.am
- packaging/debian/copyright
- packaging/debian/watch
- packaging/rhel/syslog-ng.spec
- scl/system/plugin.conf
- tests/valgrind/unit-test-leak.supp
> balabit/syslog-ng -> syslog-ng/syslog-ng transition

- dbld/images/devshell.dockerfile
docker seems to prefer the ENV value inherited from the base image (specified
using FROM) over the value in the command line, thus even though
dbld/rules specifies "--build-arg OS_PLATFORM", its value does not
make it to the Dockerfile.
Since the devshell is special in any case (using the bionic image as its
base), override OS_PLATFORM via a hard-wired value, fixing the package
installation.
This patch also removes redundant ENV/LABEL commands from the Dockerfile, as
all of those are already inherited from the parent image.
> dbld: fix OS_PLATFORM value in devshell images

- lib/logmsg/logmsg.c
In case it's left uninitialized, the message could seem as having a pri LOG_KERN | LOG_EMERG.
This is only interesting, if a user would like to create a log message, but without initial parsing,
thus log_msg_new() is not suitable, as that needs a format_handler, e.g. syslog.
Currently this is done by log_msg_new_empty(), which is used by some drivers, but they are not setting
PRI fields.
> logmsg: add default PRI value to log_msg_init

- tests/python_functional/conftest.py
- tests/python_functional/functional_tests/conftest.py
- tests/python_functional/src/common/pytest_operations.py
- tests/python_functional/src/conftest.py
- tests/python_functional/src/testcase_parameters/testcase_parameters.py
Motivation:
There was an incorrectly used pytest object in pytest_runtest_setup() hook: `item._request`
This is not a public object and it can cause a pytest error in some circumstances.
> LightPytestRuntestSetupHook: Refactor pytest_runtest_setup() hook

- scl/telegram/telegram.conf
After fixing the SCL parameter substitution in #2901, the Telegram destination has stopped working.
The type of the `use-system-cert-store()` option should be `yes/no`, strings are not accepted.
> Fix syntax error in telegram()

- contrib/valgrind/syslog-ng.supp
- lib/cfg-lexer.c
- lib/cfg.c
- lib/cfg.h
- lib/plugin.c
- lib/plugin.h
- lib/pragma-grammar.ym
- lib/template/tests/test_template_compile.c
- lib/tests/test_lexer.c
- persist-tool/persist-tool.c
The `@requires` statement should only be a declaration that the specific include file relies on
the availability of a specific plugin. We shouldn't necessarily load it as it might actually be unused.
Also, by loading it we are triggering ugly messages during startup (the kind that some plugins are registered multiple times).
This branch now properly handles the ordering between plugin discovery and the `@requires` keyword. It removes some old cruft.
> avoid `@requires` loading the plugins themselves

- modules/affile/affile-grammar.ym
- modules/afstomp/afstomp.c
- modules/afstomp/stomp.c
- modules/afstomp/tests/test_stomp_proto.c
- modules/examples/sources/threaded-random-generator/threaded-random-generator.c
- modules/pseudofile/pseudofile.c
This PR contains 4 fixes for bugs we've found with property-based testing method (using Light).
3 of them are trivial; the 4th (stomp() patch) fixes some buffer overrun issues that can be triggered remotely with suitably crafted input.
There are 3 more, but they deserve a separate PR as they are not that trivial.
> Light property based test fixes

- lib/logmatcher.c
- lib/logmatcher.h
- tests/unit/test_matcher.c
logmatcher: allow the user to disable PCRE JIT using the disable-jit flag
this should resolve #2986 at least the normal filter() case. the same in multi-line(regexp) support is not this trivial.
**EDIT**:
config examples
```
rewrite r_demo {
subst("a+" "b" value(".extra.info") flags("disable-jit"));
};
filter f_demo {
host("internal-.*" flags("disable-jit"));
};
```
> Add disable jit flag to logmatcher

- .travis.yml
Not Arm related change: replaces *gradle* fixed version with the latest.
Add basic build and Ut execution for amr64 platform.
Note: due to lack of Criterion arm64 package, this job builds Criterion locally. As it was relativly quick (~70 second) to build from zero and the overall job was not the slowest. I avoided adding Criterion build cache.
> extend travis build with arm64

- contrib/systemd/syslog-ng@.service
- packaging/debian/syslog-ng.systemd
- packaging/rhel/syslog-ng.service
fix #2667
See the discussion in the issue.
Both option allows Syslog-ng to start even if the network service is not configured or failed to start.
Before: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Before=
Wants: https://www.freedesktop.org/software/systemd/man/systemd.unit.html#Wants=
> packaging: add ordering dependencies to the service files

- configure.ac
- lib/ack-tracker/bookmark.h
- lib/ack-tracker/late_ack_tracker.c
- lib/logsource.c
- lib/logsource.h
- lib/tests/CMakeLists.txt
- lib/tests/Makefile.am
- lib/tests/test_logsource.c
This PR improves the test coverage of `LogSource`. Now only `_flow_control_rate_adjust()` is untested.
Unfortunately, these are not clean unit tests, there is a `TestPipe` object, for example, that emulates the destination queue/message acks. This would be eliminated if we could mock out a few things.
Because I measured the test coverage, I also removed unreachable and unused code, etc.
> Improve LogSource's test coverage

- modules/python/python-helpers.c
Sometimes exception reporting is called even when no exception has
happened.
For example when the python class is not found: 
While searching for python class, the code simply calls
getattr, which does not generate exception, just returns null.
In those cases python destination emitted this unnecessarily.
```
[2019-11-04T09:18:44.079993] Error printing proper Python traceback for the exception, printing the error caused by print_exception() itself;
SystemError: NULL object passed to Py_BuildValue
```
This patch makes this function no-op if no exception happened.
> fix python exception reporting when no exception happened

- lib/logsource.c
- lib/logsource.h
This reverts commit 289408b3caa83613ab1b6f2fceaca7a36ec17e0f.
The wakeup function is not completely private, it is used internally by `LogProtos`, so I should not have made it static.
Sorry about that, I was concentrating on the unit test (#2980).
> Revert "logsource: make log_source_wakeup() private"

- modules/confgen/confgen-plugin.c
Previously, when a confgen parameter was empty, syslog-ng crashed in a null-pointer dereference.
Adding an empty parameter (e.g. `parameters()`) does not make sense, but passing `__VARARGS__` to the confgen script is a real use-case, and `__VARARGS__` can be empty.
This PR fixes SCLs, such as the `network-load-balancer()`, where `__VARARGS__` is passed to the confgen script as a parameter:
https://github.com/syslog-ng/syslog-ng/blob/a72580ee65641e8f096958605a2834a346d38128/scl/loadbalancer/plugin.conf#L23-L31
Reproduction:
```
destination d_test {
network-load-balancer(targets(2));
};
```
> confgen: fix crash when parameter is empty

- modules/python/python-fetcher.c
These constants did not work because their value is overlapped with success, due to a copy paste error.
> python-fetcher: fix FETCH_NO_DATA and FETCH_TRY_AGAIN constants

- syslog-ng-ctl/CMakeLists.txt
- syslog-ng-ctl/Makefile.am
- syslog-ng-ctl/commands/commands.c
- syslog-ng-ctl/commands/commands.h
- syslog-ng-ctl/commands/config.c
- syslog-ng-ctl/commands/config.h
- syslog-ng-ctl/commands/credentials.c
- syslog-ng-ctl/commands/credentials.h
- syslog-ng-ctl/commands/ctl-stats.c
- syslog-ng-ctl/commands/ctl-stats.h
- syslog-ng-ctl/commands/license.c
- syslog-ng-ctl/commands/license.h
- syslog-ng-ctl/commands/query.c
- syslog-ng-ctl/commands/query.h
- syslog-ng-ctl/commands/verbose.c
- syslog-ng-ctl/commands/verbose.h
- syslog-ng-ctl/syslog-ng-ctl.c
This patch splits syslog-ng-ctl.c into smaller compilation units. That makes easier to add new commands.
From functional point of view, nothing should change.
> syslog-ng-ctl: refactor - split into many files

- lib/versioning.h
- modules/python/python-dest.c
Fixes: https://github.com/syslog-ng/syslog-ng/issues/2513.
Although the admin guide tells users to set the return value of open properly, the code does not check that. Instead, there is an is_opened method that was used to answer:
- if the driver is open
- In some cases, if the last open was successful or not.
This architecture makes users write unnecessary complex code, since the open-ness must be stored and updated as side-effects.
For example this does not do what one would expect, because it sends message even though open returns with false.
<details>
```
@version: 3.24
log {
source { example-msg-generator(num(1)); };
destination { python(class(PythonDest)); };
};
python {
class PythonDest(object):
def open(self):
return False
def send(self, message):
print("sending message")
return …
```
> python-dest: actually use return value of open method

- configure.ac
On Unix, C extensions are no longer linked to libpython.
They've added a pkg-config `python-3.8-embed` module to embed Python into an application: `pkg-config python-3.8-embed --libs` includes `-lpython3.8`.
> To support both 3.8 and older, try pkg-config python-X.Y-embed --libs first and fallback to pkg-config python-X.Y --libs (without --embed) if the previous command fails.
> configure: add Python 3.8 detection

- contrib/syslog-ng-debun
* version bump
* updated copyright information
* added option and functionality to save private keys
(upon express request via a CLI option (-K))
* the script now removes Splunk auth tokens from the
config by default
* minor rework on the running config collection
* added CLI option to override tcpdump CLI options
* print a warning if SELinux is in enforcing mode
* added support for gathering the installed SCL include files
* added options for cpio to dereference symlinks when copying
* fixed cpio related portability problems
* added support for gathering WEC PID and lsof information
* fixed ps related portability issues
* the script now gathers statistics at the beginning and end
of the debug session
> syslog-ng-debun: maintenance updates and small fixes

- lib/cfg-tree.c
Fixes: https://github.com/syslog-ng/syslog-ng/issues/2820
Any destination after an inline network destination driver does not handle messages.
The root cause of the issue was that afsocket overwrites its `pipe_next` field with its own writer. Previously, `pipe_next` was pointing to the rest of the config graph. Essentially distjointing the config after the inline network driver. The problem only happens with network driver, and only when the network was inline. Some additional info can be found in #2820.
For example:
```
@version: 3.24
options {
time-reopen(5);
};
destination d_network {
network("127.0.0.1" port(4448) );
};
log {
source { example-msg-generator(); };
destination { network("127.0.0.1" port(4447) ); };
destination(d_network);
flags(flow-control);
};
```
Explanation of the …
> cfg-tree: inline network destinations disjoint the rest of the config

- lib/transport/logtransport.h
- lib/transport/transport-file.c
- libtest/mock-transport.c
- libtest/mock-transport.h
- libtest/tests/test_mock_transport.c
- modules/affile/logproto-file-writer.c
- modules/affile/tests/CMakeLists.txt
- modules/affile/tests/Makefile.am
- modules/affile/tests/test_file_writer.c
- tests/copyright/policy
As discussed in #2887 due to a failing testcase the file destination was pretty optimistic on when to acknowledge a message back, even though the entire infrastructure is now in place to do it somewhat later.
This branch does exactly that, instead of acking the message in log_proto_client_post(), we do it once write() acknowledged that it wrote the message. This combined with fsync() we can really be sure that the buffer embedded in LogProtoFileWriter will not hold messages that are not yet written but are acknowledged to the source.
I think some refactorings are heavily needed here, I am just wondering what @kira-syslogng thinks about the patch.
The branch also improves testing in this corner of the codebase.
> Affile delay acks until messages written to disk

- modules/http/http.c
The template optinos default value should be the value of global template options.
In case of http destination inheriting the global options was not possible,
as the mechanism relies on:
* First calling the *log_template_options_defaults* setting external values
indicating nobody configured those fields.
* Processing the grammar rules (potentially values are overwritten)
* Initializing the template values with *log_template_options_init*
(either using the global value, if the initial external value left, or keeping
the configured value)
The *log_template_options_defaults* was missing, as a result all of the template
options defaulted to zero in case of http destination driver.
> http destination ignores global template options values

- contrib/Makefile.am
- contrib/scripts/config-graph-json-to-dot.py
- lib/CMakeLists.txt
- lib/Makefile.am
- lib/cfg-tree.c
- lib/cfg-walker.c
- lib/cfg-walker.h
- lib/logmpx.c
- lib/logpipe.c
- lib/logpipe.h
- lib/logwriter.c
- lib/mainloop-control.c
- syslog-ng-ctl/syslog-ng-ctl.c
This patchset intends add supporting code so that users could visualize configuration graph. The results could be used for debugging.
Usage:
- Generate config graph from a running syslog-ng instance using syslog-ng-ctl
```
./syslog-ng-ctl export-config-graph
```
Optional:
- Use a newly added script in contrib to convert json to dot format. Then you can create a png, pdf or your preference (paths may differ for you):
```
rm tmp.png; ./syslog-ng-ctl export-config-graph | ../../syslog-ng/contrib/scripts/config-graph-json-to-dot.py | dot -Tpng -o tmp.png && xdg-open tmp.png
```
---
The idea is simple: logpipes will be nodes, arcs will be connections either through multiplexer (`next_hop`) or `pipe_next`. The walk starts from `cfg->initialized_pipes`. Anything that does something with message …
> visualize config graph

- modules/python/python-fetcher.c
- modules/python/python-global-code-loader.c
- modules/python/python-helpers.c
- modules/python/python-helpers.h
- modules/python/python-logger.c
- modules/python/python-source.c
According to documentation:
https://docs.python.org/3/c-api/typeobj.html#c.PyTypeObject.tp_dealloc
If the type is subtypeable, then tp_free must be called. 
The invalid deallocator causes memory corruption, which eventually
leads to crash.
Reproduce: busy reload loop on this configuration:
```
@version: 3.24
log {
source { python-fetcher(class(PythonFetcher)); };
};
python {
from syslogng import LogFetcher
class PythonFetcher(LogFetcher):
def fetch(self):
return LogFetcher.FETCH_NO_DATA, None
};
```
> python-source: fix memory corruption during reload

- configure.ac
- tests/loggen/CMakeLists.txt
- tests/loggen/Makefile.am
- tests/loggen/loggen.c
Loggen plugin path was set by compile time. This was a problem when the user wants to install loggen into other directory then the default path.
This PR solves this issue by the reloc API to determine the syslog-ng (loggen) install path by run-time
In case of none standard installation methode, the user can set the SYSLOGNG_PREFIX envvar.
> Loggen plugin path

- configure.ac
- lib/reloc.c
The loggen plugin dir should follow `moduledir`, which can be set, for example, with the `--with-module-dir` configure option.
#3019 changed this behavior, to make the run-time relocation of loggen work, but this way the loggen plugin directory does not depend on `moduledir` anymore.
This PR fixes the problem.
In order not to break the loggen relocation, `${moduledir}` has to be added to the relocation API, so paths containing `${moduledir}` can be resolved correctly with `get_installation_path_for()`.
Fixes #3023
> Fix loggen plugin directory when `--with-module-dir` is used

- modules/affile/affile-dest.c
- modules/affile/affile-grammar.ym
- modules/affile/affile-source.c
- modules/affile/affile-source.h
- modules/affile/file-opener.c
- modules/affile/named-pipe.c
- modules/affile/named-pipe.h
Fixes #2635 
**Added create_dirs() option to pipe() source**:
Pipe source creates the FIFO where it will read, thus it should be able to create the path as well.
Previously file/pipe sources created the directories (due to a bug), and it was impossible to disable directory creation.
About file source: it does not need the option create-dirs(), as it will poll the path, and it shouldn't create the directories since that is the job of the destination (the one who writes into the file).
Unix-dgram() and unix-stream() dest. drivers does not need create_dirs() option: Even if they could create the directories, they couldn't connect to a not existing socket anyway.
Other changes:
- pipe()/file() source created directories by default, and it was impossible to disable it (global option did not …
> create_dirs: some cleanup

- lib/logproto/logproto-client.h
- lib/transport/transport-tls.c
syslog-ng does not call `SSL_connect()` or `SSL_do_handshake()`, so the first `SSL_read()` or `SSL_write()` call is responsible for negotiating the TLS session. Nevertheless, the initial IO `cond` should be `0`, because the `LogProto` layer should choose the initial IO direction.
In case TLS renegotiation is required, OpenSSL returns an error (`SSL_ERROR_WANT_READ` or `SSL_ERROR_WANT_WRITE`). In this case, the same read/write function must be invoked after a IO readiness notification.
With all that being said, the initial `G_IO_IN | G_IO_OUT` transport-level IO-cond is not necessary and even harmful:
If the connection is lost in a TLS destination before sending the first message, an infinite IO loop starts in the main thread. This is because ivykis reports readiness for reading, but we …
> Fix infinite loop when a TLS connection breaks

- contrib/config_option_database/config_database.py
---
`config_database: add option to list contexts and drivers`
New usage:
* `./config_database.py`: print contexts
* `./config_database.py -c CONTEXT`: print drivers of CONTEXT
* `./config_database.py -c CONTEXT -d DRIVER`: print options of DRIVER
---
`config_database: support driver name aliases`
From now on the `pipe` `source` will be accessible as:
* `config_database.py -c source -d pipe`
* `config_database.py -c source -d fifo`
instead of only:
* `config_database.py -c source -d fifo/pipe`
---
Change this:
```
tls()
tls(
ca-dir(<string>)
peer-verify(<string>)
peer-verify(<yesno>)
)
```
to this:
```
tls(
<empty>
ca-dir(<string>)
peer-verify(<string> | <yesno>)
)
```
> config_database: various features/formatting fixes

- dbld/Makefile.am
- dbld/functions.sh
- dbld/images/centos-6.dockerfile
- dbld/images/helpers/dependencies.sh
- dbld/images/helpers/packages.manifest
- dbld/images/helpers/pip_packages.manifest
- dbld/rules
- packaging/rhel/syslog-ng.spec
Just recently someone was trying to compile/run syslog-ng on RHEL6, so albeit I've dropped support
for it in dbld, it is still in use. So I've decided to go back and understand why I've felt that it was so difficult to support. With our glib compat code, it turned out not that difficult, even though we had a lot of warnings.
~~With warnings fixed, this actually improves the code, so here it comes as a PR.~~ I've added the bits independent of centos6 into a separate PR #2971.
~~This depends on #2859 so putting it into WIP until that one is merged.~~
Now all dependencies are in, so this is also ready to go in.
> Dbld readd centos6 support

- modules/http/http-worker.c
- modules/http/response-handler.c
- modules/http/tests/test_http-response_handlers.c
- modules/http/tests/test_http.c
- tests/copyright/policy
This changeset contains fixes left out from https://github.com/syslog-ng/syslog-ng/pull/3007.
Two  notable changes
- The default action for 409 is changed from retry to disconnect.
As I received an offline comment from @gaborznagy, users might resolve the conflict. The problem is not with the message itself. So we should avoid dropping it.
- The error messages contained wrong url, when the response did not return with 2XX code. Actually this is not a regression from #3007, still I wanted to fix.
----
#
> response-handler: leftover fixes

- .github/workflows/macos.yml
- .travis.yml
Also remove the same job from Travis.
With this commit, the macOs build time reduces from ~20 mins to ~8 mins, and gets separated from all the Travis jobs. 
All our jobs finish under 10 minutes now :)
> github-actions: add macOS-latest/build-and-check

- lib/cfg-lex.l
- lib/tests/test_lexer.c
- modules/affile/tests/test_wildcard_source.c
Syslog-ng has a (not well documented) feature to accept strings
without quotation marks. One of the key benefit of this feature
is that we do not need to put identifiers (i.e.: block names)
into quotation marks. Which makes the config much more readable.
We achieve this by an internal lookup. After Flex successfully
identified a "word" (for details, please investigate the rule
inside the lexer file), we will search for it in the list of
known keywords. If there is no match, we will handle that token
as a string.
Flex - by design - ignores inputs without matching patterns.
(Writes them on standard error, and continues parsing.)
Right now, if a single dot "." character do not breaks an another
pattern (i.e. order of keywords or parentheses) inside the lexer,
it will be silently ignored. …
> Handling single dots in lexer

- lib/timeutils/scan-timestamp.c
- lib/timeutils/scan-timestamp.h
- lib/timeutils/tests/test_scan-timestamp.c
Only the first two letter were checked in month (Jan, Feb, ...) and days (Mon, Fri) as they are sufficient to differentiate valid months, days from each  other.
> timeutils: fix month, day name parsing

- modules/redis/redis-grammar.ym
- modules/redis/redis-parser.c
- modules/redis/redis.c
- modules/redis/redis.h
UPDATE:
Dropped the batching part due to problems with message tracking in case of connection errors, but I thought it would be nice to include the rest of the refactors in the next release.
The reduced number of  `redis_dd_connect` calls still gives us a decent speed improvement. (~20k according my measurements)
- added timeout() option for amqp. This adds a timeout for the blocking socket operations.
----------
Add **batch-lines** support for the Redis driver. Redis API calls it pipelining: https://redis.io/topics/pipelining
Also:
- Thanks for @Kokan, some performance improvement with template handling.
- Put `_argv_to_string` behind `debug_flag`, because it has a high performance impact.
- Removed an extra `check_connection_to_redis` call from the insert call chain. (Since it requires …
> Improve Redis driver connection handling

- NEWS.md
PRs left out:
response-handler: leftover fixes. #3032
github-actions: add macOS-latest/build-and-check #3031
config_database: various features/formatting fixes. #3022
Light: SyslogNgConfig refactor part 1 #3021
astyle: add padding around spaces #3013
syslog-ng-ctl: refactor - split into many files #3006
Revert "logsource: make log_source_wakeup() private" #3001
travis: test cmake + ninja combination #2987
Improve LogSource's test coverage #2980
LightPytestRuntestSetupHook: Refactor pytest_runtest_setup() hook #2973
dbld: fix OS_PLATFORM value in devshell images #2970
Updated Quickstart link #2968
balabit/syslog-ng -> syslog-ng/syslog-ng transition #2943
Dbld jenkinsfile #2859
> NEWS: version 3.25

- lib/scanner/list-scanner/list-scanner.c
- lib/scanner/list-scanner/list-scanner.h
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/list-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
Returns with the index of the first match of `keyword` in the `list`.
Starts the search at `start_index`. 0 based. If not found, returns empty string.
New usage:
* Literal match:
`$(list-search <pattern> ${list})`
or
`$(list-search --mode literal <pattern> ${list})`
* Prefix match: `$(list-search --mode prefix <pattern> ${list})`
* Substring match: `$(list-search --mode substring <pattern> ${list})`
* Glob match: `$(list-search --mode glob <pattern> ${list})`
* Regex match: `$(list-search --mode pcre <pattern> ${list})`
Add `--start-index <index>` to change the start index.
Implements #2924
TODO:
> basicfuncs: add list-search function

- tests/loggen/loggen_helper.c
This is a fix for the same problem that #2933 resolves in syslog-ng.
The PR fixes a small memory leak as well.
> When AI_ADDRCONFIG is used, then IPv4 addresses are returned in the list
pointed to by res only if the local system has at least one IPv4 address
configured,  and  IPv6 addresses  are  returned only if the local system
has at least one IPv6 address configured. The loopback address is not
considered for this case as valid as a configured address.
> This flag is useful  on,  for  example,  IPv4-only systems, to ensure
that getaddrinfo() does not return IPv6 socket addresses that would
always fail in connect(2).
Retrying an unsuccessful resolution without `AI_ADDRCONFIG` is necessary because `::1` or `127.0.0.1` might not be resolved when the `AI_ADDRCONFIG` flag is set. …
> Improve name resolution in loggen

- dbld/rules
There was a discussion about removing the rm parameter from the shell
target. Thank you all for sharing your opinion in the topic! (See #2982)
With this patch you can override the shell command in your rules.conf file,
so everyone can have their own version of it.
my rules.conf for example (copied from the earlier PR):
```
DOCKER_SHELL=$(DOCKER) inspect $* > /dev/null 2>&1; \
if [ $$? -eq 0 ]; then \
$(DOCKER) start -ia $*; \
else \
$(DOCKER) run $(DOCKER_RUN_ARGS) -ti --name $* balabit/syslog-ng-$* /source/dbld/shell; \
fi
```
Question for the reviewers:
Is there any other target which could benefit from this approach?
> dbld: make the shell command customizable

- packaging/rhel/syslog-ng.spec
Tcp wrappers were removed from Fedora and RHEL 8.
Make sure, that only RHEL 7 requires it.
> packaging: add RHEL 8 / CentOS 8 support to syslog-ng.spec

- .travis.yml
The ARM build used the bleeding criterion, where the cmake build is broken (switched to meson).
As I do not see any CI or instruction for meson with Criterion, it is better to stick to the released version.
(This was the plan, that as soon as "master" breaks, switch to something fix.)
> travis/arm: fix criterion version

- contrib/config_option_database/syslog-ng-cfg-db.py
- contrib/config_option_database/utils/BisonGraph.py
- contrib/config_option_database/utils/ConfigOptions.py
- contrib/config_option_database/utils/MergeYm.py
- contrib/config_option_database/utils/test/test_BisonGraph.py
- lib/cfg-grammar.y
---
`process parsers`
* valid drivers are:
```
$ ./syslog-ng-cfg-db.py -c parser
Drivers of context "parser":
add-contextual-data
csv-parser
date-parser
db-parser
geoip2
grouping-by
json-parser
kv-parser
linux-audit-parser
map-value-pairs
python
snmptrapd-parser
syslog-parser
tags-parser
xml
Print the options of DRIVER with `--context parser --driver DRIVER`.
```
---
`support inner_source/dst`
* Process `diskq` and `hook-commands` inside sources or destinations.
> config_database: speed improvement, new features

- modules/geoip2/geoip-parser-grammar.ym
- modules/geoip2/geoip-parser.c
- modules/geoip2/tests/test_geoip_parser.c
Opposed to parsers that by default uses `MESSAGE` and that could be further specialised with `template()` options, the `geoip2` always uses `template`. That is enforced with the grammar rule always requiring a template in a form of string: `geoip2("template-format")`.
The PR includes the following changes:
* Extend the `geoip2` grammer with general `parse_opt` rules (currently only includes `template()`
* In init phase enforces the existence of `template`
* Changed UT according to always using `template()` opposed to using `MESSAGE` field, that works for any parser, but never actually used in case of `geoip2`
As a results both are possible configuration option:
```
geoip2("$HOST");
geoip2(template("$HOST"));
```
> geoip2: extend with template option

- modules/snmp-dest/snmpdest-grammar.ym
- modules/snmp-dest/snmpdest.c
- modules/snmp-dest/snmpdest.h
- modules/snmp-dest/tests/test_snmp_dest.c
Original code accepted only 10 character long hexadecimal values.
Checked the snmp library and the RFC, we should accept any hexadecimal
number between 5 to 32 characters.
To validate it, moved the checking part from the grammar into the
snmpdest_dd_set_engine_id function, and wrote tests against it.
> snmp adjust engineid length

- tests/loggen/CMakeLists.txt
This PR fixes an openssl dependency problem that only affects loggen, only when compiled with cmake, and openssl is installed on nonstandard location.
One can reproduce a compile error with the following: openssl 1.0.2 is installed on system (for example using ubuntu-xenial), openssl1.1.1 installed on nonstandard location, that is fed to syslog-ng by exporting `PKG_CONFIG_PATH` to the openssl pc file directory.
`loggen_helper` is intended to be a library. It contains openssl related code. Hence it needs to link to openssl. But in cmake, we do not add link target explicitely, it links only transitively to openssl.
During compiling `test_loggen_filereader`, we link only to `loggen_helper`, that only
transitively links to openssl. This means it will link to openssl1.1.1, but will use 1.0.2 …
> loggen: fix dependency error with cmake + openssl from nonstandard location

- tests/loggen/CMakeLists.txt
When syslog-ng is built with automake, it ships `loggen_helper.h` and `loggen_plugin.h`.
Now, cmake also installs these headers.
> loggen: cmake: install dev headers

- lib/tlscontext.c
- lib/tlscontext.h
- modules/http/http.c
This patch set allows to use TLS v1.3 protocol version in TLS contexts and in ssl_version() option 
- ssl_version() option has been expanded with "tlsv1_3" value
- with this value syslog-ng can force using TLS v1.3 protocol with server
```
http(
url("https://localhost:8081") 
ssl_version("tlsv1_3")
)
```
- ssl_option() option has been expanded with "no-tlsv13" value
- with this value syslog-ng can disable TLS v1.3 protocol usage
```
network(
"172.16.177.147" port(6514)
transport("tls")
tls(
ca-dir("/etc/syslog-ng/ca.d")
key-file("/etc/syslog-ng/cert.d/clientkey.pem")
cert-file("/etc/syslog-ng/cert.d/clientcert.pem")
ssl-options(no-tlsv13)
)
);
```
> Openssl: Allow to disable TLSv1.3 and force using TLSv1.3 in configuration options

- lib/rewrite/rewrite-expr-grammar.ym
The `rewrite_template_content` could be replaced with the rule in `cfg-grammar` `template_content`, despite they are not the same.
The `template_content` supports type-hinting, and with this change the rewrite rules will do so.
> rewrite: simplify grammar with using common template_content

- modules/diskq/dqtool.c
- news/bugfix-3069.md
- tests/loggen/loggen_helper.h
> loggen, dqtool: use g_path_get_basename() instead of basename()

- doc/Makefile.am
- doc/man/persist-tool.1.xml
While preparing the Debian packages for 3.25.1, it was discovered that persist-tool is without a manual page. The xml file was recovered from the docbook versions of the OSE documentation.
btw: the way manual pages are maintained/taken back from the documentation tree is currently broken. That is not addressed by this branch.
> doc/man: add manual page for persist-tool

- tests/loggen/loggen.c
- tests/loggen/loggen_helper.c
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
The main goal of this PR is to make loggen work with TLS 1.3 correctly.
We've noticed that not all of the messages that loggen sent were read by syslog-ng.
More info:
openssl/openssl#6904
----
> TLSv1.3 sessions are not established during the main handshake.
> Instead, after the main handshake is complete, a server may send some
> NewSessionTicket messages to the client.
If a client sends messages and then closes the connection immediately
without reading any NewSessionTickets from the server, the server may
not read the messages that were already sent by the client.
This issue has been fixed in openssl/openssl#6944,
but a full TCP shutdown is still required to make the server read the data.
> Fix TLS 1.3, memory leaks, and race condition in loggen

- lib/compat/getent.h
The actual functions look like this:
```
#define getprotobynumber_r _compat_sun__getprotobynumber_r
/* From getent-sun.h */
/* From netdb.h (Solaris type) */
struct protoent *getprotobyname_r(const char *name,
struct protoent *result, char *buffer,
int buflen);
/* End from netdb.h */
int _compat_sun__getprotobynumber_r(int proto,
struct protoent *result_buf, char *buf,
size_t buflen, struct protoent **result);
/* End from getent-sun.h */
```
The signature are different in the 2 functions, and that is what we are fixing in the `compat` layer. We would like to use the `_compat_sun__getprotobynumber_r()` signature for `getprotobynumber_r()`.
`_compat_sun__getprotobynumber_r()` itself is just a wrapper:
```
int
_compat_sun__getprotobynumber_r(int proto,
struct protoent *result_buf, char *buf, …
```
> compat/getent: fix compile error on solaris

- scl/checkpoint/plugin.conf
- tests/python_functional/functional_tests/parsers/checkpoint/test_checkpoint.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
Fixes #3055 
If the timestamp was in iso format, the `HOST, PROGRAM, PID, MSGID, MSG` values were shifted.
> checkpoint parser: fix parsing in case of iso timestamp

- lib/logproto/logproto-buffered-server.c
The reproduction steps are the following:
* Add a simple file source (default configuration everything)
* Send a larger message than the default log-msg-size
* syslog-ng correctly split that message (and everything works as expected)
* Change log-msg-size (insert a msg size that now larger then the sent large message before)
* Reload or Restart syslog-ng
* Send the large message again
Before this patch syslog-ng cannot process the messages from this file.
The persist file in fact stores the log-msg-size, and it is not possible to change for a file source even in case of restart.
A proposed solution is simply increasing the buffer, and updating internal buffer size so it can accommodate the bigger message size.
> Fix file source not able to process new message after log-msg-size increase

- lib/pragma-grammar.ym
- scl/elasticsearch/elastic-http.conf
- scl/elasticsearch/elastic-java.conf
- scl/slack/slack.conf
- scl/telegram/telegram.conf
This is a continuation of #2979 to improve error messages if an installed SCL is missing a dependency.
With these changes we are going to have this as an error message if we are using elasticsearch-http() without the http() module present:
```
[2019-11-14T21:18:09.766325] Cannot load required module; module='http', details='The http() driver is required for elasticsearch-http(), please install syslog-ng-mod-http (Debian) or syslog-ng-http (RHEL) package', location='etc/syslog-ng-elastic.conf:7:16'
Error parsing log statement, syntax error, unexpected LL_ERROR, expecting '}' in block destination elasticsearch-http() at /install/share/syslog-ng/include/scl/elasticsearch/elastic-http.conf:24:4:1-5:1:
1       
2       #Start Block block destination elasticsearch-http() at …
```
> Requires with error message

- tests/commits/check.sh
Our commit-check script is still too strict.
This pattern failed on commit-check due to the space between elements:
'lib, modules: don't use numeric version identifiers'
From now on, even these are supported:
'lib,    modules,	: fixup'
"li b, ,modules: fixup"
I would prefer a more relaxed commit-check,
as the basic motivation for commit-check was to enforce this pattern:
`modulename: short description of the commit`
I dedicate this PR to the failed Travis job of #3074  :+1:
> commit-check: support whitespaces around commas

- lib/CMakeLists.txt
- lib/Makefile.am
- lib/logpipe.c
- lib/logpipe.h
- lib/signal-slot-connector/CMakeLists.txt
- lib/signal-slot-connector/Makefile.am
- lib/signal-slot-connector/signal-slot-connector.c
- lib/signal-slot-connector/signal-slot-connector.h
- lib/signal-slot-connector/tests/CMakeLists.txt
- lib/signal-slot-connector/tests/Makefile.am
- lib/signal-slot-connector/tests/test_signal_slots.c
- tests/copyright/policy
The concept is simple:
* there is a `SignalSlotConnector` which stores `Signal` - `Slot` connections
* `Signal` : `Slot` = `1` : `N`, so multiple slots can be assigned to the same `Signal`
* when a `Signal` is `emitted`, the connected `Slots` are executed
* `Signals` are strings and each module can define its own signals
* Interface/protocol between `signals` and `slots`
* A macro (`SIGNAL`) can be used for defining signals as string literals:
`SIGNAL(module_name, signal, signal_parameter_type)`
The parameter type is for expressing a kind of contract between signals and slots.
usage:
```C
#define signal_cfg_reloaded SIGNAL(config, reloaded, GlobalConfig)
```
the generated literal:
```C
"config::signal_reloaded(GlobalConfig *)"
```
* `emit` passes the argument to the slots connected to the …
> Signal slot connector

- configure.ac
- modules/http/CMakeLists.txt
- modules/http/http-grammar.ym
- modules/http/http.c
- modules/http/http.h
Some `ssl-version` options were not accepted by http destination, even though they should have been:
- tlsv1_0
- tlsv1_1
- tlsv1_2
- tlsv1_3
The reason was that the used compiler switches did not exist. They were an enum instead.
Hence the relevant code was disabled.
The previous behaviour was that syslog-ng starts no matter what was the `ssl-version`, just emit a warning if something unexpected is detected.
This patch fixes:
- The compiler switches
- Syslog-ng will not start if invalid `ssl-version` string was added.
This latter might break some existing configuration: if users accidentally mistyped the option, syslog-ng will not start. I think this is acceptable, considering, this options specifies the minimum version of used ssl version, and thus might have security impact.
> http: fix curl ssl version

- scl/elasticsearch/elastic-java.conf
It was `java` instead of `mod-java`. Also the `requires` on the top is not needed now.
> elasticsearch-java: fix `requires` in scl

- COPYING
Maintaining the list of modules licensed under LGPL-2.0-or-later (along with `tests/copyright/policy`) is error-prone.
For example, we forgot to add certain units from the Python language binding, appmodel, basicfuncs (tf-template), and http-signals.
Instead of maintaining this list, I've rephrased the license text to express our original intention:
```diff
-modules/ subdirectory except the ones mentioned above)
+modules/ subdirectory except the ones that declare LGPL-2.1-or-later
+in their license notices
```
I've also listed  `syslog-ng-ctl`, `persist-tool`, and `loggen` as `LGPL-2.1-or-later`; and `scl/` subdirectories as `GPL-2.0-or-later` (with the above exception).
@bazsi Is this acceptable?
> Rephrase COPYING

- lib/Makefile.am
- lib/list-adt.h
- modules/http/CMakeLists.txt
- modules/http/Makefile.am
- modules/http/http-curl-header-list.c
- modules/http/http-curl-header-list.h
- modules/http/http-signals.h
- modules/http/http-worker.c
- modules/http/http-worker.h
- tests/copyright/policy
This PR defines the Signal interface for HTTP - with one signal at this time, but before continue the work, I'd need review to the signal-slot concept (see #3043)
What's in the PR?
* List ADT (abstract data type for list implementations) added to `lib`. 
Interface:
*  `append`
*  `foreach`
*  `is_empty`
*  `remove_all`
* Implement the List ADT in http module with `struct curl_slist` for storing the headers.
* HTTP signal(s):
Currently only one signal is added, `header_request`.
Note, that the  license for `http-signals.h` is _LGPL_ .
> Signal slot connector http

- modules/http/CMakeLists.txt
- modules/http/Makefile.am
- modules/http/autodetect-ca-location.c
- modules/http/autodetect-ca-location.h
- modules/http/http-grammar.ym
- modules/http/http-worker.c
- modules/http/http.c
- modules/http/http.h
- tests/copyright/policy
Change `use-system-cert-store` : this option was added in order to support monolithic installations that ships even libcurl...  But later, as it came out, it's not enough. 
What we really need is to do some autodetection regarding ca-file and ca-dir.
In monolithic installations that ships even libcurl we need to enable this by default in the related SCLs.
@furiel: could you check this?
> Autodetect system cert store

- news/README.md
- news/create-newsfile.py
- news/developer-note-3066.md
- tests/copyright/policy
How to create a newsfile entry
==============================
1. Create a file in the `news/` directory called `<type>-<pr-num>.md`, where `<type>` is either:
* `feature`: New functionality.
* `bugfix`: Fix to a reported bug.
* `developer-note`: Changes, that are only interesting to developers. (internal API change, etc...)
* `other`: Other important, but not categorized change.
You can calculate your PR number, by checking the most recent Issue or PR on github,
but it could be a good practice to add the commit, containing the news entry, after you
have opened your PR, as you know your PR number already.
2. Fill it with the summary of the PR.
* You can use any markdown formatting.
* Please make sure, that there are no lines longer than 120 characters.
* Make it 2-3 sentences at most.
* …
> news: add news directory and script to create NEWS.md

- .travis.yml
Our python codebase (tests) is based on python2, and it was assumed, that `python` will point to `python2`.
Newer distros (the arm based runner in travis) redirect `python` to `python3`, which was not our intention.
For some reason python3 does not have all the packages we need in pip, so our travis job breaks.
This patch forces `python2` for `pip`.
I also added `--cache-dir=$PWD/cache`, because the arm travis runner does not grant the default cache dir with proper capabilities.
> travis: force python2, add --cache-dir=$PWD/cache

- modules/http/http-grammar.ym
`CHECK_ERROR` is like assert: we need to pass true. If the predicate is
false, only then will syslog-ng generate error.
The original code breaks 001-check-scl.zts, that tests telegram. This was not executed by kira, because it is not run-local test.
No need to add change note. This is a quick fix for https://github.com/syslog-ng/syslog-ng/pull/3086
> http: fix auto-detect

- modules/python/CMakeLists.txt
- modules/python/Makefile.am
- modules/python/python-dest.c
- modules/python/python-fetcher.c
- modules/python/python-persist.c
- modules/python/python-persist.h
- modules/python/python-source.c
- modules/python/tests/CMakeLists.txt
- modules/python/tests/Makefile.am
- modules/python/tests/test_python_persist_name.c
- news/feature-3016.md
Changes:
- Users can provide a  `@staticmethod` `generate_persist_name(options)` function, that will be used for persist name generation or stats generation in python source/fetcher and python destination.
- Syslog-ng provides persist name through self.persist_name member, injected into python source/fetcher and python destination. For python source and fetcher, I could make the member readonly.
- Users can specify persist name both in configuration (`persist_name`) and `generate_persist_name`. The string from configuration is stronger.
- As small reference leak was fixed.
Motivation:
Currently, in python destination, persist name is generated from the python class name. This can cause inconvenience if the same python class is planned to be used multiple times. For example if someone …
> python: specify stats/persist name from python

- modules/python/tests/test_python_persist_name.c
With python3, `test_python_persist_name` crashes and there is an assertion error.
- Forgot to add gilstate lock in some places.
- Different error type is raised when trying to write readonly member.
news file change not needed. This just a fixup for #3016
> python: fix test_python_persist_name

- modules/http/http-worker.c
Othwerwise body-dependent headers (like azure-auth-header) will compute
bad values (bad signature in case of azure-auth-header).
> http: batching mode: format headers only after body is finished

- lib/gsockaddr.c
- lib/gsockaddr.h
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/ip-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
Fixes #3011
---
Resolves the given IP(v4/v6) address to a hostname.
Usage:
```
$(dns-resolve-ip [OPTIONS] ${IP})
```
Valid options are:
```
--use-fqdn=yesno
--use-dns=yesno
--dns-cache=yesno
--normalize-hostnames=yesno
```
The options inherit the global options.
**WARNING**: 
`$(dns-resolve-ip)` uses the same blocking implementation as the source-side DNS resolution.
While the IP is being resolved by the DNS server, message processing might stop even on paths where `$(dns-resolve-ip)` is not present/not used. For more information, see ["Multithreading and scaling in syslog-ng OSE"](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.25/administration-guide/88#TOPIC-1349634)
The main use case for `$(dns-resolve-ip)` is to granulate the DNS resolution to a …
> basicfuncs: add `$(dns-resolve-ip)` template function

- .lgtm.yml
When cmake install fails, LGTM falls back to automake and automake build
fails when autoconf-archive is missing (it's not detected
automatically).
Update: I have a reason of merge this over #3109 : currently syslog-ng cannot be built in lgtm environment with automake... and I think we should fix it (and make it possible to use as a fallback when cmake build fails).
> lgtm: install autoconf-archive

- modules/examples/CMakeLists.txt
- modules/examples/Makefile.am
- modules/examples/example-plugins.c
- modules/examples/inner-destinations/http-test-slots/CMakeLists.txt
- modules/examples/inner-destinations/http-test-slots/Makefile.am
- modules/examples/inner-destinations/http-test-slots/http-test-slots-grammar.ym
- modules/examples/inner-destinations/http-test-slots/http-test-slots-parser.c
- modules/examples/inner-destinations/http-test-slots/http-test-slots-parser.h
- modules/examples/inner-destinations/http-test-slots/http-test-slots.c
- modules/examples/inner-destinations/http-test-slots/http-test-slots.h
- news/developer-note-3093.md
as @gaborznagy requested, I added this test slot module to examples
example config:
```
@version:3.25
destination d_http {
http(
url("http://127.0.0.1:8888")
method("PUT")
user_agent("syslog-ng User Agent")
user("user")
password("password")
headers("HEADER1: header1", "HEADER2: header2")
http-test-slots(
header("xxx:aaa")
)
body("${ISODATE} ${MESSAGE}")
);
};
source s_generator {
example-msg-generator(num(1) template("test msg\n") );}
;
source s_net {
network(port(5555));
};
log {
source(s_generator);
destination(d_http);
};
```
> examples: add http-test-slots

- dbld/images/helpers/pip_packages.manifest
With newer versions of hy, 008-python-destination-loaders.zts
fails, because from 0.18 python3 is not supported by hy.
If syslog-ng is compiled with `--with-python=3` or
`-DPYTHON_VERSION=3`, then hy==0.18 works.
But for now we are compiling with python2, so 0.17 needs until python2
support is dropped.
No need to add this to changenote.
> dbld: freeze last version that supports python2

- modules/http/http-grammar.ym
- news/bugfix-3116.md
If we starts syslog-ng with the following minimal config syslog-ng will crash on first input log:
```
@version: 3.25
source s_example {
example-msg-generator(num(1) template("<34>Oct 11 22:14:15 tristram su: 'su root' failed for lonvick on /dev/pts/8\n") );
};
destination d_http {
http(
method(post)
url("http://127.0.0.1:61292") 
workers(0)
);
};
log {
source(s_example);
destination(d_http);
};
```
console log:
```
...
[2020-02-04T13:28:35.086386] syslog-ng starting up; version='3.25.1.188.g4226fa1'
[2020-02-04T13:28:35.086397] Running application hooks; hook='2'
[2020-02-04T13:28:35.086420] Setting value; name='MESSAGE', value='-- Generated message. --', msg='0x562832083d80'
[2020-02-04T13:28:35.086431] Setting value; name='MESSAGE', value='<34>Oct 11 22:14:15 tristram su: \'su root\' …
```
> HTTP: workers() must be positive numbers

- CMakeLists.txt
- Makefile.am
- lib/logmsg/tests/test_log_message.c
- libtest/cr_template.c
- libtest/msg_parse_lib.c
- libtest/msg_parse_lib.h
- libtest/proto_lib.c
- modules/linux-kmsg-format/tests/test_linux_format_kmsg.c
- modules/python/tests/test_python_logmsg.c
- modules/stardate/tests/test_stardate.c
- persist-tool/add.h
- persist-tool/generate.h
- persist-tool/persist-tool.c
- tests/unit/test_clone_logmsg.c
- tests/unit/test_matcher.c
- tests/unit/test_msgparse.c
This PR removes the `-fcommon` flag from CMake and autotools builds.
The `-fcommon` option hides (merges) multiple definition issues such as the persist-tool global variable redefinition (bc3fcb4) .
Such multi-definitions are not intentional in the syslog-ng codebase.
> The -fcommon places uninitialized global variables in a common block. This allows the linker to resolve all tentative definitions of the same variable in different compilation units to the same object.
In new GCC versions, `-fno-common` is the default:
>GCC now defaults to -fno-common. As a result, global variable accesses are more efficient on various targets. In C, global variables with multiple tentative definitions now result in linker errors. With -fcommon such definitions are silently merged during linking. 
Fixes …
> Fix multiple-definition issues

- modules/http/http-worker.c
- modules/http/tests/CMakeLists.txt
- modules/http/tests/Makefile.am
- modules/http/tests/test_http-signal_slot.c
In case batching is not enabled, but prefix and suffix is used, http-worker (`_insert_single`) calculated headers before the body is finshed (body-suffix is added).
After this patch, the msg specific headers are added in `_insert_single`, and everything else during flush, unconditionally.
No need for changenote, just a small addition to #3103.
> http: fix signal slot headers with non-batching but prefix-suffix case

- tests/copyright/check.sh
No changelog is needed.
The tempfile is deprecated and removed from newer version of coreutils, mktemp can replace it.
> replace tempfile command with mktemp

- contrib/config_option_database/utils/MergeYm.py
- contrib/config_option_database/utils/OptionParser.py
- news/bugfix-3125.md
I have run into the following problem, when I run `python3 syslog-ng-cfg-db.py` from a docker container (ubuntu:18.04)
For the notice, by deafult docker images have 'POSIX' as locale settings.
```console
$ locale
LANG=
LANGUAGE=
LC_CTYPE="POSIX"
LC_NUMERIC="POSIX"
LC_TIME="POSIX"
LC_COLLATE="POSIX"
LC_MONETARY="POSIX"
LC_MESSAGES="POSIX"
LC_PAPER="POSIX"
LC_NAME="POSIX"
LC_ADDRESS="POSIX"
LC_TELEPHONE="POSIX"
LC_MEASUREMENT="POSIX"
LC_IDENTIFICATION="POSIX"
LC_ALL=
```
The following errors I run into:
1, can not read from grammar files (like: modules/snmp-dest/snmpdest-grammar.ym)
```console
$ python3 syslog-ng-cfg-db.py 
Traceback (most recent call last):
File "syslog-ng-cfg-db.py", line 195, in <module>
main()
File "syslog-ng-cfg-db.py", line 183, in main
db = get_db(args.rebuild)
File …
```
> ConfigOptionDatabase: Use 'UTF-8' encoding while reading from files

- lib/poll-events.h
- lib/poll-fd-events.c
- modules/affile/poll-file-changes.c
- modules/affile/poll-multiline-file-changes.c
- news/feature-2963.md
update_watches is a mandatory virtual function,
which was used for update- and suspend cases too.
Usually a suspend_watches() call would be simply
a stop_watches(), but in some cases stop_watches()
and suspend_watches() differ.
Previously, poll_events_suspend_watches() called update_watches with 0.
Therefore every update_watches implementation had to be aware of this use case.
News file is not affected.
> poll-events: introduce suspend_watches virtual function

- lib/seqnum.h
- modules/snmp-dest/snmpdest.c
- modules/snmp-dest/snmpdest.h
Refactor snmp destination driver to be based on threaded destination driver.
During the development it turned out that we use g_atomic_int_exchange_and_add in seqnum.h which is deprecated since glib version 2.30. A commit has been created to fix this deprecated function.
> snmp destination driver: make it threaded

- configure.ac
- modules/python/compat/compat-python-v2.c
- modules/python/compat/compat-python-v3.c
- modules/python/compat/compat-python.h
- modules/python/python-plugin.c
- modules/python/tests/test_python_logmsg.c
- modules/python/tests/test_python_template.c
```
--with-python3-home=path Use path as a hard-coded Python home directory that
can not be overwritten by the PYTHONHOME environment variable.
```
This can be useful when a Python interpreter is bundled with syslog-ng.
Relocation is supported, for example: `--with-python3-home='${exec_prefix}'`
> Add python-home configure option

- lib/cfg.c
- lib/cfg.h
- lib/template/compiler.c
- lib/versioning.h
- modules/affile/named-pipe.c
- modules/afsocket/afunix-source.c
- modules/afsocket/transport-mapper-inet.c
- modules/dbparser/dbparser.c
- modules/getent/tfgetent.c
- modules/map-value-pairs/map-value-pairs-plugin.c
- modules/python/python-plugin.c
- modules/timestamp/timestamp-plugin.c
- news/feature-3074.md
- syslog-ng/main.c
Resolves #3068 
On syslog-ng upgrade, if the `@version:` number in the config file left on the older version, a warning `WARNING: Configuration file format is too old, syslog-ng is running in compatibility mode. Please update it to use the syslog-ng ...` can be seen.
This PR makes it possible that a syslog-ng upgrade does not have to be followed by a version number upgrade in the config file, except there is a change in compatibility.
In a lot of cases there is no compatibility changes between 2 versions, so this saves some unnecessary config editing.
It's important, that users should still use the installed syslog-ng version number in their configuration,
even if the `syslog-ng -V` `Config Version` reports the version which is compatible with.
> Only complain about older config version if there was a change

- news/bugfix-3112.md
- scl/graylog2/plugin.conf
Fixes #3110
---
There are sources, which do not set the `${PID}`, so it stays empty.
We use `$(format-json)` in `$(format-gelf)` with `int` type hinted `${PID}`. If `${PID}` is empty, the whole `$(format-json)` call will fail, and it will produce an empty message:
```
[2020-02-03T10:27:08.261055] Casting error; value='', type-hint='int32'
[2020-02-03T10:27:08.261116] Outgoing message; message=''
```
`_pid` is just and additional field in GELF, so it can be skipped:
https://docs.graylog.org/en/3.1/pages/gelf.html
> format-gelf: add --omit-empty-values

- configure.ac
- news/bugfix-3135.md
The detection of the location of the `gethostbyname` function was faulty. (except on Solaris) `gethostbyname` can be found under `libc`.
This check caused unnecessary linking against `libnsl`, now it only links if gethostbyname can be found under libnsl.
This unnecessary linking was hidden from us for several reasons:
- On Debian-based distributions libnsl is part of the libc package, so it was loaded without any problem.
- If the linker is using the `--as-needed` option (turned on by default on Debian-based distributions), than `libnsl` was removed during the final linking since nothing uses it inside Syslog-ng.
> fix gethostbyname detection

- modules/http/http-signals.h
- modules/http/http-worker.c
- modules/python/CMakeLists.txt
- modules/python/Makefile.am
- modules/python/python-grammar.ym
- modules/python/python-helpers.c
- modules/python/python-helpers.h
- modules/python/python-http-header.c
- modules/python/python-http-header.h
- modules/python/python-logger.c
- modules/python/python-parser.c
- modules/python/python-plugin.c
- news/feature-3123.md
The `python-http-header` plugin makes it possible for users to implement HTTP header plugins in Python language. It is built on top of signal-slot mechanism: currently HTTP module defines only one signal, that is `signal_http_header_request` and `python-http-header` plugin implements a python binding for this signal. This means that when the `signal_http_header_request` signal is emitted then the connected slot executes the Python code.
The Python interface is :
```
def get_headers(self, body, headers):
```
It should return a string List.
When the plugin fails, http module won't send the http request without the header items by default. 
If you want http module to trying to send the request without these headers, just disable `mark-errors-as-critical` function.
Code, or naming is not …
> Python http header

- modules/python/python-logmsg.c
- modules/python/python-tf.c
- modules/python/python-value-pairs.c
- news/bugfix-3153.md
Previously, we used `PyBytes_FromStringAndSize()`, and it was only tested with `python2`.
Our example `python()` destination has this `send()`:
```
def send(self, msg):
with open('test-python.log', 'a') as f:
f.write('{DATE} {HOST} {MSGHDR}{MSG}\n'.format(**msg))
```
In `python2` it does not matter, if we fill the `msg` dict with `bytes`-like data (which is generated with `PyBytes_FromStringAndSize()`), the `test-python.log` file will be written in `text` mode insead of `byte` mode, because it is the default.
However, in `python3` when we open the file in the default `text` mode, and we write `bytes`-like object in it, the output will still be in `byte` mode.
This causes a different behavior, which is fixed by storing the data in `text` mode, with `_py_string_from_string()`.
The same …
> python3: store strings as str instead of bytes

- news/developer-note-3144.md
- tests/functional/func_test.py
- tests/functional/log.py
- tests/functional/messagecheck.py
- tests/functional/messagegen.py
- tests/functional/test_performance.py
- tests/functional/test_python.py
- tests/functional/test_sql.py
These changes are the minimal set to run tests with Python3.
Tests are still compatible with Python2
Tested with DBLD: balabit/syslog-ng-ubuntu-bionic image, where currently the following Python versions are available:
```console
root@092a7a58dbf5:/# python
Python 2.7.17 (default, Nov  7 2019, 10:07:09) 
```
```console
root@092a7a58dbf5:/# python3
Python 3.6.9 (default, Nov  7 2019, 10:44:02)
```
Func-tests will run with Python3 interpreter when `${PYTHON}` and `${PYTHON_EXECUTABLE}` variables are expounds to python3 in `tests/functional/Makefile.am` and in `tests/functional/CMakeLists.txt`
> FuncTests: Make func-test Python3 compatible

- .travis.yml
- lib/secret-storage/nondumpable-allocator.c
- news/bugfix-3141.md
With this job we can test `--with-python=3`. Additional extra, that it runs on `bionic`, and it seems, that the only thing that needed extra care is to use an older `java` (I installed 1.8 in this case).
There are 2 things to fix, both are disabled right now:
There was a small bug, which showed itself now, when building with fresher `gcc`, the PR has he fix for it, too.
This PR is an alternative of #3104, this one uses TravisCI.
> travis: add bionic-python3 job

- lib/logmsg/logmsg-serialize-fixup.c
- lib/logmsg/logmsg-serialize.c
- lib/logmsg/logmsg-serialize.h
- lib/logmsg/logmsg.c
- lib/logmsg/nvtable.c
- lib/logmsg/nvtable.h
- lib/logmsg/serialization.h
- lib/logmsg/tests/test_logmsg_serialize.c
- lib/logmsg/tests/test_nvtable.c
- libtest/queue_utils_lib.c
- modules/diskq/diskq-grammar.ym
- modules/diskq/diskq-options.c
- modules/diskq/diskq-options.h
- modules/diskq/diskq-parser.c
- modules/diskq/logqueue-disk.c
- modules/diskq/qdisk.c
- modules/diskq/tests/test_reliable_backlog.c
This branch introduces a new parameter for disk based buffers, for example:
tcp("127.0.0.1" port(2001) disk-buffer(compaction(yes) disk-buf-size(10M)));
Note the "compaction" argument, it can either be "yes" or "no". With
compaction(yes), syslog-ng will prune the unused space in the LogMessage
representation, making the representation of the LogMessage more
compact. This is useful when syslog-ng uses a lot of name-value pairs during
processing that become unused when delivering to a destination.
Simply unsetting these values using the unset() rewrite operation does not
help, as the internal representation of a LogMessage will not release
the memory associated with these name-value pairs due to performance
reasons that help when syslog-ng is CPU bound.
In some cases however, the size of …
> Allow the LogMessage to be compacted before storing it in disk-buffer

- modules/python/python-logmsg.c
- modules/python/python-tf.c
- modules/python/python-value-pairs.c
- tests/functional/sngtestmod.py
We decided to keep the `bytes` type data.
> python: Revert #3153

- lib/compat/glib.c
- lib/compat/glib.h
- lib/signal-slot-connector/signal-slot-connector.c
- tests/loggen/CMakeLists.txt
- tests/loggen/Makefile.am
In glib 2.28 (centos6), g_hash_table_insert is a void function
No change note is necessary.
> signal-slot-connector: fix compile error with old glib

- lib/logproto/logproto-client.c
- lib/logproto/logproto-client.h
- lib/logproto/logproto-text-client.c
- modules/affile/affile-dest.c
- modules/affile/affile-dest.h
- modules/affile/logproto-file-writer.c
- news/bugfix-3133.md
According to the documentation the current `time-reap()` option describes the amount of seconds to wait before closing the destination file. The time between now and the last message to save
to a specific file (it can be different in case of templated path).
The current implementation schedule a timer at every `time-reap()` seconds and checks if there are messages in the queue to save into a file. The timer and the last message has no correlation.
This PR aims to replace the current behaviour with the one in the documentation[1]. The implementation taps into an already existing functionality of `LogWriter`'s `idle_timer`. A `LogProtoClient` could indicate a timeout value within its `_prepare` method, after that timer expires (if no message is sent till that time).
The timeout option …
> Affile, pipe time reap

- lib/tlscontext.c
- lib/tlscontext.h
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
- news/bugfix-3145.md
- news/feature-3145.md
With this option, users can specify a CA-file, which holds the certificates in a bundle file.
e.g.: `ca-file("/etc/pki/tls/certs/ca-bundle.crt")`
Can be used parallelly with the `ca-dir()` option.
Fixes #3111
> tls: add ca-file() option

- news/bugfix-3146.md
- tests/loggen/loggen.c
- tests/loggen/loggen_plugin.h
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
`../bin/loggen -S --active-connections=10 -I 120` caused crash in
loggen, because mandatory parameters were not passed: ip and port.
The reason is even if a module cannot start, stop was still called. In
our specific case, thread_array was accessed in stop, even though it
was not initialized in start (because start returned earlier due to error).
The fix is that start returns boolean now. Stop is only called a
plugin is started.
> loggen: fix crash with invalid parameterization

- news/developer-note-3157.md
- tests/python_functional/functional_tests/conftest.py
Before this patch we can not started Light with such report dir (the given directory has different base  than current directoy): `/tmp`
```consoe
python -m pytest -lvs functional_tests/source_drivers/file_source/test_acceptance.py --installdir=/install --reports /tmp/
```
we have got such an exception:
```
n = len(to_abs_parts)
cf = self._flavour.casefold_parts
if (root or drv) if n == 0 else cf(abs_parts[:n]) != cf(to_abs_parts):
formatted = self._format_parsed_parts(to_drv, to_root, to_parts)
raise ValueError("{0!r} does not start with {1!r}"
>                            .format(str(self), str(formatted)))
E           ValueError: '/tmp/test_acceptance_with_ten_logs_' does not start with '/source/tests/python_functional'
```
After this patch it will work correctly, this report dir will …
> LightReportDir: Support to define report dir with any path

- .github/workflows/macos.yml
- lib/compat/glib.c
- lib/compat/glib.h
- modules/cef/tests/test-format-cef-extension.c
- modules/json/tests/test_format_json.c
- news/bugfix-3175.md
Prior to 2.64.1, `g_utf8_get_char_validated()` in glib falsely identified embedded zeroes as valid utf8 characters. As a result, format json printed the embedded zeroes as `\u0000` instead of `\x00`.
The macOS ci job fails due to this change (test_format_json). The same unit test failure happens in archlinux. https://github.com/GNOME/glib/commit/1963821a57584b4674c20895e8a5adccd2d9effd
This is a breaking change as the output of format-json may change. Alternatively, I could maintain the original behavior, and make `g_utf8_get_char_validated()` the original value in the compat layer. Personally, I agree with glib here. That's why I am proposing this version.
> format-json: fix embedded zeroes, fix github actions

- contrib/com.syslog-ng.syslog-ng.plist
- news/packaging-3172.md
Hi all! Per @furiel comments in the Gitter channel, I'm sharing a working launchd job for syslog-ng 3.25 I tested on macOS. I'm just trying to give Mac users a little help with their syslog-ng experience :)
> contrib: add example startup configuration for macOS

- CONTRIBUTING.md
- news/developer-note-3174.md
There were a few things missing from the guide: like news file, how deal with style-check problems, mentioning light.
There are things I think is not necessary: for example opening an issue before pull request.
If you want to see the html-formatted version, just open:
https://github.com/furiel/syslog-ng/blob/update-contribution-doc/CONTRIBUTING.md.
> update contribution guide

- configure.ac
The option '--with-net-snmp' did not work, because later checks were using
the variable '$with_netsnmp' rather than '$with_net_snmp'.
As a result, the net-snmp-config option was always searched in the PATH.
There are two possible solutions:
- make the option '--with-netsnmp'
- change the internal variables
Opt for the second option so the user-visible options remain the same.
Signed-off-by: Thomas De Schampheleire <thomas.de_schampheleire@nokia.com>
(Note: I did not add a news item as I think very few people actually use this, and it was broken for almost a year, let me know if you would prefer one)
> configure.ac: fix --with-net-snmp

- modules/python/python-logger.c
- news/bugfix-3187.md
Py_RETURN_NONE is a macro that
* increments ref counter for the Py_None object
* return with Py_None
> python: fix Py_None reference counting

- modules/java/native/java-grammar.ym
- modules/java/native/java-parser.c
- modules/python/python-grammar.ym
- news/feature-3161.md
> java/python: added support for the "arrow" syntax

- news/developer-note-3185.md
- tests/python_functional/src/helpers/snmptrapd/conftest.py
Update:
This patch waits until snmptrapd log file initialized, and with this able to receive logs.
This is also a fix for:
#3183
> Light: fix snmptrapd start

- modules/affile/affile-grammar.ym
I have taken care of the earlier changes. Sorry for the issues that inadvertently popped up
Fixes: https://github.com/syslog-ng/syslog-ng/issues/3178
> logpipe-source: disable multi-line-timeout

- lib/rewrite/rewrite-expr-grammar.ym
- news/feature-3190.md
> rewrite: added conditional set-tag rule

- modules/afmongodb/CMakeLists.txt
- news/bugfix-3188.md
> afmongodb: cmake: do not build module when ENABLE_MONGODB=off

- modules/afmongodb/afmongodb.c
- news/developer-note-3199.md
Deprecation information: http://mongoc.org/libmongoc/current/mongoc_client_get_server_status.html
The documentation above suggests to use [mongoc_client_read_command_with_opts()](http://mongoc.org/libmongoc/current/mongoc_client_read_command_with_opts.html), but its documentation suggests, that if the usage of `opts` is not needed, it is enough to use [mongoc_client_command_simple()](http://mongoc.org/libmongoc/current/mongoc_client_command_simple.html).
[mongoc_client_command_simple()](http://mongoc.org/libmongoc/1.0.0/mongoc_client_command_simple.html) is available in `libmongoc` version `1.0.0`, which is set in our `configure.ac` file as the minimum needed version: `LMC_MIN_VERSION="1.0.0"`
Please do not merge, until internal tests validated the change.
Signed-off-by: Attila Szakacs …
> mongodb: replace deprecated API get_server_status()

- tests/functional/test_sql.py
python crashes at `join(paths)` in line 77, if a list element is`None` and not a `str`.
> func-test: fix crash when `dbd_dir` env variable is not set

- news/bugfix-3206.md
- news/feature-3206.md
- scl/telegram/telegram.conf
Telegram returns with 400 http response with `MESSAGE_TOO_LONG`, if the telegram message is longer than 4096 utf8 characters. I could not find this value in the official documentation, but unofficially I could find it here and there. I also tested, and 4096 long message passes, but 4097 fails. The request itself can be longer (we send other fields). Only the message field is restricted to 4096.
This patchset adds to telegram destination an additional parameter: `truncate` which tells the truncate length, which will be applied to the message. Initial value is 4096.
I wish there were `maximum` template function, that I could apply, if users provide larger length than 4096. (There is a `max` template function, but that works on message contexts instead of raw numbers. I will create a good …
> telegram: truncate message to 4096 length to avoid destination getting stuck

- modules/afsocket/afsocket-source.c
- modules/afsocket/afsocket-source.h
- news/other-3193.md
This PR contains changes, which helps the debugging process related to flow-control and connection handling.
1. Shows the number of source connections per driver in the stats output. Which can be different from the connections listed by the kernel, in case flow-control is activated.
2. Add source name and location (in the configuration) to the max connections reached error message, which makes debugging easier.
WIP:
> Improve max-connections

- lib/compat/glib-g_mkdtemp.c
- lib/compat/glib.c
- lib/compat/glib.h
- lib/signal-slot-connector/tests/test_signal_slots.c
- lib/tests/test_scratch_buffers.c
- modules/afmongodb/tests/test-mongodb-config.c
- tests/loggen/CMakeLists.txt
- tests/loggen/loggen.c
- tests/loggen/socket_plugin/CMakeLists.txt
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/CMakeLists.txt
- tests/loggen/ssl_plugin/ssl_plugin.c
This patchset fixes incompatiblilities with old glib versions. After this, unit tests and the python functinal tests pass.
https://ci.syslog-ng.com/jenkins/job/daily-compile-with-glib-2.26/2002/console
Retested with the g_mkdtemp compat change:
https://ci.syslog-ng.com/jenkins/job/daily-compile-with-glib-2.26/2007/console
> fixing incompatibilities with old glib versions (<2.32)

- .github/workflows/macos.yml
- .travis.yml
- news/packaging-3208.md
- packaging/debian/syslog-ng-mod-geoip.install
- packaging/rhel/syslog-ng.spec
This change fixes rpmbuild, if `--without maxminddb` was used. If the maxminddb development files are installed on the system, after autodetection in syslog-ng, libgeoip2-plugin.so will be compiled and installed. However it will not be picked up by any packages. Hence command failure.
@czanik FYI
This patchset also contains a minor cleanup leftover after the geoip2 removal.
> rpm: fix --without maxminddb option

- tests/python_functional/functional_tests/rewrites/set-tag/test_set_tag.py
- tests/python_functional/src/syslog_ng_config/renderer.py
- tests/python_functional/src/syslog_ng_config/statements/filters/filter.py
- tests/python_functional/src/syslog_ng_config/statements/rewrite/rewrite.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
No changenote necessary.
`condition='match("MATCHSTRING" value("MSG"))'` is a little awkward (the value is a verbatim string).
This is the first time a driver needs positional parameter inside an option block. (If there were no `"MATCHSTRING"`, light could handle it with a dictionary though.)
I was wondering if I could use a tuple format + small modification in the rendering logic, like
`condition = {"match" : ("MATCHSTRING", {"value" : "MSG"}}`, but tuple is already reserved for different logic for snmptrapd.
Unfortunately I do not know any simple way to fix this in the current architecture.
Edit: introduced a filter object that can be passed to condition
> set-tag: add test

- modules/basicfuncs/Makefile.am
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- modules/basicfuncs/tf-iterate.c
- news/feature-3205.md
This patchset adds a new template function: `iterate`.
You can think of `iterate` as a generator. The idea is the `iterate` function receives an initial value `x`, and an `f` function, and stores a current value in `$_`. When evaluated, `iterate` prints the current value, and also updates current value to `f(it)`. In other words, through evaluation, `iterate` prints `x`, `f(x)`, `f(f(x))`, ...
```
$(iterate $(+ 1 $_) 0)
```
With that, you can implement interesting stuff with syslog-ng, for example a sequence number.
Or even you can use this to loop through a list.
I would like to use these for tests: I want to generate different messages with `example-msg-generator`.
```
@version: 3.26
log {
source { example-msg-generator(num(3) freq(0.001) template("$(iterate $(+ 1 $_) 0)")); }; …
```
> iterate: new template function

- lib/transport/transport-udp-socket.c
No releases are affected. It is a minor regression from: https://github.com/syslog-ng/syslog-ng/pull/2899/
No changenote is necessary.
```
log {
source { example-msg-generator(num(1)); };
destination { syslog("localhost" transport("udp") port(5555)); };
};
```
<details>
```
==1316== 40 bytes in 1 blocks are definitely lost in loss record 31 of 59
==1316==    at 0x4C2DB8F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==1316==    by 0x519D7B8: g_malloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==1316==    by 0x51B49C2: g_slice_alloc (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==1316==    by 0x51B505D: g_slice_alloc0 (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
==1316==    by 0x4E80098: g_sockaddr_inet_new2 (gsockaddr.c:336)
==1316==    by 0x4E7FB3F: …
```
> transport-udp-socket: fixing small memory leak

- modules/examples/sources/msg-generator/msg-generator-grammar.ym
- modules/examples/sources/msg-generator/msg-generator-parser.c
- modules/examples/sources/msg-generator/msg-generator-source-options.h
- modules/examples/sources/msg-generator/msg-generator-source.c
- modules/examples/sources/msg-generator/msg-generator.c
>  example-message-generator: add support for values(name1 => value1, ...) syntax where value follows template syntax

- lib/rewrite/CMakeLists.txt
- lib/rewrite/Makefile.am
- lib/rewrite/rewrite-expr-grammar.ym
- lib/rewrite/rewrite-expr-parser.c
- lib/rewrite/rewrite-set-facility.c
- lib/rewrite/rewrite-set-facility.h
- lib/rewrite/rewrite-set-severity.c
- lib/rewrite/tests/CMakeLists.txt
- lib/rewrite/tests/Makefile.am
- lib/rewrite/tests/test_set_facility.c
- lib/rewrite/tests/test_set_severity.c
- lib/syslog-names.c
- lib/syslog-names.h
- news/feature-3136.md
- tests/copyright/policy
This PR is a followup to #3115 namely that added set-severity() and this one adds set-facility().
Apart from the new feature, this also refactors the set-severity() test program and adds a log message to set-severity(), similar to what we have in other rewrite ops (and similar to what I have added to set-facility() as  a part of this PR).
Hopefully the gods of travis et al find these patches worthwhile and give me the holy price of being "green". Apart from that this should be pretty straight-forward to get merged.
> add set facility rewrite op

- modules/examples/sources/msg-generator/msg-generator-grammar.ym
- news/feature-3245.md
- tests/python_functional/functional_tests/template_functions/slog/test_secure_logging.py
> example-msg-generator: support fast message generation

- modules/python/compat/compat-python-v2.c
- modules/python/compat/compat-python-v3.c
- modules/python/compat/compat-python.h
- modules/python/pylib/syslogng/__init__.py
- modules/python/python-config.c
- modules/python/python-main.c
- modules/python/python-main.h
- modules/python/python-persist.c
- modules/python/python-persist.h
- modules/python/python-plugin.c
- modules/python/tests/CMakeLists.txt
- modules/python/tests/Makefile.am
- modules/python/tests/test_python_persist.c
- news/feature-3171.md
This patchset exposes persist api into python code.
This is the continuation of #3016, towards the road of having proper acknowledgement support in python.
Similar to #3016, this PR neither has any usage on its own, until bookmark handling is implemented in the future.
Features:
- A `Persist` class is importable from `syslogng` module
- The object looks like a dictionary: users can store values behind keys. The difference is it is backed by an entry in the persist file, so data is persisted between restarts.
- If no persist file created yet, `defaults` constructor parameter specifies can specify values for keys.
- Handles integers and strings.
- Iterable
Limitations:
- This patchset does not support editing multiple keys in the same transaction. This means if the persist data is complex …
> python: persist api

- lib/logproto/logproto-client.c
- lib/logproto/logproto-client.h
- lib/logwriter.c
`LogProtoClientOptions` is just a reference in the `LogProtoClient` class, owners are usually driver instances, and the ownership is not transferred to the proto client.
This is true for all `*Options` in syslog-ng.
The lifetime of these `*Options` objects are clear:
The owner of the options object outlives the user. For example, `AFSocketDestDriver` is freed only after its `LogWriter`/`LogProtoClient` is deinitialized.
There are exceptions, of course. For example, the `keep-alive()` functionality of network drivers saves a deinitialized but open `LogWriter` instance in the "ReloadStore".
The reload mechanism creates a new driver instance (with new writer/proto options), and restores the `LogWriter` instance from the reload store.
This involves a `log_writer_set_options()` call, that …
> network destinations: fix invalid memory access after reload

- modules/python/python-grammar.ym
- news/feature-3247.md
> python: added support for arrow syntax

- modules/python/python-persist.c
- modules/python/tests/Makefile.am
- modules/python/tests/test_python_persist.c
In python3, integer and string cannot be sorted. So the python code throws exception, hence the testcase fails.
I forgot to add the test to `Makefile.am`, so in the end, the job that is responsible for checking unit tests with python3, did not execute this test. That's why we did not find this problem during code review.
Behind this, an actual coding error was hidden. `_py_is_string` returns true both for bytes and strings. So it should be executed last, when detecting the type of the value that is added to persist.
In python2, bytes and strings are the same, so no problem is there.
> python_persist: fix test with python3

- autogen.sh
- lib/template/macros.c
- lib/template/macros.h
- lib/transport/transport-udp-socket.c
This patchset fixes some compile problems on solaris. With these changes, I could build and run syslog-ng with afsnmp disabled.
If someone wants to test or further experiment: here are my notes of the environment: https://github.com/furiel/notes/blob/master/syslog-ng/platforms/solaris/Vagrantfile
Thanks for @alltilla for the input and guide about solaris build.
> fix compile error on solaris

- lib/timeutils/tests/test_wallclocktime.c
- lib/timeutils/wallclocktime.c
- news/bugfix-3270.md
> timeutils: fix crash in %f conversion when non-numeric character is in usec field

- modules/http/http-grammar.ym
- modules/http/http-parser.c
- modules/http/http-worker.c
- modules/http/http.c
- modules/http/http.h
- news/feature-3253.md
> http: add support for proxy

- modules/kafka/README.md
Updated the changes in syntax such as replacement of 'properties' with 'config', 'payload' with 'message'.
The docker-kafka implementation isn't working right now. Hence, on consultation with @furiel, I've replaced it with installation of kafka from official website which can be done following simple steps.
> Kafkareadme: Updated the Kafka Destination readme file with the current syntax

- lib/transport/transport-udp-socket.c
On FreeBSD, `struct in_addr` can be extracted from cmsg, not an entire `struct sockaddr_in`.
FreeBSD ip(4) man:
If the IP_RECVDSTADDR option is enabled on	a SOCK_DGRAM socket, the
recvmsg(2)	call will return the destination IP address for	a UDP data-
gram.  The	msg_control field in the msghdr	structure points to a buffer
that contains a cmsghdr structure followed	by the IP address.  The
cmsghdr fields have the following values:
```
cmsg_len =	sizeof(struct in_addr)
cmsg_level	= IPPROTO_IP
cmsg_type = IP_RECVDSTADDR
```
Fixes #3275
> Fix UDP dest-IP extraction on FreeBSD

- lib/logmsg/logmsg-serialize-fixup.c
- news/bugfix-3281.md
The handles in the logmsg are generated by the log_msg_registry, that object is not persisted between syslog-ng restarts, the handles are assigned in the order of request (incremented) therefore updating a handle to a new value might be needed at logmsg deserialization.
The current solution had a bug, that it only updated if the last handle was not updated. But the handles must be updated if any handle value changed in the logmsg and the current log_msg_registry.
Note: I wanted to write an UT covering the case when the last handle is not changed, but as the values are checked with a foreach that would rely on the way foreach loops the entries, which imho is not nice and may make the test pass but not really check the issue. So I decided not to. If anybody thinks otherwise let me know.
> Logmsg deserialization not always updated handles when changed

- dbld/hooks/build
- dbld/images/hooks/build
I mistakenly moved the build hooks in a previous PR to "./dbld", whereas it
should have remained in "./dbld/images/hooks".
Also the cwd is set by dockerhub to dbld/images which is not what we want,
so change the script to the root of the source tree and invoke docker build
from there.
> dbld: fix dockerhub automated builds

- news/bugfix-3282.md
- packaging/debian/syslog-ng-mod-rdkafka.install
All SCLs are shipped by syslog-ng-core.
> packaging/debian: fix rdkafka packaging

- lib/atomic-gssize.h
- news/developer-note-3286.md
```
glib/gatomic.h:119:46: warning: initialization of ‘gssize’ from ‘void *’ makes integer from pointer without a cast [-Wint-conversion]
119 |     __typeof__(*(atomic)) gaps_temp_newval = (newval);
```
`g_atomic_pointer_set()` is documented with the following signature:
`volatile void *atomic, gpointer newval`
Unfortunately, this is not entirely true, because these atomic methods are implemented as macros.
There are multiple implementations of `g_atomic_pointer_set()`, the best is used based on the available compiler features.
`newval` is usually cast to the appropriate type, but the new (preferred) C11-style atomic implementation is polymorphic, so they use `__typeof__` without forcing a type:
GNOME/glib@3251cce
> `__atomic_load()` and `__atomic_store()` built-ins are polymorphic, and
> …
> Fix atomic_gssize_set() warning with new glib versions 

- lib/cfg-grammar.y
- lib/cfg-lexer.c
- modules/dbparser/pdb-load.c
- modules/dbparser/pdbtool/pdbtool.c
- modules/graphite/graphite-output.c
- modules/java/native/java-destination.c
- modules/java/proxies/java-template-proxy.c
- modules/python/python-helpers.c
- news/bugfix-3265.md
- syslog-ng/main.c
- grammar: there are two different macros for error checking (namely: `CHECK_ERROR` and `CHECK_ERROR_GERROR`), we missed using the GError version at some places
- other: add missing `g_error_free` calls.
- Should we replace `g_clear_error` functions to `g_error_free` in case of local variables? `g_clear_error` makes an extra `=NULL` assignment, but it seems nitpicking for me to change them.
> fix GError handling

- dbld/rules
- scripts/version.sh
https://github.com/syslog-ng/syslog-ng/pull/3272/commits/bc10b1063dc1276fe4ea818cb471cef501e9fb29 was incomplete, it needs a little more work.
The mode variable needs to be quoted within `version.sh`. Strangely `[ ! = "release" ]` evaluates to 0 (which is true in bash), while for example  `[ ! "" = "release" ]` evaluates to 1 (which is false in bash).
Also, MODE needs to be made available for the version script.
After these changes. `dbld/rules pkg-tarball` will generate snapshot tarball, and `dbld/rules MODE=release pkg-tarball` generates release tarball
> fix snapsot version generation

- lib/secret-storage/tests/test_secret_storage.c
These asserts are not precise enough, being root is not enough to
determine if rlimit is restricted or not.
We need to check if we have `CAP_IPC_LOCK` capability. We had a run
with that, but we had to depend on `SYSLOG_NG_ENABLE_LINUX_CAPS`,
which is unfortunate in a test, because if we user does not have libcap
the tests are not run, also we will never notice, if the test stops
running for any reason.
In reality these asserts test a linux functionality, and to make it run
correctly it introduces too much complexity for no real usefulness.
Fixes #3181
> secret-storage: remove additional rlimit check

- dbld/images/kira.dockerfile
- dbld/packages.manifest
- dbld/rules
This PR upgrades syslog-ng-kira image from Ubuntu Xenial to Ubuntu Bionic.
Due to this change libmongoc* and libbson* packages should be installed with a fixed version on Ubuntu Bionic (related issue: #3184 )
> DbldKira: Upgrade Kira base image to Bionic

- tests/python_functional/functional_tests/template_functions/slog/test_secure_logging.py
This small patch shows an example how we can use `iterate` and `example-msg-generator` to generate unique messages.
Prior this patch, the same message was sent to secure logging multiple times. Now a sequence number is added.
> test_secure_logging: use iterate to generate unique strings

- lib/logthrsource/logthrsourcedrv.c
`LogThreadedSourceDriver` provided the `MsgFormatOption` variable and the `default-priority()` and `default-facility()` options from its grammar, but it did not provide its funcionality.
IMO news entry is not needed.
> threaded-source: fully support default-priority() and ...-facility()

- modules/affile/affile-dest.c
- modules/affile/file-opener.c
- modules/affile/file-opener.h
- modules/affile/file-reader.c
- modules/affile/tests/test_file_opener.c
- news/bugfix-3230.md
Instead of a simple boolean result, file_opener_open_fd will return
that the error was temporary or permanent. (Currently spurious paths
is the only permanent error.)
If the error is permanent we can do nothing about it, so we skip the
logwriter_reopen method too, thus there will be no further attempt to
open the file, and the log message will be skipped by the file
destination.
WIP:
> eliminate infinite loop in case of a spurious file path

- lib/cfg-grammar.y
- lib/logthrsource/logthrfetcherdrv.c
- lib/logthrsource/logthrfetcherdrv.h
- lib/logthrsource/tests/test_logthrfetcherdrv.c
- modules/affile/affile-grammar.ym
- news/bugfix-3306.md
- tests/python_functional/functional_tests/source_drivers/file_source/test_follow_freq_value.py
Also fixed a bug in `file()` source, where we erroneously accepted negative float numbers at `follow-freq()`.
> threaded-fetcher: support float at fetch-no-data-delay

- dbld/build.manifest
- dbld/images/debian-buster.dockerfile
- dbld/images/debian-stretch.dockerfile
- dbld/images/ubuntu-xenial.dockerfile
This branch removes Java support from xenial (not needed as our @kira-syslogng has recently been updated to bionic now).
It also removes gradle from images where we don't have java support. (this is the support we implemented in dockerfiles and not if the package installs gradle via build-depends/buildrequires).
> Remove obs and java support from old ubuntu releases

- lib/logthrdest/logthrdestdrv.c
- lib/logthrdest/logthrdestdrv.h
- lib/logthrdest/tests/test_logthrdestdrv.c
- modules/kafka/kafka-dest-driver.c
- modules/kafka/kafka-dest-worker.c
- news/bugfix-3305.md
temporary fixes: #3080 
I think this could work until we have the final solution for the issue.
Basic concept:
Poller thread (`worker_index == 0`) calls `rd_kafka_poll` publish messages in non-blocking way, and calls `rd_kafka_poll`. Other threads calls publish in a blocking way - and they don't call `poll()` method.
When the non-blocking publish returns an error (librdkafka's internal queue is full...), `worker_insert` returns `LTR_RETRY` - and then syslog-ng waits `poll_timeout` (converted to seconds) instead of `time_reopen`. Default value for `poll_timeout` is 1 second.
> Rdkafka fix simple

- doc/doc-3301.md
- modules/basicfuncs/Makefile.am
- modules/basicfuncs/basic-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- modules/basicfuncs/tf-map.c
- news/feature-3301.md
`map` template function applies a template function to all elements of a list. It returns the new list.
See documentation fragment for example and details.
CC: @jszigetvari
Referring: https://github.com/syslog-ng/syslog-ng/issues/2926
------------------
Future plans:
Originally, I wanted to add a `filter` template function together with map. However, `filter` turned out a bit more problematic. Unfortunately, the `context` is currently not passed to the filter `eval` functions. For example if you check: https://github.com/syslog-ng/syslog-ng/blob/d7d1149c17d9604d44f68e2ddf54d881a2ad460f/lib/filter/filter-cmp.c#L72
you can see `NULL` is passed, in the place of the context. Also, `context` is currently not part of the eval signature: …
> map: new template function

- lib/stats/stats.c
- news/bugfix-3320.md
The current `stats-freq` option could go as high as `2^31-1` (which of course kinda unrealistic), but the opposite happens, the stats reports start to spawn right away in an infinite loop manner.
When timer is adjusted (`timespec_add_msec(&timer->expires, freq * 1000);`) the `freq * 1000` is used, where the `freq` has the type `gint`, and the function - correctly - waits a `glong`, but the multiplication happens before the parameter assignment and in the domain of `gint` that yields `gint` overflow.
> Stats freq overflow

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/logsource.c
- lib/logsource.h
- news/feature-3323.md
This sets the `${PID}` macro to the `syslog-ng` process' PID.
If `${PID}` was set before, this option overrides it.
Defaults to `no`.
> logsource: add use-syslogng-pid() option

- .github/workflows/devshell.yml
- .travis.yml
- doc/man/slogkey.1.xml
- tests/python_functional/functional_tests/template_functions/slog/test_secure_logging.py
The failing test was fixed in https://github.com/syslog-ng/syslog-ng/pull/3284. This exclude is not needed anymore.
> Revert excluding secure logging test for cmake

- tests/python_functional/src/driver_io/file/file_io.py
- tests/python_functional/src/message_reader/message_reader.py
- tests/python_functional/src/message_reader/tests/test_message_reader.py
- tests/python_functional/src/syslog_ng/console_log_reader.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/destination_reader.py
In certain Python 2 versions, the `read()` method of buffered file objects can not be used to follow a file: after reaching EOF, subsequent calls will not read new data.
`fsync` calls have also been added to sync data to disk before reading with `READ_ALL_AVAILABLE_MESSAGES`.
Needed for #3277.
> light: fix MessageReader-based tests with Python 2

- lib/transport/transport-socket.c
- lib/transport/transport-socket.h
- lib/transport/transport-tls.c
- news/bugfix-2811.md
This pull request fixes the TLS connection closure on the source (receiver) side by sending back close_notify alerts.
RFC5425:
>  Once the transport receiver gets close_notify from the transport sender, it MUST reply with a close_notify unless it becomes aware that the connection has already been closed by the transport sender (e.g., the closure was indicated by TCP).
TODO:
- The destination (sender) side has to be fixed as well (in a separate PR):
> A transport sender MUST close the associated TLS connection if the connection is not expected to deliver any syslog messages later.  It MUST send a TLS close_notify alert before closing the connection.  A transport sender (TLS client) MAY choose to not wait for the transport receiver's close_notify alert and simply close the connection, thus …
> Fix TLS connection closure (source side)

- .github/workflows/devshell.yml
The motivation behind this change:
1. The `env:` option in the YAML cannot process embedded variables, so we had things like: `PYTHONUSERBASE: /github/home/python_packages`, which should be `${HOME}/python_packages`.
2. The `env:` option does not handle commands in variables. We need to set the python version, in configure time, with only the python major version, like 2 or 3, so we had 2 and 3 instead of 'python2' and 'python3' in the strategy matrix. The values of the strategy matrix are shown in the workflow run, and we got jobs like: (2, autotools), where the 2 is not comprehensible for the viewer.
The solution for both problems is a separate step, which sets the environment variables. But we have a problem with that too:
Environment variables set in one step are not available in …
> github-actions: cleanup ENV variables

- news/packaging-3324.md
- packaging/rhel/syslog-ng.logrotate7
- packaging/rhel/syslog-ng.spec
Fixes #1384
> I had long discussions with Red Hat about it, but renaming it to syslog-ng does not work.
https://github.com/syslog-ng/syslog-ng/issues/1384#issuecomment-286978553
More info: https://github.com/syslog-ng/syslog-ng/issues/1384#issuecomment-644716350
> RHEL 7 packaging: fix logrotate file conflict with rsyslog

- lib/signal-handler.c
- news/bugfix-2811.md
- news/developer-note-3338.md
Previously, setting `SIG_IGN` in a plugin/library (for example, in a Python module) resulted in a crash.
`SIG_DFL` and `SIG_IGN` are special values for `sa_handler`, they should not be treated as valid memory addresses.
> Fix signal handling when an external library/plugin sets SIG_IGN

- dev-utils/plugin_skeleton_creator/plugin_template_parser.c
- modules/openbsd/openbsd-parser.c
- news/bugfix-3339.md
- news/developer-note-3339.md
If syslog-ng is compiled with `--enable-debug`, the `-y` command line option adds grammar related debug information for each module. This functionality does not work for these modules due to wrong compiler switch was used.
> plugin_skeleton_creator: fix compiler switch

- lib/timeutils/misc.c
- news/bugfix-3340.md
Due to https://github.com/microsoft/WSL/issues/4898,
syslog-ng loops in `check_nanoseconds()` infinitely.
This is a wsl bug, that will be probably fixed.
On the other hand, syslog-ng should not interpret
`EINVAL` as expected failure. So this patch fixes
the error handling of `nanosleep`.
> misc: fix `check_nanoseconds()` for wsl

- requirements.txt
Due to a temporary incompatibility between the latest version of isort and Pylint (details: https://github.com/PyCQA/pylint/issues/3722), we freeze isort to version 4.3.4
Once the problem got fixed, we can remove this line and use the latest version from all library.
> requirements.txt: use isort==4.3.4

- modules/dbparser/pdb-load.c
- modules/dbparser/pdbtool/pdbtool.c
- modules/graphite/graphite-output.c
- news/bugfix-3344.md
- news/developer-note-3344.md
- tests/python_functional/functional_tests/parsers/db_parser/test_db_parser.py
- tests/python_functional/functional_tests/template_functions/graphite-output/test_graphite_output.py
- tests/python_functional/src/syslog_ng/console_log_reader.py
- tests/python_functional/src/syslog_ng_config/statements/parsers/db_parser.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
```
void
g_error_free (GError *error)
{
g_return_if_fail (error != NULL);
g_free (error->message);
g_slice_free (GError, error);
}
```
`g_error_free` does not expect it's parameter to be null. If syslog-ng
is started with `G_DEBUG=fatal-warnings`, this causes a
crash. Otherwise there is a warning:
```
[2020-07-01T13:17:46.293581] g_error_free: assertion 'error != NULL' failed
```
Example configuration:
```
@version: 3.27
log {
parser { db-parser(file("/tmp/patterndb.xml")); };
};
```
/tmp/patterndb.xml:
```
<patterndb version='4' pub_date='2020-03-03'>
<ruleset name='test' id='x'>
</ruleset>
</patterndb>
```
-------------------------
```
$ ../bin/pdbtool merge -D tmp --pdb output/merge.xml
(pdbtool:11058): GLib-CRITICAL **: g_error_free: assertion 'error != NULL' failed
(pdbtool:11058): …
```
> db-parser, pdbtool, graphite-output: fix glib assertion error

- lib/cfg-tree.c
- lib/cfg-tree.h
- lib/cfg.c
- lib/logpipe.h
- lib/logthrdest/logthrdestdrv.c
- lib/logthrdest/logthrdestdrv.h
- lib/logthrdest/tests/test_logthrdestdrv.c
- lib/logthrsource/logthrsourcedrv.c
- lib/logthrsource/tests/test_logthrfetcherdrv.c
- lib/logthrsource/tests/test_logthrsourcedrv.c
- lib/mainloop.c
- modules/afamqp/afamqp.c
- modules/afmongodb/afmongodb.c
- modules/afsmtp/afsmtp.c
- modules/afsnmp/afsnmpdest.c
- modules/afsql/afsql.c
- modules/afstomp/afstomp.c
- modules/http/http.c
- modules/http/tests/test_http-signal_slot.c
- modules/java/native/java-destination.c
- modules/kafka/kafka-dest-driver.c
- modules/python/python-dest.c
- modules/redis/redis.c
- modules/riemann/riemann.c
- news/bugfix-3176.md
In current version, syslog-ng registers revert_config task after cfg_init.
When applying config failed, ivykis task list can be illustrated as the following:
```
| _reenable_worker_jobs | _io_process_input | ... | _revert_config |
^
| ivykis task list
```
If there is a log before `_revert_config` finished, syslog-ng will use uninitialized log pipe to process it. This will lead to a crash.
Therefore, `main_loop_reload_config_revert` is scheduled to be called immediately via `main_loop_worker_sync_call` after applying config failed.
To avoid recursion in `main_loop_worker_sync_call`, there is a global flag named `sync_call_running`.
According to this flag, syslog-ng can determine whether it has to call `_invoke_sync_call_actions`.
fixes: https://github.com/syslog-ng/syslog-ng/issues/3173 …
> fix config reload crash via introducing on_config_inited in LogPipe

- news/feature-3234.md
- scl/CMakeLists.txt
- scl/Makefile.am
- scl/paloalto/panos.conf
- tests/python_functional/functional_tests/parsers/panos/test_panos_parser.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
This branch continues the great work in originally in #3234 with a couple of changes/improvements:
* support for custom logs are added (e.g. the CONFIG changes with two extra columns: before_change_detail and after_change_detail columns)
* the panos-parser() now handles non paloalto logs by dropping those that don't appear to be valid. (e.g. not enough CSV columns)
* performance improvement by using fixed string matching instead of regexps
* the naming of the fields is matched against the Paloalto official naming (which is a change compared to the original submission)
* support for fields added in later versions of Paloalto were added.
* the application adapter now classifies logs a bit better.
@spricer sorry for taking so long to go through your patches and I hope the changes above are …
> panos-parser() source as SCL

- lib/scratch-buffers.c
- lib/tests/test_scratch_buffers.c
- news/bugfix-3355.md
Due to some bug, the `global.scratch_buffers_count.queued` could shown an invalid value (e.g. 2^32 value, while the actual usage was just decreased to 0).
This bug only affected the stats_counter value, not the actual memory usage (i.e. memory usage was fine before).
> scratch-buffers: fix 'global.scratch_buffers_count.queued' bug

- lib/tlscontext.c
- news/bugfix-3356.md
https://www.openssl.org/docs/man1.1.1/man3/SSL_CTX_set1_curves_list.html
> SSL_CTX_set1_groups() sets the supported groups for ctx to glistlen
> groups in the array glist. The array consist of all NIDs of groups in
> preference order. For a TLS client the groups are used directly in the
> supported groups extension. For a TLS server the groups are used to
> determine the set of shared groups.
> ...
> The curve functions are synonyms for the equivalently named group
> functions and are identical in every respect.
> tlscontext: apply ecdh-curve-list for client, too

- news/developer-note-3236.md
- tests/functional/func_test.py
- tests/functional/messagecheck.py
1. While investigating func-test errors - It was easier for me to see the list of failed test cases after each run.
2. Checking logstore_reader was a dead code, since we returned from the loop on first iteration.
> Improve func-test

- .github/workflows/devshell.yml
- tests/commits/check.sh
Fetch mechanism changed when switched from actions/checkout@v1 to v2.
This PR tweaks the invokation of `tests/commits/check.sh` to match the new behavior, also makes it fail if bad revisions are given.
Thanks @Kokan for the heads-up :)
> github-actions: fix commits-check

- cmake/add_module.cmake
- modules/examples/CMakeLists.txt
- modules/examples/Makefile.am
- modules/examples/destinations/example_destination/CMakeLists.txt
- modules/examples/destinations/example_destination/Makefile.am
- modules/examples/destinations/example_destination/example_destination-grammar.ym
- modules/examples/destinations/example_destination/example_destination-parser.c
- modules/examples/destinations/example_destination/example_destination-parser.h
- modules/examples/destinations/example_destination/example_destination-plugin.c
- modules/examples/destinations/example_destination/example_destination.c
- modules/examples/destinations/example_destination/example_destination.h
- modules/examples/destinations/example_destination/example_destination_worker.c
- modules/examples/destinations/example_destination/example_destination_worker.h
- modules/examples/example-plugins.c
- tests/python_functional/functional_tests/destination_drivers/example_destination/test_example_destination.py
- tests/python_functional/src/syslog_ng/console_log_reader.py
- tests/python_functional/src/syslog_ng/syslog_ng.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/example_destination.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
By adding the example destination from gitbook to the repo, we have better chance to keep gitbook updated.
The port is not a blind copy paste, there are some changes comparted to the gitbook version.
- The module is not under `modules/example_destination`, but under `modules/examples/destinations/example_destinations`.
- It is not a module on it's own, but it is part of a larger `libexamples` module.
- It is built as static, instead of dynamic.
- The `ModuleInfo` is missing as it is not a module on it's own. The plugin list is moved to the libexamples.
- The functionality is changed a bit: example destination will actually write to a file: the output contains the thread id of the worker.
Other changes:
- the `add_module` in cmake has a new parameter: which can tell if a module wants to …
> add example destination from gitbook

- news/feature-3363.md
- scl/snmptrap/snmptrapd-source.conf
Inspired by mail list question: https://lists.balabit.hu/pipermail/syslog-ng/2020-July/025972.html
> snmptrap: improve error message when missing dependency

- lib/cfg.c
- lib/cfg.h
- lib/pragma-grammar.ym
- lib/pragma-parser.c
- news/feature-3368.md
From release to release we `sed` previous version values to the current version value...
I think it could be useful if we would have a `@version: current` syntax in the config file.
This PR implements this.
> Cfg version current

- lib/afinter.c
- lib/afinter.h
- lib/cfg-grammar.y
- lib/versioning.h
- news/other-3229.md
This PR is a proposal that adds a limit to the `internal()` source's temporary queue.
The max capacity is hard-coded in the proposal, but a config option can be added easily, if needed.
Why do I want this?
syslog-ng currently uses message queues only on the destination side. The size and behavior of those queues can be configured with the `log-fifo-size()` destination, and the `flags(flow-control), log-iw-size()` source options. syslog-ng drops new messages when flow control is not configured and the destination queue exceeds the `log-fifo-size()` limit. When flow control is configured and syslog-ng reaches `log-iw-size()` number of messages kept in memory per source, it stops the given source.
In both cases, the memory footprint has an upper limit and it can be calculated based on the …
> Limit the size of internal()'s temporary queue

- lib/stats/stats-counter.h
- lib/stats/tests/test_external_ctr_reg.c
- news/bugfix-3361.md
When trying to reset a read-only stats counter with
`syslog-ng-ctl query get '*' --reset`
syslog-ng crashed before this patch.
As this situation can be triggered by users, it does not
count as a programming error, so using assert is not reasonable.
Reported-by: Peter Kokai <peter.kokai@balabit.com>
> stats-counter: do not crash when set an external/read-only counter

- lib/stats/stats-query.c
- news/bugfix-3376.md
This  patchset speeds up `syslog-ng-ctl query get "*"` command. When the stats counters were collected into a list, they were appended instead of prepend and reverse in the end. The former is quadratic in complexity, the latter is linear. This made `query` impractical to be used with large number of counters.
PS: I experimented with `stats` too, but me seemed changing `num` changes the execution time linearly. So I believe there is no such problem with stats.
```
@version: 3.29
options {
stats-level(3);
};
log {
source { example-msg-generator(freq(0) num(50000)
values("HOST" => "host$(iterate $(+ 1 $_) 0)") keep-hostname(yes)); };
destination { file(/dev/null); };
};
```
Before:
```
$ time ./syslog-ng-ctl query get "*" | wc -l
194637
real	0m59.636s
user	0m0.003s
sys	0m0.019s
```
After: …
> stats-query: speedup

- dbld/builddeps
- dbld/packages.manifest
- This PR fixes python related docker builds for CentOS-6 and Debian-Sid
> DBLD: Fix docker build for centos6 and debian sid

- lib/cfg-grammar.y
- lib/cfg-parser.c
- news/bugfix-3383.md
This branch fixes a couple of issues in configuration error reporting:
1) when the configuration file has lines longer than 1024 bytes, the report could become confusing
2) the location of the error was incorrectly reported in some cases
+1 I've added the parsed value to the main grammar error message for cases where the value is a string.
All this together would probably have avoided the bug report in #3382
> Fixed location reporting and long lines in config errors

- lib/filter/tests/test_filters_common.c
- lib/filter/tests/test_filters_regexp.c
- lib/logmatcher.c
- news/bugfix-3393.md
When the regex filters used the `store-matches` flag and it was possible to not to set all of the named matches.
The current known case for not setting is when there were an optional named match: `(?<foobar>foobar) (?<foo>foo)?(?<bar>bar)` such as `foo` here, and if the provided string did not contain the `foo` string itself. In that case either `foobar` or `bar` were not saved into the `LogMessage`.
Additionally there was a test case error, that could lead to false positive asserts.
> Filter regex missing named matches

- scripts/version.sh
News file is not needed as the change it fixes not released and not visible to any user.
Fixes dbld devshell with cmake + ninja
> version.sh: version number must be without newline

- lib/logmatcher.c
- lib/logmatcher.h
Allow dupnames flag to be used in PCRE expressions, allowing duplicate names for named subpatterns as explained here https://www.pcre.org/original/doc/html/pcrepattern.html#SEC16
> add dupnames pcre flag

- modules/python/CMakeLists.txt
- modules/python/Makefile.am
- modules/python/pylib/syslogng/__init__.py
- modules/python/python-ack-tracker.c
- modules/python/python-ack-tracker.h
- modules/python/python-bookmark.c
- modules/python/python-bookmark.h
- modules/python/python-fetcher.c
- modules/python/python-logmsg.c
- modules/python/python-logmsg.h
- modules/python/python-plugin.c
- modules/python/python-source.c
- modules/python/tests/CMakeLists.txt
- modules/python/tests/Makefile.am
- modules/python/tests/test_python_ack_tracker.c
- modules/python/tests/test_python_bookmark.c
- modules/python/tests/test_python_persist_name.c
This PR adds acknowledgment support for Python sources.
Example:
```Python
from syslogng import LogSource
from syslogng import LogMessage
from syslogng import Logger
from syslogng import InstantAckTracker, ConsecutiveAckTracker, BatchedAckTracker
import signal
signal.signal(signal.SIGINT, signal.SIG_IGN)
import threading
import time
class TestSource(LogSource):
def init(self, options):
self.stop_event = threading.Event()
self.ack_tracker = InstantAckTracker(ack_callback=self.save_bookmark)
self.ack_tracker = ConsecutiveAckTracker(ack_callback=self.save_bookmark)
self.ack_tracker = BatchedAckTracker(timeout=5000, batch_size=100,
batched_ack_callback=self.save_bookmarks)
return True
def deinit(self):
pass
def save_bookmark(self, bookmark):
print(bookmark)
def save_bookmarks(self, …
```
> Python source acknowledgement

- modules/python/python-source.c
In some cases we have a client and ACKs are propagated back
to the message originator. In these cases clients cannot be closed
in a deinit() method as there can be pending ACKs even after deinit().
The finalize() method is for closing these clients when the
PythonSource is freed up.
> python-source: add finalize() method

- scl/cisco/plugin.conf
> scl/cisco: fix clobbered timestamp in case the triplet contains 3 dashes

- modules/kafka/CMakeLists.txt
- modules/kafka/Makefile.am
- modules/kafka/kafka-dest-driver.c
- modules/kafka/kafka-dest-driver.h
- modules/kafka/kafka-dest-worker.c
- modules/kafka/kafka-grammar.ym
- modules/kafka/kafka-internal.h
- modules/kafka/kafka-parser.c
- modules/kafka/tests/CMakeLists.txt
- modules/kafka/tests/Makefile.am
- modules/kafka/tests/test_kafka_topic.c
The librdkafka based Kafka implementation doesn't support template syntax in the topic parameter. This patch implements the same.
The flow is as follows
Case 1 - Topic name isn't a template.
Here, we check if the topic name is valid. If the topic name isn't valid, we return a run time error. Here, we don't need fallback topic even though the grammar allows for the same since its not possible for a message publish failure due to a VALID topic name to be fixed by another valid topic name.
Case 2 - Topic name is a template.
Here, we first check if the topic name is in hashmap. If it isn't present, we check  If it is valid, then we insert the valid topic name into hash map. In case topic name isn't valid, we use the fallback topic which has to be defined(as the driver would generate run time …
> Implement template syntax in the topic parameter for kafka destination

- modules/python/python-debugger.c
- modules/python/python-dest.c
- modules/python/python-fetcher.c
- modules/python/python-helpers.c
- modules/python/python-helpers.h
- modules/python/python-http-header.c
- modules/python/python-logparser.c
- modules/python/python-main.c
- modules/python/python-persist.c
- modules/python/python-source.c
- modules/python/python-tf.c
- modules/python/python-value-pairs.c
- news/bugfix-3405.md
Kudos for @alltilla finding the ordering issue.
If an exception is triggered in python code, such as with the following
configuration[1], normally a message reports in which function what kind of
exception happened. If syslog-ng was compiled with recent clang (10.0) instead of
showing the exception the default None was displayed.
I did not dig into deep enough why this only happens with clang and not with gcc,
it is a good idea - just like in case of ERRNO - to save the exception before
anything else, this patch does exactly that.
Note: also unit test fails due to this issue with clang
[1] configuration that could trigger this issue
```
python {
from syslogng import LogSource
class S(LogSource):
def init(self, options):
raise ValueError('exception')
def run(self):
pass
def …
```
> python: fixing printing None instead of the actual exception

- modules/systemd-journal/journal-reader.c
- modules/systemd-journal/journal-reader.h
- modules/systemd-journal/systemd-journal-grammar.ym
A libc allocation must be deallocated with libc deallocaton (example: strdup -> free),
and the same with glib (example: g_strdup -> g_free).
News file not needed.
> systemd-journal: match g_free with g_strdup

- modules/systemd-journal/journal-reader.c
- modules/systemd-journal/journal-reader.h
- news/bugfix-3407.md
WIP: This PR is a modification on top of #3358 (it should be merged first), however I was unable to open a pull request on: https://github.com/bjoe2k4/syslog-ng
This PR helps to resolve _CURSOR issues in the persist file in case the namespace option changes.
(According to the systemd documentation the _CURSOR identifies an entry. However we got seeking errors in case the namespace parameters changes, even if syslog-ng should seek to the same log entry again.)
This PR also prepares the code to allow multiple systemd-journal sources at the same time. Before systemd v2.45 it was illogical to add multiple journal sources (they could even conflict with each other) so it is prohibited now. However if two journal sources are configured to read from two different namespaces they can work side by …
> Add namespace to the systemd-journal persist name

- lib/afinter.c
- lib/logmatcher.c
- lib/logmsg/logmsg.c
- lib/logmsg/tests/test_log_message.c
- lib/logproto/logproto-framed-server.c
- lib/logproto/logproto-regexp-multiline-server.c
- lib/logwriter.c
- lib/mainloop-worker.c
- lib/mainloop.c
- lib/rcptid.c
- lib/stats/tests/test_external_ctr_reg.c
- lib/template/macros.h
- lib/tests/test_reloc.c
- lib/timeutils/tests/test_unixtime.c
- lib/timeutils/zoneinfo.c
- modules/affile/logproto-file-writer.c
- modules/afsnmp/afsnmpdest.c
- modules/dbparser/patternize.h
- modules/dbparser/pdb-rule.h
- modules/http/http-loadbalancer.h
- modules/python/python-main.c
This was ~~inpsired~~ -> inspired by #3394.
I've ran spellintian (from the lintian package) on dbld devshell image (ubuntu-focal).
Every fix is in comments.
Some seems to be invalid (duplicate word findings sometimes false reports), e.g. `./modules/dbparser/tests/test_timer_wheel.c: latest latest (duplicate word) -> latest`
```
./libtest/mock-transport.c: count count (duplicate word) -> count
./modules/dbparser/tests/test_patternize.c: korte korte (duplicate word) -> korte
./modules/dbparser/tests/test_timer_wheel.c: latest latest (duplicate word) -> latest
./modules/dbparser/pdb-rule.h: the the (duplicate word) -> the
./modules/dbparser/patternize.h: in in (duplicate word) -> in
./modules/python/python-main.c: hanlding -> handling
./modules/http/http-loadbalancer.h: existance -> …
```
> Fix typos found by spellintian

- modules/afprog/afprog.c
- news/bugfix-3416.md
Parent waits for child to close all *fd* before `exec`.
Fixes #3409.
> afprog: manual cloexec

- modules/syslogformat/syslog-format.c
- news/feature-3244.md
- tests/unit/test_msgparse.c
While the RFC5424 states that the maximum length for the SD-ID and PARAM-NAME fields is 32 characters. It also states that a syslog relay should forward messages, even if the SDATA is mailformed.
With this patch, syslog-ng will accept SDATA fields longer than 32 characters, using the message size as the upper limit.
Fixes #3197
> accepting longer sdata keys

- .github/workflows/macos.yml
- contrib/Brewfile
Use `python@3` as `python@2` was removed from brew.
Also did some refactors in the workflow file.
> github-actions: fix macos job

- modules/python/pylib/Makefile.am
- modules/python/pylib/syslogng/debuggercli/__init__.py
- modules/python/pylib/syslogng/debuggercli/editline.py
support BSD licensed `editline` when using debuggercli
motivation: when you have a python without the GPL licensed readline, then you can install [pyeditline](https://pypi.org/project/pyeditline/) for enabling command-completion support. This patch is for enabling completion support also for the built-in debuggercli.
The default is readline - when your python have readline module, then using editline in debuggercli is pointless.
I've tested it my environments and worked as expected.
> Editline debugger cli

- lib/logmsg/nvtable-serialize-legacy.c
- lib/logmsg/nvtable-serialize.c
- lib/logmsg/nvtable.c
- lib/logmsg/nvtable.h
nv_table_serialize can be called from destinations, for example in
LogStore. In destination (logwriter) context, this means these
counters are changed from multiple threads, so they need to be
protected. This patch turns ref_cnt to an atomic counter.
As there are no destinations that serialize messages in ose,
no changenote is necessary.
> nvtable: use atomic refcount

- modules/afsocket/socket-options.c
Added support of *SO_REUSEPORT_LB* socket option, allowing multiple programs or threads to bind to the same port, and incoming connections load balanced using a hash function. The option has been included in [FreeBSD 12.0](https://www.freebsd.org/releases/12.0R/relnotes.html) (https://github.com/freebsd/freebsd/commit/bbf7d4dd035a71710ac94fe1ada4d99244102159).
As continuation for #2379.
> afsocket: added support SO_REUSEPORT_LB

- tests/python_functional/src/syslog_ng_config/statements/sources/network_source.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
The IO layer will be done with Loggen later.
> Light: add basic NetworkSource without IO layer

- lib/logmsg/logmsg-serialize.c
- lib/logmsg/nvtable-serialize-legacy.c
- lib/logmsg/nvtable-serialize.c
- lib/logmsg/nvtable.c
- lib/logmsg/nvtable.h
This patch reverts: https://github.com/syslog-ng/syslog-ng/pull/3434.
As it turns out `nv_table_ref` is not necessary during `nv_table_serialize`: we have a better resolution of the problem in #3434 
Changenote is not needed. This is just a fixup for #3434
> nv_table_serialize: do not nv_table_ref

- lib/afinter.c
- lib/afinter.h
- lib/cfg.c
The `internal()` source currently runs in the main thread, while the main thread main goal is to orchestrate the work and not doing it.
> internal() source running in dedicated thread

- lib/logwriter.c
After this change, these two logs will occur together:
```
Destination timeout has elapsed, closing connection; fd='12'
Destination timed out, reaping; template='/dev/stdout', filename='/dev/stdout'
```
Originally, only the first one was visibe (without verbose
flag). Withouth the context of the second, this can cause confusion.
> logwriter: destination timeout to verbose from notice

- configure.ac
- dbld/packages.manifest
- modules/python/pylib/syslogng/debuggercli/editline.py
With older pkg-config versions (0.27.1 on centos-7) PKG_CONFIG_CHECK_MODULES() macro doesn't check the library's version on multiple calls (if they have the same prefix).
It seems to be that the macro is idempotent.
With version 0.29.1 it is allowed to call the macro multiple times with the same prefix.
See config.log on centos-7 with pkg-config  version 0.27.1, on the second call it simply returns true.
```
configure:18300: checking for libsystemd
configure:18307: $PKG_CONFIG --exists --print-errors "libsystemd >= ${LIBSYSTEMD_MIN_VERSION}"
configure:18310: $? = 0
configure:18324: $PKG_CONFIG --exists --print-errors "libsystemd >= ${LIBSYSTEMD_MIN_VERSION}"
configure:18327: $? = 0
configure:18365: result: yes
configure:18372: checking for libsystemd
configure:18437: result: yes
``` …
> Fix journald namespaces detection on centos-7

- .github/workflows/devshell.yml
* Moving `pytest` and `pylib` linter checks to the `style-check` job, so we get to the `Light` tests sooner.
* Moving `Light` run before `make func-test`, so we get to the `Light` tests sooner.
* Uploading `Light`'s `reports` dir in case of failure.
Example run with failed style checks and failed `Light` checks:
https://github.com/alltilla/syslog-ng/runs/1274648859?check_suite_focus=true
Worth to check the failing jobs and the uploaded artifacts.
> github-actions: Light improvements

- .gitignore
- tests/python_functional/Makefile.am
- tests/python_functional/conftest.py
- tests/python_functional/functional_tests/conftest.py
- tests/python_functional/pytest.ini
- tests/python_functional/src/helpers/loggen/loggen.py
This PR contains some smaller fixes for the light framework:
- updating the .gitignore fil, so git status will not include the reports folder
- eliminate the pytest_plugins variable (Continuation of #3448)
- KUDO for @mitzkia , updating the log_print statement
- add the possibility to insert extra (static) files into the test case folder.
> Light framework small fixes

- modules/afsocket/afinet-dest.c
- modules/afsocket/afinet-source.c
- modules/afsocket/afsocket-dest.c
- modules/afsocket/tests/test-transport-mapper-inet.c
- modules/afsocket/transport-mapper-inet.h
- news/bugfix-3447.md
For TLS certificate hostname verification, the certificate's hostname needs to be compared to the configured hostname
of the primary and each failover server.
TLSVerifier needs the configured hostname of the server to verify the hostname in the certificate.
Previously, the verifier used only the primary host, failover server names were not updated.
> Fix TLS certificate hostname verification when using failover() servers

- news/developer-note-3462.md
- tests/loggen/loggen.c
- tests/loggen/loggen_helper.c
- tests/loggen/loggen_helper.h
- tests/loggen/loggen_plugin.h
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
This PR adds three new command-line option to the loggen to allow the users to define the
source IP, destination IP, and port parameters used in the proxy protocol header.
> Loggen: command line parameters for proxy protocol header

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/logwriter.c
- lib/logwriter.h
- modules/afsocket/afinet-dest.c
- news/bugfix-3474.md
- news/feature-3474.md
- tests/unit/test_logwriter.c
The PR contains the following changes:
* A new option for `LogWriter` based destinations for truncating formatted message length `tuncate_size`, with default not truncating any messages.
* Change the default truncate_size only for udp network destination to 65507.
* New counters indicating truncation:
```
dst.network;d_local#0;udp,127.0.0.1:1111;a;truncated_count;1
dst.network;d_local#0;udp,127.0.0.1:1111;a;truncated_bytes;1
```
* Fix logwriter unit test (`LogWriterOptions` was "hand" initialized)
> option truncating logwriter based destination msg payload size

- lib/timeutils/wallclocktime.c
- modules/timestamp/tests/test_date.c
- news/bugfix-3453.md
- news/feature-3453.md
Our date parser is based on the NetBSD `strptime` implementation, that differs from the linux implementation.
The version of `strptime` used from NetBSD supported local and GMT timezone with `%z` and the `%Z` supported the other timezones. This was changed in linux and also in later version of NetBSD.
In our documentation the newer NetBSD behaviour was written, this patch updates to code accordingly.
> date-parser: extend %z to support time zones other then local and gmt

- modules/afuser/afuser.c
- news/bugfix-3473.md
With this PR, on 1 message there could be multiple error messages (as many as logged in users are for the configured username), this could fill the internal log pretty much.
Nevertheless, I think usertty() destination is mainly intended for alarms and critical log messages, thus logging this much internal  messages is okay.
I don't think a news entry is needed (not a bugfix, and not really something that should be announced).
> usertty: error message on open error

- dbld/prepare-release
This PR fixes a bug in ./dbld/prepare-release, namely the email address and name values are incorrectly propagated into debian/changelog.
> dbld/prepare-release: fix name/email propagation to Debian tools

- dbld/packages.manifest
when `tarball` image was created (#3455), some dependencies (doxygen, docbook-xsl) for distcheck had removed from ubuntu images, therefore from devshell too (which is based on ubuntu focal).
This PR is a quick solution before devshell can be based onto debian testing (#3476).
github actions distcheck job going to be failed for this PR, as docker images are pulled from docker hub and not re-built.
I've tested this on my fork, with locally built docker image pushed to dockerhub under my namespace: https://github.com/gaborznagy/syslog-ng/runs/1395335808
> Fix distcheck on devshell image (ubuntu-focal)

- lib/logmsg/nvtable.h
- modules/afuser/afuser.c
With image-tarball now pointing to debian testing, we are getting extra warnings (and compile failures due to -Werror) because of 
-Wstringop-overflow.
This PR fixes those.
> Fix stringop overflow warnings

- Makefile.am
- configure.ac
- scripts/Makefile.am
- scripts/test-grep.sh
This is an attempt to popularise sanitiser as default option for development.
As of now only cmake supported sanitiser, as a developper using autotools might had harder time to configure and so set as a "default" configure option for themself.
The option is `--with-sanitizer=address/thread/etc`.
This option not a drop in replacement for valgrind, both valgrind and sanitizer cover leaks and memory violations but they won't cover almost the same subset of issues  (but neither of them a subset of the other).
The benefit of using sanitiser opposed to valgrind that sanitizer built into the binary and such it is always on. No need for extra step to check for leaks as well as it is done every time syslog-ng & tests are started.
The current downside is that current syslog-ng violates the odr(one …
> autotools: support sanitizers

- .github/workflows/draft-release.yml
note: name should be the same as in case of previous releases
(-> support scripts polling our repository for new releases)
> github/workflows/draft-release: upload the correct tar.gz

- .github/workflows/comment-on-version-bump-pr.yml
- .github/workflows/devshell.yml
- .github/workflows/gh_export.sh
- .github/workflows/macos.yml
- tests/copyright/policy
Based upon #3484. I have opened a new PR, because this problem just become critical, as `set-env` is removed, and nearly all of our CI jobs fail.
> github-actions: use new env API

- .github/workflows/devshell.yml
- .github/workflows/macos.yml
A test run on my fork:
https://github.com/gaborznagy/syslog-ng/actions/runs/387375769/workflow
> github-actions: run jobs nightly

- dbld/rules
We don't publish .deb/.rpm as a part of release (only a tarball), so
remove them to make builds faster.
> dbld/rules: remove deb/rpm build from the "release" target

- .github/workflows/packages.yml
Since #3464 and #3498 is merged, we could build packages in the nightly job.
> github-actions: build packages nightly

- lib/compat/glib.c
- news/bugfix-3504.md
- tests/functional/test_performance.py
When compiling syslog-ng with old glib versions (< 2.32), our compactibility implementation of `g_cond_wait_until()` is used.
The implementation of the compat call had a bug, which could cause indefinite waiting when `loggen` tries to connect to a TCP/TLS host.
https://github.com/syslog-ng/syslog-ng/blob/f7812c4a1d2fd9e4402f25e85f0cf5940500d50f/tests/loggen/socket_plugin/socket_plugin.c#L199
----
The deprecated `g_cond_timed_wait()` call operates with system wall-clock time, passing `GTimeVal` based on system monotonic time is not valid.
We've found this issue with `tests/functional/test_performance.py`. This test failed due to undefined, but very short timeouts.
A code snippet to reproduce the problem:
https://gist.github.com/MrAnno/6b4ec783a91975177a1028bd357fddbc
Docs:
- …
> glib-compat: fix g_cond_wait_until() with older glib versions (< 2.32) 

- lib/stats/stats-cluster-logpipe.c
- lib/stats/stats-cluster-single.c
- lib/stats/stats-cluster.c
- lib/stats/stats-cluster.h
Reproduction:
1. syslog-ng configuration with at least one network source
2. start syslog-ng with a leak detector
(2.1 optional do restart (in order to have the exact leak as above))
3. stop syslog-ng
```
=================================================================
==2095056==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 8 byte(s) in 1 object(s) allocated from:
#0 0x55a4f86db781 in calloc (/tmp/install/sbin/syslog-ng+0xc5781)
#1 0x7f343f03a941 in g_malloc0 (/usr/lib/libglib-2.0.so.0+0x50941)
#2 0x7f343acb37c7 in _make_connection_conter_stats_queryable /home/user/src/syslog-ng/build/../modules/afsocket/afsocket-source.c:1007:9
#3 0x7f343acb30f3 in afsocket_sd_init_method /home/user/src/syslog-ng/build/../modules/afsocket/afsocket-source.c:1060:5
#4 0x7f343acbc358 in …
```
> fix leaking stats counter_names per creation

- dbld/prepare-release
- dbld/rules
- dbld/validate-release-version
Note: it is enough to merge this PR after releasing 3.30.1, if we manually do these bumps this time for 3.30.1.
> dbld: bump versioning.h in prepare-release

- modules/dbparser/groupingby.c
- modules/dbparser/patterndb.c
- modules/dbparser/tests/test_timer_wheel.c
- modules/dbparser/timerwheel.c
- modules/dbparser/timerwheel.h
- news/bugfix-3515.md
This PR accumulates synthetic messages in an array, and forwards them
after releasing the GroupingBy parser's lock.
It is NOT allowed to call `log_pipe_forward_msg()` when locks are held,
because it would slow down the entire pipeline, and it could also result
in deadlock, for example:
1. A new message is produced in syslog-ng's worker pool, which goes
through the parser, so it acquires `GroupingBy::lock`, and starts
processing the message (continues in step 3).
2. The main thread schedules `grouping_by_timer_tick()`, which needs to
hold `GroupingBy::lock`, so it blocks and waits for the other thread.
3. A new synthetic message is emitted in the worker thread (step 1).
`stateful_parser_emit_synthetic()` is called in
`grouping_by_expire_entry()`, which is protected by `GroupingBy::lock`, …
> grouping-by: fix deadlock when context expires

- .github/workflows/macos.yml
- contrib/Brewfile
Sometimes python2 fails to install in the macOS runner:
```
Using python
Error: Could not symlink bin/2to3
Target /usr/local/bin/2to3
already exists. You may want to remove it:
rm '/usr/local/bin/2to3'
To force the link and overwrite all conflicting files:
brew link --overwrite python@3.9
To list all files that would be deleted:
brew link --overwrite --dry-run python@3.9
Linking /usr/local/Cellar/python@3.9/3.9.1... 
```
There is no point of testing the support for python2 on the latest macOS.
> github-actions: build macOS with --with-python=3

- .github/workflows/devshell.yml
- tests/functional/func_test.py
After merging #3476 some devshell-based jobs failed (they were badly tested, and since github actions uses a previously built balabit/syslog-ng-devshell image CI did not detect the issue either).
As it's discussed in #3476 java modules are not tested in devshell, they are tested with the [binary packages](https://github.com/syslog-ng/syslog-ng/actions?query=workflow:%22Binary+packages%22) CI job.
This PR also fixes a python 3.9 deprecation warning about `base64.decodestring().
> Fix devshell CI

- .github/workflows/macos.yml
- lib/gprocess.c
- news/bugfix-3522.md
man `setrlimit()`:
> It no longer accepts "rlim_cur = RLIM_INFINITY" for RLIM_NOFILE.
> Use "rlim_cur = min(OPEN_MAX, rlim_max)".
Note:
I could have used `sysconf()` to get `OPEN_MAX` in a portable manner, like this:
https://github.com/syslog-ng/syslog-ng/blob/013df12e397eb3bfc40d00f0c1b7cb228d28483f/modules/affile/directory-monitor.c#L57
but I think it's not necessary in this case, as `rlim_cur` can be set to `rlim_max` on all platforms except for macOS.
Fixes #3385.
> gprocess: fix macOS compatibility

- lib/logreader.c
- modules/affile/file-list.c
- modules/affile/file-list.h
- modules/affile/tests/test_file_list.c
- modules/affile/wildcard-source.c
reproduction of the crash:
config:
```
@version: 7.0
log {
source {
wildcard_file(
base-dir("/tmp/input/")
filename-pattern("*")
);
};
destination {
file("/tmp/output.txt");
};
flags(flow-control);
};
```
create a non empty file in /tmp/input/
1. start syslog-ng with the above configuration
2. start an infinite loop with renaming the file created in /tmp/input/
(for example while true ; mv /tmp/input/2 /tmp/input1 && mv
/tmp/input/1 /tmp/input2 ; end)
The crash might occure right away, or after a few minutes.
Signed-off-by: Kokan <kokaipeter@gmail.com>
> affile/wildcard: fix crash when reader replaced

- lib/host-resolve.c
- modules/afsocket/afinet-dest.c
> host-resolve: invalidate ivykis "now" after blocking calls to DNS

- lib/host-resolve.c
#3526 introduced coupling between the host-resolve unit and ivykis.
`iv_now` invalidation is needed because DNS lookup can be a long-running blocking call, and the ivykis time cache has to be invalidated "after any operation that takes a significant amount of wall clock time".
(Similar coupling exists in several syslog-ng units, ivykis operates on global and thread-local states.)
This commit makes `iv_now` invalidation conditional. This avoids crashes when host-resolve functions are called from non-ivykis threads. (An internal module encountered such a scenario.)
> host-resolve: make iv_now invalidation conditional

- dbld/rules
Dependencies of dbld docker images come from:
- manifest files, e.g. dbld/packages.manifest
- packaging files (see dbld/builddeps install_debian_build_deps() and install_rpm_build_deps())
We should check if a dependency is changed in the packaging files.
However rpm spec file and debian control file contain other packaging instructions besides build dependencies.
This means that e.g. when we are releasing, the PR that is opened by "version bump" github actions will re-build the docker images just because of the version bump itself.
@bazsi What do you think of this change?
> dbld: improve cache-image rule

- modules/afsocket/afinet-dest.c
- news/bugfix-3528.md
- news/packaging-3528.md
The problem, we worked around, has been fixed in libnet 1.1.6, which is out in every major distro. The workaround can be safely removed.
Fixes #3525.
~NOTE: Internal testing is still in progress!~
>  afinet: don't disable checksum calculation with spoof-source'd UDP6

- lib/msg-format.c
- lib/msg-format.h
- modules/syslogformat/syslog-format.c
- news/feature-3538.md
- tests/unit/test_msgparse.c
This patch was originally part of #3536 but is split off to a separate PR, as it is a feature of its own right. #3536 would depend on this.
The new header can be used either at a source:
```
source s_udp { 
udp(flags(no-header)); 
};
```
Or with syslog-parser()
```
parser p_syslog {
syslog-parser(flags(no-header));
};
```
The no-header flag means that the syslog header is not present (or does not adhere to the conventions/RFCs), so the entire message (except from the PRI field) is shoved into $MSG.
It is somewhat similar to flags(no-parse), except that no-parse would skip the PRI field too.
> add "no-header" flag to syslog-parser()

- lib/rewrite/CMakeLists.txt
- lib/rewrite/Makefile.am
- lib/rewrite/rewrite-expr-grammar.ym
- lib/rewrite/rewrite-expr-parser.c
- lib/rewrite/rewrite-set-pri.c
- lib/rewrite/rewrite-set-pri.h
- lib/rewrite/tests/CMakeLists.txt
- lib/rewrite/tests/Makefile.am
- lib/rewrite/tests/test_set_pri.c
- news/feature-3546.md
- tests/copyright/policy
This branch adds a new rewrite operation, set-pri() that allows one to set the pri value of the message (e.g. facility * 8 + severity) based on a template string.
The template string needs to expand to a number between in the interval [0, 1023] inclusive, that permits up to 127 facilities.
The format accepted by set-pri() is a simple number, e.g. if you extract this value from a syslog header, the brackets "<" and ">" needs to be removed first.
The format may be extended in the future if use-cases arise, I was thinking of allowing the brackets to be present, or the use of the dot separated, string based format, such as "mail.info".
Fixes #3541
> add set-pri() as a rewrite operation

- lib/logsource.c
- lib/logsource.h
Currently, it is not supported to reconfigure either `log-iw-size()` or the `dynamic-window-size()` option on a kept-alive source. The current behavior is to maintain original window sizes when `keep-alive()` is enabled for a network source. New connections and connections configured with `keep-alive(no)` will, of course, use the recently configured window values.
This commit fixes a crash (underflow) in the dynamic window mechanism by using the static window size that is actually in-use, not `LogSourceOptions::init_window_size`, which may contain a different, recently configured value.
Reproduction steps:
```
log {
source {
network(port(4444) log-iw-size(4000) max-connections(10) dynamic-window-size(100000) keep-alive(yes));
};
};
```
1. Start syslog-ng with the config above
2. Connect …
> Fix crash with dynamic-window-size() when a kept-alive connection is reconfigured

- modules/diskq/qdisk.c
- news/feature-3550.md
No configuration change needed, or option to disable. The directory is created with the same permission as the syslog-ng is running with.
> diskq: create the path specified by dir() if not exists

- news/feature-3558.md
- scl/telegram/telegram.conf
This PR adds support to send telegram notifications in silent mode. 
I have telegram alerting in place for my ssh server. Recently, some enthusiastic hackers tend to wake me up at night with their login attempts. Although fail2ban is in place, a few attempts still generate notifications. Sleep deprivation eventually leads to denial of service, just not for the server, so I thought it would be nice if syslog-ng could send telegram messages without sound.
A new option is introduced: `disable_notification(true/false)`. Default value is "false", same as the original behavior: notification with sound. More on the option(s) here: https://core.telegram.org/bots/api#sendmessage
I also added an `extra-parameters` option, that we can use to quicky add a missing option in the future, without the …
> telegram: support silent mode

- dbld/builddeps
- due to latest get-pip.py not supported with Python2
Issues with the latest get-pip.py
```shell
+ python2 get-pip.py
Traceback (most recent call last):
File "get-pip.py", line 24244, in <module>
main()
File "get-pip.py", line 199, in main
bootstrap(tmpdir=tmpdir)
File "get-pip.py", line 82, in bootstrap
from pip._internal.cli.main import main as pip_entry_point
File "/tmp/tmpksJPUp/pip.zip/pip/_internal/cli/main.py", line 60
sys.stderr.write(f"ERROR: {exc}")
^
SyntaxError: invalid syntax
The command '/bin/sh -c /dbld/builddeps install_pip2' returned a non-zero code: 1
```
> DbldPipInstall: Add Python2 compatible URL for get-pip.py script

- lib/timeutils/tests/test_wallclocktime.c
- lib/timeutils/wallclocktime.c
Since #3453 %Z was converted to allow a missing timezone specifier (porting over https://github.com/NetBSD/src/commit/1ab766532027329c2d69f6c89c0b9b5907553d15)
However, one case was missing: when a non-numeric timezone was specified but we couldn't find a match in nast/nadt/tzname. In that case we errored out, while NetBSD accepted it if the timezone was not mandatory.
I've added unit test coverage for both %z and %Z with this branch and identified another bug (but in this case it is an actual bug in NetBSD too), if the timezone was only using two digits (in the form "+05"), that should be interpreted in HOURs and not minutes. I've fixed that issue too.
@Kokan please let me know if you think this is not right. Thanks
> wallclocktime: fix non-mandatory parsing of timezone name

- lib/apphook.c
- lib/apphook.h
- lib/mainloop.c
- lib/timeutils/CMakeLists.txt
- lib/timeutils/Makefile.am
- lib/timeutils/cache.c
- lib/timeutils/cache.h
- lib/timeutils/tests/test_wallclocktime.c
- lib/timeutils/timeutils.c
- lib/timeutils/timeutils.h
- lib/timeutils/wallclocktime.c
- lib/timeutils/wallclocktime.h
- modules/timestamp/tests/test_date.c
- syslog-ng/main.c
- tests/copyright/policy
@rfaircloth-splunk encountered crashes since 3.30 was released. After looking at the core it turned out that there's a quite severe
race that we triggered with the latest changes in strptime() %z format.
If someone is using "%z" in his config and multiple threads are used (and running due to load), we were crashing every few seconds because of a race on the "tzname" global variable.
I've initially included a number of not-closely related patches within this PR, but I've now split them off to a separate #3561. This now concentrates on the fix and only the fix.
> Fix crash in dateparser %z parsing

- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
This PR adds some missing error handlings to stop() and reload() methods.
> Light: Extend error handlings in SyslogNgCli

- lib/logthrdest/logthrdestdrv.c
- lib/logthrdest/logthrdestdrv.h
- modules/afamqp/afamqp.c
- modules/afmongodb/afmongodb.c
- modules/afsmtp/afsmtp.c
- modules/afsnmp/afsnmpdest.c
- modules/afsql/afsql.c
- modules/examples/destinations/example_destination/example_destination.c
- modules/java/native/java-destination.c
- modules/kafka/kafka-dest-driver.c
- modules/python/python-dest.c
- modules/redis/redis.c
- modules/riemann/riemann.c
- tests/python_functional/functional_tests/source_drivers/internal_source/test_internal_acceptance.py
- tests/python_functional/src/syslog_ng/syslog_ng.py
- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
- tests/python_functional/src/syslog_ng/syslog_ng_executor.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/example_destination.py
- tests/python_functional/src/syslog_ng_config/statements/sources/internal_source.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
Solves #3548 
Based on @bazsi 's instructions: moved every construction into the LogThreadedDestDriver init phase, so from now on *on_config_inited* only starts the constructed workers.
KUDO's for @MrAnno for all the help and second opinions.
> LogThreadedDestDriver move worker (and queue) construction into the init phase

- .github/workflows/devshell.yml
- modules/python/python-dest.c
- news/bugfix-3568.md
When these two objects are passed to `PyObject_SetAttrString()`, their reference counter is incremented. In the next line, we drop our own reference to them with `Py_DECREF()`, but still keep track of them to free it later in `_py_free_bindings()`.
It is not needed, the python lib will take care of the reference, that was added in `PyObject_SetAttrString().
Because we do not need these objects in our code, it is the easiest, to not store them in our struct.
> python: do not double free seqnum and template_options

- lib/logwriter.c
- modules/affile/affile-dest.c
- news/bugfix-3574.md
When reloading configuration, syslog-ng performs the following operations
1. Load modules
2. Initialize modules (calling `%s_module_init`)
3. ...
4. Create log pipes
5. Initialize log pipes
There are two issues:
---
`affile_module_init` calls `affile_dd_global_init` to register an application hook.
However, it doesn't use any flag to avoid registering hook repeatedly.
Therefore, if we reload configuration 1000 times, there will be 1000 entries in `applications_hooks`.
This can be observed by executing the following commands in gdb
```
set $hook=application_hooks
while ($hook != 0)
p *((ApplicationHookEntry*)($hook->data))
set $hook=$hook->next
end
```
---
`affile-dest` creates LogWriter if necessary ([code](https://github.com/syslog-ng/syslog-ng/blob/master/modules/affile/affile-dest.c#L19 …
> Fix improper initialization in affile and LogWriter

- lib/afinter.c
- lib/apphook.c
- lib/apphook.h
- lib/host-resolve.c
- lib/logmsg/logmsg.c
- lib/logmsg/tags.c
- lib/mainloop-control.c
- lib/msg-stats.c
- lib/scratch-buffers.c
- lib/tests/test_apphook.c
- lib/timeutils/timeutils.c
- modules/affile/affile-dest.c
- modules/afstreams/afstreams.c
- modules/java/native/java_machine.c
- news/bugfix-3561.md
- news/developer-note-3561.md
This PR is split off from #3553 which adds a new run-mode for apphooks, namely the ability to be called any number of times
instead of just once. This simplifies a number of locations where the hook needs to re-register itself.
It also contains fixes to minor bugs, where this re-registration was missing.
Right now it depends on #3553, as it converts that call-site to the new API too. If we drop that patch (ie. the last patch) from the series, this can be merged even prior to that.
> Apphook add "REPEAT" run mode for hooks

- modules/kafka/kafka-dest-driver.c
- news/bugfix-3583.md
Delivery_report_callback re-adds the message to the head of the queue for resending.
(with more workers, the message is possibly re-added to a different worker thread's queue than the original worker who tried to sent out the message, as we always poll from worker#0 and re-add the message to worker#0's queue).
The problem was, that the message was re-added to the queue with acknowledgement re-enabled.
This can cause trouble in both flow-controlled and non flow-controlled cases, as even with a flow-controlled log path, the message is already acknowledged since kafka-c driver's insert method returned with SUCCESS, and delivery failure only detected in the delivery_report callback.
Acknowledgement in kafka-c has to be revised, so we can acknowledge at the right time. Currently, flow-control …
> kafka-c: fix double ack on re-added messages

- lib/persist-state.c
Persist file uses a "pre-allocation" mechanism to circumvent some side effects of a running out of space scenario.
More on that in PR #1785, especially in 45a4157.
Thus PERSIST_FILE_WATERMARK must be bigger than any entry we want to store in the persist file. (Including the extra headers and flags.)
One of our internal module has an 8k buffer. Considering the extra space for the headers, the current value is: 8k+256 bytes.
---
Note: I have two alternative follow up plans. Currently work in progress, but I do not want to block this fix: 
A) https://github.com/szemere/syslog-ng/tree/persist_changes_wip Create a static assert on struct sizes. 
B) https://github.com/szemere/syslog-ng/tree/persist_changes_wip2 Eliminate the pre-allocation logic. This way we can always check on the real alloc …
> Change PERSIST_FILE_WATERMARK size

- dbld/builddeps
using "--no-cache-dir" flag in pip install ,make sure downloaded packages
by pip don't cached on system . This is a best practice which make sure
to fetch from repo instead of using local cached one . Further , in case
of Docker Containers , by restricting caching , we can reduce image size.
In term of stats , it depends upon the number of python packages
multiplied by their respective size . e.g for heavy packages with a lot
of dependencies it reduce a lot by don't caching pip packages.
Further , more detail information can be found at
https://medium.com/sciforce/strategies-of-docker-images-optimization-2ca9cc5719b6
Signed-off-by: Pratik Raj <rajpratik71@gmail.com>
> python: use `--no-cache-dir` flag to `pip` in dockerfiles to save space

- modules/python/python-logmsg.c
- modules/python/tests/test_python_logmsg.c
- news/bugfix-3557.md
Previously, the `keys()` method of `LogMessage` returned non-existent keys and duplicates that were part of the name-value registry.
The name-value registry contains all the possible names that are referenced in our codebase or in the syslog-ng configuration.
Reproducer code:
```
rewrite r_neverused { set("${neverused}" value("nonexistent")); };
log {
source { stdin(); };
parser { python(class(Test)); };
destination{ file("/dev/stdout"); };
};
python {
class Test(object):
def parse(self, log_message):
for akey in log_message.keys():
print(akey)
return True
};
```
The above Python snippet prints "neverused" and "nonexistent" as if they were valid name-value pairs of the message, as well as duplicates, because the preceding `log_msg_values_foreach()` call added all keys including regex …
> python: fix LogMessage.keys() listing non-existenting keys and duplicates

- modules/kafka/kafka-dest-worker.c
We increase the ref-count when we publish the message to the kafka broker, and normally decrease it in the delivery callback.
However if the publishing fails, the delivery callback is never called, though the message re-publishing will be re-tried again increasing the ref-count of the same message.
After certain number of retries an integer overflow can happen to the ref-counter, causing an abort on the next call of log_msg_ref.
> kafka: fix missing log_msg_unref in case of failure

- modules/system-source/system-source.c
- news/bugfix-3586.md
Remove the no-parse flag from kernel messages, so the message
header is no more part of the message.
> system source: fix FreeBSD kernel messages

- news/packaging-3587.md
- packaging/rhel/syslog-ng.spec
Simplify spec file by removing obsolete technologies:
- remove RHEL 6 support
- remove Python 2 support
- keep Java support, but remove Java-based drivers (HDFS,
Elasticsearch, etc.)
- minor reorganization to make it more readable
> packaging: simplify spec file for RHEL/Fedora

- .gitignore
- dbld/build/.gitignore
- dbld/install/.gitignore
- dbld/release/.gitignore
dbld/rules in some cases may start docker before calling mkdir for the
above listed directories. This may lead to permission issues, as docker
runs as root and creates those directories with root, but the user
calling dbld/rules may not be root user, thus not able to utilize those
directories.
A possible solution would be to make sure in every execution path the
directories are created before docker run. That is full of trial and
error.
This alternative solution adds those directories to git, and as such
make sures the files exists before even the user able to run dbld/rules.
No news file, neither updating NEWS.md.
Tested in my own fork: https://github.com/Kokan/syslog-ng/runs/2030802765?check_suite_focus=true
> dbld/release: create dbld/{install,release,build} dir before docker does

- .github/workflows/devshell.yml
Note: `cmake` does not generate this log file, but it shows the test case's error while `make check` runs.
> github-actions: cat and upload test-suite.log if make check fails

- dbld/builddeps
This bison version contains the local patch, previously was applied in 5754d6aaea7380b86ca0bb3c2faabe4f63445324
Tested the new bison via the csvparser change: https://github.com/syslog-ng/syslog-ng/pull/3547 
The pip2 link also updated, due to their instruction. 
> The URL you are using to fetch this script has changed, and this one
will no onger work. Please use get-pip.py from the following URL instead:
>
>     https://bootstrap.pypa.io/pip/2.7/get-pip.py
>
> Sorry if this change causes any inconvenience for you!
> dbld: upgrade bison to 3.7.6

- .github/workflows/devshell.yml
- news/packaging-3603.md
As `python2` became EOL and as every syslog-ng packager switched to `python3` (except some old platforms in OBS) we no longer feel the need to support `python2`.
We do not plan to remove the `python2` related code yet, because it would take a lot of effort, but we can easily remove the `python2` related tests from the CI. This means with future changes we might break `python2`, and we will not see it, but we do not plan to support it anyways.
> github-actions: remove python2 tests

- lib/tlscontext.c
TVM_NONE was only used in one place, and it was used in the same
way as "optional-untrusted". So there were no need for it.
However I left the TVM_NONE as the original 0th element of the enum.
Hopefully it will reveal hidden uninitialised issues.
Note: original intention was to modify the behavior of the `tls_session_verify` function, so it will skip certificate validation in case of `peer-verify(none)`.
https://github.com/syslog-ng/syslog-ng/blob/de4997facb5a66c394f625d8562b4923c15425f3/lib/tlscontext.c#L186
> tlscontext: eliminate TVM_NONE when using peer-verify(none)

- lib/logmsg/logmsg.c
- lib/logmsg/logmsg.h
- lib/logmsg/tests/test_log_message.c
- lib/msg-format.c
- lib/msg-format.h
- modules/dbparser/pdbtool/pdbtool.c
- modules/linux-kmsg-format/linux-kmsg-format.c
- modules/linux-kmsg-format/linux-kmsg-format.h
- modules/pacctformat/pacct-format.c
- modules/python/tests/test_python_template.c
- modules/secure-logging/tests/CMakeLists.txt
- modules/syslogformat/syslog-format.c
- modules/syslogformat/syslog-format.h
- modules/syslogformat/syslog-parser-grammar.ym
- modules/syslogformat/syslog-parser-parser.c
- modules/syslogformat/syslog-parser.c
- modules/syslogformat/syslog-parser.h
- news-3565.md
This PR contains a combination of a long-needed msg-format related refactor (moving common code out of format modules into the msg-format layer) and the ability for syslog-parser() to drop incorrectly formatted messages (right now it is only RFC5424 that can indicate invalid messages, RFC3164 consumes everything).
The motivation behind this feature is that more and more rfc5424 style messages are actually incorrectly formatted, while still containing the initial "1 " version indicator right after the priority field. Instead of making the parser less strict, the drop-invalid() setting allows the easy identification of these messages, so that an alternative parser can be applied, like this:
```
@version: 3.30
log {
source { tcp(port(2000) flags(no-parse)); };
if {
parser { …
```
> Syslog parser drop invalid

- .github/workflows/version-bump.yml
- dbld/prepare-release
These changes allowed me to prepare a maintenance release for 3.31.x using github actions.
The changes are:
1) I wanted to manually update the NEWS file as I was cherry-picking patches without NEWS entries
2) I wanted the PR to be opened against the "3.31/master" branch instead of "master"
3) I needed to fix the versioning.h update, as it was incrementing the hex value instead of just calculating it from major/minor
With these the 3.31.2 PR was generated properly.
> GitHub workflow changes to allow maintenance releases

- tests/loggen/loggen.c
- tests/loggen/loggen_plugin.h
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
Fix #3623 incorrect debug message  for loggen
This is because socket-plugin and ssl-plugin is implemented as shared libraries, i.e., libloggen_socket_plugin.so and libloggen_ssl_plugin.so. If these two file have global variables with the same identifier, one of them will become invisible.
Use different names for different loggen plugins based on the filename.
First, we rename the loggen_plugin_info in socket_plugin.c and change all `loggen_plugin_info.name` to `socket_loggen_plugin_info.name` (take it for example, same for ssl_plugin.c):
```c++
PluginInfo socket_loggen_plugin_info =
{
.name = "socket-plugin",
// ...
};
```
Second, we define three Macro in loggen_plugin.h , which will be used later:
```c++
#define LOGGEN_PLUGIN_LIB_PREFIX "libloggen_"
#define LOGGEN_PLUGIN_LIB_SUFFIX …
```
> Fix issue #3623 incorrect debug message for loggen

- lib/cfg-grammar.y
- lib/logpipe.h
- lib/logthrdest/logthrdestdrv.c
- lib/logthrdest/logthrdestdrv.h
- lib/logthrsource/logthrfetcherdrv.c
- lib/logthrsource/logthrfetcherdrv.h
- modules/affile/affile-dest.c
- modules/afprog/afprog.c
- modules/afsocket/afsocket-dest.c
- modules/afuser/afuser-grammar.ym
- modules/afuser/afuser.c
- modules/afuser/afuser.h
- modules/geoip2/tests/test_geoip_parser.c
- modules/kvformat/tests/test_kv_parser.c
- modules/pseudofile/pseudofile-grammar.ym
- modules/pseudofile/pseudofile.c
- modules/pseudofile/pseudofile.h
- news/feature-3585-2.md
- news/feature-3585.md
Support `time-reopen()` option. `syslog-ng` will wait `time-reopen()` seconds (instead of the previously hard-coded 600), when it could not connect to the usertty terminal, then try to connect again.
Add per driver `time-reopen()` option, for drivers, which were previously supporting it, but was not able to set it per driver.
> afuser: support time-reopen() 

- lib/filter/tests/test_filters_regexp.c
PCRE introduced a constraint in pcre 8.34 to named subpatterns: names must start with a non-digit character. [1]
This means that the following pattern is invalid: `(?P<1name>foo)`.
For the current documentation, see: http://pcre.org/original/doc/html/pcrepattern.html#SEC16
[1] https://vcs.pcre.org/pcre?view=revision&sortby=rev&revision=1394
> test_filters_regexp: skip a negative test in case of old libpcre

- lib/timeutils/tests/test_wallclocktime.c
- lib/timeutils/wallclocktime.c
- lib/timeutils/wallclocktime.h
- modules/timestamp/date-parser.c
- modules/timestamp/tests/test_date.c
Fix #3598 date parser incorrect sets seconds
This is because the default value of the `WallClockTime` is -1. After the `mktime()` function is called, we would get an incorrect for undefined filed. For instance, '%Y-%b-%d %I:%M %p%z', where second is not provided.
Adding a new function called `set_default_value_for_undefined` to provided default values for undefined fields. I set the default value as in [strptime](https://docs.python.org/3/library/time.html#time.strptime). In addition, testing coverage is added to the unit test.
Pass unit tests
> Fix issue #3598 date parser incorrect sets seconds

- lib/cfg-tree.c
Fixes https://github.com/syslog-ng/syslog-ng/issues/3429
An empty logpath with flow-control enabled caused syslog-ng to stop in an assert.
```
@version: 3.29
log {
flags(flow-control);
};
```
Th crash:
```
ERROR:/home/furiel/workspace/test-syslogng/syslog-ng/lib/cfg-tree.c:1033:cfg_tree_compile_sequence: assertion failed: (((node->flags & LC_FLOW_CONTROL) && (first_pipe || source_join_pipe)) || !(node->flags & LC_FLOW_CONTROL))
```
News entry: I do not think this worth mentioning in the news file.
> cfg-tree: fix empty config crash

- scl/Makefile.am
The ownership of build user is preserved for some target files, fixed it by
adding --no-same-owner option to tar when extracting files.
Signed-off-by: Ming Liu <ming.liu@windriver.com>
Signed-off-by: Yi Fan Yu <yifan.yu@windriver.com>
> scl: fix wrong ownership during installation

- lib/cfg-grammar.y
- lib/cfg-lexer.c
- lib/tests/test_lexer.c
- modules/kafka/kafka-grammar.ym
- news/bugfix-3658.md
Global keywords could conflict with librdkafka's own configuration keywords. An example of this is the `retries`. This PR fixes that, as in destination/kafka-c/config context temporarly remove the keywords (using mechanism of `CFG_KEYWORD_STOP`).
```
@Version: 3.30
log {
destination {
kafka-c(
topic("test-topic")
bootstrap-servers("localhost:9092")
config(
retries => 1
)
);
};
};
```
> Fix config parsing for kafka-c/config

- packaging/rhel/syslog-ng.spec
After PR #3647 lib/merge-grammar.py has python3 in it's shebang instead of "python",
there is no need for the sed command anymore in the .spec file (python2 is not supported).
Also, the sed expression currently creates an invalid python reference, see result:
`#!/usr/bin/python33`
Packaging CI jobs doesn't hit this issue, as they are creating packages from tarball
(as intended due to bison v3.7.6 which is not yet available on many platforms).
This bug prevented releasing on rpm platforms where the grammar files are changed.
This PR is not critical from OSE release point of view.
> packaging/rhel: remove python3 path fixup in syslog-ng.spec

- lib/compat/CMakeLists.txt
- lib/compat/Makefile.am
- lib/compat/getent-openbsd.c
- lib/compat/getent-openbsd.h
- lib/compat/getent.h
- lib/host-resolve.c
- lib/tlscontext.c
- lib/transport/transport-udp-socket.c
- modules/getent/tfgetent.c
- tests/loggen/loggen_helper.c
This PR fixes the following issues that prevent building syslog-ng on OpenBSD:
* OpenBSD uses a different flavor of reentrant getent functions
* OpenBSD doesn't support IPv4-mapped IPv6 addresses (they are considered harmful)
* OpenBSD uses IP_RECVDSTADDR for UDP dest-IP like FreeBSD does
* tlscontext.c uses AF_INET and AF_INET6 but doesn't include sys/socket.h where they are defined.
> Fix compilation issues on OpenBSD

- modules/openbsd/openbsd-driver.c
- modules/openbsd/openbsd-plugin.c
No news file entry needed (these are compiler warnings, they're not user-visible in my opinion).
> Minor fixes for OpenBSD source

- tests/loggen/loggen.c
- tests/loggen/loggen_plugin.h
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
- tests/python_functional/functional_tests/Makefile.am
- tests/python_functional/functional_tests/tools/loggen/test_loggen_with_reconnect.py
- tests/python_functional/src/helpers/loggen/loggen.py
Fix [#3469](https://github.com/syslog-ng/syslog-ng/issues/3469) loggen should attempt reconnect when destination connections are lost
When destination connections are lost, loggen just stopped sending and never reconnected.
Add a new opt in loggen_options,
```
{ "reconnect", 0, 0, G_OPTION_ARG_NONE, &global_plugin_option.reconnect, "Attempt to reconnect when destination connections are lost", NULL},
```
and if encounter connection_error and option->reconnect is true, try to reconnect.
> Fix issue #3469: add reconnect opt in loggen

- modules/openbsd/Makefile.am
Fixes https://github.com/syslog-ng/syslog-ng/issues/3674
> openbsd: targz missing openbsd grammar files

- modules/afmongodb/afmongodb-worker.c
- news/bugfix-3677.md
Prior to v1.11.0, `mongoc_collection_destroy()` and `bson_destroy()` were not NULL-safe.
https://github.com/mongodb/mongo-c-driver/releases/tag/1.11.0
```
mongoc_collection_destroy(): precondition failed: collection
Abort (core dumped)
```
This is a regression, I broke it in #3621, sorry.
Unfortunately, relatively old mongo-c-drivers are used in different distros. For example, Ubuntu Bionic is affected too, they use v1.9.2.
https://repology.org/project/mongo-c-driver/versions
> mongodb: fix abort with older mongo-c-driver versions

- modules/kafka/kafka-dest-driver.c
Motivation: win smallest syslog-ng PR 2021 award. :)  Real motivation came from #3660.
Existing unit tests cover the refactor.
> kafka: use log_template api in _topic_name_is_a_template()

- contrib/openbsd-packaging/syslog-ng.conf
The syslog-ng.conf file in OpenBSD ports has recently been updated to match the current version of the OpenBSD syslog.conf file.
> contrib/openbsd-packaging/syslog-ng.conf: sync with OpenBSD ports

- modules/syslogformat/syslog-format.c
- news/bugfix-3690.md
- tests/unit/test_msgparse.c
KUDO for @mitzkia
Tried to add a new positive testcase for hostname parsing, spotted this small error.
> Fix hostname parsing

- modules/java-modules/common/src/main/java/org/syslog_ng/logging/SyslogNgInternalLogger.java
- modules/java-modules/kafka/src/main/java/org/syslog_ng/KafkaDestination.java
- modules/java/proxies/internal-message-sender-proxy.c
- modules/java/src/main/java/org/syslog_ng/InternalMessageSender.java
- news/bugfix-3679.md
This PR fixes Java debug logging.
Previously log4j's log level was left on its default value, even when syslog-ng was started in debug/trace mode.
Now the log4j log level is set to syslog-ng's internal log level, so they'll be in sync.
Note:
Currently, the log level is not updated when debug/trace is enabled or disabled at runtime (using syslog-ng-ctl).
----
The class names and their responsibilities can be confusing here:
- `InternalMessageSender` - this is a native Java "proxy" class that can be used to send messages through the `internal()` source.
- `SyslogNgInternalLogger` - this is a log4j log appender implementation, which uses `InternalMessageSender` - it extends `org.apache.log4j.AppenderSkeleton`.
> java(): fix debug logging of Java-based destinations

- dbld/build.manifest
- dbld/builddeps
- dbld/images/debian-sid.dockerfile
- dbld/images/debian-testing.dockerfile
- dbld/images/ubuntu-bionic.dockerfile
- dbld/packages.manifest
As the unofficial OBS repository is discontinued, I checked what depended on it in our CI and dbld.
- Ubuntu Bionic has librdkafka <1.0.0, so we added librdkafka >1.0 from OBS because that is our min. required version and we wanted a full feature set in our devshell image. The devshell image is now based on Debian Testing, therefore this workaround is not needed anymore. Note: The kafka-c destination is no longer built/packaged on Ubuntu Bionic.
- libmongoc had a CMake-only build issue in v1.9.2, thus we used v1.15.0 instead. The devshell image is now based on Debian Testing, so this is not needed anymore. This has no impact on the MongoDB destination's packaging.
The ubuntu-bionic was the last user of `add_obs_repo()` in dbld, so it has been removed as well.
> dbld: remove OBS dependencies from the ubuntu-bionic image

- lib/logmpx.c
- lib/logmsg/logmsg.c
- lib/logmsg/logmsg.h
- news/bugfix-3708.md
In `LogMultiplexer`, checking the number of `next_hops` is not enough to determine the number of `LogPipes`, that will get the current `LogMessage`, because we need to take account of `pipe_next`, too.
See the following log path, for example:
```
log {
source(s_network);
destination(d_http);
rewrite(r_set)
};
```
Here, the `LogMultiplexer` has one `next_hop` (`d_http`) and one `pipe_next` (`r_set`). In this case we do not set the write protection, so the `r_set` rewrite rule will modify the same `LogMessage` that is queued for `d_http`. If the `LogMessage` gets handled in the threaded destination (`d_http`) after `r_set` has changed it, we get an unexpected behavior, in a bad case even a crash.
---
The other problem is that we remove the write protection before forwarding the `LogMessage` …
> logmpx: fix write protecting LogMessage 

- lib/driver.c
- lib/logqueue-fifo.c
- lib/logqueue-fifo.h
- lib/logqueue.h
- news/bugfix-3700.md
When a disk-buffer is removed from the configuration, and syslog-ng is reloaded, syslog-ng starts acquiring a memory queue instead, but first it fetches and tries to use the previous queue from cfg-persist. The type of the old queue is not validated, so we end up using a different type of queue than what the user configured.
This is not a disaster, this behavior could have been documented, but we also crash when trying to use the old queue, because it was not initialized with the queue's own initialization method (`DiskQ::acquire_queue()`).
This PR fixes the crash by safely closing the disk-buffer queue, and allocating a memory queue instead (exactly what the user wants; and unsent messages remain available in the disk buffer file).
Note: switching from a memory queue to a disk-based …
> Fix crash when switching between disk-based and memory queues

- configure.ac
- news/packaging-3713.md
The problem was the new python 3.10 isn't compatible with previous "python finding script", because it check is only 1 digit or "<digit>.<digit>" and I added a new condition to check "<digit>.<digit><digit>".
This bug can be easily caused. Only need a python 3.10 version and run the configure with this flag: "--with-python=3.10" it will not find the 3.10, but with the bugfix it will found.
Other possible solution:
- using if-else instead of switch-case, because in the if statement can be put regex expression.
- using the configure "if-else", because there can put regex expression also. 
issue: #3709
> bugfix/python 3.10 not detected FIX
