modules/riemann/riemann-grammar.ym, modules/riemann/riemann.c, modules/riemann/riemann.h
This makes the riemann destination respect `flush-lines()`, and send event in batches of configurable amount (defaults to 1). In case of an error, all messages within the batch will be retried, and eventually lost if retries do not succeed. Dropped messages, and messages that result in formatting errors do not count towards the batch size.
There is no timeout, but messages will be flushed upon deinit.
This fixes #284.
Requested-by: Fabien Wernli
Signed-off-by: Gergely Nagy <algernon@madhouse-project.org>
=> riemann: Add batched event sending support

lib/cfg-grammar.y, lib/filter/Makefile.am, lib/filter/filter-expr-grammar.ym, lib/filter/filter-expr-parser.c, lib/filter/filter-netmask6.c, lib/filter/filter-netmask6.h, lib/filter/tests/Makefile.am, lib/filter/tests/test_filters.c, lib/filter/tests/test_filters_netmask6.c
usage:
"ipv6address/prefix"
where
ipv6address = valid ipv6 address
prefix = integer number from 1 to 128
Signed-off-by: Fried Zoltan <zoltan.fried@balabit.com>
=> filter: add new ipv6 netmask filter by "netmask6" tag

modules/json/dot-notation.c, modules/json/tests/test_dot_notation.c
When receiving JSON objects whose keys have `@` or `-` characters, it is
currently not possible to extract them with `extract-prefix` since they
are not considered as a valid JS identifier.
In JS, bracket notation should be used instead when accessing such
properties. This is not implemented in syslog-ng as only array indices
can be accessed with this notation.
This commit extends the set of supported characters to `@` and `-`. `-`
can be easily found in the wild while `@` is part of the event log
format of Logstash (`@version` and `@timestamp`).
This commit could be extended to support `$` (which is a valid character
in a JS identifier) but this may conflict with variable expansion. Any
character other than `[` and `.` could be accepted as they don't have a
meaning in the dot notation. …
=> json: accept more characters in `extract-prefix` for `json-parser()`

Mk/subdir.mk, configure.ac, lib/crypto.c, lib/tlscontext.c, lib/tlscontext.h, lib/transport/transport-tls.c, lib/uuid.c, modules/afsocket/Makefile.am, modules/afsocket/afinet-dest.c, modules/afsocket/afinet-source.c, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, modules/afsocket/afsocket-plugin.c, modules/afsocket/tests/Makefile.am, modules/afsocket/tests/test-transport-mapper-inet.c, modules/afsocket/transport-mapper-inet.c, modules/afsocket/transport-mapper-inet.h, modules/afsql/afsql.c, modules/cryptofuncs/cryptofuncs.c, modules/cryptofuncs/tests/test_cryptofuncs.c, tests/loggen/loggen.c, tgz2build/rules
This patch also enables all SSL-dependent features by default.
Signed-off-by: Budai Laszlo <Laszlo.Budai@balabit.com>
=> syslog-ng: set OpenSSL as a hard dependency

modules/csvparser/csvparser-grammar.ym
=> csvparser: add missing | to `csvparser-grammar.ym`, because the delimiters(",") syntax didn't work

modules/afstomp/stomp.c
=> afstomp: fix destination port

syslog-ng-ctl/Makefile.am
When building in parallel, we need to set _DEPENDENCIES, otherwise make might attempt linking syslog-ng-ctl without having the dependencies fully built. Unfortunately, automake cannot infer the libsyslog-ng-crypto dependency from the $(CRYPTO_LIBS) variable, because that is only available at run-time, while we need this kind of dependency at Makefile.in generation time.
The problem does not affect master, because of the crypto merge.
=> syslog-ng-ctl/Makefile.am: Add _DEPENDENCIES for parallel build

lib/logthrdestdrv.c
When syslog-ng got a signal (i.e. SIGTERM) in worker_thread_init(),
it tried to deinitialize itself gracefully, but the watches was not initialized,
so it caused a SIGSEGV.
Signed-off-by: Benke Tibor <tibor.benke@balabit.com>
=> log_threaded_destination: initialize watches before worker_thread_init()

lib/mainloop-worker.c, lib/mainloop-worker.h
as such as existing logthreaded destination
Signed-off-by: MÓZES Ádám István <adam.mozes@balabit.com>
=> external_input_thread: add possibility to create logthreaded source

configure.ac
=> java-version: because of dron.io we should agree jdk 1.6

lib/control/control.c, lib/control/control.h, lib/control/tests/test_control_cmds.c, lib/stats/Makefile.am, lib/stats/stats-counter.c, lib/stats/stats-counter.h, syslog-ng-ctl/syslog-ng-ctl.c
The statistics counters (see the output of "syslog-ng-ctl stats") now can be reset with syslog-ng-ctl stats --reset.
=> syslog-ng-ctl: added counter reset capability 

.travis.yml, configure.ac, doc/Makefile.am
It was not a problem on Debian based platforms. This topic was mentioned more times but the elegant solution was hard to find. Now a new option was created for `./configure` that is `--enable-manpages` that enables the generation of manpages using docbook from online source. `--with-docbook=PATH` gives you the opportunity to specify the path for your own installed docbook.
**Examples**
- `./configure --enable-manpages`: generation from online source
- `./configure --enable-manpages --with-docbook=/usr/share/xml/docbook/stylesheet/docbook-xsl/manpages/docbook.xsl`: generation of manpdocsages using the path given
- `./configure`: no docs will be generated
=> Docbook: there was a hardcoded path that caused build to fail if docbook is not on that path.

Makefile.am, configure.ac
caused `XSL_STYLESHEET` to be empty that's why build failed on Drone.io.
=> Docbook: the lack of `--enable-manpages` option

lib/filter/filter-expr-grammar.ym
The filter_plugin rule expected an LL_IDENTIFIER and filter_comparison
expected a string which in turn is an LL_IDENTIFIER or LL_STRING. It
caused a conflict in the grammar which prevented to load external
filter plugins. See the GitHub issue here:
https://github.com/balabit/syslog-ng/issues/427
Signed-off-by: Tibor Benke <ihrwein@gmail.com>
=> filter: fix external filter plugin lookup

modules/python/sngexample.py
There are indentation problems in modules/python/sngexample.py file, because 3 lines are indented with tab instead of 4 spaces. This caused an error, when I tried to use this example file. This patch will fix this problem.
Signed-off-by: Botond Borsits <borsits.b@gmail.com>
=> python: fixed sngexample.py indentation

modules/riemann/riemann.c
keyword
See 5ea764d6 and [corresponding riemann issue](/aphyr/riemann/issues/545)
=> riemann: also exclude "tags" as attribute which conflicts with reserved

modules/systemd-journal/journald-helper.c
We found journal entries that contained values without an equal sign,
which then caused syslog-ng to crash. Instead of crashing drop these.
=> systemd-journal: drop name-value pairs without an equal sign

.travis.yml, Makefile.am, configure.ac, doc/Makefile.am
Backported docbook-xsl `--enable-manpages` from `3.7/master`.
=> 3.6/f/docbook xsl enable option

modules/afamqp/afamqp.c
This removes the faulty file descriptor set, and should fix the "socket
error" problem.
=> afamqp: fix in the connect process

modules/python/pylib/syslogng/debuggercli/completerlang.py
Local variable 'state' is not in frame 1 anymore, it is in frame 2 in
PLY-3.6 (there is a callback which calls our function this is the reason why
the state variable is in frame 2).
Note that this is an ugly-ugly hack :-)
We have to eliminate this sitation somehow.
=> completerlang: quick fix for PLY-3.6

.travis.yml, README.md
sync within the community.
Badges added to check TravisCI and Drone.io state.
Badge added to Gitter room.
=> Gitter integration added to syslog-ng to make it easier to

modules/afsql/afsql.c
When an insert failed(after retries), syslog-ng didn't drop the connection
and thus an invalid transaction was kept in open state. When a new message
arrived, syslog-ng wanted to append that to the invalid transaction,
which caused failure and the message was dropped.
The problem occured when retries was set to 1.
if (self->failed_message_counter < self->num_retries - 1) // if (0 < 0)
{
// retry AND return false, which means to the caller
// that the connection should be suspended
}
else
{
// drop msg AND return true, which means to the caller
// that connection should be kept open
}
This is why a simple workaround (setting reties to 2) could solve this problem.
fixes #469
=> afsql: fixed retry_sql_inserts(1) isssue

modules/python/pylib/Makefile.am
Run those shell commands in the same subshell.
During Debian packaging execution permission was missing from the test_pylib script
=> pylib: Makefile.am fixed

modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-dest.h
If the host cannot be connected during the initialization of `afsocket` 
destination and it is possible that it can be done later then we will retry it periodically
scheduled by `time-reopen`.
This patch was written in pair with @dnsjts
ref: #318 
=> afsocket: initialization phase was refactored. 

modules/system-source/system-source.c
Kernel messages read from /dev/kmsg may not have accurate timestamps.
The  time  source  used for the logs is not updated after system
SUSPEND/RESUME. With this patch we ignore the original (and possibly
inaccurate) timestamp and use the time of reception.
Fixes #121
=> system: use keep-timestamp(no) in case of Linux kernel log messages

lib/cfg-lex.l
syslog-ng parses configuration in an erroneous way when CR characters are present at line endings,
and will give misleading error messages:
Error parsing main, syntax error, unexpected LL_IDENTIFIER, expecting '}' in dos-ending.conf at line 97, column 20:
facility(local0) and
^^^^
filter f_dp_gwy_app_audit {^M
facility(local0) and^M
host("BTESBDPGWYAppAudit");^M
};^M
Steps to reproduce:
[ERROR]
[WILL WORK OK]
=> cfg-lex: exclude the '\r' character from word declaration

configure.ac
I think the original notion was to fail in this case.
=> configure: fix syntax error in configure

lib/logpipe.h, lib/logwriter.c, modules/affile/affile-dest.c
When a not writeable file becomes writeable later, syslog-ng recognize it and
delivers messages to the file without dropping the messages received during
the file was not available.
Some technical details:
AFFileDestDriver owns one(single file) or more(templated filenames)
AFFileDestWriter objects.
Each AFFileDestWriter is responsible for writing logs to the associated file
via its LogWriter object.
LogWriter object has a LogProtoClient which actually writing the logs.
When a file is not available, proto construction is failed, but it is possible
to create the LogWriter object with empty proto. This is what we are doing.
And the LogWriter object handles a timer (reopen_timer). If the timer is
elapsed, it notifies(NC_REOPEN_REQUEST) the AFFileDestWriter who will
reopen itself by retrying …
=> affile: reopen timer added to logwriter

modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-dest.h
If the host cannot be connected during the initialization of `afsocket` destination and it is
possible that it can be done later then we will retry it periodically
scheduled by `time-reopen`.
This patch was written in pair with @dnsjts
=> afsocket: initialization phase was refactored.

modules/python/Makefile.am, modules/python/pylib/Makefile.am
Conditionally setting .PHONY makes automake very sad. Instead of doing
that, include modules/python/pylib/Makefile.am unconditionally, and add
ENABLE_PYTHON guards there, with the .PHONY dependencies moved out into
an unconditional part.
Signed-off-by: Gergely Nagy <algernon@madhouse-project.org>
=> python: Fix the automake warnings in the Python module

configure.ac
Backported from 3.7.
Original patch is written by Tibor Benke <tibor.benke@balabit.com>
=> configure: fix syntax error around libsystemd-journal handling

configure.ac
The problem was, that the enable_python variable wasn't set to 'no',
when with_python was 'no'.
--with-python now accepts parameters, like --with-python=2,
--with-python=2.7, --with-python=auto. The --with-python=yes case was
removed, because --enable-python replaced this behavior.
=> configure: fix python related make distcheck problems

doc/man/syslog-ng.8.xml
Manpage entry added referring --control option for it was missing
from the docs only mentioned in program help.
fixes #436
Signed-off-by: Gregory Nagy <gergo.nagy@balabit.com>
=> docs: manpage entry for --control option

.travis.yml, modules/java/Makefile.am
=> java: do not build the SyslogNg.jar into the pre-built release tgz.

lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c
allowed values: no-sslv2, no-sslv3, no-tlsv1, no-tlsv11, no-tlsv12, none
I think, they are self-explanatory.
Signed-off-by: PÁSZTOR György <gyorgy.pasztor@balabit.com>
=> ssl_options() option inside tls()

modules/java/Makefile.am
This patch fixes the following build error (make dist, make distcheck)
on machines without java support:
make: *** No rule to make target `modules/java/LogDestination.h',
needed by `distdir'.
$(JAVA_HEADER_FILES) are generated files which will be generated only
when java is enabled, however `make dist` (or `make distcheck`) 'uses'
`modules_java_libmod_java_la_SOURCES`.
=> jave: Makefile.am fixed

configure.ac, modules/afsocket/transport-unix-socket.c, modules/afsocket/unix-credentials.h
fixes #542
Signed-off-by: Adam Arsenault <adam.arsenault@balabit.com>
=> afsocket: using msg_control only when credential passing is supported

contrib/README.syslog-debun, contrib/syslog-debun
* On certain situations, like in ubuntu's own syslog-ng package, the pidfile is not in $vardir/run, it is in the $vardir. Now it is handled correctly.
Signed-off-by: PÁSZTOR György <gyorgy.pasztor@balabit.com>
=> contrib/syslog-debun: minor fix

modules/afstomp/tests/Makefile.am
Tests should not be run if the user didn't request its
support. Otherwise, we get the following error during compilation:
libtool: link: cannot find the library `./modules/afstomp/libafstomp.la' or unhandled argument `./modules/afstomp/libafstomp.la'
Makefile:6141: recipe for target 'modules/afstomp/tests/test_stomp_proto' failed
make[3]: *** [modules/afstomp/tests/test_stomp_proto] Error 1
Signed-off-by: Vincent Bernat <vincent@bernat.im>
=> afstomp: don't run tests when disabled

modules/Makefile.am, modules/systemd-journal/tests/Makefile.am
This was the only module to not have an entry in the top `Makefile.am`
file in `modules_test_subdirs`. Also, ensure tests are not run when the
support is not enabled.
Please note, that I don't fully understand the change I made. This could be a terrible mistake. :)
=> systemd-journal: ensure tests are run only when enabled

contrib/syslog-debun
* generalized service stop & starts: default: /etc/init.d/...
* Handel Solaris 10+ systems, where there is no /etc/init.d/, but SMF is there
* generalized alive pid check, later it can be easily portable for systems where no procfs is
* save the service "status" info .pre and .post
* the test's binary -a has less precedence over the unary -a, and it cause problems under special circumstances, so [ exp1 -a exp2 ] => [ exp1 ] && [ exp2 ]
* when the tracing and debug mode is used at the same time, and we killed the tracing pid, the debugging process were left there, and the system's syslog service could not be restarted, since the old debug process locked the resources (eg. /dev/log )
Signed-off-by: PÁSZTOR György <gyorgy.pasztor@balabit.com>
=> contrib/syslog-debun: portability improvements and fixes

configure.ac
The name of the `--with-docbook-dir` parameter was wrong. (Wrong documentation string.)
fixes #572 
=> configure.ac: docbook dir option name corrected

modules/json/dot-notation.c, modules/json/json-parser.c
Starting from jsonc 0.10, `json_object_is_type()` started handling NULL
appropriately. With previous versions, calling this function with NULL
would lead to a segfault.
The version embedded in syslog-ng is recent enough. This fix is for
people using `--with-jsonc=system` and having a too old system jsonc
library (like the one in Ubuntu Precise).
I have experienced the "bug" in `json/json-parser.c`. I think that the "bug" could also be triggered in `dot-notation.c` but I can't be sure. The test may be unneeded.
Not using embedded libs is a common culture in distributions and is useful to get security updates (jsonc had several CVE fixes in the past). So, I think the use case is valid, but I can understand if it would be dismissed.
=> json: do not rely on json_object_is_type() accepting NULL

lib/misc.c, lib/misc.h, modules/java/native/java-destination.c, modules/python/python-dest.c, modules/python/python-dest.h, modules/python/python-grammar.ym, modules/python/python-parser.c, modules/python/sngexample.py
Arguments can be passed to python destinations
using `options` token in the config file.
Example:
```
log {
source { tcp(port(12345));  };
destination {
python(
class("sngexample.DummyPythonDest")
options(
key1("value for key1")
key2("value for key2")
)
);
};
};
```
Fixes #535
Created-with: Arsenault Adam <adam.arsenault@balabit.com>
=> python: passing arguments from `syslog-ng.conf`

modules/afprog/afprog.c
=> afprog: do not send SIGTERM when getpgid() fails

requirements.txt
This PR fixes the `drone.io` build failures.
There is a version conflict between the installed Python eggs.
This commit solves it by choosing the proper version so the
unit tests are OK again.
=> requirements: add logilab-common as a dependency

modules/java-modules/Makefile.am, modules/java-modules/common/build.gradle, modules/java-modules/elastic/build.gradle, modules/java-modules/hdfs/build.gradle, modules/java-modules/kafka/build.gradle, modules/java/Makefile.am
For building on OBS, offline jars are necessary because OBS builders don't have
internet access. This patch makes gradle first check a local folder for jars.
Signed-off-by: Arsenault Adam <adam.arsenault@balabit.com>
=> java: modified java modules to allow local caching of jar files

lib/Makefile.am, lib/misc.c, lib/misc.h, lib/msg-format.c, lib/msg-format.h, lib/stats/stats-csv.c, lib/tests/Makefile.am, lib/tests/test_utf8utils.c, lib/utf8utils.c, lib/utf8utils.h, libtest/template_lib.c, modules/json/format-json.c, modules/json/tests/test_format_json.c, modules/syslogformat/syslog-format.c
This branch does a couple of things:
1) implements proper utf8 sanitization for untrusted output (two kinds actually, but read those in the patches)
2) migrates stats and format-json to use these
3) implements sanitize-utf8 as an input flag
The last one should probably be a separate branch as it's a new feature, the other two is just refactors. My original intent was to port $(format-welf) that would be using these new functions, but I didn't get there so far.
PS: I know that the syslog-format code that implements sanitize-utf8 is ugly with the GString mockery, however it is a fast path and I wanted to avoid a GString object allocation. I also know that there's a syslog-format refactor en-route, which probably conflicts with this change, so feel free to integrate only the first few …
=> utf8 sanitization

lib/value-pairs.c
This patch makes it possible to use value-pairs expressions like this:
$(format-json MSG DATE)
instead of
$(format-json --key MSG --key DATE)
=> value-pairs: make it possible to pass --key as a positional argument

lib/cfg-grammar.y
Mark mode setting is set and used from options section.
Fixes #547 
Signed-off-by: Fried Zoltan <zoltan.fried@balabit.com>
=> grammar: apply configured mark mode on options section

modules/java-modules/Makefile.am
Without setting GRADLE_USER_HOME (via -g option), build fails on OBS.
Redirection of gradle log also eliminated in order to make available build logs
in OBS log (and to provide feedback to users who build syslog-ng from source,
see #585 ).
=> java: set GRADLE_USER_HOME in Makefile.am for java-modules

modules/java/Makefile.am
Syslog-ng's classloader didn't find syslog-ng-core.jar because it only
searched in lib/syslog-ng/java-modules. This commit installs all *.jar files
under lib/syslog-ng/java-modules so the classloader will find them.
Fixes #594
Fixes #595 
=> java: install all *.jar files under lib/syslog-ng/java-modules

modules/java/Makefile.am
Included the previously-unincluded JNI_LIBS flags for linking
libmod-java to libjvm.so.
Fixes #596
Signed-off-by: Arsenault Adam <adam.arsenault@balabit.com>
=> java: Fixed libjvm linking

.travis.yml
Java support requires:
* gradle-2.2.1
* openjdk-7-jdk
(gradle-2.2.1 is provided by the OBS repo)
Fixes #612
=> .travis.yml: Java support added

configure.ac
`with-docbook` option was misleading for it showed that you should pass the path to the `.xsl` file not to the directory of `docbook`. This notation was provided by @faxmodem and fixe in `3.7`. The new name shows that you should pass the directory of docbook because that path is different in many distros.
This is only a patchport.
=> configure.ac: 'with-docbook' option renamed

modules/syslogformat/syslog-format.c, tests/unit/test_msgparse.c
Fixed logic and made clearer the inference of year from bsd-style
rfc3164 syslog-messages, which do not include a year.
Signed-off-by: Adam Arsenault <adam.arsenault@balabit.com>
=> syslogformat: Fixed bsd year inference

lib/timeutils.c, tests/unit/test_zone.c
when we run the command `date 010100001970.00` after the
syslog-ng daemon restart. The timestamp in the log file
have the wrong value to be record:
1900-01-00T00:00:00+00:00 localhost syslog-ng[18736]: ....
1900-01-00T00:00:00+00:00 localhost syslog-ng[18736]: ....
....
....
1970-01-01T00:00:01+00:00 localhost syslog-ng[18736]: ....
1970-01-01T00:00:01+00:00 localhost syslog-ng[18736]: ....
after one second later, it becomes ok.
This reason for this error is the improper initialization for
gm_time_cache. so this patch fix that and add the testcase.
Signed-off-by: Wang Long <long.wanglong@huawei.com>
=> timeutils: Fix the cached_gmtime error

modules/afsocket/transport-mapper-unix.c
=> transport-mapper-unix: remove the second typedef of _TransportMapperUnix

lib/gprocess.c
--fd-limit can still override this, but the default will be configured based on
existing system limits.
Issue: https://github.com/balabit/syslog-ng/issues/646
Signed-off-by: Avleen Vig <avleen@gmail.com>
=> Make the default for RLIMIT_NOFILE equal to the current system limits.

modules/redis/redis.c
It's just a forward port from 3.6, please merge.
[we missed it somehow...]
=> redis: free reply object after a succesful ping

modules/dbparser/radix.c
Fixes #658
I'm not the original author I just copied the diff into this commit.
Author: Balazs Scheidler <balazs.scheidler@balabit.com>
=> dbparser: handle NULL value for the match parameter in r_parser_email()

contrib/systemd/syslog-ng.service
The systemd service file does read `/etc/default/syslog-ng` and `/etc/sysconfig/syslog-ng`, but doesn't do anything with their contents. The `ExecStart` line should include `$SYSLOGNG_OPTS` and whatever the variable is called on RedHat too.
=> systemd service file only half-respects /etc/default/syslog-ng

modules/python/pylib/Makefile.am
When installing the python modules, allow overriding the options. This is useful for distributions that want to pass extra options. For example, on Debian, we want `--install-layout="deb"` instead of the `--prefix` and `--root` options.
With this change, the previous behaviour remains the default, but one can supply `PYSETUP_OPTIONS` on the make command-line to override it.
=> Allow overriding the python setup.py options

Makefile.am, doc/Makefile.am
I recently started to update my Debian packaging, and noticed that when using the [tarball release](https://github.com/balabit/syslog-ng/releases/download/syslog-ng-3.7.1/syslog-ng-3.7.1.tar.gz), after a ./configure && make && make install, the xsd files are not installed for some odd reason.
I have not tried building from a git checkout yet.
=> make install fails to install patterndb xsds

modules/afsocket/afsocket-dest.c
And, thus, do not replace writer when protocol not changed during reload.
This is actually a backport.
=> afsocket: replace writer only when protocol changed during reload

lib/logmsg.c, lib/logmsg.h
I need this change for my Rust bindings. I have to use `&mut LogMessage` references every time I call this function and that prohibits of using other read only references till the mutable one goes out of scope.
Signed-off-by: Tibor Benke <ihrwein@gmail.com>
=> logmsg: make log_msg_values_foreach() take the receiver as const pointer

modules/afsocket/afsocket-source.c
https://github.com/balabit/syslog-ng/issues/695  
afsocket_sc_init should also fail after tls_context_setup_session failed
transport_mapper_inet_construct_log_transport can probably only return NULL in TLS cases.
This is why the issue surfaced for TLS.
It causes a segfault for any kind of TLS error.
=> Fix #695: Segfault on TLS errors

modules/afsmtp/afsmtp-grammar.ym
PR #419 introduced some inconsistencies in the grammar. I took the
chance to eliminate all tabs and use the same convention through the
whole file.
Fixes #638
=> afsmtp: fix grammar inconsistencies in the grammar

scl/Makefile.am, scl/mbox/mbox.conf
This source can be used to fetch emails from local mbox files:
source { mbox("/var/spool/mail/root"); };
This will fetch root emails and parse them into a multiline $MSG.
Original implementation by Fabien Wernli, I only converted it into
an SCL.
=> scl: add mbox() source

modules/afsocket/transport-unix-socket.c
This bug was reported by valgrind, readlink() does not null terminate
data, so do that explicitly.
=> afsocket: fix use-of-uninitialized data

lib/cfg-grammar.y
=> cfg-grammar: fix template_fn memory leak

lib/cfg.c
The global template options were not properly initialized as the
log_template_options_init() call was missing.  This meant that the few call
sites that use GlobalConfig->template_options directly (for instance the
debugger), didn't use the time-zone related parameters, as the TimeZoneInfo
pointers were not initialized.
=> cfg: initialize global options

lib/logwriter.c, lib/ml-batched-timer.c
The problem is that if the reload is fast enough (done in 1sec),
then the mark_timer will be unregistered without resetting the expire time in the log_writer_deinit.
In the log_writer_init the mark_timer will be updated, but it won't be updated,
because the new expire time will be the same as the current expire time
and because of the "race condition shield" in the ml_batched_timer_update the timer won't be registered.
In case of deinit we should cancel the mark_timer instead of unregister,
because the cancel reset the expire date to 0.
fixes #701
=> periodical-mark-mode: cancel the mark_timer instead of unregister it

modules/java-modules/http/src/main/java/org/syslog_ng/http/HTTPDestination.java, modules/java-modules/http/src/main/java/org/syslog_ng/http/HTTPDestinationOptions.java
HTTP destination is now able to receive HTTP method as an option.
The new option can be passed using `method(<METHOD>)`.
valid methods:
* PUT
* POST
fixes #668
=> java-modules: http destination improvements

lib/cfg.c
When a name-value pair is added to the persist config then the user
can set a destroy function which can be called in two cases:
a) when the key is already added to the hash table
b) config doesn't have PersistConfig
For case b) syslog-ng check whether the destroy function is set or not and
calls only when it is set.
For case a) this patch fix the issue.
=> cfg.c: call destroy() only when it is set in cfg_persist_config_add()

scl/elasticsearch/plugin.conf, scl/hdfs/plugin.conf, scl/kafka/plugin.conf
unfortunately we make a mistake around java SCL-s: in the header we used C comment marks instead of the '#'
please, merge
=> scl: fixed comment marks in java SCLs copyright headers

lib/logsource.c
When the name of the host is too long, the buffer we use to format the
chained hostname is truncated. However g_snprintf() returns the length the
result would be if no truncation happened, thus we will read uninitialized
bytes off the stack when we use that pointer to set $HOST
with log_msg_set_value().
There can be some security implications, like reading values from the stack
that can help to craft further exploits, especially in the presense of
address space randomization. It can also cause a DoS if the hostname length
is soo large that we would read over the top-of-the-stack, which is probably
not mmapped causing a SIGSEGV.
Reported-by: Badics, Alex <alex.badics@balabit.com>
=> logsource: validate hostname length in log_source_mangle_hostname()

tests/unit/test_zone.c
=> tests: unit/test_zone.c LogStamp uninitialized field fixed

syslog-ng.pc.in
If a program wants to compile something which includes headers from syslog-ng then it needs to know that eventlog is also needed.
Signed-off-by: Tibor Benke <ihrwein@gmail.com>
=> syslog-ng.pc: add eventlog as a required package

lib/logmsg.c
Explanation for the diff:
* `#define ACKTYPE_TO_ABORTFLAG(x) (x == AT_ABORTED ? 1 : 0)`
* AT_ABORTED is equal to 2
Therefore the second check will fail always.
This issue has been found by Coverity Scan.
CID: 41449
Related Common Weakness Enumeration: CWE-569.
The report can be found here:
https://scan4.coverity.com/
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/balabit/syslog-ng/751)
=> logmsg: Fix a logmsg_cached_abort assignment

modules/redis/redis.c
Fix a SIGSEGV when redis result of command return an error.
Fixes #754
Signed-off-by: Fried Zoltan <zoltan.fried@balabit.com>
=> redis: Return error result when redis command is failed

modules/afprog/afprog-grammar.ym, modules/afprog/afprog-parser.c, modules/afprog/afprog.c, modules/afprog/afprog.h
This pull request adds the possibility of letting the program destination unclosed and reused between configuration reloads.
New option: `keep_alive(x)`, where `x` is either `yes` or `no`.
The default behaviour has not been changed.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/balabit/syslog-ng/722)
=> Keep the program destination open between configuration reloads

lib/pathutils.c, lib/pathutils.h, modules/affile/affile-common.c
It could be changed only if the file (source or destination) is not
a device because all devices are system entity in filesystem. 
Fixes #383 
Signed-off-by: Fried Zoltan <zoltan.fried@balabit.com>
=> file: avoid change file permission if file is device

modules/afsocket/transport-unix-socket.c
The reason is that the function return value is a -1 on error, however
the variable to store that is unsigned, therefore it is unable to store
the error value and will underflow. The subsequent check will therefore
not catch the error.
To fix this change content_len from gsize (unsigned) to gssigned
(signed).
This was found with Address Sanitizer.
Fixes https://github.com/balabit/syslog-ng/issues/780
=> Fix an integer underflow.

modules/kvformat/linux-audit-scanner.c, modules/kvformat/tests/test_linux_audit_scanner.c
Argument lists are encoded in a0, a1, ... fields that can potentially be
hex-encoded.
=> linux-audit-scanner: recognize a0-a9* as fields to be decoded

modules/afprog/afprog.c
This pull request fixes the warning messages found in #776 .
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/balabit/syslog-ng/779)
=> Fix warning messages in afprog

scl/Makefile.am, scl/apache/apache.conf
This parser consumes both the "common" and "combined" log formats and
parses them into name value pairs prefixed with ".apache." (but can be specified using the
standard prefix() option). 
The name-value pairs match the one that logstash uses, so it is pretty easy to use syslog-ng to forward apache logs to elasticsearch and display it with kibana.
It also extracts the timestamp of the apache log entry properly, relying on the brand new date-parser().
=> scl: add apache-accesslog-parser()

configure.ac, modules/afamqp/Makefile.am
Currently only the internal librabbitmq-c is supported,
if we want to use the preexisting library, the configuration
will fail.
This change is required if we want to get rid of the
internal libraries.
[<img src="https://reviewable.io/review_button.png" height=40 alt="Review on Reviewable"/>](https://reviewable.io/reviews/balabit/syslog-ng/752)
=> afamqp: support systemwide librabbitmq-c

scl/Makefile.am, scl/loggly/loggly.conf
Examples:
```
Just send all syslog to loggly:
log {
source { system(); };
destination { loggly(token("USER-TOKEN-AS-PROVIDED-BY-LOGGLY")); };
};
Send JSON data:
log {
source { system(); };
destination {
loggly(token("USER-TOKEN-AS-PROVIDED-BY-LOGGLY")
template("$(format-json --scope all-nv-pairs)"));
);
};
};
Send already parsed apache logs to loggly:
log {
source { file("/var/log/apache2/access.log" flags(no-parse)); };
parser { apache-accesslog-parser(); };
destination {
loggly(token("USER-TOKEN-AS-PROVIDED-BY-LOGGLY")
tag(apache)
template("$(format-json .apache.* timestamp=${ISODATE})"));
};
}
```
as requested by @fekete-robert  and fixes #798
=> scl: add loggly() destination

scl/Makefile.am, scl/logmatic/logmatic.conf
This patch implements an integration with logmatic.io.
Examples:
Just send all syslog to logmatic:
log {
source { system(); };
destination { logmatic(token("API-KEY-AS-PROVIDED-BY-LOGMATIC")); };
};
Send JSON data:
log {
source { system(); };
destination {
logmatic(token("API-KEY-AS-PROVIDED-BY-LOGMATIC")
template("$(format-json --scope all-nv-pairs)"));
);
};
};
Send already parsed apache logs to logmatic:
log {
source { file("/var/log/apache2/access.log" flags(no-parse)); };
parser { apache-accesslog-parser(); };
destination {
logmatic(token("API-KEY-AS-PROVIDED-BY-LOGMATIC")
tag(apache)
template("$(format-json .apache.*)"));
};
}
=> scl: add logmatic() destination

lib/cfg-lex.l
The code generated by flex contains yy_fatal_error() which is not used in
the generated code. Insert an artificial reference so that it doesn't
get reported.
=> cfg-lex.l: don't report yy_fatal_error() as an unused symbol

modules/python/pylib/syslogng/debuggercli/completerlang.py, modules/python/pylib/syslogng/debuggercli/readline.py, modules/python/pylib/syslogng/debuggercli/syslognginternals.py, requirements.txt
My #696 failed because some pylint errors. This PR updates some python dependencies and fixes the freshly introduced warnings.
=> Fix pylint errors

modules/afstreams/Makefile.am, modules/afstreams/afstreams-grammar.ym, modules/afstreams/afstreams-parser.c, modules/afstreams/afstreams.c
=> afstreams: get rid of superfluous conditional compilation

modules/affile/affile-grammar.ym, modules/afprog/afprog-grammar.ym, modules/afsocket/afsocket-grammar.ym, modules/afstreams/afstreams-grammar.ym, modules/geoip/geoip-parser-grammar.ym
Fixes #786
Modules
Legend:
* `not needed` (to change): everyting was ok
* `(doesn't have grammar)`: the module doesn't have a grammar file
This PR depends on PR (I have to rebase this after it's merged) #819.
=> fix double-free in yydestruct

.travis.yml
Somehow, nowadays the infrastructure is unhealthy and some flags remain
set that interfere with autoconf include directory detection.
=> .travis.yml: unset PYTHON_CFLAGS

lib/template/macros.c
=> macros: remove lurking semicolon after if statement

modules/afprog/afprog-grammar.ym, modules/afprog/afprog-parser.c, modules/afprog/afprog.c, modules/afprog/afprog.h
Source/destination program used to inherit the entire environment of the parent process.
This pull request introduces a configuration option which can turn off this behavior.
=> Can turn off inheritance of environment variables in program destinations/sources

modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/ESClient.java, modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/ESNodeClient.java, modules/java-modules/elastic/src/main/java/org/syslog_ng/elasticsearch/client/ESTransportClient.java
Previously, this feature was available only for node mode.
By supporting loading native elasticsearch config, it is possible now
to use Shield with syslog-ng.
When you want to use Shield, you have to add elasticsearch-shield-1.3.3.jar
to your classpath.
```
shield.ssl.keystore.path: /home/test/es/shield/client.jks
shield.ssl.keystore.password: qqq123
shield.transport.ssl: true
shield.user: es_admin:qqq123
```
```
@version: 3.8
destination d_elastic {
elasticsearch(
client_lib_dir(/usr/share/elasticsearch/lib)
client_mode("transport")
cluster("es-syslog-ng")
index("es-syslog-ng")
port("9300")
server("vagrant-es-server")
type("slng_test_type")
resource("/opt/syslog-ng/etc/elasticsearch.yml")
);
};
```
Fixes: #826
=> Support native Elasticsearch configuration for transport mode

.gitmodules, autogen.sh, configure.ac, modules/afmongodb/Makefile.am, modules/afmongodb/afmongodb-grammar.ym, modules/afmongodb/afmongodb-parser.c, modules/afmongodb/afmongodb.c, modules/afmongodb/afmongodb.h, tests/collect-cov.sh
Rebased and migrated https://github.com/balabit/syslog-ng/pull/728
Should be almost the be the same codebase, except:
* added a missing g_free(uri)
* reordered two variables
* deleted an extra lines
After `somebody` does sanity checking to verify that the rebase went alright and they like the squashed commit organization, it would be ready for merge from my perspective.
Please assign it to someone else if you are assigned and you don't have time for this.
=> Use official MongoDB C Driver instead of libmongo-client

modules/java-modules/http/src/main/java/org/syslog_ng/http/HTTPDestination.java
Fixes: #669 
Signed-off-by: Laszlo Varady <laszlo.varady@balabit.com>
=> Log HTTP response error codes in HTTP destination

lib/str-utils.h, lib/tests/Makefile.am, lib/tests/test_str-utils.c, lib/utf8utils.c, modules/csvparser/csv-scanner.c, modules/syslogformat/syslog-format.c
…for strchr()
This patch adds an optimized version of strchr() that is often used by
$(format-json) to output escaped strings, which improves $(format-json)
performance by about 3 percent.
=> Improve the performance of utf8-utils by using an optimized implementation of strchr()

Mk/Makefile.am, configure.ac, scl/Makefile.am, syslog-ng.pc.in
following up PR #628 that tries to address issue #587.
this PR solves the issue and also cleans up related configure.ac/Makefile.am machinery a bit.
Please note @lbudai, @czanik that once this gets integrated, the --datadir configure option should be removed from debian/rules and rpm specfiles, as it will generate paths like:
/usr/share/syslog-ng/syslog-ng/scl & /usr/share/syslog-ng/syslog-ng/tools
I am not sure where and how we should open tickets about the packaging files to avoid getting lost.
=> Clean up configure directory

lib/cfg-grammar.y
Fixes #865 
The original bugreport is somewhat invalid, because the tested commit was made in nov 30. The mentioned issue cannot be reproduced today with the current master, but it "forced" me to recheck the grammar files.
https://github.com/balabit/syslog-ng/pull/817 eliminated the possible double frees in the modules, but I didn't check the grammar files under lib.
This PR fixes the possible double frees in the grammar files under lib/. AFAIK there is none file left out.
=> Fix possible double-frees in yydestruct

modules/dbparser/patterndb.c
patterndb: the set emit function is possible to callback to the mainloop.
But if the mainloop currently runs the tick_timer of the patterndb,
it causes deadlock, because the timer wait for the patterndb's lock (held by the _pattern_db_process)
and the emit function waits for the mainloop.
Solution is, that unlock the lock, while the emit functions are run
=> Fix possible deadlock in patterndb

lib/filter/filter-netmask6.c
=> Fix byteorder handling on bigendian systems in netmask6 filter

.travis.yml
This switch is added in order to show as many compilation error
as possible, therefore the output of a failed Travis CI build might be
more valuable.
[<img src="https://reviewable.io/review_button.svg" height="40" alt="Review on Reviewable"/>](https://reviewable.io/reviews/balabit/syslog-ng/895)
=> travis.yml: add --keep-going to make

modules/afsocket/afunix-source.c, modules/afsocket/afunix-source.h
Fixes: #894 
The global `create-dirs` and `pass-unix-credentials` options were not
inherited in afunix-source if the `options{};` block was positioned lower in the
configuration file than the given module declaration.
This pull request fixes this issue by moving the "inheritance" assignment from
`afunix_sd_new_instance` to `afunix_sd_init`.
=> Fix global option inheritance in afunix-source

m4/check_java_support.m4
configure --enable-java doesn't work for me (syslog-ng 3.7.2):
checking for JAVA_VERSION... ./configure: 16173: test: 1: unexpected operator
=> fix java version check ('test' has '=', not '==' as operator)

.travis.yml, modules/python/pylib/syslogng/debuggercli/completerlang.py, modules/python/pylib/syslogng/debuggercli/readline.py, modules/python/pylib/syslogng/debuggercli/syslognginternals.py, requirements.txt
From #837:
> Somehow, nowadays the infrastructure is unhealthy and some flags remain
set that interfere with autoconf include directory detection.
Also from #815:
> This PR updates some python dependencies and fixes the freshly introduced warnings.
=> Fix Travis' python related issues in syslog-ng 3.7

modules/affile/affile-common.h, modules/affile/affile-dest.c
When the global `create-dirs` option was set to `yes`, the local one was ignored.
Signed-off-by: László Várady <laszlo.varady@balabit.com>
=> Fix create-dirs() inheritance in file destinations

configure.ac
If hiredis is distributed without a pkg-config script, the minimal
requirement can be overridden by using the --with_redis configure
parameter.
Note, if you use a hiredis version under 0.11.0 you may experience
deadlocks (#792).
Fixes #792
=> Set 0.11.0 as the minimal required version of hiredis to avoid possible deadlocks

configure.ac
In mongo-c-driver sasl support is set to auto by default, but
we forced to link against the sasl2 lib.
As mongo-c-driver is able to work without sasl support, syslog-ng
should also be able to work.
=> configure.ac: link against sasl2 lib only when it is available

configure.ac, doc/Makefile.am, lib/cfg.c, modules/dbparser/dbparser.h, scl/scl.conf, syslog-ng.pc.in
This one should be a partial fix to #908 as it doesn't yet fix xsddir, but it does for scldir and config_includedir
NOTE: YOU CAN GET SEGFAULTS after merging this in a development environment: I've found a segfault in the lexer if two instances of scl/system/plugin.conf is included into the same config. I'm still diagnosing that issue, but I wanted to get this in.
=> make sure all path/dir variables are defined in a single location, by configure.ac

.travis.yml, Makefile.am, tests/Makefile.am, tests/copyright/check.sh, tests/copyright/policy
* tests/copyright/policy:
* Ignore our git submodules
* tests/copyright/check.sh:
* Reduce default verbosity
* Makefile.am,.travis.yml:
* Invoke check-copyright on `make check`
=> Check copyright headers during the execution of make check

modules/afsocket/transport-unix-socket.c
This is a backport PR, the original pull request can be found here: #783
>The reason is that the function return value is a -1 on error, however
>the variable to store that is unsigned, therefore it is unable to store
>the error value and will underflow. The subsequent check will therefore
>not catch the error.
>To fix this change content_len from gsize (unsigned) to gssigned
>(signed).
>This was found with Address Sanitizer.
>Fixes #780
=> afsocket: Fix an integer underflow.

tests/Makefile.am
=> Don't fail during cleanup if there are no copyright-* logs

modules/afprog/afprog.c, modules/afprog/afprog.h
This is a backport PR, the original pull request can be found here: #864
> Fixes: #863
=> Fix program driver keep-alive() option linkage

modules/java-modules/Makefile.am, modules/java-modules/build.gradle, modules/java-modules/elastic-v2/build.gradle, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/ElasticSearchDestination.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/ElasticSearchOptions.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESClient.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESClientFactory.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESNodeClient.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESTransportClient.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESTransportShieldClient.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/UnknownESClientModeException.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/DummyProcessor.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/ESBulkMessageProcessor.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/ESMessageProcessor.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/ESMessageProcessorFactory.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/ESSingleMessageProcessor.java, modules/java-modules/settings.gradle, scl/elasticsearch/plugin.conf
Support ElasticSearch 2 with Shield.
```
destination d_elastic {
elasticsearch2(
client_lib_dir(/usr/share/elasticsearch/lib)
client_mode("shield")
cluster("es-syslog-ng")
index("es-syslog-ng")
port("9300")
server("vagrant-es-server")
type("slng_test_type")
resource("/opt/syslog-ng-ose-3.8/etc/elasticsearch.yml")
);
};
```
=> Add Elasticsearch 2 destination with Shield support

modules/systemd-journal/journal-reader.c, modules/systemd-journal/tests/test_systemd_journal.c
Fixes #831 
The following changes are included in this PR:
* insert all the read key-value pairs under `.journald.`
* if we can map something to a syslog-ng macro, do it as we do it now (like `_HOSTNAME`)
* prefer `SYSLOG_IDENTIFIER` over `_COMM` for setting `PROGRAM`
* make these changes enabled only after `3.8`
After the changes I did some refactoring.
=> Fix journald program name flapping

modules/java-modules/Makefile.am
This environment variable was exported by modules/java but it was removed by #928.
=> Export GRADLE_OPTS environment variable in java-modules so Gradle can use it

modules/systemd-journal/journald-subsystem.c
syslog-ng was crashing in my development environment at startup
if the systemd-journal() driver was used, in a backtrace like this:
Program received signal SIGSEGV, Segmentation fault.
g_module_symbol (module=0x6771b0, symbol_name=0x7ffff4942a65 "sd_journal_open", symbol=0x7ffff7f838f0 <sd_journal_open>) at /build/glib2.0-ajuDY6/glib2.0-2.46.1/./gmodule/gmodule.c:818
818	/build/glib2.0-ajuDY6/glib2.0-2.46.1/./gmodule/gmodule.c: No such file or directory.
(gdb) bt
#0  g_module_symbol (module=0x6771b0, symbol_name=0x7ffff4942a65 "sd_journal_open", symbol=0x7ffff7f838f0 <sd_journal_open>) at /build/glib2.0-ajuDY6/glib2.0-2.46.1/./gmodule/gmodule.c:818
#1  0x00007ffff493e6cd in load_journald_subsystem () at /home/bazsi/zwa/projects/syslog-ng-ose-3.6/source/syslog-ng/modules/systemd-journal/jou …
=> systemd-journal: fix segmentation fault in g_module_symbol() on startup

modules/Makefile.am, modules/diskq/Makefile.am, modules/diskq/qdisk.c, modules/diskq/tests/Makefile.am
We experienced a warning during diskq building and `make -j` wasn't stable also. This PR intends to fix these two issues.
```
Warning: Linking the executable modules/diskq/dqtool against the loadable module
libdisk-buffer.so is not portable!
```
=> Fix diskq linking

lib/gsockaddr.h, modules/date/Makefile.am, modules/java/Makefile.am, modules/kvformat/Makefile.am
This PR fixes some linking and header issues in `date`, `kvformat`, `java` modules and in `gsockaddr.h` on OS X (Apple LLVM version 7.0.2).
Partial fix for #821.
=> Minor linker/include fixes related to OS X build

modules/java-modules/common/src/main/java/org/syslog_ng/logging/SyslogNgInternalLogger.java
This PR resolves multiple issues with the `SyslogNgInternalLogger`:
- `FATAL` loglevel was missing
- only the default log appender worked, `SyslogNgInternalLogger` hasn't produced any output (with kafka destination, where the kafka lib also manipulates on log4j's root logger)
- `locationInformationExists()` wasn't used properly
=> Fix Java's internal logger

configure.ac
Fixes #958 
There was a minor typo in the configure script which prevented
us from disabling the compilation of the MongoDB destination.
You can use --with-libmongo-client=no configure option to disable
this destination.
=> Fix disabling MongoDB destination support in syslog-ng 3.7

configure.ac
You can use --with-mongoc=no configure option to disable
this destination.
=> Fix disabling MongoDB destination support in syslog-ng 3.8

README.md
I've just noticed that the informations under https://github.com/balabit/syslog-ng#installation-from-source are no longer correct.
=> README: fix release download link

lib/apphook.c, lib/cfg-grammar.y, lib/cfg.c, lib/cfg.h, lib/dnscache.c, lib/dnscache.h, lib/host-resolve.c, lib/tests/test_host_resolve.c, modules/diskq/tests/test_diskq_full.c, tests/unit/test_dnscache.c
This is an improved version of #876 by @jbfuzier, which starts with a step-by-step refactor of the dns cache code and adds cache recycling as a trivial last step.
I am not completely satisfied with the end result of dnscache.c, but it is way better than what it was, and I'd like to get this integrated, as I'll have to focus elsewhere.
=> DNS cache refactor and recycling

lib/service-management.c
the systemd service manager will be the current service manager,
even that systemd wasn't active.
Signed-off-by: Juhász Viktor <jviktor@balabit.hu>
EDIT: Backport of #327, fixes #987
=> service-management: if previous code was compiled with ENABLE_SYSTEMD,

modules/dbparser/radix.c, modules/dbparser/tests/test_radix.c
Fixes #931
The `r_parser_ipv6()` function returned `FALSE` if a colon presents after parsing the last four 8-bits as decimal values.
This is not always a good behaviour, for example:
```
Received disconnect from @IPv6:ipv6addr@: @ESTRING:code::@ @ANYSTRING:message@
Received disconnect from ::ffff:200.200.200.200: 2000: Timeout, server not responding.
```
Instead of returning `FALSE`, the parser loop can be stopped at the end of the decimal part.
=> Fix IPv6 pattern parser

modules/diskq/diskq-parser.c, modules/diskq/qdisk.c
I saw a warning on OSX and checked the diskq module for further prefixing issues. These two were the only ones.
=> Fix defines in diskq

lib/logpipe.c, lib/logpipe.h, modules/native/parser.c
This PR contains the following changes:
* update native parser bindings
* https://github.com/balabit/syslog-ng/commit/899b1241eefa10c378696724c33c8609439ac099
* https://github.com/balabit/syslog-ng/commit/0d595504734af2dc5da528ef7055277af3d00898
* refactor `LogPathOptions` to use booleans instead of bitfields (https://github.com/balabit/syslog-ng/commit/24ebce202564328350cb77e7e1c73be4ef1a9910)
=> Update native parser bindings

m4/check_java_support.m4
Fixes #1002
The find command does not search in symlink directories by default.
Adding a trailing slash after the path solves the problem.
In this case, the find command starts from the target of the symbolic link, not from the symbolic link itself.
=> Fix finding JNI library

lib/cfg-grammar.y, modules/dbparser/dbparser-parser.c
This pull request fixes the `value()` option of the `grouping-by()` parser and removes non-existent `kw_req_version` values from dbparser-parser.
This is a completion of PR #828.
=> Fix dbparser grouping-by keywords

lib/value-pairs/value-pairs.c, modules/json/tests/test_format_json.c
Fixes #949.
This revert resolves parsing problems when a token starts with '@'.
In that case, the starting @ symbol disappeared because the `token_start` variable was updated at the beginning of the parser loop.
Also, @dnsjts has a completely rewritten `vp_walker_split_name_to_tokens` function which is much cleaner in my opinion.
=> Fix value-pairs tokenizer

modules/dbparser/tests/test_patterndb.c
This series splits test_patterndb_rule testcase to smaller functions, making the tested functions easier
to understand. This is a preparatory step to implement create-context action, which will be posted in a separate branch.
=> split test_patterndb_rule testcase

modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/ElasticSearchOptions.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESClient.java, scl/elasticsearch/plugin.conf
This patch makes it possible to index documents when the cluster state is
yellow, or even red. This could be only possible when the index you want
to use is writable.
How to use?
Add `skip_cluster_health_check("true")` to your elasticsearch2 destination.
Fixes: #968
=> elasticsearch2: added an option for skipping cluster health check

modules/http/http.c, scripts/rm-extra-msg-sentinel.sh, tests/copyright/policy
msg_error("description", evt_tag_str("when", "before"), NULL);
msg_error("description", evt_tag_str("when", "after"));
This was the automated transformation done in this pull request:
#941 "F/remove msg error etc null sentinel"
f36548b
"dropped extra NULL sentinel at msg_*() call sites"
It was copied from the commit message verbatim, but it may be improved
in the future.
=> F/remove msg error etc null sentinel.sh, run on http module

modules/dbparser/patterndb.c, modules/dbparser/pdb-load.c, modules/dbparser/pdb-ruleset.c, modules/dbparser/pdb-ruleset.h
If no ruleset is present, patterndb wont try to find any matching pattern.
Signed-off-by: Peter Gyorko <peter.gyorko@balabit.com>
=> PatternDB: fixed fastpath of empty patterndb

lib/cfg-args.c
cfg-args: always normalize option names
We have to normalize option names set by users.
'Normalize' means that we replace all hyphen('-') to underscore('_') in an
option name so we will find the key in the underlying hashtable and thus we
can update or read its value.
With this patch users can use both hyphen(-) and underscore (_) in
SCLs.
Fixes: #910
=> scl: handle option names with both hyphen(-) and underscore (-) in SCLs

modules/afprog/afprog.c
If, for some reason, the program source/destination failed to set up its
own process group, we need to make sure we do not run killpg() on that
process group, as it would kill ourselves.
Signed-off-by: Henrik Grindal Bakken <henribak@cisco.com>
=> afprog: Don't kill our own process group

modules/native/parser.c
Without this change, a native parser cannot use configuration dependent
features, such as templates.
Signed-off-by: Tibor Benke <ihrwein@gmail.com>
=> Pass a GlobalConfig pointer to native_parser_proxy_new()

doc/xsd/patterndb-4.xsd, modules/dbparser/Makefile.am, modules/dbparser/dbparser.h, modules/dbparser/pdb-action.c, modules/dbparser/pdb-error.c, modules/dbparser/pdb-error.h, modules/dbparser/pdb-file.c, modules/dbparser/pdb-file.h, modules/dbparser/pdb-load.c, modules/dbparser/pdb-rule.c, modules/dbparser/pdbtool/pdbtool.c, modules/dbparser/tests/test_parsers_e2e.c, modules/dbparser/tests/test_patterndb.c
This series of patches improve test_patterndb test program a lot and also contains a number of refactors, in preparation for the new create-context action in patterndb.
It depends on PR #1004, so that should go in first, but I wanted to submit this separately to facilitate review in smaller batches.
=> dbparser: add XML validation in test_patterndb

libtest/template_lib.c, libtest/template_lib.h, modules/basicfuncs/basic-funcs.c, modules/basicfuncs/numeric-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c
This PR contains three new template functions, which can be used together with correlation plugins such as [correlation-parser](https://github.com/ihrwein/syslog-ng-rust-modules/tree/master/correlation-parser/correlation), [grouping-by() parser](https://czanik.blogs.balabit.com/2016/04/the-grouping_by-parser-in-syslog-ng-3-8/) and [PatternDB](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#patterndb-correlation).
These correlation plugins create message contexts that contain multiple messages.
The newly introduced `$(sum)`, `$(min)` and `$(max)` functions receive one argument, and operate on message contexts. The argument of the template function will be used to calculate the summation, the minimum and …
=> Add $(sum), $(min) and $(max) template functions

modules/dbparser/radix.c
pdbtool iterates through this debug list, this is how the "Pattern matching part" string is created. The list should follow the parsing order to make the output of pdbtool interpretable.
Fixes #1043
=> Fix the ordering of the debug-info list in PatternDB

modules/basicfuncs/tests/test_basicfuncs.c
This PR removes the glib 2.22 specific `g_ptr_array_new_with_free_func()` function call in `test_basicfuncs`.
It is necessary to meet the `GLIB_MIN_VERSION` (`2.10.1`) requirement of the configure script.
=> Fix basicfuncs tests compatibility with GLIB_MIN_VERSION

lib/logproto/logproto-server.c
Although, most libc implementations provide a native iconv with various
aliases, libiconv does not know about the alias `utf8`.
Neither does glib provide this alias if compiled with libiconv.
Furthermore, be advised that the user can only specify in the syslog-ng
config those iconv codes which are supported by the local iconv or
libiconv.
Fixes #1048
Regression introduced:
3fa60288548b54bcfad7b42deb145ef2eafa029c
"logproto: handle invalid encoding() options at parsing time"
=> lib/logproto/logproto-server.c: refer to utf8 as utf-8

modules/systemd-journal/tests/Makefile.am
The ivykis library wasn't linked to the test binary.
CCLD     modules/systemd-journal/tests/test_systemd_journal
/usr/bin/ld: modules/systemd-journal/tests/modules_systemd_journal_tests_test_systemd_journal-test_systemd_journal.o: undefined reference to symbol 'iv_task_registered@@IVYKIS_0.29'
/tmp/pe7-tibi/install/lib/libivykis.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[3]: *** [modules/systemd-journal/tests/test_systemd_journal] Error 1
make[2]: *** [check-am] Error 2
make[1]: *** [check-recursive] Error 1
make: *** [check] Error 2
=> Fix a linker related problem in systemd-journal's tests

modules/basicfuncs/basic-funcs.c, modules/basicfuncs/numeric-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c
Further improvements to #1037:
* Rename a few static functions
* Abstract out iteration when finding first element and aggregating
* Implement numeric mean (average)
* Refactor test cases to reduce redundancy
=> F/ctx template funcs2 - mean operator, further stylistic improvements to #1037

README.md, modules/system-source/system-source.c
This branch adds a quickstart section into the readme file and also contains a fix to the system() source to properly set PID based on .unix.pid if the former is unset.
=> Quickstart section

lib/cfg-lexer.c
We can reproduce an other double free in the grammer related to LL_IDENTIFIER-s and
yydestruct()/maual frees in the grammar actions. Fortunately, this problem is only reproducible with native-parser (AFAIK)
which is not widely used (currently).
I modified the grammar of csv-parser to reproduce the problem without any native-parser based
parsers.
The double free will occur depending on the optional free() call/configuration validation.
The memory allocation and first free() call happen on the same place in both cases.
In the first case, the second free() call is triggered manually (and the syntax is valid!).
Configuration:
```
@version: 3.8
log {
parser {
#csv-parser(kutya());
csv-parser();
};
};
```
Cherry-pick 8fec099bbe6be2aea68fa841599e778140d37709.
Backtrace:
``` …
```
=> Fix LL_IDENTIFIER double frees in the grammar

modules/native/native-grammar.ym
This PR depends on #1061 (syslog-ng will crash without that PR).
=> Add missing free to native parser's grammar

lib/cfg-tree.c, lib/cfg-tree.h
this branch fixes #1065 
cfg_tree_compile() is not idempotent for at least two reasons:
* it stores the pipes to be initialized in an array, which will grow
for each cfg_tree_compile() calls
* it uses PIF_INLINED to indicate if a LogPipe was pasted directly into
the config rather than cloned
But cfg_tree_start() invokes cfg_tree_compile() unconditionally, which
means that if a config is initialized multiple times, cfg_tree_compile()
will accumulate cruft in its state.
Issue #1065 on github explains one case where syslog-ng crashes on reload:
https://github.com/balabit/syslog-ng/issues/1065
This patch fixes this problem by guarding the compile function with
a variable, which ensures that the body of the function is executed only
once.
Signed-off-by: Balazs Scheidler …
=> cfg-tree: fix a potential crash in reload logic

lib/cfg-lex.l
This patch fixes #1055 
When we return the EOF token, yylloc was not properly initialized, possibly
causing NULL derefs in the error reporter function, if the error is happening
right at the $end token.
Reported-by: Agostino Sarubbo <ago@gentoo.org>
=> cfg-lex: initialize yylloc even if we are returning YYEOF

.travis.yml, configure.ac, modules/afsql/afsql.c, modules/afsql/afsql.h, modules/python/sngexample.py, modules/systemd-journal/systemd-journal-grammar.ym, modules/systemd-journal/tests/Makefile.am, scripts/get-libjvm-path.sh, tests/functional/test_sql.py
These are the core fixes that are needed to enable `func_test` in Travis. As enabling all tests in Travis leads to a longer discussion, I have separated the fixes themselves here. They are mostly typos and version incompatibilities.
https://github.com/balabit/syslog-ng/pull/982 can be merged on top of this one.
I will do some quick adjustments now, but after this one gets a green light, it is ready for review.
=> F/fix make func-test typos that keeps us from enabling it in CI

modules/java-modules/http/src/main/java/org/syslog_ng/http/HTTPDestination.java, modules/java-modules/http/src/main/java/org/syslog_ng/http/HTTPDestinationOptions.java
eg:
java(
class-path("/usr/lib64/syslog-ng/java-modules/*.jar")
class-name("org.syslog_ng.http.HTTPDestination")
option("url", "http://host:8080/prefix-${YEAR}.${MONTH}.${DAY}/mailtrack/${macro}/update")
option("method", "POST")
option("template", "$(format-json --scope dot_nv_pairs)")
);
=> Add ability to use templates in both url and message format

lib/CMakeLists.txt
This is a bugfix commit for #1051 
CMake didn't create the `libsyslog-ng.so` symlink during installation so the linker wasn't able to find syslog-ng with `-lsyslog-ng`.
=> Create libsyslog-ng.so symlink on installation with CMake

modules/java-modules/build.gradle
This is required by OBS (or any offline build system).
Flat dir is not an option anymore as we support both native ElasticSearch 1.x
and 2.x java clients (transport/node/shield modes). The client jars are
conflicting as they are on the same path, so we have to support an offline
dependency  management system.
We had two options:
1. package local gradle cache into a deb package and install it inside OBS
2. convert local gradle cache into a local maven repository and package
that repository, then we can set this as a build dependency
2nd solution is more elegant and future proof (using gradle with
an external cache that is stolen from another version of gradle
is not something I'd trust).
Related project where my converter script is available: …
=> java-modules: use local maven repository instead of flat dir

lib/parse-number.c
From manpage:
> If an underflow occurs, strtol() returns LONG_MIN. If an overflow occurs, strtol() returns LONG_MAX. In both cases, errno is set to ERANGE. Precisely the same holds for strtoll() (with LLONG_MIN and LLONG_MAX instead of LONG_MIN and LONG_MAX).
>The implementation may also set errno to EINVAL in case no conversion was performed (no digits seen, and 0 returned).
Fixes #1083
=> Fix incorrectly checked integer underflow/overflow

lib/logmsg/logmsg.c
This patch fixes a potential SIGSEGV for code that uses log_msg_clear()
in production (e.g. syslog-parser()).
The role of log_msg_clear() is to clear up all name-value pairs,
SDATA, tags and sockaddr in order to reset the message into its
default state.
In this function we also relinquished self->original, which points
to the message where we cloned the current one from.
The problem with this was that it actually breaks the acknowledgement
logic, as ack_func was not reset at the same time.
It would be a layering violation to reset it back to its original value,
I simply remove dropping the link to self->original, which is only going to
be used for acks and nothing really else.
=> logmsg: don't release "original" from the cleared message

lib/str-utils.h, lib/utf8utils.c, modules/cef/format-cef-extension.c, modules/json/tests/test_format_json.c
This issue can cause invalid UTF-8 characters in `format-cef-extension`, `format-welf` and `format-json`.
`g_utf8_get_char_validated()` converts a sequence of bytes encoded as UTF-8 to a Unicode character (`gunichar` --> UTF-32), so checking for an UTF-8 leading byte (`< 0xc0`) is not an option here.
`0x80` can be used instead.
This is a performance optimization, where we can append the given unichar with `g_string_append_c()` if it fits in 7 bits.
In all other cases, conversion is required (`g_string_append_unichar()`).
Partial fix for #999
=> Fix invalid handling of UTF-8 strings

modules/native/parser.c
I forgot to forward the `deinit()` calls to the native parsers. This can cause problems with reloads.
I also added a commit for calling `log_parser_init_method()` in `init()`. It didn't produce problems, but other parsers call it, so it's best to call it here as well.
=> Implement deinit() for native parsers

modules/java-modules/elastic-v2/build.gradle, modules/java-modules/elastic/build.gradle, modules/java-modules/hdfs/build.gradle, modules/java-modules/http/build.gradle, modules/java-modules/kafka/build.gradle
The dependencies in `fileTree()` are conflicts with the local maven repo (on those machines where both of the dependencies are installed).
Please, merge.
=> java-modules: gradle: removed unnecessary dependency

modules/geoip/tests/Makefile.am
Previously, when geoip was found on a machine where automake was run, after moving to another machine geoip tests failed while building.
This patch modifies the makefiles, so geoip tests are only run when geoip is enabled.
=> include geoip tests only when geoip is enabled

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logmsg/tests/test_log_message.c, lib/logstamp.c, lib/logstamp.h, lib/logwriter.c, modules/dbparser/synthetic-message.c
This function creates a new LogMessage with LF_LOCAL flag and its
timestamps are initialized to the same value.
Reason: $YEAR and other time related macros use timestamps[LM_TS_STAMP]
timestamp. If that timestamp isn't initialized (-1), then $YEAR is
evaluated to 1969.
I handle LogMessage instances as opaque pointers, so I don't have access
to their flags. LogMessage doesn't have setter and getter methods for
its flags and I don't want to modify them after an instance is created,
so this is the simplest and less intrusive solution I could think of.
=> logmsg: add log_msg_new_local() function

modules/native/native-grammar.ym, modules/native/parser.c, modules/native/parser.h
This PR changes the signature of `native_parser_set_option()` to return with a boolean value and so makes possible to fail-fast in case of an invalid option value.
What's an invalid option value?
* the value is a path and the file doesn't exist
* the value is a regular expression, but it's invalid
* every other native parser specific 
This PR also contains a little refactor (fixing an include guard, removing some duplicated function prototypes).
There are no unit tests for this change, mainly because I don't know any examples where syslog-ng's grammar tested this way.
This PR is the pair of https://github.com/ihrwein/syslog-ng-rust-modules/pull/35
=> Native parser: fail-fast when configuration setting failed

lib/parser/parser-expr.c
In #1102, `log_parser_process_message()` was extracted from `log_parser_queue()` to make it possible to invoke template processing from outside code.
Unfortunately, this transformation is not fully equivalent. `self->process()` can create a new LogMessage instance (`log_msg_clone_cow()`).
In this case, only the local `msg` pointer will be updated, `*pmsg` will remain unchanged.
This PR fixes this issue by passing the original `pmsg` variable to the `process()` function.
=> parser: fix invalid pointer usage in log_parser_process_message()

lib/cfg-lexer.c
Let's suppose we have a config file which includes files this way:
`scl/*/*.conf`
If we create a `scl/e/e.conf` file under `etc`, this glob pattern is
expanded as:
```
etc/scl/e/e.conf
share/syslog-ng/include/scl/a/a.conf
share/syslog-ng/include/scl/b/b.conf
```
We have to place these files on the same include stack level, as they were
expanded from the same pattern.
syslog-ng pushed on the include stack every time it evaluated a new
include-path prefix (etc and share/syslog-ng/include/scl). This mishandling caused the SEGFAULT (though I didn't track it down exactly why).
I moved the include stack level increasing one level upper, so it's
increased only once. If syslog-ng isn't able to include a file (so the
top of the stack is unused), we restore the stack to it's original state.
=> Fix segmentation fault when including SCLs

lib/logmsg/logmsg.c, lib/logmsg/nvtable.c, lib/logmsg/nvtable.h, lib/logmsg/tests/test_nvtable.c
This PR continues the work started in #1126. This PR contains a modification so the deleted unit tests can be kept.
=> 32bit wide NVHandle with unittests

modules/add-contextual-data/csv-contextual-data-record-scanner.c
In case of too many field in a csv line, syslog-ng doesn't stop. However, syslog-ng mustn't start if the input csv file is invalid.
This PR introduces a check to handle too long lines.
=> add-context-data: stop when too many fields are in a line

modules/affile/tests/test_affile_open_file.c, modules/date/strptime-tz.c, modules/dbparser/pdb-file.c
Two problems were detected on FreeBSD
- timezone function call incompatibility
- missing header includes in two files
Now, syslog-ng compiles and make check passes. However, I haven't tested syslog-ng with python modules and java modules yet.
=> FreeBSD compatibility of 3.8 - fixes #1138

debian/syslog-ng-mod-elastic.install, modules/java-modules/Makefile.am, modules/java-modules/elastic-v2/build.gradle, scl/elasticsearch/plugin.conf
elastic-v2 is part of the mod-elastic package (plugin.conf is common
for elastic and elastic-v2 drivers).
Jest client is also added to this package.
This may be a little bit confusing, but I have my own reasons:
* syslog-ng supports Elastisearch: not 1.7, 2.x, 5, but Elasticsearch
* elastic and elastic-v2 exists just because the Elasticsearch Java clients
are not compatible between 1.7.x and 2.x versions (and the bad thing
that the package names are almost identical, but internal representation
has been changed)
* elastic-v2 could be packaged separately, but we have a http mode extension
to that which is able to work with both ElasticSearch 1.x, 2.x and Elastic5
So the elastic is only for 1.7.x series, elastic-v2 could work with 2.x series
with node, transport and shield mode, and …
=> elastic-v2: fixed debian packaging

lib/cfg-tree.c, modules/add-contextual-data/context-info-db.c
* include missing header
* as `g_array_set_clear_func` is only available from glib version 2.32,
I removed it
Fixes: #1144
=> add-contextual-data: build fixed on SLES-11

modules/afstreams/afstreams.c
After this small change I was able to compile syslog-ng on Oracle Solaris 11.
( the environment setup was a little bit s*ck, if someone interested in the details , I'll share my experiences )
=> afstreams: include missing header (errno.h)

lib/logmsg/gsockaddr-serialize.c, lib/logmsg/tests/test_gsockaddr_serialize.c
During deserialization, `sockaddr_in` and `sockaddr_in6` should be zeroed out, to avoid uninitialized fields.
=> Fix deserialization of GSockAddr

modules/add-contextual-data/context-info-db.c, modules/add-contextual-data/csv-contextual-data-record-scanner.c, modules/add-contextual-data/tests/test_context_info_db.c
This PR
- adds CRLF line ending support to add-contextual-data
- sets the dialect of `CSVScanner` to [escape-double-char](https://www.balabit.com/sites/default/files/documents/syslog-ng-ose-latest-guides/en/syslog-ng-ose-guide-admin/html-single/index.html#reference-parsers-csv) in `ContextualDataRecordScanner` (as recorded in [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt))
Fixes #1179 (Issue 1 and 3)
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/balabit/syslog-ng/1184)
=> Minor add-contextual-data fixes

configure.ac
If the enable-linux-caps flag is not specified explicitly (`enable_linux_caps="auto"`), the corresponding `ENABLE_...` macro in syslog-ng-config.h will be set to a constant FALSE value.
This PR fixes this issue by setting the value of `enable_linux_caps` after calling `AC_CHECK_LIB`.
Fixes #1207
=> Fix automatic libcap detection

lib/logproto/logproto-framed-server.c, lib/tlscontext.c, lib/tlscontext.h, lib/transport/transport-tls.c
Having macros for these values will allow syslog-ng servers to use attributes from the clients certificate, if presented, in file name paths.
This would allow servers to use values that are unique per client, but unchangeable by the client.
Combined with peer-verify(require-trusted) we can issue clients a certificate with attributes that they cannot change. We can use those values to uniquely identify that client without relying on the client to put an identifier in the actual log message.
=> Create X509_* macros for CN, O, OU of the peer certifacate

modules/affile/affile-source.c
Previously, if a file was not available on init it was only checked twice if it had become available
even if follow mode was on. From now on, opening the file is attempted every time the interval set in follow-freq elapses.
This PR cleans up the work done in #847. After merging this PR, that one have to be closed.
=> Try to open file more than twice - closes #841

lib/logproto/logproto-buffered-server.c, lib/logproto/logproto-server.c, lib/logproto/logproto-server.h, lib/logproto/logproto-text-server.c, modules/affile/affile-source.c
There was a performance issue around TCP source.
As it came out LateAckTracker was used instead of EarlyAckTracker.
The reason was that position tracking was enabled by default for the
LogProto type that is used for TCP source.
=> logproto: do not enable position tracking by default

doc/man/pdbtool.1.xml
Another small typo fix, in this case in the pdbtool man page.
=> Fixed the path of the configuration file

modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, modules/afsocket/afsocket-source.c, modules/afsocket/afsocket-source.h, tests/functional/test_input_drivers.py
This patch introduces listen-backlog() option as one applicable to stream
oriented transports (both unix domain and inet).
Here's a sample configuration:
@version: 3.8
log {
source { tcp(port(6514) listen-backlog(2048)); };
destination { file("/dev/stdout"); };
};
=> afsocket: make listen-backlog configurable

modules/afsocket/socket-options-inet.c
The #ifdef macros disable the TCP_KEEPIDLE, TCP_KEEPCNT, TCP_KEEPINTVL
set socket options as the header file that defines them is not included.
Include the necessary header file to enable the options.
Signed-off-by: Kyle Manna <kyle@kylemanna.com>
=> afsocket: tcp: Include missing setsockopt header

lib/tests/Makefile.am, lib/tests/test_cache.c, tests/unit/Makefile.am, tests/unit/test_logwriter.c, tests/unit/test_pathutils.c, tests/unit/test_zone.c
Following tests were ported
* `lib/tests/test_cache`
* `tests/unit/test_zone`
* `tests/unit/test_logwriter`
* `tests/unit/test_cache`
Now every test under tests/unit folder depends on Criterion.
=> switch to Criterion

autogen.sh
This is a temporary quick workaround to help testing, do not merge yet.
* TODO: extract mongo-c-driver kludges to a separate function
* TODO: introduce configure option to reenable shm counters with warnings
=> autogen.sh: temporarily disable shm counters in mongo-c-driver

lib/dnscache.c, tests/unit/test_dnscache.c
As reported on the mailing list, DNS cache corruption occurs when the dns-cache-size limit is reached.
Kudos for the great report go to Claus Albøge.
This patch fixes a SIGABRT that happens when an element is being
removed from the DNS cache, due to the high number of elements already
present. Both the cache_list and the persist_list lists were incorrectly
handled.
=> dnscache: fix cache list corruption causing SIGABRT

modules/diskq/logqueue-disk-non-reliable.c
In non-reliable mode, qoverflow_size was set to mem_buf_size instead of
mem_buf_length, which is wrong, as the first is measured in bytes, whereas
the latter is measured in number of elements.
=> diskq: fix qoverflow_size setting in nonreliable mode

modules/java-modules/common/src/main/java/org/syslog_ng/logging/SyslogNgInternalLogger.java
Requesting location information (class name, method name, line number) is a slow operation, this should be displayed only in DEBUG (and TRACE) mode.
=> java-modules: report location information only when 'loglevel <= DEBUG'

modules/afsocket/socket-options-inet.c
This is the continuation of #1214.
On BSD-like platforms, `IPPROTO_TCP` should be used instead of `SOL_TCP`.
Related to #1249
=> afsocket: add SOL_TCP alias to fix compilation on BSD systems

modules/java-modules/common/src/main/java/org/syslog_ng/logging/SyslogNgInternalLogger.java
Getting location information (e.g. `org.syslog_ng.hdfs.HdfsDestination.open:83 - Opening hdfs`) is an expensive operation. This caused a 70% performance loss in the HDFS destination.
A "syslog-ng debug-mode" checker should be implemented on the Java side. After this, we can revert this patch if someone finds this kind of location information useful.
Fixes #1229
=> java-modules: remove location information from internal debug logs

modules/add-contextual-data/add-contextual-data-selector.h, modules/add-contextual-data/add-contextual-data-template-selector.c, modules/add-contextual-data/add-contextual-data.c, modules/add-contextual-data/tests/test_selector.c
Evaluation order of selectors are defined by user in the ContextInfoDB file.
It is possible to implement such selector where this ordering is needed.
=> add-contextual-data: add ordered list of selector to selector::init

modules/java/native/java-grammar.ym
Earlier, values passed by the option() config option could only be
strings, this change would allow specifying LL_NUMBER tokens as well.
=> java: make it possible to pass numbers to generic options

modules/java-modules/common/src/main/java/org/syslog_ng/options/TemplateOption.java
... after the underlying C object has been freed
=> java/TemplateOptions: release java object

tests/unit/test_msgparse.c
Build time_t by using mktime() instead of using magic
numbers(that magic number does not
work anymore as last year was a leap year).
=> tests/unit: fix test_msgparse

modules/Makefile.am, modules/getent/Makefile.am, modules/getent/getent-group.c, modules/getent/getent-passwd.c, modules/getent/getent-protocols.c, modules/getent/getent-services.c, modules/getent/tfgetent.c, tests/copyright/policy
This module adds $(getent) that allows one to look up various NSS based
databases, such as passwd, services or protocols.
A few examples:
$(getent passwd $UID)
$(getent passwd $UID gecos)
Supported databases and members:
- passwd: name, uid, gid, gecos, dir, shell
- group: name, gid, members
- services: none
- protocols: none
Original implementation was created by:
Gergely Nagy <algernon@madhouse-project.org>
Fabien Wernli <cpan@faxm0dem.org
Their original signed-off-by is reproduced here for clarity, their patches
were ported as a single commit by Balazs Scheidler <balazs.scheidler@balabit.com>.
Signed-off-by: Gergely Nagy <algernon@madhouse-project.org>
@faxm0dem Please, send a signed-off-by on this branch in order to get it …
=> getent: add getent module

lib/cfg-parser.c
The displayed link to the online documentation is a bit broken, because it misses the filter for the syslog-ng product.
=> cfg-parser: fix link for online documentation

README.md
Remove build status on drone.io, because the building is no longer maintaned.
=> README: rm drone.io as it is no longer maintined by syslog devs

modules/afsocket/afsocket-grammar.ym
The max_connections in network source must be a positive integer, there were no validation for it before.
=> config: validate max_connections setting

modules/python/python-debugger.c, modules/python/python-dest.c, modules/python/python-grammar.ym, modules/python/python-helpers.c, modules/python/python-helpers.h, modules/python/python-main.c, modules/python/python-tf.c
* We should only delete if the "_syslogng" module
exists
* Without this patch syslog-ng crashes at start
in the following conditions:
* OS: Ubuntu 16.04
* config contains: python{};
Signed-off-by: Andras <andras.mitzki@balabit.com>
=> PythonModule: Handle deletion of _syslogng module

lib/logproto/logproto-server.c, lib/logproto/logproto-text-server.c
Using multi-line file sources, EOL is not equivalent with EOM therefore two additional cases should be handled:
- the buffer should be split when log_proto_text_server_extract() can not extract the message from the current buffer.
- if the buffer is full with a single message, the buffer should be yielded as a complete message
Previously, the meaning of the log-msg-size() option was not clearly defined when encoding was set.
In multi-line mode, the buffer size increased without limit to the maximum size due to our conversion mechanism.
This PR also defines the meaning of the log-msg-size() option if conversion is enabled:
If the size of incoming message is greater than log-msg-size() (in the internal UTF-8 representation), it will be splitted.
Fixes #1318
=> logproto: fix possible reading loop in case of multi-line file source

lib/control/control-commands.c, lib/stats/CMakeLists.txt, lib/stats/Makefile.am, lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, lib/stats/stats-query-commands.c, lib/stats/stats-query-commands.h, lib/stats/stats-query.c, lib/stats/stats-query.h, lib/stats/stats-registry.c, lib/stats/stats-registry.h, lib/stats/tests/Makefile.am, lib/stats/tests/test_stats_query.c, syslog-ng-ctl/syslog-ng-ctl.c
Previously, the only possiblity to get statistics of syslog-ng was using `stats` command of `syslog-ng-ctl`. It is limited as it return all of the counters in CSV format. From now on, it is possible to filter, so only desired metrics are shown using the new `query` command. The new format of each counter and its value is `<counter-id>: <value>`.
`list` - List all counters with matching name
`get` - Get the value of selected counter
`get --sum` - Get the aggregated value of selected counters
```
$ syslog-ng-ctl query list
center.received.processed
src.internal.s_local#0.processed
src.internal.s_local#0.stamp
center.queued.processed
global.payload_reallocs.processed
global.sdata_updates.processed
destination.d_local.processed
global.msg_clones.processed
source.s_local.processed
```
```
$ …
```
=> new syslog-ng-ctl command: query

lib/str-utils.h, lib/tests/test_str-utils.c, lib/tests/test_utf8utils.c, lib/utf8utils.c
This branch adds new testcases in utf8 encoding, as an issue was reported on this functionality.
The new testcases didn't reveal a bug, and it turned out to be a non-issue, but nevertheless this improves test coverage and also improves the production code somewhat.
This also includes a fix into our optimized strchr() implementation.
=> Utf8 encoding tests

lib/tests/Makefile.am, lib/tests/test_timeutils.c
There were no unit tests for it, and we got some complaints about this heuristic. Now it is clear that it is intended to work this way. It can be changed later, just the reference tests must be updated.
See e0548d870a0fb4d85379814240e8f8f746a764b4 and 7e280cafb450125d26affdbde2610d05c0951bd8, and #818.
=> Add unit tests for BSD format year calculation

modules/add-contextual-data/add-contextual-data.c
The syslog-ng cannot start (with message `Error initializing message pipeline;`) if a named parser is referenced multiple times.
```
syslog-ng 3.9.1
Installer-Version: 3.9.1
Revision: 
Module-Directory: /home/matefarkas/install/syslog-ng/lib/syslog-ng
Module-Path: /home/matefarkas/install/syslog-ng/lib/syslog-ng
Available-Modules: afmongodb,affile,sdjournal,confgen,cryptofuncs,syslogformat,pseudofile,afsocket,afamqp,basicfuncs,afuser,linux-kmsg-format,tfgetent,afprog,kvformat,mod-python,date,graphite,disk-buffer,csvparser,dbparser,add-contextual-data,cef,afstomp,system-source,json-plugin
Enable-Debug: on
Enable-GProf: off
Enable-Memtrace: off
Enable-IPv6: on
Enable-Spoof-Source: off
Enable-TCP-Wrapper: off
Enable-Linux-Caps: off
```
1. `touch etc/hosts.csv`
2. Edit `syslog-ng.conf`
3. Try …
=> Named parser cannot be referenced multiple times

lib/compat/CMakeLists.txt, lib/compat/Makefile.am, lib/compat/pcre.h, lib/logmatcher.c, lib/logproto/logproto-regexp-multiline-server.c
This branch builds on PR #1345 by @juhaszviktor so it works on older PCRE releases as well. It removes ifdef trickery by introducing a compat/pcre.h file.
=> Fix pcre jit leak

syslog-ng-ctl/syslog-ng-ctl.c
=> syslog-ng-ctl: support UTF-8 chars

lib/scanner/list-scanner/tests/Makefile.am
Run Criterion tests only when Criterion is installed on the system.
=> list-scanner-test: add enable criterion condition

modules/java/proxies/java-destination-proxy.c
Previously the log messages were always in local timezone independently from the `time-zone()` configuration option.
We have a simple file destination and the dummy Java destination, which just prints the received log message to the console. We expect to have the same message in both cases.
```
@version: 3.9
options {
time_zone("-08:00");
};
source s_oneline { program("echo syslog-ng-test-oneline"); };
destination d_outfile {file(
'/home/matefarkas/work/syslog-ng/install/out.txt'
template("FILE / ${DATE} / ${ISODATE}")
);};
destination d_java {
java(
class_path("/home/matefarkas/work/syslog-ng/install/lib/syslog-ng/java-modules/*.jar")
class_name("org.syslog_ng.DummyTextDestination")
template("JAVA / ${DATE} / ${ISODATE}")
option("name", "timezonetest")
);
};
log {
source(s_oneline); …
```
=> Apply timezone configuration in Java destinations

syslog-ng-ctl/syslog-ng-ctl.c
This patch makes it possible to detect if no counter matched the filter specified using `syslog-ng-ctl query`. Thus, `syslog-ng-ctl query` can be utilized in scripts.
=> syslog-ng-ctl: return 1 when response of the server is empty

syslog-ng-ctl/syslog-ng-ctl.c
When `syslog-ng-ctl` was called simply `--help`, it returned with 1, as if it was a failure. From now on, when the user calls `syslog-ng-ctl --help` the return value indicates success.
=> syslog-ng-ctl: exit with 0 if --help is specified

lib/template/templates.c, modules/python/python-logmsg.c
Please note, that hard macros are also added to the list of keys.
Hard macros are cannot be overwritten.
Fixes: #1379
=> python-parser: add macros to keys()

lib/rewrite/rewrite-groupset.c
Syslog-ng crashes if 2 instance is used of a groupunset rewrite rule.
The groupunset is a bit modified groupset object. But the clone method of the groupset object did not copy the modification, so it had to be implemented there.
```
@version: 3.9
rewrite r_test {
set ("Hello Core dump!", value ("TEST"));
groupunset(values("TEST"));
};
log {
source {file ("/opt/syslog-ng/etc/in.log");};
rewrite(r_test);
rewrite(r_test);
};
```
```
<30>Sep 17 23:54:54 test test[1234]: test
```
=> groupunset: fix clone function

lib/cfg-grammar.y, lib/logthrdestdrv.c, modules/afamqp/afamqp-grammar.ym, modules/affile/affile-grammar.ym, modules/afmongodb/afmongodb-grammar.ym, modules/afsmtp/afsmtp-grammar.ym, modules/afsocket/afsocket-grammar.ym, modules/afsql/afsql-grammar.ym, modules/afsql/afsql.c, modules/afstomp/afstomp-grammar.ym, modules/dbparser/dbparser-grammar.ym, modules/diskq/diskq-grammar.ym, modules/redis/redis-grammar.ym, modules/riemann/riemann-grammar.ym, modules/systemd-journal/systemd-journal-grammar.ym
Add rules to grammar to be able to require non-negative and positive integers. Some of our configuration options expected those kind of values, but they were not validated before. (Just the program crashed due an invalid setting.)
(@MrAnno collected this list before, it was reviewed and splitted into the positive and the non-negative parts. Copied from https://github.com/balabit/syslog-ng/pull/1330#issuecomment-275225263)
* [listen-backlog()](https://www.balabit.com/documents/syslog-ng-ose-3.9-guides/en/syslog-ng-ose-guide-admin/html/reference-source-syslog-chapter.html#idp4343616)
* [log-fetch-limit()](https://www.balabit.com/documents/syslog-ng-ose-3.9-guides/en/syslog-ng-ose-guide-admin/html/reference-source-syslog-chapter.html#idp4358576)
* …
=> Validate non negative numbers

modules/Makefile.am, modules/map-value-pairs/Makefile.am, modules/map-value-pairs/map-value-pairs-grammar.ym, modules/map-value-pairs/map-value-pairs-parser.c, modules/map-value-pairs/map-value-pairs-parser.h, modules/map-value-pairs/map-value-pairs-plugin.c, modules/map-value-pairs/map-value-pairs.c, modules/map-value-pairs/map-value-pairs.h, tests/copyright/policy, tests/functional/func_test.py, tests/functional/test_map_value_pairs.py
This patch adds a map-value-pairs() parser that can be used to map existing
name-value pairs to a different set during processing, in bulk.  Normal
value-pairs expressions can be used, just like with value-pairs based
destinations.
For example:
```
parser p_remap_name_values {
map-value-pairs(
key('.apache.*' rekey(add-prefix("foo")))
pair('.apache.foobar.xxx', "bar")
pair('123', "567")
pair("username", '($sha1 $username)')
);
};
```
=> map-value-pairs: add map-value-pairs() parser

lib/stats/stats-query-commands.c, lib/stats/stats-query.c, lib/stats/stats-query.h, syslog-ng-ctl/syslog-ng-ctl.c
From now on, it is possible to reset counters after querying them. Resetting is supported for all of the query commands: `get`, `get --sum` and `list`.
Example:
```
$ syslog-ng-ctl query get --reset '*'
center.received.processed: 5
$ syslog-ng-ctl query get '*'
center.received.processed: 0
```
=> syslog-ng-ctl: enable resetting counters after query

lib/cfg-lexer.c
This PR fixes an old token duplication issue in the output of the `--preprocess-into` command line option.
Since every token in a `CfgTokenBlock` is an 'injected token', the injected flag should be set in all cases.
---------------------------
- `etc/syslog-ng-example.conf`:
```
@version: 3.9
parser p_parser {};
filter f_filter { host(""); };
rewrite r_rewrite {};
source s_source {};
destination d_destination {};
log {};
```
1. Start syslog-ng: `sbin/syslog-ng -Fedv -f etc/syslog-ng-example.conf --preprocess-into test.txt`
2. cat test.txt
Example output (notice the duplicated '}' tokens):
```
@version: 3.9
parser p_parserke {}};
filter f_filter { host(""); }};
rewrite r_rewrite {}};
source s_source {};
destination d_destination {};
log {};
```
=> cfg-lexer: fix token duplication in the output of '--preprocess-into'

lib/compat/openssl_support.c
CRYPTO_set_id_callback (openssl<1.0.0) has been replaced by
CRYPTO_THREADID_set_callback.
Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>
=> openssl: replace deprecated thread callback function

.travis.yml
Failure because manifest tries to install python, but it's already installed.
Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>
=> Setup for CI environment seems to fail for clang

configure.ac, lib/logmsg/logmsg.c, lib/logproto/logproto-buffered-server.c
Warnings about uninitialized variables are often accurate.
Signed-off-by: Philip Prindeville <philipp@redfish-solutions.com>
=> increase compiler verbosity and clean up warnings

Makefile.am, configure.ac
We have the `Werror` flag in Travis, but we do not want to enforce it in every build environment.
This is a continuation of #1398.
=> Remove hardcoded Werror

lib/compat/openssl_support.c, modules/basicfuncs/str-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c, modules/cryptofuncs/cryptofuncs.c, modules/cryptofuncs/tests/test_cryptofuncs.c
This branch follows up #1397 and improves readability of the various #ifdef cases.
This patch improves the readability of the code by breaking it up
along logical pieces instead of driven by openssl versions and code
required for various versions.
=> openssl_compat: improve ifdefs to break the code into independent pieces

lib/str-repr/tests/test_encode.c
The argument for format template is missing,
therefore it can crash
Signed-off-by: Juhász Viktor <juhasz.viktor81@gmail.com>
=> test_encode: coredump correction.

lib/cfg.c
Because in modern log infrastructure the general log size is higher
and syslog-ng should process it by default.
Signed-off-by: Zoltan Pallagi <pzoleex@gmail.com>
=> cfg.c: default log_msg_size is increased to 64Kbyte from 8Kb

lib/cfg-grammar.y, modules/redis/redis-grammar.ym, modules/redis/redis-parser.c, modules/redis/redis.c, modules/redis/redis.h
For issue:
https://github.com/balabit/syslog-ng/issues/1320
```
destination d_redis {
redis(
host("127.0.0.1")
port(6379)
auth("Pa55W0rD") # <---
command("HINCRBY", "hosts", "$HOST", "1")
);
};
```
=> Redis auth support

modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java, modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsOptions.java, scl/hdfs/plugin.conf
Example:
```
destination d_hdfs{
hdfs(client-lib-dir(/hdfs-libs)
hdfs-uri("hdfs://myhdp.com:8020")
hdfs_file("/hdfs/text.txt")
kerberos_keytab_file("/opt/syslog-ng/etc/hdfs.headless.keytab")
kerberos_principal("hdfs-hdpcluster@MYREALM"));
};
```
Signed-off-by: Zoltan Pallagi <pzoleex@gmail.com>
=> HDFS destination: Added kerberos support

modules/basicfuncs/Makefile.am, modules/basicfuncs/basic-funcs.c, modules/basicfuncs/fname-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c
This module adds template functions to extract the filename and
the directory name from a filename.
Example usage:
$(basename $FILE_NAME)
=> basicfuncs: add $(basename) and $(dirname) functions

lib/scanner/csv-scanner/csv-scanner.c, lib/scanner/csv-scanner/csv-scanner.h, modules/add-contextual-data/csv-contextual-data-record-scanner.c, modules/add-contextual-data/csv-contextual-data-record-scanner.h, modules/csvparser/csvparser.c
csv-parser appears not to be thread safe when attached to a network source
https://github.com/balabit/syslog-ng/issues/1334
csv scanner object contained a few fields that are used for iterating
through columns. As multiple threads uses the same scanner object,
those threads broke the state of the common scanner. This patch creates
the scanner object on the stack of the parse function of the parser,
so each threads will have their own dedicated scanner objects.
=> csv-parser appears not to be thread safe when attached to a network source

NEWS.md, README.md
GitHub changed the way Markdown headings are parsed, so this change fixes it.
See [bryant1410/readmesfix](https://github.com/bryant1410/readmesfix) for more information.
Tackles bryant1410/readmesfix#1
=> Fix broken headings in Markdown files

modules/afsocket/afsocket-grammar.ym, modules/http/http-grammar.ym, modules/http/http-parser.c, modules/http/http-plugin.h, modules/http/http.c
Add SSL/TLS related options to the http (curl) module.  It is already possible to use https URLs (since curl supports this natively) but there is no way to control the SSL/TLS parameters.  This diff add the following options: ca_dir, ca_file, cert_file, key_file, cipher_suite and peer_verify.  Note that unlike the main syslog-ng peer_verify option, this one just takes a boolean value.
Closes https://github.com/balabit/syslog-ng/issues/1436
Signed-off-by: Todd C. Miller <Todd.Miller@courtesan.com>
=> Add SSL/TLS options to the http (curl) module

scl/rewrite/cc-mask.conf
syslog-ng automatically stores the first result in the $1 macro thus
we don't need to name it.
Otherwise the original solution did not work because PCRE does not supported group names
started with digits anymore.
=> cc-mask: Removed unnecessary group name

Makefile.am, configure.ac, lib/Makefile.am, modules/afamqp/Makefile.am
This PR fixes `make dist` when syslog-ng is configured with `--with-ivykis=system` or `--with-librabbitmq-client=system`.
=> Include ivykis and librabbitmq in the dist tarball

modules/afsocket/afsocket-dest.c
Otherwise processed stats counter won't be updated.
Fixes: #1409
=> afsocket: use the log_dest_driver_queue_method for queueing

lib/afinter.c, lib/control/tests/test_control_cmds.c, lib/driver.c, lib/logmsg/logmsg.c, lib/logmsg/tags.c, lib/logsource.c, lib/logthrdestdrv.c, lib/logwriter.c, lib/stats/CMakeLists.txt, lib/stats/Makefile.am, lib/stats/stats-cluster-logpipe.c, lib/stats/stats-cluster-logpipe.h, lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, lib/stats/stats-csv.c, lib/stats/stats-log.c, lib/stats/stats-query.c, lib/stats/stats-registry.c, lib/stats/stats-registry.h, lib/stats/stats-syslog.c, lib/stats/stats.c, lib/stats/tests/test_stats_cluster.c, lib/stats/tests/test_stats_query.c, lib/syslog-ng.h, modules/afsql/afsql.c, modules/diskq/tests/test_diskq_full.c
- Motivation
- support new types of counters that are not fit into the existing StatsCluster implementation
- example for new types: LogQueue related metrics (queue size in bytes which is definitely not a STORED/PROCESSED/... kind of counter)
- Changes initiated by this PR
- extracted StatsClusterKey
- (id, component, instance)  group was used as a key for StatsCluster so this is just an equivalent change and as a side effect the interface is simpler now (number of parameters has been reduced significantly for register_counter method-family)
- initiated StatsCounterGroup (this name is not the final one, maybe StatsClusterCounters is better... )
- number of counters can vary
- the group initializer(that is reponsible for allocating counters) method added to StatsClusterKey
=> Stats cluster refact

lib/cfg-lex.l
It caused infinite loop if the config file had a comment line without newline as a last expression. (We got 0 instead of EOF, so we never stopped reading.)
Fixes #1460
=> cfg-lex: handle API change in flex

lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, lib/stats/stats-counter.c, lib/stats/stats-counter.h, lib/stats/stats-query-commands.c, lib/stats/stats-query.c, lib/stats/stats-query.h, lib/stats/stats-registry.c, lib/stats/stats-registry.h, lib/stats/stats.c, lib/stats/tests/test_stats_query.c
Motivation
========
The main goal of this PR is to support fully globbing when searching for counters and eliminate workarounds introduced in an earlier PR. So from now on it is possible to search using `src.*` and get all of the counters which name stats with `src.`. There is no need to add further `.*` to get all counters.
Changes
=======
* `StatsCounterItem` has an attribute named `name` which consist of the `query_id` of its `StatsCluster` and the name of the type.
* Add `counter_index` hash table where the key is name of the counter and the value is the pointer to the counter. As the construction of the key is expensive, it is only generated once when a `StatsCounterItem` is queried.
* Introduce `indexed_mask` for `StatsCluster`s to know which counter is in `counter_index`. …
=> Add "index" to counter container

lib/stats/stats-counter.h, lib/stats/stats-csv.c, lib/stats/stats-log.c, lib/stats/stats-query-commands.c, lib/stats/tests/test_stats_query.c
On 64 bit platforms we can use 64 bit atomic counters.
=> stats: replace type of StatsCounter value from gint to gssize

lib/msg-format.c, lib/msg-format.h, modules/linux-kmsg-format/linux-kmsg-format.c, modules/linux-kmsg-format/tests/test_linux_format_kmsg.c, modules/syslogformat/syslog-format.c, tests/unit/test_msgparse.c
The solution is that print the position where the parsing was failed,
not only a something evil happened message
fixes: #SYSLOGMT-643
Signed-off-by: László Várady <laszlo.varady@balabit.com>
=> syslogformat: If the parsing of a message failed, then we had to find the problem with eyegrep

modules/kvformat/kv-scanner.c, modules/kvformat/tests/test_kv_scanner.c
`_skip_initial_spaces()` calls the `_match_delimiter()` function which uses the value of `value_was_quoted`.
Since this variable contains the state of the previously parsed value, it should be invalidated.
=> kvformat: invalidate value_was_quoted before extracting the next value

lib/CMakeLists.txt, lib/Makefile.am, lib/apphook.c, lib/cfg-lexer.c, lib/dnscache.c, lib/filter/filter-cmp.c, lib/logmsg/tags-serialize.c, lib/mainloop-worker.c, lib/mainloop-worker.h, lib/mainloop.c, lib/scratch-buffers2.c, lib/scratch-buffers2.h, lib/tests/Makefile.am, lib/tests/test_scratch_buffers.c, modules/afamqp/afamqp.c, modules/afsocket/transport-unix-socket.c, modules/afsql/afsql.c, modules/afstomp/afstomp.c, modules/dbparser/pdb-load.c, modules/dbparser/pdbtool/pdbtool.c, modules/diskq/dqtool.c, modules/diskq/tests/test_diskq.c, modules/geoip/geoip-parser.c, modules/json/json-parser.c, modules/linux-kmsg-format/linux-kmsg-format.c, modules/pseudofile/pseudofile.c, modules/riemann/riemann.c, tests/unit/test_logqueue.c
This branch implements an alternative scratch buffers implementation that should be easier to use and that solves the per-thread buffer allocation which is freed automatically.
=> Scratch buffers2

lib/stats/stats-cluster.c, lib/stats/stats-query.c, lib/stats/stats-query.h, lib/stats/stats.c, lib/stats/tests/test_stats_query.c
Aggregated `StatsCounterItem` is introduced using views on `stats_cluster_container`. These counters can be used to query calculated values from syslog-ng and to alias existing counters.
A view consist of a list of queries, which is used to collect input counters. After input counters are collected, an aggregator function is called on these and a single `StatsCounterItem` is returned.
It is possible to create a new view using:
```
void
_aggregator_function(GList *input_counters, StatsCounterItem **result)
{
gint sum = 0;
for (GList *counter = input_counters; counter; counter = counter->next)
{
StatsCounterItem *item = (StatsCounterItem *) counter;
sum += stats_counter_get(item);
} 
}
void
setup_my_view(void)
{
GList *queries = NULL;
queries = g_list_append(queries, "src.pipe.my_source"); …
```
=> Introduce calculated metrics

lib/logthrdestdrv.c, modules/afmongodb/afmongodb.c, modules/afsmtp/afsmtp.c, modules/java/native/java-destination.c, modules/python/python-dest.c, modules/python/python-grammar.ym
With this patch one can use retries() option for
python destination. For example:
destination d_python {
python(class("ClassFoo") retries(3));
};
See:
https://github.com/balabit/syslog-ng/issues/1424
=> python: retries support for python destination

lib/logthrdestdrv.c, modules/afmongodb/afmongodb.c, modules/afsmtp/afsmtp.c, modules/java/native/java-destination.c
This patch was reverted on master, as it caused @kira-syslogng tests to break. This branch contains the offending patch and should go through the testing/review process again.
The breaking patch is: 484e27665f68013a31eab3e762dcf20ef49e97e8
The revert is: 5a7ecae21cc54bb7506968c5eadbbcb681b8bdc2
Once this is green, it can go in again.
=> readd reverted refactoring patch of LogThreadedDestination's retry logging

lib/stats/tests/test_stats_query.c
As pointed out by @lbudai, `stats_init` was called twice, so tests failed during teardown. This is now fixed.
Furthermore, unnecessary test cases were removed, because those
have become obsolete as the internals of quering had changed.
=> stats-query: fix unittest

lib/logqueue-fifo.c, lib/logqueue.c, lib/logqueue.h, lib/logthrdestdrv.c, lib/logthrdestdrv.h, lib/logwriter.c, lib/scratch-buffers2.c, lib/stats/stats-cluster-logpipe.c, lib/stats/stats-cluster-logpipe.h, lib/stats/stats-counter.c, lib/stats/tests/test_stats_query.c, modules/afsql/afsql.c, modules/afsql/afsql.h, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c
From now on `stored` counter is going to be called `queued`. Log messages which are `queued` are  sent out to destinations.
Please make sure that you follow up the changes in your scripts, because it might broke if you depend on the name `stored`. The Kira check is expected to be red, as it checks for the counter names.
=> Rename stored to queued

lib/stats/stats-query-commands.c
The format is changed to make parsing easier.
=> syslog-ng-ctl: change output format to =

lib/logthrdestdrv.c, lib/logwriter.c, lib/stats/CMakeLists.txt, lib/stats/Makefile.am, lib/stats/stats-counter.h, lib/stats/stats-query.c, lib/stats/stats-query.h, lib/stats/stats-registry.c, lib/stats/stats-registry.h, lib/stats/stats-views.c, lib/stats/stats-views.h
Add written view for every destination to see how many messages have been sent out by destinations. The method to calculate it is the following:
```
written = processed - queued - dropped
```
A module `stats-views`, which contains views, so it can be reused in different places.
=> Introduce written counter for destinations

lib/stats/stats-views.c
In a counter name is query, it was freed twice. Once when the views were freed and once when the index was freed. From now on it is fixed,
=> stats-view: fix double free of written counter

lib/scanner/csv-scanner/csv-scanner.c, modules/add-contextual-data/tests/test_context_info_db.c, modules/csvparser/csvparser.c, modules/csvparser/tests/test_csvparser_perf.c
Improving csvparser performance by using scratch-buffer2.
For: https://github.com/balabit/syslog-ng/issues/1426
=> csvparser: scratch-buffers2-ification

lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, modules/python/python-dest.c
This patchset fixes two issues related to python destionation.
- counter statistics: emit dst.python instead of dst.none
https://github.com/balabit/syslog-ng/issues/1362
- during retry-send, code only checked if is_opened(), but did not try to open if not.
https://github.com/balabit/syslog-ng/issues/1422
Stats error counter feature depends on both.
=> Python stat fix

modules/dbparser/CMakeLists.txt, modules/dbparser/Makefile.am, modules/dbparser/patterndb.c, modules/dbparser/patterndb.h, modules/dbparser/pdb-context.c, modules/dbparser/pdb-context.h, modules/dbparser/pdb-lookup-params.h, modules/dbparser/pdb-ratelimit.c, modules/dbparser/pdb-ratelimit.h, modules/dbparser/pdb-ruleset.c, modules/dbparser/pdb-ruleset.h, modules/dbparser/tests/test_patterndb.c
This series of patches incorporate a number of refactoring steps within db-parser and also fix a deadlock situation reported by Evan Rempel.
The refactoring steps aim at two things:
* split out a few helper classes to modules of their own
* introduce a per-thread state that is used throughout pattern_db_proces() and its chain of function calls to simplify parameter lists
The fix itself builds on the second refactoring step: we use this state to store a list of messages to be emitted, instead of emitting them right away. This way we can release all locks through log_db_parser_emit(), which resolves the deadlock. Earlier a number of workarounds were present in the code, that were only partial fixes, this patch removes the workarounds and resolves the situation for good.
=> Db parser deadlock2

lib/stats/stats-cluster-logpipe.c, lib/stats/stats-cluster-single.c, lib/stats/stats-cluster-single.h, lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, lib/stats/tests/test_stats_cluster.c, lib/stats/tests/test_stats_query.c
This change is needed by implementing some new counters.
@kvch   : you will use this refact, so it is up to you whether you just use this refact as a first patch of your PR, or merge this as is.
=> stats: support custom tagnames for StatsCounterGroups

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logmsg/nvtable.h, lib/logmsg/tests/test_log_message.c, lib/logqueue-fifo.c, lib/logqueue.c, lib/logqueue.h, lib/logthrdestdrv.c, lib/logthrdestdrv.h, lib/logwriter.c, lib/stats/stats-cluster-logpipe.c, lib/stats/stats-cluster-logpipe.h, lib/stats/stats-control.c, lib/stats/stats-counter.c, lib/stats/stats-counter.h, modules/afsql/afsql.c, modules/afsql/afsql.h, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/tests/test_diskq.c, tests/unit/test_logqueue.c
New counter that measures the memory used by messages in the different kind of queue types in bytes: logqueue-fifos, reliable disks and non-reliable disks.
=> Monitoring buffers: memory_usage

lib/filter/filter-cmp.c, lib/filter/filter-expr.c, lib/filter/filter-in-list.c, lib/filter/filter-pipe.c, lib/filter/filter-re.c, lib/filter/filter-tags.c, lib/logmatcher.c, lib/logmpx.c, lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/rewrite/rewrite-groupset.c, modules/cryptofuncs/tests/test_cryptofuncs.c, scl/Makefile.am, scl/cisco/plugin.conf
This branch adds a parser for cisco generated messages, assuming they were received using flags(no-parse).
It works like this:
```
@version: 3.9
log {
source { udp(flags(no-parse)); };
parser { cisco-parser(); };
destination { ... };
};
```
The parser would parse various formats generated by routers (e.g. various settings to service timestamps, service sequence-number, logging origin-id), and normalizes messages so that:
MESSAGE=%FAC-SEV-MNEMONIC: message
HOST=origin-id
DATE=<as parsed from timestamp>
It also extracts information to a number of Cisco specific name-value pairs:
${.cisco.facility}
${.cisco.severity}
${.cisco.mnemonic}
NOTE: It contains a number of improvements/fixes that were found while creating the parser, obviously those could be merged separately.
=> Cisco parser

scl/osquery/plugin.conf
It reads the osquery log file and parses with the JSON parser,
creating name-vaule pairs with an .osquery. prefix by default.
file() and prefix() can be overriden.
Example usage:
source s_osquery { osquery(prefix("micimaci.")); };
destination d_json { file("/var/log/test.json" template("$(format_json --scope rfc5424 --scope nv-pairs)\n\n")); };
log { source(s_osquery); destination(d_json); };
=> Add osquery scl to syslog-ng

lib/scanner/kv-scanner/kv-scanner.c, lib/scanner/kv-scanner/kv-scanner.h, lib/str-format.c, lib/str-format.h, lib/str-repr/decode.c, lib/str-repr/decode.h, modules/Makefile.am, modules/snmptrapd-parser/CMakeLists.txt, modules/snmptrapd-parser/Makefile.am, modules/snmptrapd-parser/snmptrapd-header-parser.c, modules/snmptrapd-parser/snmptrapd-header-parser.h, modules/snmptrapd-parser/snmptrapd-nv-context.h, modules/snmptrapd-parser/snmptrapd-parser-grammar.ym, modules/snmptrapd-parser/snmptrapd-parser-parser.c, modules/snmptrapd-parser/snmptrapd-parser-parser.h, modules/snmptrapd-parser/snmptrapd-parser-plugin.c, modules/snmptrapd-parser/snmptrapd-parser.c, modules/snmptrapd-parser/snmptrapd-parser.h, modules/snmptrapd-parser/tests/Makefile.am, modules/snmptrapd-parser/tests/test_snmptrapd_parser.c, modules/snmptrapd-parser/tests/test_varbindlist_scanner.c, modules/snmptrapd-parser/varbindlist-scanner.c, modules/snmptrapd-parser/varbindlist-scanner.h, scl/Makefile.am, scl/snmptrap/snmptrapd-source.conf, tests/copyright/policy
This PR contains the snmptrapd parser plugin and a filesource-based snmptrapd SCL source block.
snmptrapd-parser can be used to parse the default output of Net-SNMP's snmptrapd.
The parsed information is available as key-value pairs, which can be used/serialized (macros, format-json, etc.) in the log path.
Because the `:` character is not accepted as a macro name in the configuration language of syslog-ng, all consecutive `:` characters are replaced with a single `_`.
For example, the value of the `NET-SNMP-EXAMPLES-MIB::netSnmpExampleString` key can be accessed with `${NET-SNMP-EXAMPLES-MIB_netSnmpExampleString}`.
If you want to forward the message in a structured way, you can disable the default message generation with the `set-message-macro(no)` option.
Currently, the default V2 output …
=> snmptrapd parser

modules/systemd-journal/journal-reader.c
This is not yet mergeable, as it does not have tests.
=> systemd-journal: fix prefix() default for new config versions

lib/logmpx.c
=> logmpx: do not make logmsg write protected in case of single logpath

lib/gprocess.c, lib/logreader.c, lib/logwriter.c, lib/mainloop-io-worker.c, lib/mainloop-worker.c
Prior this patch, in case of high load scratchbuffers garbage
collection might not be executed for a very long time, because ivykis
worker thread is optimized to exhaust the main thread.
This patch explicitely calls scratchbuffers garbage collection during
fetching and flushing messages.
@bazsi @MrAnno
=> Scratchbuffers optimization

scl/elasticsearch/plugin.conf
Elasticsearch and Kibana use UTC internally. Sending logs with UTC,
they end up in the right index and show up at the right time in
Kibana. Helps to avoid surprises and long debugging sessions :)
Suggested by Fabien Wernli on the syslog-ng mailing list.
=> Set the default time-zone to UTC for elasticsearch2

modules/diskq/diskq-options.c
Grammar allows disk-buf-size to be 0.
However in that case syslog-ng exits on the first incoming message due to SEGFAULT.
The code detects that the disk-buf-size is not correct, but allows it.
"[2017-05-31T09:46:05.408827] WARNING: The configured disk buffer size is zero. No disk queue file will be created.;"
=> diskq: cover case disk-buf-size(0)

modules/riemann/riemann.c
This patchset contains various bugfixes/improvements for Riemann destination.
A little comment for one of these issues: in case flush-lines is configured, messages can get stuck in the internal queue of Riemann destination. 
The optimistic path when Riemann server is connected is covered by this patchset. But the failure path when Riemann server is not connected is not covered. In the latter case syslog-ng will try to send batch once, but will not retry again, until the new messages arrived, or the batch filled suddenly completely, which latter case is again covered by this patch.
Also, for now in case flush-lines is used and unaccessible Riemann server, all events except the latest in the batch will be lost, because LogThrDestDriver do not support such message bulk rewind support. Only …
=> Riemann destination: various bugfixes including heap corruption

lib/gprocess.c
The java8 oracle implementation puts two additional variables to
the environ(it is reallocated by libc). It caused crash in java
destination during our testing process.
The fix: track how many items we put to the environ array,
and free only those items. This works as libc use memcpy when realloc
the environ array and the new items appeded to the end of the
reallocated array.
=> gprocess: fix oracle-8-jvm related issue

modules/affile/tests/Makefile.am
Previously, `modules_affile_tests_TESTS` were redefined if Criterion was found on the system. Because of this on my systems syslog-ng did not compile. On other systems `affile_open_file` unittest never ran.
=> Do not redefine modules_affile_tests_TESTS in Makefile

modules/geoip/Makefile.am, modules/geoip/geoip-helper.c, modules/geoip/geoip-helper.h, modules/geoip/geoip-parser.c, modules/geoip/tfgeoip.c
Fixing: https://github.com/balabit/syslog-ng/issues/663
and https://github.com/balabit/syslog-ng/issues/1446
This patchset removes the invalid database warning that is written by geoip plugin in syslog-ng in certain circumstances.
There are two database types that operators can use: city and the country version. In the original behaviour, syslog-ng tried to interpret the database as if it was city version: GeoIP_record_by_name, and in case it fails, she falls back to the country version: GeoIP_country_code_by_name.
But in case of mismatch, libgeoip writes an unmaskable warning about invalid database. Hence the problem.
The resolution is the following: during init phase, syslog-ng detects the database type, and uses only the appropriate api call that is compatible with the detected …
=> geoip: legacy library - invalid database warning

configure.ac
This PR contains 3 minor configure fixes which are needed to compile syslog-ng _correctly_ with `--enable-all-modules`.
=> Minor configure fixes

lib/logwriter.c, modules/systemd-journal/journal-reader.c
This patchset contains fixes for two invalid read issues:
- System source: a value (program name) that needs to be added to nvtable is invalidated due to nvtable realloc.
- File destination: in case target file cannot be created, reopen_timer goes on infinitely, not stopped even after syslog-ng stops. Thus the scheduled timer has invalid cookie, thus an invalid read occurs during syslog-ng stop.
A little more verbose description can be found in commit messages.
=> Invalid read in system source/nvtable and in file destination

lib/logthrdestdrv.c, lib/logwriter.c
Otherwise value of written counter could underflow when diskq is used
and the diskq contains some messages after restart.
written = processed - (queued+dropped)
=> stats: set processed counter to the value of queued counter in init-time

configure.ac
In 3615b6698daf166c814588fe9fcdaa4ed93204cb, the libnet detection check was implemented incorrectly.
=> configure: fix enable-spoof-source again

lib/logqueue.c, lib/logqueue.h, lib/logwriter.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk.h, modules/diskq/qdisk.c, modules/diskq/qdisk.h
In case syslog-ng stopped with messages in a non reliable queue,
after next start non-reliable queue restores the qout queue. This
restoration should be visible in memory_usage, otherwise when the
destination becomes writable, memory_usage will underflow.
=> Logwriter: memory_usage underflow in case of non-reliable queue

modules/diskq/diskq.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c
Previously, `queue->type` was not initialized correctly at all (fixed in #1539), so `_acquire_queue` created a new queue in every case.
NOTE: The removed logic is reasonable and valuable, so we should consider reverting this patch after log_queue_disk_load_queue() is fixed.
=> diskq: remove an always TRUE condition in _acquire_queue

lib/logqueue.c, lib/logqueue.h, modules/diskq/logqueue-disk-non-reliable.c
We have found an error around memory usage counter when non-reliable disk-buffer is used and syslog-ng is reloaded.
We have found that the problem is around the overflow buffer which was not re-initialized after reload.
It caused an underflow in memory usage counter when syslog-ng can successfully send the messages from the disk-buffer.
Using the same solution that was done for qout buffer.
=> Fix memory usage counter bug #2: disk-buffer, overflow buffer and reload

lib/logthrdestdrv.c, lib/logwriter.c
Previously, it was added not set. This doubled the value and
led to bad written counter value.
=> stats: set processed counter to the value of queued

lib/logthrdestdrv.c, lib/logwriter.c, lib/stats/stats-registry.c, lib/stats/stats-registry.h, modules/afsocket/afsocket-dest.c
During reload, memory_usage counter is reset, but the queue might be maintained, for example when it contains messages. This leads counter value inconsistency during reload. After opening the destination, memory_usage will underflow.
To prevent this, memory_usage counter is saved to the persistent storage inside GlobalConfig, so that its value can be reloaded together with the queue.
During the implementation we run into another bug: after reload the reference to the cfg object of writer is corrupted, because when we fetch the writer object from persistent config, the writer object will refer to the already destroyed config object. This needed to be fixed by this patchset as well.
=> LogQueueFifo memory usage underflow and cfg object corruption during reload

scl/apache/apache.conf
This way it can parse any templates, not just MESSAGE. To retain
backwards compatibility, MESSAGE is parsed by default.
=> Add template() option to apache-accesslog-parser(). 

lib/logsource.c
This information can be useful when a user wants to find out why syslog-ng doesn't receive messages.
@jszigetvari 
Note that these are just debug messages; if you want to measure the "availability of sources", an `iw-size` related stat counter would be a better choice.
=> logsource: add "source suspended/resumed" debug messages

dbld/images/jessie/dev-dependencies.txt
release tarball requires automake1.11
=> dbld: use automake.11 in debian environment

lib/stats/stats-query.c
During counter registration the StatsCluster->indexed_mask was
accounted inappropriately: the shift operator was missing when set or
reset the bitmap.
=> stats-counter: missing counters due to invalid indexing

lib/cfg-tree.c
Example:
Error initializing message pipeline; location='syslog-ng.conf:26:23'
This "location" can help to point which driver failing during the
config initializtion.
=> CfgTree: Improve error message when config can not initialized

lib/logthrdestdrv.c, lib/logthrdestdrv.h, modules/afamqp/afamqp.c
Fixes: https://github.com/balabit/syslog-ng/issues/1513
There were two issues with afamqp that lead to crashing when
timer_reopen registered.
Afamqp did not virtualize connect function, even though it
should have done. As a result, connect/reconnect logic did not work
inside LogThrDestDrv, essentially logthrdestdrv marked the destination
as connected even though connection failed. Therefore, logthrdestdrv
pushed message to afamqp. Afamqp knew well that she was not connected,
so she tried to reconnect. Though the connection failed again, so
WORKER_INSERT_RESULT_NOT_CONNECTED was sent back to
logthrdestdrv. Receiving this error code, logthrdestdrv start the
suspend logic.
Afamqp, as the the connect function was not virtualized, tried to
execute the suspend logic during connect as well.
In …
=> afamqp: layer violation in suspending thrdestdrv results in crash

.gitignore, lib/.gitignore, modules/diskq/diskq.c, modules/diskq/dqtool.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-non-reliable.h, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk-reliable.h, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/tests/test_diskq.c, modules/diskq/tests/test_diskq_full.c, modules/diskq/tests/test_reliable_backlog.c
This PR fixes 2 minor memory leaks in the disk buffer module.
```
41 bytes are definitely lost
by g_strdup (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
by _acquire_queue (diskq.c:56)
61 bytes are definitely lost
by persist_state_lookup_string (persist-state.c:825)
by _acquire_queue (diskq.c:58)
8 bytes are definitely lost
by g_mutex_new (in /lib/x86_64-linux-gnu/libglib-2.0.so.0.4800.2)
by log_queue_reset_parallel_push (logqueue.c:69)
```
I've also added a refactor commit, which propagates `persist_name` through the constructor of `LogQueue`.
@furiel I'm dedicating this PR to you. :smile:
=> Fix minor memory leaks in disk buffer

modules/dbparser/dbparser-grammar.ym, modules/dbparser/dbparser-parser.c, modules/dbparser/dbparser.c, modules/dbparser/dbparser.h
This patch adds a new drop-unmatched() option to db-parser() that causes
unmatched messages to be dropped, like this:
db-parser(drop-unmatched(yes));
If none of the rules match, the message would be dropped. If there's
a match the message goes "through".
=> dbparser: add drop-unmatched() option

Makefile.am, contrib/Makefile.am, contrib/README.syslog-ng-debun, contrib/syslog-ng-debun
This PR 
- renames syslog-debun to syslog-ng-debun
- installs syslog-debun, so it can be included easily in .rpm, .deb packages
@lbudai @jszigetvari @czanik
=> contrib: install syslog-debun

modules/affile/affile-dest.c
We allow using disk-buffer for file sources, nevertheless syslog-ng crashes.
It is crashing when the file destination is reaping and log_writer_flush is called during deinit.
The reason is that during reaping we deinitialized the diskq and then called log_writer_flush which tries to access the diskq, but its already a NULL pointer.
This patch checks if the diskq is deinitialized before trying to access the diskq.
=> diskq: fix crash when diskq is used with file destionation and file is reaped

lib/logmsg/logmsg.c, lib/logmsg/nvtable.c, lib/logmsg/nvtable.h, lib/logmsg/tests/test_nvtable.c
This PR contains multiple refactor steps in NVTable and a fix for #1514.
These are equivalent transformations except for a37a042f785cd105c6fe2840512626421a6ccb35.
Example config (to reproduce the bug):
```
log {
source { program("/usr/bin/yes"); };
rewrite {
subst(".*", "nope", value(".SDATA.missing.value"));
};
destination { file("/tmp/out.txt"); };
};
```
Fixes #1514
=> Fix subst() on non-existing macro

contrib/Makefile.am, contrib/solaris-packaging/syslog-ng-sol11-smf.example.xml, contrib/solaris-packaging/syslog-ng.method
Added Syslog-ng multi-instance support for Solaris 10 and 11, originally created by @pasztor with some minor modifications.
=> Solaris SMF multi-instance support

modules/http/http-grammar.ym, modules/http/http-parser.c, modules/http/http-plugin.h, modules/http/http.c
- Memory leak during reload/stop
- Invalid handling of retry-send when remote is down.
See: https://github.com/balabit/syslog-ng/issues/1500
- Replacing some loops with foreach
- Using scratchbuffers to store body of the http request
- Curl options are set only once during init
- Timeout is configurable for http request
- HTTP responses handled correcty: 2XX ack, 4XX drop, 5XX retry.
Please wait @mitzkia or @pzoleex with the merge.
=> http destination: improvements

scl/cisco/plugin.conf
With this option a user can change the prefix for cisco specific fields
and for example add it to SDATA. Just change prefix to ".SDATA.cisco."
=> cisco-parser: Added prefix option

.travis.yml
I've released it in my OBS repository for Travis.
https://build.opensuse.org/package/show/home:laszlo_budai:syslog-ng/libmaxminddb
=> travis: install libmaxminddb-dev in Travis

contrib/solaris-packaging/solaris10_install.txt, contrib/solaris-packaging/syslog-ng.method, contrib/solaris-packaging/syslog-ng@default
contrib/solaris-packaging/syslog-ng.method: reworked to support new default files
contrib/solaris-packaging/syslog-ng@default: added an example default file
contrib/solaris-packaging/solaris10_install.txt: added step to install default file
* added support for systemd-multi-instance type of default files
* default files should now work the same way as with systemd instances
* naming of the default files has changed to reflect those supporting systemd
* reworked the method file to support additional options
* set up a hierachy how settings take precedence of each other
* installation directories/prefixes such as /usr/local may be a bit off
and may require corrections by the end user to match his/her use case
* renamed config variables to match those used with systemd's instances …
=> Rework of Solaris SMF multi-instance support, to support unified-style default files

lib/cfg-lexer.c, lib/cfg.c, lib/cfg.h
With these patches, the syslog-ng's configuration mechanism can be used to parse syslog-ng config file snippets.
```c
GlobalConfig *cfg_snippet = cfg_new_snippet(configuration->user_version);
cfg_read_config(cfg_snippet, file_path, FALSE, NULL);
GList *objects_in_cfg_snippet = cfg_tree_get_objects(&cfg->tree);
for (GList *cfg_object = objects_in_cfg_snippet; cfg_object != NULL; cfg_object = cfg_object->next)
{
LogExprNode *node = (LogExprNode *) cfg_object->data;
/* work with `node` */
}
```
We are already do this, and there were a bug report that some modules were loaded multiple times. This is an alternative implementation of #1568.
=> Add function to load config snippet

scl/Makefile.am
* without this patch "scl/osquery/plugin.conf" will not copied under share/syslog-ng/include/scl/
=> SCL: Add missing reference for osquery into scl/Makefile.am

lib/logthrdestdrv.c
Like in afsql, an explicit GC call is necessary before (at least) every do_work().
=> logthrdestdrv: add missing GC call

.travis.yml, lib/debugger/tests/test-debugger.c, lib/filter/tests/test_filters.c, lib/filter/tests/test_filters_in_list.c, lib/filter/tests/test_filters_statistics.c, lib/logmsg/tests/test_logmsg_serialize.c, lib/rewrite/tests/test_rewrite.c, lib/template/tests/test_template_compile.c, lib/tests/test_host_resolve.c, lib/value-pairs/tests/test_value_pairs.c, lib/value-pairs/tests/test_value_pairs_walk.c, libtest/msg_parse_lib.c, modules/add-contextual-data/tests/test_selector.c, modules/affile/tests/test_wildcard_source.c, modules/afmongodb/tests/test-mongodb-config.c, modules/csvparser/tests/test_csvparser.c, modules/csvparser/tests/test_csvparser_statistics.c, modules/date/tests/test_date.c, modules/dbparser/tests/test_patterndb.c, modules/dbparser/tests/test_patternize.c, modules/diskq/tests/test_diskq.c, modules/diskq/tests/test_diskq_full.c, modules/diskq/tests/test_reliable_backlog.c, modules/linux-kmsg-format/tests/test_linux_format_kmsg.c, modules/snmptrapd-parser/tests/test_snmptrapd_parser.c, modules/systemd-journal/tests/test_systemd_journal.c, tests/unit/test_hostid.c, tests/unit/test_logwriter.c
Loading all candidate modules in unit tests is unnecessary.
This PR also contains a small Travis configuration modification to make our master green.
Finalize #1575 and #1597
=> tests: replace cfg_new() with cfg_new_snippet()

modules/riemann/riemann-grammar.ym, modules/riemann/riemann-parser.c, modules/riemann/riemann.c, modules/riemann/riemann.h
New configuration parameter is added to riemann destination that
controls the calculation of event time: event_time(). In case omitted,
the default value is ${UNIXTIME}.
For example:
destination d_riemann {
riemann(
server("127.0.0.1")
port(5555)
event_time("${UNIXTIME}")
[...]
);
Fixes: https://github.com/balabit/syslog-ng/issues/1598
=> riemann: configurable event time

lib/logthrdestdrv.c, lib/logthrdestdrv.h, lib/mainloop-worker.c, lib/mainloop-worker.h, lib/mainloop.c
Reload and stop commands are implemented as an async calls. These async calls only executed when there are no workers running.
In case of slow workers or high load, workers might not be exited for a long time, possibly infinitely in case sources are faster than the destinations. This results in such async calls held back.
The original implementation g_asserts that only one async call is running at a given time, though it is possible in the scenarios above that the 100ms is not enough for the previous async call to exit, resulting in crash.
See: https://github.com/balabit/syslog-ng/issues/1506
This patch collects the commands to be executed in a queue. When all workers exited, we iterate through the queue and call all such actions.
This fixes the crash part.
But certainly it is also an …
=> MainLoop: crash due to async calls might be held back without limit

autogen.sh
Unfortunately conditional include of an automake file is not supported.
=> autogen: include {debian,tgz2build}/Makefile.am when exists

modules/diskq/tests/test_diskq.c
The goal of the referring assertion is to have some estimate of the
memory usage of a message, and to track its change in future
developments. As it is hard to give precise memory usage, only a
reasonable lower and upper bound was given. The problem was that only
64bit systems were taken into consideration. On 32bit systems, message
size can be lower. This patch extends the boundaries so that assertion
would not be triggered on 32bit systems either.
Fixes: https://github.com/balabit/syslog-ng/issues/1545
=> statistics: msg_size issue in unit testcase

modules/geoip/tfgeoip.c
Prior this patch only the geoip parser was marked as deprecated,
although template function and parser should have been marked as
deprecated at the same time. Now a notice will be emitted if user uses
geoip template function too, suggesting to change for geoip2.
=> geoip: deprecated notice in geoip template function

modules/dbparser/pdbtool/pdbtool.c, modules/diskq/dqtool.c
Loading candidate_modules is unnecessary.
=> pdbtool,dqtool: replace cfg_new() with cfg_new_snippet()

lib/cfg-lexer.c, lib/cfg.c
At this point, all plugin info should be available for license.
This is the Lagrangian point of the license module.
=> cfg: load license after '@module' pragma initialization

lib/mainloop-worker.c
The reload mechanism is syslog-ng is done in 3 stages.
- Stage1: ctl/hup signal initiates reload
Old configuration saved, new configuration validated, stage2 is
registered to be executed when no workers are
running (main_loop_worker_sync_call).
All workers are notified to stop as soon as possible.
- Stage2: Configuration applied.
Configuration applied, (workers are still stopped), stage3 registered to be executed later.
- Stage3: Reenables workers, reload finished.
There is a special case when no workers are created. In that case the
three stages can be executed in one step. It is handled by a special
if-branch in main_loop_worker_sync_call. But this branch only called
stage2, and did not call stage3. This means the reload was never
finalized, resulting in that users cannot reinitiate …
=> mainloop: regression: reload not finalized if no workers around

syslog-ng/main.c
Fix macro usage acording to our syslog-ng-config.h.
Compile date will be visible with -V option.
=> main: fix compile date macro usage

modules/syslogformat/syslog-format.c, tests/unit/test_msgparse.c
Fixes:
https://github.com/balabit/syslog-ng/issues/1616
=> syslog-format: cannot parse ipv6 into hostname

modules/java/native/java-destination.c, modules/java/proxies/java-destination-proxy.c, modules/java/proxies/java-destination-proxy.h, modules/java/proxies/java-template-proxy.c, modules/java/src/main/java/org/syslog_ng/LogDestination.java, modules/java/src/main/java/org/syslog_ng/LogTemplate.java
Fixes: https://github.com/balabit/syslog-ng/issues/1410
Prior this patch zero was passed as sequence number in java destination templates. This patch propagates the sequence number controlled by the threaded destination driver into LogDestination class, so it will be available in the inherited classes. Thus users can pass it to LogTemplate object when sequence number is used in a template formula.
For example:
```
LogTemplate logTemplate = new LogTemplate(getConfigHandle());
logTemplate.compile("${SEQNUM}\n");
InternalMessageSender.debug(logTemplate.format(logMessage, 0, logTemplate.LTZ_SEND, getSeqNum()));
```
=> java destination: sequence number support for templates

configure.ac, lib/compat/openssl_support.c, lib/compat/openssl_support.h, lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afinet-dest.c, modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, modules/afsocket/afsocket-source.c, modules/afsocket/transport-mapper-inet.c, modules/afsocket/transport-mapper.h
This PR contains
- a medium-sized refactor in tlscontext
- minor fixes
- TLS features:
- startup time `ssl-options()` and `peer-verify()` check
- startup time `key_file`, `cert_file`, `ca_dir`, `crl_dir` and `cipher_suite` check
- **ECDH  cipher support** (OpenSSL 1.0.1, 1.0.2, 1.1.0) with the `ecdh-curve-list()` option (only available >= 1.0.2)
- for < 1.0.2, a hard-coded curve is used
- for >= 1.0.2, automatic curve selection is used (the `ecdh-curve-list()` option can restrict this list)
- **DH cipher support** with the `dhparam-file()` option
- if the option is not specified, fallback RFC 3526 parameters are used
Example usage:
```
$ openssl dhparam -out /dh/dh2048.pem 2048
syslog(
port(4444)
transport(tls)
tls(
ecdh-curve-list("prime256v1:secp384r1") # <---- new …
```
=> TLS improvements

modules/affile/tests/Makefile.am
=> affile/tests: test_file_opener depends on criterion

lib/cfg-grammar.y, lib/cfg-parser.c, lib/logsource.c, lib/logsource.h, modules/systemd-journal/journal-reader.c
This PR supports `read_old_records` only for journal source.
=> Read old records

modules/add-contextual-data/add-contextual-data-selector.h, modules/add-contextual-data/add-contextual-data.c, modules/add-contextual-data/context-info-db.c, modules/add-contextual-data/context-info-db.h, modules/add-contextual-data/tests/test_context_info_db.c
**This pull request breaks the API of `AddContextualDataSelector`, so it MUST be merged together with our internal modules (branchname: acd-optional-ordering)**
Template based selection does not require ordering, so the time complexity of this operation is unnecessary here.
Fixes #1439
=> add-contextual-data: make ordering optional

modules/affile/wildcard-source.c
Previously `create_directory_monitor()` used the default value: "auto".
=> Fix the monitor-method() option of wildcard-file()

lib/logmsg/logmsg.c, lib/logmsg/tests/test_log_message.c
Any JSON object can be parsed to SDATA, so the key could contain any character, while the specification does not declare any way to encode the the keys, just the values.
The goal is to have a syntactically valid syslog message.
Fixes #1583
```
...
STRUCTURED-DATA = NILVALUE / 1*SD-ELEMENT
SD-ELEMENT      = "[" SD-ID *(SP SD-PARAM) "]"
SD-PARAM        = PARAM-NAME "=" %d34 PARAM-VALUE %d34
SD-ID           = SD-NAME
PARAM-NAME      = SD-NAME
...
SD-NAME         = 1*32PRINTUSASCII
; except '=', SP, ']', %d34 (")
...
SP              = %d32
PRINTUSASCII    = %d33-126
...
```
=> logmsg: sanitize sdata keys

lib/logmsg/logmsg.c
In eee3bb4bf61ad03785e97c86a18b208155f09790, a `g_sprintf()` call has been introduced, which is declared only in gprintf.h (because of the stdio dependency).
>Note that the functions g_printf(), g_fprintf(), g_sprintf(), g_snprintf(), g_vprintf(), g_vfprintf(), g_vsprintf() and g_vsnprintf() are declared in the header gprintf.h which is not included in glib.h (otherwise using glib.h would drag in stdio.h), so you'll have to explicitly include <glib/gprintf.h> in order to use the GLib printf() functions.
This PR should not be added to the NEWS file.
=> logmsg: fix compiler warning

lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c
The new `pkcs12-file()` TLS option can be used to specify a `PKCS #12` file container that can store 
a private key, a certificate and CA certs.
`pkcs12-file()` works together with the `ca-dir()` option, but this is optional since the p12 file may contain CA certificates as well.
If this option is used in the configuration file, the value of `key-file()` and `cert-file()` will be omitted.
Passphrase is currently not supported.
Example:
```sh
openssl pkcs12 -export -inkey serverkey.pem -in servercert.pem -certfile cacert.pem -out server.p12
```
```
source s_tls {
syslog(
transport(tls)
tls(
pkcs12-file("/path/to/server.p12")
ca-dir("/path/to/cadir") # optional
peer-verify(yes)
)
);
};
```
=> TLS: PKCS 12 support

contrib/valgrind/syslog-ng.supp, lib/afinter.c, lib/afinter.h, lib/apphook.c, lib/control/control-commands.c, lib/control/control-commands.h, lib/crypto.c, lib/messages.c, lib/reloc.c, lib/reloc.h, lib/stats/stats-control.c, lib/stats/stats-control.h, lib/stats/stats.c, lib/value-pairs/value-pairs.c, syslog-ng/main.c
This patchet intends to fix some entries in valgrind report. All of these issues are minors, i.e non of them accumulate over time. All of these changes intended to be cosmetic, explicitely calling deinits/frees, instead of just adding new exceptions to a valgrind suppress file.
Credits for @bkil-syslogng for https://github.com/balabit/syslog-ng/pull/975, which gave much inspiration for this pull request.
Only there are two commits in 975 that were not ported. I list them here for documentation reason.
-  g_process_set_argv_space. There were a lot of fight on these recently. The proposed change is still incomplete, see https://github.com/balabit/syslog-ng/pull/1528 for details.
- g_static_mutex_free. Syslog-ng mutexes are typically statically initialized. The glib documentation states that …
=> memleak hunting: cleanup based on valgrind report

.travis.yml, configure.ac, modules/python/Makefile.am, modules/python/compat/compat-python-v2.c, modules/python/compat/compat-python-v3.c, modules/python/compat/compat-python.c, modules/python/compat/compat-python.h, modules/python/python-debugger.c, modules/python/python-helpers.c, modules/python/python-logmsg.c, modules/python/python-module.h
Two changes in python3 c api compared to python2:
1) In python3, all strings are utf8, so PyBytes_Check will fail. This
patch will use PyUnicode_Check for python3 instead.
2) The function PyBytes_AsString is removed in python3. This patch
will use PyUnicode_AsUTF8 instead.
Fixes: https://github.com/balabit/syslog-ng/issues/1363
=> python-dest: string compatibility for python3

configure.ac
Introduced in: https://github.com/balabit/syslog-ng/pull/1632
A distribution might not label python pkg-config pc file as python2 or
python3. In such case auto-detection will not work.
In case of autodetection, we will look for pc files in this order:
python3, python2, python. This will work on even archlinux where only
python2 or python3 is used.
The decision between v2 and v3 will be done later by a call to
AC_CHECK_FUNCS instead.
=> python: regression in python version auto-detection

.travis.yml, configure.ac, modules/afamqp/afamqp.c
=> Clang compile error because of -Werror

lib/cfg-tree.c, lib/rewrite/rewrite-subst.c
There are two kind of memory leaks in syslog-ng related to cloning pipes. One of them is general: all clone invocations are affected. The other one is rewrite rule specific.
Please see the commit messages for detailed explanation of the issues and the patches.
These memory leaks can be reproduced if one defines a named filter/rewrite rule, and refer them twice in the configuration. For example:
```
@version: 3.11
filter f_warn  { level(warn, err, crit)  };
log {
filter(f_warn);
filter(f_warn);
};
```
These leaks are accumulated during reload.
As a workaround: configuration can be changed to use every reference only once.
Reported in: https://github.com/balabit/syslog-ng/issues/1317
=> Memory leak related to cloning pipes

modules/http/http.c
verbose() option:
- default value: no
Without this option syslog-ng can not log verbose logs of libcurl module which can be very useful sometimes.
Let see some syslog-ng console examples
* http connection with verbose(no):
```
[2017-06-11T15:34:02.049183] Syslog connection accepted; fd='15', client='AF_INET(127.0.0.1:57090)', local='AF_INET(127.0.0.1:10001)'
[2017-06-11T15:34:02.050122] Incoming log entry; line='<38>2017-06-11T15:34:02 localhost prg00000[1234]: seq: 0000000000, thread: 0000, runid: 1497188042, stamp: 2017-06-11T15:34:02 PADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADDPADD'
[2017-06-11T15:34:02.050427] Setting value; msg='0x7f773c014600', name='HOST_FROM', value='localhost' …
```
=> Http: Add verbose option to http() destination

modules/getent/getent-protocols.c
The `p_proto` returned by  `getprotobyname_r` does not require the `htons` call.
(See the man page for `getprotobyname_r`.)
=> [getent] protocol number look up by name returns incorrect number

modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/ElasticSearchDestination.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/ESClient.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/esnative/ESNativeClient.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/http/ESHttpClient.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/http/HttpBulkMessageProcessor.java, modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/http/HttpMessageProcessor.java
Fixes: #1509
Flush the message automatically when there are no more message in the queue.
Earlier it caused problem when there were less messages than flush_limit() and syslog-ng
does not flush them only at reload/restart.
Possible side effects: if the messages come slower syslog-ng will flush more often
instead of waiting flush_limit().
The classes inherited from ESNativeClient does not use this method
because the bulkprocessor here is responsible for the auto flush.
Signed-off-by: Zoltan Pallagi <pzolee@balabit.com>
=> elasticsearch.http: implemented onMessageQueueEmpty function

contrib/solaris-packaging/syslog-ng.method, contrib/solaris-packaging/syslog-ng@default
contrib/solaris-packaging/syslog-ng@default: modified some default values for parameters
* minor improvements to fix possible file collisions across instances
* VAR_DIR will now contain the instance name for non-default instances
if not defined otherwise
* persist, pid and ctl files will not reflect the instance names, but
their paths will
* changed VAR_DIR paths
Signed-off-by: Janos SZIGETVARI <jszigetvari@gmail.com>
=> modified VAR_DIR to include instance name

contrib/syslog-ng-debun
Fixed bugs in the area of file size parsing for the PKI CSV and hash generation for the manifest
Also added the outputs of top, netstat -lunp, and sar (CPU and disk)
=> Syslog-ng-debun improvements

modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java, modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsOptions.java, scl/hdfs/plugin.conf
New option: hdfs_append_enabled("true|false"), default: false
When this option is enabled, syslog-ng will append the file if it already exists.
In that case, syslog-ng does not extend the filename with a unique id as earlier.
!!!
Warning: always ensure that your hdfs server supports append (and it is enabled) before enable this option!
!!!
Note: if you have a very small hdfs cluster (number of nodes < replication factor, for example for testing purpose), you can receive
"Failed to replace a bad datanode on the existing pipeline due to no more good datanodes being available to try"
error message at flush. In that case either decrease the value of dfs.replication or
add dfs.client.block.write.replace-datanode-on-failure.policy key with "NEVER" value
in hdfs-site.xml and give it as resource …
=> HDFS destination: Added append support

modules/xml/tests/test_xml_parser.c, modules/xml/xml.c, modules/xml/xml.h
- strip-whitespace option is not copied during clone
- when exclude pattern is used and the pipe element is cloned, shutdown leads to double free
- memory leak when exclude patterns is used, and the provided patterns force a string reverse
Now unit tests run on a cloned version of the pipe element instead of the original.
=> xml-parser: bugfixes 

lib/compat/glib.c
Due to coding error, the backported g_list_copy_deep modified the
original list instead of the new list, causing a side effect, and
returns with a new list. This causes crash during free in xml parser.
=> xml-parser: eliminate side effect g_list_copy_deep

configure.ac
It is used for testing and preprocessing grammar rules.
=> configure: check for Python

lib/apphook.c, lib/apphook.h, lib/control/control-commands.c, lib/mainloop.c, modules/affile/affile-dest.c, modules/affile/affile-dest.h, modules/affile/affile-plugin.c, syslog-ng-ctl/syslog-ng-ctl.c
I'm not sure it is feasible to solve issue #1423 in a good way without any penalty in performance given if it is related to race between multiple threads (which I suspect is the problem). So I tackled this from another point of view by avoiding a reload the configuration all together as it is not needed from the problem scenario stated in the issue and adding a new signal handler to only trigger a re-opening of log files instead.
=> affile: Add possibility to only signal re-open of file handles

lib/cfg-grammar.y
**Please don't merge it.**
string_list: if we always insert into the first position into the list no reverse is needed in the end.
=> Grammar: string_list link in reverse order (eliminate reverse overhead)

contrib/syslog-ng-debun
Fixed a trivial minor bug that broke file collection for syslog-ng's var directory when its total size was greater than 1000 KB.
=> contrib/syslog-ng-debun: bug fix

lib/parse-number.c, lib/tests/test_parse_number.c, libtest/template_lib.c, libtest/template_lib.h, modules/basicfuncs/basic-funcs.c, modules/basicfuncs/cond-funcs.c, modules/basicfuncs/str-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c, modules/basicfuncs/tf-template.c
This branch adds a $(binary) template function, evolving the code originally found in PR #531 
The rationale of this function needs some explanation, as the configuration lexer enables us to encode binary characters in any string, by using C like backslash escapes, e.g. this should work:
template("\x00");
The issue with that is that the lexer->grammar interface does not support embedded NUL characters, thus anything past the NUL would be dropped when the configuration is loaded.
With this function the sample above would become:
template("$(binary 0x00)");
Which is properly parsed, and the embedded zero would only be processed by the destination, which might be supporting embedded NULs. All LogWriter based destinations (file, socket based stuff, program(), pipe, etc) do support that, so …
=> Binary template function

modules/affile/affile-dest.c
Both single_writer and writer_hash can be uninitialized as the opening of a file is deferred until there is some message to write.
Fixes: #1699
See comment on code from the pull request that introduced this feature for more information: https://github.com/balabit/syslog-ng/pull/1530#pullrequestreview-65297802
=> affile: Do not iterate writer_hash if uninitialized

modules/java/native/java_machine.c
The `jvm_options` splits the string via `-`, ` `(space) or `\t`, but the `-` could be part of a valid path.
Currently if there is a `-` in the jvm_options, it is going to be splits as a new option and passed to the JVM C, causing the crash.
Fixes #1696.
=> The jvm_options uses '-' as a separator, which is a valid in path

lib/logreader.c
logreader: remove unused LogReader fields (inode, size) 
They were introduced in 0a287bd61240503a970e6431d4ebfb65d42b469d, (backport most of the 3.0 PE features into OSE) without usage on the OSE side.
(Sorry for the spam, this PR is almost unavailing. I was just studying the LogReader class.)
=> Minor clean-up in LogReader

lib/compat/CMakeLists.txt, lib/compat/Makefile.am, lib/compat/getent-bb.h, lib/compat/getent.c, lib/compat/getent.h, modules/afstreams/afstreams.c, modules/getent/getent-group.c, modules/getent/tfgetent.c
There is a little API difference between the linux and solaris version of getent functions.
In Linux, they return errno, and data in an output parameter.
In solaris, they return the data, and set errno.
This patch provides wrapper around the solaris versions, so that we can use them as in linux: errno is returned, and data is written to the output parameter.
There was a minor compile error in sun_streams, it is fixed as well.
Fixes: https://github.com/balabit/syslog-ng/issues/1667 and https://github.com/balabit/syslog-ng/issues/1692
=> solaris: compile errors in getent and sun_streams

.astylerc, .travis.yml, modules/afamqp/afamqp-parser.c, modules/afamqp/afamqp.c
There are three improvement in the initial PR #1683 is blocked by #1657 from which two of them could be merged without issue.
This PR aims to contains only those changes:
1) Style check excludes the *amqp* module, but it should only exclude the *rabbitmq-c* submodule under it.
2) In Travis CI if the style-check fails, in the console output it is going to print, why.
=> Style check for amqp

modules/confgen/confgen-plugin.c, scl/Makefile.am, scl/loadbalancer/gen-loadbalancer.sh, scl/loadbalancer/plugin.conf
It implements a simple round-robin load balancing between multiple destination.
Balancing is based on MSEC hashing where destinations share the same configuration
except the destination address.
The main purpose to make load balance configuration simple.
It can be used as a simple network destination and all network parameters are
recognized, the destination servers must be configured as a space separated list
of host using the "targets" option:
destination mydest {
load-balancer(
targets(server1 server2 server2) # mandatory option
transport(udp)
port(3456)
)
};
NOTE: as failover-server is not supported in this version it is left out. Otherwise
nodes are used for fail-over servers to maintain availability.
The idea and original configuration comes from Ferenc Sipos.
Big kudos for the …
=> Simple rr-network load balancer

lib/cfg-lexer.c, lib/cfg.c, lib/cfg.h, lib/logmatcher.c, lib/logreader.c, lib/template/macros.c, lib/template/templates.c, lib/template/tests/test_template.c, lib/versioning.h, modules/affile/affile-source.c
This branch fixes #1423 as well as it drops the compatibility to syslog-ng versions below 3.0.
The bug itself manifests because of the compatibility support and fixing it is pretty complicated, as it would require propagating the GlobalConfig instance to a place where it isn't present.
Anyway, I felt it was time to drop support for syslog-ng config versions below 3.0, as 3.0 is roughly 9 years old anyway (released on 24th December 2008 as a christmas present :)
=> Fix reload race in msg macro + drop compatbility with syslog-ng < 3.0

lib/cfg-lexer.c
Free config file memory after inclusion
Most likely relates to #1317
Signed-off-by: Sam Stephenson <sam.stephenson@alliedtelesis.co.nz>
=> cfg: Free filename after config file inclusion.

modules/affile/logproto-file-writer.c
Fix a crash that occurs following a write failure when the file writer
buffer becomes full and a config reload is triggered.
If a write failure occurs in log_proto_file_writer_post as the buffer
becomes full, a subsequent call will be made where msg and
self->buffer[self->buff_count].iov_base point to the same memory.
The first call to log_proto_file_writer_flush will write the message
and free the buffer. The following call will raise an abort signal
when it attempts to free the buffer a second time.
If the message has been stored in self->buffer, it should be marked
as consumed irrespective of the result of log_proto_file_writer_flush.
This may relate to #1425
Signed-off-by: Sam Stephenson <sam.stephenson@alliedtelesis.co.nz>
=> affile: Mark messages as consumed in a write failure.

lib/logpipe.h, lib/logproto/logproto-server.h, lib/logproto/logproto-text-server.c, lib/logreader.c, lib/logreader.h
The "preemption" logic with NC_FILE_SKIP was an implementation detail of the old wildcard file source.
This is dead code now.
This PR removes code from a "hot path", but I guess this is not a significant performance improvement. :)
=>  logreader/logproto: remove preemption

modules/java/proxies/java-logmsg-proxy.c
=> This fixes access to indirect values within Java destination

scl/osquery/plugin.conf
Send log messages to osquery's syslog table.
The interface between osquery and syslog-ng is a named pipe (default path is
set in the SCL file, custom value can be set with the `pipe()` parameter.)
* Run osqueryi:
`osqueryi --enable_syslog --disable-events=false`
* if you want to store the db on disk:
`osqueryi --enable_syslog --disable-events=false --database_path=/tmp/osquery.db`
You can check the messages by typing `select * from syslog;`
* custom named pipe:
```
osqueryi --enable_syslog
--disable-events=false
--database_path=/tmp/osquery.db
--syslog_pipe_path=/tmp/osq.pipe
```
* example config:
```
@version: 3.12
source s_net {
network(port(5514));
};
destination d_osquery {
#osquery(pipe("/tmp/osq.pipe"));
#osquery(file("/var/log/osquery_inserts.log" …
```
=> osquery: add osquery destination as an SCL plugin

lib/mainloop-worker.c, lib/mainloop.c, lib/mainloop.h
During shutdown, mainloop did not wait worker threads to stop: app_shutdown and app_thread_stop was racing. This could lead to a use after free issue in the code: a dns_cache object could be returned to an already unallocated pool: unused_dns_caches.
Two possible resolutions to the problem:
- Reference counting for unused_dns_caches.
- Blocking mainloop until all workers exit.
This patchset contains both versions. I would like to open up a discussion if we need either one or both. 
Me seems reference counting is simpler in terms of code complexity, and has less possible side effects comparing to the version of blocking mainloop. Though the latter one could eliminate the currently unknown or possible future race conditions of these functions as well.
I could only manually test the blocking …
=> dns-cache: during shutdown: possible use after free

configure.ac, lib/Makefile.am, modules/afamqp/Makefile.am, modules/afmongodb/Makefile.am
The following dependencies (as git submodules) were optional to include into the dist compressed files:
* ivykis
* librabbitmq-c
* mongoc
This should be only in case of internal option, and not in case of system, as the system shall provide those files.
=> Fix distdir target in case of system option

modules/afsocket/afsocket-dest.c
Asserting that self->writer is null seems to be incorrect.
If the config being initialized is new, self->writer is guaranteed
to be null, however if we are re-initializing an old config after initializing
a new configuration failed, an existing writer may be present if keep-alive
is off (old_config self->writer is set to null if the connection is saved)
Fixes #1722
Signed-off-by: Sam Stephenson <sam.stephenson@alliedtelesis.co.nz>
=> afsocket: Remove invalid assertion from afsocket_dd_restore_writer.

packaging/debian/syslog-ng-core.install, packaging/debian/syslog-ng-mod-json.install
Related scls
* windowseventlog
* loadbalancer
* osquery
Signed-off-by: Andras Mitzki <mitzkia@gmail.com>
=> PackagingSclFiles: Add missing scl dirs for debian packaging

modules/afamqp/afamqp-grammar.ym, modules/afamqp/afamqp-parser.c, modules/http/http-grammar.ym, modules/http/http-parser.c, modules/riemann/riemann-grammar.ym, modules/riemann/riemann-parser.c
Three destination drivers: amqp(), http(), riemann() allows to use tls options inside the driver configuration. 
This patch-set provides to use these tls options also in a general tls() block as it is used in network type drivers.
The patch-set did not brake the original usage for actual drivers.
Example new type of configuration for tls options in riemann destination:
```
destination d_riemann {
riemann(
server("127.0.0.1") 
port(5672) 
tls(
ca_file("ca") 
key_file("key")
)
);
};
```
=> Provide tls block for tls options in amqp(), http(), riemann() dest. drivers

modules/affile/stdin.c
In case stdin() driver is used: syslog-ng closes the zero file
descriptor (stdin) before restarting. After restart this same zero
file descriptor is intended to be added back to epoll in
ivykis. Being already closed: epoll_ctl returns with error:
errno=EBADF.  Hence syslog-ng cannot initialize after reload, and
when she tries to fallback, initialization will fail again with
the same reason. Hence the crash.
This patch duplicates the file descriptor of stdin, and the dupped
version will be watched, instead of zero.
Fixes: https://github.com/balabit/syslog-ng/issues/1736
=> stdin: crash with syslog-ng reload

configure.ac, modules/riemann/riemann-grammar.ym, modules/riemann/riemann-parser.c, modules/riemann/riemann.c, modules/riemann/riemann.h
This patch introduces support for event time as microseconds in Riemann destination. 
The event_time() option in Riemann destination configuration
shall take an extra optional parameter specifying the time format
is in seconds (unixtime) or microseconds.
For example:
```
event_time("$(* $UNIXTIME 1000000)" microseconds)
event_time("12345678" microseconds)
event_time("12345678" seconds)
event_time("12345678")
```
In case the parameter is omitted, syslog-ng defaults to the seconds version. In case event_time is omitted, syslog-ng will default to the seconds version with $UNIXTIME, the same as the original behaviour.
Dependencies:
- riemann-c-client: 1.10.0 or newer
- Riemann: 2.13 or newer
With older riemann-c-client, the microseconds option will not be
available.
Older Riemann cannot …
=> riemann: microseconds support

.travis.yml, modules/snmptrapd-parser/snmptrapd-header-parser.c, modules/snmptrapd-parser/tests/test_snmptrapd_parser.c
This PR fixes a one hour difference when a incoming timestamp is in DST and a local time is in winter time, and the local timezone is not CEST.
The issue can be reproduced with snmptrapd-source.
Signed-off-by: Gabor Nagy <gabor.nagy@balabit.com>
=> SnmpTrapdParser: Fix tm_hour differences in outgoing messages came from snmptrapd() source

lib/parser/parser-expr.c, lib/parser/parser-expr.h, modules/dbparser/dbparser.c, modules/dbparser/groupingby.c, modules/dbparser/stateful-parser.h, modules/kvformat/kv-parser.c, modules/native/parser.c, modules/python/python-logparser.c
This patch adds log_parser_init_method() to the init() call chain,
where it was missing. This fixes #1738, as well as any potential
missing initialization problem in the future.
=> groupingby: add missing "discarded" counter

lib/cfg-lex.l, lib/cfg-lexer.c
Fix the double free of level->yy_buff and double close of
level->file.include_file that can occur during a config reload if a config
file is deleted.
This was observed on a system with frequent dynamic config change. The issue
occurs when a config file is deleted between the glob expansion/directory
scanning in cfg_lexer_include_file_*() functions and files being opened in
cfg_lexer_start_next_include.
Fixes #1720
Signed-off-by: Sam Stephenson <sam.stephenson@alliedtelesis.co.nz>
=> cfg: Fix double free/double close crashes

modules/diskq/diskq-options.c
Using the word "omitted" may be confusing, as it sounds like something should have been there, but was not taken into account. Let's use "ignored" instead, as for something that *should not* be there in the first place (and therefore was ignored).
Also be more verbose and suggest the other configuration parameter.
Fixes #1733.
=> Emit less confusing warnings for diskq

Makefile.am, configure.ac
Parametrized tests in criterion crashes with aslr enabled.
https://github.com/Snaipe/Criterion/issues/208
This can be a problem, because for example in ubuntu 17.04 gcc
produces position  independent executable code by default. With
randomize_va_space > 0, it leads criterion tests to crash.
This patch will compile the tests into a non position independent
binary, avoiding the crash.
Non test related binaries are untouched.
Test:
$ file modules/xml/tests/test_xml_parser
modules/xml/tests/test_xml_parser: ELF 64-bit LSB executable [...]
However for syslog-ng binary:
$ file ../root/sbin/syslog-ng
../root/sbin/syslog-ng: ELF 64-bit LSB shared object
=> criterion: disabling aslr for testcases

lib/cfg-parser.c, lib/versioning.h
The error message in case of configuration issue contain a burned in product name and link to mailing-list.
Also the documentation link should point to **syslog-ng-ose** instead of **syslog-ng**.
> syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng
> mailing list: https://lists.balabit.hu/mailman/listinfo/syslog-ng
This modification makes it easily replaceable via redefining macro that has the information.
The new message would be:
> syslog-ng documentation: https://www.balabit.com/support/documentation?product=syslog-ng-ose
> contact: https://lists.balabit.hu/mailman/listinfo/syslog-ng
=> Configuration error footnote parameterized

lib/cfg-grammar.y, lib/cfg-parser.c, lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, lib/stats/stats-query.c, lib/stats/stats-registry.c, lib/stats/stats-registry.h, lib/stats/stats.c, lib/stats/stats.h, lib/stats/tests/Makefile.am, lib/stats/tests/test_dynamic_ctr_reg.c
*   Users can limit the number of registered dynamic counters via the `stats_max_dynamics` global option.
This is not a limit for the number of counters but for the number of _clusters_ which means that users
can limit the number of different dynamic value occurrences (as each
cluster has a pre-allocated array of counters).
*   Note that after reload, when users set a lower limit,
they have to wait for stat-freq-timer being expired to remove the
previously allocated dynamic clusters.
*   Dynamic values are
* source host (from stats level 2)
* sender host (host from) (from stats level 3)
* program (from stats level 3)
* By default this change is backward compatible: if someone not uses this feature, number of dynamic counters won't be limited.
* It is  possible to disable dynamic counters …
=> Limit dynamic counters

modules/afmongodb/afmongodb.c
* rename status to reply
There is a small leak in afmongodb.c: at:
Reproduction:
* start syslog-ng behind a valgrind with the following config below:
```
@version: 3.12
source s_file {file("/dev/stdin");};
destination d_mongodb {mongodb();};
log {source(s_file); destination(d_mongodb);};
```
* valgrind start:
```
valgrind --run-libc-freeres=no --leak-check=full --tool=memcheck sbin/syslog-ng -Fedv -f syslog_ng_mongodb.conf
```
* send some SIGHUP to syslog-ng process
Valgrind:
* Relevant part of valgrind log:
```
==12168== 768 bytes in 6 blocks are definitely lost in loss record 77 of 89
==12168==    at 0x4C2FB0F: malloc (in /usr/lib/valgrind/vgpreload_memcheck-amd64-linux.so)
==12168==    by 0x75D7BFD: bson_malloc (bson-memory.c:67)
==12168==    by 0x75CAE2C: bson_new (bson.c:1863) …
```
=> Mongodb: original status variable was not free, cause memory leak

modules/getent/getent-group.c, modules/getent/tfgetent.c
Fixes: https://github.com/balabit/syslog-ng/issues/1757
=> getent: fix group - name to gid calculation

modules/redis/redis.c
- without this syslog-ng gets segfault
syslog-ng crashes when we start redis destination driver without defining command() option
Reproduction:
* start syslog-ng with the config below (command() option is commented out)
```
@version: 3.12
source s_file {file("/dev/stdin");};
destination d_redis {redis( 
);
};
log {source(s_file); destination(d_redis);};
```
Crash:
```
[2017-11-17T17:53:57.998296] Initializing Redis destination; driver='d_redis#0', host='127.0.0.1', port='6379'
[New Thread 0x7ffff7fd4700 (LWP 29778)]
[2017-11-17T17:53:57.998529] Worker thread started; driver='d_redis#0'
[2017-11-17T17:53:57.998547] Worker thread started; driver='d_redis#0'
[2017-11-17T17:53:57.998643] Running application hooks; hook='1'
[2017-11-17T17:53:57.998651] Running application hooks; hook='3' …
```
=> Redis: Do not init redis driver without command() option

modules/confgen/confgen-plugin.c
To make confgen related troubleshooting easier, add a new debug message
that includes the exact output the program generated.
=> confgen: send a debug message about the text the program generates

Makefile.am, autogen.sh, dbld/Makefile.am, dbld/deb, dbld/generate-debian-directory, dbld/generate-rpm-specfile, dbld/images/centos7/dev-dependencies.txt, dbld/images/zesty/Dockerfile, dbld/images/zesty/dev-dependencies.txt, dbld/pkg-tarball, dbld/rpm, dbld/rules, packaging/debian/changelog, packaging/debian/rules, packaging/debian/syslog-ng-core.install, packaging/rhel/syslog-ng.conf, packaging/rhel/syslog-ng.logrotate, packaging/rhel/syslog-ng.service, packaging/rhel/syslog-ng.spec, tests/copyright/policy
This branch finally integrates the debian packaging in packaging/ to the docker based build flow, which
basically makes it possible to do snapshots and releases using docker, right from the source, in a controlled environment.
It makes it easy for anyone to compile a binary snapshot without a need to struggle with autoconf and friends.
=> Docker based build updates

lib/scanner/kv-scanner/kv-scanner.c, lib/scanner/kv-scanner/kv-scanner.h, lib/scanner/kv-scanner/tests/test_kv_scanner.c, modules/kvformat/kv-parser.c, modules/kvformat/kv-parser.h, modules/kvformat/linux-audit-parser.c, modules/kvformat/tests/test_linux_audit_scanner.c, modules/snmptrapd-parser/tests/test_varbindlist_scanner.c, modules/snmptrapd-parser/varbindlist-scanner.c, modules/snmptrapd-parser/varbindlist-scanner.h
=> Kv scanner scratch buffers

lib/cfg-args.c, lib/cfg-args.h, lib/cfg-block.c, lib/cfg-parser.c, lib/cfg-parser.h, modules/appmodel/app-parser-generator.c, modules/appmodel/tests/test_app_parser_generator.c, modules/system-source/system-source.c, scl/default-network-drivers/plugin.conf
This patch implements auto-parse(yes/no) option into
- the app-paser()
- and through the use of __VARARGS__ system() and default-network-drivers()
this was requested by @czanik
=> App parser kill switch

dbld/tarball
Fixes #1793
@czanik: Could you try it? ( `dbld/rules tarball` ) 
list of files in `doc/man`:
```
dqtool.1
dqtool.1.xml
loggen.1
loggen.1.xml
pdbtool.1
pdbtool.1.xml
syslog-ng.8
syslog-ng.8.xml
syslog-ng.conf.5
syslog-ng.conf.5.xml
syslog-ng-ctl.1
syslog-ng-ctl.1.xml
syslog-ng-debun.1
syslog-ng-debun.1.xml
```
=> dbld: add manpages to tarball

packaging/debian/README.source, packaging/debian/control, packaging/debian/rules
As the Incubator is being phased out, and there are no other third party modules of note, the virtual package was becoming not only unnecessary, but a burden too.
This drops it completely, re-introducing a tight dependency between syslog-ng-core and modules.
=> debian: Drop the syslog-ng-abi-* virtual package

README.md
./autogen.sh needs to be run before trying to execute the configure
script. I mention it in this patch.
Signed-off-by: Andy Alt
<andy400-dev@yahoo.com>
=> README.md:compile from source -> add missing step [skip-ci]

lib/logmatcher.c, lib/rewrite/tests/test_rewrite.c
In case of `LogMatcherPcreRe`, the `matches` array may contain -1 values.
https://www.pcre.org/original/doc/html/pcreapi.html
>  It is possible for capturing subpattern number n+1 to match some part of the subject when subpattern n has not been used at all. For example, if the string "abc" is matched against the pattern (a|(z))(bc) the return from the function is 4, and subpatterns 1 and 3 are matched, but 2 is not. When this happens, both values in the offset pairs corresponding to unused subpatterns are set to -1.
> Offset values that correspond to unused subpatterns at the end of the expression are also set to -1. For example, if the string "abc" is matched against the pattern (abc)(x(yz)?)? subpatterns 2 and 3 are not matched. The return from the function is 2, because the highest …
=> Fix message corruption caused by a bug in the subst() rewrite rule

lib/filter/filter-call.c
if `filter_call_init` being called twice or more, `filter_expr_ref(self->filter_expr)` will trigger each time, but `filter_call_free` -> `filter_expr_unref(self->filter_expr)` will only trigger once, so `self->filter_expr` will leak.
This commit prevent furthermore initialization when `self->filter_expr` has value.
Signed-off-by: Shen-Ta Hsieh <ibmibmibm.tw@gmail.com>
=> filter: fix memory leak with multiple call on FilterCall's init

lib/afinter.c
writing next_mark_target.tv_sec is not guaranteed as an atomic operation.
=> afinter: avoid data race on next_mark_target

syslog-ng.pc.in
This remaining reference to the evenetlog package prevents compiling the syslog-ng-incubator.
=> Remove the last leftover of the eventlog package

modules/affile/directory-monitor.c
In case the PATH_MAX is not defined, there is
a redundant opening curly brackets. And also
there is a missing underline once in the name
of the path_max variable. This patch closes #1827
=> Fixes two typos in the get_path_max code

modules/python/pylib/syslogng/debuggercli/tests/test_completer.py, modules/python/pylib/syslogng/debuggercli/tests/test_completerlang.py, modules/python/pylib/syslogng/debuggercli/tests/test_getoptlexer.py, modules/python/pylib/syslogng/debuggercli/tests/test_lexer.py, modules/python/pylib/syslogng/debuggercli/tests/test_macrocompleter.py, modules/python/pylib/syslogng/debuggercli/tests/test_tablexer.py
See https://docs.python.org/2/library/unittest.html#deprecated-aliases
=> Use assertEqual because the plural form is deprecated

modules/python/pylib/syslogng/debuggercli/__init__.py
But both python2 and python3 has the function input.
The difference between the two implementation that
in python2 input can return with other type than
string.
=> python3 has no function raw_input

lib/cfg-grammar.y, modules/diskq/diskq-grammar.ym
Every time `nonnegative_integer` or `positive_integer` is used in the grammar, the numbers end up being stored on 32 bits (except for `disk-buf-size`, which is 64-bit wide). Not properly bounds-checking these numbers can result in us ending up with a negative value.
Seeing as there is only one exception, this patch changes `nonnegative_integer` and `positive_integer` to do proper bounds checking too, and error out if the value does not fit. For `disk-buf-size`, we introduce `nonnegative_integer64`, local to that part of the grammar.
Fixes #1820.
=> grammar: Make sure that nonnegative and positive integers fit into 32 bits

CMakeLists.txt, scripts/style-checker.sh
A new option for the `style-check` script to exclude directories, which could be used for `cmake` or in git commit hook to exclude the build directory.
The `autotools` provides the `$(top_buildir)` that contains `.` that `astyle` cannot interpret:
> Directory  ../*.c
Exclude  build/lib/jsonc
Exclude  build/lib/ivykis
Exclude  build/modules/afamqp/rabbitmq-c
Exclude  build/modules/afmongodb/mongo-c-driver
Exclude  lib/jsonc
Exclude  lib/ivykis
Exclude  modules/afamqp/rabbitmq-c
Exclude  modules/afmongodb/mongo-c-driver
Exclude (unmatched)  .
=> Style check exclude dir

modules/python/compat/compat-python-v2.c, modules/python/compat/compat-python-v3.c, modules/python/compat/compat-python.h, modules/python/python-dest.c, modules/python/python-dest.h, modules/python/python-grammar.ym, modules/python/python-logmsg.c, modules/python/python-logparser.c, modules/python/python-logparser.h, modules/python/python-parser.c, modules/python/python-plugin.c, modules/python/tests/test_python_logmsg.c
This patch contains the code change identified in https://github.com/balabit/syslog-ng/issues/1361.
The goal of the patchset is to be able to write parsers/destinations in hy.
Example:
```
syslog-ng.conf
@version: 3.13
log {
source { stdin(flags(no-parse)); };
destination { python( imports("hy") class("mymodule.MyPyDest")); };
};
```
```
mymodule.hy:
(defclass MyPyDest [object]
(defn init [self options] True)
(defn send [self message] (print (get message "MESSAGE")) True)
)
```
=> python: hy module related fixes

lib/mainloop-worker.c
1. Prevent undefined behavior - [Shift-pass-bitwidth](https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html)
2. Holding lock on condition variable signaling. See [glibc document](https://developer.gnome.org/glib/stable/glib-Threads.html#g-cond-signal).
=> Mainloop refactor

contrib/README.syslog-ng-debun, contrib/syslog-ng-debun
Details:
-  cosmetic changes to remove backtick-style code invokations in favor of dollarsign+parentheses
-  gather the persist file even when vardir is too big
-  gather two sets of syslog-ng stats, with Unix timestamps to allow EPS counting based on the diffs
=> Syslog ng debun improvements

configure.ac, lib/filter/tests/Makefile.am, libtest/Makefile.am, modules/python/Makefile.am
This patchset fixes
- python unit test should not be compiled if python is disabled
- if ipv6 support is disabled, test_filter_netmask6 should not be compiled
- There was a whitespace in libtest makefile after backslash, causing autotools warning
- The compile of http module was unaffected by --enable/disable-all-modules, even though the default detection state was auto
=> autotools: small fixes related to --disable-all-modules

modules/afprog/afprog.c
The problem this fixes is that when the destination tries to use a program that does not exist, we end up trying to restart it endlessly, forever, without logging anything about it on a reasonable log level. This spams the logs, and is very unhelpful anyway.
Instead, this patch changes the restart logic, so it is not always immediate. On a write error, we'll defer restart to the child manager, which will have access to the exit status. We check this exit status, and if it is 127, with no core dump, and the child did not die due to a signal, we can be pretty certain that this is a command-not-found error. As such, in this case, we delay the restart, and use a `time-reopen`-long delay, after logging the fact. In every other case, the restart is silent below verbose level, and happens …
=> afprog: Smarter child restart in the destination

lib/compat/tests/CMakeLists.txt, lib/compat/tests/test_strtok_r.c, lib/value-pairs/tests/CMakeLists.txt, lib/value-pairs/tests/test_value_pairs.c, lib/value-pairs/tests/test_value_pairs_walk.c, modules/xml/tests/CMakeLists.txt, modules/xml/tests/test_xml_parser.c
* Converts the strtok and value_pairs unit test from libtest to criterion.
* Remove not required include from xml parser test.
=> strtok and value_pairs test to criterion

lib/mainloop.c, lib/mainloop.h
This resolves the following build error on OSX 10.13:
```
:info:build   CCLD     lib/libsyslog-ng.la
:info:build clang: warning: argument unused during compilation: '-pthread'
:info:build clang: warning: argument unused during compilation: '-pthread'
:info:build ld: warning: option -noall_load is obsolete and being ignored
:info:build ld: warning: option -noall_load is obsolete and being ignored
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-apphook.o
:info:build duplicate symbol _main_loop_workers_running in:
:info:build     lib/.libs/lib_libsyslog_ng_la-afinter.o
:info:build     lib/.libs/lib_libsyslog_ng_la-cfg.o
:info:build duplicate symbol _main_loop_workers_running in: …
```
=> Properly declare main_loop_workers_running extern

CMakeLists.txt, Makefile.am, lib/logmsg/logmsg-serialize.c, lib/logmsg/tests/test_logmsg_serialize.c, lib/rewrite/rewrite-expr-grammar.ym, lib/stats/tests/test_stats_query.c, lib/value-pairs/tests/test_value_pairs.c, modules/basicfuncs/str-funcs.c, tests/valgrind/unit-test-leak.supp
This pull request is the continuation of https://github.com/balabit/syslog-ng/pull/1080. Thank you @bkil-syslogng for the investigation and putting together the original pull request.
I moved most of the commits from the original pull request here. One notable exception is the travis part. Unfortunately the valgrind execution of the unit test set is too long to execute in travis.
Besides autotools, cmake support is added as well.
Usage:
- autotools
- configure with --enable-valgrind option
- make check-valgrind-tool #optionally add VALGRIND_TOOL=memcheck
- cmake
After the usual compile: one can execute
- ctest -T memcheck
=> valgrind support for unit tests

modules/diskq/diskq-options.c, modules/diskq/diskq.c
When the `disk-buffer` directory is changed, but the destination already has a disk buffer file, syslog-ng continues to use the old path without any warning.
This modification aims to notify the user about the fact that disk queue is not changed.
Solves first part of the #1851.
=> Disk queue directory change in configuration

modules/diskq/qdisk.c
There is a hard-coded limitation in disk-buffer: the length of a record can not be more than 10 mebibyte.
A record consists of multiple fields serialized by `log_msg_serialize()`, so it is just a serialized `LogMessage` object.
The limit is used as a heuristic to detect an incorrect record and to prevent extreme memory usage in case of a corrupt message. Since a record includes structured data (the `NVTable`) and not just a simple serialized message, there is no way to derive an appropriate dynamic limit from the value of the `log-msg-size()` option.
The best would be to remove this limitation, but in that case, a few "consistency guarantees" and/or per-record checksum would be required.
=> Refactor and increase the maximum record length of disk-buffer()

lib/tests/test_scratch_buffers.c
If scratch_buffers_explicit_gc() is not called at all, a warning would be
emitted by the scratchbuffers module. However the messages module is
not initialized in the unit tests, hence all unit test crashes.
This patch calls garbage collection explicitely during teardown,
avoiding the crash. The alternative would have been to call msg_init(TRUE); during startup, though that would couple the scratchbuffers unit test with messages module, that I wanted to avoid.
Criterion does not signal error, if crash happens during teardown, that's why this crash could go undetected:
```
$ ./lib/tests/test_scratch_buffers
[----] Warning! The test `scratch_buffers::reclaim_marked_allocs` crashed during its setup or teardown.
[----] Warning! The test `scratch_buffers::alloc_returns_a_gstring_instance` …
```
=> scratchbuffers: fixing unit test crash

lib/host-id.c, lib/host-id.h, lib/logproto/logproto-buffered-server.c, lib/mainloop.c, lib/persist-state.c, lib/persist-state.h, lib/run-id.c, lib/run-id.h, modules/systemd-journal/journal-reader.c
Continuing https://github.com/balabit/syslog-ng/pull/717 in a new PR due that I do not have write access to the original PR. Credits for @juhaszviktor for the investigation and putting together the original pr!
Fixes: #716 
As I see the only thing left to do was to inverse the dependency between persist_state and mainloop. This is fixed here.
However, I ran into another problem while testing: 
Test: created a small tmpfs mountpoint for the persist state. Setting wildcard-file source and creating a lot of files with very long names, waiting for crash.
It turned out syslog-ng crashed for another reason:
```
ERROR:../syslog-ng/lib/persist-state.c:295:_alloc_value: assertion failed: (_check_free_space(self, size))
[1]    22773 abort (core dumped)  ./syslog-ng -Fe -R tmpfs/persist.file
```
The …
=> Crash with SIGBUS when persist_file cannot grow

lib/timeutils.c, lib/timeutils.h, modules/diskq/qdisk.c
In the past qdisk_save_queue only wrote the serialized data to the diskq when all messages have been popped from the queue and serialized.
During serialization each serialized message is appended to the same string buffer which could lead to huge memory usage (proportional to the log-fifo-size).
With this patch we define an internal memory limit of the string buffer.
When the limit is reached, we write the serialized messages to the disk-buffer and truncate the buffer.
=> Disk-buffer save queue in qdisk write chunks instead whole buffer

lib/scanner/kv-scanner/kv-scanner.c, lib/scanner/kv-scanner/kv-scanner.h, lib/scanner/kv-scanner/tests/test_kv_scanner.c, modules/kvformat/kv-parser.c, modules/kvformat/kv-parser.h, modules/kvformat/tests/test_linux_audit_scanner.c
In rare conditions KVParser may crash due to concurrent access to the "formatted_key" field.
Solution: Moved formatted_key from KVParser into a _process local variable.
Also splitted the _get_formatted_key function along the "if prefix" logic, because it can be decided in config time. (Function called for each key in _process.)
Question:
- Is it needed to modify the key_formatter function anywhere else than kv_parser_set_prefix?
=> Fixing KVParser rare crash in race condition

lib/stats/stats-cluster.c, lib/stats/stats-cluster.h
The `module_names` must match the list of `SCS_` items defined in the header.
Should the `static_assert` defined in compat layer instead of not doing the check if not exists ?
=> Statistics static assert for module_names

modules/python/pylib/syslogng/debuggercli/commandlinelexer.py, modules/python/pylib/syslogng/debuggercli/completerlang.py, modules/python/pylib/syslogng/debuggercli/templatelexer.py
This pylint issue alerts if the return statements
are inconsistent. It also alerts when some return
statement return with value, but at the function end
the return statement is missing.
Signed-off-by: SZALAY Attila <sasa@ubainba.hu>
=> Fix python issue R1710

lib/merge-grammar.py
In case missing/misconfigured locale settings, python3's open() and
fileinput() method fails to detect encoding: see
https://github.com/balabit/syslog-ng/issues/1831#issuecomment-362014420
for details. As a result, syslog-ng cannot be compiled on some systems.
This patch specifies the encoding type to avoid misdetection.
Fixes: #1831
=> merge-grammar: fixing utf8 detection for python3

modules/affile/affile-dest.c
The race is in the file destination between our queueing mechanism (`affile_dd_queue()`) and `time-reap()` (`affile_dd_reap_writer()`).
Basically, `time-reap()` could deinitialize the writer while the queue (and the writer) was being used.
An example schedule:
1. In the main thread, reap is called (timer); the queue seems to be empty, so we "start reaping".
2. Context switch
3. In a worker thread, a new message arrives; the `next` writer is selected with the help of a mutex:
https://github.com/balabit/syslog-ng/blob/e07700c463fe905b66e1ffa95a6fb378fcdeae1e/modules/affile/affile-dest.c#L716-L730
4. The mutex is unlocked.
5. Context switch
6. The writer (and the queue) is deinitialized without any locks. `log_pipe_deinit` is the problem here, `log_pipe_unref` is protected (see below): …
=> File destination (time-reap) crash under immense load

cmake/add_tests.cmake, lib/value-pairs/tests/Makefile.am, modules/add-contextual-data/tests/test_context_info_db.c, modules/csvparser/tests/test_csvparser_perf.c, tests/unit/Makefile.am
The root cause is the same as in: #1872 
As garbage collection is not explicitely called, unit test tries to write an internal message (warning) about possible leak. Though the internal messaging is not initialized, hence there is a crash.
For now I created the same fix as in #1872, calling garbage collection explicitely. Though I am starting to feel this is not the correct way to handle these issues.
Another problem is with test_context_info_db testcase is that scratchbuffers is not used at all by the test code, still the test code needs to deal with the lifecycle of scratchbuffers. It is unfortunate that the test code needs to know the internal mechanics of memory management of the tested module.
I am not sure about the alternatives though.
We can cut the dependency between …
=> scratchbuffers: crash in test_context_info_db: missing explicit_gc()

lib/cfg-grammar.y, lib/cfg-lexer.c, lib/cfg-parser.c, lib/cfg.c, lib/cfg.h, modules/java/CMakeLists.txt, modules/java/Makefile.am, modules/java/native/java-config.c, modules/java/native/java-config.h, modules/java/native/java-destination.c, modules/java/native/java-grammar.ym, modules/java/native/java-parser.c, modules/java/native/java-plugin.c
This extends the `ModuleConfig` with automatic module load. A module (like `java`) is able to declare a module specific global option(s).
=> globalconfig: plugin support for global options

CMakeLists.txt, lib/CMakeLists.txt, lib/Makefile.am, lib/apphook.c, lib/control/control-commands.c, lib/control/tests/Makefile.am, lib/secret-storage/CMakeLists.txt, lib/secret-storage/Makefile.am, lib/secret-storage/nondumpable-allocator.c, lib/secret-storage/nondumpable-allocator.h, lib/secret-storage/secret-storage.c, lib/secret-storage/secret-storage.h, lib/secret-storage/tests/CMakeLists.txt, lib/secret-storage/tests/Makefile.am, lib/secret-storage/tests/test_nondumpable_allocator.c, lib/secret-storage/tests/test_secret_storage.c, lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-source.c, modules/afsocket/transport-mapper-inet.c, modules/afsocket/transport-mapper-inet.h, modules/afsocket/transport-mapper.h, syslog-ng-ctl/syslog-ng-ctl.c, tests/copyright/policy
The solution has three key parts
* need to store the secret keys somewhere, possible in a non-dumpable memory area (credential store)
* inject secret into syslog-ng with syslog-ng-ctl (syslog-ng-ctl)
* afsocket:
* network source
* make it possible to disable client connections until a valid password is not provided by the user, and open connections when the password is available
* network destination
* try to reconnect to destination until a valid password is not available
In case of TCP network source, we call a `TransportMapper` init as part of the main init. This `TransportMapper::init` is responsible for setting up the `TLSContext`.
In the original implementation, when someone uses a password protected SSL key, OpenSSL will ask for the password (from stdin as we did not set the …
=> Password protected ssl keys

lib/secret-storage/tests/test_secret_storage.c, packaging/debian/syslog-ng-core.install
- Unit test needed to be branched based on executor user id. Please see commit message for details.
- Add missing libsecret-storage.so to deb packaging.
@lbudai this one was tricky because we used lib_LTLIBRARIES instead of module_LTLIBRARIES, meaning the generated so file will be something like libsecret-storage.so.0.0.0 instead of the usual libsecret-storage.so, thats why libsecret-storage.so.* needed to be used in the install file. Probably the same hack will be necessary in obs. Thanks for @algernon helping me in the fix.
=> Fixes for 3.14 release

modules/diskq/logqueue-disk.c, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_diskq.c
If a pop operation fails during reading from the disk-queue file the restart_corrupted method is called.
It has to close the current disk-queue file and rename it to "<filename>.corrupted" then it has to start a new file from scratch.
The function reuses the existing QDisk object after a deinit call, although it forgets to initialize the object properly before use and that causes a crash.
Questions:
* Who creates the DiskQueueOptions object and where is it passed to the QDisk object?
* Is it okay to get a reference of the `options` member?
Probably fixes crash in #1770 (but not the corruption of the disk-queue).
=> Diskq: fix restart disk-queue

modules/getent/CMakeLists.txt
In autotools, the getent module is called tfgetent. In cmake, it is
called just getent. This fails the getent-related e2e tests in the cmake version. 
The cmake version is aligned to the autotools version.
=> cmake: fixing different naming of getent between autotools and cmake

syslog-ng-ctl/syslog-ng-ctl.c
sgtty.h doesn't need and cause compile error on freebsd.
closes #1901 
=> Fix compile issue #1901 on freebsd

dbld/images/jessie/dev-dependencies.txt
* Updated jsonc module needed a newer (v.1.14) automake
=> JessieDocker: Update automake in Jessie dev-dependencies

modules/python/python-dest.c
**module/python** (python_destination)
Now init is optional in python destination.
These changes were made by taking help from similar deinit method.
Signed-off-by: Utsav Krishnan <utsav.krishnan.cse15@iitbhu.ac.in>
=> python: make init() optional for destinations

.travis.yml, configure.ac
`eventlog` is not an external library anymore.
Instead of adding an `-levtlog` ld flag, this patch adds the internal `libevtlog` explicitly as a dependency.
=> eventlog: avoid linking to old system libevtlog libraries

lib/tlscontext.c, modules/afsocket/transport-mapper-inet.c
key_file and cert_file are optional (the client cert is not mandatory).
Fixes #1916
Questions:
- `secret-storage` does not work with NULL keys. Should we fix the API to prevent such cases? (Passing NULL causes a crash.)
=> Fix TLS-based destinations in case of a missing client key/cert

configure.ac, lib/compat/glib.c, lib/compat/glib.h, lib/secret-storage/secret-storage.c
Fixes issue #1270  
SLES 11 has glib version <=2-26, in which g_list_free_full function is not present.
Added compat : glib patch to fix the issue.
=> Added g_list_free_full in lib/compat/glib & configure.ac

lib/cfg-grammar.y, lib/cfg-parser.c, lib/cfg-tree.c, lib/cfg-tree.h, lib/logpipe.h, scl/cisco/plugin.conf, scl/solaris/plugin.conf
We are already able to do conditional evaluation with a bit arcane syntax:
junction {
channel {
filter { EXPR1 };
...
flags(final);
};
channel {
filter { EXPR2 };
...
flags(final);
};
channel {
flags(final);
};
};
However, this is not very intuitive. This patch adds syntactic sugar using
the if / else keywords to achieve the same, such as:
if (message('foo')) {
...
} elif (message('bar')) {
...
} else {
...
}
This should make the configuration for complex of stuff a lot simpler.
=> add conditionals into the config syntax

libtest/mock-transport.c, libtest/mock-transport.h
Previously there was a heuristic in that object
which tried to detect if the data is a string or an
error code. But this heuristic was failing in GNU Hurd.
With this patch, the heuristic is replaced with a
type field in a structure.
This patch fixes issue #1912
I welcome every suggestion and, as you can see, the giving name is still not my cup of tea, so if somebody knows a better name for the variables or the new structure, I would be more than happy to rename them.
=> Make the data type explicit in transport mock

lib/filter/tests/test_filters.c, lib/logmatcher.c, lib/logmatcher.h, tests/unit/test_matcher.c
This branch is building on top of filter-logging-improvements (could rebase, but I've figured that other one would go in first anyway).
This drops support for POSIX regular expressions in favour of using PCRE. We have migrated to using PCRE in other parts of the code base, and I've figured there's not much sense on keep supporting both.
PCRE is a required dependency and is much better both functionality and performance wise.
=> logmatcher: remove POSIX regexp support

modules/graphite/graphite-output.c, modules/java/native/java-destination.c
The LogTemplate->name member is used to store the name of the template
statement, so it is not needed in case we are creating inline template
instances. Get rid off that parameter from everywhere.
=> template: remove unneeded name argument from call sites

dbld/rules
dbld/rules login would drop you in a shell within the default container,
just like shell.
dbld/image would just build the default image
=> Dbld login and image targets

lib/file-perms.c, lib/file-perms.h, modules/affile/file-opener.c, modules/affile/file-opener.h
The file source checks if the provided path exists, and in case of the path does not exists it has a side effect to put a terminating zero, thus corrupting the passed filename argument. That parameter should be read only.
Because of this I also modified the rest of the `file_perm_*` functions, where it did not cause any issue.
* Does it okay to `memcpy` the `name` paramater from performance point of view? (Does it have per message performance penalty?!)
Fixes #1934
=> file source filename corruption in case of missing path

lib/logmsg/logmsg.c, modules/diskq/logqueue-disk-non-reliable.c
After fixing the restart functionality of disk-queue (see PR #1886) our test cases found another bug in non-reliable disk-queue.
After a successful message pop from disk-queue (either from qout or from overflow buffer or from the disk itself) we call a `move_disk` function to move the messages between the different queues.
Order of moving messages:
qout <-- qdisk <-- qoverflow.
In this `move_disk` function there is a lack of error handling when reading from the disk which results in a crash when `log_msg_get_size` is called with passing a NULL pointer to it.
Note that reliable disk-buffer is not affected.
Question:
* When will the invalid read reported to the user of disk-queue? `_move_disk()` is a void function.
=> Diskq: Fix crash when corrupt disk-queue is read (during move)

modules/afamqp/afamqp.c
Fixes issue #1909 . LogTemplateOptions were ignored in the driver because it was not called by log_template_format() function.
=> afamqp: LogTemplateOptions fix

lib/logpipe.h, lib/persist-state.c, modules/affile/directory-monitor-inotify.c, modules/affile/file-reader.c, modules/affile/file-reader.h, modules/affile/poll-file-changes.c, modules/affile/wildcard-source.c
This patchset fixes 3 independent crashes in wildcard file source.
- in persist state, g_cond_wait was not checked in a while loop, though it is possible to it returns early, without g_cond_signal. This resulted in an assert. I could trigger this with creating and deleting non-empty files in busy loop, while reloading syslog-ng, also in a busy loop.
- When a file is deleted wildcard source deinits the reader in the main thread, but in the meantime it was possible the worker threads try to post message to the pipe element, resulting in an assert. The deinit of the reader is moved to another part of the code: it is handled together with the other reader notifications. Those are synchronized with the pipe post mechanism, eliminating the crash.
- Missing check for directory monitoring …
=> wildcard file source: fixing various crashes

lib/logthrdestdrv.c, lib/mainloop-io-worker.c
There is an explicit scratch_buffer_gc call in `log_threaded_dest_driver_do_work()`
(see `main_loop_worker_run_gc`), 
but the insert() method can be called several times in one do_work call.
If `scratch_buffers_alloc()` is used in the insert method and have been called several times then the memory usage will be increased.
With this patch the used scratch buffers will be reclaimed after each insert() call.
Question:
- Why should the current `main_loop_worker_run_gc` remain in do_work() function?
=> Fix scratch-buffer memory usage in threaded destinations

CMakeLists.txt, Makefile.am, lib/Makefile.am, lib/template/tests/CMakeLists.txt, lib/template/tests/Makefile.am, lib/template/tests/test_template.c, lib/template/tests/test_template_speed.c, libtest/CMakeLists.txt, libtest/Makefile.am, libtest/cr_template.c, libtest/cr_template.h, modules/basicfuncs/tests/CMakeLists.txt, modules/basicfuncs/tests/test_basicfuncs.c, modules/cef/tests/CMakeLists.txt, modules/cef/tests/test-format-cef-extension.c, modules/cryptofuncs/tests/CMakeLists.txt, modules/cryptofuncs/tests/test_cryptofuncs.c, modules/graphite/CMakeLists.txt, modules/graphite/Makefile.am, modules/graphite/tests/CMakeLists.txt, modules/graphite/tests/Makefile.am, modules/graphite/tests/test_graphite_output.c, modules/json/tests/CMakeLists.txt, modules/json/tests/test_format_json.c, modules/kvformat/tests/CMakeLists.txt, modules/kvformat/tests/test_format_welf.c, modules/stardate/tests/CMakeLists.txt, modules/stardate/tests/test_stardate.c, modules/tagsparser/tests/test_tagsparser.c
This PR
- adds unit tests for the `$(graphite-output)` template function
- rewrites all template-related unit tests in Criterion
Resolves #268
=> Rewrite/add template-related unit tests

modules/basicfuncs/list-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c
Negative indexes are interpreted in a similar way to $(list-slice), e.g.
they are calculated from the end of the list.
=> basicfuncs: add support for negative indexes in $(list-nth)

lib/cfg-block-generator.c, lib/cfg-block-generator.h, lib/cfg-block.c, lib/cfg-block.h, lib/cfg-grammar.y, lib/cfg-lexer.c, lib/cfg-lexer.h, lib/cfg-parser.c
This patch vastly improves error reporting in case a syntax error happens in the configuration. It is in a way doing something similar to what #1931 does with Python exceptions.
Should make troubleshooting config issues a lot simpler.
=> Improve error reporting

lib/Makefile.am
See details in the issue.
Fixes #1949
=> libsyslog-ng: missing dependency libsecret-storage

modules/afstomp/afstomp.c, modules/afstomp/tests/CMakeLists.txt, modules/afstomp/tests/test_stomp_proto.c
As discovered in issue #1909 amqp `LogTemplateOptions` were not used in `log_format_template` call.
I have checked syslog-ng code for every template usage and discovered that `stomp()` dest. driver has the same problem, but only for the body part of the message.
Header part works: value_pairs call is using template options.
=> Fix stomp template option

libtest/cr_template.c, libtest/cr_template.h
Only testing is affected!
Now both cr_template and msg_parse_lib contain the same symbol: `MsgFormatOptions parse_options`. Also the syslogformat module initializer/deinitializer functions are copy-pasted between the two modules.
This patch resolves the problem: cr_template should use these symbols from msg_parse_lib.
=> testing: fixing symbol redefinition error

modules/python/python-grammar.ym
Will fix #1364 . syntax for python destination was "options('arg_name', ('arg_value'))" and for python parser it was : options('arg_name', 'arg_value'). This patch will make python destination syntax as it is in python parser.
=> python: fix the syntax for options() in python destination to make it in parity with python parser

lib/logmsg/logmsg-serialize-fixup.c
This crash happens, when a message is deserialized. (An example for this is the disk queue file.)
The deserialization process has two steps. One that actually make the deserialization, and an additional *fixup* step.
The additional *fixup* step tries to validate and updated the index table with the new handles (if they are new).
The issue comes from this fixup, because first it creates a temporary index table, if a handle has a new handle it saves the updated entry to the temporary table.
After going through all of the entries, if there was even one updated entry it just swaps the two table (temporary, and active).
The issue here, that when there were some handle which has been updated, and there were some that have not, the temporary table has gaps with uninitialized entities.
This …
=> nvtable: deserialized handle access crash

lib/logmsg/nvtable.h
Subtracting an "out-of-boundary" number from a pointer is undefined.
The result may underflow making the condition false, causing a crash.
(`alloc_size` is the size of a new entry that we want to store in NVTable.)
Apart from this, my change is an equivalent transformation.
This bug has been identified on a Solaris 11 machine, where `NVTable` is often stored on low addresses.
=> Fix possible LogMessage-related crash (NVTable)

lib/logwriter.c
The else branch has a same debug message as the modified one in #1890
=> log_writer_write_message: same modification as PR 1890

modules/affile/affile-dest.c
There is a pre-existing race condition related to `time-reap()`: when the timer times out, we check the queue without a lock (for a lot of reasons related to performance), to see if we should reap the destination. If a message arrives when the check finished, but the function didn't return yet, we'll put that in the queue, and still reap the destination. The new message in this case will likely get lost.
This condition has existed in `time-reap` for a long time, but recent changes and refactors made the situation worse. This pull request reverts the changes that do so.
We should fix the race properly, but until we can do so, bringing down the frequency at which it happens reduces the impact considerably.
=> Partially revert some time-reap changes, to lessen the impact of a race

Makefile.am, configure.ac
The final helper PR for #1302.
This is the last part I would like to extract from #1302. The idea is the following:
- This patchset adds those warnings to enable extra warnings that do not generate warnings for now. The other part of the list is left in #1302.
- Besides that part, I ported the CFLAGS specification cleanup patch of @bazsi.
The plan is #1302 will only contain those warning options, that we need to deal with code change. When we have a list, we will write issues about those and expect those be fixed/analyzed through the newly created issues and prs. As such, #1302 will be resolved.
=> Enable warning: warning manipulation

dbld/images/devshell-apt/all.txt, dbld/images/devshell.dockerfile
This patch adds locale and ensures en_US.utf8 is generated during
image build. This is required to use an utf8 locale at runtime, which
is the most common setup these days.
=> dbld/images/devshell: generate utf8 locale

lib/logmsg/logmsg.c, lib/logmsg/tests/test_log_message.c
If SDATA comes from a JSON object, block names may contain characters not allowed by the standard.
In test_log_message.c: changed **test_sdata_sanitize_keys** testcase to a more general **test_sdata_sanitization** and added only one additional message. (Don't want to duplicate all the messages since the sanitization was made by the same function.)
=> log_msg_append_format_sdata: added block name sanitization.

lib/pragma-grammar.ym, lib/pragma-parser.c, scl/cim/template.conf, scl/elasticsearch/plugin.conf, scl/ewmm/ewmm.conf, scl/graylog2/plugin.conf, scl/loggly/loggly.conf, scl/logmatic/logmatic.conf
A lot of `scl` has a hidden dependency for modules to be present. In case of that `scl` uses a plugin, that is not installed; the syslog-ng is not going to start up even if that specific block is not used in the configuration (but only included).
One of the most common example is the `json`, if the `json` module is not installed, with the default set of `scl`s syslog-ng is not going to start. There are two main workaround exists for this:
* install the module
* remove the scl file
This PR aim to give a solution by creating a new pragma keyword, which can specify module requirement. If the requirement is not specified the syslog-ng is going to skip the current file, thus not causing an issue in case of missing module.
Fixes #827.
=> pragma module-dependency for optional include

lib/tlscontext.c
When using OpenSSL 1.1, and clients supporting SSL session resumption, we
need to set the SSL session ID context, otherwise Windows clients with client
certificate will fail to connect for the 2nd time.
Very helpful PostgreSQL thread:
https://www.postgresql.org/message-id/CADT4RqBU8N-csyZuzaook-c795dt22Zcwg1aHWB6tfVdAkodZA%40mail.gmail.com
Original bugreport:
https://github.com/balabit/syslog-ng/issues/1936
Should fix #1936
=> tlscontext: set the ssl session id context to a static value

lib/mainloop-worker.c
We are storing the allocated thread ids as a bit array stored in a
guint64. However when trying to check single bits, we used an int
to shift into the various bit locations. ints are 32 bits, thus
when we shifted 1 << 32, we got 0, which is not correct.
This patch properly adds the LL suffix to those literal numbers, making
sure that we actually shift 64 bit values.
This fixes a crash on machines with more than 32 CPUs/cores.
Originally reported by @czanik in an email.
=> mainloop-worker: fix thread_id allocation for more than 32 CPUs

.travis.yml, lib/control/CMakeLists.txt, lib/control/Makefile.am, lib/control/control-server.c, lib/control/control.c, lib/control/tests/CMakeLists.txt, lib/control/tests/test_control_cmds.c, lib/control/tests/test_control_connection.c, lib/debugger/tests/CMakeLists.txt, lib/debugger/tests/test-debugger.c, lib/rewrite/tests/CMakeLists.txt, lib/rewrite/tests/test_rewrite.c
This PR has a few changes that is not a criterion conversion. 
* Tweaks the Travis.
* "Performance" tests take too long, while does not catch perf issues at all, so the iteration is decreased 
* The control command tests should use only the interface and shall not include `. c` files either.
=> Rewrite some unit tests to criterion based

lib/control/tests/test_control_cmds.c
The CMake modernization PR changed some include paths, and the UT refactor used the old one the lack of rebasing causes a compile error on the master. This PR fixes the include path in the test source file.
=> CMake compile issue because of PR #2003 and #2007

lib/logsource.c
This PR adds per-source "src.host" and "src.sender" counters.
These counters exist in previous syslog-ng versions, my PR just adds them to syslog-ng OSE.
```
options {
stats_level(3);
};
source s_1 {
//network(...);
};
destination d_1 {
//...
};
log {
source(s_1);
destination(d_1);
};
```
New per-source counters:
```
src.host;s_1#0;10.0.1.8;d;processed;3
src.host;s_1#0;10.0.1.8;d;stamp;1525433153
src.sender;s_1#0;10.0.1.8;d;processed;3
src.sender;s_1#0;10.0.1.8;d;stamp;1525433153
```
Please note that this is not equivalent with the `src.network;s_1#0;tcp,127.0.0.1;o;processed;3` counter, where the IP is coming from the source connection. The hostname/IP of `src.host` and `src.sender` is derived from the `HOST` and `HOST_FROM` fields of the actual LogMessage.
=> Add per-source counters to "src.host" and "src.sender"

tests/copyright/policy, tests/loggen/loggen.c
=> Modify the loggen.c license from GPL to LGPL [skip-ci]

lib/logpipe.h
The clone should be defined before the usage, this assert should force it. 
=> Assert clone exist 

dbld/images/helpers/functions.sh, dbld/images/required-epel/all.txt, dbld/rpm, packaging/rhel/syslog-ng.spec
RPM generation process update from @Czanik.
This is the first step in a long process, the final goal is to harmonize Peter's work and `/dbld`
- remove syslog-ng-add-contextual-data.pc from file list
- update to 3.14.1
- re-enable amqp & mongodb on RHEL only
- keep tcp wrappers support only on RHEL
Fixes: #1857
=> rpm generation process update

modules/affile/file-reader.c
* without this log_pipe_location_tag() will return with '#unknown' in log_source_queue()
Signed-off-by: László Várady <laszlo.varady@balabit.com>
=> FileReader: Set missing expr_node in file_reader_init_instance()

configure.ac, modules/diskq/Makefile.am, syslog-ng-ctl/Makefile.am
When using mixed linking, we want to link libevtlog dynamically, and without using libtool. For this reason, we can't use the '.la' file, and we want to link it before we tell the linker to "link the rest statically".
Additionally, we need to specify the libraries in a certain order, otherwise the linker will not be able to resolve symbols. The diskq and syslog-ng-ctl Makefiles were adjusted accordingly.
Fixes #2020.
=> configure.ac: Fix mixed linking

dbld/images/helpers/functions.sh
- enable_dbgsyms(): fix keyserver.ubuntu.com URI, without this change fetching can be stuck
- install_perf(): install OS native version of linux-tools instead of hosts OS version
=> Dbld: Add fixes to functions.sh

tests/functional/log.py
`%m` (month) and `%M` (minutes) were mixed up.
=> tests/functional/log.py: fix date format

packaging/debian/syslog-ng-core.install
=> packaging/debian: Add libhook-commands.so to syslog-ng-core.install

configure.ac, lib/logpipe.h, modules/geoip2/maxminddb-helper.c
This patchset contains the following changes:
- fixing no-pie detection for gcc 4.4. With version 4.4, gcc cannot be configured to fail on unknown cli parameters. As a result, `-no-pie gcc: error: unrecognized command line option '-no_pie'` is emitted during the build. This did not cause any problem, just an unnecessary warning is emitted.
- Adding an assert for the exciting cpu-cache optimization introduced in  9fc86dfc6de3ad66862218522b2588d4553c70de.
- using glib macro in format string to write uint64 number.
=> autotools: fixing emitted warnings due to -no-pie detection for gcc 4.4

libtest/CMakeLists.txt, libtest/Makefile.am, libtest/mock-transport.c, libtest/mock-transport.h, libtest/tests/CMakeLists.txt, libtest/tests/Makefile.am, libtest/tests/test_mock_transport.c
This patchset adds a few enhancements to LogTransportMock:
- Exposing a new `log_transport_mock_inject_data` function, which can be used to add data to the transport. Originally, all data must have been added in the constructor. Now data can be injected after LogTransportMock is created
- General purpose user data is added to LogTransportMock, which can be used to carry test-specific data in the mock. For example one can give a name to the mock.
- Support for cloning LogTransportMock. Cloning can be used for testing drivers that can replace their transport on the fly. In that case, clone can carry the already injected and written data, that will be available after changing transport.
- Removing restriction of the number of injectable data chunks. Originally it was limited to 32.
- Support …
=> LogTransportMock enhancement

libtest/mock-transport.c
In gcc 4.4, one cannot initialize unions using compound literals. It results in a compiler error.
=> mock-transport: fix compiler error for gcc 4.4

syslog-ng-ctl/syslog-ng-ctl.c
On ubuntu 18.04 the `syslog-ng-ctl query` command does not work because the command send the wrong data over the control file. The global `raw_query_params` "duplicates" the first parameter.
[Edit] As it turned out it was not related to the distribution, see my comment below.
=> syslog-ng-ctl: fix shifting of the raw_query_params

lib/cfg-parser.c
Instead of simply failing the configuration parse process when the parser encounters a memory exhaustion, report the fact more properly. To do this, we store the result of `self->parse`, so that we can check for the OOM state too. If we are in that state, report the error with a suggestion. We still narrow the return value of `cfg_parser_parse` to a boolean, with the OOM case obviously being a failure case.
Fixes #2030.
=> cfg-parser: Report memory exhaustion errors during config parsing

lib/cfg-grammar.y, lib/cfg-lex.l, lib/cfg-lexer.c, lib/cfg-parser.c, lib/cfg-parser.h
The issue I noticed while finishing up a previous PR was that line tracking got broken by 2e196c393e. While fixing the problem I've also improved error logging a bit more, which I've piggybacked to the same branch.
cfg-lex.l: fix location tracking for multi-line block-refs
For tokens that span multiple lines (in our case this only happens when
a block-ref is parsed that spans multiple lines), we blew up the line
number counter, so whenever reporting locations or errors we got an
incorrect value.
This patch fixes that by shifting to the new line number relative to
last_line, instead of simply increasing the first_line.
=> Fix lloc tracking for multi line blockrefs

modules/afprog/afprog.c
We don't have a debug message about a successful program source/destination start with the **fd** in it.  
That could be used later for identifying the driver when we see errors in the internal logs which only refer to fd-s.
This would be similar to what we currently have in the network based sources/destinations, e.g.
`Syslog connection accepted;` messages.
=> Add debug message to program source/destination about successful start

lib/filter/filter-call.c, lib/filter/filter-cmp.c, lib/filter/filter-expr.c, lib/filter/filter-expr.h, lib/filter/filter-in-list.c, lib/filter/filter-netmask.c, lib/filter/filter-netmask6.c, lib/filter/filter-pipe.c, lib/filter/filter-pri.c, lib/filter/filter-re.c, lib/filter/filter-tags.c, lib/logmsg/logmsg.c, lib/logsource.c, lib/parser/parser-expr.c, lib/rewrite/rewrite-expr.c, modules/add-contextual-data/add-contextual-data.c, modules/csvparser/csvparser.c, modules/date/date-parser.c, modules/dbparser/dbparser.c, modules/geoip/geoip-parser.c, modules/geoip2/geoip-parser.c, modules/json/json-parser.c, modules/kvformat/kv-parser.c, modules/map-value-pairs/map-value-pairs.c, modules/python/python-logparser.c, modules/snmptrapd-parser/snmptrapd-parser.c, modules/syslogformat/syslog-parser.c, modules/tagsparser/tags-parser.c, modules/xml/xml.c
Adding improved debug log for parsers, rewrite rules and logsources.
**Motivation came from**: 
* after adding new config elements like: default-network-drivers, ewmm, app-parser..., syslog-ng's debug log became hard readable
* improved debug logs of filters 9e3415b4e49b1addc8fac6eccd9f9c814e395e3d
**Conception**:
1. Log debug message at the beginning and at the end of queuing methods, like: 
* log_source_queue(), 
* log_parser_queue(), 
* log_rewrite_queue()
* Debug message should contains:
* name of the relevant logpipe element
* rule name
* location
* msg pointer
* result of filter_expr_eval_root() or log_parser_process_message() -> only at the end of queuing methods
* Example:
```
>>>>>> parser rule evaluation begin; rule='#anon-parser0', location='parser generator app-parser:5:15', …
```
=> LogPipe: Improved debug logs 

lib/host-resolve.c
Fully disabling DNS should also disable the DNS cache. To this end, when the configuration parser sees an `use-dns()` option, set `use-dns-cache()` to the same value too, unless it is `persist-only` (in which case the dns cache settings are not touched).
=> dnscache: Disable the DNS cache if use-dns(no) is used

modules/afsql/afsql-grammar.ym, modules/afsql/afsql-parser.c, modules/afsql/afsql.c, modules/afsql/afsql.h
* If ignore_tns_config is "yes" then oracle sql destination does not use
tnsnames.ora config file.
* Default value of ignore_tns_config is "no".
Destination driver uses tnsnames.ora
The motivation behind this patch is to be able to use Oracle destination without supplying tnsnames.ora config file.
=> afsql: added ignore_tns_config sql config option

lib/control/control-commands.c, lib/control/control-server.c, lib/secret-storage/nondumpable-allocator.c, lib/secret-storage/nondumpable-allocator.h, lib/secret-storage/secret-storage.c, lib/secret-storage/secret-storage.h, lib/secret-storage/tests/test_nondumpable_allocator.c, lib/secret-storage/tests/test_secret_storage.c, syslog-ng-ctl/CMakeLists.txt, syslog-ng-ctl/Makefile.am, syslog-ng-ctl/syslog-ng-ctl.c
A simple `memset()` call can be optimized away. To prevent the optimization, `nondumpable_mem_zero()` has been added.
~It uses `explicit_bzero()` where available and falls back to a volatile memset function pointer (which is not guaranteed to be called, but it is better than calling `memset()` directly).~
Since secret-storage is not used on fast paths, I replaced the original implementation with a simple iteration on a pointer to a volatile char.
=> secret-storage: add safer mem_zero()

lib/cfg-args.c, lib/cfg-args.h, lib/cfg-block-generator.c, lib/cfg-block-generator.h, lib/cfg-block.c, lib/cfg-grammar.y, lib/cfg-lex.l, lib/cfg-lexer.c, lib/cfg-tree.c, modules/appmodel/app-parser-generator.c, modules/appmodel/tests/test_app_parser_generator.c, modules/confgen/confgen-plugin.c, modules/system-source/system-source.c, scl/default-network-drivers/plugin.conf, scl/elasticsearch/plugin.conf, scl/ewmm/ewmm.conf, scl/graphite/plugin.conf, scl/hdfs/plugin.conf, scl/kafka/plugin.conf, scl/loadbalancer/plugin.conf, scl/loggly/loggly.conf, scl/logmatic/logmatic.conf, scl/nodejs/plugin.conf, scl/osquery/plugin.conf, scl/pacct/plugin.conf, scl/snmptrap/snmptrapd-source.conf
This branch makes the __VARARGS__ functionality in SCL blocks explicit, as currently it is very easy to mis-spell an argument, which is not logged in any way. It changes the syntax slightly:
```
block source something(foo() bar() ...) {
};
```
The ... at the end of the argument list tells syslog-ng that this macro indeed wants to accept __VARARGS__, thus any name-value pair can be passed without validation.
=> Error reporting on misspelled block args

lib/logproto/logproto-buffered-server.c, lib/logproto/logproto-buffered-server.h, lib/logproto/logproto-client.h, lib/logproto/logproto-framed-server.c, lib/logproto/logproto-server.h, lib/logproto/logproto-text-client.c, lib/logproto/logproto-text-server.c, lib/logreader.c, lib/logwriter.c, modules/affile/logproto-file-writer.c, modules/afsocket/afsocket-dest.c
LogProto can now express an idle timeout during prepare. When the timeout elapsed, logwriter/logreader will close the controlling pipe.
Credits for @MrAnno for the logwriter part.
=> logreader+logwriter: timeout support

lib/logproto/logproto-server.c, lib/logproto/logproto-server.h, lib/logreader.c, lib/logreader.h, modules/afsocket/afsocket-source.c
Previously, the connection was closed after calling the destructor of LogReader.
The destruction of LogReader might be delayed, for example, by AckTracker, so an explicit close method is required.
=> Fix connection close in network sources

lib/logproto/logproto-buffered-server.c, lib/logproto/logproto-buffered-server.h, lib/logproto/logproto-framed-server.c, lib/logproto/logproto-server.h, lib/logproto/logproto-text-server.c, lib/logreader.c
This PR adds a thread-safe suspend and wakeup functionality to LogReader.
LogProtoServer is now able to instruct LogReader to suspend until an asynchronous event occurs.
----------------
Questions:
- I haven't changed the signature of LogProtoClient's prepare(). Since it does not have "suspend" functionality, I think it might be OK to leave it as is. What do you think?
=> LogReader async wakeup

dbld/images/required-pip/all.txt
We are only using requirements.txt to bootstrap the development environment,
and that file is not really used in production. It is better to rely on
the latest and greatest so we actually follow pep8/pylint etc changes as
they happen.
If we get too many issues with that, we might pin some of the version
numbers in te future, but so far the experience has been that we simply
forget to bump versions and stick to very old versions instead.
=> requirements.txt: drop explicit version numbers

.gitignore, dbld/bootstrap, dbld/images/devshell-apt/all.txt, dbld/rules, tests/collect-cov.sh
This patch set makes it possible to generate coverage reports in the devshell image. It contains a set of fixes that:
1) removes python-venv from dbld/bootstrap
2) adds lcov package to the devshell image
3) fixes an lcov compatibility issue that comes up with the lcov version in artful
4) makes it possible to customize dbld options locally from a dlbd/rules.conf file that is included into the main makefile.
With that, if --enable-gcov is added as a configure option, "make coverage" would work from within the devshell image, generating an HTML report into dbld/build/coverage.html
We roughly have 67% coverage with the unit tests alone. Could be better, but some parts look really nice, others less so.
=>  Dbld coverage

modules/java/native/java_machine.c, modules/java/native/java_machine.h, modules/java/proxies/java-destination-proxy.c, modules/java/proxies/java-logmsg-proxy.c
Just two small refactor in the java module.
=> Small java code refactor

modules/python/pylib/syslogng/debuggercli/completerlang.py
The yacc implementation we are using (ply), didn't publish its state
variable, requiring us to look that up using sys._getframe() calls, which
was pretty fragile.
@dabeaz was nice enough to add this function to ply in 2016 (version 3.9),
which has now trickled into various distributions, so the hack can be removed.
https://github.com/dabeaz/ply/issues/65
=> debuggercli: remove getframe() hacks from completerlang

lib/cfg-grammar.y, lib/parser/parser-expr-parser.c, modules/affile/affile-grammar.ym, modules/dbparser/dbparser-grammar.ym, modules/dbparser/dbparser-parser.c
The following grammar does not parsed successfully, the syslog-ng reports that the `file` is an unexpected symbol (which is clearly not).
```
parser test_parser {
channel {
if (message('foo')) {
filter {message('foo2')};
parser { date-parser();};
destination { file("/tmp/out2" ); };
};
};
```
Thanks @mitzkia to come up with this configuration snippet.
The strange thing is that it works with every other destination (network, redis, ...) as far as I could see only the file was effected.
As it turned out the KW_FILE token was in a global namespace, every parser has a KW_FILE in it. In this situation the tokenazier must have found the KW_FILE (which is should not found, but because the lack of this token it should try to load the parser for the affile plugin.), but because it found this …
=> KW_FILE token in a global namespace

lib/logproto/logproto-server.c, lib/logproto/logproto-server.h, lib/logreader.c, lib/logreader.h, modules/affile/file-reader.c, modules/afsocket/afsocket-source.c
This PR reverts #1991 and fixes connection close in afsocket on the proto level.
`log_reader_reopen(self, NULL, NULL);` is already used in `file-reader`, I just gave it a more descriptive name (`log_reader_close_proto`) and used it in `afsocket_sd_close_connection`.
=> logreader: add log_reader_close_proto()

lib/transport/tests/test_transport_factory_registry.c, lib/transport/transport-factory-registry.c, lib/transport/transport-factory-registry.h
Reason: to support writing "advanced" unit tests where it is required to
override an existing TransportFactory with a FakeFactory.
(override : remove old/steal TransportFactoryId/add fake factory with
the stolen id)
=> transport: extend TransportFactoryRegistry with remove() method

lib/cfg.c
`cfg_tree_free_instance()` deallocates all `LogExprNode` instances (and their `LogPipe` instances as well).
**`LogPipe`s are deinitialized in this state, but they can still write to and read from `PersistState`, so it must not be freed.**
For example:
1. `cfg_free()` deallocates its persist-state
2. `cfg_tree_free_instance()` is called, which produces the following chain:
```
afsocket_dd_free() --> log_queue_fifo_free() --> log_reader_free() --> log_proto_server_free()
```
3. `LogProtoServer` does not have a deinit() method, so implementations might want to write/read persist-state in free() in order to persist their last state.
Since an active `AckTracker` prevents freeing the `LogReader` instance in deinit-time (to handle the remaining acks), `LogReader` will be freed only after the …
=> cfg: free PersistState after deallocating all LogPipe objects

lib/tests/test_rcptid.c
After calling `restart_persist_state`, rcptid must be reinitialized with the new `PersistState` instance.
The macOS CI job caught this. \o/
=> Fix test_rcptid

modules/basicfuncs/Makefile.am, modules/basicfuncs/basic-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c, modules/basicfuncs/urlencode.c, packaging/debian/syslog-ng-mod-http.install, scl/CMakeLists.txt, scl/Makefile.am, scl/telegram/telegram.conf
This patchset contains two changes:
- Support to send messages to [telegram](https://telegram.org/).
- urlencode template function
CC: @fekete-robert for documentation
CC: @lbudai - packaging
**Telegram destination:**
A new destination is available:
```
destination d_telegram {
telegram(
template("$(urlencode \"${MSG}\")")
throttle(1)
parse-mode("markdown")
disable-web-page-preview("true")
bot-id("<bot id>")
chat-id("<chat id>"));
};
```
Parameters:
- template: specifies the content of the message. Optional. Default value: `$(urlencode \"${MSG}\")`. According to telegram API, the message must be urlencoded.
- throttle: same as in other destinations: rate limit of sending message. One can read the limits from telegram in https://core.telegram.org/bots/faq#my-bot-is-hitting-limits-how-do-i-a …
=> telegram destination + urlencode template function

lib/logmsg/logmsg-serialize-fixup.c, lib/logmsg/tests/CMakeLists.txt, lib/logmsg/tests/test_logmsg_serialize.c
The #1919 was not fixed by the #1967 because the sdata should has also a fixup, that has the same fault.
This PR tries to cover also sdata.
=> nvtable: deserialize sdata invalid if fixed up

lib/Makefile.am, lib/tests/Makefile.am
`lib/tests` contains `EXTRA_DIST` inputs for tests, for example: `lib/tests/testdata-lexer/`. They should not be excluded from the dist tarball, even if testing is disabled.
Note that only `EXTRA_DIST` is affected by automake's `if` conditional, source files can't be excluded from the tarball by `if`. automake handles them automatically (see `SOURCES_DIST`).
=> Always add test datafiles to the dist tarball

lib/logmsg/logmsg-serialize.c
`sd_element_name` is a pointer, `sizeof()` can not be called on it to determine the array size.
Detected by gcc 8.1.1, configured with `--enable-extra-warnings`.
=> Fix a bug in the old LogMessage deserialization

lib/secret-storage/nondumpable-allocator.c, lib/secret-storage/tests/test_nondumpable_allocator.c, lib/secret-storage/tests/test_secret_storage.c
PAGESIZE is a define in some libc libraries, which conflicts with these local variables.
This PR is fix for:
```
In file included from
/mnt/a/oe/build/tmp/work/core2-64-bec-linux-musl/syslog-ng/3.15.1-r0/recipe-sysroot/usr/include/limits.h:8,
from
/mnt/a/oe/build/tmp/work/core2-64-bec-linux-musl/syslog-ng/3.15.1-r0/recipe-sysroot/usr/lib/glib-2.0/include/glibconfig.h:11,
from
/mnt/a/oe/build/tmp/work/core2-64-bec-linux-musl/syslog-ng/3.15.1-r0/recipe-sysroot/usr/include/glib-2.0/glib/gtypes.h:32,
from
/mnt/a/oe/build/tmp/work/core2-64-bec-linux-musl/syslog-ng/3.15.1-r0/recipe-sysroot/usr/include/glib-2.0/glib/galloca.h:32,
from
/mnt/a/oe/build/tmp/work/core2-64-bec-linux-musl/syslog-ng/3.15.1-r0/recipe-sysroot/usr/include/glib-2.0/glib.h:30,
from ../syslog-ng-3.15.1/lib/compat/glib.h:31, …
```
=> secret-storage: rename PAGESIZE variables to pagesize

dbld/images/required-epel/all.txt, packaging/rhel/syslog-ng.spec
packaging/rhel: add support for modularized loggen
use external rabbitmq-devel as it's no more bundled
Signed-off-by: Laszlo Szemere <laszlo.szemere@balabit.com>
=> preparation for 3.16 OSE rhel/packaging

lib/CMakeLists.txt, lib/Makefile.am, lib/children.c, lib/children.h, lib/signal-handler.c, lib/signal-handler.h, modules/java/Makefile.am
The initial issue:
In case of both java destination and program source/destination configured, syslog-ng cannot reap the program source/destination, which is started in a fork. Those fork remains in Zombie state until syslog-ng is restarted.
This is because the java virtual machine  sets  its own  signal handler. The syslog-ng reaping
happens when the SIGCHLD handler is  called, but the java replaced our SIGCHLD
handler. Therefore every forked process became a zombie, there is nobody calling wait on them.
A proposed solution:
The sigaction is registers the signal handlers, to overcome the java own
registration process in syslog-ng we implement our own sigaction implementation,
which is called instead of the one in libc. Every single case our sigaction
calls the original one, except in …
=> force syslog-ng SIGCHLD handlers on top

packaging/debian/syslog-ng-dev.install
The library is generated only when criterion is available.
As criterion (and criterion-dev) is not part of the Build-Depends
in control file, this should be removed from here.
Criterion is not supported by deb package builder environments
currently, this is why not adding criterion-dev to Build-Depends.
=> packaging/debian: remove libsyslog-ng-test.a from syslog-ng-dev package

libtest/mock-transport.c, libtest/mock-transport.h
Tests might need to inherit from mock-transport, for example calling some test specific business logic before read, or after write method. This patch exposes the necessary functions so that specialized test transport classes can be built from mock-transport.
=> mock-transport: make it inheritable

modules/systemd-journal/systemd-journal.c
This PR enables the global "center;;received" counter on the `systemd-journal` source.
=> Fix global "center;;received" counter when systemd-journal() is used

lib/file-perms.c
Default to -1 for file and directory ownership, meaning no ownership changes will be applied, unless explicitly specified. This becomes important when running syslog-ng as a user (with appropriate capabilities granted), because one would expect that - unless configured otherwise - it will use the running user for the owner of files it creates.
Fixes #2002.
=> file-perms: Default to -1 for file and directory owners

dbld/images/devshell-apt/all.txt, lib/logthrdestdrv.c, lib/logthrdestdrv.h, modules/afamqp/afamqp.c, modules/afmongodb/afmongodb-private.h, modules/afmongodb/afmongodb.c, modules/afmongodb/tests/test-mongodb-config.c, modules/afsmtp/afsmtp.c, modules/afstomp/afstomp.c, modules/http/http-plugin.h, modules/http/http.c, modules/java/native/java-destination.c, modules/java/native/java-destination.h, modules/python/python-dest.c, modules/redis/redis.c, modules/riemann/riemann.c
This is the initial set of _non-functional_ changes in log threaded dest driver that should be risk-free to merge. 
I've extracted these from PR #2063 
I am going to rebase the rest of my branches on top of this one.
The core of the patches are:
* rename and reorder functions to make logthrdestdrv.c easier to navigate
* extract some code into smaller functions (without other changes)
* drop some unused functionality from afmongodb and the supporting code from logthrdestdrv
I also left in my devshell dbld patch, which adds gdbserver to the devshell docker image, so that I can run/debug unit tests within docker.
=> Logthreaded nonfunctional changes

lib/logwriter.c
Mark mode messages need not be acked. Without this patch, protos can
crash that do not immediately acknowledge back messages.
=> logwriter: disable ack for mark mode

contrib/selinux/src/root_safe/syslog_ng.el5.fc.in, contrib/selinux/src/root_safe/syslog_ng.el6.fc.in, contrib/selinux/src/root_safe/syslog_ng.el7.fc.in, contrib/selinux/src/syslog_ng.el67.te.in, contrib/selinux/syslog_ng.sh
src/root_safe/syslog_ng.el6.fc.in: added conf.d/*.conf to be marked as config files
src/root_safe/syslog_ng.el7.fc.in: added conf.d/*.conf to be marked as config files, removed labels for the init script
src/syslog_ng.el67.te.in: bumped module version to 1.0.6
syslog_ng.sh: updated OS detection code to properly detect CentOS 7, updated code for init-script labeling
* added conf.d/*.conf to be marked with the label syslog_conf_t
* removed labels for the init script for RHEL/CentOS 7
* module version bump to 1.0.6
* OS detection had problems with CentOS 7, when lsb_release was present, fixed it
* updated init script relabeling code, to handle when the init scripts are not present
Signed-off-by: Szigetvari Janos <jszigetvari@gmail.com>
=> Minor updates to SELinux policy installer script

contrib/Makefile.am, contrib/selinux/src/syslog_ng.el5.te.in, contrib/selinux/src/syslog_ng.el6.0to4.te.in, contrib/selinux/src/syslog_ng.el67.te.in, contrib/selinux/src/syslog_ng.module.version, contrib/selinux/syslog_ng.sh
contrib/selinux/src/syslog_ng.el5.te.in: removed version information
contrib/selinux/src/syslog_ng.el6.0to4.te.in: removed version information
contrib/selinux/src/syslog_ng.el67.te.in: removed version information
contrib/selinux/syslog_ng.sh: updated to combine the version string and the .te.in files
contrib/selinux/src/syslog_ng.module.version: added new file to hold module version
Signed-off-by: Janos SZIGETVARI <jszigetvari@gmail.com>
=> Fixed selinux module version inconsistency

CMakeLists.txt, cmake/Modules/FindGLIB.cmake, cmake/Modules/Findcriterion.cmake, tests/copyright/policy
Changes:
* Copyright does not need to check the `cmake` directory, because there only should be compile related files
* Updated the `FindGLIB` for cmake
* Fix missing dependency for `FindCriterion`
=> cmake: glib detection more robust

configure.ac, lib/logproto/tests/Makefile.am, syslog-ng/Makefile.am
To help linkers find symbols in libsecret-storage, even when used only indirectly via libsyslog-ng, link everything to it. We do this by adding it to `TOOLS_DEPS_LIBS`, and fixing a few places where this wasn't used.
This fixes #2094.
=> build: Link everything to libsecret-storage

cmake/add_tests.cmake
This PR contains a workaround for a bug in the implementation of the `POSITION_INDEPENDENT_CODE` property (CMake).
https://gitlab.kitware.com/cmake/cmake/issues/16561
=> Fix CMake unit test compilation (no-pie)

scl/telegram/telegram.conf
Due to scl error users needed to append "bot" before bot id:
The api url is
```https://api.telegram.org/bot{api-token}/sendMessage```
instead of
```https://api.telegram.org/{api-token}/sendMessage```
Fixes: https://github.com/balabit/syslog-ng/issues/2141
CC: @czanik thanks for the interest and test of the telegram destination!
=> telegram: fixing bug with bot id

modules/pseudofile/pseudofile-grammar.ym, modules/redis/redis-grammar.ym, scl/graylog2/plugin.conf, scl/mbox/mbox.conf, scl/osquery/plugin.conf
This branch fixes a couple of cases where the source_driver_option or dest_driver_option rules were not
referenced.
It also fixes scl source/destination drivers to include __VARARGS__.
Both of these changes support the ability to use inner source/dest plugins such as hook-commands() in all drivers.
=> All drivers should support inner dst or src plugins

lib/logqueue-fifo.c, tests/unit/test_logqueue.c
In the original code, the content of backlog is dropped earlier, then
the empty list is iterated through to update memory_usage
counter. This means when messages put back to backlog later again,
the size was subtracted twice, hence the underflow.
This patch first updates statistics, then drops the content of backlog, fixing the problem.
The only place when this code path is walked in ose is in afsql, where I could reproduce the problem:
created an sql destination with type(sqlite3), setting flush-lines(1000). After starting to send logs, I deleted the sql database file. This triggered an underflow in memory_usage. After this patch, the memory_usage counter goes back to zero, when the load stops.
=> logqueue-fifo: memory_usage - possible underflow (afsql)

lib/host-resolve.c
Since bad916a9e6c5 ("Enforce use-dns-cache(no) when use-dns(no) is
set"), the emitted warning does not refer to an existing setting
=> dns: Inform about the right dns-cache() configuration

lib/pragma-grammar.ym
The `@requires' keyword wrote a warning, when the component was missing. 
It is probably too verbose, this PR moves that warning message into the debug level.
Fixes #2138
=> pragma: lower the require message level to debug

CMakeLists.txt, Mk/lex-rules.am, cmake/Modules/GenerateYFromYm.cmake, configure.ac, modules/python/CMakeLists.txt, tests/functional/CMakeLists.txt, tests/functional/Makefile.am, tests/functional/runtests.sh
Instead of using `AC_PATH_PROG` to find the python binary (which can only find binaries named `python`, not `python3` and similar), use `AM_PATH_PYTHON` instead, and take `--with-python` into account as well.
For this to work, we also need to call a few of our python scripts through the interpreter, to avoid having to generate the scripts.
Fixes #2090.
=> Better python binary detection

lib/afinter.c
Prior this patch, internal mark mode messages were generated independently
from flow control. This means mark mode messages were sent even if the
destination cannot handle messages.
With the patch, mark mode messages can fill now the available window,
as such, internal source can be suspended properly because of them,
and no mark mode messages are generated in that case.
How to test?
Leave syslog-ng running with -Fevd without a destination. You will see that around 100 mark mode messages, the mark mode generation stops. Without this patch, mark mode messages are generated infinitely.
```
@version: 3.16
options {
time-reopen(1);
mark-freq(1);
};
log {
source { internal(); };
source { network(port(4444) transport(tcp)); };
destination { network(localhost port(5555) transport(tcp) …
```
=> afinter: adjusting window size for internal mark mode

lib/cfg-tree.c, lib/serialize.c
* In the `cfg_tree_compile_junction` function the `fork_mpx` unconditionally dereferenced, and it can be a null pointer.
* When the `LogMessage` is deserialized and the `sdata` does not have data (`sdata==NULL`), it tries to read zero byte into a zero length buffer (null pointer).  Reading zero was a valid operation before this PR, it just make sure, that the read function does not touch anything as they should not.
Question:
* Is it okay to move the `outer_pipe_head` initialization ?
=> undefined behavior fix

lib/afinter.c, lib/logwriter.c
afinter: mark mode - no need to update watches
update_watches will be called in afinter_source_post later.
Regression was introduced in:  https://github.com/balabit/syslog-ng/pull/2146
The problem is update_watches reschedules
mark_timer, but in this code path, the timeout was not increased. It
is only increased when the mark message is actually added to the
queue (log_src_driver_queue_method). In older ivykis versions, this
caused infinite loop: the handler of the timer in the past is called
infinitely. With newer ivykis versions, the handler of the passed
timer is not called immediately, so syslog-ng could call the queue for
the message, which would increase the timeout, avoiding infinite loop.
https://github.com/buytenh/ivykis/commit/7190532aca902865ec8e578ac1c23d504f52a75a
=> regression - internal mark mode: infinite loop with old ivykis

modules/diskq/diskq-grammar.ym, modules/diskq/diskq-parser.c, modules/diskq/diskq.c, modules/diskq/diskq.h, modules/hook-commands/hook-commands-parser.c, modules/hook-commands/hook-commands.c, modules/hook-commands/hook-commands.h
This fixes two leaks connected to the `DiskQDestPlugin`.
The first could be triggered during configuration parsing, if the parsing was not successful the `cleanup` function were `log_pipe_unref`, but the `DiskQDestPlugin` has no relationship with the `LogPipe`. It was at least a leak, or arbitrary code execution from random memory.
The second one was easier, the `_free` function of `DiskQDestPlugin` did not called `g_free` on itself.
[edit]
Also the same have been done for hook commands.
=> DiskQDestPlugin was not freed

lib/rewrite/rewrite-expr.c
- this can be misleading when rewrite rule is used without condition,
for example with: set()
=> RewriteExpr: Remove misleading print of result from log_rewrite_queue()

configure.ac, syslog-ng/Makefile.am
At some point we broke the disable-dynamic-linking option. This patch tries to fix this.
I created a jenkins job that can be used to test it:
With master (red):
https://ci.syslog-ng.com/jenkins/job/furiel-test-static-linking-mode/5/
With the patch (green):
https://ci.syslog-ng.com/jenkins/job/furiel-test-static-linking-mode/4/
This job can be started manually together with the other tests in https://ci.syslog-ng.com/jenkins/view/furiel/job/furiel-paranoid/.
@algernon I somewhat agressively modified your patch in #2100, can you please recheck with this pr if you can still compile syslog-ng? My strategy was that libsecret-storage is applied similarly to libeventlog,  so I expect this version would work for you too, but I would like to be sure of it.
=> autotools: linking mode static

configure.ac
libcap will be detected via pkg-config first.
If it fails, the existing fallback detection is used instead.
This change is useful when one wants to compile syslog-ng using a non-system libcap.
`libcap.pc` is not available on all platforms, so the original `AC_CHECK_LIB` detection should not be removed.
=> Extended Linux capabilities detection (pkg-config)

tests/loggen/ssl_plugin/ssl_plugin.c
FreeBSD 11.2 builderror SOCK_STREAM on tests/loggen/ssl_plugin/ssl_plugin.c with syslog-3.16.1 
fix issues #2124 and #2150
=> FreeBSD 11.2 builderror SOCK_STREAM

lib/CMakeLists.txt, lib/Makefile.am, lib/early_ack_tracker.c, lib/late_ack_tracker.c, lib/logsource.c, lib/logsource.h, lib/tests/CMakeLists.txt, lib/tests/Makefile.am, lib/tests/test_window_size_counter.c, lib/window-size-counter.c, lib/window-size-counter.h
@MrAnno : please check whether it supersedes #2045 or not. 
* suspend is set by `log_source_flow_control_suspend`
* suspend is unset by `log_source_wakeup`
* `free_to_send` blocks reading until suspend bit is set or the window size is 0
* when window size was 0 before `log_source_flow_control_adjust` is called, then we call `log_source_wakeup`
* when ack_tracker receives an ACK, then it checks if source is suspended or not (and based on the acknowledge type it makes a decision whether we need to suspend/wakeup the source)
=> Fix suspend race cond

modules/java/native/java_machine.c, modules/java/tools/syslog-ng.conf.example
Once a java is configured, and the JVM is loaded, and it is not possible to safely unload the JVM.
Because there cannot be two or more JVM in one process, the second time syslog-ng tries to create a JVM it wont succeeed.
The plan is to keep the JVM once created as long as syslog-ng is runnig.
Fixes #2163
=> Once java always java

lib/cfg-grammar.y, lib/cfg-tree.c, lib/logwriter.c, lib/str-utils.c, lib/str-utils.h, modules/afsql/afsql-grammar.ym, modules/afsql/afsql.c, modules/csvparser/csvparser-grammar.ym, syslog-ng-ctl/syslog-ng-ctl.c
Release notes:
- syslog-ng-ctl: fixing a memleak
- afsql: normalizing key when checking flags
This can be useful on a rare occasion when user tries to use `dont_create-tables` or dont-create_tables`.
- Normalizing flags in log writer options. This can be useful on a rare occasion when user tries to use `no-multi_line` or `no_multi-line`.
- csvparser: normalizing flags was not supported earlier at all.
Developer notes:
- new token added: normalized_flag that can be used in grammar to replace underscores with hyphens.
- log_flags: just a refactor to use the new normalized_flag token
=> Fix missing normalize flags

CMakeLists.txt, configure.ac, lib/atomic.h, lib/compat/glib.h
Extracted from #2045.
This function was not used only for initialization, because its name deceived others.
The name does not imply being racy, so I've fixed the implementation.
=> Make g_atomic_counter_set() atomic and update minimum glib version to 2.26

scl/linux-audit/linux-audit.conf
Add a new SCL: linux-audit() source. It reads and automatically
parses the Linux audit logs. You can override the file name using
the filename() parameter and the prefix for the created
name-value pairs using the prefix() parameter. Any additional
parameters are passed to the file source.
Example:
```
source s_auditd {
linux-audit(
prefix("test.")
hook-commands(
startup("auditctl -w /etc/ -p wa")
shutdown("auditctl -W /etc/ -p wa")
)
);
};
```
=> New linux-audit() source as SCL

modules/basicfuncs/str-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c
Triggered by the mailing list. To calculate the proper prefix length, we divide by the length of the optional padding string (default: <space>) , which leads to crash in case of zero length input.
Rewritten from "TEMPLATE_FUNCTION_SIMPLE" to a state full template. In prepare time, we:
- make the padding length number conversion
- create a helper string with the length of the maximum possible padding.
Thus, the work/message is reduced.
Questions:
- Why do we use `parse_number_with_suffix` to parse the padding width?
- Can we trust in the number of arguments in the "_call" method? (Not existing macros are expanded to empty strings)
=> Fix padding template function

lib/cfg-args.c, lib/cfg-args.h, modules/system-source/system-source.c
system-source: removed container detection from system source,
because changes in kernel code made it unreliable. Since it was
only used for excluding kmsg logs, a new optional "exclude-kmsg()"
option was introduced to make the function user configurable.
Question: Where should we store the const string literal for the option?
Resolves #2156
=> system-source: added exclude_kmsg option instead of container detection

modules/affile/tests/test_wildcard_file_reader.c, modules/affile/wildcard-file-reader.c, modules/affile/wildcard-file-reader.h, modules/affile/wildcard-source.c, modules/affile/wildcard-source.h
The callbacks have to be registered separated, not in the constructor.
New functions are introduced:
- wildcard_file_reader_on_deleted_file_finished
- wildcard_file_reader_on_deleted_file_eof
The wildcard_file_reader_is_deleted is also introduced in order to avoid
direct access of an object member
Signed-off-by: Viktor Juhasz <juhasz.viktor81@gmail.com>
=> WildcardFileReader: the callback registration mechanism is refactored

lib/stats/stats-cluster.c, lib/stats/stats-counter.c, lib/stats/stats-counter.h, lib/stats/stats-query-commands.c, lib/stats/stats-query.c, lib/stats/stats-query.h, lib/stats/tests/test_stats_query.c
During the investigation of #2084, I fixed/refactored a few stats-related things.
This PR contains:
- minor "simplifications" in the implementation of `stats-query`
- a fix for the usage of the format callback of aggregated queries
- a fix for `remove_counter_from_index()`
- a modification in the deallocation of `StatsCounterItem::name`
Questions:
- Why do we use a HashTable (`counter_index`) in `stats-query.c` when we do not call one single lookup function on it? (Only a full iteration is used [linear search])
- This "index" is updated before every query (which requires a full iteration of `stats_cluster_foreach_counter`) call. Does this increase the query performance?
=> Minor stats-query fixes and refactor

lib/tlscontext.c, lib/tlscontext.h, lib/transport/transport-factory-tls.c, lib/transport/transport-factory-tls.h, modules/afsocket/afinet-dest.c, modules/afsocket/afinet-source.c, modules/afsocket/tests/test-transport-mapper-inet.c, modules/afsocket/transport-mapper-inet.c, modules/afsocket/transport-mapper-inet.h
When a TLS session is initiated, the afsocket module passes a
reference to the AFInetDestDriver instance to the TLSSession
structure to use as verification data. Due to the timing of
configuration changes, the driver structure may be freed before
the TLSSession structure, meaning that TLSSession will contain a
dangling pointer to the AFInetDestDriver. The afsocket module may
try to verify the session using the invalid data, which result in
a crash.
This patch adds two extra function pointers to the
TransportMapperInet structure, one that is used to increment the
driver's reference counter when it is passed to the TLSSession,
and one that is called to decrement the driver's reference
counter when the session structure is destroyed. This ensures
that the driver is only freed once there are …
=> afsocket: Add ref-counted TLSVerifier struct

scl/ewmm/ewmm.conf
scl/ewmm/ewmm.conf: added definition of syslog-ng() source
* introduced the syslog-ng() source for ewmm formatted logs
* originally only the syslog-ng() destination was defined here, but in
most cases sources and destinations arrive in pairs, so I just
implemented that
Signed-off-by: Janos SZIGETVARI <jszigetvari@gmail.com>
=> Introduce syslog-ng() source

modules/diskq/diskq-options.c, modules/diskq/diskq.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_reliable_backlog.c
The reliable disk buffer can contain messages in the backlog, and during syslog-ng lifetime it is perfectly fine (by design).
But if there is a message in the backlog when syslog-ng is starting, it is not expected to have message in the backlog, because it should have been acknowledged or rewinded.
As of now it keeps that backlog slot as a sliding window, and message could be stuck there until other message does not replace it. (No message stuck there forever.)
This patch contains 2 things:
* When reliable disk buffer is started, it check if there is a message in the backlog, and moves them back the reliable queue, therefore they are going to be reprocessed again.
* dqtool is extended, so when the `dqtool info` is used with `-d` (debug) option, it also prints extra information: …
=> Reliable disk buffer non-empty backlog

lib/eventlog/src/evtlog.h, lib/eventlog/src/evttags.c, scl/elasticsearch/plugin.conf, scl/hdfs/plugin.conf, scl/kafka/plugin.conf, tests/loggen/loggen_helper.c
- elastic, hdfs, kafka: make client-lib-dir() optional
- loggen: fix strncpy compiler warning
- eventlog: use long long parameter for evt_tag_long()
=> client-lib-dir, loggen, eventlog: minor fixes

lib/cfg-lexer.c
This PR contains equivalent transformations only (I hope so).
Extracted methods:
- `cfg_lexer_lex_next_token()`
- `cfg_lexer_append_preprocessed_output()`
- `cfg_lexer_parse_and_run_block_generator()`
- `cfg_lexer_parse_include()`
- `cfg_lexer_preprocess()`
=> Goodbye "goto relex" (refactor)

.travis.yml, dbld/images/required-apt/all.txt, dbld/images/required-apt/stretch.txt, dbld/images/required-obs/stretch.txt, dbld/images/required-pip/all.txt, dbld/images/required-pip/artful.txt, dbld/images/required-pip/centos6.txt, dbld/images/required-pip/centos7.txt, dbld/images/required-pip/devshell.txt, dbld/images/required-pip/jessie.txt, dbld/images/required-pip/stretch.txt, dbld/images/required-pip/trusty.txt, dbld/images/required-pip/xenial.txt, dbld/images/stretch.dockerfile, requirements.txt
Some packages (e.g.  pylint 2.0.0) declare package tags that are not
supported by ancient setuptools packages, that are available in centos 6 and
7, therefore use fixed versions on ancient distributions.
=> dbld: fix pip package versions on older Distro releases

scl/sudo/sudo.conf
sudo may generate some log messages through libpam, drop those messages.
=> sudo: filter out incorrectly parsed logs

scl/ewmm/ewmm.conf
syslog-ng is just an alias for the ewmm destination there's no syslog-ng()
source and shouldn't be one, even if it sounds asymmetrical.
Rationale:
- on the source side we want ewmm to be processed on the same channel as
everything else is coming in.
- we already created default-network-drivers() for exactly this use-case
- the ewmm() source below is a pretty limited use-case that is probably
only good enough for testing.
- with this, we have symmetry: ewmm() source and destination. And we
also reserved the name "syslog-ng()" to send messages to an actual
syslog-ng instance.
if someone needs a different use-case, the recommended way is to construct
the source plus parsing bits at the configuration file level, as that
use-case is not generic enough.
Signed-off-by: Balazs Scheidler …
=> scl/ewmm: rename syslog-ng() source to ewmm()

modules/diskq/dqtool.c
The `dqtool` currently does not print out the backlog items from the disk queue file.
This patch allow `dqtool` to use the backlog, and rewinds messages (only in memory), so `dqtool` could access them.
=> diskq: dqtool cat print backlog items
