syslog-ng/syslog-ng

- contrib/README.syslog-debun
- contrib/syslog-debun
Debug Bundle generator script for Syslog-NG
> syslog-ng debug bundle generator script & README

- .gitmodules
- modules/afamqp/afamqp.c
Relevant modifications to the code according to the API were added.
Signed-of-by: Gergő Nagy <gergo.nagy@balabit.com>
> RabbitMQ module changed to the upstream.

- .gitmodules
- modules/afamqp/afamqp.c
Relevant modifications according to the API fixed.
> RabbitMQ submodule changed to the upstream.

- lib/logmsg.c
> logmsg: when ack is not requested do not call the ack function

- lib/control/control.c
- lib/stats/stats-counter.c
- lib/stats/stats-counter.h
This pull request should fix #441.
> stats-counter: reset will not affect the stored counters

- lib/hostname.c
> hostname: fix potential abort in case the localhost name cannot be detected

- modules/java/Makefile.am
> java: fixed Makefile.am: resolve dependencies by hand

- modules/riemann/riemann-grammar.ym
- modules/riemann/riemann-parser.c
- modules/riemann/riemann.c
- modules/riemann/riemann.h
> riemann: Add support for TLS connections

- configure.ac
- modules/python/Makefile.am
> configure: add --disable-python option to configure

- configure.ac
> configure: systemd support fixed

- lib/messages.c
- lib/messages.h
- syslog-ng/main.c
See issue #319 for details.
fixes #319
> Startup debugging implemented

- tests/loggen/loggen.c
This patch adds local specific timezone offsets to syslog-protocol log messages. The original
solution was to include the +02:00 string in all cases.
Fixes #362
> loggen: use the proper timezone offset in the generated message

- contrib/README.syslog-debun
- contrib/syslog-debun
* enhanced process information gathering
* syscall tracing (strace/truss)
* enhanced configuration gathering (--preprocess-into)
* selinux related information gathering
* debian/redhat recognition when lsb_release is not available
* solaris information gathering enhancements (sysdef, kstat, showrev, release)
* get information about syslog-ng svr4 solaris packages, if possible
Signed-off-by: PÁSZTOR György <gyorgy.pasztor@balabit.com>
> syslog-debun: several enhancements

- configure.ac
- doc/man/syslog-ng.8.xml
- modules/afprog/afprog.c
- modules/afsocket/transport-unix-socket.c
- modules/afsocket/unix-credentials.h
I checked the latest feature release (`3.7.0beta2` june 26) and cherry picked all commits from `3.6/master` to this branch (after june 26).
Fixes #599
> Forward fixes from the maintenance branch

- modules/afsocket/afsocket-dest.c
And, thus, do not replace writer when protocol not changed during reload.
> afsocket: replace writer only when protocol changed during reload

- modules/afsmtp/afsmtp-grammar.ym
- modules/afsmtp/afsmtp.c
- modules/afsmtp/afsmtp.h
request: #197
closes#197
fixes #197 
Signed-off-by: Kristof Havasi <kristof.havasi95@gmail.com>
> afsmtp: recipients are templatable now.

- lib/tlscontext.c
- lib/tlscontext.h
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
This is a backport of #457 to 3.6/master. Closes #623.
> ssl-options backport for 3.6

- lib/logmsg.c
- lib/logwriter.c
- modules/systemd-journal/journal-reader.c
This is actually not my PR, I've just create it from Bazsi's branch.
[containing fixes for the journal replay issue for 3.6]
> 3.6/f/fix journal replay

- modules/python/python-dest.c
The path taken by if (!_py_invoke_is_opened(self)) {...} missed it.
> modules/python/python-dest.c: always release GIL

- modules/python/python-debugger.c
> modules/python: acquire GIL for calls to the C API

- modules/python/python-debugger.c
- modules/python/python-debugger.h
- modules/python/python-plugin.c
This extends https://github.com/balabit/syslog-ng/pull/711 with hotfix for runtime error
> python: support python3 library

- contrib/syslog-debun
* eliminate bashisms (not yet complete!) and become more posix shell compatible
* basic FreeBSD support
* basic HP-UX support
> contrib/syslog-debun: portability improvements and fixes

- tests/functional/sngtestmod.py
This patch fixes up a func-test failure.
> func_test: fix up test_python

- lib/cfg-grammar.y
- lib/cfg-lexer.c
- lib/cfg-lexer.h
- lib/plugin.c
> Revert 740 f/fix lexer

- modules/syslogformat/syslog-format.c
Fixes the broken master (it's December...)
Signed-off-by: MÓZES Ádám István <adam.mozes@balabit.com>
> syslog-format: fix BSD timestamp parsing

- configure.ac
This PR fixes the compilation error in the master branch. 
> Fix compile error in Travis

- lib/template/macros.c
This is a cleaned up version of pr #810 submitted by @flaviommedeiros . He asked me to squash the patches and rebase it to master. 
I've added his signed-off-by as well. Flavio, please confirm (just an ok should be enough) that you understand that this means that you have all rights to submit this patch as described here: https://github.com/balabit/syslog-ng/blob/master/CONTRIBUTING.md
A suggestion to compile entire statements and expressions, as suggested by code style guidelines from the Linux Kernel and practitioners.
https://git.kernel.org/cgit/linux/kernel/git/torvalds/linux.git/tree/Documentation/CodingStyle#n892
https://www.cqse.eu/en/blog/living-in-the-ifdef-hell/
It might improve code understanding, maintainability and error-proneness.
Signed-off-by: Flavio Medeiros …
> templates: clean up $SOURCEIP macro expansion

- tests/functional/test_file_source.py
- tests/functional/test_filters.py
- tests/functional/test_input_drivers.py
- tests/functional/test_performance.py
- tests/functional/test_python.py
- tests/functional/test_sql.py
> functest: bump config version numbers to 3.8

- modules/afprog/afprog.c
- modules/afprog/afprog.h
Fixes: #863 
Signed-off-by: László Várady <laszlo.varady@balabit.com>
> afprog: fix afprogram_dd_set_keep_alive() linkage

- modules/java-modules/Makefile.am
- modules/java/Makefile.am
Fixes #640
Reported-by: Peter Czanik <peter.czanik@balabit.com>
> java: export GRADLE_OPTS environment variable

- modules/afamqp/afamqp.c
This is a backport PR, the original pull request can be found here: #811
> Improve error handling in amqp

- debian/syslog-ng.conf.example
> Update debian example configuration file

- modules/java-modules/kafka/build.gradle
Add Kafka 0.9.0.0 support.
Fixes: #839
> Add support of Kafka 0.9.0.0

- modules/java-modules/common/src/main/java/org/syslog_ng/logging/SyslogNgInternalLogger.java
Backport of https://github.com/balabit/syslog-ng/pull/961/
> Backport of "Fix java logger"

- modules/affile/affile-source.c
This is an attempt at fixing #990
> 3.7/f/file source reopen on error

- autogen.sh
- configure.ac
- lib/compat/Makefile.am
- lib/compat/time.c
- lib/logmsg/logmsg.c
- m4/check_java_support.m4
Fixes: #805
Fixes: #808 
Partial fix for #821
Related to #937
> Prepare OS X support

- libtest/template_lib.c
- libtest/testutils.c
- libtest/testutils.h
- modules/kvformat/kv-parser.c
- modules/kvformat/kv-scanner.c
- modules/kvformat/tests/test_kv_scanner.c
- modules/syslogformat/syslog-format.c
> F/kv parser robustness improvements, drop empty keys, better test coverage

- lib/logmpx.c
The last_delivery logic kind-of breaks the ack counting logic for junctions
that have branches that modify the LogMessage.
This causes aborts during execution like this:
ERROR:../lib/logmsg.c:1510:log_msg_refcache_stop: assertion failed: ((logmsg_cached_acks < LOGMSG_REFCACHE_BIAS - 1) && (logmsg_cached_acks >= -LOGMSG_REFCACHE_BIAS))
This patch resolves github issue #610.
> logmpx: remove last_delivery logic

- dev-utils/plugin_skeleton_creator/create_plugin.sh
- dev-utils/plugin_skeleton_creator/plugin_template_CMakeLists.txt
- dev-utils/plugin_skeleton_creator/plugin_template_Makefile.am
- dev-utils/plugin_skeleton_creator/plugin_template_grammar.ym
- dev-utils/plugin_skeleton_creator/plugin_template_parser.c
- dev-utils/plugin_skeleton_creator/plugin_template_parser.h
- dev-utils/plugin_skeleton_creator/plugin_template_plugin.c
- tests/copyright/policy
This PR continues and hopefully finishes the work started in #270.
Additional changes to the previous PR:
- add copyright to the script
- the generated plugin include the current year and the git user name of the author
- add CMakeLists.txt template to the generator
> plugin skeleton creator

- lib/Makefile.am
Fixes: #1064
Please, do not merge this until the questions on #1064 has not been answered.
> lib/Makefile.am: fixed ivykis CFLAGS

- modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/esnative/ESNodeClient.java
> elasticsearch_v2: set default path.home for node client

- modules/java-modules/elastic-v2/build.gradle
> elastic-v2: mode http: fixed slf4j StaticLoggerBinding issue

- configure.ac
Fixed issue: #1191 
Signed-off-by: SZALAY Attila sasa@debian.org
> Fixed the case when system librabbitmq does not found

- configure.ac
fixes issue: #1189 
Signed-off-by: SZALAY Attila <sasa@debian.org>
> Fixed the name of the libmongoc pc file

- lib/compat/time.c
- lib/compat/time.h
> Fix time compat library on Mach-based distributions

- modules/java-modules/elastic-v2/build.gradle
Signed-off-by: Zoltan Pallagi <pzoleex@gmail.com>
> (elasticsearch) build.gradle: Updated libs to 2.4.0

- modules/systemd-journal/journald-subsystem.c
Before v209 journal functions are in libsystemd-journal, then they merged into
libsystemd.so .
more information:
https://lists.freedesktop.org/archives/systemd-devel/2014-February/017146.html
> systemd-journal: journal functions can be located in two libraries

- Makefile.am
- configure.ac
- lib/cfg-grammar.y
- lib/cfg-lexer.c
- lib/cfg-tree.c
- lib/cfg-tree.h
- modules/add-contextual-data/CMakeLists.txt
- modules/add-contextual-data/Makefile.am
- modules/add-contextual-data/add-contextual-data-grammar.ym
- modules/add-contextual-data/add-contextual-data-selector.h
- modules/add-contextual-data/add-contextual-data-template-selector.c
- modules/add-contextual-data/add-contextual-data-template-selector.h
- modules/add-contextual-data/add-contextual-data.c
- modules/add-contextual-data/add-contextual-data.h
- modules/add-contextual-data/context-info-db.c
- modules/add-contextual-data/context-info-db.h
- modules/add-contextual-data/csv-contextual-data-record-scanner.c
- modules/add-contextual-data/tests/Makefile.am
- modules/add-contextual-data/tests/test_context_info_db.c
- modules/add-contextual-data/tests/test_selector.c
- syslog-ng-add-contextual-data.pc.cmake
- syslog-ng-add-contextual-data.pc.in
This PR contains
* fixes of prefix to be consistent with existing prefix functionality
* selector as a plugin to make it easier to add new selectors
> Refactor add-contextual-data

- ISSUE_TEMPLATE.md
Sometimes vital information is missing from issues. To avoid unnecessary roundtrips in issue fixing this template is introduced.
> ISSUE_TEMPLATE: add one to make issue handling more effective

- lib/plugin.c
> plugin: debug instead of error when unable to open

- lib/template/tests/test_template.c
> template: followup version changes in unit test

- modules/systemd-journal/journal-reader.c
> journal-reader: show warning message only for older config versions

- modules/afsql/afsql.c
Fixes #1258
Signed-off-by: ddaa <0xddaa@gmail.com>
> afsql: Initialize terminate flag

- .travis.yml
- autogen.sh
> autogen.sh: fix typo in the name of "skip_submodules"

- debian/Makefile.am
- debian/changelog
- debian/rules
- debian/syslog-ng-core.NEWS
- debian/syslog-ng.conf
> debian: preparations for 3.9.1

- modules/kvformat/kv-scanner.c
- modules/kvformat/tests/test_kv_scanner.c
this should fix the issues pointed out in #1282
> Kv scanner allow using space as pair separator

- lib/stats/stats-query-commands.c
- lib/stats/stats-query.c
- lib/stats/stats-query.h
- lib/stats/tests/test_stats_query.c
These changes were required by the upcoming monitoring source.
> Change interface of stats query to enable formatting and returning different outputs

- modules/python/python-helpers.c
- modules/python/python-logparser.c
This branch starts from #1382 .
> Python parser init deinit fixes

- contrib/syslog-debun
* platform support extensions like AIX, SuSE and Slackware Linux
* enhance the capabilities in case of already supported platformas (Solaris, HPUX)
* extended and improved information gathering (startup scripts)
* refactoring of code
* bug fixes
> Update and extend syslog-debun's capabilities

- lib/cfg.c
- lib/logproto/logproto-buffered-server.c
> logproto: fix invalid state handling

- .gitmodules
Adding ignore = dirty to .gitmodules for sake of convenience
Signed-off-by: Antal Nemes antal.nemes@balabit.com
> Ignore "dirty" changes in submodules

- modules/affile/file-reader.c
> affile: fix stats source for pipes

- lib/stats/stats-query.c
In case of paralell querying through stats_query a race could be possible when editing the index records. But not anymore! :)
> stats-query: lock index before editing it

- lib/stats/stats-cluster.c
- lib/stats/stats-query.c
- lib/stats/tests/test_stats_cluster.c
- lib/stats/tests/test_stats_query.c
Please note that changes in #1478 should be followed up after merging this.
> stats-query: change separator to ; && follow-up tests

- modules/basicfuncs/str-funcs.c
- modules/basicfuncs/tests/test_basicfuncs.c
- Fix remaining trailing whitespace
- Add boundary check when it needed
- And small refactors
> Improve strip template function

- contrib/Makefile.am
Closes: https://github.com/balabit/syslog-ng/issues/1415
> Add debun script and doc to release tgz

- modules/add-contextual-data/add-contextual-data.c
The context_info_db is shared across add-contextual-data instances, so the first init checking method was a bad idea, because the selector's init was called only first time, and it was missing for the cloned ones.
Now it is refactored to do the init phases step-by-step.
> add-contextual-data: fix multiple init error

- lib/filter/filter-call.c
- lib/filter/filter-expr.h
- lib/filter/filter-pipe.c
- lib/filter/filter-pipe.h
- lib/filter/tests/Makefile.am
- lib/filter/tests/test_filters_statistics.c
- lib/logpipe.h
- lib/parser/parser-expr.c
- lib/parser/parser-expr.h
- lib/stats/stats-cluster-logpipe.c
- lib/stats/stats-cluster-logpipe.h
- lib/stats/stats-cluster.c
- lib/stats/stats-cluster.h
- modules/csvparser/tests/Makefile.am
- modules/csvparser/tests/test_csvparser_statistics.c
- modules/kvformat/kv-parser.c
Discarded statistics counter for parsers.
Matched, not matched statistics counters for filters.
> Filter, Parser: discarded, matched, not matched messages statistics

- lib/logthrdestdrv.c
PR: https://github.com/balabit/syslog-ng/pull/1464
introduced a regression, when the worker instantly drops a message
(returns with WORKER_INSERT_RESULT_DROP),
the same error message is written as if it was dropped due to multiple
retries failure.
For example in case of invalid ttl setting for riemann destination:
like: ttl("string")
"2017-05-24T14:00:12.709410] Multiple failures while sending message to
destination, message dropped; driver='d_riemann#0', number_of_retries='3'"
This is changed for:
"[2017-05-24T14:30:56.081535] Message dropped while sending message
to destinaton; driver='d_riemann#0'"
> logthrdestdrv: regression: wrong error message when dropping message

- lib/stats/stats-query-commands.c
- lib/stats/stats-query.c
- Invalid write
- Memory leak
- view key corruption
> written counters: bugfixes

- lib/gprocess.c
The reason why environ is copied during g_process_set_argv_space so to be
able to overwrite process title in ps/top commands to
supervisor. In bsd there is setproctitle call which solve this,
but currently it is not available for linux.
The problem is that modules can add their own env variables to the
list, which must not be freed here, otherwise it would result
double free (e.g some version of Oracle Java). One might also would
try to track which environment variables are added by syslog-ng,
and free only those. There is still a problem with this, **environ
itself cannot be freed in some cases. For example libcurl registers
an at_exit function which needs an environment variable, that would
be freed here before at_exit is called, resulting in invalid read.
As this leak does not cause …
> g_process_finish: reverting attempt to fix memleak

- modules/diskq/logqueue-disk-non-reliable.c
- modules/diskq/logqueue-disk-reliable.c
> diskq: set the type

- modules/affile/affile-common.h
- modules/affile/affile-dest.c
- modules/affile/file-reader.c
- modules/affile/tests/test_affile_open_file.c
- modules/affile/wildcard-source.h
> Fix compilation error on BSD

- modules/systemd-journal/journal-reader.c
> systemd-journal: sd_journal_xxx does not set errno but returns (-errno)

- doc/Makefile.am
- doc/man/.gitignore
- doc/man/dqtool.1.xml
- doc/man/loggen.1.xml
- doc/man/pdbtool.1.xml
- doc/man/syslog-debun.1.xml
- doc/man/syslog-ng-ctl.1.xml
- doc/man/syslog-ng.8.xml
- doc/man/syslog-ng.conf.5.xml
- doc/man/update-manpages.sh
- tgz2build/rules
Using the man pages from [official admin guide](https://github.com/balabit/syslog-ng-ose-guides/).
> Update manpages from v3.3 to v3.10

- modules/dbparser/groupingby.c
This way the trigger can use the already accumulated set of messages.
> grouping-by: pass the entire context to the trigger() exception

- dbld/images/xenial/dev-dependencies.txt
> dbld/xenial: add libmaxminddb-dev

- .travis.yml
Fixes CI in #1561
See https://github.com/balabit/syslog-ng/pull/1561#issuecomment-314820563
> travis: disable parallel make install

- ISSUE_TEMPLATE.md
- contrib/README.syslog-ng-debun
- contrib/syslog-ng-debun
* Added -r option to avoid accidental invokation
* Edited ISSUE_TEMPLATE.md to reference syslog-ng-debun
* Extended stats gathering
* Updated syslog-ng-debun's README
> Syslog-ng-debun improvements

- Mk/Makefile.am
- Mk/lex-rules.am
- cmake/Modules/GenerateYFromYm.cmake
- lib/CMakeLists.txt
- lib/Makefile.am
- lib/merge-grammar.py
- tests/build-log-cflags-propagation.sh
Just because there were a TODO item about it, and I think this one is much more readable.
> Lib: rewrite merge-grammar script from Perl to Python

- modules/systemd-journal/journal-reader.c
- modules/systemd-journal/journald-subsystem.c
- modules/systemd-journal/journald-subsystem.h
- modules/systemd-journal/tests/journald-mock.c
This reverts commit 194b85ce8ab70e41d1a3c2efa2069334ae4fc3df, reversing
changes made to 67876774d268d7ecc2d2e22533dc1c10b2289c80.
Fixes: #1587
> Revert "Merge pull request #1571 from faithlesstomas/issue1570"

- ISSUE_TEMPLATE.md
- doc/Makefile.am
- doc/man/dqtool.1.xml
- doc/man/loggen.1.xml
- doc/man/pdbtool.1.xml
- doc/man/syslog-ng-ctl.1.xml
- doc/man/syslog-ng-debun.1.xml
- doc/man/syslog-ng.8.xml
- doc/man/syslog-ng.conf.5.xml
> Manpages: update to 3.11

- modules/afamqp/afamqp-grammar.ym
- modules/afamqp/afamqp-parser.c
- modules/afamqp/afamqp.c
- modules/afamqp/afamqp.h
> Hi, this reopen (https://github.com/balabit/syslog-ng/pull/1355) that I closed because I've done a mess with my branch :/
> 
> Anyway, I've updated params name's according to discussion with @presidento in the old PR  
> 
> Thank you for your time.
Original author: Giuseppe D'Anna @LarryWax 
Original PR: #1519
> Add SSL support to AMQP module

- lib/cfg-lexer.c
> cfg-lexer: fix plugin load

- modules/java-modules/Makefile.am
- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsDestination.java
- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsFile.java
- modules/java-modules/hdfs/src/main/java/org/syslog_ng/hdfs/HdfsOptions.java
- scl/hdfs/plugin.conf
Don't merge it, needs more test
> HDFS: support macro in filename

- contrib/syslog-ng-debun
* Added hash values for all files contained within the bundle to easily detect fiddling and file deletions
* Added disk space check to avoid disk full scenarios caused by queue files in the syslog-ng var directory
> hash checksums and free space check

- tests/build-log-cflags-propagation.sh
> lib/ivykis: update to 0.42

- scl/Makefile.am
- scl/windowseventlog/plugin.conf
- scl/windowseventlog/windowseventlog.conf
- scl/windowseventlog/windowseventlog.xml
Here are my windows eventlog patterndb related modifications.
- I'm not sure about the place of the PatternDB XML file.
- I've only added the new SCL directory to `Makefile.am`, but not to `CMakeLists.txt`. Is it OK?
- I'm stuck with the deployment of the PatternDB XML file. How should I deploy it to `/etc/patterndb.d/...`?
- I'm not sure how I should integrate executing PatternDB test (`pdbtool test --validate ...`)
> Windows eventlog pattern parser

- .travis.yml
Signed-off-by: Kokan <peter.kokai@balabit.com>
> Travis: cache apt installs

- dev-utils/plugin_skeleton_creator/plugin_template_Makefile.am
- modules/Makefile.am
- modules/snmptrapd-parser/Makefile.am
- modules/stardate/Makefile.am
- modules/xml/Makefile.am
>dev-utils: remove "mod-file" from plugin skeleton creator
>
>This is just a leftover from affile.
> Minor fix for plugin skeleton creator

- lib/afinter.c
1) Is there any configured internal source in the config
2) Does the configured internal source free to send or not
If there isn't configured internal source,
the messages shouldn't be stored in the internal queue,
because there is no one to read them.
But if there is a configured internal source,
the messages should be stored in the internal queue,
independently from the queue source is ready to work or not.
There is a side effect of this patch, that if there was no
internal source, before reload, but after reload it exists,
then the internal messages generated before reload will be lost
Fixes: #1494
Signed-off-by: Juhász Viktor <juhasz.viktor81@gmail.com>
> afinter: current_internal_source was used for 2 different things

- lib/filter/filter-expr.c
- lib/filter/filter-in-list.c
- lib/filter/filter-netmask.c
- lib/filter/filter-netmask6.c
- lib/filter/filter-pri.c
- lib/filter/filter-re.c
- lib/filter/filter-tags.c
- modules/dbparser/dbparser-grammar.ym
- modules/dbparser/groupingby.c
These are fixes to the grouping-by parser that @pzoleex has found, please do not merge until kira is updated with the testcases.
> Grouping by fixes

- modules/afsocket/afsocket-dest.c
Based on the comments of @lbudai at https://github.com/balabit/syslog-ng/pull/1723#issuecomment-339361112.
This is only refactor, the behavior should be identical as the previous implementation.
> afsocket: simplify restoring writer from reload cache

- modules/python/python-value-pairs.c
There is a reference leak in python destination when fields are added
to the message through value pairs. The leak happens per message, so
the memory usage of syslog-ng can increase considerably in a short
period of time.
Also, original implementation led to crash when python destination was fed with binary data (for example loggen -U). This patch also checks if the conversion from char*/long to pyobj was successful.
Example configuration:
```
@version: 3.13
destination d_python {
python(class("Foo") value-pairs(scope(everything)));
};
log {
source{tcp(port(10514));};
destination(d_python);
flags(flow-control);
};
python {
import sys
class Foo(object):
def init(self, options):
return True
def send(self, msg):
return True
};
```
Fixes: https://github.com/balabit/syslog-ng/issues/1253
> python-dest: value-pairs reference leak

- syslog-ng/main.c
Someone might want to check what is the current config version.
@mitzkia : this is what we talked about yesterday ;)
> syslog-ng: extend '--version' with config version

- modules/afmongodb/tests/test-mongodb-config.c
fixes: #1653
Signed-off-by: SZALAY Attila <sasa@ubainba.hu>
> afmongodb: make test compatible with mongoc 1.7

- packaging/debian/Makefile.am
- packaging/debian/control
- packaging/debian/syslog-ng-core.install
- packaging/debian/syslog-ng-mod-json.install
- packaging/debian/syslog-ng-mod-json.postinst
- packaging/debian/syslog-ng-mod-json.postrm
- packaging/debian/syslog-ng-mod-json.preinst
- packaging/debian/tools/list-modules.sh
> debian: json is a core dependency

- lib/cfg-args.c
> cfg-args: revert _resolve_unknown_blockargs_as_varargs()

- lib/cfg-grammar.y
> Report unknown context in "block" definitions

- lib/rewrite/rewrite-expr.c
replace init calling to helper function calling
> rewrite: refactor FilterExprNode->init

- modules/pseudofile/pseudofile.c
Signed-off-by: Shen-Ta Hsieh <ibmibmibm.tw@gmail.com>
> pseudofile: fix potential fd leak on write error occurs

- lib/persist-state.c
Signed-off-by: Shen-Ta Hsieh <ibmibmibm.tw@gmail.com>
> persist-state: fix potential fd leak on file size too large

- tests/loggen/loggen.c
Signed-off-by: Shen-Ta Hsieh <ibmibmibm.tw@gmail.com>
> loggen: fix potential leak on strdup variable

- .travis.yml
The install repository link is outdated.
> Travis outdated obs link

- modules/http/Makefile.am
- modules/python/Makefile.am
- modules/riemann/Makefile.am
> Consistent dist tarball generation (http, riemann, python)

- modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/client/http/ESHttpClient.java
- modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/http/HttpBulkMessageProcessor.java
- modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/http/HttpMessageProcessor.java
- modules/java-modules/elastic-v2/src/main/java/org/syslog_ng/elasticsearch_v2/messageprocessor/http/HttpSingleMessageProcessor.java
@faxm0dem : could you check this?
#1342 is conflicting, so I'm open this new PR
(if you tested my changes, you can rebase your branch against master and then cherry pick my commit ;) )
> Elastic 2 fix bulk silent drop

- lib/compat/tests/Makefile.am
- lib/value-pairs/tests/Makefile.am
> lib: build shouldn't fail on systems  where criterion is not available

- modules/python/sngexample.py
Resolves #1896
Signed-off-by: videet <videetssinghai@gmail.com>
> Bug 1896 fixed

- README.md
* The request change came from doc team
> [WIP]Readme: Minor updates in README.md file

- .travis.yml
- dbld/bootstrap
- dbld/deb
- dbld/images/centos6.dockerfile
- dbld/images/centos7.dockerfile
- dbld/images/required-apt/all.txt
- dbld/images/required-yum/all.txt
- dbld/rules
- dbld/shell
- dbld/tarball
- requirements.txt
These are the dbld changes that I've backed out from #1913. This one should go in first, the other depends on this.
The changes are pretty minor and self-explanatory, however the patches are pretty independent, so it might be easier to review them by patches and not as a whole.
> Dbld refinements

- lib/cfg-grammar.y
- lib/gsockaddr.c
- lib/gsockaddr.h
- lib/logproto/logproto-client.h
- lib/logproto/logproto-server.h
- lib/logreader.c
- lib/logwriter.c
- lib/transport/transport-socket.c
- lib/transport/transport-tls.c
- modules/afsocket/afsocket-dest.c
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-source.c
- handshake for LogReader and LogWriter
- grammar-based LogProto plugin support
- minor changes and additional utility functions
> Extend LogProto

- .travis.yml
- Makefile.am
- configure.ac
- lib/cfg.c
- lib/gprocess.c
- lib/mainloop.c
- lib/scanner/kv-scanner/kv-scanner.c
- lib/secret-storage/tests/test_secret_storage.c
- lib/service-management.c
- lib/value-pairs/tests/test_value_pairs.c
- modules/add-contextual-data/add-contextual-data-filter-selector.c
- syslog-ng-ctl/syslog-ng-ctl.c
> declaration related warnings fixes

- dbld/images/devshell-apt/all.txt
- dbld/images/devshell-apt/artful.txt
- dbld/images/devshell-pip/all.txt
- dbld/images/devshell.dockerfile
- dbld/images/helpers/functions.sh
- dbld/images/required-apt/all.txt
- dbld/make
- dbld/rules
- dbld/shell
Another set of dbld improvements that I've encountered while doing all my development work using the docker containers. Mostly small stuff. Tarball generation should not be risky, The only change that could affect that is that I've added joe and netcat to the apt based images.
> Dbld refinements2

- modules/afsocket/afsocket-source.c
This patchset contains a fix initialization related crash in afsocket.
> Fix possible crash in afsocket

- Makefile.am
- lib/block-ref-grammar.ym
- lib/cfg-grammar.y
- lib/cfg-lexer-subst.c
- lib/cfg-parser.c
- lib/logproto/logproto-multiline-server.c
- lib/pragma-grammar.ym
- lib/str-repr/decode.c
- lib/template/macros.c
- lib/template/repr.c
- lib/template/templates.c
- modules/afamqp/afamqp.c
- modules/afprog/afprog.c
- modules/afsocket/afsocket-dest.c
- modules/afsocket/afsocket-source.c
- modules/afsocket/socket-options-inet.c
- modules/afuser/afuser-grammar.ym
- modules/diskq/diskq-grammar.ym
> Switch case default warning fixes

- Mk/subdir.mk
- lib/logmsg/logmsg.c
- lib/logmsg/logmsg.h
- lib/mainloop.c
- modules/python/CMakeLists.txt
- modules/python/Makefile.am
- modules/python/compat/compat-python-v2.c
- modules/python/compat/compat-python-v3.c
- modules/python/compat/compat-python.h
- modules/python/pylib/pylintrc
- modules/python/pylib/syslogng/debuggercli/tests/test_commandlinelexer.py
- modules/python/pylib/syslogng/debuggercli/tests/test_lexer.py
- modules/python/pylib/syslogng/debuggercli/tests/test_templatelexer.py
- modules/python/python-debugger.c
- modules/python/python-dest.c
- modules/python/python-global-code-loader.c
- modules/python/python-global-code-loader.h
- modules/python/python-grammar.ym
- modules/python/python-helpers.c
- modules/python/python-helpers.h
- modules/python/python-logmsg.c
- modules/python/python-logmsg.h
- modules/python/python-logparser.c
- modules/python/python-main.c
- modules/python/python-main.h
- modules/python/python-plugin.c
- modules/python/python-tf.c
- modules/python/python-value-pairs.c
- modules/python/tests/test_python_logmsg.c
This one improves the Python API by adding exceptions to the error paths. This branch depends on #1913 to get in first.
It is an alternative implementation to #1920
> Python logmsg exceptions

- lib/cfg-lexer.c
- lib/cfg-lexer.h
- lib/tlscontext.c
- lib/tlscontext.h
- lib/transport/transport-tls.c
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/tests/test-transport-mapper-inet.c
- scl/default-network-drivers/plugin.conf
- scl/syslog-ng.conf
This should fix #1945 
@lbudai @MrAnno please review the SSL piece, as it might somewhat be questionable, but I am open for suggestions.
> Fix default network drivers

- lib/logwriter.c
- modules/afsocket/afinet-dest.c
- modules/afsocket/afinet-dest.h
- modules/afsocket/afsocket-dest.c
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-parser.c
> afsocket: port basic client side failover functionality

- scl/default-network-drivers/plugin.conf
* replace channels with if-else in SCL
> default-network-drivers: Use if-else statements

- lib/tests/test_parse_number.c
- lib/tests/test_string_list.c
- lib/tests/test_type_hints.c
These unit tests were rewritten based on criterion framework:
test_parse_number
test_string_list
test_type_hints
> Re-write some unit tests based on criterion framework

- CMakeLists.txt
- Makefile.am
- configure.ac
- tests/loggen/CMakeLists.txt
- tests/loggen/Makefile.am
- tests/loggen/file_reader.c
- tests/loggen/file_reader.h
- tests/loggen/loggen.c
- tests/loggen/loggen.md
- tests/loggen/loggen_helper.c
- tests/loggen/loggen_helper.h
- tests/loggen/loggen_plugin.c
- tests/loggen/loggen_plugin.h
- tests/loggen/logline_generator.c
- tests/loggen/logline_generator.h
- tests/loggen/socket_plugin/CMakeLists.txt
- tests/loggen/socket_plugin/Makefile.am
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/CMakeLists.txt
- tests/loggen/ssl_plugin/Makefile.am
- tests/loggen/ssl_plugin/ssl_plugin.c
Loggen has been splitted into smaller chunks and prepared to
support plugins which can implement any further protocol
See technical details in loggen.md file
> Loggen refactor

- packaging/debian/syslog-ng-core.install
> Fix deb package build issue caused by new loggen

- tests/loggen/loggen_helper.c
- tests/loggen/logline_generator.c
- fix undeclared function `gettimeofday()`
- fix OpenSSL 1.1 support 
@norberttak
> Loggen refactor fixes

- packaging/debian/syslog-ng-core.install
> Add missing loggen plugin files to deb package

- lib/transport/transport-factory-id.c
- lib/transport/transport-factory-registry.c
- lib/transport/transport-factory-registry.h
https://developer.gnome.org/glib/2.32/glib-Hash-Tables.html#g-hash-table-insert
> multitransport: older glib support

- configure.ac
- tests/loggen/loggen.c
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
This PR is about a fix for bug #2073 and add some error messages in case of number of activated plugins is not 11.
> Fix loggen plugin handling

- lib/transport/multitransport.c
- lib/transport/transport-factory-tls.c
- lib/transport/transport-factory-tls.h
> multitransport: keep  I/O condition synced

- packaging/debian/syslog-ng-core.install
- tests/loggen/socket_plugin/Makefile.am
- tests/loggen/ssl_plugin/Makefile.am
This PR is to fix package generation related errors around loggen plugins.
> Loggen packaging

- modules/confgen/confgen-plugin.c
> confgen: fix reading the output of the program

- lib/tlscontext.c
- lib/tlscontext.h
- lib/transport/transport-factory-tls.c
- modules/afsocket/transport-mapper-inet.c
> tlscontext: make TLSContext refcounted

- modules/dbparser/tests/CMakeLists.txt
- modules/dbparser/tests/Makefile.am
- modules/dbparser/tests/test_parsers.c
- modules/dbparser/tests/test_parsers_e2e.c
- modules/dbparser/tests/test_patterndb.c
- modules/dbparser/tests/test_patterndb.h
Rewrite patternDB test cases based on criterion
> Rewrite patternDB test cases based on criterion

- lib/logsource.c
> OSX warning elimination

- scl/cisco/plugin.conf
Jun 14 11:57:27 PM.685 UTC :  %UC_LOGIN-4-AuthenticationFailed: %[Login Date/Time=06/15/2018 at 09:57:27][Login IP Address/Hostname=10.25.1.16][Login Interface=cucm-uds][Login UserID=POBAR][App ID=Cisco Tomcat][Cluster ID=][Node ID=cucmsub-prd-t2]: Login Authentication failed.
> cisco: add parsing of Cisco unified call manager

- tests/loggen/file_reader.h
- tests/loggen/loggen.c
- tests/loggen/loggen_helper.c
- tests/loggen/loggen_helper.h
- tests/loggen/loggen_plugin.h
- tests/loggen/logline_generator.c
- tests/loggen/logline_generator.h
- tests/loggen/socket_plugin/socket_plugin.c
- tests/loggen/ssl_plugin/ssl_plugin.c
> Loggen minor fixes

- lib/CMakeLists.txt
- lib/Makefile.am
- lib/atomic-gssize.h
- lib/compat/glib.h
- lib/stats/stats-cluster.c
- lib/stats/stats-counter.h
- lib/stats/stats.c
- lib/tests/CMakeLists.txt
- lib/tests/Makefile.am
- lib/tests/test_atomic_gssize.c
- modules/diskq/tests/test_diskq_full.c
- tests/unit/test_logqueue.c
Motivation: sometimes we need a 64 bit counter on 64 bit systems.
> Add atomic gssize

- modules/csvparser/tests/CMakeLists.txt
- modules/csvparser/tests/test_csvparser.c
csv_parser test: revwrite based on criterion
> csv_parser test: revwrite based on criterion

- scl/cim/adapter.conf
> scl/cim: add requires json-plugin

- modules/java/native/java_machine.c
Based on @Ancsur 's feedback I updated the warning message.
> java: warning message correction

- lib/cfg-lexer.c
- lib/pragma-grammar.ym
- modules/confgen/CMakeLists.txt
- modules/confgen/Makefile.am
- modules/confgen/confgen-plugin.c
- modules/confgen/tests/CMakeLists.txt
- modules/confgen/tests/Makefile.am
- modules/confgen/tests/confgentest.sh
- modules/confgen/tests/test_confgen.c
Add unit/integration test for the confgen module.
> Confgen and pragma improvements

- packaging/debian/changelog
> packaging: fix debian/changelog

- packaging/debian/syslog-ng-core.install
> DebianPackaging: Add linux-audit SCL to included dirs

- modules/json/tests/CMakeLists.txt
- modules/json/tests/test_dot_notation.c
- modules/json/tests/test_json_parser.c
rewrite test_json_parser, test_dot_notation based on criterion
> Rewrite json tests based on criterion

- README.md
So there is only one H1, and adds link to the community section
> Improve Readme.md header structure

- dbld/images/required-apt/artful.txt
- dbld/images/required-apt/xenial.txt
- add packages to pass tests in Kira
> DbldPackages: Add missing packages to DBLD

- modules/dbparser/tests/CMakeLists.txt
- modules/dbparser/tests/test_patternize.c
- modules/dbparser/tests/test_radix.c
- modules/dbparser/tests/test_timer_wheel.c
rewrite test_timer_wheel, test_patternize, test_radix unit tests of dbparser based on criterion framework
> Rewrite dbparser tests based on criterion

- lib/logmsg/logmsg-serialize.c
- lib/logthrdestdrv.c
- lib/mainloop-worker.c
- modules/diskq/qdisk.c
- modules/http/http.c
This patchset contains some low-hanging changes. The changes are triggered from recent PR comments that are marked as optional and not resolved by those PRs. Nothing critical change should be here.
CC:
@MrAnno for ULL
@Kokan for CURLcode
@lbudai for void to static void
@lbudai for _reset_backlog factor out
@bodnartibi FYI for logmsg-serialize related changes
> Optional changes

- lib/cfg-tree.c
- lib/cfg-tree.h
- lib/logpipe.c
- lib/logpipe.h
- lib/logsource.c
> Fix log expr node use after free

- modules/riemann/riemann-grammar.ym
- modules/riemann/riemann.c
- modules/riemann/riemann.h
I am just stealing a patch from #2291 which fixes a riemann issue caused by #2098 so it could go in faster.
> riemann crashes in flush

- modules/examples/Makefile.am
- modules/examples/sources/threaded-random-generator/Makefile.am
> examples: fix conditional include (Makefile)

- CMakeLists.txt
- Makefile.am
- configure.ac
- lib/logmsg/nvtable-serialize-legacy.c
- lib/persist-state.c
- lib/ringbuffer.c
- lib/secret-storage/nondumpable-allocator.c
- modules/affile/logproto-file-writer.c
- modules/dbparser/Makefile.am
- modules/dbparser/pdb-program.c
- modules/dbparser/pdb-ruleset.c
- modules/dbparser/pdbtool/Makefile.am
- modules/dbparser/pdbtool/pdbtool.c
- modules/dbparser/radix.c
- modules/dbparser/radix.h
- modules/dbparser/tests/Makefile.am
- modules/dbparser/tests/test_parsers.c
- modules/dbparser/tests/test_radix.c
- modules/diskq/tests/Makefile.am
> warning elimination: pointer arithmetics

- dbld/images/required-apt/xenial.txt
Sorry I forget it, this is the last dependency
> dbld.xenial: Added python3-yaml

- lib/logsource.c
Some mangle callbacks depends on the original LogMessage that is received, therefore their invocation has to be made sooner.
As some processing is elemantary (e.g. hostname resolving), I hesitatedto call it first before anything else to avoid breaking things which assumes differently.
> LogSource: reorder some operations on LogMessage

- lib/control/control-commands.c
- lib/mainloop.c
- lib/mainloop.h
- syslog-ng-ctl/syslog-ng-ctl.c
> Issue 2304 | verify the configuration is the same as on the disk

- NEWS.md
- lib/logthrdestdrv.c
- lib/logthrdestdrv.h
- modules/http/CMakeLists.txt
- modules/http/Makefile.am
- modules/http/http.c
- modules/http/http.h
- modules/http/tests/CMakeLists.txt
- modules/http/tests/Makefile.am
- modules/http/tests/test_http.c
- modules/riemann/riemann.c
- tests/copyright/policy
- few memory leaks
- invalid read during reload with invalid configuration
- http error code 4xx -> drop instead of retry. 
- updated news file with #2345 
Thanks @bazsi for help with the investigations and fix!
> small fixes in preparation for 3.18 release

- scl/cisco/plugin.conf
> cisco-parser: add support for cisco catalyst formatted triplets

- dbld/images/helpers/dependencies.sh
Depends on Snaipe/Criterion#272
> dbld: update criterion to 2.3.3

- modules/system-source/system-source.c
Instead of using an explicit exclude-kmsg() option, let's use an alternative detection mechanism to see
if we can pull /proc/kmsg. This alternative mechanism is implemented in this PR.
I've removed support for the exclude-kmsg() option but silently ignoring it if it's present in the configuration.
At the same time I've submitted a PR in syslog-ng-docker to remove system().
https://github.com/balabit/syslog-ng-docker/pull/37
> system-source: check if /proc/kmsg can be opened

- modules/java/native/java-destination.c
- modules/java/native/java-destination.h
- modules/java/native/java_machine.c
This patchset intends to fix a few leaks in java destination.
> java destination: fixing a few memleaks

- modules/json/json-parser.c
> json: refine log messages to be less alarming

- packaging/debian/syslog-ng-mod-http.install
- scl/CMakeLists.txt
- scl/Makefile.am
- scl/slack/slack.conf
Added slack destination as an scl block.
Usage:
To get the hook-url, you need to create an App (you can name it "syslog-ng bot" for better readability) in your Slack Workspace, then in the App's options, under Features -> Incoming Webhooks, generate a "Webhook URL".
In the config, you can modify the nearly every field of the HTTP request. See https://api.slack.com/docs/message-attachments for more details. I gave default values on my personal liking, so if you want to set up the slack destination as quick as possible, it is enough to only provide the hook-url.
The color on the left side is mapped to the severity value of the log message. You can define your own colors with the `colors` option.
Throttle is 1 for default, because generally Slack has a 1 message/sec limit on the webhook, but …
> scl: slack destination

- tests/pytest_framework/conftest.py
- tests/pytest_framework/src/syslog_ng_config/statements/destinations/destination_driver.py
This patch set fixes some previous bugs in pytest fw.
> PytestPART1: Add some bug fixes

- tests/pytest_framework/functional_tests/source_drivers/file_source/test_acceptance.py
- tests/pytest_framework/src/message_builder/bsd_format.py
- tests/pytest_framework/src/message_builder/log_message.py
- tests/pytest_framework/src/setup/testcase.py
This patch set allows to define various message parts during the message generation from functional tests
> PytestPART2: MessageBuilder updates

- lib/rewrite/rewrite-subst.c
- packaging/debian/syslog-ng-core.install
- scl/CMakeLists.txt
- scl/Makefile.am
- scl/websense/plugin.conf
This branch adds a parser/application adapter for fixing up websense logs.
This branch also adds a trace message into subst() to make that easier to debug.
> Websense parser

- packaging/debian/control
> packaging: fix the description of mod-examples

- modules/http/http-worker.c
result of curl_easy_getinfo was not used (CURLcode code), the result of
the previus curl_xxx call was used (CURLcode ret)
> http-worker: refactor & fix curl_easy_getinfo error message

- lib/logthrdestdrv.c
small refactor (I think it is easier to modify the `process_result` function after this change)
> logthrdestdrv: factor out _process_result_xxx functions

- modules/redis/redis-grammar.ym
- modules/redis/redis.c
- modules/redis/redis.h
Similar issue as what we have seen in #2514.
> redis: consume ref at set_command

- modules/python/python-source.c
Fixes: https://github.com/balabit/syslog-ng/issues/2368
In syslog-ng, logwriters are lazily created: the first message
triggers the creation, and the creation is done by the posting
thread. To avoid race condition, the process is done through a
`main_loop_call()` function. So that to work, on needs to initialize
the posting thread with `main_loop_call_thread_init()`. However, this
api is not exposed to python, hence posting from thread cannot work
from a python thread other than the one started by the threaded
source.
This patch saves the assigned thread id, and compares the current
thread id of the `post_message` caller. In case of mismatch, exception
is thrown.
> python-source: fix crash when posting from python thread

- lib/logthrdestdrv.c
Before this commit, the worker's queue's `persist_name` was stored in a static string, and it was accessed and changed by multiple threads in the same time.
The static string was there to avoid having to care about malloc/free, it is not performance critical, so it can be changed to local.
Follow up for the comments at #2512.
> threaded-dest: make persist_name local

- lib/scanner/xml-scanner/tests/test_xml_scanner.c
- lib/template/simple-function.c
- lib/tests/test_pathutils.c
- modules/affile/tests/test_file_list.c
Easy way to reproduce these issues with https://github.com/balabit/syslog-ng/pull/2562
> Few leak fix

- lib/logmsg/tests/test_log_message.c
- modules/afsmtp/afsmtp.c
- modules/diskq/qdisk.c
- modules/stardate/stardate.c
> format nonliteral fixes

- lib/transport/tests/CMakeLists.txt
- lib/transport/tests/test_aux_data.c
> test_aux_data: rewrite test cases in criterion

- lib/stats/tests/CMakeLists.txt
- lib/stats/tests/test_stats_cluster.c
> test_stats_cluster: rewrite test cases in criterion

- CONTRIBUTING.md
- dbld/README.md
- dbld/images/README.md
The main goal of this PR is to add the preferred commit message format to the CONTRIBUTION.md description. (Currently it is only available in gitbook.)
Updated the dbld README files to represent the new manifest based package handling.
> Updating docs

- lib/filter/tests/CMakeLists.txt
- lib/filter/tests/test_filters_in_list.c
> test_filters: rewrite test cases in criterion

- lib/tests/CMakeLists.txt
- lib/tests/test_cfg_lexer_subst.c
> test_cfg_lexer_subst: rewrite test cases in criterion

- lib/str-repr/tests/CMakeLists.txt
- lib/str-repr/tests/test_decode.c
> test_decode: rewrite test cases in criterion

- modules/csvparser/tests/CMakeLists.txt
- modules/csvparser/tests/test_csvparser_perf.c
> test_csvparser_perf: rewrite test cases in criterion

- modules/afsocket/tests/CMakeLists.txt
- modules/afsocket/tests/test-transport-mapper-inet.c
- modules/afsocket/tests/test-transport-mapper-unix.c
- modules/afsocket/tests/test-transport-mapper.c
- modules/afsocket/tests/transport-mapper-lib.h
> test_transport_mapper: rewrite test cases in criterion

- lib/tests/test_host_resolve.c
> test_host_resolve: rewrite test cases in criterion

- README.md
Other changes include making formatting (like capitalisation and punctuation after bullet points) more consistent, and fixing or removing dead links.
Many of the rewordings are stylistic and may be personal preference. Feel free to question me on these or veto them.
> Make rewording and other small edits to README

- modules/diskq/tests/CMakeLists.txt
- modules/diskq/tests/test_diskq.c
- modules/diskq/tests/test_diskq_full.c
- modules/diskq/tests/test_diskq_truncate.c
- modules/diskq/tests/test_reliable_backlog.c
> test_diskq: rewrite test cases in criterion

- lib/logproto/tests/test-regexp-multiline-server.c
- lib/logproto/tests/test-server-options.c
- lib/logproto/tests/test_logproto.c
> Fix double-free error in logproto unit tests

- CMakeLists.txt
- Makefile.am
- lib/secret-storage/secret-storage.c
- lib/stats/stats.c
> old style definition warning fixes

- lib/logmsg/tests/CMakeLists.txt
- lib/logmsg/tests/test_tags.c
> test_tags: rewrite test cases in criterion

- modules/systemd-journal/tests/CMakeLists.txt
- modules/systemd-journal/tests/test-source.c
- modules/systemd-journal/tests/test_systemd_journal.c
> test_systemd_journal: rewrite test cases in criterion

- packaging/debian/syslog-ng-core.install
- scl/CMakeLists.txt
- scl/Makefile.am
- scl/junos/plugin.conf
> junos: add application adapter for Junos classification

- modules/dbparser/pdb-file.c
> dbparser: fix memleak

- packaging/debian/Makefile.am
- packaging/debian/control
- packaging/debian/syslog-ng-mod-rdkafka.install
> packaging/debian: add syslog-ng-mod-rdkafka

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/cfg-parser.h
- modules/appmodel/app-parser-generator.c
see my [comment](https://github.com/balabit/syslog-ng/pull/2671#issuecomment-490909232)
> Revert yesno aliases

- NEWS.md
> NEWS: version 3.21

- lib/cfg.c
- lib/cfg.h
- lib/mainloop.c
- modules/add-contextual-data/add-contextual-data-filter-selector.c
Handle file open errors in case of --preprocess-into is used.
Fixes #2720.
> Preprocess-into error handling

- modules/geoip2/geoip-parser.c
- modules/geoip2/geoip-parser.h
- modules/geoip2/tfgeoip.c
> geoip2: include ip into the error message

- tests/loggen/loggen.c
This is a quick implementation of changing message rate at runtime.
`SIGUSR1` doubles, `SIGUSR2` halves the message rate.
> loggen: change message rate at runtime using signals

- lib/cfg-grammar.y
- modules/appmodel/appmodel-grammar.ym
Fix
* generator plugin was not accepted in options block
* multiple semicolons were not accepted in a few place (for example in options)
> global options: support generator plugin

- lib/cfg-lex.l
- lib/tests/test_lexer.c
> Fix escaped quote in block argument

- lib/filter/filter-expr-grammar.ym
- lib/logmatcher.c
> Improve regexp error messages

- lib/tests/test_userdb.c
- tests/python_functional/src/common/network_operations.py
- tests/python_functional/src/message_builder/log_message.py
Running the test suite on FreeBSD currently fails.
This PR fix a few issues.  The test suite is still not 100% green.
> FreeBSD fixes for the test suite

- NEWS.md
> NEWS: version 3.22

- .travis.yml
- CMakeLists.txt
- Makefile.am
- tests/Makefile.am
- tests/commits/check.sh
- tests/copyright/policy
Quick stats while working on this, on all commits of the master branch (excluding merge commits):
|                       | Commits | Percent |
|-----------------------|--------:|--------:|
| **Total**             |    8313 | 100.00% |
| **No problem**        |    5763 |  69.32% |
| **No signed-off-by**  |    1673 |  20.12% |
| **Malformed subject** |    1888 |  22.71% |
These stats where generated using:
```sh-session
romain@zappy ~/Projects/syslog-ng % ./tests/commits/check.sh --root |& grep FAIL | wc -l
2550
```
Fixes: #2800
> Check the commit messages are properly formatted

- modules/dbparser/patterndb.c
`_advance_time_based_on_message()` is responsible for updating the time based on the incoming message and for triggering  `pattern_db_expire_entry()` on expired contexts.
`pattern_db_expire_entry()` (invoked by `timer_wheel_set_time`) then executes the actions of the expired context. In order to do this, it needs a `PDBProcessParams` instance as an output object, so it can, for example, buffer emitted messages.
An expired context can change the fields of `process_params`, therefore `_advance_time_based_on_message()` should not be called in the middle of another rule execution, because it can lead to crashes.
To avoid such scenarios, `_pattern_db_advance_time_and_flush_expired()` has been added, which triggers the actions of the expired contexts and flushes the output separately.
-------- …
> dbparser: fix crash when context times out in the middle of another rule

- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
One of my branch failed because of this exception, this just add a very minor information that might help in case of this exception.
> light: syslogngcli include exit_value

- NEWS.md
> NEWS: version 3.23

- lib/filter/filter-cmp.c
- lib/filter/filter-re.c
Spring cleanup from my disk.
This commit is somewhat questionable: https://github.com/balabit/syslog-ng/commit/06ce5030352c6732710331861bf20a7bad74cb33
> filter: small refactors

- lib/run-id.c
> run-id: Fix "equality comparison with extraneous parentheses"

- modules/afsocket/afsocket-dest.c
In d29b98c9a261cbfd04dbe6afbb17008fa5108e7c we changed the persist name
from afsocket_dd_connection to afsocket_dd_connections (notice the s)
We also changed the hostname parameters.
There is no API to actually rename an entry in the persist file (We can
do it for runtime use only.), so we actually allocate a new entry with
the new name, and copy the content of the old one.
Question for the reviewer: Why don't we check the return value of https://github.com/balabit/syslog-ng/blob/master/modules/afsocket/afsocket-dest.c#L237
> afsocket-dest: rename old persist entries

- modules/kafka/kafka-dest-worker.c
> kafka-c: Fix multiple memleaks

- lib/host-resolve.c
`AI_NUMERICHOST`: We will check, if the host is declared as a plain IP address, so we can skip the whole hostname lookup phase.
`AI_V4MAPPED | AI_ADDRCONFIG`: We will try to lookup the IP from the hostname, taking into account the system's network interfaces.
- If the system has an IPv6 interface configured, and there is an IPv6 resolution of the hostname, we use it.
- If the system only has an IPv4 interface configured, and there is an IPv6 resolution of the hostname, we use it.
- If the system does not have any network interfaces configured, (lo interface does not count here), we go for the third try.
`AI_V4MAPPED`: We try to resolve the hostname not taking into account the system's network interfaces (we can resolve the lo interface IPs).
If we could not resolve the hostname after …
> host-resolve: try getaddrinfo() with different flags

- .github/ISSUE_TEMPLATE/10-bug-report.md
- .github/ISSUE_TEMPLATE/20-documentation-issue.md
- .github/ISSUE_TEMPLATE/30-feature-request.md
- Makefile.am
1. Bug report
2. Documentation issue
3. Feature request
Example: https://github.com/tensorflow/tensorflow/issues/new/choose
> issues: add templates for "New Issue" on github

- lib/logthrdest/logthrdestdrv.c
- lib/persist-state.c
- lib/persist-state.h
- modules/afsocket/afsocket-dest.c
- modules/afsql/afsql.c
Handling legacy formatted qfile names in sql driver persist state.
> Handle legacy sql qfile names

- lib/logproto/logproto-buffered-server.c
LogProtoBufferedServer is designed to work without persist state if the
allocation fails. (persist-state will schedule a mainloop exit in this
case, but LPBServer will keep runing until we shut down gracefully)
The statless mode is handled internally by returning a dummy state in
case of allocation failure. There are safeguards in _get_state, and
_put_state to not actually try to "persist_state_map_enty" this value.
However in Bookmark handling we only pass the persist_handle to the
callback function, not the whole LogProtoBufferedServer, and we can not
use our safeguards to prevent 'persist_state_map_entry' that invalid
value. This patch separates that case by using a different callback
function.
> logproto-buffered-server: fix an issue with bookmark/persist handling

- NEWS.md
> NEWS: version 3.24

- dbld/Jenkinsfile
This branch adds an initial jenkinsfile from ci.syslog-ng.com to be able to maintain that in-tree
going forward. We need to wait for the dbld image caching to go in first #2858.
> Dbld jenkinsfile

- .travis.yml
- CMakeLists.txt
- cmake/add_tests.cmake
- lib/compat/glib.h
- lib/stats/stats-cluster.c
- m4/m4_esyscmd_s.m4
- modules/affile/file-list.c
- modules/hook-commands/hook-commands.c
- modules/http/http-loadbalancer.c
- modules/python/pylib/CMakeLists.txt
- modules/snmp-dest/snmpdest.c
This is the generic portions of #2860 that omits the centos6 related images, but still includes the code changes that should go in regardless. I am opening this to make this easier to merge.
> Fix compat with older systems

- .travis.yml
- CMakeLists.txt
This only replaces one of the cmake + make build with cmake + ninja.
> travis: test cmake + ninja combination

- lib/timeutils/zoneinfo.c
- libtest/mock-cfg-parser.c
- modules/dbparser/patterndb.c
Compiling with `-fsanitize=undefined` and executing the UT test set reports these issues (well others as well, but most of them are related to nvtables)
> Few undefined behaviour issue in code

- contrib/Makefile.am
- contrib/config_option_database/.coveragerc
- contrib/config_option_database/.gitignore
- contrib/config_option_database/config_database.py
- contrib/config_option_database/requirements.txt
- contrib/config_option_database/utils/BisonGraph.py
- contrib/config_option_database/utils/ConfigOptions.py
- contrib/config_option_database/utils/MergeYm.py
- contrib/config_option_database/utils/OptionParser.py
- contrib/config_option_database/utils/Yacc2Graph.py
- contrib/config_option_database/utils/test/test_BisonGraph.py
- contrib/config_option_database/utils/test/test_OptionParser.py
- contrib/config_option_database/utils/test/test_Yacc2Graph.py
- lib/cfg-parser.c
- modules/kafka/kafka-parser.c
- tests/copyright/policy
Usage:                                                                      
`./config_database.py <context> <driver>`
By default it caches the option database. Use the `-r` or `--rebuild` flag to force rebuild it.
For example:
```
$ ./config_database.py destination kafka-c
destination kafka-c(
bootstrap-servers/kafka-bootstrap-servers(<string>)
client-lib-dir(<string>)
config/option()
config/option(<string> <arrow> <string-or-number>)
config/option(<string> <string-or-number>)
flush-timeout-on-reload(<number>)
flush-timeout-on-shutdown(<number>)
frac-digits(<number>)
key(<string>)
local-time-zone/time-zone(<string>)
log-fifo-size(<number>)
message/template(<string>)
on-error(<string>)
persist-name(<string>)
poll-timeout(<number>)
properties-file(<path>)
send-time-zone(<string>) …
```
> Add config_database.py

- tests/python_functional/functional_tests/logpath/test_flags_catch_all.py
- tests/python_functional/functional_tests/logpath/test_flags_fallback.py
- tests/python_functional/functional_tests/logpath/test_flags_final.py
- tests/python_functional/functional_tests/logpath/test_multiple_embedded_logpaths.py
- tests/python_functional/functional_tests/logpath/test_multiple_flags.py
- tests/python_functional/functional_tests/parsers/app-parser/test_topic_syslog.py
- tests/python_functional/functional_tests/parsers/app-parser/test_topic_syslog_raw.py
- tests/python_functional/functional_tests/source_drivers/file_source/test_acceptance.py
- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/destination_reader.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/file_destination.py
- tests/python_functional/src/syslog_ng_config/statements/filters/filter.py
- tests/python_functional/src/syslog_ng_config/statements/parsers/parser.py
- tests/python_functional/src/syslog_ng_config/statements/sources/example_msg_generator_source.py
- tests/python_functional/src/syslog_ng_config/statements/sources/file_source.py
- tests/python_functional/src/syslog_ng_config/statements/sources/source_writer.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
This PR is a first part of a bigger SyslogNgConfig refactor
- this part contains only functionally equivalent changes
> Light: SyslogNgConfig refactor part 1

- modules/snmptrapd-parser/CMakeLists.txt
- modules/snmptrapd-parser/tests/CMakeLists.txt
- packaging/debian/syslog-ng-core.install
- packaging/debian/syslog-ng-mod-elastic.install
- packaging/debian/syslog-ng-mod-graphite.install
- packaging/debian/syslog-ng-mod-hdfs.install
- packaging/debian/syslog-ng-mod-http.install
- packaging/debian/syslog-ng-mod-kafka.install
- packaging/debian/syslog-ng-mod-pacctformat.install
- packaging/debian/syslog-ng-mod-snmptrapd-parser.install
- scl/elasticsearch/elastic-http.conf
- scl/elasticsearch/elastic-java.conf
- scl/graphite/plugin.conf
- scl/kafka/kafka-java.conf
- scl/kafka/kafka.conf
- scl/pacct/plugin.conf
- scl/scl.conf
- scl/snmptrap/snmptrapd-source.conf
- scl/telegram/telegram.conf
> Debian moves scls to the core package

- .mailmap
> mailmap: Add attila.szakacs@oneidentity.com

- news/developer-note-3043.md
- news/developer-note-3044.md
- news/feature-3078.md
- news/other-3086.md
- news/other-3092.md
Question: what about example configs?
Do we want to include them in the news file?
(I've added example configs... sometimes it is useful for users...)
> missing news files

- dbld/images/helpers/packages.manifest
- dbld/images/helpers/pip_packages.manifest
- dbld/images/kira.dockerfile
- dbld/rules
- separate docker environment for tests
- this image will used in our CI to run test related jobs
> DBLD: Add support for Kira image

- news/developer-note-3125.md
> news: Add missing news file for PR-3130

- lib/cfg-parser.c
- lib/versioning.h
We also need this in the commercial version.
> Documentation link update

- scl/loggly/loggly.conf
For issue https://github.com/syslog-ng/syslog-ng/issues/3148
Signed-off-by: Dylan Perry <dylan.perry@gmail.com>
> scl: fix loggly TLS destination

- .travis.yml
- news/developer-note-3126.md
- tests/python_functional/functional_tests/conftest.py
- tests/python_functional/functional_tests/destination_drivers/snmp_destination/test_snmp_destination_v2c_cisco_ios_traps.py
- tests/python_functional/pytest.ini
- tests/python_functional/src/helpers/snmptrapd/conftest.py
- tests/python_functional/src/syslog_ng_config/renderer.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/destination_reader.py
- tests/python_functional/src/syslog_ng_config/statements/destinations/snmp_destination.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
Add snmp destination related test cases to Light.
The test shall be able to start the snmptrapd parser (if it is not installed, the test case will skip)
The trapd output file will be parsed to check for the expected log message.
> Light: Add snmp destination tests

- news/feature-3149.md
> news: add feature entry for #3149

- news/bugfix-3048.md
- news/bugfix-3056.md
- news/bugfix-3058.md
- news/bugfix-3064.md
- news/bugfix-3067.md
- news/bugfix-3070.md
- news/bugfix-3075.md
- news/bugfix-3082.md
- news/developer-note-3034.md
- news/developer-note-3038.md
- news/developer-note-3071.md
- news/feature-2955.md
- news/feature-3015.md
- news/feature-3029.md
- news/feature-3051.md
- news/feature-3063.md
- news/feature-3115.md
- news/other-2979.md
- news/other-3072.md
- news/other-3134.md
If I added you to the reviewers, that is because I wrote the news entry about the PR you have created. Please leave comment if you would have wrote something differently.
> news: add newsfile entries for PRs before the newsfile generating script

- news/developer-note-3038.md
Add missing developer notes for #3038.
> news: add developer notes for #3038 [skip-ci]

- libtest/Makefile.am
- news/developer-note-3179.md
> libtest: install missing libtest headers

- news/bugfix-3180.md
Added as a bugfix, as I agreed with @furiel :+1:
> news: add news for pr 3180

- news/README.md
> news: README.md changes

- news/feature-3194.md
- scl/CMakeLists.txt
- scl/Makefile.am
- scl/sumologic/sumologic.conf
> scl: add sumologic

- lib/compat/glib.c
- news/bugfix-3212.md
> compat/glib: fix recursive call issue

- packaging/debian/control
- packaging/debian/syslog-ng-core.install
- packaging/debian/syslog-ng-mod-slog.install
- packaging/debian/syslog-ng-mod-slog.manpages
- packaging/rhel/syslog-ng.spec
> packaging: move $(slog) and related functionality to a separate package

- .travis.yml
- tests/python_functional/conftest.py
- tests/python_functional/functional_tests/template_functions/slog/test_secure_logging.py
- tests/python_functional/src/helpers/secure_logging/conftest.py
- tests/python_functional/src/syslog_ng/syslog_ng_paths.py
- tests/python_functional/src/syslog_ng/tests/test_syslog_ng_paths.py
> secure-logging: add simple test

- news/feature-3237.md
Signed-off-by: Vivin Peris <vivinperis98@gmail.com>
> news: feature-3237

- CMakeLists.txt
- Makefile.am
- lib/scanner/csv-scanner/csv-scanner.c
- modules/kafka/kafka-props.c
> Makefile.am: Eliminate warning for discarded qualifiers

- CMakeLists.txt
- Makefile.am
> Makefile.am: Eliminate warnings for multiple errors

- lib/crypto.c
- news/bugfix-3271.md
> crypto: fixes hang on boot due to lack of entropy

- .travis.yml
astyle is only available in the devshell image.
> travis: use devshell for style-check

- modules/kvformat/tests/test_format_welf.c
This patch add a few testcases for test_format_welf.
> test_format_welf: add a few testcases

- contrib/config_option_database/syslog-ng-cfg-db.py
- contrib/config_option_database/utils/MergeYm.py
> cfg-db: small refactor

- .github/workflows/devshell.yml
> github-actions: add devshell based CI job

- dbld/Jenkinsfile
- dbld/Makefile.am
- dbld/images/fedora-32.dockerfile
- dbld/rules
pulled in from a patch by @czanik 
Fixes #3314
> Dbld fedora 32 support

- .github/workflows/devshell.yml
> github-actions: use checkout v2

- packaging/debian/syslog-ng-mod-slog.manpages
- packaging/rhel/syslog-ng.spec
> Prepare 3.28

- lib/logwriter.c
- lib/reloc.c
- modules/diskq/tests/test_diskq_full.c
Just clean up, no functional impact
> misc: clean up some duplicate header includes

- tests/python_functional/functional_tests/source_options/test_use_syslogng_pid.py
- tests/python_functional/src/syslog_ng/syslog_ng.py
- tests/python_functional/src/syslog_ng/syslog_ng_cli.py
> light: add testcase for use_syslogng_pid

- modules/syslogformat/syslog-format.c
- news/bugfix-3364.md
> syslog parser fix crash during handling short inputs

- .github/workflows/macos.yml
https://github.com/Homebrew/homebrew-bundle/issues/751
> github-ci: run brew update in macOS job before installing dependencies

- lib/tests/test_lexer.c
- lib/tests/test_pragma.c
- modules/system-source/system-expand.sh
- tests/functional/globals.py
IMHO news file is not required - it's internal and straightforward
> Use cfg version current

- dbld/builddeps
- dbld/images/devshell.dockerfile
- dbld/packages.manifest
- also upgrade setuptools package along with pip
This PR fixes various python related issues in build packages, and also clarify python related installs during dbld image setup.
> DBLDBuilddeps: Generalize python / pip install and upgrade for various python versions

- news/feature-3381.md
I hope I don't have to provide a news file for this PR ;)
> news: add news file for PR#3381

- modules/json/json-parser.c
- modules/json/tests/test_json_parser.c
- news/bugfix-3403.md
> json-parser: parse 64 bit integer numbers

- news/feature-3372.md
> news: add news entry for #3372

- lib/control/control-server.c
- lib/control/control-server.h
- lib/mainloop.c
- lib/mainloop.h
- lib/stats/stats-control.c
- lib/stats/stats-query-commands.c
- lib/thread-utils.h
- news/bugfix-3349.md
Split #3349 
First part of the PR is:
* run stats/query commands in a separate thread
> Threaded ctl command runner

- modules/python/python-helpers.c
- modules/python/python-persist.c
- modules/python/tests/test_python_ack_tracker.c
- modules/python/tests/test_python_bookmark.c
- modules/python/tests/test_python_persist_name.c
> python module leaks and fixes in UT

- .github/workflows/comment-on-version-bump-pr.yml
- .github/workflows/draft-release.yml
- .github/workflows/version-bump.yml
- dbld/prepare-release
- dbld/rules
- news/create-newsfile.py
This job creates a version bump branch based on master, and opens a PR from it.
The branch will have the version bumped in all necessary parts of the code, and it will generate the NEWS.md content from the NEWS snippets.
Organization members have the chance to add or modify the commits on the branch, if necessary.
The job will also generate a tarball, and reference it in the PR's description.
The job cannot be started, if there is an open PR with the version given.
Manual steps:
1. Navigate to https://github.com/syslog-ng/syslog-ng/actions.
2. Choose the "Version bump" job.
3. Click "Run workflow".
4. Fill the new release version, and click "Run workflow".
5. When the PR is opened, double check the changes, if necessary, add commits.
6. When the PR is merged, the "Draft release" job will …
> github-actions: add release jobs

- .github/workflows/devshell.yml
Since #3405 was merged, these jobs are fixed.
> github-actions: test python3-clang

- news/developer-note-2526.md
> news: add news entry for #2526

- lib/tlscontext.c
- news/bugfix-3466.md
> Tls cert verification ipv6 fix

- news/README.md
- news/next-pr-id.py
- tests/copyright/policy
> news: add next_pr_id script

- lib/ack-tracker/batched_ack_tracker.c
- lib/control/control-server.c
g_mutex_init, and embedding GMutex in a struct is only supported since glib 2.32.
See:
https://developer.gnome.org/glib/stable/glib-Threads.html#g-mutex-init
please note, this patch adds deprecated APIs (since 2.32) though:
https://developer.gnome.org/glib/stable/glib-Deprecated-Thread-APIs.html#g-mutex-new
We should consider increasing the minimum version of glib.
Most of the distros use newer versions, and centos6 will be EOL on november 30 (https://wiki.centos.org/About/Product).
glib versions in distros: https://repology.org/project/glib/versions
We've discussed that some enterprise distros (e.g. SLES) use old glib too, but I've checked SLES 12 and it seems to use newer glib.
(lifecycle: https://www.suse.com/lifecycle/, SUSE Linux Enterprise Server 12 SP5 with general EOL 31 Oct 2024) …
> Fix glib2.28 support

- .github/workflows/draft-release.yml
- lib/versioning.h
> draft-release: fix release names

- CMakeLists.txt
- Makefile.am
- lib/tests/test_scratch_buffers.c
- lib/tests/test_type_hints.c
> Fix leak and invalid memory access in unit tests

- lib/logwriter.h
- tests/unit/test_logwriter.c
No news file is needed as #3474 has one.
> test_logwriter: add some unit tests

- scl/cisco/plugin.conf
> add the extraction of syslog PRI value in cisco-parser()

- modules/dbparser/pdb-load.c
- modules/dbparser/pdb-program.c
- modules/dbparser/pdb-program.h
- modules/dbparser/pdbtool/pdbtool.c
- modules/dbparser/radix.c
- modules/dbparser/radix.h
- modules/dbparser/tests/test_radix.c
I have created these patches while looking into #3542, please don't merge until that is concluded.
> improve db-parser() error messages on duplicate patterns

- news/bugfix-3553-2.md
- news/bugfix-3553.md
> news: add entries for #3553

- dbld/rules
- dbld/shell
I finally had enough of my gdb not saving its history file, so here's a couple of patches that allows me to do that.
> Dbld shell improvements

- contrib/get-github-actions-status.py
This will be used to poll the status of the GitHub Actions jobs in the Jenkins dashboard.
> get-github-actions-status: add new script

- lib/logmsg/logmsg.c
- lib/logmsg/tests/test_log_message.c
> logmsg/logmsg: fix a potential crash caused by a bug in log_msg_clear()

- news/bugfix-3599.md
Add missing news file for #3599
> news: add news entry for #3599

- lib/filter/tests/test_filters_regexp.c
Fix #3397 Improve regex related test cases
* introduce new test cases for dupnames.
* introduce various test cases to ensure the correctness of the code
Pass unit tests
> Fix issue #3397 Improve regex related test cases 

- lib/transport/transport-tls.c
(Triggered by the failover mechanism.) Syslog-ng reported a very strange error
message if the other end closed the connection before sending any data first:
> I/O error occurred while reading; fd='13', **error='Success (0)'**
The root cause of the problem is that `SSL_read` handles the read()==0
as a syscall error, and such as expect it to set an errno number.
This is a known bug in OpenSSL. Unfortunately the fix got reverted because
it broke too many legacy code. Details can be found here: https://github.com/openssl/openssl/pull/11400
> transport-tls: handle missing errno in case of unexpected EOF

- news/packaging-3547.md
> news: bison min version is bumped

- CMakeLists.txt
- Makefile.am
- lib/timeutils/misc.c
- lib/timeutils/tests/test_scan-timestamp.c
- libtest/fake-time.c
- modules/afsocket/afsocket-grammar.ym
- modules/afsocket/afsocket-source.c
- modules/afsocket/afsocket-source.h
- modules/basicfuncs/numeric-funcs.c
- modules/python/python-logmsg.c
- tests/loggen/loggen_plugin.c
> Build: add -Wfloat-conversion to extra warning

- modules/diskq/qdisk.c
Since this PR is only a cosmetic change mainly focusing on working with the `dqtool info` command. I am marking it as a Draft, and I am open for second opinions.
---
Sometimes GitHub mixes the lines for me in the diff. What happened here:
- On info level
Print the filename, and the number of messages in the file.
- On debug level:
Pint the filename, and the raw header positions / counters, so one can calculate the necessary information.
> qdisk: modify debug messages during loading diskqueue

- dbld/images/hooks/build
Didn't renamed the argument in docker hub hook
> Fix Docker Hub build (#3715 bugfix)

- modules/kafka/CMakeLists.txt
- modules/kafka/tests/CMakeLists.txt
- modules/kafka/tests/test_kafka_config.c
> kafka: minor test-related fixes

- dbld/README.md
Update Xenial based guide
Update Xenial based guide to Focal based install from tarball because it was outdated.
> dbld: update README.md

- tests/python_functional/functional_tests/source_drivers/file_source/test_no_header_flag.py
Signed-off-by: Benedek Cserhati <benedek.cserhati@balabit.com>
> LightFunctionalTests: Add new test cases for no-header flag

- modules/system-source/system-source.c
- news/feature-3761.md
Upstreaming patch from NetBSD pkgsrc
> system source: add NetBSD support

- lib/template/tests/test_template.c
> template: fix string comparison in unit tests

- .github/workflows/devshell.yml
WIP: Depends on https://github.com/syslog-ng/syslog-ng/pull/3782
Signed-off-by: Laszlo Szemere <laszlo.szemere@oneidentity.com>
> actions: use GitHub docker registry in CI@devshell action

- .github/workflows/macos.yml
> github-actions: macos: update path for PKG_CONFIG_PATH

- news/feature-3781.md
This is based on https://github.com/syslog-ng/syslog-ng/pull/3816.
Only as agreed a shortened news entry, and pushed needed content into original PR.
> news: add entry for #3781

- lib/file-perms.c
- lib/file-perms.h
- modules/affile/affile-dest.c
- modules/affile/affile-dest.h
- modules/affile/affile-grammar.ym
- modules/affile/affile-parser.c
- modules/affile/file-opener.c
- modules/affile/file-opener.h
- news/feature-3855.md
Proposed implementation for #3854
> add "symlink-as" option for file destinations

- modules/python/compat/compat-python.h
- modules/python/python-integerpointer.c
- modules/python/python-logmsg.c
- news/other-3865.md
This PR "adds support" for Python 3.10 by following new API constraints.
https://docs.python.org/3/whatsnew/3.10.html
@furiel
> Support Python 3.10

- modules/dbparser/dbparser.c
> db-parser: add more detail to db-parser() log messages

- README.md
Preview: https://github.com/Kokan/syslog-ng/tree/log4j-a#log4j
> readme: add log4j statement

- tests/python_functional/functional_tests/Makefile.am
- tests/python_functional/functional_tests/filters/throttle/test_throttle_filter_acceptance.py
- tests/python_functional/src/helpers/loggen/loggen.py
- tests/python_functional/src/syslog_ng_config/statements/filters/filter.py
- tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
- tests/python_functional/src/syslog_ng_ctl/driver_stats_handler.py
> Light: add testcase for throttle() filter

- tests/unit/test_matcher.c
Since we are only testing logmatcher, we don't need to use the entire syslog message as input in these testcases. Make
things simpler by using log_msg_set_value() instead of running it through syslogformat to parse it.
Originally part of my typing work, but completely independent, so by opening a separate PR I hope we can merge it sooner.
> test_matcher: avoid using complete syslog messages as test input

- lib/control/control-commands.c
> control: include string.h for strncmp() and strlen()

- modules/kafka/kafka-grammar.ym
In the end, this was just a typo  and everything is fine.
> kafka: correct context on grammar

- scl/mariadb/audit.conf
- tests/copyright/policy
This adds an SCL to parse mariadb/mysql audit logs
> Add mariadb audit log parsing

- modules/diskq/tests/test_diskq.c
This also fixed an ASLR issue in this Criterion testcase.
More info: Snaipe/Criterion#338
> diskq: refactor test_diskq_statistics

- .github/workflows/upload-packages.yml
> github-actions: fix usage of ubuntu-jammy in create-packages

- modules/afsql/afsql-grammar.ym
- modules/afsql/afsql.c
- modules/afsql/afsql.h
- tests/functional/test_sql.py
This pull requests improves @vivinperis 's PR #3295 so that it integrates with the latest typing changes.
This only received limited testing at this point.
> Afsql typing support (4.0)

- lib/template/macros.c
- lib/template/tests/test_template.c
Fixes #4100 
* news file is still missing
> template: fix assertion failure for escaped templates

- lib/timeutils/scan-timestamp.c
- lib/timeutils/tests/test_scan-timestamp.c
- modules/syslogformat/CMakeLists.txt
- modules/syslogformat/Makefile.am
- modules/syslogformat/syslog-format.c
- modules/syslogformat/tests/CMakeLists.txt
- modules/syslogformat/tests/Makefile.am
- modules/syslogformat/tests/test_syslog_format.c
- news/bugfix-4110.md
> Fix buffer handling of syslog and timestamp parsers

- modules/basicfuncs/numeric-funcs.c
This branch changes the basicfuncs/num-funcs.c plugin to use the new GenericNumber implementation instead its own local implementation for Numbers.
> Migrate the numeric part of basicfuncs to use GenericNumbers

- news/feature-4127.md
This is just the missed NEWS entry for #4127
> news: added NEWS entry for PR #4127

- tests/copyright/check.sh
Signed-off-by: Bálint Horváth <bal.horv.98@gmail.com>
> copyright-check: Added permissive ', LLC.' to parent company name.

- lib/cfg.c
- lib/template/macros.c
- lib/template/templates.c
- lib/template/templates.h
- modules/python/python-logmsg.c
> Remove python logmsg blacklist

- modules/python/pylib/syslogng/__init__.py
- modules/python/python-dest.c
- modules/python/python-dest.h
- modules/python/python-helpers.c
- modules/python/python-helpers.h
- modules/python/python-logparser.c
- modules/python/python-logparser.h
- modules/python/python-plugin.c
- modules/python/tests/test_python_persist_name.c
This is the first chunk of #4165 to add base classes for Python based LogDestination and LogParser classes.
> Python log dest and parser base classes

- lib/secret-storage/nondumpable-allocator.c
> secret-storage: handle missing MAP_ANONYMOUS

- modules/python/python-dest.c
- modules/python/python-fetcher.c
- modules/python/python-helpers.c
- modules/python/python-source.c
- modules/python/tests/test_python_persist_name.c
This is the 2nd chunk of #4165 clarifying log output of the Python module and fixing up an ugly logging issue in one of our unit tests. 
NOTE: This builds on top of #4188 but could be merged separately by rebasing to master first. I didn't want to base it on master, as that would break my larger PR or I would have to merge PRs into my mega-PR.
> Python log message improvements

- lib/cfg.h
- lib/template/tests/test_template.c
- lib/tests/test_lexer.c
- modules/json/tests/test_format_json.c
This PR fixes a couple of tests that break due to the version number change in #4204
no news is needed
> Fix version 4 triggered test issues

- tests/light/conftest.py
- tests/light/functional_tests/conftest.py
- tests/light/functional_tests/source_drivers/network_source/proxyprotocol/test_pp_tls_passthrough.py
- tests/light/src/common/file.py
- tests/light/src/driver_io/file/file_io.py
- tests/light/src/driver_io/network/network_io.py
- tests/light/src/syslog_ng/console_log_reader.py
- tests/light/src/syslog_ng/syslog_ng.py
- tests/light/src/syslog_ng/syslog_ng_cli.py
- tests/light/src/syslog_ng_config/statements/destinations/example_destination.py
- tests/light/src/syslog_ng_config/statements/destinations/file_destination.py
- tests/light/src/syslog_ng_config/statements/destinations/unix_dgram_destination.py
- tests/light/src/syslog_ng_config/statements/destinations/unix_stream_destination.py
- tests/light/src/syslog_ng_config/statements/sources/file_source.py
- tests/light/src/syslog_ng_config/syslog_ng_config.py
> Light: Closing open fds on testcase teardown

- .github/workflows/create-packages.yml
- .github/workflows/dbld-images.yml
- .github/workflows/packages.yml
- dbld/Makefile.am
- dbld/builddeps
- dbld/images/fedora-37.dockerfile
- dbld/rules
This is the resolution for ticket #4220 provided by @czanik 
Resolves  #4220
Signed-off-by: @czanik 
> dbld: Changes needed for Fedora 37 support by CZP

- configure.ac
- modules/python-modules/CMakeLists.txt
- modules/python-modules/Makefile.am
> Conditional python modules

- README.md
- https://archlinux.org/packages/extra/x86_64/syslog-ng/
- https://github.com/Homebrew/homebrew-core/blob/master/Formula/syslog-ng.rb
> readme: update with Arch Linux and macOS install steps

- packaging/debian/control
It is needed for the venv setup postinstall script.
```
Creating or updating syslog-ng Python virtualenv in /var/lib/syslog-ng/python-venv
Running python -m venv...
The virtual environment was not created successfully because ensurepip is not
available.  On Debian/Ubuntu systems, you need to install the python3-venv
package using the following command.
apt-get install python3-venv
You may need to use sudo with that command.  After installing the python3-venv
package, recreate your virtual environment.
Failing command: ['/var/lib/syslog-ng/python-venv/bin/python3', '-Im', 'ensurepip', '--upgrade', '--default-pip']
```
```
root@alltilla-Precision-5530:/# apt install syslog-ng-mod-python
Reading package lists... Done
Building dependency tree... Done
Reading state information... Done
... …
```
> packaging/debian: add python3-venv to mod-python deps

- .github/workflows/nightly-release.yml
- .github/workflows/stable-release.yml
- .github/workflows/test-apt-packages.yml
- .github/workflows/trigger-tests-on-packages.yml
A syntax error has been introduced in #4231.
> ci: fix syntax error in output parameter generation

- .github/workflows/devshell.yml
- .github/workflows/publish-docker-image.yml
> ci: add missing safedir setup for commit and copyright check

- news/packaging-4294.md
> news: add entry for #4294

- modules/python-modules/syslogng/modules/kubernetes/__init__.py
> kubernetes: add warning for ApiException instead of printing the stacktrace

- .github/workflows/devshell.yml
> github-actions: run devshell on ubuntu-latest

- dev-requirements.txt
- modules/python/python-debugger.c
- requirements.txt
This branch fixes a couple of bugs that rendered the interactive debugger inoperable. The problems were introduced when we did Python type support.
> Fix the Python based frontend for the interactive debugger

- lib/versioning.h
This adds more relevant contact information at the end of a syntax error report.
> versioning.h: update PRODUCT_CONTACT

- modules/java-modules/common/build.gradle
- modules/java-modules/elastic-v2/build.gradle
- modules/java-modules/hdfs/build.gradle
- modules/java-modules/http/build.gradle
- modules/java-modules/kafka/build.gradle
> java: fix build with newer gradle versions

- lib/cfg-args.c
- lib/multi-line/multi-line-factory.c
> lib: include missing headers

- tests/light/functional_tests/Makefile.am
- tests/light/src/Makefile.am
> light: add missing sources/tests to EXTRA_DIST

- CONTRIBUTING.md
> CONTRIBUTING: fix link for "Reporting Bugs"

- lib/CMakeLists.txt
- lib/Makefile.am
- lib/cfg-persist.c
- lib/cfg-persist.h
- lib/cfg.c
- lib/cfg.h
- lib/driver.c
- lib/logthrdest/logthrdestdrv.c
- modules/affile/affile-dest.c
- modules/afprog/afprog.c
- modules/afsocket/afsocket-dest.c
- modules/afsocket/afsocket-source.c
- modules/correlation/dbparser.c
- modules/correlation/groupingby.c
- modules/diskq/diskq.c
As a preparation for improving metric labeling I started this refactorm which can be submitted separately.
> Extract cfg-persist into separate module

- modules/correlation/groupingby.c
Sorry, this is a follow-up for #4390.
> correlation: add clone_id to user-specified persist name

- doc/man/dqtool.1.xml
- doc/man/loggen.1.xml
The previous link pointed to a website which did not have any "Administrator Guide". Replaced it with an updated link.
> doc: replaced obsolete admin guide links 

- scripts/CMakeLists.txt
> cmake: Fixed some file permissions during installation

- lib/healthcheck/healthcheck.c
- lib/logreader.c
- lib/logwriter.c
- lib/mainloop-io-worker.c
- lib/mainloop-io-worker.h
- lib/mainloop-worker.c
- lib/mainloop-worker.h
- modules/systemd-journal/journal-reader.c
These are the first couple of patches of #3966 that we should be able to merge without the rest.
No NEWS entry is needed.
> Mainloop refactors in preparation for threaded processing

- lib/multi-line/smart-multi-line.c
- modules/examples/inner-destinations/tls-test-validation/tls-test-validation.c
> lib/modules: fix include headers

- scl/logscale/logscale.conf
> logscale: raise workers to 20

- modules/python/python-helpers.c
- modules/python/python-main.c
> Python virtualenv warning

- modules/json/format-json.c
- modules/json/tests/test_format_json.c
- news/bugfix-4477.md
> format-json: fix adding unnecessary comma when failing to cast 

- modules/json/format-json.c
> format-json: fix base64 encoding with glib < 2.54.0

- Makefile.am
- modules/grpc/otel/Makefile.am
> otel: do not put built protos in tarball

- modules/diskq/logqueue-disk.c
> diskq: abort on corrupted restart failure

- README.md
This PR adds references to the revised markdown based documentation for AxoSyslog Core and references to the AxoSyslog container image.
> README.md: added references to AxoSyslog container images/documentation

- lib/logsource.h
- lib/scratch-buffers.c
- lib/scratch-buffers.h
- lib/tests/test_scratch_buffers.c
- modules/afsocket/afsocket-source.c
Hopes to fix certain counter over/underflow issues, likely caused by narrowing type conversions.
> Counter underflow fixes

- lib/filter/tests/test_filters_regexp.c
> filter: remove unnecessary pcre.h include

- .github/workflows/create-packages.yml
- .github/workflows/dbld-images.yml
- .github/workflows/packages.yml
- .github/workflows/test-apt-packages.yml
- .github/workflows/upload-packages.yml
- README.md
- dbld/Makefile.am
- dbld/build.manifest
- dbld/images/debian-bookworm.dockerfile
- dbld/images/ubuntu-lunar.dockerfile
- dbld/rules
- news/other-4561.md
> dbld: add Ubuntu Lunar Lobster and Debian Bookworm support 

- cmake/print_config_summary.cmake
> cmake: Added support of printing found libraries by cmake in summary list

- news/feature-4560.md
> news: add entry again for #4560

- cmake/print_config_summary.cmake
- modules/http/CMakeLists.txt
cmake: fixed linker issues after http module changes
also added some cmake scripts simplifying and enhancements
Fixes #4600
> Fix cmake builds zlib link issues

- modules/grpc/otel/otel-dest-worker.hpp
- modules/grpc/otel/otel-dest.hpp
We had a symbol missing error.
> otel: fix virtual destructor

- .github/workflows/macos.yml
> CI: Add support of macOS autotools, cmake - gcc, clang variants matrix to CI builds

- scl/cisco/plugin.conf
> scl/cisco: add yet another timestamp format

- modules/correlation/pdbtool/pdbtool.c
In patterndb, you can add extra name-value pairs following a match with the <value> tags. But the actual value of these name-value pairs were never validated against their types, meaning that an incorrect value could be set using this construct. This patch adds this validation as an extra step in "pdbtool test"
This fixes #4599
> pdbtool: add validation for types of <value> tags

- news/bugfix-4621.md
> news: add bugfix #4621

- news/other-4607.md
- news/packaging-4607.md
> news: add entries for #4607

- lib/logpipe.c
- modules/add-contextual-data/add-contextual-data.c
> logpipe: fix cloning user-specified persist name

- tests/light/src/syslog_ng/syslog_ng_executor.py
This patch allows you to run syslog-ng under gdb as it is being exercised by the light test framework.
```
To use gdb to launch syslog-ng, you will need the following (in the
container if you are running this in dbld)
* xterm
* access to your X server (-v /tmp/.X11-unix/:/tmp/.X11-unix -e DISPLAY=$$DISPLAY to docker)
You can use it by supplying --run-under=gdb to light.
syslog-ng will start up under gdb while the tests execute, gdb will
be opened in an xterm window.
```
To test, you will need to ```./dbld/rules root-login``` into your container and apt-get install xterm. You also need a couple of options specified to docker as it runs your container, I added those into my ```./dbld/rules.conf```
> Preliminary gdb support to light

- lib/filter/filter-expr-grammar.ym
- lib/template/tests/test_template.c
- modules/afamqp/afamqp-grammar.ym
- modules/afsmtp/afsmtp-grammar.ym
- modules/afstomp/afstomp-grammar.ym
- modules/correlation/correlation-grammar.ym
- modules/grpc/loki/loki-grammar.ym
- modules/http/http-grammar.ym
- modules/kafka/kafka-grammar.ym
- modules/mqtt/mqtt-grammar.ym
- modules/pseudofile/pseudofile-grammar.ym
- modules/rate-limit-filter/rate-limit-grammar.ym
- modules/rate-limit-filter/rate-limit-parser.c
- news/other-4666.md
- news/other-4679.md
Follow up for #4666.
Fixing https://github.com/syslog-ng/syslog-ng/pull/4666#discussion_r1365036653 and https://github.com/syslog-ng/syslog-ng/pull/4666#discussion_r1365085384.
> Driver specific templates followup

- .github/workflows/check-cfg-grammar-changes.yml
See:
* https://github.com/alltilla/syslog-ng-cfg-diff-pr
* https://github.com/alltilla/syslog-ng/pull/123
> github-actions: add check-cfg-grammar-changes

- tests/light/functional_tests/conftest.py
Running light tests in VSCode was buggy, as all tests failed due to the open fds check. This PR adds a workaround that enables running tests in VSCode's terminal.
No news file is needed.
> light: add workaround for running light tests in VSCode terminal

- modules/python-modules/syslogng/modules/s3/s3_destination.py
- news/bugfix-4700.md
> s3: remove unnecessary SharedBool import 

- news/feature-4698.md
- scl/CMakeLists.txt
- scl/Makefile.am
- scl/openobserve/openobserve.conf
- tests/copyright/policy
> scl: add openobserve output

- .github/workflows/draft-release.yml
> github-actions: fix draft-release workflow commenting

- tests/light/src/common/file.py
`readline()` returns if it reaches `"\n"` or `EOF`.
If `File::wait_for_lines::find_lines_in_file()` is called when only a part of a line was written to the file, `readline()` returns because of `EOF`, and only the first part of the line is processed/compared, and the rest of the line is processed separately. In this case we should try to read multiple times until `"\n"`, join the line parts, and process the joined line as a whole.
This PR implements that.
> light: fix readline() called while file is being written

- lib/on-error.c
> on-error: include string.h

- .github/workflows/create-packages.yml
- .github/workflows/dbld-images.yml
- .github/workflows/packages.yml
- dbld/Makefile.am
- dbld/builddeps
- dbld/images/fedora-39.dockerfile
- dbld/rules
resolves https://github.com/syslog-ng/syslog-ng/issues/4742
Signed-off-by: peter@czanik.hu
> dbld: Fedora 37 is EoL: use Fedora 39

- modules/grpc/otel/otel-dest-worker.cpp
> otel: log temporary and permanent logs while flushing batch

- lib/transport/transport-socket.c
- modules/afsocket/transport-unix-socket.c
This patch should fix #4597 and also contains a refactoring step to eliminate UNIX domain socket specific code duplication.
> Fix incorrect pid logging on 32bit arm

- scl/cisco/plugin.conf
- tests/light/functional_tests/parsers/cisco-parser/test_cisco_parser.py
RP is from ios-xr 7.x NCS5500 and asr9922
CLC comes from CBR8 running ios-xe 16.x and 17.x
Samples courtesy of discord user exseven.
> scl/cisco: add additional IOS samples

- modules/grpc/otel/syslog-ng-otlp-dest.cpp
- modules/grpc/otel/syslog-ng-otlp-dest.hpp
> syslog-ng-otlp: add url to persist name

- lib/timeutils/unixtime.c
- lib/timeutils/unixtime.h
- modules/grpc/loki/CMakeLists.txt
- modules/grpc/loki/loki-worker.cpp
> loki: added cmake build missing components

- modules/python/python-types.c
- news/bugfix-4790.md
> python: fix refcounting in list support 

- lib/logmsg/logmsg.c
- modules/xml/CMakeLists.txt
- modules/xml/Makefile.am
- modules/xml/tests/CMakeLists.txt
- modules/xml/tests/Makefile.am
- modules/xml/tests/test_windows_eventlog_xml_parser.c
- modules/xml/windows-eventlog-xml-parser.c
- modules/xml/windows-eventlog-xml-parser.h
- modules/xml/xml-grammar.ym
- modules/xml/xml-parser.c
- modules/xml/xml-private.h
- modules/xml/xml.c
- news/feature-4793.md
- tests/copyright/policy
> xml: add windows-eventlog-xml-parser() 

- modules/grpc/otel/otel-protobuf-formatter.cpp
- modules/grpc/otel/otel-protobuf-parser.cpp
- modules/grpc/otel/tests/test-otel-protobuf-formatter.cpp
- modules/grpc/otel/tests/test-otel-protobuf-parser.cpp
> otel: add list support

- scl/pihole/pihole.conf
- scl/qbittorrent/qbittorrent.conf
> `pihole-ftl()`: Use the new parsing of `set-severity()`

- .gitmodules
@buytenh merged our out-of-tree patches to the ivykis dev branch in a preparation for a new release of ivykis \o/
This branch intends to exercise @kira-syslogng to see if there are any dropouts, I've already tested it locally with the unit tests and light and both were positive.
If this turns green then there's nothing stopping us from using an upstream ivykis again, which is great news.
> lib/ivykis: upgrade to v0.43

- lib/logmsg/logmsg.c
- lib/logthrdest/logthrdestdrv.c
- lib/logthrdest/logthrdestdrv.h
- lib/logwriter.c
- lib/logwriter.h
This branch implements the "no-seqnum" variant of sequence numbering, which disables sequence numbers altogether.
> Add no-seqnum flag to destinations

- modules/python-modules/syslogng/modules/s3/s3_destination.py
- modules/python-modules/syslogng/modules/s3/scl/s3.conf
- news/feature-4813.md
> s3: use default AWS URL if url() is not set

- modules/mqtt/mqtt-grammar.ym
- modules/mqtt/source/mqtt-source.c
- news/feature-4824.md
> mqtt: add the topic name to $MQTT_TOPIC

- news/feature-4777.md
- news/feature-4804-1.md
- news/feature-4804-2.md
> news: #4804, #4777

- modules/affile/directory-monitor-inotify.c
- modules/affile/tests/test_wildcard_source.c
- modules/affile/wildcard-source.c
- modules/afsocket/afsocket-source.c
- modules/python-modules/syslogng/modules/kubernetes/scl/kubernetes.conf
I was playing with the AxoSyslog helm charts and the kubernetes() source emitted
a couple of ugly warnings out of the box.
this is an attempt to fix those.
> K8s limit fixes

- contrib/syslog-ng-helm-chart/templates/compress-job.yaml
- contrib/syslog-ng-helm-chart/templates/tests/test-connection.yaml
- modules/java/src/main/java/org/syslog_ng/SyslogNgClassLoader.java
Fixes security problems of undisclosed origin.
> Random fixes

- modules/grpc/otel/filterx/CMakeLists.txt
- modules/grpc/otel/filterx/Makefile.am
- modules/grpc/otel/filterx/otel-field.cpp
- modules/grpc/otel/filterx/otel-field.hpp
- modules/grpc/otel/filterx/otel-logrecord.cpp
- modules/grpc/otel/filterx/protobuf-field.cpp
- tests/light/functional_tests/filterx/test_filterx.py
Otel AnyValue type handling in Filterx
> Filter expr language #2

- modules/grpc/otel/filterx/otel-resource.cpp
- modules/grpc/otel/filterx/otel-scope.cpp
- modules/grpc/otel/tests/test-otel-filterx.cpp
> otel: filterx resource and scope setter getter

- modules/grpc/otel/CMakeLists.txt
- modules/grpc/otel/Makefile.am
- modules/grpc/otel/otel-dest-worker.cpp
- modules/grpc/otel/otel-dest-worker.hpp
- modules/grpc/otel/otel-logmsg-handles.cpp
- modules/grpc/otel/otel-logmsg-handles.h
- modules/grpc/otel/otel-logmsg-handles.hpp
- modules/grpc/otel/otel-plugin.c
- modules/grpc/otel/otel-protobuf-formatter.cpp
- modules/grpc/otel/otel-protobuf-formatter.hpp
- modules/grpc/otel/otel-protobuf-parser.cpp
- modules/grpc/otel/tests/test-otel-protobuf-formatter.cpp
- modules/grpc/otel/tests/test-otel-protobuf-parser.cpp
- modules/grpc/otel/tests/test-syslog-ng-otlp.cpp
- tests/copyright/policy
> otel: more perf improvements

- modules/grpc/otel/filterx/CMakeLists.txt
- modules/grpc/otel/filterx/Makefile.am
- modules/grpc/otel/filterx/object-otel-array.cpp
- modules/grpc/otel/filterx/object-otel-array.hpp
- modules/grpc/otel/filterx/object-otel-kvlist.cpp
- modules/grpc/otel/filterx/object-otel-kvlist.hpp
- modules/grpc/otel/filterx/object-otel-logrecord.cpp
- modules/grpc/otel/filterx/object-otel-logrecord.hpp
- modules/grpc/otel/filterx/object-otel-resource.cpp
- modules/grpc/otel/filterx/object-otel-resource.hpp
- modules/grpc/otel/filterx/object-otel-scope.cpp
- modules/grpc/otel/filterx/object-otel-scope.hpp
- modules/grpc/otel/filterx/object-otel.h
- modules/grpc/otel/filterx/otel-field.cpp
- modules/grpc/otel/filterx/otel-field.hpp
- modules/grpc/otel/otel-plugin.c
- modules/grpc/otel/tests/test-otel-filterx.cpp
Now we can set any kind of `AnyValue`, and the `attributes` field, too.
> otel: `KVList` and `Array` support

- lib/logmsg/logmsg.c
- modules/grpc/otel/filterx/otel-field.cpp
- news/bugfix-4847.md
> small otel fix and `rename()` type fix

- lib/filterx/CMakeLists.txt
- lib/filterx/expr-comparison.c
- lib/filterx/expr-comparison.h
- lib/filterx/filterx-grammar.ym
- lib/filterx/tests/CMakeLists.txt
- lib/filterx/tests/Makefile.am
- lib/filterx/tests/test_expr_comparison.c
Filter object comparison logic ported into FilterX
> Filter expr language - filter comparison ported 

- news/feature-4881.md
> news: add entry for #4881

- lib/filterx/CMakeLists.txt
- lib/filterx/Makefile.am
- lib/filterx/expr-get-subscript.c
- lib/filterx/expr-get-subscript.h
- lib/filterx/expr-isset.c
- lib/filterx/expr-isset.h
- lib/filterx/expr-message-ref.c
- lib/filterx/expr-set-subscript.c
- lib/filterx/expr-set-subscript.h
- lib/filterx/expr-unset.c
- lib/filterx/expr-unset.h
- lib/filterx/filterx-expr.h
- lib/filterx/filterx-grammar.ym
- lib/filterx/filterx-object.c
- lib/filterx/filterx-object.h
- lib/filterx/filterx-parser.c
- lib/filterx/filterx-scope.c
- lib/filterx/filterx-scope.h
- lib/filterx/object-dict-interface.c
- lib/filterx/object-dict-interface.h
- lib/filterx/object-json-array.c
- lib/filterx/object-json-object.c
- lib/filterx/object-list-interface.c
- lib/filterx/object-list-interface.h
- modules/grpc/otel/filterx/object-otel-array.cpp
- modules/grpc/otel/filterx/object-otel-array.hpp
- modules/grpc/otel/filterx/object-otel-kvlist.cpp
- modules/grpc/otel/filterx/object-otel-kvlist.hpp
- tests/light/functional_tests/filterx/test_filterx.py
This is an alternative to #4879 that sits on top of my previous branch #4886
@alltilla
> Filterx isset changes bazsi

- scl/fortigate/fortigate.conf
> scl/fortigate: set $HOST value from .fortigate.devid

- lib/filterx/filterx-eval.c
> filterx: fix expr-eval segfault

- README.md
Fixes comment https://github.com/syslog-ng/syslog-ng/commit/f10ca8221ead7091173271ce87268253f6f5ec4c
> readme: Typo fix

- lib/scanner/kv-scanner/kv-scanner.h
- modules/kvformat/CMakeLists.txt
- modules/kvformat/Makefile.am
- modules/kvformat/filterx-func-parse-kv.c
- modules/kvformat/filterx-func-parse-kv.h
- modules/kvformat/kvformat-plugin.c
- modules/kvformat/tests/CMakeLists.txt
- modules/kvformat/tests/Makefile.am
- modules/kvformat/tests/test_filterx_func_parse_kv.c
- tests/copyright/policy
- tests/light/functional_tests/filterx/test_filterx.py
kvformat parser ported to filterx
> Filterx parse_kv function

- lib/filterx/filterx-object.h
- lib/filterx/object-json-array.c
- lib/filterx/object-json-object.c
- libtest/filterx-lib.c
- libtest/filterx-lib.h
- modules/kvformat/CMakeLists.txt
- modules/kvformat/Makefile.am
- modules/kvformat/filterx-func-format-kv.c
- modules/kvformat/filterx-func-format-kv.h
- modules/kvformat/filterx-func-parse-kv.h
- modules/kvformat/kvformat-plugin.c
- modules/kvformat/tests/CMakeLists.txt
- modules/kvformat/tests/Makefile.am
- modules/kvformat/tests/test_filterx_func_format_kv.c
- tests/copyright/policy
```
format_kv(kvs_dict, optional_value_separator, optional_pair_separator)
```
> filterx: `format_kv()`

- modules/grpc/loki/loki-worker.cpp
I recently helped someone on Discord who had Loki connectivity issues and at that point I noticed
that connection errors are only logged at the debug level.
I fixed that and also added the URL to our loki related errors.
> loki: add "url" to error messages and also log about connection errors

- README.md
Resolves: https://github.com/syslog-ng/syslog-ng.github.io/issues/36
> doc: Updated the main dev site README.md according to latest doc changes

- news/feature-4544.md
news: Updated the news file of [proxied source changes](https://github.com/syslog-ng/syslog-ng/pull/4544)
> news: Updated the news file of proxied source changes

- .github/workflows/create-packages.yml
- .github/workflows/dbld-images.yml
- .github/workflows/packages.yml
- dbld/Makefile.am
- dbld/images/fedora-40.dockerfile
- dbld/rules
> dbld: support fedora-40

- .github/workflows/comment-cfg-grammar-changes.yml
> actions: comment-cfg-grammar-changes.yml use github token as GH_TOKEN

- news/other-5002.md
> news: add entry for #5002

- .github/workflows/create-packages.yml
- .github/workflows/dbld-images.yml
- .github/workflows/packages.yml
- dbld/Makefile.am
- dbld/build.manifest
- dbld/builddeps
- dbld/images/almalinux-9.dockerfile
- dbld/images/centos-stream9.dockerfile
- dbld/images/fedora-latest.dockerfile
- dbld/images/fedora-rawhide.dockerfile
- dbld/rules
- packaging/rhel/syslog-ng.spec
This PR adds three platforms and modifies a fourth. These include:
* **Fedora Rawhide** - for testing purposes, forecasting any eminent breaking changes in Fedora
* **Fedora Latest** - replaces Fedora 40 as an alias
* **AlmaLinux 9** - for building packages for Enterprise Linux 9 compatibles
* **CentOS Stream 9** - for testing purposes, forecasting any eminent breaking changes in EL9
> New DBLD Platforms

- tests/functional/messagegen.py
- tests/light/.pre-commit-config.yaml
- tests/light/functional_tests/filterx/test_filterx_scope.py
- tests/light/functional_tests/rewrites/set-pri/test_set_pri.py
- tests/light/src/common/network.py
- tests/light/src/driver_io/message_readers.py
- tests/light/src/helpers/loggen/loggen.py
This PR fixes multiple light test failures caused by python dependency upgrades.
> CI Python Fixes

- lib/cfg-block.c
Fixes #5026
Thanks to @nivelus for signaling this!
> cfg: fixed a possible not checked NULL argument during config block parsing

- modules/affile/affile-dest.c
Fixes #5025
Thanks to @nivelus for signaling this!
> affile-dest: affile_dw_set_owner can be called with NULL owner that is not handled at all

- modules/grpc/bigquery/bigquery-dest.cpp
- modules/grpc/bigquery/bigquery-dest.h
- modules/grpc/bigquery/bigquery-dest.hpp
- modules/grpc/bigquery/bigquery-grammar.ym
- modules/grpc/bigquery/bigquery-parser.c
- modules/grpc/bigquery/bigquery-worker.cpp
- modules/grpc/bigquery/bigquery-worker.hpp
- modules/grpc/loki/loki-dest.cpp
- modules/grpc/loki/loki-dest.h
- modules/grpc/loki/loki-dest.hpp
- modules/grpc/loki/loki-grammar.ym
- modules/grpc/loki/loki-parser.c
- modules/grpc/loki/loki-worker.cpp
- modules/grpc/otel/otel-dest-worker.cpp
- modules/grpc/otel/otel-dest-worker.hpp
- modules/grpc/otel/otel-dest.cpp
- modules/grpc/otel/otel-dest.h
- modules/grpc/otel/otel-dest.hpp
- modules/grpc/otel/otel-grammar.ym
- modules/grpc/otel/otel-parser.c
- news/feature-5012.md
Introduces the option to add RPC headers to certain destinations.
Backports https://github.com/axoflow/axosyslog/pull/192
> Add otel headers

- lib/cfg-block.c
- lib/logreader.c
- lib/plugin.c
- lib/template/repr.c
- modules/affile/affile-dest.c
- news/bugfix-216.md
Patches are originally coming from #4132 (by @OverOrion)
Fixes #5025
Fixes #5026
Backport of [#216](https://github.com/axoflow/axosyslog/pull/216) by @MrAnno
> Further null ptr fixes

- lib/messages.c
> event-logging: Added automatic logging of the thread_id (with tag thread_id) in each event log message for debug builds

- dbld/packages.manifest
Backport of [#222](https://github.com/axoflow/axosyslog/pull/222) by @MrAnno
> Remove hardcoded dbld python version deps

- .github/workflows/test-apt-packages.yml
Backport of [#235](https://github.com/axoflow/axosyslog/pull/235) by @alltilla
> github-actions: temp remove debian-testing official test

- lib/apphook.c
- lib/metrics/CMakeLists.txt
- lib/metrics/Makefile.am
- lib/metrics/metrics-template.c
- lib/metrics/metrics-template.h
- lib/metrics/metrics-tls-cache.c
- lib/metrics/metrics-tls-cache.h
- lib/metrics/metrics.c
- lib/metrics/metrics.h
- modules/metrics-probe/metrics-probe.c
- tests/copyright/policy
Backport of [#166](https://github.com/axoflow/axosyslog/pull/166) by @alltilla
> metrics: Factor out tls cache

- .github/workflows/publish-docker-image.yml
Based on [#191](https://github.com/axoflow/axosyslog/pull/191/files) by @MrAnno
> CI: scan docker image on CVEs

- .github/workflows/publish-docker-image.yml
- docker/Dockerfile
Seems severity setting has effect on the later runs when using sarif format?!?
> CI: reordered scan passes

- modules/affile/directory-monitor.c
> directory-monitor: ivykis cleanups must be called on main tread

- modules/afsnmp/afsnmpdest.c
- modules/afsql/afsql.h
- modules/grpc/otel/otel-source-services.hpp
- modules/riemann/riemann-worker.c
Slightly modified backport of [#262](https://github.com/axoflow/axosyslog/pull/262) by @MrAnno
> Warning elimination

- modules/grpc/otel/otel-protobuf-parser.cpp
- modules/grpc/otel/otel-protobuf-parser.hpp
> otel/ipv6: respect ipv6 compile switch

- lib/template/tests/test_macro.c
Missing test case fix of #5084
> test: added a missing fix for test if IPV6 support is disabled

- lib/cfg-tree.c
- lib/cfg-tree.h
- lib/logpipe.h
- modules/affile/affile-source.c
- modules/affile/affile-source.h
- modules/affile/file-reader.c
- modules/affile/file-reader.h
- modules/affile/stdin.c
- modules/affile/tests/test_wildcard_file_reader.c
- news/bugfix-5091.md
> Crash if the same wildcard source is used in multiple sources

- modules/grpc/bigquery/bigquery-worker.cpp
- modules/grpc/otel/filterx/object-otel-array.cpp
- modules/grpc/otel/filterx/object-otel-array.hpp
- modules/grpc/otel/filterx/object-otel-kvlist.cpp
- modules/grpc/otel/filterx/otel-field.cpp
> grpc: type usage corrections that could cause compilation errors

- CMakeLists.txt
> testing: do not search for criterion by default if testing is not turned on

- CMakeLists.txt
- modules/darwinosl/CMakeLists.txt
@HofiOne Could you please check if this works correctly for you or something must be changed?
What I want to achieve is leave default behavior unchanged, but allow a manual configuration to work correctly.
> Allow building with gcc on macOS

- lib/persist-state.c
- lib/persist-state.h
- modules/affile/file-reader.c
- modules/affile/file-reader.h
- modules/affile/tests/test_wildcard_file_reader.c
- modules/affile/wildcard-file-reader.c
- news/bugfix-5091.md
This update of https://github.com/syslog-ng/syslog-ng/issues/5090 is based on [291](https://github.com/axoflow/axosyslog/pull/291/) by @MrAnno 
> Update persist state instead of dropping it

- modules/python-modules/syslogng/modules/s3/s3_destination.py
Fixes: https://github.com/syslog-ng/syslog-ng/issues/5131
> s3: use python3.9 compatible glob()

- .github/workflows/macos.yml
- modules/grpc/CMakeLists.txt
Resolves: https://github.com/protocolbuffers/protobuf/issues/18307
> Add cmake grpc build fix

- .github/workflows/devshell.yml
- .github/workflows/macos.yml
- modules/grpc/bigquery/CMakeLists.txt
- modules/grpc/bigquery/Makefile.am
- modules/grpc/bigquery/bigquery-dest.cpp
- modules/grpc/loki/CMakeLists.txt
- modules/grpc/loki/Makefile.am
- modules/grpc/otel/CMakeLists.txt
- modules/grpc/otel/Makefile.am
- modules/grpc/otel/filterx/CMakeLists.txt
- modules/grpc/otel/filterx/Makefile.am
- modules/grpc/otel/filterx/object-otel-array.cpp
- modules/grpc/otel/filterx/object-otel-kvlist.cpp
- modules/grpc/otel/filterx/object-otel-logrecord.cpp
- modules/grpc/otel/filterx/object-otel-resource.cpp
- modules/grpc/otel/filterx/object-otel-scope.cpp
- modules/grpc/otel/otel-protobuf-formatter.cpp
- modules/grpc/protos/CMakeLists.txt
- modules/grpc/protos/Makefile.am
Related https://github.com/buytenh/ivykis/pull/38
Signed-off-by: Hofi [hofione@gmail.com](mailto:hofione@gmail.com)
> Turn on -Werror everywhere

- lib/filterx/filterx-eval.h
- lib/logmpx.c
- lib/logthrsource/logthrsourcedrv.c
- lib/logthrsource/logthrsourcedrv.h
- news/bugfix-5148.md
Backport of [#314](https://github.com/axoflow/axosyslog/pull/314) by @MrAnno
> logthrsource: fix sources getting stuck due to unclosed batches

- news/feature-5063.md
Fixes typo in feature-5063's description
> news: Fixes typo in feature-5063's description

- lib/cfg-tree.c
> cfg-tree: add trace log entry about pipe creation with persist-name

- .github/workflows/create-packages.yml
- .github/workflows/dbld-images.yml
- .github/workflows/upload-packages.yml
- README.md
- dbld/Makefile.am
- dbld/build.manifest
- dbld/rules
> dbld: ubuntu mantic builds cannot find some repos, but mantic is eol for a while, let's drop it

- .github/workflows/check-cfg-grammar-changes.yml
> CI: use the updated Check config grammar changes action

- .github/workflows/publish-docker-image.yml
- README.md
- docker/Dockerfile
- docker/entrypoint.sh
- packaging/package-indexer/indexer/deb_indexer.py
- tests/copyright/policy
> Correct the docker image and the azure package indexer

- lib/cfg-args.c
- lib/cfg-args.h
- modules/python/python-plugin.c
Backport of [#348](https://github.com/axoflow/axosyslog/pull/348) by @bazsi
> cfg-args: fix potential NULL deref in cfg_args_get_as_boolean()

- lib/logthrdest/logthrdestdrv.c
- modules/grpc/bigquery/bigquery-dest.cpp
- modules/grpc/bigquery/bigquery-dest.h
- modules/grpc/bigquery/bigquery-dest.hpp
- modules/grpc/bigquery/bigquery-grammar.ym
- modules/grpc/bigquery/bigquery-worker.cpp
- modules/grpc/common/grpc-dest-worker.cpp
- modules/grpc/common/grpc-dest-worker.hpp
- modules/grpc/common/grpc-dest.cpp
- modules/grpc/common/grpc-dest.h
- modules/grpc/common/grpc-dest.hpp
- modules/grpc/common/grpc-grammar.ym
- modules/grpc/common/grpc-source.cpp
- modules/grpc/common/metrics/grpc-metrics.cpp
- modules/grpc/loki/loki-dest.cpp
- modules/grpc/loki/loki-dest.h
- modules/grpc/loki/loki-dest.hpp
- modules/grpc/loki/loki-grammar.ym
- modules/grpc/loki/loki-worker.cpp
- modules/grpc/loki/loki-worker.hpp
- modules/grpc/otel/otel-dest-worker.cpp
- modules/grpc/otel/otel-dest-worker.hpp
- modules/grpc/otel/otel-dest.cpp
- modules/grpc/otel/otel-dest.hpp
- news/feature-5184.md
Backport of [#334](https://github.com/axoflow/axosyslog/pull/334) by @alltilla 
Depends on https://github.com/syslog-ng/syslog-ng/pull/5178
> otel, loki: support dynamic headers()

- modules/grpc/bigquery/CMakeLists.txt
- modules/grpc/bigquery/Makefile.am
- modules/grpc/bigquery/bigquery-dest.cpp
- modules/grpc/bigquery/bigquery-dest.h
- modules/grpc/bigquery/bigquery-dest.hpp
- modules/grpc/bigquery/bigquery-grammar.ym
- modules/grpc/bigquery/bigquery-parser.c
- modules/grpc/bigquery/bigquery-worker.cpp
- modules/grpc/bigquery/bigquery-worker.hpp
- modules/grpc/common/CMakeLists.txt
- modules/grpc/common/Makefile.am
- modules/grpc/common/grpc-dest.cpp
- modules/grpc/common/grpc-dest.h
- modules/grpc/common/grpc-dest.hpp
- modules/grpc/common/grpc-grammar.ym
- modules/grpc/common/grpc-parser.h
- modules/grpc/common/schema/CMakeLists.txt
- modules/grpc/common/schema/Makefile.am
- modules/grpc/common/schema/grpc-schema.cpp
- modules/grpc/common/schema/grpc-schema.hpp
- modules/grpc/loki/CMakeLists.txt
- modules/grpc/loki/Makefile.am
- modules/grpc/loki/loki-grammar.ym
- modules/grpc/otel/filterx/CMakeLists.txt
- modules/grpc/otel/filterx/Makefile.am
- modules/grpc/otel/otel-grammar.ym
- modules/grpc/protos/Makefile.am
This will be useful for other drivers that want to support setting the message schema from config.
Backport of [338](https://github.com/axoflow/axosyslog/pull/338) by @alltilla 
Depends on https://github.com/syslog-ng/syslog-ng/pull/5184
> grpc: factor out schema related functionality from bigquery to common

- .github/workflows/create-packages.yml
- .github/workflows/dbld-images.yml
- .github/workflows/packages.yml
- .github/workflows/upload-packages.yml
- dbld/packages.manifest
- dbld/rpm
> Fix dbld packaging again

- .github/workflows/dbld-images.yml
- .github/workflows/nightly-release.yml
> dbld: publish the dbld images from develop branch

- .github/ISSUE_TEMPLATE/20-documentation-issue.md
> github: update the new doc issue template to redirect the user to the new location

- lib/mainloop-worker.c
> lib/mainloop-worker: Rephrased a warning message

- lib/logpipe.c
This patch refactors log_pipe_queue() to allow tail-call-optimization, meaning gcc uses a jmp to "call" the next queue method instead of a call, thereby eliminating the stack frame of log_pipe_queue().
This means that stacktraces are shorter when measuring them with perf and may also improve a bit of performance, although it was 2-3% in my measurements, which could easily be attributed to jitter.
Backport of [426](https://github.com/axoflow/axosyslog/pull/426) by @bazsi
Depends on https://github.com/syslog-ng/syslog-ng/pull/5260
> logpipe: allow log_pipe_queue() to be tail-call-optimized

- dbld/packages.manifest
- tests/functional/test_sql.py
> devshell: let the functional tests run SQL tests

- lib/dnscache.c
- lib/scratch-buffers.c
Some performance improvements from [400](https://github.com/axoflow/axosyslog/pull/400) by @bazsi
> timeutils: performance improvements

- lib/cfg-grammar.y
- lib/cfg-parser.c
- lib/logproto/logproto-client.c
- lib/logproto/logproto-client.h
- lib/logproto/logproto-server.c
- lib/logproto/logproto-server.h
- lib/logproto/logproto-text-client.c
- modules/affile/logproto-file-writer.c
Backport of [355](https://github.com/axoflow/axosyslog/pull/355) by @bazsi
Depends on https://github.com/syslog-ng/syslog-ng/pull/5319
> Add idle timeout support for logreader based sources

- .astylerc
- .editorconfig
- news/developer-note-5331.md
- tests/copyright/policy
Backport of [550](https://github.com/axoflow/axosyslog/pull/550) by @dseomn
> editorconfig: configure editors for the project's style

- packaging/rhel/syslog-ng.spec
Add python3-tornado as RPM dependency due to webhook support.
> packaging: update the RPM spec file

- requirements.txt
Reverts syslog-ng/syslog-ng#5379
> Revert "build(deps): bump tornado from 6.4.2 to 6.5.1"

- modules/http/http-worker.c
Resolves: https://github.com/syslog-ng/syslog-ng/issues/5374
> http-worker: prevent curl from logging to stderr

- lib/timeutils/tests/test_wallclocktime.c
- lib/timeutils/wallclocktime.c
- lib/timeutils/wallclocktime.h
- news/bugfix-5386.md
Backport of [626](https://github.com/axoflow/axosyslog/pull/626) by @alltilla
> wallclocktime: strptime and strftime fixes

- .github/workflows/dbld-images.yml
- dbld/builddeps
> dbld: Use Azure's ubuntu mirror when running in github.

- modules/grpc/common/schema/grpc-schema.cpp
- modules/grpc/otel/filterx/object-otel-array.cpp
- modules/grpc/otel/filterx/object-otel-kvlist.cpp
- modules/grpc/otel/filterx/otel-field.cpp
- modules/grpc/otel/filterx/protobuf-field.cpp
- modules/grpc/otel/filterx/protobuf-field.hpp
Closes: https://github.com/syslog-ng/syslog-ng/pull/5263
> grpc: add backward compatible workarounds of protobuf 30 changes

- lib/ack-tracker/consecutive_ack_tracker.c
- modules/affile/file-reader.c
- modules/affile/wildcard-source.c
Resolves: #5436
Resolves: #5427
> Fix ack tracker crash

- .github/workflows/codeql.yml
The autobuild of C/C++ targets became broken (because of some Gradle issues).
Added an advanced CodeQL setup with manual build steps.
> CI: Create codeql.yml

- .github/workflows/dbld-images.yml
- .github/workflows/devshell.yml
- .github/workflows/freebsd.yml
- .github/workflows/macos.yml
- .github/workflows/packages.yml
- Use PRs always
- Do not use private branches
- Trigger actions on PRs, or push to branches: [ "develop", "master" ] only
> CI: Trigger actions on push to branches: [ "develop", "master" ] only

- .github/workflows/macos.yml
- contrib/Brewfile
- fixed brew openssl@3 update issue of leftover links to openssl@1
> Fix ci macos builds

- README.md
Related: https://github.com/syslog-ng/syslog-ng/pull/5517
> README.md: added package links after static indexing
