syslog-ng/syslog-ng

modules/kafka/kafka-dest-driver.c, modules/kafka/kafka-dest-driver.h, modules/kafka/kafka-dest-worker.c, news/bugfix-3711.md
RD_KAFKA_MSG_F_BLOCK flag caused that rd_kafka_prouce call blocks in case of librdkafka's internal queue filled
(see "queue.buffering.max.messages" or "queue.buffering.max.kbytes").
We set this flag only in worker threads that are not doing rd_kafka_poll (see is_poller_thread), i.e. when we have multiple worker threads e.g. with config workers(4).
This blocking call can cause that a reload or shutdown blocks infinitely if the queue filled when the kafka broker(s) not available.
UPDATE: instead of setting rd_kafka_produce to non-blocking mode, we should trigger a flush and purge when the worker threads are shutting down.
Since, the librdkafka API is thread safe [1] we don't need to lock the flush/purge operations.
[1] https://docs.confluent.io/5.5.1/clients/librdkafka/md_INTRODUCTION.html#t …
=> kafka-c: fix blocking rd_kafka_produce() calls hanging syslog-ng reload/shutdown

modules/basicfuncs/tests/test_basicfuncs.c, news/feature-3717.md, scl/CMakeLists.txt, scl/Makefile.am, scl/discord/discord.conf
This PR adds a `discord()` SCL destination to syslog-ng.
Based on @czanik's [blog post](https://www.syslog-ng.com/community/b/blog/posts/first-steps-of-sending-alerts-to-discord-and-others-from-syslog-ng-http-and-apprise).
Example usage:
```
destination {
discord(url("https://discord.com/api/webhooks/x/y"));
};
```
Options:
```
discord(
url("https://discord.com/api/webhooks/x/y")
avatar-url("https://example.domain/any_image.png")
username("$HOST-bot") # Custom bot name, accepts macros
tts(true) # Text-to-Speech message
template("${MSG:-[empty message]}") # Message to send, can't be empty
);
```
Setup guide: https://support.discord.com/hc/en-us/articles/228383668-Intro-to-Webhooks
----
API docs:
https://discord.com/developers/docs/resources/webhook#execute-webhook
The default throttle …
=> scl: add discord() destination

contrib/get-github-actions-status.py
There was a problem, where we received the status about a PR, which was opened from fork-of-someone/master.
We want to get the latest syslog-ng/master CI run from the REST API. Unfortunately, it seems that we cannot filter for the repo or the owner as I would expect to (tested with ?owner=syslog-ng and ?repo=syslog-ng).
https://docs.github.com/en/rest/reference/actions#list-workflow-runs
Knowing these, I falled back to filter out PR runs, so hopefully our merge and schedule runs will be queried after this commit.
Example of the problematic PR run:
```
{
"id": 999485327,
"name": "CI @ devshell",
"node_id": "WFR_lAHOAGRToM4A19zFzjuS748",
"head_branch": "master",
"head_sha": "73e98ab47fd54404a47d07fa12fd1cb86457bdde",
"run_number": 1680,
"event": "pull_request",
"status": "completed", …
```
=> get-github-actions-status: filter out PR runs

lib/versioning.h, modules/diskq/CMakeLists.txt, modules/diskq/Makefile.am, modules/diskq/diskq-config.c, modules/diskq/diskq-config.h, modules/diskq/diskq-grammar.ym, modules/diskq/diskq-options.c, modules/diskq/diskq-options.h, modules/diskq/diskq-parser.c, modules/diskq/diskq-plugin.c, modules/diskq/diskq.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_diskq_truncate.c, news/feature-3689.md
TODO:
---
`ftruncate()` is an expensive call.
In the current form, in case of a reliable disk-buffer when the destination acks the message, the truncate is usually called.
Let's look at the situation, where the destination can keep up with the speed of the source:
1. Incoming message, it gets written to the disk buffer, the write head moves to `RESERVED_SPACE` + `msg_size`.
2. We read the message from the disk-buffer, and send it to the destination, the read head moves to `RESERVED_SPACE` + `msg_size`.
3. The destination acks the message, the backlog_head moves to `RESERVED_SPACE` + `msg_size`.
4. At the end of the ack, we see, that the disk buffer is "empty", meaning all heads are at the same position, so we truncate the file to `RESERVED_SPACE`, and move all 3 heads there.
5. A new …
=> qdisk: don't truncate if it would make a small size difference

modules/kafka/tests/test_kafka_topic.c
Kafka was initialized with `kafka_dd_init` instead of proper `log_pipe_init`. Due to this the `LogPipe` was not considered initialized.
No news file is needed.
=> kafka/test: proper init called

modules/mqtt/CMakeLists.txt
Every module starts with ENABLE_ prefix, and the configure option was also named only after mqtt. Not mentioning destination part.
=> mqtt/cmake: follow naming convention

scl/discord/discord.conf, scl/telegram/telegram.conf
Recently, we introduced a way to mark modules as hard-requirements, so in case those modules (packages) are missing, then syslog-ng won't start.
The error message helps to show that a module (package) is probably missing.
=> Fix http requires in scls

modules/diskq/qdisk.c, modules/diskq/tests/test_diskq_truncate.c, news/bugfix-3726.md
We do not check beforehand, whether we can fit a new message to the disk-buffer, we decide to wrap the `write_head` after we wrote over the `disk-buf-size` limit.
It is possible to be just before the `disk-buf-size` with the `write_head` and write a huge message, then wrap the `write_head` to the beginning. This will change `self->file_size` to be a large value.
Let's say we set `truncate-size-ratio(1)`, so we never truncate and never change the `file_size` from that large value.
Imagine, that we handled every message, then wrote a lot of messages to the disk-buffer again, so we are just before the `disk-buf-size` limit.
We write 2 small messages, one will end just after `disk-buf-size` but still before the huge `self->file_size`, the next one will start at the beginning, and end a bit …
=> diskq: fix invalid read after disk_buf_size

modules/diskq/dqtool.c
Fix the following static build failure:
```
/data/buildroot-autobuilder/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/riscv64-buildroot-linux-musl/10.2.0/../../../../riscv64-buildroot-linux-musl/bin/ld: ./lib/.libs/libsyslog-ng.a(lib_libsyslog_ng_la-messages.o):(.sbss+0x2c): multiple definition of `verbose_flag'; modules/diskq/dqtool.o:(.sbss+0x4): first defined here
/data/buildroot-autobuilder/instance-0/output-1/host/opt/ext-toolchain/bin/../lib/gcc/riscv64-buildroot-linux-musl/10.2.0/../../../../riscv64-buildroot-linux-musl/bin/ld: ./lib/.libs/libsyslog-ng.a(lib_libsyslog_ng_la-messages.o):(.sbss+0x30): multiple definition of `debug_flag'; modules/diskq/dqtool.o:(.sbss+0x8): first defined here
```
Fixes:
- http://autobuild.buildroot.org/results/ccd0a954f6e0676db67026f8b8c898 …
=> modules/diskq/dqtool.c: fix static build

lib/cfg-grammar.y, lib/cfg-parser.c, modules/afamqp/afamqp-grammar.ym, modules/afmongodb/afmongodb-grammar.ym, modules/afmongodb/afmongodb-parser.c, modules/afsmtp/afsmtp-grammar.ym, modules/afsql/afsql-grammar.ym, modules/afstomp/afstomp-grammar.ym, modules/examples/destinations/example_destination/example_destination-grammar.ym, modules/http/http-grammar.ym, modules/http/http-parser.c, modules/java/native/java-grammar.ym, modules/kafka/kafka-grammar.ym, modules/kafka/kafka-parser.c, modules/mqtt/mqtt-grammar.ym, modules/python/python-grammar.ym, modules/redis/redis-grammar.ym, modules/riemann/riemann-grammar.ym, news/developer-note-3741.md
Not every `LogThreadedDest` implementation utilizes `batch-lines()` and `batch-timeout()`.
Similarly not every `LogThreadedDest` implementation utilizes `workers()`.
The batch-related options had the problem, where any descendant driver inherited them, even if they did not use them.
The `workers()` option had the problem, where every descendant driver needed to re-implement it in order to use it.
This PR fixes both.
---
**Note for the reviewers:**
This PR is not a simple refactor, I needed to check which threaded drivers use the batch-related options.
When reviewing, please make sure to check that I have found every driver which uses them, and that I have not put it to drivers, which do not use them.
Thanks!
=> log-threaded-dest: add grammar rules to opt-in for workers() and batch-...() options

modules/redis/CMakeLists.txt, modules/redis/Makefile.am, modules/redis/redis-grammar.ym, modules/redis/redis-worker.c, modules/redis/redis-worker.h, modules/redis/redis.c, news/feature-3732.md
This PR adds `workers()` support for the `redis()` destination driver.
This increases the throughput of the Redis destination driver.
=> Add workers() option to the Redis destination

modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/qdisk.c, modules/diskq/qdisk.h
We are currently profiling and measuring the performance of the `disk-buffer()` module in different scenarios in order to identify its bottlenecks and to improve its speed.
This PR is the first step in this adventure.
As we got familiar with the code base, we found some trivial performance-related issues, which we've fixed:
- reduced two consecutive `pwrite()` calls to a single one when writing the serialized message and its length
- removed unnecessary read/deserialization logic when skipping messages that are already available in the qreliable memory segment
- replaced heap allocations with scratch_buffers on hot paths
This resulted in a ~20% performance improvement in general.
The PR also contains refactor commits.
For reviewers:
<details>
<summary>Click to expand!</summary>
The …
=> disk-buffer: trivial performance-related fixes and refactor

modules/redis/redis-worker.c, news/bugfix-3748.md
If redis reply returned with error, we did not detect it. Simple reproduction is to configure a command that does not exists, and syslog-ng reports is as written message.
=> Handle redis reply error

modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/qdisk.c, modules/diskq/qdisk.h
It is common to have multiple source threads.
When we use disk-buffer, the message's serialization and writing it to the disk happen in the source thread.
Currently, the serialization happens while the source thread is holding the `LogQueue`'s lock. Also it is inbetween two accesses of the `QDisk`.
If we just simply move the serialization outside the lock, we are not guaranteed to have the same `QDisk` state, as we were having beforehand, so it is better to move the whole serialization between `QDisk` is ever accessed and the lock is obtained.
This can yield significant performance improvement, because while the source threads are doing their slow serialization, the destination thread can process messages from the `QDisk`. In my local measurements, this change introduced a 40-50% …
=> logqueue-disk: serialize outside of the lock in the source threads

modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, news/bugfix-3750.md
log_queue_disk_drop_message() is responsible for dropping a message
when the disk-buffer reaches its full capacity.
In case flow-control is enabled, the source will stop before the queue
becomes full, so no message loss is possible, but there are special/rare
cases when the user configures mem-buf-length() or mem-buf-size()
incorrectly, and the message has to be dropped.
log_queue_disk_drop_message() must force-suspend the source in the above
case, but we had already lost one single message by then.
log_msg_drop() not only acks the message with the specified ack type,
it also calls log_msg_unref() on the message, which should be done in
both cases to avoid leaking the memory.
=> disk-buffer(): fix a rare memory leak

modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/qdisk.c, modules/diskq/qdisk.h, news/bugfix-3752.md
We need the next tail's position and the head's position info in the reliable disk-buffer, because it is matching its memory queue's messages to the qdisk's messages by their position in the qdisk.
Currently we guess these positions on the caller side, based on the `write_head`'s and `read_head`'s position.
This guess is not always right, because for example `push_tail()` can change the `write_head` before writing to the disk.
I think accessing any of the three QDisk::`..._head`s publicly should not be allowed, because it is an implementation detail, but I did not want to refactor the whole code around that. So I only added the 2 function, which I think would be the correct to have, and used them in the respective parts of the code.
---
In the news entry, I mention that we fixed a rare …
=> qdisk: fix read and write head guessing

modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/qdisk.c, modules/diskq/tests/test_diskq.c, modules/diskq/tests/test_diskq_full.c
This PR refactors the non-reliable disk buffer and simplifies how messages are moved among queue segments.
(The trigger behind this refactor was to avoid unnecessarily (de)serialization and disk I/O operations in the move logic, but I had to drop those changes because they would have had unpleasant side effects.)
The last 2 commits improve the performance of the non-reliable disk buffer by using the entire qout when moving messages, and by eliminating a lock during qbacklog operations.
According to my measurements, this could increase the performance up to 20%.
No news file is needed, we'll add a news entry separately about the overall performance improvement we achieved.
=> Perf improvement and refactor for the non-reliable disk buffer

modules/diskq/diskq-options.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk-reliable.h, modules/diskq/logqueue-disk.c, news/feature-3754.md
This PR adds a fast-path memory queue implementation to the reliable disk-buffer, which can save time, when messages are coming in with a smaller rate, similarly to the qout memory queue in the non-reliable disk-buffer.
This queue still guarantees, that all the received messages are written to the disk as soon as possible.
Also added `qout-size()` option to reliable disk-buffer, which limits the number of messages in the new memory queue.
---
The idea behind this improvement, is that if there is space in qout, additionally to storing the serialized message on the disk, we store the message in memory, too. When we arrive to that message on the disk, we do not read it from the disk, and we do not deserialize it, but use the one, stored in the memory, and skip the one on the disk.
--- …
=> disk-buffer: add qout-like memory queue to reliable disk-buffer

modules/afsocket/afsocket-source.c, modules/afsocket/socket-options-inet.c, modules/afsocket/socket-options.c, modules/afsocket/socket-options.h, news/bugfix-3751.md
This should improve POSIX (and by extension NetBSD) compatibility as
the POSIX standard does not guarantee the inheritance of options between listening and peer sockets.
I moved the `socket_options_inet_setup_tcp_keepalive_timers()` function
after `accept()`, and created a new virtual function (`setup_peer_socket()`) in `SocketOptions`
which is redefinied in `SocketOptionsInet`.
Solves #3701
Signed-off-by: Parrag Szilárd <szilard.parrag@gmail.com>
=> afsocket: move TCP keepalive options setting after `accept()` call

modules/redis/redis-grammar.ym, modules/redis/redis-worker.c, modules/redis/redis.c, news/feature-3745.md
This PR adds `batch-lines()` support for the `redis` destination driver which increases performance.
Performance improvement is significant (8665U, 32 GiB RAM): [1]
| 8 workers, no batch-lines() option | 8 workers, batch-lines(100) |
|------------------------------------|-----------------------------|
| ~ 80k/s                            | ~ 240k/s (peak 450k/s)      |
The batching is based on the [pipelining feature of Redis](https://github.com/redis/hiredis#pipelining). We have to count the sent (appended) messages as we must retrieve as many as we sent.
I also tested that when the Redis server goes offline it will reconnect.
[1] I used the following configuration:
```
source s_local {
network(
port(4444)
max-connections(100)
log-iw-size(100000)
log-fetch-limit(1000)
);
};
destination …
```
=> Add batch-lines support to Redis destination

dbld/images/tarball.dockerfile
Debian testing has fortunately migrated to using bison 3.7.6 already, so
installing it from source is not needed anymore.
=> dbld tarball image: remove bison-3.7.6 install from source

news/developer-note-3766.md, tests/python_functional/src/helpers/loggen/loggen.py
This PR adds loggen's proxy related options to the Light framework
Signed-off-by: Parrag Szilárd <szilard.parrag@gmail.com>
=> Light: add loggen proxy options (src/dst ip/port)

lib/stats/stats-cluster.h, lib/stats/stats-control.c, lib/stats/stats-csv.c, lib/stats/stats-registry.c, lib/stats/stats.c, news/feature-3760.md, syslog-ng-ctl/commands/ctl-stats.c
This PR adds a new command line flag for `syslog-ng-ctl stats`: `--remove-orphans`.
`--remove-orphans` safely removes all counters that are not referenced by any syslog-ng stat producer objects.
The flag can be used to prune dynamic and static counters manually. This is useful, for example, when a templated file destination produces a lot of stats:
```
dst.file;#anon-destination0#0;/tmp/2021-08-16.log;o;processed;253592
dst.file;#anon-destination0#0;/tmp/2021-08-17.log;o;processed;156
dst.file;#anon-destination0#0;/tmp/2021-08-18.log;a;processed;961
...
```
Note: `stats-lifetime()` can be used to do the same automatically and periodically, but currently `stats-lifetime()` removes only dynamic counters that have a timestamp field set.
TODO
=> syslog-ng-ctl: add stats --remove-orphans

dbld/packages.manifest
- with help of gdb tool testdb can extract a backtrace from core files
Signed-off-by: Andras Mitzki <andras.mitzki@quest.com>
=> Dbld/images/Kira: Add gdb tool to kira image

lib/atomic-gssize.h, lib/logreader.c, lib/logreader.h, lib/logthrdest/logthrdestdrv.c, lib/logthrdest/logthrdestdrv.h, lib/logwriter.c, lib/stats/CMakeLists.txt, lib/stats/Makefile.am, lib/stats/aggregator/CMakeLists.txt, lib/stats/aggregator/Makefile.am, lib/stats/aggregator/stats-aggregator-registry.c, lib/stats/aggregator/stats-aggregator-registry.h, lib/stats/aggregator/stats-aggregator.c, lib/stats/aggregator/stats-aggregator.h, lib/stats/aggregator/stats-average.c, lib/stats/aggregator/stats-change-per-second.c, lib/stats/aggregator/stats-maximum.c, lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, lib/stats/stats-control.c, lib/stats/stats-registry.c, lib/stats/stats-registry.h, lib/stats/stats.c, modules/http/http-worker.c, modules/http/http.c, modules/systemd-journal/journal-reader.c
Create average/largest message size && EPS stats for 
source (important sources: network, syslog, tcp, udp) and
destination (important destination: network, syslog, tcp, upd, file, logstore, http)
Created new API for stats (can be create new aggregated stats later - for example: minimum message size)
This feature should work for every non threaded source/destination and for http threaded destiantion
=> Avg and max message size and EPS stats

.github/workflows/draft-release.yml
Example run, where the jobs only failed, because we *correctly* cannot upload the generated packages to the APT repository from a fork: https://github.com/alltilla/syslog-ng/actions/runs/1220228559
NOTE: The draft release job comments on the version bump PR prematurely. I will fix that problem in a separate PR, as it is not essential to the release.
=> draft-release: fix tarball upload

.github/workflows/draft-release.yml
See: https://github.com/actions/upload-artifact#customization-if-no-files-are-found
Example run for successful artifact upload: https://github.com/alltilla/syslog-ng/runs/3565129785?check_suite_focus=true
Example run for unsuccessful artifact upload: https://github.com/alltilla/syslog-ng/runs/3565250330?check_suite_focus=true
=> draft-release: use if-no-files-found in the correct place

lib/cfg-parser.c, lib/cfg-parser.h, news/packaging-3784.md
Starting with bison 3.8, bison generates the function declarations we have already done in `CFG_PARSER_DECLARE_LEXER_BINDING`. https://github.com/akimd/bison/blob/master/NEWS#L19
The only difference between the generated one, and our macro is a `const` qualifier before `CFG_LTYPE *yylloc`.
In order to work with both 3.8 and older bison versions, we should keep our manual function definitions in the code, but it should match with the one, bison generates.
Green macOS CI job should validate this PR: https://formulae.brew.sh/formula/bison
=> build: support build with bison 3.8

.github/workflows/nightly-packages.yml
It is most likely that forked repositories don't want to upload the
binary packages, but this step (in this form) will break their CI.
Negative test: https://github.com/szemere/syslog-ng/commit/b1489797716940bcb119da5ed31d908be9a4156c (commit is deleted from the PR) -> https://github.com/szemere/syslog-ng/actions/runs/1229853496
Positive test: https://github.com/szemere/syslog-ng/actions/runs/1229627448
=> disable package upload on forked repositories

dbld/builddeps, news/developer-note-3780.md
As new distributions use `python3` by default it makes sense to explicitly state older platforms which use `python2` instead of the other way around, so it is not necessary to add that new platform to the `python3` case.
Signed-off-by: Parrag Szilárd <szilard.parrag@gmail.com>
=> dbld: change default python case to python3

dbld/pip_packages.manifest
We need that in our internal tests.
=> dbld: add distro pip package to KIRA

contrib/Brewfile
This PR aims to fix our macOS build failure.
Signed-off-by: Parrag Szilárd <szilard.parrag@gmail.com>
=> macos: explicitly require OpenSSL 1.1

dbld/build.manifest, news/packaging-3797.md
`librdkafka-devel` 1.5.3 is available in Czanik's COPR.
`paho-c-devel` 1.3.1 is available in EPEL 7.
```
$ dbld/rules shell-centos-7
...
bash-4.2$ yum info librdkafka-devel
...
Name        : librdkafka-devel                                                                                                                                                                                       
Arch        : x86_64
Version     : 1.5.3
Release     : 1.el7
Size        : 575 k
Repo        : installed
From repo   : copr:copr.fedorainfracloud.org:czanik:syslog-ng-githead
Summary     : The Apache Kafka C library (Development Environment)
URL         : https://github.com/edenhill/librdkafka
License     : BSD
Description : librdkafka is a C/C++ library implementation of the Apache Kafka protocol,
: …
```
=> dbld: enable kafka and mqtt on centos-7

dbld/builddeps, dbld/images/debian-testing.dockerfile
This is a "backport" of the patch that fixed this warning in glib to fix our
CI.
We can drop this once 2.70.1 is released.
=> debian-testing.dockerfile: add a fix for a warning in glib2.70

Makefile.am, lib/logmsg/tests/Makefile.am, lib/logmsg/tests/dump_logmsg.c, lib/tests/Makefile.am, tests/copyright/policy
This branch adds a 'dump-logmsg' make target to generate a binary dump (in the form of a C array) of a serialized log message,
as prepared by the _serialize_message_for_test() function in test_logmsg_serialize.c
I've used these patches on top of various syslog-ng versions to generate a test set for legacy, serialized message payloads,
but merging these means that it's going to be easier to add further testcases as the serialization code changes.
=> Generate serialized messages

.github/workflows/dbld-images.yml
syslog-ng forks with uppercase letters in their names had problems building dbld images:
> invalid reference format: repository name must be lowercase
https://github.community/t/additional-function-s-lowercase-uppercase/140632
=> actions: transform container registry name to lowercase

.travis.yml, README.md
> September 30, 2021 As planned, the DST Root CA X3 cross-sign has expired,
> and we’re now using our own ISRG Root X1 for trust on almost all devices.
> If clients of your API are using OpenSSL, they must use version 1.1.0 or
> later. In OpenSSL 1.0.x, a quirk in certificate verification means that
> even clients that trust ISRG Root X1 will fail
https://letsencrypt.org/docs/dst-root-ca-x3-expiration-september-2021/
Unfortunately, it is not enough to add the mentioned Root CA to the
system's trusted certificates, an OpenSSL upgrade would have been also
required.
Instead of implementing the above workarounds, this commit upgrades to
Ubuntu Focal (from Xenial).
=> travis: upgrade to focal (fix for root CA issuue)

lib/logmsg/tests/Makefile.am
Criterion is still an optional dependency, it can only be used without
the `ENABLE_TESTING` guard in `make check` tests.
Since `noinst_PROGRAMS` builds all targets unconditionally,
an `ENABLE_TESTING` conditional has to be added manually.
Fixes #3806
=> logmsg: build dump_logmsg test tool conditionally

dbld/make
VERSION as a value is generated into Makefiles by autoconf/automake.
If we re-execute the configure script from the Makefile (which happens
automatically if configure.ac changes), this VERSION value gets exported
to configure, thus also exported to scripts/version.sh.
So even if we do have VERSION environment variable set at the time of
the make invocation, it will be clobbered:
* make sets VERSION to its own value
* re-executes configure, which picks the value as supplied by the Makefile
* this configure script writes out a new Makefile, with the same, clobbered VERSION value
The same does not happen when a full bootstrap is done, because in that
case the configure script is not invoked from within the Makefile.
I needed this change when compiling various versions of syslog-ng in the …
=> dbld/make: propagate VERSION value into the Makefile

dbld/build.manifest, dbld/images/debian-testing.dockerfile
libcriterion-dev was removed from debian-testing.
Until it gets fixed we can install criterion from their release tarball.
! Revert this, when libcriterion-dev gets fixed on debian-testing !
https://tracker.debian.org/pkg/criterion
=> dbld: install criterion from release tarball on debian-testing

lib/filter/filter-expr-grammar.ym, lib/filter/filter-throttle.c, lib/filter/filter-throttle.h
This PR adds template supports, and as a last step removes `value()` option.
`value("A")` can be replaced with `template("${A}")`.
This PR somewhat conflicts with:
*  https://github.com/syslog-ng/syslog-ng/pull/3816 (news entry)
* https://github.com/syslog-ng/syslog-ng/pull/3815 (light tests)
I'll provide patches in those, but as the result no separate news entry is needed here.
```
throttle(
template("${.journald._UID}")
rate(1)
);
```
=> Throttle filter add template support

lib/logproto/tests/test-text-server.c, libtest/mock-transport.c, libtest/tests/test_mock_transport.c
This PR contains a bugfix and some modifications for the transport mock.
We've found these while writing unit tests for #3770.
=> libtest: minor fixes for LogTransportMock

lib/stats/aggregator/stats-change-per-second.c
I found this during debugging a stats-related issue (the output was the raw format string `name: %s_%s_%s`).
No news file entry needed.
=> stats-cps: fix trace message

lib/cfg-parser.c, lib/cfg.c, lib/logreader.c, lib/logreader.h, lib/transport/tests/test_aux_data.c, lib/transport/transport-aux-data.c, lib/transport/transport-aux-data.h, lib/versioning.h, modules/afsocket/CMakeLists.txt, modules/afsocket/Makefile.am, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, modules/afsocket/afunix-source.c, modules/afsocket/compat-unix-creds.c, modules/afsocket/compat-unix-creds.h, modules/afsocket/socket-options-unix.c, modules/afsocket/socket-options-unix.h, modules/afsocket/transport-mapper-unix.c, modules/afsocket/transport-unix-socket.c, news/feature-3670.md, tests/copyright/policy
syslog-ng automatically collects information such as PID, UNIX UID/GID and similar process related information on the sender application when local logs are delivered via the unix-dgram() or unix-stream() drivers. This information becomes part of each log message, under the ".unix" prefix.
In extreme logging loads, the auxiliary data processing path might become a bottleneck, causing syslog-ng to consume more CPU than the application generating the logs (it was a Zorp instance at -v8, which is known to produce huge amount of logs).
This branch introduces a new flag, "ignore-aux-data" that allows disabling the collecting of UNIX related aux data.
=> Logreader ignore aux data flag

news/bugfix-3832.md, tests/loggen/loggen.c, tests/loggen/loggen_plugin.h
This was reported in https://github.com/syslog-ng/syslog-ng/issues/3829#issuecomment-962663348
=> Fix loggen loading plugins on non linux platforms

packaging/rhel/syslog-ng.spec
Signed-off-by: rfaircloth-splunk <rfaircloth@splunk.com>
=> packaging: add python3.9 and pacct to rpm specfile

syslog-ng-ctl/commands/verbose.c
Tiny refactor, the `dispatch_command` does exactly what is hand crafted in verbose command.
=> syslog-ng-ctl: verbose cmd use dispatch_command

lib/logproto/logproto-builtins.c, lib/logproto/logproto-client.h, lib/logproto/logproto-proxied-text-server.c, lib/logproto/logproto-proxied-text-server.h, lib/logproto/logproto-server.h, lib/logproto/logproto-text-server.c, lib/logproto/logproto-text-server.h, lib/logproto/tests/test-proxy-proto.c, news/feature-3770.md, tests/loggen/loggen.c, tests/loggen/loggen_plugin.h, tests/loggen/ssl_plugin/ssl_plugin.c, tests/python_functional/functional_tests/source_drivers/network_source/proxyprotocol/test_pp_tls_passthrough.py, tests/python_functional/src/driver_io/network/network_io.py, tests/python_functional/src/helpers/loggen/loggen.py, tests/python_functional/src/syslog_ng_config/statements/sources/network_source.py
This PR adds a new transport method `proxied-tls-passthrough` which is capable of detecting the PROXY header before the TLS payload. Loggen has been updated with the ` -proxied-passthrough ` option for testing purposes.
TODO:
~~- [x] add news file~~
Resolves #3758
=> Proxied TLS passthrough

news/bugfix-3843.md, scl/cisco/plugin.conf, tests/python_functional/functional_tests/parsers/app-parser/test_topic_syslog_raw.py
We've received an example log from the community, in which the timestamp had a leading dot.
I've slightly modified the hostname and the message parts
`<180>782431: machine1: .Nov 18 21:03:22.631 GMT: %CDP-4-NATIVE_VLAN_MISMATCH: Native VLAN mismatch discovered on TenGigabitEthernet.`
I haven't found an official documentation about the leading dot yet, only cisco community posts, e.g.:
https://community.cisco.com/t5/other-network-architecture/logging-shows-an-asterisk-quot-jan-13-11-05-40-quot/td-p/564707
https://community.cisco.com/t5/other-security-subjects/log-entries-with-a-dot-before-timestamp/td-p/590136
The leading asterisk is better documented in multiple system guides:
https://www.cisco.com/c/en/us/td/docs/routers/crs/software/crs_r4-1/system_monitoring/command/reference/sysmon_cr4 …
=> cisco-parser: allow leading dot in timestamps

contrib/balabit-initscripts/init.d
=> contrib: remove non-OSE comment from init.d script

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/rewrite/CMakeLists.txt, lib/rewrite/Makefile.am, lib/rewrite/rewrite-expr-grammar.ym, lib/rewrite/rewrite-expr-parser.c, lib/rewrite/rewrite-rename.c, lib/rewrite/rewrite-rename.h, lib/rewrite/tests/CMakeLists.txt, lib/rewrite/tests/Makefile.am, lib/rewrite/tests/test_rename.c, news/feature-3838.md
This is a native implementation of https://github.com/syslog-ng/syslog-ng/pull/3814. The interface has been tweaked a little with using positional options.
```
rewrite { rename("old_name" "new_name"); };
```
In the following cases the `rename()` does not changes the message:
* If `source()` equals to `destination()`
* If `source()` entry not present in the message
=> Rewrite rename

lib/logqueue.c, lib/logqueue.h, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk.c, news/bugfix-3851.md
The disk buffer is re-created when it detects it became corrupt, but the queued message statistics is not set accordingly.
=> reset queued stats if disk queue corrupted and restarted

.github/workflows/dbld-images.yml, dbld/rules
Sometimes an image build fails, but most of the time due to some infrastructure failure.
We discussed that we should build the other images and also upload them regularly, not just in case of special events (e.g. dbld folder's content is changed).
I've tested image build failure (in a dummy way though), see some workflow runs on my fork:
- [with synchronized output](https://github.com/gaborznagy/syslog-ng/actions/runs/1587504844)
- [with image upload](https://github.com/gaborznagy/syslog-ng/runs/4498754819) (by explicitly enabling image upload)
- [ordinary run](https://github.com/gaborznagy/syslog-ng/actions/runs/1587371301) (no image upload due to running on fork)
=> Github Actions: continue to build dbld images even if one platform fails

modules/afamqp/afamqp.c, news/bugfix-3869-2.md, news/bugfix-3869.md
There is also a minor error reporting fix.
Fixes #3820
=> amqp: drop message if it is larger than the max frame size

lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, news/feature-3792.md
This PR adds a new TLS block option: `keylog-file()` which will be used to export TLS secrets between clients/servers. This should aid debugging sessions as the specified file can be loaded into Wireshark and then Wireshark is able to decrypt the traffic.
Fixes #3592
=> Add TLS keylog capability

lib/ringbuffer.c, modules/basicfuncs/str-funcs.c, modules/dbparser/radix.c
LGTM reports gboolean bit fields as ambiguously signed declarations.
This is because `gboolean` is typedefed to `gint`, and it is implementation specific whether an int is signed or unsigned.
Since `gboolean` is meant to represent a TRUE/FALSE value, this is not a real issue.
I've added a [modified CodeQL query](https://github.com/github/codeql/blob/main/cpp/ql/src/Likely%20Bugs/AmbiguouslySignedBitField.ql) that accepts gboolean bit fields.
=> lgtm: minor fixes

lib/filter/filter-expr.c, lib/filter/filter-throttle.c, lib/filter/tests/test_filters_common.c, lib/filter/tests/test_filters_fop.c, news/bugfix-3863-2.md, news/bugfix-3863.md, tests/python_functional/functional_tests/filters/test_filter_reference.py, tests/python_functional/src/syslog_ng/syslog_ng_cli.py, tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
When cloning negated filter expressions, the negation field was left out.
This was a regression in v3.35.
Config to reproduce the issue:
```
filter f_f2 {
not (program("a") and message("b"));
};
filter f_f3 {
filter(f_f2)
};
log {
source { stdin(); };
filter(f_f3);
destination { file("/dev/stdout"); };
};
```
Prior to this fix, `f_f2` and `f_f3` produced non-identical results.
Note: this PR is about fixing the actual issue. I'm preparing another branch for some refactor around filter expressions and for another filter-related bugfix.
Reported by @hbakken on IRC.
=> Fix cloning negated filters 

modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_diskq_truncate.c, news/bugfix-3845.md
This PR does 3 things:
* Removes a layering violation in `qdisk.c` regarding message serialization.
* Fixes the crash mentioned in the title of the PR.
* Force disables compaction when saving the memory queues of non-reliable `disk-buffer` for safety reasons.
More details can be seen in the commit messages.
Signed-off-by: Balázs Barkó <Balazs.Barko@oneidentity.com>
=> qdisk: fix a race condition crash in serialization

news/bugfix-3853.md, scl/rewrite/cc-mask.conf, tests/python_functional/functional_tests/Makefile.am, tests/python_functional/functional_tests/rewrites/cc-mask/test_cc_mask_and_cc_hash.py, tests/python_functional/src/syslog_ng_config/statements/rewrite/rewrite.py, tests/python_functional/src/syslog_ng_config/syslog_ng_config.py
A user reported the VISA credit regex isn't working correctly.
More info about the regex: https://www.regular-expressions.info/creditcard.html
This site has some example credit card numbers, so can check it is working correctly: https://www.paypalobjects.com/en_GB/vhelp/paypalmanager_help/credit_card_numbers.htm
=> Fix credit card regex

.github/workflows/publish-docker-image.yml, contrib/Makefile.am, contrib/syslog-ng-helm-chart/.helmignore, contrib/syslog-ng-helm-chart/Chart.yaml, contrib/syslog-ng-helm-chart/LICENSE, contrib/syslog-ng-helm-chart/templates/NOTES.txt, contrib/syslog-ng-helm-chart/templates/_helpers.tpl, contrib/syslog-ng-helm-chart/templates/compress-job.yaml, contrib/syslog-ng-helm-chart/templates/config.yaml, contrib/syslog-ng-helm-chart/templates/deployment.yaml, contrib/syslog-ng-helm-chart/templates/hpa.yaml, contrib/syslog-ng-helm-chart/templates/pvc.yaml, contrib/syslog-ng-helm-chart/templates/service.yaml, contrib/syslog-ng-helm-chart/templates/serviceaccount.yaml, contrib/syslog-ng-helm-chart/templates/tests/test-connection.yaml, contrib/syslog-ng-helm-chart/values.yaml, dbld/prepare-release, docker/Dockerfile, docker/README.md, docker/syslog-ng.conf, news/other-3870.md, tests/copyright/policy
This PR moves our "production" Docker image from https://github.com/balabit/syslog-ng-docker to the main syslog-ng repo.
A separate docker directory has been created.
Note: this is not added as a dbld image, because most of the dbld commands do not make sense on the production syslog-ng image, which uses the syslog-ng APT repository.
A GitHub Actions job has been added that pushes the image to Docker Hub when the release is published.
Important note: APT packages has to be published before pushing the release button (we should update the Wiki if this gets in).
Example run:
https://github.com/MrAnno/syslog-ng/actions/runs/1664402242
Fixes balabit/syslog-ng-docker#38
Deprecation warning for the syslog-ng-docker repo: balabit/syslog-ng-docker#78
Since I had 2 approvals on this PR before the …
=> Publish syslog-ng Docker image automatically

contrib/selinux/syslog_ng.sh, contrib/syslog-ng-debun
Added bugfixes and enhancements to the SELinux policy installer script and syslog-ng-debun
* corrected an OS-detection related bug in the SELinux policy installer's code
* updated syslog-ng-debun's OS-detection code to cope with the same problem
* bumped the version number and updated copyright information
* updated syslog-ng-debun to gather more, useful information
(these include wec version, lsof-like information if lsof is not installed, information about socket files)
Signed-off-by: Janos SZIGETVARI jszigetvari@gmail.com
=> Bugfixes and enhancements to the SELinux policy installer script and syslog-ng-debun

dbld/builddeps, dbld/images/fedora-33.dockerfile
https://mirrors.fedoraproject.org/ often returns 503 error code, when we are trying to pull the metalink.
We can work this around by using a dedicated mirror, and not trying to look for mirrors via the metalink file at all.
The actual server was chosen from this list: https://admin.fedoraproject.org/mirrormanager/mirrors/Fedora/33/x86_64
I tried to choose a server which is EU based, and has large bandwidth.
Fixes #3882
=> dbld: workaround RPM repos for fedora-33

lib/timeutils/scan-timestamp.c, lib/timeutils/tests/test_scan-timestamp.c, news/feature-3893.md, tests/unit/test_msgparse.c
This patch implements accepting ISO8601 timestamps with a space instead of a 'T' in the middle, as this format happens a lot in the wild.
For instance ZScaler produces this syslog header:
```
<134>2022-01-27 10:32:35      reason=Allowed... # message continues
```
The patch causes syslog-ng to accept this timestamp both in RFC5424 and RFC3164 mode. I've decided this way as even if we permitted the incorrect formatting only in RFC3164 mode, I expect the same to happen in 5424 implementations too. And I know it's against the spec, but this seems to be an uphill battle.
=> Accept iso timestamp with a space instead of t

lib/msg-format.c, lib/msg-format.h, modules/syslogformat/syslog-format.c, news/feature-3891.md, tests/unit/test_msgparse.c
This flag would allow you to attempt parsing RFC5424 first without
an automatic fallback to RFC3164.
RFC3164. With this option it is possible to use drop-invalid(yes)
plus no-rfc3164-fallback, effectively being able to filter on RFC5424 only.
=> syslog-format: add support for no-rfc3164-fallback flag

dbld/builddeps, dbld/prepare-image-build
When we are building multiple images simultaneously, it is possible that `dbld/extra-files` is modified by multiple image build tasks.
Although we only copy files there, in rare scenarios it can cause a race condition.
=> dbld: use separate dirs in extra-files for each platform

lib/control/tests/test_control_cmds.c, lib/mainloop-control.c, news/bugfix-3900.md
Fix a SIGSEGV triggered by an incorrectly formatted "CONFIG"
command, received on the syslog-ng control socket.  The only known
implementation of the control protocol is syslog-ng-ctl itself, which always
sends a correct command, but anyone with access to the UNIX domain socket
`syslog-ng.ctl` (root only by default) can trigger a crash.
=> Fix SIGSEGV in the "CONFIG" command over syslog-ng-ctl

modules/diskq/tests/test_qdisk.c
qdisk/test: remove unnecessary argument, use the argument
filename argument wasn't used in `create_qdisk` function
use dq_type instead of TDISLQ_RELIABLE
Signed-off-by: Balázs Barkó <Balazs.Barko@oneidentity.com>
=> Little fix in qdisk unit test

lib/stats/stats-counter.h, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_qdisk.c, news/bugfix-3887-2.md, news/bugfix-3887.md
The reliable disk buffer maintains in-memory copies of the "beginning" and the "end" of the disk buffer for performance and flow-control purposes.
These memory buffers are not necessarily continuous slices of the disk buffer file, so they are emptied by a logic that queries the reader head of QDisk.
Currently, it is not allowed for the reader and writer heads to overlap when the buffer is full, so it is possible that the read head points to the very end of the file, but the next read will be done from the beginning of the file.
This corner case has to be taken into account when comparing the current position with in-memory copies.
Note: In the next PR, I'll try to get rid of all the reader/writer/backlog head correction trickeries. It would greatly reduce the complexity of QDisk.
Fixes …
=> disk-buffer: fix "memory leak" and inconsistent buffer handling 

lib/logproto/logproto-buffered-server.c, lib/logproto/logproto-buffered-server.h, lib/logproto/logproto-text-server.c, lib/logproto/logproto-text-server.h, lib/logproto/logproto.h, lib/logproto/tests/test-text-server.c, lib/logproto/tests/test_logproto.c, libtest/proto_lib.c, news/bugfix-3892.md
`log_proto_text_server_split_buffer()` moves data within `self->data` for which we maintain additional pointers: `buffer_start`.
This pointer needs to be updated after the `memmove()` call, otherwise it could point to partially overwritten data in case the `memmove()` operation overlaps.
A few lines below my fix, `buffer_start` is passed to a decoder function called `log_proto_text_server_get_raw_size_of_buffer()`, which could fail and report incorrect positions.
This could result in message duplication, partial message loss, but it only occurs when non-fixed length or less known fixed-length encodings are used (encodings that are not listed in `fixed_encodings`).
=> logproto: fix invalid buffer handling when encoding() is used

modules/afstomp/stomp.c, modules/diskq/dqtool.c
This patch corrects following bugs: https://github.com/syslog-ng/syslog-ng/issues/3917
Fixes  #3917
=> afstomp: this patch corrects memory-leak in stomp.c; diskq: this ptach corrects use-after-free in dqtool.c

modules/system-source/system-source.c, news/feature-3710.md
This patch was originally created by @yashmathne, see more in #3710.
I've fixed the commit message format and wrote a news entry.
----
The system-source() source driver for syslog-ng automatically identifies the system and then links the appropriate source to read the system and kernel logs from.
On macOS, since macOS version 10.8, there is no separate kernel log file, instead both system logs and kernel logs get logged onto a file named system.log. ( /var/log/system.log ).
I have modified the system-source.c file to add a file driver to this file using a function already defined for creating files drivers for the different systems in accordance with the system-source() [documentation](https://www.syslog-ng.com/technical-documents/doc/syslog-ng-open-source-edition/3.30/administration-guide …
=> system-source: added macOS system source

lib/eventlog/src/evtlog.h, lib/eventlog/src/evttags.c, lib/find-crlf.c, lib/find-crlf.h, lib/logmsg/logmsg.c, lib/logproto/logproto-builtins.c, lib/logproto/logproto-text-server.c, lib/logproto/logproto-text-server.h, lib/logproto/tests/test-text-server.c, lib/logwriter.c, lib/msg-format.c, news/feature-3913.md, tests/light/functional_tests/source_drivers/network_source/text_with_nuls/test_nul_acceptance.py, tests/light/src/syslog_ng_config/statements/sources/network_source.py, tests/loggen/file_reader.c, tests/loggen/socket_plugin/socket_plugin.c, tests/loggen/ssl_plugin/ssl_plugin.c, tests/unit/test_findcrlf.c
This patch adds a new transport "text-with-nuls" that can be used to accept log messages that have embedded NULs in them.
It is recommended to use flags(no-multi-line) on the source in this case, so that NULs are replaced with a space upon
reception. Otherwise funny things could happen.
This sample source works for me;
```
source { network(port(2000) transport(text-with-nuls) flags(no-multi-line)); };
```
Resolves #3755
=> Allow embedded nuls

lib/rewrite/rewrite-rename.c
The init phase only guards if the source, destination are empty. The grammar makes sure that at least empty string is provided.
News file not needed.
=> rename: improve configuration error message

lib/cfg.c, lib/cfg.h, lib/tests/test_lexer.c, lib/versioning.h
The plan to release syslog-ng 4.0 would be as follows:
* we are accumulating changes destined for 4.0 by merging them into
subsequent syslog-ng 3.x releases, but working in a compatible mode so
that no changes would be visible to 3.x users.
* Usually we report changes to behavior using warnings at
startup and we do this release-by-release. With 4.0, we expect a broader
set of changes that we would like to present to users as a whole. For
this reason we will suppress these warnings for changes we plan for
4.0 at least until the user explicitly indicates interest in the
experimental features.
* the user can start using the new features as follows:
- by using @version: 3.255 in a config, the warnings about changes get
enabled (while continuing to work in 3.x compatibility mode)
- by using …
=> versioning: add versioning framework for the syslog-ng 4.0 transition (4.0)

modules/afamqp/afamqp.c, news/bugfix-3929.md
`amqp_ssl_socket_new()` can return with `NULL`, which causes a segfault in `amqp_ssl_socket_set_cacert()`.
This change does not fix the problem coming from `amqp_ssl_socket_new()`, but handles its error gracefully.
Fixes #3924
=> amqp: handle error from amqp_ssl_socket_new()

modules/basicfuncs/Makefile.am, modules/basicfuncs/basic-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c, modules/basicfuncs/vp-funcs.c, news/feature-3911.md, tests/copyright/policy
These template functions can be used to:
1) convert a set of name-value pairs to a list:
$(format-json a=list($values .SDATA.*))
2) check if a name-value with a specific prefix exists:
$(if '$(list-count $(names .SDATA.*)) > 0' WE-HAVE-SDATA WE-DONT-HAVE_SDATA)
=> basicfuncs: add $(names) and $(values) template functions

.github/workflows/test-apt-packages.yml, .github/workflows/trigger-tests-on-nightly-packages.yml, .github/workflows/trigger-tests-on-stable-packages.yml
This PR is about to add some basic GitHubActions checks for APT repo packages.
The solution uses a reusable workflow concept. Which means there is a "trigger" job which can start the main workflow with different inputs. With this solution we can reduce the boilerplate codes in workflows.
Our inputs are: 
- "pkg_type" which refers for the installer type: nightly or stable
- "revision_name" which refers for the installer revision: snapshot or stable
Current checks on installed packages:
- is the installed syslog-ng revision correct related to actual package type
- are the installed syslog-ng package versions correct related to installed revision
- can syslog-ng starts with the default config
One minor question is remaining to finish this PR, when should the jobs triggered?
For now I set it …
=> WIP: GitHubActions: Reusable tests for APT packages

lib/cfg-grammar.y, lib/cfg-parser.c, lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logmsg/tests/test_log_message.c, lib/rewrite/rewrite-groupset.c, lib/value-pairs/cmdline.c, lib/value-pairs/internals.h, lib/value-pairs/tests/test_value_pairs.c, lib/value-pairs/tests/test_value_pairs_walk.c, lib/value-pairs/value-pairs.c, lib/value-pairs/value-pairs.h, libtest/cr_template.c, libtest/msg_parse_lib.c, libtest/msg_parse_lib.h, modules/afmongodb/afmongodb.c, modules/json/format-json.c, modules/json/json-parser.c, modules/json/tests/test_format_json.c, modules/json/tests/test_json_parser.c, modules/map-value-pairs/map-value-pairs-grammar.ym, modules/riemann/riemann-grammar.ym, scl/cim/template.conf, scl/discord/discord.conf, scl/ewmm/ewmm.conf, scl/graylog2/plugin.conf, scl/slack/slack.conf
This branch has been split off from #3831 and contains the first change on the road to 4.0.
It introduces typing support in json-parser() so that $(format-json) would reproduce the parsed JSON with proper types.
The branch has the following noteworthy changes:
* value-pairs based destinations and template functions become type aware, e.g. they will get the type information associated with a name-value pairs. The destination/template function may ignore this information, but if it uses it (like $(format-json)), typing would just work (tm)
* Most uses of value pairs ignore types (e.g. just uses the string representation), in other cases this might generate a compatibility concern (more on that later).
* embedded JSON arrays are converted to syslog-ng lists
* top-level JSON arrays are …
=> JSON type support (4.0)

.github/workflows/dbld-images.yml, dbld/rules
It scales better and much easier to debug what had failed.
Depending images (e.g. `tarball` -> `debian-testing`) still not resolved.
Also changed the cases when the github actions is triggered: in cases of PR/push events the github action will only start if
the content of `dbld`, the `packaging/(rhel|debian)` directories or the github actions yaml file itself change.
Example run, where `centos-7` failed: https://github.com/gaborznagy/syslog-ng/actions/runs/1924046749
=> github-actions: do concurrent image building (dbld-build-images)

.github/workflows/test-apt-packages.yml
New day, new fix for the nightly APT repo github-actions!!
Unfortunately, I didn't check before that both the patch version (e.g 3.36.1)
and the commit distance in git describe (e.g. 3.36.1.2)
had a very strict quantifier check:
I've relaxed the criteria for both of them.
Some examples of the recent package versions:
3.35.1.361.g1cd66f0-snapshot+20220226T230235
3.36.1-snapshot+20220304T230252
3.36.1.2.g134cd38-snapshot+20220307T230230
I've tested the regex against additional versions too:
3.36.1.66.g7ae5f3f-snapshot+20220308T093606
3.36.1.81.g4bfb039-snapshot+20220308T093744
Test runs:
* nightly: https://github.com/gaborznagy/syslog-ng/actions/runs/1952410456
* stable: https://github.com/gaborznagy/syslog-ng/actions/runs/1952411863
=> github-actions: more version-checking fix for nightly APT repo tests

lib/timeutils/scan-timestamp.c, lib/timeutils/tests/test_scan-timestamp.c, news/feature-3949.md
=> scan-timestamp: add support for using comma instead of a dot for frac part

lib/logmsg/tags.c, lib/logthrsource/tests/test_logthrfetcherdrv.c, lib/logthrsource/tests/test_logthrsourcedrv.c
This fixes only the unit test failure described in #3920.
The PR won't stop the race from happening in production, I just removed the unnecessary `app_config_changed()` call from the unit test.
=> Fix threaded source tests

lib/logthrdest/logthrdestdrv.h, lib/logthrdest/tests/test_logthrdestdrv.c, news/bugfix-3928.md, news/other-3928.md
logthrdestdrv: don't set sequenceId for non-local messages
The SDATA meta.sequenceId is the concept behind our SEQNUM macro, e.g.  it
is a destination specific sequence number of local messages being sent.
But this sequenceId only needs to be assigned to messages where we are the
originator, as described here:
7.3.1.  sequenceId
The "sequenceId" parameter tracks the sequence in which the
originator submits messages to the syslog transport for sending.  It
is an integer that MUST be set to 1 when the syslog function is
started and MUST be increased with every message up to a maximum
value of 2147483647.  If that value is reached, the next message MUST
be sent with a sequenceId of 1.
NOTE the word "originator" in the first sentence.  Non-local messages don't
have a locally generated SEQNUM …
=> Logthrdestdrv dont count non local messages in seq num

lib/pragma-grammar.ym, lib/versioning.h
#3896  was opened before 3.36 had been released.
=> pragma-grammar: fix version number in deprecation warnings

modules/afstomp/afstomp.c
After 3d124fb the uniqueness of the `seq_num` field is not guaranteed.
In theory this could cause a problem in the STOMP communication, but with the current implementation it works correctly.
With this commit I intend to emphasize that we do not need a unique ID in the receipt header by using the same one each time. I also added a comment which explains why it is not a problem currently, and how it could cause a problem in the future.
------------------------------------------------------------------------
Explanation:
We check the server's response before sending a new frame to it.
Because of this, we do not need a unique receipt header.
This changes if multiple workers and/or batching support is introduced.
Make sure to use a unique receipt-id if one of the above gets implemented. …
=> afstomp: always use "0" in the receipt header

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logmsg/type-hinting.c
News entry is not needed IMO.
Question for the reviewers:
* The new field in the log message hints type features on the source side, which is a 4.0 feature. I think it is not a problem, but if we want, we can show it only if 4.0 is enabled. What do you think?
=> logmsg: add "type" field to set_value()'s trace logs

dbld/build.manifest, dbld/builddeps, dbld/images/debian-testing.dockerfile
GLib2.0 is on 2.72.0 version in Debian testing!
We no longer need https://github.com/syslog-ng/syslog-ng/commit/6590edcb6df2a7a06bcea2a6d1d17d2b421fb77e
=> Fix CI: Drop glib workaround patch

contrib/Brewfile, lib/transport/tests/test_transport_factory_id.c
Criterion is now part of the official brew repository.
=> Update Criterion in macOS tests

lib/cfg.c, lib/cfg.h, lib/mainloop.c, lib/mainloop.h
This method can be used to obtain the pending configuration we wish to switch to during reload.
One of our internal modules does some questionable things at an early stage of the reload process. Those things need to acquire the pending configuration.
This logic could be delayed easily by an apphook (`AH_CONFIG_CHANGED`), but unfortunately, it is currently not possible as we register source mangle callbacks there, and those need to be registered before cfg_init() to avoid data races with threaded sources.
=> mainloop: add main_loop_get_pending_new_config()

tests/light/src/syslog_ng/syslog_ng_cli.py, tests/light/src/syslog_ng/syslog_ng_executor.py
Light has a `--run-under=` execution parameter from the beginning. It is useful for debugging purposes. With it we can tell Light we want to start syslog-ng in testcases behind a chosen tool. For now the following tools are supported (strace, valgrind):
```bash
python3 -m pytest --installdir=/install --run-under=strace functional_tests/source_drivers/file_source/test_acceptance.py
python3 -m pytest --installdir=/install --run-under=valgrind functional_tests/source_drivers/file_source/test_acceptance.py
```
In booth cases output will be generated under: 
- reports/[current-run]/strace_*.log
- reports/[current-run]/valgrind_*.log
Our dbld/devshell container already contains these two tools, so it will be works out of the box.
Somewhere in the past we have updated parameters for …
=> Light: Fix --run-under execution parameter

.github/workflows/dbld-images.yml
Currently, we try to push an image even if the build step failed.
This is a leftover of when the image build job was refactored in [edb1d06](https://github.com/syslog-ng/syslog-ng/pull/3932/commits/edb1d06371d1a3ed15f3ceacf1a79ae86de88dfa).
Previously we built the images in 1 job concurrently and then tried to push the built images.
Since even 1 image build resulted in a job failure, we used the `always()` condition in the later steps.
Thanks @MrAnno for noticing this behaviour!!! :+1:
=> github-actions/dbld-images: do not try to automatically push docker images

.github/workflows/devshell.yml, dbld/packages.manifest
pre-commit doesn't work on Debian Testing after python is upgraded to 3.10.
It seems that this issue is only going to be resolved in python 3.11
1. https://github.com/pre-commit/pre-commit/issues/2299
2. https://github.com/pre-commit/pre-commit/issues/2336
3. https://bugs.launchpad.net/ubuntu/+source/python3.10/+bug/1967920
4. https://github.com/python/cpython/issues/89576
Green CI workflow: https://github.com/gaborznagy/syslog-ng/runs/6171859432
=> devshell: workaround for python 3.10 on Debian Testing

lib/gprocess.c, lib/gprocess.h
Some internal tools reuse code parts from syslog-ng modules, which uses capabilities.
For some of these tools this is not needed, so let's allow them to disable it, similarly to `--no-caps` option of syslog-ng.
=> disable caps API

dbld/builddeps
funcparserlib v1.0.0 is released: https://github.com/vlasovskikh/funcparserlib/issues/65#issuecomment-1114668161
For more info, see: 661e546e820dfccf02813c5bfa5445c79c00efa0
=> dbld: remove setuptools version freeze

lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, news/feature-4000.md
This PR adds 2 new TLS options, which make it possible to restrict which signature/hash pairs can be used in digital signatures.
This is a TLS extension specified by RFC5246:
https://datatracker.ietf.org/doc/html/rfc5246#section-7.4.1.4.1
sigalgs:
> This sets the supported signature algorithms for TLSv1.2 and TLSv1.3.
> For clients this value is used directly for the supported signature
> algorithms extension. For servers it is used to determine which
> signature algorithms to support.
client-sigalgs:
> This sets the supported signature algorithms associated with client
> authentication for TLSv1.2 and TLSv1.3. For servers the value is used
> in the signature_algorithms field of a CertificateRequest message.
> For clients it is used to determine which signature algorithm to use
> with the …
=> Add new TLS options sigalgs() and client-sigalgs() 

contrib/syslog-ng-debun
Those files are currently used only in syslog-ng PE.
No news file entry is needed.
=> syslog-ng-debun: collect *.state files and var/reports unconditionally

lib/logreader.c, lib/logwriter.c, modules/systemd-journal/journal-reader.c, news/bugfix-3997.md
This is an alternative fix for #3985. 
fix `threaded(no)` related crash: if threaded mode is disabled for asynchronous sources and destinations (all syslog-like drivers such as tcp/udp/syslog/network qualify), a use-after-free condition can happen due to a reference counting bug in the non-threaded code path.  
The `threaded(yes)` setting has been the default since 3.6.1 so if you are using a more recent version, you are most probably unaffected.  If you are using `threaded(no)` a use-after-free condition happens as the connection closes.  The problem is more likely to surface on 32 bit platforms due to pointer sizes and struct layouts where this causes a NULL pointer ereference.
=> logreader: fix use-after-free bug in non-threaded mode

packaging/package-indexer/config/config.py, packaging/package-indexer/index-packages.py, packaging/package-indexer/indexer/deb_indexer.py, packaging/package-indexer/indexer/utils.py
We are planning to move the package indexing to GitHub Actions. With this PR I am adding some security enhancements to the indexing script.
Namely:
- Loading the config content through a CLI with `--config-content`.
- Hiding YAML loading errors, so we do not leak any part of the config in case of a load failure.
- Cleaning up the temporary `GNUPGHOME` dir after it is no longer in use.
- Moving the temporary `GNUPGHOME` dir to the script's current dir.
- Supporting passphrase protected GPG keys, with the passhprase loaded from `STDIN`.
Note, that until we start indexing the packages in GitHub Actions, these changes do not get used anywhere.
I tested the changes locally with both passphrase protected and not protected GPG keys, if you need help to try the new code out, I am happy to help. …
=> package-indexer: security enhancements

modules/basicfuncs/tests/test_basicfuncs.c
There were two issues with these:
* the $APP.VALUE wasn't using braces, so it expanded to the value
of ${APP} and ".value" concatenated
* it used numeric comparisons, meaning it compared two
non-numbers numerically, which is always true (0 == 0)
=> basicfuncs: fix comparisons in test_basicfuncs testcases

lib/cfg-tree.c, lib/filter/filter-expr.c, lib/rewrite/rewrite-groupset.c, lib/rewrite/rewrite-rename.c, lib/rewrite/rewrite-set-facility.c, lib/rewrite/rewrite-set-pri.c, lib/rewrite/rewrite-set-severity.c, lib/rewrite/rewrite-set-tag.c, lib/rewrite/rewrite-set.c, lib/rewrite/rewrite-subst.c, lib/rewrite/rewrite-unset.c, modules/dbparser/correlation.c, modules/dbparser/correlation.h, modules/dbparser/dbparser-grammar.ym, modules/dbparser/dbparser.c, modules/dbparser/groupingby.c, modules/dbparser/groupingby.h, modules/dbparser/patterndb.c, modules/dbparser/tests/CMakeLists.txt, modules/dbparser/tests/test_grouping_by.c, modules/dbparser/timerwheel.c, modules/timestamp/rewrite-fix-timezone.c, modules/timestamp/rewrite-guess-timezone.c, modules/timestamp/rewrite-set-timezone.c, news/bugfix-3957.md
grouping-by() had an incomplete log_pipe_clone() implementation, which meant that whenever we were using a grouping-by() through a reference (e.g. not as an inline block), not all settings propagated to different references.
This branch is a much larger than I anticipated as ~~it also implements state sharing between these clones and~~ refactors a lot of similarities between db-parser() and grouping-by() as they share a common infrastructure.
I added a test to get at least some unit test coverage for grouping-by(), but that's still far from complete. db-parser() has a more complete testsuite and a lot of the code is shared between the code. I do hope that @kira-syslogng and light has some end-to-end tests.
~~Albeit this branch makes it possible it does not add similar state sharing to …
=> Fix grouping-by() use through parser references

packaging/debian/syslog-ng-core.syslog-ng.logrotate
The existing logrotate config uses a postrotate command of:
invoke-rc.d syslog-ng reload > /dev/null
This fails for several reasons.
A working equivalent is:
syslog-ng-ctl reload > /dev/null
This commit simply swaps out the failing command for a working one
The consequence of the failing command is that if cron is started,
logrotate will be called and will rotate the /var/logs/messages log
written by syslog-ng but syslog-ng will continue writing to the old log
because it fails to be reloaded.
=> Correct logrotate not reloading syslog-ng

lib/compat/openssl_support.c, lib/compat/openssl_support.h, lib/tlscontext.c, modules/afsql/afsql.c, modules/cryptofuncs/cryptofuncs.c, modules/cryptofuncs/tests/test_cryptofuncs.c, modules/secure-logging/secure-logging.c, modules/secure-logging/slog.c, modules/secure-logging/slog.h, modules/secure-logging/slogencrypt/slogencrypt.c, modules/secure-logging/tests/test_secure_logging.c
This PR adds support for warning-free compilation with OpenSSL 3.0.
Kudos to @MrAnno
A few notes:
- MD4 hash template function will be deprecated  (see 67ae1c3 for details)
- Ubuntu 22.04 ships with OpenSSL 3.0 by default if you want to check the warning-free compilation without compiling OpenSSL for yourself
- Please do not merge it yet, I still want to run some (internal) tests
I was hesitant to move the modifications regarding `cmac` function to the compat layer, my reasoning:
-  It is in the `secure-log` module meaning that it is acceptable to directly interface with the OpenSSL API
If it should be in the compat layer, then please let me know and I will move it accordingly.
=> OpenSSL V3 (3.0) support

scl/CMakeLists.txt, scl/Makefile.am, scl/kubernetes/kubernetes.conf, tests/copyright/policy
This is an alternative PR inspired by #3905 but rewritten completely. It adds support for a kubernetes() source driver that tails container logs managed by kubelet and extracts both kubernetes metadata and a log content.
```
#
#
#
#
#
#
#
```
=> Kubernetes log source

lib/logmsg/logmsg.c, lib/logmsg/tags.h, lib/rewrite/rewrite-expr-grammar.ym, lib/rewrite/rewrite-set-tag.c, lib/rewrite/rewrite-set-tag.h, lib/rewrite/rewrite-set.c, lib/rewrite/tests/CMakeLists.txt, lib/rewrite/tests/Makefile.am, lib/rewrite/tests/test_rewrite.c, lib/rewrite/tests/test_set_tag.c, lib/template/templates.c, lib/template/templates.h, news/bugfix-3962.md, news/feature-3962.md, tests/copyright/policy, tests/light/functional_tests/rewrites/set-tag/test_set_tag.py
Fixes #3956 and adds both light and unit test coverage.
Test config:
```
@version: 3.36
rewrite foo {
set-tag("dyn::$PROGRAM");
};
log {
source { tcp(port(2000)); };
rewrite(foo);
rewrite { set-tag("dyn::$HOST"); };
rewrite(foo);
};
```
The result of the above config is that we get trace messages on the tags being set properly.
=> Support template expressions in set-tag()

modules/dbparser/synthetic-message.c, modules/dbparser/tests/test_patterndb.c
This completes db-parser() support for typing. Unfortunately it depends on #3948 while I thought it could go in independently. So I am rebasing this against that for now.
=> dbparser: propagate type information in <value> tags (4.0)

.github/workflows/create-packages.yml, .github/workflows/dbld-images.yml, .github/workflows/packages.yml, .github/workflows/test-apt-packages.yml, .github/workflows/upload-packages.yml, README.md, dbld/Makefile.am, dbld/build.manifest, dbld/images/ubuntu-jammy.dockerfile, dbld/rules
This PR extends the supported platforms in `dbld` with the latest Ubuntu LTS (22.04 Jammy Jellyfish).
=> Add support for Ubuntu 22.04 Jammy Jellyfish

libtest/CMakeLists.txt, libtest/Makefile.am, libtest/config_parse_lib.h, libtest/mock-logpipe.c, libtest/mock-logpipe.h, modules/dbparser/dbparser.c, modules/dbparser/groupingby.c, modules/dbparser/stateful-parser.c, modules/dbparser/stateful-parser.h, modules/dbparser/tests/test_grouping_by.c, scl/kubernetes/kubernetes.conf, tests/copyright/policy
This is a followup to #3990 to add ```inject-mode(aggregate-only) ``` to grouping-by(). It also adds a rework of test_grouping_by and improvements to libtest along the way.
Since this contains the patch to #3990 to actually use the new feature, there's an ordering dependency at the moment, #3990 should go in first and then this.
Also, this depends on my previous work on grouping-by state handling #3957 so that needs to go in too. The dependency is more in the unit tests as both PRs touched on that.
=> Grouping by inject mode aggregate only

lib/compat/openssl_support.c, lib/compat/openssl_support.h
The error:
```
../../lib/compat/openssl_support.c:285:10: error: invalid use of incomplete typedef 'DH' {aka 'struct dh_st'}
285 |   if ((dh->p == NULL && p == NULL)
....
```
https://github.com/syslog-ng/syslog-ng/runs/6852574427?check_suite_focus=true#step:7:1367
OpenSSL made its structs opaque in OpenSSL 1.1.1 hence the error for accessing its members. Here's how this piece of code ended up in the building phase:
Starting with 2022-06-11 OpenSSL 3.0 is in Debian testing (https://tracker.debian.org/pkg/openssl), which will give depracation warnings if deprecated features are used (e.g. `DH_set0_pqg`).
```
configure:17662: checking whether DH_set0_pqg is declared
configure:17662: gcc -c  -O2 -g -pthread -Werror   conftest.c >&5
conftest.c: In function 'main':
conftest.c:80:3: error: …
```
=> Fix `make distcheck` failure with OpenSSL V3.0+

.github/pull_request_template.md, CONTRIBUTING.md
This PR tries to give a gentle reminder of some steps that are required, but might not be enforced by the current CI and/or might be overlooked.
We've agreed on that it should be similar to the current issue template format, meaning that there are no checkboxes to tick as it would make things unnecessary complicated for smaller contributions. 
You can check how it looks on my fork:
https://github.com/OverOrion/syslog-ng/compare/master...OverOrion:test_branch?expand=1
I was reluctant to add the whole `PR description` from the [`CONTRIBUTING.md`](https://github.com/syslog-ng/syslog-ng/blob/master/CONTRIBUTING.md#pr-description) as they might not be in sync in the future and first time contributors are already informed to read the guidelines, nevertheless I am open to adding it, just let me …
=> Add Pull Request template

modules/dbparser/pdbtool/pdbtool.c, news/bugfix-4037.md
This branch hopes to fix #4035. 
@czanik  maybe we should add this patch to  freebsd ports  as a patch, as 3.37 was released last Friday.
=> pdbtool: postpone stats_destroy() until after log_tags_global_deinit()

scl/mariadb/audit.conf, tests/light/functional_tests/Makefile.am, tests/light/functional_tests/parsers/mariadb-parser/test_mariadb_audit_parser.py, tests/light/src/syslog_ng_config/syslog_ng_config.py
This PR integrates `mariadb-audit-parser` into Light along with some basic tests.
=> Add `mariadb-audit-parser` tests to Light

lib/logmatcher.c, lib/logmsg/logmsg.h, libtest/msg_parse_lib.c, libtest/msg_parse_lib.h, modules/regexp-parser/tests/test_regexp_parser.c, news/bugfix-4043.md, tests/unit/test_matcher.c
#3948 implemented that even named based captures would be stored as indirect values (this improves performance and makes the LogMessage->payload smaller as it avoids duplications).
However, not all name-value pairs can be stored in an indirect fashion and the abort described in #4042 was triggered as one of the assumptions was violated by the new behaviour.
Basically if you use a named capture group and use that to store a value into a builtin name-value pair (e.g. PROGRAM, PID, HOST, HOST_FROM, MESSAGE, MSGID, SOURCE) we are triggering that abort, which is a regression in 3.37. 
I am not sure how often this occurs in the wild, regexp-parser() being a relatively new feature, but we might want to release an emergency 3.37.2 release. 
With that said, this branch fixes the issue and adds new …
=> Fix log matcher abort with indirect values

lib/rewrite/rewrite-set-tag.c, lib/rewrite/tests/test_set_tag.c, news/bugfix-4065.md
Fixes #4062
The template were not saved when literal template were detected, in case of clonning the template is required to construct a new object.
=> Fix rewrite set tag

modules/afuser/afuser.c
Hello!
Previously commit 816d2eca2c already fixed an issue with a potential buffer overrun in afuser's utmp buffer handling, but it looks like there are two more issues:
* The `line` buffer was not getting null-terminated if `strncpy()` hit the requested limit of 32 chars without encountering a null terminator in `ut_line`, causing the `open()` and debug/error messages afterwards to potentially overrun the `line` buffer. This can only happen with tty device names >= 32 chars (which is rare, I know :)).
* The `ut_user/ut_name` field was used in debug/error messages as if it was null-terminated (`passed to evt_tag_str()`), but it may also be non-null-terminated, just like `ut_line`.
The two patches should fix this. I've been testing them here both with master and with syslog-ng 3.31.2, on …
=> afuser: Fix more utmp buffer overruns

.github/workflows/comment-on-missing-news-file.yml
This PR adds a new GitHub Actions job, which will give a subtle a reminder comment regarding missing news file(s) on Pull Request opening.
Currently it will only comment once, when the pull request is opened. If the PR branch had been updated and no news file was written, then it won't comment again.
See the following example runs (all other jobs had been disabled for clarity's sake):
- [news file exists](https://github.com/OverOrion/syslog-ng/pull/28)
- [news file does NOT exist](https://github.com/OverOrion/syslog-ng/pull/27)
- [news file did not exist at PR opening, was added later](https://github.com/OverOrion/syslog-ng/pull/26)
-----
Question(s) to the reviewers: 
- Should I add a link to the [news/README.md](https://github.com/syslog-ng/syslog-ng/blob/master/news/README.md) file? …
=> github-actions: add "comment on missing news file" job

lib/template/templates.c, lib/template/templates.h, lib/template/tests/test_template.c, lib/value-pairs/cmdline.c, modules/add-contextual-data/add-contextual-data.c, modules/add-contextual-data/contextual-data-record-scanner.c, news/feature-4051.md
This PR adds type support to add-contextual-data(), two things:
* the ability to propagate the type-hint from LogTemplate to a newly set name-value pair
* the ability to use type-hints in the add-contextual-data() database, in the format of "type-hint(template_expression)"
=> Type support add-contextual-data (4.0)

modules/add-contextual-data/context-info-db.c
We are using ScratchBuffers while loading the CSV input for
add-contextual-data(), and we do this in the main thread. These
buffers are not returned to the system once we start up in the
anticipation of needing more of these buffers in the future.
=> add-contextual-data: explicitly free scratch buffers we use while loading

news/create-newsfile.py
Hopefully the removal of my name will not make any changes in the upcoming actual news files :)
=> news: remove Attila and Zoltan from fixed contributors

contrib/systemd/syslog-ng@.service
Per systemd.unit(5) documentation:
In case of template units listing non template units, the listing unit
must have DefaultInstance= set, or systemctl enable must be called
with an instance name.
Since syslog-ng already ships a configuration for syslog-ng@default,
add DefaultInstance=default to the template service file. This means
that the command systemctl enable syslog-ng@.service will create the
appropriate symlink multi-user.target.wants/syslog-ng@default.service to
syslog-ng@.service. Previously it would fail.
Signed-off-by: Alvin Šipraga <alsi@bang-olufsen.dk>
=> contrib: specify DefaultInstance= in systemd template service file

tests/light/functional_tests/Makefile.am, tests/light/functional_tests/destination_drivers/network_destination/test_network_destination_transport.py, tests/light/functional_tests/destination_drivers/unix_dgram_destination/test_unix_dgram_destination.py, tests/light/functional_tests/destination_drivers/unix_stream_destination/test_unix_stream_destination.py, tests/light/src/Makefile.am, tests/light/src/common/asynchronous.py, tests/light/src/common/file.py, tests/light/src/common/network.py, tests/light/src/driver_io/file/file_io.py, tests/light/src/driver_io/file/tests/test_file_io.py, tests/light/src/driver_io/message_readers.py, tests/light/src/driver_io/network/network_io.py, tests/light/src/syslog_ng_config/statements/destinations/example_destination.py, tests/light/src/syslog_ng_config/statements/destinations/file_destination.py, tests/light/src/syslog_ng_config/statements/destinations/network_destination.py, tests/light/src/syslog_ng_config/statements/destinations/unix_dgram_destination.py, tests/light/src/syslog_ng_config/statements/destinations/unix_stream_destination.py, tests/light/src/syslog_ng_config/syslog_ng_config.py
First of all I would like to give huge thanks to @MrAnno who made the low-level part of this PR
This PR add support to use following network based destination drivers in functional testcases:
- network (with tcp and udp transport support)
- unix-dgram
- unix-stream
In the low-level part this PR introduce an asyncio based communication between the user API (from testcases) and network servers (listeners) API.
class diagramm for low-level API:
=> Light: Add support for network based destinations

CMakeLists.txt, cmake/add_tests.cmake
Our custom no-pie detection is broken due to Wunused-command-line-argument.
https://gitlab.kitware.com/cmake/cmake/-/issues/16561 has been fixed by
CMP0083, so we let CMake handle the necessary linker flags.
=> cmake: let CMake handle no-pie flags

lib/value-pairs/cmdline.c, lib/value-pairs/cmdline.h, lib/value-pairs/internals.h, lib/value-pairs/tests/test_value_pairs_walk.c, lib/value-pairs/value-pairs.c, lib/value-pairs/value-pairs.h, modules/afmongodb/afmongodb-worker.c, modules/basicfuncs/vp-funcs.c, modules/cef/format-cef-extension.c, modules/graphite/graphite-output.c, modules/json/format-json.c, modules/json/json-parser-grammar.ym, modules/json/json-parser-parser.c, modules/json/json-parser.c, modules/json/json-parser.h, modules/json/tests/test_format_json.c, modules/json/tests/test_json_parser.c, news/feature-4093-2.md, news/feature-4093.md
Unfortunately, sometimes the input JSON contains keys that have dots in them (e.g. kubernetes labels). In those cases, using
dot notation to represent the input data is ambiguous.
E.g. these JSONs parse to the same representation in syslog-ng:
```
{"foo.bar.baz": "value"}
and
{"foo":{"bar":{"baz": "value"}}}
```
This would not necessarily cause an issue, however, when we $(format-json) this, we would always get the latter even if the input is the former.
The only solution I could come up with was to add support for custom separators, e.g. instead of using dots to represent "levels" of the input, use a special character, which will not clash with other embedded dots.
Here's an example configuration:
```
@version: 3.37
log {
source { tcp(port(2000) flags(no-parse)); };
parser { …
```
=> add support for custom separators in json-parser() and $(format-json)

modules/dbparser/synthetic-message.c
This allows <value> to contain type hints like this:
```
<value name="foobar">int($PID)</value>
```
note that int() cast within the value. This then becomes a syslog-ng type information.
=> db-parser: add support for explicit type hints in <value> tags

modules/secure-logging/slog.h, tests/light/functional_tests/template_functions/slog/test_secure_logging.py
```
warning: '%lu' directive output may be truncated writing between 1 and 20 bytes into a region of size 17 [-Wformat-truncation=]
1190 |           snprintf(key, CTR_LEN_SIMPLE+1, "%"G_GUINT64_FORMAT, i);
|                                           ^~~
../modules/secure-logging/slog.c:1190:43: note: directive argument in the range [0, 18446744073709551614]
1190 |           snprintf(key, CTR_LEN_SIMPLE+1, "%"G_GUINT64_FORMAT, i);
```
=> secure-logging: fix possible invalid truncation of counters

tests/light/functional_tests/conftest.py, tests/light/functional_tests/destination_drivers/unix_dgram_destination/test_unix_dgram_destination.py, tests/light/functional_tests/destination_drivers/unix_stream_destination/test_unix_stream_destination.py, tests/light/functional_tests/source_drivers/network_source/proxyprotocol/test_pp_tls_passthrough.py, tests/light/src/common/file.py, tests/light/src/conftest.py, tests/light/src/driver_io/network/network_io.py, tests/light/src/helpers/loggen/loggen.py, tests/light/src/helpers/secure_logging/conftest.py, tests/light/src/helpers/snmptrapd/conftest.py, tests/light/src/syslog_ng/syslog_ng_cli.py, tests/light/src/syslog_ng/syslog_ng_paths.py, tests/light/src/syslog_ng_config/statements/destinations/example_destination.py, tests/light/src/syslog_ng_config/statements/destinations/file_destination.py, tests/light/src/syslog_ng_config/statements/parsers/db_parser.py, tests/light/src/syslog_ng_config/statements/sources/file_source.py, tests/light/src/syslog_ng_ctl/syslog_ng_ctl_executor.py, tests/light/src/testcase_parameters/testcase_parameters.py
Behind the working dir the main concept was the following:
- we are running Light from the following base dir: tests/light/
- in setup phase for every testcase working dir has been calculated: tests/light/reports/date/testcase_name/
- during the testrun Light will collect/write each testcase related files into the working dir
- the code uses the path reference for these files with their absoulute or relative paths
The problem with working dir concept:
- basically with the working dir we reference for the files with their absolute path
- in some cases this path can not be longer than a certain character length (~160 chars for sockets), which makes
a hard limit for reports dir and testcase file names also 
- because of this relative working dir path will be introduced 
-  because there are …
=> Light: Dropping working dir concept

.github/workflows/devshell.yml
`g_spawn_command_line_sync()` will make a call to `clone()`, which is not available by default.
By default an unprivileged container runs with the default `seccomp` policy, which has an allowlist for syscalls:
https://github.com/moby/moby/blob/master/profiles/seccomp/default.json#L59
The reason why `g_spawn_command_line_sync()` was unable to run succesfully was its call to `clone()`:
sample program
```C
#include <glib.h>
int main () {
char *stderr_buff = NULL;
char *stdout_buff = NULL;
int exit_status;
g_spawn_command_line_sync("ls -l", &stdout_buff, &stderr_buff, &exit_status, NULL);
}
```
Compile and check it with `strace`
``` shell
gcc `pkg-config --cflags glib-2.0` main.c -o spawn `pkg-config --libs glib-2.0` && strace -o spawn_strace_output.txt ./spawn
```
Looked for syscalls **NOT** …
=> github-actions: add correct docker privileges for `distcheck` step

.github/workflows/devshell.yml, dbld/packages.manifest
Signed-off-by: Andras Mitzki <andras.mitzki@quest.com>
This PR tries to fix the issue related to building devshell image
=> DevshellPackages: Update to python3.11

.github/workflows/devshell.yml
This change would collect test binaries along with core files, should the test fail.
This allows me to analyse core files from test programs and avoids the roundtrip of reproducing the test issue locally.
=> .github/workflows/devshell: collect test binaries along with corefiles

lib/logproto/logproto-buffered-server.c, lib/logproto/tests/test-text-server.c, news/bugfix-4084.md
I think skipping one byte might cause a misalignment in case of wide characters, which could possibly produce jumbled output.
Would it be better to stop processing and return the successfully converted string instead?
---
Fixes #4083
=> buffered-server: skip invalid characters 

lib/cfg-grammar.y, lib/filter/filter-cmp.c, lib/filter/filter-cmp.h, lib/filter/filter-expr-grammar.ym, lib/filter/filter-expr-parser.c, lib/filter/tests/test_filters_fop_cmp.c
This branch implements === and !== operators to verify type AND value at the same time, similarly to the same-named JavaScript
operators.
Question: is it a good idea to have both int32 and int64 types? These operators would differentiate between int64(32) and int32(32), which is probably not what we want.
=> Implement === and !== operators (4.0)

modules/redis/redis-worker.c, news/bugfix-4114.md
Fixed problem where Redis driver failed without `batch-line` option in use. 
Signed-off-by: Bálint Horváth <bal.horv.98@gmail.com>
=> redis: fix no batch mode

modules/riemann/riemann-worker.c
This PR changes the riemann driver to use GenericNumber and its associated number parsing functions, instead of using  using strtoll() without error handling.
This is not really a functional change, rather it is a refactor, but has originally been done in the scope of the 4.0 typing work.
=> Use generic-number in riemann (4.0)

README.md
Can be merged after publishing v3.38.1 packages.
=> readme: use latest Ubuntu LTS (Jammy) as apt repo example

lib/value-pairs/value-pairs.c, modules/json/tests/test_format_json.c
This one fixes a $(format-json) issue that causes format-json to work incorrectly in case --key-delimiter is used.
See the unit test case that reproduces the issue.
=> Key delimiters fix

news/other-4124.md, scl/sumologic/sumologic.conf
- The `tls()` option is now optional, Sumo Logic servers will be verified using the system's certificate store by default.
- Batching support: default is 1000 messages or 1 MiB of data, whichever comes first
- Breaking change: the default sumologic-http() payload was incomplete, only the `$MESSAGE` was sent. The new default is a JSON object, containing all name-value pairs.
todo:
=> sumologic-http() improvements

lib/persist-state.c
As `_map_header_of_entry_from_handle()` may fail, the return value
should be checked.
It could cause a crash, if the the handle or the entry was corrupted.
Signed-off-by: Szilárd Parrag <szilard.parrag@gmail.com>
=> lib: `_free_value()` fix

lib/eventlog/src/evttags.c, lib/eventlog/tests/CMakeLists.txt, lib/eventlog/tests/Makefile.am, lib/eventlog/tests/evt_tag_mem.c, lib/logproto/logproto-proxied-text-server.c
This PR adds some unit tests regarding `evt_tag_mem()`.
There is also a fix regarding `signed/unsigned` comparison in `evt_tag_mem()`.
=> Fix signed/unsigned comparison in `evt_tag_mem()` and add unit tests for it

lib/logwriter.c, lib/logwriter.h, modules/afprog/afprog.c, modules/afsocket/afinet-dest.c, modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-dest.h, news/bugfix-4044.md
We've found a crash when after reload a half-initialized dest-driver (e.g. hostname resolving fails) with kept-alive connections receives a connections close event from the remote.
=> Fix crash in case of kept alive connections

lib/cfg-grammar.y, lib/cfg-parser.c, lib/cfg.c, lib/cfg.h, lib/control/tests/test_control_cmds.c, lib/mainloop-control.c, lib/messages.c, lib/messages.h, lib/tests/test_messages.c, news/feature-4091.md, syslog-ng-ctl/CMakeLists.txt, syslog-ng-ctl/Makefile.am, syslog-ng-ctl/commands/log-level.c, syslog-ng-ctl/commands/log-level.h, syslog-ng-ctl/syslog-ng-ctl.c, tests/copyright/policy
This patch adds a feature to control the internal verbosity of syslog-ng (e.g. verbose, debug, trace) via the configuration file.
Example:
```    
options {
log-level(debug);
};
```
Possible values for log-level:
- default, just normal log messages
- verbose, normal + messages that get enabled via -v
- debug, verbose + messages that get enabled via -d
- trace, debug + messages that get enabled via -t
If the option is unset, we leave the settings as specified on the command line.
If we have log-level(default) it would override settings specified via the command line.
Rationale: in containerized environments, it is much easier to override log verbosity settings via the config file than via changing the command line options.
=> Set loglevels from config

lib/cache.c, lib/cache.h, lib/cfg.c, lib/mainloop.c, lib/plugin.c, lib/reloc.c, lib/reloc.h, lib/resolved-configurable-paths.c, lib/resolved-configurable-paths.h, lib/tests/test_cache.c, modules/dbparser/pdbtool/pdbtool.c, modules/java/native/java_machine.c, news/bugfix-4143.md, syslog-ng/main.c
This one fixes #4138, which was forwarded by @mochrul from Debian ticket 
https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=962839
=> syslog-ng/main: resolve path templates in --help output

configure.ac, lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, modules/http/CMakeLists.txt, modules/http/http-grammar.ym, modules/http/http-parser.c, modules/http/http-worker.c, modules/http/http.c, modules/http/http.h, news/feature-4082.md
This PR adds OCSP stapling support for network destinations and for the `http()` module.
When OCSP stapling verification is enabled, the server will be requested to send back OCSP status responses.
This status response will be verified using the trust store configured by the user (ca_file, ca_dir, pkcs12_file).
Note: RFC 6961 multi-stapling and TLS 1.3-provided multiple responses are currently not validated, only the peer certificate is verified.
Resolves #4013
More info:
https://www.openssl.org/docs/man1.0.2/man3/SSL_set_tlsext_status_type.html
https://www.openssl.org/docs/man1.1.1/man3/OCSP_resp_find_status.html
All new OpenSSL calls are compatible with OpenSSL 1.0.2 and above (CentOS 7 still uses v1.0.2).
Source (server) side OCSP stapling is not part of this pull request.
TODO:
---- …
=> `network`/`syslog`/`http` destination: OCSP stapling support

lib/versioning.h, modules/add-contextual-data/context-info-db.c, modules/add-contextual-data/contextual-data-record-scanner.c, modules/dbparser/synthetic-message.c, news/bugfix-4158.md
This branch adds a couple of new warnings where the new type-hinting functionality causes incompatibilities.
These are db-parser(), grouping-by() and add-contextual-data() where the template strings can now contain type-hints, which were not supported before.
These cause an incompatibility if the previous templates did contain a parenthesis, as encountered by @ryanfaircloth in issue #4155
=> Type hinting compat fixes

dbld/pip_packages.manifest, news/packaging-4174.md, requirements.txt, tests/light/conftest.py, tests/light/functional_tests/conftest.py, tests/light/functional_tests/source_drivers/network_source/proxyprotocol/test_pp_tls_passthrough.py, tests/light/src/common/blocking.py, tests/light/src/common/file.py, tests/light/src/driver_io/network/network_io.py, tests/light/src/helpers/loggen/loggen.py, tests/light/src/helpers/secure_logging/conftest.py, tests/light/src/helpers/snmptrapd/conftest.py, tests/light/src/syslog_ng/syslog_ng_cli.py, tests/light/src/syslog_ng/syslog_ng_paths.py, tests/light/src/syslog_ng/tests/test_syslog_ng_paths.py, tests/light/src/syslog_ng_config/statements/destinations/example_destination.py, tests/light/src/syslog_ng_config/statements/destinations/file_destination.py, tests/light/src/syslog_ng_config/statements/destinations/unix_dgram_destination.py, tests/light/src/syslog_ng_config/statements/destinations/unix_stream_destination.py, tests/light/src/syslog_ng_config/statements/parsers/db_parser.py, tests/light/src/syslog_ng_config/statements/sources/file_source.py, tests/light/src/syslog_ng_ctl/syslog_ng_ctl_executor.py, tests/light/src/testcase_parameters/testcase_parameters.py, tests/light/tox.ini
The main goal of this PR:
- From the early life of Light there was an endeavor to support Python 2 along with Python 3 (which I intended as an additional value)
- Python 2 has been EOL-ed
- In this PR I would like to drop the Python 2 support from Light to focusing on pure Python 3 usage
Additional tasks with this PR:
=> Light: Remove Python 2 compatibility

modules/dbparser/dbparser-grammar.ym, news/bugfix-4180.md
This patch fixes #4179, where an incorrect pointer was referenced during parsing when processing the persist-name() option.
=> dbparser: fix persist-name() setting from grammar

dbld/distcheck, dbld/tarball
This patch will add a /dbld/distcheck tool that allows me to run a distcheck locally, mimicking what github CI does.
Originally part of a larger Python related work, but since this is completely independent, opening a new PR for it.
no need for a news file.
=> dbld: add distcheck script

dbld/packages.manifest
I am adding virtualenv support in #4165 and I need python3-venv for that. This needs to go in first as I can't use the just updated
dbld image in "CI @ devshell"
=> dbld: add python3-venv package on Debian and derivatives

modules/python/python-debugger.c, modules/python/python-dest.c, modules/python/python-fetcher.c, modules/python/python-helpers.c, modules/python/python-helpers.h, modules/python/python-http-header.c, modules/python/python-logmsg.c, modules/python/python-logparser.c, modules/python/python-main.c, modules/python/python-persist.c, modules/python/python-plugin.c, modules/python/python-source.c, modules/python/python-tf.c, modules/python/python-types.c, modules/python/python-types.h, modules/python/python-value-pairs.c, modules/python/tests/test_python_logmsg.c
This PR adds support for handling name-value pairs that have datetime() as type, such name-value pairs would be propagated
to Python as a datetime.datetime instance. 
When setting a name-value pair, if the value is a datetime.datetime instance, it would similarly be converted to a value with syslog-ng's datetime as type.
```
@version: 4.0
options {
ts-format(iso);
};
python {
def foo(msg):
return msg["dtvalue"].isoformat()
};
log {
source { tcp(port(2000)); };
rewrite { set(datetime("1664885832.123") value("dtvalue")); };
destination { file("foobar" template("$(python foo)\n")); };
};
```
This is how you set the timestamp:
```
msg.set_timestamp(datetime.datetime(1977, 8, 14, 5, 30))
```
This is how you set a name-value pair with datetime type:
```
msg['dtvalue'] = …
```
=> Python: add support for datetime() type

dbld/packages.manifest
This drops Python2 related packages from dbld/packages.manifest. We are not building those packages anymore, so we don't need python2 here either.
=> dbld/packages.manifest: drop python2 packages

lib/timeutils/misc.c
This is needed for compatibility with some macOS versions due to use of `clock_gettime` in `check_nanosleep`.
=> Add compat/time.h to timeutils/misc.c

modules/python/python-fetcher.c, modules/python/python-persist.c, modules/python/python-source.c
This is chunk #3 of #4165 including two fixes, one for a deadlock in the Python wrapper of our ack tracker functionality, the other an ugly segfault if the Persist class is instantiated before cfg_init(), e.g. in the class body or in global scope.
NOTE: these could potentially be merged separately by rebasing them to master, right now it is part of the sequence as I was splitting up #4165
=> Python fix deadlock and a crash

modules/python/pylib/Makefile.am, modules/python/pylib/syslogng/dest.py, modules/python/pylib/syslogng/logger.py, modules/python/pylib/syslogng/message.py, modules/python/pylib/syslogng/parser.py, modules/python/pylib/syslogng/persist.py, modules/python/pylib/syslogng/source.py, modules/python/pylib/syslogng/template.py, modules/python/python-dest.c, modules/python/python-fetcher.c, modules/python/python-helpers.c, modules/python/python-helpers.h, tests/copyright/policy
This is the 4th chunk of #4165 adding various improvements to our Python glue layer (e.g. the syslogng package that sits between user code and our C-exported interface).
NOTE: I do have some improvements of the fake classes in this PR (those that let me write unit tests for user-code running outside of syslog-ng), which we might want to pull here. Those are in #4175 and  #4173
=> Python syslogng package improvements

libtest/cr_template.c, modules/python/python-tf.c
This is chunk 7 from #4165 which fixes a heap corruption issue in the $(python) template function that surfaced on MacOS but then I could reproduce using valgrind locally.
NOTE: this can be integrated separately by rebasing it against master.
=> Python fix heap corruption in $(python) template function

packaging/debian/control
This PR moves logrotate from being Recommended to Suggested, which causes our docker image to be a lot leaner, as logrotate pulls in a lot of dependencies.
=> Don't recommend logrotate in Debian packaging

tests/light/.pre-commit-config.yaml
flake8 has migrated to github from gitlab and the old reference does not work anymore causing the CI to fail. More information here:
https://github.com/PyCQA/flake8/issues/1290
=> light: use the github repository of flake8

modules/examples/inner-destinations/http-test-slots/Makefile.am
Found when trying to build with cmake from a tarball.
=> examples: add missing CMakeLists.txt to tarball

modules/dbparser/dbparser-grammar.ym, modules/dbparser/dbparser-parser.c, modules/dbparser/dbparser.c, modules/dbparser/dbparser.h, modules/dbparser/groupingby.c, modules/dbparser/groupingby.h, modules/dbparser/patterndb.c, modules/dbparser/patterndb.h, modules/dbparser/pdb-load.c, modules/dbparser/pdb-ruleset.c, modules/dbparser/pdb-ruleset.h, modules/dbparser/pdbtool/pdbtool.c, modules/dbparser/radix.c, modules/dbparser/radix.h, modules/dbparser/synthetic-message.c, modules/dbparser/synthetic-message.h, modules/dbparser/tests/test_grouping_by.c, modules/dbparser/tests/test_parsers_e2e.c, modules/dbparser/tests/test_patterndb.c, modules/dbparser/tests/test_radix.c, news/feature-4133.md
This intends to fix #4130
@ryanfaircloth the original idea behind db-parser() was to be the "global" parser for any kind of data. For that reason, I kind of expected all name-value pairs to be specified right within the pattern database. It kind of failed in that mission, today I view db-parser() as a useful alternative to regexps, because it is MUCH faster. But in this role you are right, prefix() would make sense.
These are just a few preparatory patches, but I wanted to submit them so 1) you see there's progress, 2) I can get feedback via the automatic tests.
In the meanwhile, could you please describe your use-case how you'd apply db-parser() to it? It would be useful to learn from. Thanks.
=> db-parser prefix() support

.github/workflows/gh-tools.sh
The stdout based solution was deprecated.
https://github.blog/changelog/2022-10-11-github-actions-deprecating-save-state-and-set-output-commands/
no news file needed
=> .github/workflows/gh-tools: use GITHUB_OUTPUT environment file

contrib/Brewfile
This fixes the macOS CI build.
(pcre was probably fetched transitively until now, but everyone is transitioning to pcre2, so should we: 4140)
=> contrib: add pcre dependency to macOS Brewfile

CMakeLists.txt, cmake/Modules/FindRiemannClient.cmake, cmake/print_config_summary.cmake
- Fixed some automake and cmake issues happened building syslog-ng on macOS (Silicon/Ventura 13.1)
- Added a module enabled state summary to configure end
=> Enhance make, cmake builds

lib/tlscontext.c, lib/tlscontext.h, modules/afsocket/afsocket-grammar.ym, modules/afsocket/afsocket-parser.c, news/feature-4209.md
SSL_CONF_cmd is added to support a common interface for setting the so many various SLL_CTX and SSL options
that can be set earlier via separated openssl function calls (e.g. SSL_CTX_set_options(), SSL_CTX_set_min_proto_version(), SSL_CTX_set_cipher_list(), etc.)
IMPORTANT:
The newly introduced `openssl-conf-cmds` always has the highest priority, its content parsed last,
so it will override any other options can be found in the `tls()` section, does not matter if they
appear before or after `openssl-conf-cmds`.
Regarding to the other `tls()` options.
As described in the SSL_CONF_cmd documentation, the order of operations is significant and executed in
top-down order, basically it means if there are multiple occurrences of setting the same option then the 'last wins'.
This is also true for …
=> #3993 support ssl conf cmd

modules/diskq/tests/test_diskq_truncate.c
The default for `truncate-size-ratio()` changed from `v3.x`'s 0.1 to `v4.x`'s 1.
The `truncate-size-ratio(1)` case is tested in the `test_diskq_truncate_size_ratio_1` unit test case, but we want tests for the v3.x's default 0.1 value, too.
=> disk-buffer: fix truncate unit test after v4 version bump

docker/Dockerfile
This PR adds jemalloc to our production image for improved performance, less memory fragmentation issues, plus a more aggressive returning of memory to the system.
It is also configurable using the MALLOC_CONF environment variable, that is explained here: https://linux.die.net/man/3/jemalloc
We also get memory profiling and leak detection.
=> docker: add jemalloc to production image

dev-requirements.txt, modules/python-modules/Makefile.am, modules/python-modules/setup.py, modules/python-modules/syslogng/message.py, modules/python-modules/syslogng/modules/kubernetes/__init__.py, modules/python-modules/syslogng/modules/kubernetes/scl/kubernetes.conf, modules/python-modules/syslogng/modules/kubernetes/tests/test_kubernetes_api_enrichment.py, news/feature-4173.md, packaging/debian/syslog-ng-mod-python.install, scl/CMakeLists.txt, scl/Makefile.am, scl/kubernetes/kubernetes.conf, scl/python/python-modules.conf, tests/copyright/policy
This work was originally done by @alltilla to implement a parser that associates kubernetes metadata with log messages. I turned this into a fully fledged Python module as implemented by #4165
=> Kubernetes metadata enrichment

modules/python-modules/Makefile.am, modules/python-modules/syslogng/confgen.py, modules/python/CMakeLists.txt, modules/python/Makefile.am, modules/python/python-confgen.c, modules/python/python-confgen.h, modules/python/python-dest.c, modules/python/python-helpers.c, modules/python/python-helpers.h, modules/python/python-main.c, tests/copyright/policy
This PR is split off from #4175 and implements Python based confgen. The original confgen module allows someone to write an external script/program to generate parts of the syslog-ng configuration.
This PR brings this into the syslog-ng process by allowing you to execute a Python function instead of the external script. An example how this can be used is in #4175 or this example:
```
@version: 4.0
python {
from syslogng import register_config_generator
def generate_foobar(args):
print(args)
return "tcp(port(2000))"
register_config_generator("source", "foobar", generate_foobar)
};
log {
source { foobar(this(is) a(value)); };
destination { file("logfile"); };
};
```
Please notice that the source declaration in the log statements towards the end of the example uses the foobar() source. That …
=> Python based confgen (4.0)

modules/riemann/riemann-worker.c, news/bugfix-4238.md
=> riemann: report flush errors with msg_error() instead of trace

configure.ac
This makes a bit of a difference when configuring:
`--disable-all-modules --enable-python`
Before: python enabled, python-modules enabled
After:  python enabled, python-modules disabled
I think we want the latter to happen.
=> configure: add python-modules to all-modules

configure.ac, modules/python-modules/Makefile.am
This change adds a new setting for --with-python-packages: "none" specifies that we should not install dependencies in any way while installing our own modules.  This allows the downstream distributor to include our Python modules without having to deploy their Python dependencies in the build environment.  This will mean that unit tests will not be able to execute, but apart from that the code is installed.
This can then be further customized by culling code that does not apply to a specific target platform.
=> configure.ac: add --with-python-packages=none

lib/timeutils/cache.c, modules/python/tests/Makefile.am, modules/python/tests/test_python_logmsg.c
No NEWS file is needed, especially until the fixes in this branch are confirmed.
@yurivict I couldn't reproduce the test_python_logmsg breakage on my local FreeBSD box (e.g. as you reported it in #4230), but while testing that I've found an unrelated issue that I've fixed in this branch. 
Can you please check if it fixes both issues in your environment? Thanks.
=> Freebsd unit test fixes

.github/workflows/test-apt-packages.yml
This is an emergency PR to help resolve our 4.0.0 release related issue. It adds coverage for smoke testing .deb packages against Debian's official packages, not just against our own, previous version.
The PR does not touch code, except a .github workflow and should cause the nightly to fail (which it should have previously as well).
Once nightly fails, I can resolve that using the packaging fix I have in #4252
=> .github/workflows/test-apt-packages: test against Debian's official packages

packaging/debian/control, packaging/debian/syslog-ng-core.install, packaging/debian/syslog-ng-scl.install
To mimic how syslog-ng is packaged on Debian, supply an "scl" package to contain all our SCL files.
This resolves an issue with updating from Debian installed syslog-ng to our own packages that caused problems in 4.0.0
=> packaging/debian: add a syslog-ng-scl package

packaging/debian/control
Due to our tests failing while upgrading Ubuntu bionic's syslog-ng 3.13.1 package.
=> packaging/debian: add Replaces/Breaks lines to syslog-ng-scl

.github/workflows/comment-on-version-bump-pr.yml, .github/workflows/create-packages.yml, .github/workflows/dbld-images.yml, .github/workflows/devshell.yml, .github/workflows/draft-release.yml, .github/workflows/index-packages.yml, .github/workflows/macos.yml, .github/workflows/nightly-release.yml, .github/workflows/package-indexer-checks.yml, .github/workflows/packages.yml, .github/workflows/publish-docker-image.yml, .github/workflows/stable-release.yml, .github/workflows/test-apt-packages.yml, .github/workflows/upload-packages.yml, .github/workflows/version-bump.yml
Currently there are some warnings in the CI (see https://github.com/syslog-ng/syslog-ng/actions/runs/3608033376 for example).
> The ubuntu-18.04 environment is deprecated, consider switching to ubuntu-20.04(ubuntu-latest), or ubuntu-22.04 instead. For more details see https://github.com/actions/virtual-environments/issues/6002
This PR addresses the first two (as they are straightforward to fix) and I will happily fix the `ubuntu-18.04` environment deprecation as well, just tell me which version it should be bumped to.
=> GitHub Actions: fix (some) deprecation warnings

lib/mainloop-call.c
The patches in this branch fixes #4258. 
Thanks a lot for @chucksilvers for the diagnosis and the proposed fix. At the end I wasn't using the proposed fix as it was, but I did included a Reported-By header. This fix would probably not exist today if it wasn't your hard work to reproduce and diagnose the issue.
=> Fix mainloop call crash on freebsd

modules/timestamp/CMakeLists.txt, modules/timestamp/Makefile.am, modules/timestamp/tests/CMakeLists.txt, modules/timestamp/tests/Makefile.am, modules/timestamp/tests/test_format_date.c, modules/timestamp/tf-format-date.c, modules/timestamp/tf-format-date.h, modules/timestamp/timestamp-plugin.c, news/feature-4202.md, tests/copyright/policy
$(format-date [options] format-string [timestamp])
$(format-date) takes a timestamp in the DATETIME representation and formats it according to an strftime() format string.  The DATETIME representation in syslog-ng is a UNIX timestamp formatted as a decimal number, with an optional fractional part, where the seconds and the fraction of seconds are separated by a dot.
If the timestamp argument is missing, the timestamp of the message is used.
Options:
--time-zone <TZstring> -- override timezone of the original timestamp
=> modules/timestamp: add $(format-date) template function

.github/workflows/devshell.yml
Maybe
```
container:
image: ...
options: --user root
```
as an alternative.
=> ci: setup Git safe directories for Docker-based CI runs

lib/afinter.c, lib/apphook.c, lib/apphook.h, lib/cfg-tree.c, lib/cfg-tree.h, lib/cfg.c, lib/logpipe.h, lib/logqueue-fifo.c, lib/logqueue.c, lib/logthrdest/logthrdestdrv.c, lib/logthrdest/tests/test_logthrdestdrv.c, lib/logthrsource/logthrsourcedrv.c, lib/logthrsource/logthrsourcedrv.h, lib/logthrsource/tests/test_logthrfetcherdrv.c, lib/logthrsource/tests/test_logthrsourcedrv.c, lib/mainloop-io-worker.c, lib/mainloop-worker.c, lib/mainloop-worker.h, lib/tests/test_cfg_tree.c, lib/tests/test_logqueue.c, modules/diskq/tests/test_diskq.c, modules/http/tests/test_http-signal_slot.c, modules/mqtt/destination/mqtt-worker.c, modules/mqtt/source/mqtt-source.c, modules/python/python-source.c, news/developer-note-3969.md
This is a spin-off from #3966 which merges the thread ID space for worker threads and associates a thread_id even with
threads spawned by LogThreadedSourceDriver. This will enable the scalable input processing in LogQueueFifo and makes a few things simpler.
It also increases the number of supported threads to 256 which is becoming a simple compile-time constant, instead of a constraint imposed by the underlying data structure (the previous limit of 64 being the number of bits in a guint64).
While #3966 still depends on an ivykis change (https://github.com/buytenh/ivykis/issues/24) but I don't want to stall the commits that make sense even without the ivykis dependency.
=> Add scalable FIFO support to LogThreadedSource based sources

lib/transport/tls-context.c, lib/transport/tls-context.h
> Some TLS implementations do not send the mandatory close_notify alert on
> shutdown. If the application tries to wait for the close_notify alert but
> the peer closes the connection without sending it, an error is generated.
Error message:
> error:0A000126:SSL routines::unexpected eof while reading
This option disables above error messages but enables the possibility of undetected truncation attacks.
Do not use this option unless you are actively hit by this error message, AND you use an acknowledged protocol type that prevents/detects truncation, AND you have no control over fixing the other side that does not send close_notify as it should.
In any other cases, update/fix the other party that does not send close_notify properly.
=> tlscontext: add ignore-unexpected-eof option for TLS

lib/logqueue.h, lib/mainloop-worker.c, news/bugfix-4282.md
Reproduction steps:
`--worker-threads=1` and a network source with an active connection
=> Fix worker warning

lib/secret-storage/secret-storage.c, news/bugfix-4276.md
A small bugfix concerning proper shutdown.
the bug concerns the mutex guarding the initialisation of secret-storage, where the mutex has been locked, but no unlock is present.
=> Secret-storage no unlock fix

configure.ac, modules/http/CMakeLists.txt, modules/http/http-worker.c
../modules/http/http-worker.c: In function '_setup_static_options_in_curl': ../modules/http/http-worker.c:163:7: warning: 'CURLOPT_REDIR_PROTOCOLS' is deprecated: since 7.85.0. Use CURLOPT_REDIR_PROTOCOLS_STR [-Wdeprecated-declarations]
163 |       curl_easy_setopt(self->curl, CURLOPT_REDIR_PROTOCOLS, CURLPROTO_HTTP | CURLPROTO_HTTPS);
|       ^~~~~~~~~~~~~~~~
In file included from ../modules/http/http-curl-header-list.h:31,
from ../modules/http/http-worker.h:30,
from ../modules/http/http-worker.c:24:
/usr/include/x86_64-linux-gnu/curl/curl.h:1755:3: note: declared here
1755 |   CURLOPTDEPRECATED(CURLOPT_REDIR_PROTOCOLS, CURLOPTTYPE_LONG, 182,
|   ^~~~~~~~~~~~~~~~~
=> http: fix curl related warning

.github/workflows/publish-docker-image.yml
`gh_output` can not export multi-line output, and it is not trivial to do that safely:
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#multiline-strings
(see the warning about script injection).
=> ci: fix multiline output issue with tags

.gitignore, modules/systemd-journal/tests/journald-mock.c
This PR fixes the broken mock part of journald integration tests when --with-systemd-journal=optional configure option is used
Also added  some builds genereated leftover to the .gitignore
fixes: #4287
=> Redeclaration-errors-with-older-gcc-versions-4287

modules/python/python-main.c
Our devshell CI is red on master as long as this is not merged.
This is an attempt to work around
https://github.com/python/cpython/issues/101471 until a more permanent solution is found.
@alltilla @MrAnno @HofiOne could you please review this so I can expedite merging this? Thanks
=> python: workaround Python 3.11 PYTHONPATH issue

modules/systemd-journal/journald-subsystem.h
This patch fixes #4300 that was a regression from #4225.
=> systemd-journal: fix --with-systemd-journal=optional mode

dbld/builddeps
pip can fail with setuptools>=66 if there are system packages installed which do not comply with PEP440:
https://github.com/pypa/setuptools/issues/3772#issuecomment-1398809718
As long as our supported distros have invalidly named packages, this will be an issue.
Either debian package maintainers start to conform PEP440 versioning, or setuptools loosens this strictness or this workaround sticks for a while.
Either way, we need to see make or CI green, so until one of the above happens I think we should go with this workaround.
=> dbld/builddeps: workaround setuptools 66 PEP440 enforcement

.github/workflows/macos.yml
rabbitmq-c 0.12.0 broke the pc file version, which breaks our minimum version check. Once it is fixed, we should reenable amqp.
https://github.com/alanxz/rabbitmq-c/issues/755
=> github-actions/macos: temporarily disable amqp

dbld/build.manifest, dbld/images/debian-testing.dockerfile
Criterion was dropped from Debian testing because of an FTBFS (failed to build from source).
Criterion fails to build, as there was a minor change in nanopb command line processing, which causes the criterion.options file to not be found while processing the protobuf declarations.
This is the fix against criterion, which if applied, this entire patch can be reverted.
```
--- criterion-2.4.1/src/protocol/gen-pb.py 2022-04-26 06:51:30.000000000 +0000
+++ criterion-2.4.1.patched/src/protocol/gen-pb.py 2023-02-04 12:51:27.398255067 +0000
@@ -17,7 +17,7 @@
cmdline = [protoc_path, '--plugin=protoc-gen-nanopb=' + gen_path,
'-I' + source_dir,
-      '--nanopb_out=' + '-f ' + options_file + ':' + build_dir,
+      '--nanopb_out=' + '-f' + options_file + ':' + build_dir,
proto_file] …
```
=> dbld: install criterion from source on Debian testing

packaging/package-indexer/indexer/deb_indexer.py
Tested locally:
```
Ign:1 http://127.0.0.1:8000/apt nightly InRelease
Get:2 http://127.0.0.1:8000/apt nightly Release [2497 B]                                      
Ign:3 http://127.0.0.1:8000/apt nightly Release.gpg                                           
Get:4 http://127.0.0.1:8000/apt nightly/ubuntu-jammy amd64 Packages [11.7 kB]                 
Hit:5 http://archive.ubuntu.com/ubuntu jammy InRelease                                        
Hit:6 http://archive.ubuntu.com/ubuntu jammy-updates InRelease
Get:7 http://archive.ubuntu.com/ubuntu jammy-backports InRelease [107 kB]
Hit:8 http://security.ubuntu.com/ubuntu jammy-security InRelease                              
Fetched 121 kB in 7s (17.4 kB/s)                                                              
Reading package …
```
=> package-indexer: add .gz, .xz and .bz2 compression for Packages

.github/workflows/macos.yml
rabbitmq-c 0.13.0 was released, which fixes our build issue.
https://formulae.brew.sh/formula/rabbitmq-c
=> github-actions: reenable amqp build

modules/python-modules/syslogng/modules/kubernetes/__init__.py, modules/python-modules/syslogng/modules/kubernetes/scl/kubernetes.conf, modules/python-modules/syslogng/modules/kubernetes/tests/test_kubernetes_api_enrichment.py
This is a work in progress branch to find a good solution for representing kubernetes metadata that contains dots in JSON keys,
causing our name-value representation to become ambiguous
I don't feel the solution in this PR is right, but we can address this post 4.0, so I am splitting this off from #4173
=> Python kubernetes key separator

lib/logmsg/logmsg.h, lib/logsource.c, lib/tests/test_logsource.c
This flag was unused, even if the functionality has merit, it should have been passed to LogSource through options and not via LogMessage flags.
The flag itself will not survive clones, so not really useful anyway.
@HofiOne this one is probably used by one of your internal modules. An easier alternative to achieve the same is to set LogSourceOptions->chain_hostnames to FALSE. No need to use a LogMessage flag for this purpose.
No NEWS needed.
PS: I am trying to add another LogMessage flag in an alternative branch, that's when I encountered this one.
=> logmsg: remove LF_SIMPLE_HOSTNAME

lib/logmsg/tests/test_type_hints.c, lib/logmsg/type-hinting.c, lib/logmsg/type-hinting.h, lib/timeutils/scan-timestamp.c, lib/timeutils/scan-timestamp.h, modules/timestamp/date-parser.c, modules/timestamp/date-parser.h, modules/timestamp/tests/test_format_date.c, modules/timestamp/tf-format-date.c, modules/timestamp/timestamp-grammar.ym, news/feature-4319.md
This PR improves 3 things to deliver more complete support for processing non-standard timestamps.
1) type-hinting: improve the format we can use for DATETIME values by allowing usec granularity (instead of msec) and adding timezone offset information.
2) date-parser now allows extracting timestamps into a name-value pair (in addition to storing the extracted time in the message timestamps)
3) $(format-date) now uses the improved datetime format, so the timezone offset is properly handled when formatting the timestamp.
=> add value() parameter to date-parser()

news/bugfix-4262.md, news/bugfix-4298.md, news/feature-4213.md, news/other-4305.md, news/other-4313.md, news/packaging-4302.md
=> news: add entries for #4213, #4262, #4298, #4302, #4305, #4313

modules/diskq/diskq.c, modules/diskq/dqtool.c, modules/diskq/logqueue-disk.c, modules/diskq/qdisk.c, modules/examples/sources/threaded-diskq-source/threaded-diskq-source.c, news/bugfix-4308-1.md, news/bugfix-4308-2.md, news/bugfix-4308-3.md
There is a bug in `dqtool` which was caused by 2 things:
1. We changed the condition of the cursor wrapping from file size to `disk-buf-size()`.
2. We do not store the `disk-buf-size()` in the disk-queue header.
There is no way to tell where we should wrap without knowing the `disk-buf-size()` before loading the disk-queue.
With this patch set we now store the initial `disk-buf-size()` in the header and use that for the wrap condition.
Also we can now detect whether the user tries to change the `disk-buf-size()` of an existing disk-queue file. For now we will reject that change and go with the original `disk-buf-size()`, which is a bugfix itself, as before this patch set we did not realize that with a config change and might have tried to overread/overwrite the disk-queue file.
We can …
=> diskq: `disk-buf-size()` related fixes: `dqtool cat`, `example-diskq-source()`, changing `disk-buf-size()`

lib/cfg-lexer.c
This branch is a preparation for a major overhaul of our "debugger" functionality. As a prep to that I cleaned up the CfgLexer code
and extracted CfgIncludeLevel to be more of a separate class, instead of just being a data structure manipulated in a complicated
way.
The outcome of the branch is that cfg_lexer_start_next_include() became a few lines of code.
No NEWS entry is needed.
=> cfg-lexer refactor and cleanup

lib/scanner/csv-scanner/csv-scanner.c, lib/scanner/csv-scanner/tests/test_csv_scanner.c, lib/tests/test_utf8utils.c, lib/utf8utils.c
This branch fixes #4274 by:
1) making sure that apache style escaping in access.logs are parsed properly, even if it contains escaped binary characters
2) on output uses \xXX escaping style for binary characters, instead of \uXXXX, which shouldn't be needed for control characters anyway.
This might still be a change compared to our 3.38 behaviour, I guess in that case these binary characters were considered a single field and then re-escaped as it was sent out in JSON to ElasticSearch.
So it was probably sent to Elastic as: ```"\\x16\\x03\\x01"``` Note the double backslashes.
This patch will make that use binary, e.g. elastic would receive the original: ```"\x16\x03\x01"``` string, which it would de-escape probably. So this is still a change compared to 3.38 but I think this behaviour is …
=> Apache rawrequest escaping binary characters

lib/apphook.c, lib/timeutils/cache.c, lib/timeutils/cache.h
Each time a worker thread terminates, the 2 allocated tznames are leaked. Solution is to explicitly deinit the cache from the stop function of the thread.
=> Fix memory leak in timeutils/cache (syslog-ng#4332)

lib/cfg-grammar.y, lib/cfg-parser.c, lib/msg-format.c, lib/msg-format.h, modules/correlation/tests/test_patternize.c, modules/syslogformat/CMakeLists.txt, modules/syslogformat/Makefile.am, modules/syslogformat/sdata-parser.c, modules/syslogformat/sdata-parser.h, modules/syslogformat/syslog-format-plugin.c, modules/syslogformat/syslog-format.c, modules/syslogformat/syslog-format.h, modules/syslogformat/syslog-parser-grammar.ym, modules/syslogformat/syslog-parser-parser.c, modules/syslogformat/tests/CMakeLists.txt, modules/syslogformat/tests/test_syslog_format.c, news/feature-4281.md, tests/copyright/policy, tests/light/functional_tests/parsers/sdata-parser/test_sdata_parser.py, tests/light/src/syslog_ng_config/syslog_ng_config.py
This allows someone to incrementally parse a malformed RFC5424 message, where the SDATA portion is not at the right spot. The SDATA format is relatively complex, so extracting it as a separate component makes it easier to process this kind of data.
This is WIP, because:
=> add sdata-parser() & accept unquoted RFC5424 SD-PARAM-VALUE

dbld/builddeps, dbld/images/centos-7.dockerfile, dbld/images/debian-buster.dockerfile, dbld/images/devshell.dockerfile, dbld/images/fedora-37.dockerfile, dbld/images/tarball.dockerfile, dbld/images/ubuntu-bionic.dockerfile, dbld/images/ubuntu-focal.dockerfile, dbld/images/ubuntu-jammy.dockerfile, dbld/pip_packages.manifest, dev-requirements.txt, scripts/build-python-venv.sh, scripts/syslog-ng-update-virtualenv.in
Debian declines to install pip packages to system paths, because of [PEP-668](https://peps.python.org/pep-0668/). The solution to this is to install pip packages to a venv.
At this point I am not sure that we need pip packages installed to the dbld images, as we have build and install time venvs. The only benefit is that we ship these pip packages with the image, and those packages can be used for anything not syslog-ng related even, but I think it is not enough of a reason to keep them there.
With this patchset, we no longer install pip packages during dbld image build, except KIRA, which needs python2 and python3 at the same time and it is not running tests with our prepared build or install venv.
Example devshell CI run: https://github.com/alltilla/syslog-ng/actions/runs/4282919593 …
=> dbld: fix externally managed python pip install

lib/cfg-block.c, lib/cfg-grammar.y, lib/cfg-lex.l, lib/cfg-lexer.c, lib/cfg-lexer.h, lib/cfg-parser.c, lib/cfg-tree.c, lib/pragma-grammar.ym, lib/pragma-parser.c, lib/tests/test_lexer.c, lib/tests/test_lexer_block.c, libtest/config_parse_lib.c, libtest/mock-cfg-parser.c
This PR builds on the cfg-lexer refactor and will improve the debugger source display dramatically as we become able to
track code that is inside blocks properly.
It also adds the ability to generate syslog-ng configuration using external tools and mark generated code with "@line" to refer to the original source file, in a similar vein to how C/C++ tracks header files, etc.
=> Improve debugger source display

lib/debugger/debugger-main.c, lib/debugger/debugger.c, lib/debugger/debugger.h, lib/driver.c, lib/filter/filter-pipe.c, lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logpipe.h, lib/parser/parser-expr.c, lib/rewrite/rewrite-expr.c
This is more a proof of concept that improves the interactive debugger of syslog-ng (-i). There are actually two changes in here:
1) the debugger will only stop at user-specified LogPipe instances (and not all of them, which is cumbersome to trace through)
2) a new "trace" command that will display tracing/timing information on how a message traverses the configuration
3) a new "info pipe" command
These three could actually be split. The first two patches implement the 1), the two subsequent patch implement 2) and the new info pipe is the last patch. I just didn't want to bomb you would a lot of PRs. But I can split this easily.
NEWS is still missing, let me see if it's green.
=> Preliminary tracing support in debugger

lib/logproto/logproto-proxied-text-server.c, lib/logproto/logproto-proxied-text-server.h, lib/logproto/tests/test-proxy-proto.c, libtest/proto_lib.c, news/feature-4211.md, tests/loggen/loggen.c, tests/loggen/loggen_helper.c, tests/loggen/loggen_helper.h, tests/loggen/loggen_plugin.h, tests/loggen/ssl_plugin/ssl_plugin.c
This PR adds support for PROXY protocol v2 as requested in #4205 
@g-psantos I have tested this blindly, e.g. I wrote my own test program based on the specification, so it might not work in an actual environment, would be great if you could do some manual testing.
NOTE: This does adds some improvement to the existing code, but I feel PROXY v1 should have been done very differently. Instead of a LogProto implementation that combines the PROXY protocol and RFC3164 -like transport over TCP, this should have been a LogTransport implementation that can be combined with any LogProto instances easily. I did NOT address this architectural problem with this PR. I am also not sure that the key-value pairs we are adding to the message (e.g. PROXIED_SRCIP) are the right choice when handling this kind …
=> Add support for PROXY protocol v2

contrib/scripts/config-graph-json-to-dot.py, dev-requirements.txt, lib/CMakeLists.txt, lib/Makefile.am, lib/cfg-grammar.y, lib/cfg-tree.c, lib/cfg-tree.h, lib/metrics-pipe.c, lib/metrics-pipe.h, news/feature-4342.md, tests/copyright/policy, tests/light/functional_tests/logpath/__init__.py, tests/light/functional_tests/logpath/test_named_logpaths.py, tests/light/functional_tests/logpath/test_named_logpaths_with_catchall_flag.py, tests/light/functional_tests/logpath/test_named_logpaths_with_fallback_flag.py, tests/light/functional_tests/logpath/test_named_logpaths_with_final_flag.py, tests/light/src/syslog_ng_config/renderer.py, tests/light/src/syslog_ng_config/statements/logpath/logpath.py, tests/light/src/syslog_ng_config/syslog_ng_config.py, tests/light/src/syslog_ng_ctl/prometheus_stats_handler.py, tests/light/src/syslog_ng_ctl/syslog_ng_ctl.py, tests/light/src/syslog_ng_ctl/syslog_ng_ctl_cli.py, tests/light/src/syslog_ng_ctl/syslog_ng_ctl_executor.py
E.g.:
```
log top-level {
source(s_local);
log inner-1 {
filter(f_inner_1);
destination(d_local_1);
};
log inner-2 {
filter(f_inner_2);
destination(d_local_2);
};
};
```
Each named log path counts its ingress and egress messages:
```
syslogng_log_path_ingress{id="top-level"} 114
syslogng_log_path_ingress{id="inner-1"} 114
syslogng_log_path_ingress{id="inner-2"} 114
syslogng_log_path_egress{id="top-level"} 103
syslogng_log_path_egress{id="inner-1"} 62
syslogng_log_path_egress{id="inner-2"} 41
```
Note that the egress statistics only count the messages which have been have not been filtered out from the related
log path, it does care about whether there are any destinations in it or that any destination delivers or drops the message.
Depends on #4325 and #4339.
Signed-off-by: Attila Szakacs …
=> cfg: add named logpaths with counters

modules/diskq/dqtool.c
This was completely non-functional as the persist file was validated as a diskq file.
=> diskq: fix dqtool assign

lib/cfg-grammar.y, lib/cfg-tree.c, lib/cfg-tree.h, lib/logmpx.c, lib/logmpx.h, lib/logpipe.h, lib/metrics-pipe.c, lib/versioning.h, tests/copyright/policy, tests/light/functional_tests/logpath/test_conditionals.py, tests/light/functional_tests/logpath/test_midpoint_destinations.py, tests/light/src/syslog_ng_config/statements/destinations/destination_driver.py, tests/light/src/syslog_ng_config/statements/destinations/file_destination.py, tests/light/src/syslog_ng_ctl/driver_stats_handler.py
This PR started out as a fix for an issue reported by @faxm0dem on gitter, with config and patterndb here: https://gist.github.com/faxm0dem/3dfc0873842d4c05ebcd8cb7f8eda8ab
The issue turned out to be an issue how we process the "unmatched" state for a log path. With time, another case came up in #4339 and it turns out we have a limited-incomplete definition on how we define that a log path did not match.
Since this is a complicated issue, let me try to write this up, hopefully it will be useful for my future self or anyone trying to understand the compilation process.
So let's take one step back. 
**Why do we need the notion of a message being "unmatched" for a log path?**
syslog-ng supports both independent and dependent log paths. An independent one is simple: let's take the stream of …
=> fix conditional evaluation with a dangling filter

docker/Dockerfile
Add opencontainers image source label, which is used by external tooling/systems for various purposes.
One example is https://github.com/renovatebot/renovate/blob/main/lib/modules/datasource/docker/readme.md
=> docker: add metadata label for opencontainers

modules/diskq/qdisk.c, modules/diskq/tests/test_qdisk.c
This PR refactors the monster `qdisk_start()` function. There are some minor edge case fixes, but no functional change is expected.
No NEWS file needed.
=> qdisk: refactor qdisk_start()

lib/parser/parser-expr.c, lib/parser/parser-expr.h, modules/correlation/stateful-parser.c, news/bugfix-4370.md, tests/light/Makefile.am, tests/light/functional_tests/logpath/test_conditionals.py
As a followup to #4366 and #4058, another edge case was identified where syslog-ng evaluation handles matched messages incorrectly.
If we are using a correlation while processing the message, the incoming messages are consumed into a context and then the individual messages get dropped, at least when using inject-mode(aggregate-only).
In these cases we should not consider dropping of these messages to be unmatching, as dropping happens as a part of correlation.
This patch adds a light based testcase to exercise this problem and includes a fix, so that messages consumed into corrlation in `inject-mode(aggregate-only)` mode will not cause those messages to traverse any alternative paths.
=> fix "matched" logic in case of correlating parsers

lib/logqueue-fifo.c, lib/logqueue.c, lib/logqueue.h, lib/logthrdest/tests/test_logthrdestdrv.c, lib/tests/test_logqueue.c, modules/diskq/logqueue-disk.c, modules/diskq/tests/test_diskq.c, modules/diskq/tests/test_diskq_full.c, modules/diskq/tests/test_logqueue_disk.c
To me `stats_cache` does not tell anything, and the fact that some counters are shared between `LogQueues` are not communicated clearly.
I think the new naming better shows the counters which are shared between `LogQueues`, and counters (`atomic_gssizes`) which are owned by a `LogQueue instance`.
Related PR #4356.
=> logqueue: rename variables of stats counters and cache 

.mailmap, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_qdisk.c
=> qdisk: account for overwriting in get_empty_space()

modules/diskq/qdisk.c, modules/diskq/tests/test_diskq_truncate.c
Related comment: https://github.com/syslog-ng/syslog-ng/pull/4335#discussion_r1135321974
=> qdisk: preallocate qdisk file after creating header

dbld/build.manifest, dbld/images/debian-testing.dockerfile
This reverts commit e423d82b37320ec97128d0adfe7e01b3d2d51602.
Criterion is available again in Debian testing.
=> Revert "dbld: install criterion from source on Debian testing"

modules/diskq/qdisk.c, news/bugfix-4381.md
This PR fixes a rare race condition when calculating disk-buffer filename:
As two threads or two syslog-ng instances can run `_next_filename()` simultaneously, and they can get the same filename.
To mitigate this I have introduced an flock, which solves the issue between two syslog-ng instances, but does not solve it for threads in the same syslog-ng instance (man 2 flock):
> If  a  process  uses  open(2)  (or similar) to obtain more than one file descriptor for the same
> file, these file descriptors are treated independently by flock().  An attempt to lock the  file
> using one of these file descriptors may be denied by a lock that the calling process has already
> placed via another file descriptor.
To solve this, I have introduced a static lock, too.
Depends on #4380.
Signed-off-by: …
=> qdisk: fix filename race

lib/stats/stats-cluster-key-builder.c, lib/stats/stats-cluster-key-builder.h, lib/stats/tests/test_stats_cluster_key_builder.c
While preparing #4356, a couple more use cases have emerged, which can be solved with these two functions.
=> stats-cluster-key-builder: add clone() and reset()

modules/add-contextual-data/contextual-data-record-scanner.c, modules/correlation/synthetic-message.c, modules/python/python-logmsg.c, modules/python/python-tf.c, modules/python/tests/test_python_logmsg.c, news/bugfix-4394.md
Prior to this PR, `python()`, `db-parser()`, `grouping-by()`, and `add-contextual-data()` used the new typing feature regardless of the config version.
=> Fix v3 typing compat

lib/timeutils/tests/test_wallclocktime.c, lib/timeutils/wallclocktime.c, news/bugfix-4401.md
From libc docs:
> If Daylight Saving Time is never used, tzname[1] is the empty string.
Empty strings should not be compared against the input of strptime().
=> timeutils: fix strptime(%z) when no Daylight Saving Time is specified

modules/diskq/diskq.c, modules/diskq/dqtool.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-non-reliable.h, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk-reliable.h, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_diskq.c, modules/diskq/tests/test_diskq_full.c, modules/diskq/tests/test_diskq_truncate.c, modules/diskq/tests/test_logqueue_disk.c, modules/diskq/tests/test_qdisk.c, modules/diskq/tests/test_reliable_backlog.c, modules/examples/sources/threaded-diskq-source/threaded-diskq-source.c
This PR is a preparation step for #4356.
There, we will need to know the filename when creating a `LogQueueDisk` instance in order to properly setup the `StatsClusterKey` for the metrics.
=> qdisk: set filename sooner

modules/diskq/CMakeLists.txt, modules/diskq/Makefile.am, modules/diskq/diskq-config.c, modules/diskq/diskq-config.h, modules/diskq/diskq-global-metrics.c, modules/diskq/diskq-global-metrics.h, modules/diskq/diskq-grammar.ym, modules/diskq/diskq-parser.c, modules/diskq/diskq-plugin.c, modules/diskq/diskq.c, news/feature-4399.md, tests/copyright/policy
```
syslogng_disk_buffer_dir_available_space_bytes{dir="/var/syslog-ng"} 870109413376
```
=> disk-buffer: add dir metrics

modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/tests/CMakeLists.txt, modules/diskq/tests/Makefile.am, modules/diskq/tests/test_diskq_counters.c, news/feature-4356.md, tests/copyright/policy
New metrics:
* "capacity_bytes": The theoretical maximal useful size of the disk-buffer. This is always smaller, than `disk-buf-size()`, as there is some reserved space for metadata. The actual full disk-buffer file can be larger than this, as syslog-ng allows to write over this limit once, at the end of the file.
* "disk_allocated_bytes": The current size of the disk-buffer file on the disk. Please note that the disk-buffer file size does not strictly correlate with the number of messages, as it is a ring buffer implementation, and also syslog-ng optimizes the truncation of the file for performance reasons.
* "disk_usage_bytes": The serialized size of the queued messages in the disk-buffer file. This counter is useful for calculating the disk usage percentage (disk_usage_bytes / …
=> disk-buffer: add disk-buffer related metrics

syslog-ng/main.c
When syslog-ng fails to initialize its configuration when it starts up, it left behind some of its configuration as allocations without freeing them, showing up in valgrind reports.
This does not solve the entire issue, but improves it a lot. 
No NEWS file needed.
=> main: free global states before exiting due to failed initialization

lib/logmsg/logmsg.c, modules/correlation/pdbtool/pdbtool.c, news/bugfix-4405.md
`pdbtool test`: fix two type validation bugs:
1) When `pdbtool test` validates the type information associated with a name-value
pair, it was using string comparisons, which didn't take type aliases
into account. This is now fixed, so that "int", "integer" or "int64"
can all be used to mean the same type.
2) When type information is missing from a `<test_value/>` tag, don't
validate it against "string", rather accept any extracted type.
In addition to these fixes, a new alias "integer" was added to mean the same
as "int", simply because syslog-ng was erroneously using this term when
reporting type information in its own messages.
=> Fix type validation in "pdbtool test"

lib/afinter.c, lib/afinter.h, lib/healthcheck/healthcheck-control.c, lib/metrics-pipe.c, modules/afsocket/afsocket-source.c, modules/afsocket/afsocket-source.h, modules/afsocket/afunix-source.c, modules/afsocket/systemd-syslog-source.c, news/feature-4411.md, news/other-4411.md, tests/light/functional_tests/logpath/__init__.py, tests/light/src/syslog_ng_config/statements/logpath/logpath.py
New metrics
`network()`, `syslog()`: TCP connection metrics
```
syslogng_socket_connections{id="tcp_src#0",driver_instance="afsocket_sd.(stream,AF_INET(0.0.0.0:5555))",direction="input"} 3
syslogng_socket_max_connections{id="tcp_src#0",driver_instance="afsocket_sd.(stream,AF_INET(0.0.0.0:5555))",direction="input"} 10
syslogng_socket_rejected_connections_total{id="tcp_src#0",driver_instance="afsocket_sd.(stream,AF_INET(0.0.0.0:5555))",direction="input"} 96
```
`internal()`: `internal_events_queue_capacity` metric
`syslog-ng-ctl healthcheck`: new healthcheck value `syslogng_internal_events_queue_usage_ratio`
The following Prometheus metrics have been renamed:
`log_path_{in,e}gress` -> `route_{in,e}gress_total`
`internal_source` -> `internal_events_total`
The `internal_queue_length` stats …
=> TCP connection metrics and minor improvements

lib/logmsg/tags.c, lib/logreader.c, lib/logsource.c
```
syslogng_input_events_total{id="#anon-source0#2",driver_instance="tcp,127.0.0.1"} 1
syslogng_tagged_events_total{id=".source.#anon-source0"} 5
```
=> inputs/tags: get rid of "processed" label in Prometheus metrics 

modules/python/python-logmsg.c, modules/python/python-logmsg.h, modules/python/python-tf.c, modules/python/python-types.c, modules/python/tests/test_python_logmsg.c, modules/python/tests/test_python_tf.c, news/bugfix-4410-2.md, news/bugfix-4410-3.md, news/bugfix-4410.md, news/feature-4410.md
`python()`: new LogMessage methods for querying as string and with default values
- `get(key[, default])`
Return the value for `key` if `key` exists, else `default`. If `default` is
not given, it defaults to `None`, so that this method never raises a
`KeyError`.
- `get_as_str(key, default=None, encoding='utf-8', errors='strict', repr='internal')`:
Return the string value for `key` if `key` exists, else `default`.
If `default` is not given, it defaults to `None`, so that this method never
raises a `KeyError`.
The string value is decoded using the codec registered for `encoding`.
`errors` may be given to set the desired error handling scheme.
Note that currently `repr='internal'` is the only available representation.
We may implement another more Pythonic representation in the future, so …
=> `python()`: new `LogMessage` methods and bugfixes

modules/json/json-parser.c, modules/json/tests/test_json_parser.c, news/bugfix-4396.md
=> json-parser: fix parsing non-string arrays 

modules/json/format-json.c, modules/json/tests/test_format_json.c, news/bugfix-4415.md
RFC8259 does not allow '+' sign and leading zeros in numbers, but these and leading spaces are allowed by type_cast_to_number().
Because syslog-ng should always store the original representation (normalizing the stored value would break other functionality), normalization/sanitization/etc. should be done in formatter functions.
=> format-json: fix RFC8259 number violation

lib/utf8utils.c, lib/utf8utils.h, modules/json/format-json.c, modules/json/tests/test_format_json.c, news/bugfix-4417.md
This fixes a regression introduced in 4b416642528de59290642ca2602b7d5040cbd1c7, where the control char escaping of append_unsafe_utf8_as_escaped_text() has been changed from \u to \x.
RFC8259 only allows \uXXXX escaping.
=> format-json: fix escaping control characters

lib/stats/stats-cluster-key-builder.c, lib/stats/stats-registry.c, lib/stats/stats-registry.h, modules/diskq/diskq-global-metrics.c, modules/diskq/diskq-global-metrics.h, modules/diskq/diskq.c, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/diskq/tests/test_diskq_counters.c, news/feature-4402.md
Availability is the same as the `disk_queue_dir_available_bytes` metric.
```
syslogng_disk_queue_capacity_bytes{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 104853504
syslogng_disk_queue_disk_allocated_bytes{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 273408
syslogng_disk_queue_disk_usage_bytes{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 269312
syslogng_disk_queue_events{abandoned="true",path="/var/syslog-ng/syslog-ng-00000.rqf",reliable="true"} 860
```
Depends on #4399 and #4356.
Fixes #4400
=> disk-buffer: add metrics for abandoned disk-buffer files

lib/mainloop.c, news/bugfix-4418.md
This does the same that syslog-ng does during reload: a partial (failed) initialization should be followed by a deinit() call.
It makes sure that the pipeline is deinitialized before exiting; for example, that disk-buffers are persisted and closed.
=> mainloop: deinit() configuration when init() fails on startup

modules/correlation/CMakeLists.txt, modules/correlation/Makefile.am, modules/correlation/correlation-context.c, modules/correlation/correlation-context.h, modules/correlation/correlation-grammar.ym, modules/correlation/correlation-plugin.c, modules/correlation/correlation.c, modules/correlation/correlation.h, modules/correlation/dbparser.c, modules/correlation/grouping-parser.c, modules/correlation/grouping-parser.h, modules/correlation/groupingby.c, modules/correlation/groupingby.h, modules/correlation/patterndb.c, modules/correlation/patterndb.h, modules/correlation/pdbtool/pdbtool.c, modules/correlation/stateful-parser.c, modules/correlation/stateful-parser.h, modules/correlation/tests/test_patterndb.c, news/other-4424.md
This is the initial set of refactors split off from #4225  Apart from a large amounts of refactoring steps, there's a user
visible change too, as described in this news snippet
`grouping-by()`: Remove setting of the `${.classifier.context_id}`
name-value pair in all messages consumed into a correlation context.  This
functionality is inherited from db-parser() and has never been documented
for `grouping-by()`, has of limited use, and any uses can be replaced by the
use of the built-in macro named `$CONTEXT_ID`.  Modifying all consumed
messages this way has significant performance consequences for
`grouping-by()` and removing it outweighs the small incompatibility this
change introduces. The similar functionality in `db-parser()` correlation is
not removed with this change.
=> Extract grouping-parser()

modules/afsocket/afinet-dest.c, modules/afsocket/afsocket-signals.h, modules/examples/CMakeLists.txt, modules/examples/Makefile.am, modules/examples/example-plugins.c, modules/examples/inner-destinations/tls-test-validation/CMakeLists.txt, modules/examples/inner-destinations/tls-test-validation/Makefile.am, modules/examples/inner-destinations/tls-test-validation/tls-test-validation-grammar.ym, modules/examples/inner-destinations/tls-test-validation/tls-test-validation-parser.c, modules/examples/inner-destinations/tls-test-validation/tls-test-validation-parser.h, modules/examples/inner-destinations/tls-test-validation/tls-test-validation.c, modules/examples/inner-destinations/tls-test-validation/tls-test-validation.h, tests/copyright/policy
As discussed in #4219, currently there is no OCSP/CRL validation for remote peer certificates.
In this PR, a hook is added for a custom certificate validation for remote certificate. The hook is only called when the remote certificate is being verified. The hook will call the plugin with SSL_CONTEXT which allows the custom validation.
A plugin example, called tls-test-validation,  was added that verifies if a certificate has an expected identifier.
```
destination test {
syslog("172.16.17.4" transport("tls") ip-protocol(4) port(6514) keep-alive(no)
suppress(5)
tls(
ca-dir("/path/to/ca/")
peer-verify(yes)
)
tls-test-validation(identity("test"))
disk-buffer(
mem-buf-length(2000)
disk-buf-size(8388608)
dir("/tmp")
)
);
```
Let me know if any changes are needed
=> TLS custom certificate validation plugin

CMakeLists.txt, cmake/print_config_summary.cmake
CMake builds did not fully respect the ENABLE_TESTING option
=> cmake: Added missing handling of ENABLE_TESTING option in cmake builds

lib/mainloop.c, lib/mainloop.h, news/feature-4435.md, syslog-ng/main.c
Similarly to `--syntax-only`, this command line option parses the configuration
and then prints its ID before exiting.
It can be used to query the ID of the current configuration persisted on
disk.
Note:
`--syntax-only` could have been used for the same functionality.
In that case, `--config-id` would just be an alias.
=> `syslog-ng`: add `--config-id` command line option

modules/afprog/afprog.c, news/bugfix-4438.md
There were 2 issues in the `_close_all_fd` implementation
- iterating through the file handler numbers used an `int` though the init value is an `rlim_t` (that can be an `unsigned long long`) that can have an `RLIM_INFINITY` value, so an overflow could happen, therefore no file handlers were closed at all that led to a freeze in `_wait_for_child_closing_fds`
- as the `rlp.rlim_max` can be `RLIM_INFINITY` that is an extremely large number in that case, calling close() for such a huge number of handlers could take an extremely long time.
=> afprog: Fixed possible freezing on some OSes

lib/persist-state.c, lib/tests/test_persist_state.c
lib:  make persist_state_alloc_string() reuse the same entry if possible
Resolves #3337
=> lib:  make persist_state_alloc_string() reuse the same entry if possible

packaging/debian/syslog-ng.conf
When installing the Debian package, the installed sample configuration
file include some legacy settings that cause a warning:
> WARNING: Your configuration file uses an obsoleted keyword, please update your configuration; keyword='stats_freq', change='Use the stats() block. E.g. stats(freq(1));', location='/etc/syslog-ng/syslog-ng.conf:10:4'
Adjust the sample configuration to use the updated syntax instead.
=> Update the sample Debian config to not throw warning

lib/template/templates.c, lib/template/templates.h, modules/add-contextual-data/context-info-db.c, modules/add-contextual-data/contextual-data-record-scanner.c, modules/add-contextual-data/contextual-data-record.c, modules/add-contextual-data/contextual-data-record.h, modules/add-contextual-data/tests/test_context_info_db.c, news/feature-4444.md
The PR significantly decreases the memory use for add-contextual-data() (e.g. 40%) as reported in #4439 
I'd appreciate some testing with your original CSV database, so testing would absolutely be welcome. 
Note that add-contextual-data()'s data representation is not really optimized for memory usage, I could easily slash it almost half, but anything more would seems more complicated. 
db-parser() is difficult to use but it's performance/memory use is difficult to beat. If you are interested I could help you on Axoflow's discord server for a more interactive chat, https://discord.gg/E65kP9aZGm
Depending on how you deploy syslog-ng, you could use the PR specific binaries produced by github or compile from source, etc.
=> Fix memory use of add contextual data

lib/cfg-grammar.y, lib/value-pairs/cmdline.c, lib/value-pairs/tests/test_value_pairs.c, lib/value-pairs/transforms.c, lib/value-pairs/transforms.h, news/feature-4452.md, tests/copyright/policy, tests/light/functional_tests/Makefile.am, tests/light/functional_tests/value-pairs/test_value_pairs.py
This is an attempt to add support for lower/upper transformations in value-pairs expressions as discussed in #4422 
This is how to use it:
```file("logfile" template("$(format-json * --lower)\n")); ```
Or, a slightly different example:
```file("logfile" template("$(format-json * foo.bar=value --rekey foo.* --upper)\n"))```
=> Value pairs upper and lower transforms

modules/metrics-probe/metrics-probe-grammar.ym, modules/metrics-probe/metrics-probe-parser.c, modules/metrics-probe/metrics-probe.c, modules/metrics-probe/metrics-probe.h, modules/metrics-probe/tests/test_metrics_probe.c, modules/python-modules/syslogng/modules/kubernetes/scl/kubernetes.conf, news/feature-4453.md
```
syslogng_last_config_file_modification_timestamp_seconds 1683030288
syslogng_last_config_reload_timestamp_seconds 1683030289
syslogng_last_successful_config_reload_timestamp_seconds 1683030289
syslogng_scratch_buffers_bytes 43008
syslogng_scratch_buffers_count 179
```
```
syslogng_events_allocated_bytes 1189424
syslogng_filtered_events_total{id="#anon-filter0",result="matched"} 2302
syslogng_filtered_events_total{id="#anon-filter0",result="not_matched"} 0
syslogng_input_event_bytes_total{cluster="k8s",driver="kubernetes",id="s_kubernetes",namespace="default",pod="log-generator-1682517834-7797487dcc-49hqc"} 67460
syslogng_input_event_bytes_total{cluster="k8s",driver="kubernetes",id="s_kubernetes",namespace="default",pod="opensearch-cluster-master-0"} 84974 …
```
=> kubernetes: make SCL drivers internal

modules/python/python-confgen.c, news/bugfix-4459.md
We are parsing the function pointer a couple lines above with "O".
> O (object) [PyObject *]
> Store a Python object (without any conversion) in a C object pointer. The C program thus receives the actual object that was passed. The object’s reference count is not increased. The pointer stored is not NULL.
Its reference count is not increased with the parsing, however we decrease its reference in `python_config_generator_free()`.
This causes a problem, when we are reloading and re-registering the same function.
=> python: fix reference counting of generator function 

modules/examples/destinations/example_destination/example_destination_worker.c
This patch fixes a memory leak in case the destination worker fails in the _dw_insert method.
=> examples: fix memory leak

news/feature-4462.md, scl/CMakeLists.txt, scl/Makefile.am, scl/splunk/splunk.conf, tests/copyright/policy
splunk: Added support for sending messages to Splunk HEC.
The `splunk-hec-event()` destination feeds Splunk via the [HEC events API](https://docs.splunk.com/Documentation/Splunk/9.0.4/RESTREF/RESTinput#services.2Fcollector.2Fevent.2F1.0).
Minimal config:
```
destination d_splunk_hec_event {
splunk-hec-event(
url("https://localhost:8088")
token("70b6ae71-76b3-4c38-9597-0c5b37ad9630")
);
};
```
Additional options include:
* `event()`
* `index()`
* `source()`
* `sourcetype()`
* `host()`
* `time()`
* `default-index()`
* `default-source()`
* `default-sourcetype()`
* `fields()`
* `extra-headers()`
* `extra-queries()`
* `content-type()`
`event()` accepts a template, which declares the content of the log message sent to Splunk.
By default we send the `${MSG}` value.
`index()`, `source()`, …
=> splunk: add splunk-hec-raw() and splunk-hec-event() drivers

configure.ac
This can be useful in containerized environments, where the venv is built into the image, but users want to mount an empty statedir.
=> configure: add --with-python-venv-dir option

modules/python-modules/syslogng/source.py
Fixes a bug introduced in #4175.
No news file needed because this has not been released yet.
=> python-modules: fix signature of BatchedAckTracker fake class

lib/logreader.c, lib/transport/transport-aux-data.h, lib/transport/transport-socket.c, lib/transport/transport-socket.h, lib/transport/transport-udp-socket.c, modules/afsocket/compat-unix-creds.h, modules/afsocket/transport-unix-socket.c
This PR adds support for SO_TIMESTAMPNS getsockopt to retrieve an accurate timestamp from the kernel to retain packet ordering.
=> Retrieve packet timestamp from the kernel

cmake/Makefile.am
packaging: added missing print_config_summary.cmake file reference
Fixes #4473
=> packaging: added missing print_config_summary.cmake file reference

news/feature-4472.md, scl/CMakeLists.txt, scl/Makefile.am, scl/logscale/logscale.conf, tests/copyright/policy
The `logscale()` destination feeds LogScale via the [Ingest API](https://library.humio.com/falcon-logscale/api-ingest.html#api-ingest-structured-data).
Minimal config:
```
destination d_logscale {
logscale(
token("my-token")
);
};
```
Additional options include:
* `url()`
* `rawstring()`
* `timestamp()`
* `timezone()`
* `attributes()`
* `extra-headers()`
* `content-type()`
=> logscale: add logscale() destination

.github/workflows/devshell.yml, Makefile.am, configure.ac
Quick fix for https://github.com/syslog-ng/syslog-ng/issues/4494, it made clang the default cpp tool on macOS that will invoke libtool correctly, without any errors.
=> configure: fix autotools C++

m4/ax_require_defined.m4
fixes #4501 
This is a limitation inside aclocal, that aclocal can only run twice, any more attempt in runinng it again will fail.
I have searched multiple project about this issue I found out that most of them fixed this like this, so I choose this fix.
The other approach was calling aclocal again.
=> Add ax_require_defined.m4 to fix aclocal's too many loop error

.github/workflows/macos.yml
Put back earlier pyhon 2<->3 workaround that will also fix later brew python3 update issues
Removed existing symlinks that normally should have been overwritten by link: true, force: true
Signed-off-by: Hofi [hofione@gmail.com](mailto:hofione@gmail.com)
=> Fix CI python3 update issues

modules/python-modules/syslogng/modules/hypr/__init__.py
Hypr registers a confgen plugin, implemented in Python, which depends on the Python requests module. If that is not present (e.g. because we are not using a virtualenv), syslog-ng startup would fail. This patch will defer the error to the actual initialization, this way syslog-ng would start in these cases and would only fail if Hypr is actually used.
=> Hypr: allow syslog-ng to start even if the Python requests module is missing

Mk/python-venv.am, configure.ac, modules/python-modules/Makefile.am, modules/python-modules/setup.py
This should fix #4486 by installing the core syslog-ng Python modules even if --disable-python-modules is used.
@czanik can you please test if this fixes your issue?
=> Keep python core while disabling python modules

lib/cfg-grammar.y, lib/cfg-parser.c, lib/debugger/debugger.c, lib/filter/filter-cmp.c, lib/filter/tests/test_filters_fop_cmp.c, lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logmsg/tests/test_type_hints.c, lib/template/eval.c, lib/template/tests/test_template.c, lib/value-pairs/cmdline.c, lib/value-pairs/cmdline.h, lib/value-pairs/internals.h, lib/value-pairs/tests/test_value_pairs.c, lib/value-pairs/value-pairs.c, lib/value-pairs/value-pairs.h, libtest/cr_template.c, modules/afmongodb/afmongodb-worker.c, modules/afmongodb/afmongodb.c, modules/afsql/afsql.c, modules/basicfuncs/vp-funcs.c, modules/cef/format-cef-extension.c, modules/graphite/graphite-output.c, modules/json/format-json.c, modules/json/tests/test_format_json.c, modules/kvformat/format-welf.c, modules/python/python-logmsg.c, modules/python/python-types.c, modules/python/tests/test_python_logmsg.c, modules/python/tests/test_python_tf.c
We are implementing these with the following behavior:
* LogMessage API: `log_msg_get_value()` and `log_msg_values_foreach()`, etc returns them with the proper value and type.
* Template evaluation:
* Accessing the NVPair simply (e.g. `$bytes_value`) behaves if like they were unset.
* Accessing the NVPair with explicit type cast (e.g. `bytes($bytes_value)` or `protobuf($protobuf_value)`) returns them with the proper value and type.
* Value Pairs API: By default it behaves like it was unset, but an optional `--include-bytes` option can be added, which returns them with the proper value and type. This is opt-in, and the call site must be prepared to handle the values.
* Python binding: They behave as they were unset, as we cannot differentiate between `LM_VT_STRING` <-> `bytes` and …
=> logmsg: add bytes and protobuf types

modules/afmongodb/afmongodb-worker.c
afmongodb: mongo-c rised an exception that caused a crash at app exit if there's no bulk operation in progress
=> Fix mongo-c module crash at app exit

modules/correlation/pdbtool/pdbtool.c
This is related to #4498 where @erempel mentioned return code related fooes.
A review/testing is still needed as I just had a quick glimpse over various exit paths from pdbtool actions. I just didn't want to lose this set of patches.
I've also opened a PR against documentation.
=> Pdbtool exit code cleanup

lib/value-pairs/tests/test_value_pairs.c, lib/value-pairs/value-pairs.c, modules/json/tests/test_format_json.c
=> value-pairs: add v3 unit tests for bytes types & fix no --include-bytes with explicit cast

.github/workflows/macos.yml, contrib/Brewfile
A problem appeared overnight with macos and openssl@1.1:
```
Undefined symbols for architecture x86_64:
"_SSL_get_peer_certificate", referenced from:
_tls_session_info_callback in libsyslog_ng_la-tls-session.o
_tls_session_ocsp_client_verify_callback in libsyslog_ng_la-tls-session.o
ld: symbol(s) not found for architecture x86_64
collect2: error: ld returned 1 exit status
```
I have not investigated the issue thoroughly, just tried to upgrade to 3.0, and it works.
We can investigate it if we are concerned, but we have other platforms with openssl 1.1, and they seem to work, so I guessed it is something macos related, but not sure.
=> macos: install openssl 3

lib/logqueue-fifo.c, news/bugfix-4528.md
In high-performance use cases, users may configure log-iw-size() and
fetch-limit() to be higher than 2^16, which caused flow-control issues,
such as messages stuck in the queue forever or log sources not receiving
messages.
=> Fix flow-control when `fetch-limit()` is set higher than 64K

lib/mainloop-call.c
Now that we've had the previous fix from #4258 in production for a while, we've started to see that syslog-ng is now occasionally hanging, and the hangs are unfortunately caused by that previous fix.  
Here are the stack traces of the two threads that cause the hang:
```
(gdb) i thr
Id   Target Id                  Frame 
* 1    LWP 101322 of process 1003 _umtx_op_err ()
at /usr/src/lib/libthr/arch/amd64/amd64/_umtx_op_err.S:40
2    LWP 101323 of process 1003 _kevent () at _kevent.S:4
3    LWP 976246 of process 1003 _umtx_op_err ()
at /usr/src/lib/libthr/arch/amd64/amd64/_umtx_op_err.S:40
(gdb) bt
#0  _umtx_op_err ()
at /usr/src/lib/libthr/arch/amd64/amd64/_umtx_op_err.S:40
#1  0x000015e1cb8f324c in __thr_umutex_lock (mtx=0x15e1d480a688, id=0x18bca)
at …
```
=> mainloop-call: fix hang caused by the previous fix for pending mainloop-calls

lib/logmsg/tests/test_type_hints.c, lib/logmsg/type-hinting.c, modules/json/tests/test_format_json.c, news/bugfix-4535.md
db-parser()'s @NUMBER@ extractor allows hex numbers and then marks up the value as integer, so we should accept it in type casts too.
fixes: #4532
=> type-hints: accept hex values as integers

news/packaging-4534.md, packaging/debian/syslog-ng-scl.install, packaging/rhel/syslog-ng.spec, scl/CMakeLists.txt, scl/Makefile.am
It helps to run syslog-ng in containers, with minimizing the content of the etc/ dir, which is mounted usually.
Because of our file include logic, if `etc/scl.conf` exists, it is loaded and `share/syslog-ng/include/scl.conf` is ignored.
This is suitable for an upgrade path, as with an upgrade the old one will be used, but with new installments the new one will be used.
=> scl: move scl.conf to ${config_includedir} 

modules/python-modules/syslogng/source.py, news/bugfix-4549.md, tests/copyright/policy
Fix InstantAckTracker, ConsecutiveAckTracker and BatchedAckTracker calling the C init function, currently the parent constructor (imported from C) is never called, meaning that the callbacks are never called making them non functional
=> python: Create proper fake classes for LogSource, LogFetcher, InstantAckTracker, ConsecutiveAckTracker and BatchedAckTracker

modules/python/python-dest.c, modules/python/python-dest.h, modules/python/python-fetcher.c, modules/python/python-fetcher.h, modules/python/python-grammar.ym, modules/python/python-http-header.c, modules/python/python-http-header.h, modules/python/python-logparser.c, modules/python/python-logparser.h, modules/python/python-source.c, modules/python/python-source.h, modules/python/tests/test_python_persist_name.c
This should fix a crash in case a Python parser is added as a part of a parser {} statement and not referenced in-line.
Program received signal SIGSEGV, Segmentation fault.
python_options_create_py_dict (self=self@entry=0x55555571b890) at /source/modules/python/python-options.c:325
325	        const PythonOption *option = (const PythonOption *) elem->data;
(gdb) up
#1  0x00007ffff70cb217 in _py_invoke_bool_method_by_name_with_options (instance=<optimized out>, method_name=method_name@entry=0x7ffff70de5bb "init", 
options=0x55555571b890, class=0x5555556e07b0 "MyParser", module=0x5555556b9500 "p_foo") at /source/modules/python/python-helpers.c:389
389	      PyObject *py_options_dict = options ? python_options_create_py_dict(options) : NULL;
(gdb) up
#2  0x00007ffff70d1f7a in …
=> python: avoid consuming the argument in python_XX_set_options()

.github/workflows/test-apt-packages.yml
The official syslog-ng got removed from debian:testing because of pcre: https://tracker.debian.org/news/1445295/syslog-ng-removed-from-testing/
Hopefully this fixes the nightly release.
GitHub Actions reference: https://docs.github.com/en/actions/using-jobs/using-a-matrix-for-your-jobs#excluding-matrix-configurations
=> github-actions: skip debian:testing official package test

modules/afsocket/afsocket-dest.c, modules/afsocket/socket-options.c, modules/afsocket/socket-options.h, news/bugfix-4559.md
`tcp-keepalive-*()` options were broken on the destination side since v3.34.1.
Fixes #4546
=> `network()` destination: fix TCP keepalive

news/feature-4560.md, scl/CMakeLists.txt, scl/Makefile.am, scl/opensearch/opensearch.conf
It is similar to `elasticsearch-http()`, with the difference that it does not have the `type()` option, which is deprecated and advised not to use.
=> scl: add opensearch 

lib/logwriter.c
`affile_dd_reuse_writer()` calls `affile_dw_set_owner()` on an already initialized writer.
Reproduction:
```
@version: 4.3
options {
stats_level(1);
};
source s_local {
example-msg-generator();
};
destination d_file {
file("/tmp/b");
};
log {
source(s_local);
destination(d_file);
};
```
```
syslog-ng-ctl reload
```
=> logwriter: fix stats related memleak in case of reload

modules/python/python-dest.c, modules/python/python-dest.h, modules/python/python-fetcher.c, modules/python/python-fetcher.h, modules/python/python-grammar.ym, modules/python/python-http-header.c, modules/python/python-http-header.h, modules/python/python-logparser.c, modules/python/python-logparser.h, modules/python/python-options.c, modules/python/python-options.h, modules/python/python-source.c, modules/python/python-source.h, modules/python/tests/test_python_options.c, modules/python/tests/test_python_persist_name.c
`python_options_add_options()` took the ownership of the `PythonOption`, resulting in double frees in case of cloning.
Fixes #4566
=> python: reference count python-option

cmake/Modules/FindRiemannClient.cmake
Added the new library naming changes to enhance package discovery
=> cmake: Riemann client is now supports OpenSSL as a backing TLS library

CMakeLists.txt, modules/grpc/CMakeLists.txt
Also, disable GRPC on the Apple platform by default independently from the ENABLE_CPP setting
=> Let the user control the ENABLE_CPP option on the Apple platform

modules/java-modules/CMakeLists.txt
Also made ENABLE_JAVA_MODULES switch always visible in the summary list
=> cmake: Use the same JAVA MODULE (ENABLE_JAVA_MODULES) option switch in autotools and cmake configs

packaging/debian/control
For example, to allow reflective usage of Protocol Buffers (parsing/loading protobufs at runtime).
`libabsl-dev`: `google::protobuf::compiler` leaks Abseil data structures.
=> packaging: add libprotoc-dev and libabsl-dev builddep

modules/grpc/otel/otel-dest-worker.cpp, modules/grpc/otel/otel-dest.hpp, news/bugfix-4583.md
=> otel: fix drop handling in insert

packaging/debian/syslog-ng-core.install, packaging/debian/syslog-ng-scl.install
The default configuration includes "scl.conf", so unless syslog-ng-scl is installed, we would have a broken config.
Fixes: #4585
=> packaging/debian: move the SCL package to syslog-ng-core

lib/logqueue-fifo.c, lib/logqueue.h, lib/logthrdest/logthrdestdrv.c, lib/logwriter.c, lib/tests/test_logqueue.c, libtest/queue_utils_lib.c, libtest/queue_utils_lib.h, modules/diskq/dqtool.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/tests/Makefile.am, modules/diskq/tests/test_diskq.c, modules/diskq/tests/test_diskq_counters.c, modules/diskq/tests/test_diskq_full.c, modules/diskq/tests/test_diskq_truncate.c, modules/diskq/tests/test_reliable_backlog.c
This branch removes some unused aspects of the LogQueue interface, namely the push_head() method (which aborted in
the disk buffer cases) and the optionality of the backlog queue.
NEWS file not needed.
=> Log queue remove unused code

lib/rewrite/rewrite-set-pri.c, lib/rewrite/rewrite-set-pri.h, modules/grpc/otel/CMakeLists.txt, modules/grpc/otel/Makefile.am, modules/grpc/otel/otel-dest-worker.cpp, modules/grpc/otel/otel-dest-worker.hpp, modules/grpc/otel/otel-dest.cpp, modules/grpc/otel/otel-dest.hpp, modules/grpc/otel/otel-grammar.ym, modules/grpc/otel/otel-parser.c, modules/grpc/otel/otel-plugin.c, modules/grpc/otel/otel-protobuf-formatter.cpp, modules/grpc/otel/otel-protobuf-formatter.hpp, modules/grpc/otel/otel-protobuf-parser.cpp, modules/grpc/otel/otel-protobuf-parser.hpp, modules/grpc/otel/otel-source-services.hpp, modules/grpc/otel/otel-source.cpp, modules/grpc/otel/otel-source.hpp, modules/grpc/otel/syslog-ng-otlp-dest-worker.cpp, modules/grpc/otel/syslog-ng-otlp-dest-worker.hpp, modules/grpc/otel/syslog-ng-otlp-dest.cpp, modules/grpc/otel/syslog-ng-otlp-dest.h, modules/grpc/otel/syslog-ng-otlp-dest.hpp, modules/grpc/otel/tests/CMakeLists.txt, modules/grpc/otel/tests/Makefile.am, modules/grpc/otel/tests/test-syslog-ng-otlp.cpp, news/feature-4564.md, tests/copyright/policy
The `syslog-ng-otlp()` source and destination helps to transfer the internal representation of a log message between syslog-ng instances. In contrary to the `syslog-ng()` (`ewmm()`) drivers, `syslog-ng-otlp()` does not transfer the messages on simple TCP connections, but uses the OpenTelemetry protocol to do so.
It is easily scalable (`workers()` option), uses built-in application layer acknowledgement, out of the box supports google service authentication (ADC or ALTS), and gives the possibility of better load balancing.
The performance is currently similar to `ewmm()` (OTLP is ~30% quicker) but there is a source side limitation, which will be optimized. We measured 200-300% performance improvement with a PoC optimized code using multiple threads, so stay tuned.
_Note: The …
=> otel: add syslog-ng <-> syslog-ng communication via OTLP

modules/http/http-worker.c
On certain systems with certain gcc versions (notably gcc 2.11) curl_easy_setopt() nested inside g_assert() is too complex/long for the compiler.
=> http: Fix assert macro breaking gcc compiler

.gitmodules
the last missing step to get the latest ivikys fork state in syslog-ng builds
=> ivikys: set submodule lib/ivikys default branch to iv-work-pool-support-for-slave-work-items and synced HEAD to latest from the origin

scl/elasticsearch/elastic-http.conf
Setting it to non-empty value is not compatible with Elasticsearch v7+.
Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>
=> scl/elasticsearch-http: allow the deprecated `type()` field to be omitted

modules/http/compression.c
SLES 12 has rather stringent requirements for compiling on the platform. Such a check failed on the ground of strcmp() not being fortified.
resolves #4603
=> http: Fix strcmp() failing on SLES 12 compiler check

CMakeLists.txt, Makefile.am, modules/metrics-probe/metrics-probe-grammar.ym, modules/metrics-probe/metrics-probe.c, modules/metrics-probe/metrics-probe.h, modules/metrics-probe/tests/test_metrics_probe.c, news/feature-4610.md
You can use all value-pairs options, like `key()`, `rekey()`, `pair()` or `scope()`, etc...
Example:
```
metrics-probe(
key("foo")
labels(
"static-label" => "bar"
key(".my_prefix.*" rekey(shift-levels(1)))
)
);
```
```
syslogng_foo{static_label="bar",my_prefix_baz="almafa",my_prefix_foo="bar",my_prefix_nested_axo="flow"} 4
```
=> `metrics-probe`: Add dynamic labelling support via name-value pairs   

lib/stats/aggregator/stats-aggregator-registry.c, lib/stats/aggregator/stats-aggregator.c, lib/stats/aggregator/stats-aggregator.h, lib/stats/aggregator/stats-average.c, lib/stats/aggregator/stats-change-per-second.c, lib/stats/aggregator/stats-maximum.c
These commits were part of #4565.
This set of patches breaks KIRA for some reason. I think they are functionally correct, and further investigation is needed whether the testcase should be adjusted or the code. I have separated these commits as they are not necessary for #4565, so we should not block that PR on this change.
Depends on #4565.
=> stats-aggregator: refactor and realtime counters

lib/driver.c, lib/driver.h, lib/logqueue-fifo.c, lib/logqueue-fifo.h, lib/logqueue.c, lib/logqueue.h, lib/logsource.c, lib/logthrdest/logthrdestdrv.c, lib/logwriter.c, lib/stats/stats-cluster-key-builder.c, lib/stats/stats-cluster-key-builder.h, lib/stats/stats-cluster.h, lib/stats/tests/test_stats_cluster_key_builder.c, lib/tests/test_logqueue.c, modules/affile/affile-dest.c, modules/afprog/afprog.c, modules/afsocket/afsocket-dest.c, modules/diskq/diskq.c, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-non-reliable.h, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk-reliable.h, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/tests/test_diskq_counters.c, modules/diskq/tests/test_logqueue_disk.c, modules/examples/sources/threaded-diskq-source/threaded-diskq-source.c
This PR adds the functionality to set the options of the builder on different layers, so we don't need to unnecessarily clone and reset it. The call site calls a `push()`, does its thing, then calls a `pop()`, and the builder's state will be restored.
News file entry not needed.
=> stats-cluster-key-builder: add stack feature

modules/systemd-journal/journal-reader.c, modules/systemd-journal/tests/test-source.c, modules/systemd-journal/tests/test-source.h, modules/systemd-journal/tests/test_systemd_journal.c, news/feature-4553.md
Resolves #3417 
This PR enables using multiple systemd-journal() sources as long as they use different namespaces.
The persist names were already configured to use the systemd-journal namespace as part of the string, so no changes were needed with creating persist names.
=> systemd-journal: enable multiple systemd-journal sources

COPYING, docker/Dockerfile
Based on:
https://github.com/balabit/syslog-ng-docker/blob/master/LICENSE
Resolves #4425
=> docker: add license header

modules/python/python-startup.c
=> python: Fix use-after-free

lib/transport/tls-context.c, lib/transport/tls-context.h, modules/afsocket/afinet-dest.c, modules/afsocket/afsocket-signals.h, modules/examples/inner-destinations/tls-test-validation/tls-test-validation.c, news/feature-4628.md
This is a somewhat modified version of #4613
@CedricArickx I changed your PR but I didn't want to overwrite it, please review the changes I have made and let me know if you agree. I opened a new PR instead of overwriting yours.
=> No hostname check ssl opt

lib/cfg-grammar.y, lib/cfg-parser.c, lib/logqueue-fifo.c, lib/logqueue.h, lib/logscheduler.c, lib/logscheduler.h, lib/logthrdest/logthrdestdrv.c, lib/logthrdest/logthrdestdrv.h, lib/template/eval.c, lib/template/eval.h, modules/diskq/logqueue-disk-non-reliable.c, modules/diskq/logqueue-disk-reliable.c, modules/diskq/logqueue-disk.c, modules/diskq/logqueue-disk.h, modules/diskq/qdisk.c, modules/diskq/qdisk.h, modules/http/http-grammar.ym, modules/http/http-parser.c
This PR is a preparation step for the Loki destination driver.
This option can be used to direct similar messages to the same worker.
Similarity is determined based on hashing the value of the `worker-partition-key()` template specified by the user.
It can be used to retain ordering for a subset of messages or, to accumulate batches of certain types of messages.
When the `flush_on_key_change` flag is set, the destination driver will close and flush batches when a key change (key collision) is detected.
=> logthrdestdrv: worker partitioning

modules/grpc/CMakeLists.txt, modules/grpc/loki/CMakeLists.txt, modules/grpc/otel/CMakeLists.txt
=> cmake: Made Loki and Otel modules both switchable in cmake builds and made the corresponding module switches always visible

lib/cfg-args.c
Required block parameters are represented as NULL values in the CfgArgs object, which means that we can encounter NULL as value for a block argument when formatting __VARARGS__.
Take care of this by substituting an empty string in this case.
=> cfg-args: fix __VARARGS__ substitution of NULL values

lib/cfg-grammar.y
syslog-ng was giving me invalid error traces whenever I was using blocks, at least if the starting brace of the block was not on the same line as the "block" keyword. E.g:
```
block source whatever() {
};
block source whatever(
foo(bar)
baz(bat)
)
{
};
```
The fix is to record the location of the block content instead of the block statement as a whole. This fixes up @line references that are emitted as blocks get expanded.
=> cfg-grammar.y: fix location information for blocks

lib/host-resolve.c, modules/afsocket/afinet-source.c, modules/afsocket/afsocket-source.c, modules/afsocket/afsocket-source.h, modules/basicfuncs/tests/test_basicfuncs.c
When the port is set to 0, we would allocate a dynamic port for
our listeners. This can happen when we explicitly set port to 0 or when
we use an unknown service name (as syslog-ng will happily resolve the
service from /etc/services).
This behaviour does not add too much value, syslog-ng would open a port randomly.
This patch changes afsocket to avoid opening the listener in these cases.
The intent for this change is to be able to list source drivers in a
complex driver such as default-network-drivers() and still be able to
disable the constituent drivers just by setting their port to 0.
=> Dont activate listener for port 0

lib/gprocess.c, syslog-ng/main.c
There's an ugly warning message at startup in containers, unless the --no-caps command line option is explicitly used. This PR should prevent that by disabling capability management completely when we are running as non-root.
At the moment, I am checking this with euid == 0, which might not be the best way to check this.
I've also added stricter validation for the --user and --group options so that we exit if either cannot be resolved.
=> Disable capability management when running as non root

lib/transport/tls-context.c, lib/transport/tls-context.h, lib/transport/tls-session.c, news/feature-4642.md
In some cases you want to verify the ssl certificate authenticity but don't care about the validity period. For example when working in a system without an NTP server.
Currently there is no way to do this except for simply not verifying the certificate at all.
This option disables the ssl validity period check, but still does all other verification steps.
=> tls-context: add ignore-validity-period option for TLS

lib/mainloop.h, news/feature-4646.md, syslog-ng/main.c
This should fix #4592 
It adds a --check-startup command line option that causes syslog-ng to perform a complete config initialization and then
exit with the exit code indicating the result: 0 indicates complete success, non-zero indicates failure. (1 indicates syntax error, 2 a runtime error)
=> Add heavy weight config check

.github/workflows/devshell.yml
Please note the `-print0` part, which is needed as some filenames have special characters in them that are not allowed (e.g., *).
This has been split off from the PostgreSQL csvlog parser as it is valuable by itself and currently 2 PRs are affected by it as well ([4660](https://github.com/syslog-ng/syslog-ng/actions/runs/6387435123/job/17340795274?pr=4660) and [4544](https://github.com/syslog-ng/syslog-ng/actions/runs/6420892834/job/17434026527?pr=4544))
=> gha: fix light reports folder upload

.gitmodules
Instead of merging all syslog-ng originated patches from a PR, create a tip branch that incorporates them all.
The ivykis commit id itself is not changed with this patch, it remains the same.
This would be pretty important to be merged as new git clones would checkout the wrong branch without this.
I've cleaned up the original PR so that can be merged to ivykis master.
=> .gitmodules: instead of a PR use a syslog-ng specific tip branch

lib/secret-storage/tests/test_secret_storage.c, modules/afprog/afprog.c, modules/syslogformat/syslog-format.c
This branch fixes a warning that just popped up for me with a new gcc.
It also contains a fix for an older, but so far unfixed warning in afprog.c
And gets rid off some dead code in syslog-format.
No user visible changes, no NEWS file.
=> Minor warning fixes

CMakeLists.txt, cmake/print_config_summary.cmake, configure.ac
autotools, cmake: macOS XCode15 new linker has some issues, added options (--enable-force-classic-linking, FORCE_CLASSIC_LINKING) to switch back to classic linking till  those are not fixed
Signed-off-by: Hofi [hofione@gmail.com](mailto:hofione@gmail.com)
=> Fix macOS C++ builds

configure.ac, modules/examples/CMakeLists.txt, modules/examples/Makefile.am, modules/examples/destinations/example_destination/CMakeLists.txt
This is a bit more generic version of https://github.com/syslog-ng/syslog-ng/pull/4660 that allows switching on/off all the example modules both in cmake and autotools builds
- Removed autotools, and `example_destination` example only compile switch ENABLE_EXAMPLE_DESTINATION
- Added example modules wide common option ENABLE_EXAMPLE_MODULES both to autotools and cmake builds
=> Add option to turn on/off all example modules

lib/scanner/csv-scanner/csv-scanner.c, lib/scanner/csv-scanner/csv-scanner.h, lib/scanner/csv-scanner/tests/test_csv_scanner.c, modules/csvparser/csvparser.c, modules/csvparser/csvparser.h, modules/csvparser/tests/Makefile.am, modules/csvparser/tests/test_csvparser.c, modules/csvparser/tests/test_csvparser_from_config.c, news/feature-4678.md
This is a slightly reworked version of #4160  which allows csv-parser() to parse into the anonymous list $*
With this config:
@version: current
log {
source { tcp(port(2000) flags(no-parse)); };
parser { csv-parser(delimiters(',')  dialect(escape-backslash)); };
destination { stdout(template("$ISODATE $*\n")); };
};
=> Csv parser columnless

lib/cfg-grammar.y
The template_item nonterminal overwrites the value of $0, so we need to set it again.
Bug was catched via valgrind:
```
==2803776== Invalid read of size 1
==2803776==    at 0x491A973: log_template_set_escape (templates.c:298)
==2803776==    by 0x48EAA94: main_parse (cfg-grammar.y:883)
==2803776==    by 0x48AD89A: cfg_parser_parse (cfg-parser.c:434)
==2803776==    by 0x48A7994: cfg_run_parser (cfg.c:562)
==2803776==    by 0x48A7E8D: cfg_read_config (cfg.c:684)
==2803776==    by 0x48CD526: main_loop_read_and_init_config (mainloop.c:692)
==2803776==    by 0x10ADF6: main (main.c:320)
==2803776==  Address 0x6782808 is 40 bytes inside a block of size 87 free'd
==2803776==    at 0x484B27F: free (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==2803776==    by 0x48EAB75: main_parse …
```
=> cfg-grammar: fix setting template-escape() in template block

modules/metrics-probe/metrics-probe.c, news/bugfix-4685.md
A `metrics-probe()` instance might be used in multiple threads at the same time, so it must be stateless.
Fixes #4677.
=> metrics-probe: move label_buffers to TLS 

lib/filter/filter-cmp.c, lib/filter/filter-cmp.h, lib/filter/filter-expr-grammar.ym, lib/filter/filter-pipe.c, lib/parser/parser-expr.c
Something I stumbled into while working on something else. I am not sure it warrants a news entry.
* We leak an EVTTAG instance per filter comparison operator upon each reload (~100 bytes per operator)
* we might use the LogMessage instance right after being freed if trace level logging is enabled (to query the rcptid)
=> Fix per reload memory leak and a use after free in trace level logging

modules/grpc/CMakeLists.txt, modules/grpc/loki/CMakeLists.txt, modules/grpc/otel/CMakeLists.txt, modules/grpc/protos/CMakeLists.txt
- added the missing cmake grpc-protos lib dependency to loki module
- added missing loki protobuf generation to the cmake builds
- based on our conversation with @bazsi dropped all the grpc sub-module switches, only enable-grpc remained
- dropped the otel/loki autotools module switch PR (#4676)
- removed the earlier (cmake only) otel/loki module switches  (#4649)
Signed-off-by: Hofi [hofione@gmail.com](mailto:hofione@gmail.com)
=> cmake: Loki and Otel module building corrections

lib/cfg-parser.c, news/bugfix-4689.md
If the input was at least 32 bytes long, then the terminating NULL character was placed on the flag[32] position instead of flag[31].
I was only able to reproduce it using [axosyslog](https://github.com/axoflow/axosyslog-docker/pkgs/container/axosyslog) images.
=> cfg-parser: fix flag buffer overflow

.github/workflows/macos.yml, CMakeLists.txt, configure.ac, modules/python/tests/CMakeLists.txt, modules/python/tests/Makefile.am
- CI: Re-enabled cmake check build step in the CI Action
- cmake/autotools: added the missing -flat_namespace linker option to cmake builds and made this option conditional, it is not needed for production build just for the current mocking solution in the criterion tests
Fixes: https://github.com/syslog-ng/syslog-ng/issues/4625
Signed-off-by: hofione@gmail.com
=> macOS CMake check fails

lib/filter/filter-tags.c, modules/appmodel/app-parser-generator.c, tests/light/functional_tests/parsers/app-parser/test_app_parser.py, tests/light/src/syslog_ng_config/renderer.py, tests/light/src/syslog_ng_config/syslog_ng_config.py
This branch adds the new allow-overlaps() option to control whether application adapters are assumed to not overlap. In this case the first matching app wins and the rest of the patterns are not even tried.
If allow-overlaps(yes) is specified to app-parser(), that would mean that all adapters are tried sequentially and matching
continues even if we found the first matching one.
There are a couple of changes in this mode:
``` 
app-parser(allow-overlaps(yes)) changes app-parser the following ways:
1) all applications are tried and we don't stop at the first matching one
2) app-parser() will accept the message by default, even if NO app matches it
3) the ${.app.name} value is not set
```
=> app-parser(): allow multiple apps to match

lib/cfg-grammar.y, lib/logmsg/type-hinting.c, lib/logmsg/type-hinting.h, lib/scanner/csv-scanner/csv-scanner.c, lib/scanner/csv-scanner/csv-scanner.h, lib/scanner/csv-scanner/tests/test_csv_scanner.c, lib/template/templates.c, lib/template/templates.h, modules/add-contextual-data/context-info-db.c, modules/add-contextual-data/contextual-data-record-scanner.c, modules/csvparser/csvparser-grammar.ym, modules/csvparser/csvparser.c, modules/csvparser/csvparser.h, modules/csvparser/tests/test_csvparser.c, modules/csvparser/tests/test_csvparser_perf.c, modules/csvparser/tests/test_csvparser_statistics.c, modules/examples/sources/msg-generator/msg-generator-source.c, tests/light/functional_tests/parsers/csv-parser/test_csv_parser.py, tests/light/functional_tests/templates/test_template_stmt.py
This PR adds type validation support to csv-parser:
```
csv-parser(delimiters(',')  columns(int(a), float(b)) dialect(escape-backslash));
```
Notice the type-hints around the column names. If the type validation fails, the parsing will fail too. What happens is determined by drop-invalid.
This PR depends on #4678
=> Csv parser typing

Makefile.am, optional-dev-requirements.txt, scripts/build-python-venv.sh
This tool helps in development, too.
You can find it in devshell at: `/source/dbld/build/venv/bin/syslog-ng-cfg-helper`
---
I have added this as an optional dev requirement, because old platforms (centos-7) does not support it.
=> optional-dev-requirements: add syslog-ng-cfg-helper

lib/logmsg/type-hinting.c, lib/parse-number.c, news/bugfix-4702.md
=> type-hinting,parse-number: use locale independent `strtod()`

lib/timeutils/scan-timestamp.c, lib/timeutils/tests/test_scan-timestamp.c
A discussion on reddit me at 3am triggered me to look into this, and due to past refactors this was a lot easier than I thought.
This is an often occuring issue with incoming syslog style logs.
=> timeutils: accept BSD timestamps where the day-of-month is not padded with spaces

.github/workflows/comment-on-version-bump-pr.yml, .github/workflows/draft-release.yml, .github/workflows/version-bump.yml
`hub` has been removed from the `ubuntu-latest` image.
Test runs:
* Version Bump: https://github.com/alltilla/syslog-ng/actions/runs/6956723251/job/18928427298
* PR: https://github.com/alltilla/syslog-ng/pull/126
* Draft Release: https://github.com/alltilla/syslog-ng/actions/runs/6957504148/job/18930527572
=> github-actions: use gh instead of hub

.github/workflows/check-cfg-grammar-changes.yml, .github/workflows/comment-cfg-grammar-changes.yml
As the `check-cfg-grammar-changes` workflow is triggered by the `pull_request` event, it acquires the permissions from the originator repo of the PR. If the originator repo is a fork, then it will not be able to comment on an upstream PR.
The solution to this is introducing a `workflow_run` workflow, which gets triggered by a completed `check-cfg-grammar-changes` run, runs in the upstream repo, and has the necessary permissions to comment on a PR.
A `workflow_run` workflow always runs on the source code on master, so it cannot be exploited by changing it in a PR.
For more info, see https://github.com/syslog-ng/syslog-ng-cfg-diff-pr/tree/v2
=> github-actions: comment cfg grammar diff in a separate workflow

lib/CMakeLists.txt, lib/Makefile.am, lib/on-error.c, lib/on-error.h, lib/template/templates.c, lib/template/templates.h, modules/csvparser/csvparser-grammar.ym, modules/csvparser/csvparser-parser.c, modules/csvparser/csvparser.c, modules/csvparser/csvparser.h, news/feature-4586.md, scl/CMakeLists.txt, scl/Makefile.am, scl/pgsql/pgsql.conf, tests/copyright/policy, tests/light/functional_tests/Makefile.am, tests/light/functional_tests/parsers/postgresql-csvlog-parser/test_postgresql_csvlog_parser.py, tests/light/src/syslog_ng_config/syslog_ng_config.py
add a new parser to process CSV log formatted by PostgreSQL (https://www.postgresql.org/docs/current/runtime-config-logging.html). The CSV format is extracted into a set of name-value pairs.
=> SCL parser for PostgreSQL csvlog

modules/correlation/radix.c, modules/correlation/tests/test_radix.c
When using 2 chars to match quoted strings (e.g. `(), `[]`, `{}`), we
want to detect nesting to capture the whole containing expression.
Matching `(foo (bar (baz) qux)) quux` against `@QSTRING::()@` previously
captured `(foo (bar (baz)` and now capture `(foo (bar (baz) qux))`.
Fixes: #4716
Signed-off-by: Romain Tartière <romain@blogreen.org>
=> patterndb: Add support for nested quotted string in @QSTRING@

doc/man/dqtool.1.xml, doc/man/loggen.1.xml, doc/man/pdbtool.1.xml, doc/man/persist-tool.1.xml, doc/man/secure-logging.7.xml, doc/man/slogencrypt.1.xml, doc/man/slogkey.1.xml, doc/man/slogverify.1.xml, doc/man/syslog-ng-ctl.1.xml, doc/man/syslog-ng-debun.1.xml, doc/man/syslog-ng.8.xml, doc/man/syslog-ng.conf.5.xml
This patch restores the copyright attribution / license to the manual pages.
The Copyright attribution is restored based on the commit + signed-of-by lines that created the file in the first place.
The license is GPL like the rest of the project (as per COPYING)
=> doc/man: add missing copyright information

lib/logqueue.c, lib/stats/stats-cluster.c, lib/stats/stats-cluster.h, lib/stats/stats-control.c, lib/stats/stats-control.h, lib/stats/stats-query-commands.c, lib/stats/stats-query.c, lib/stats/stats-query.h, lib/stats/stats-registry.c, lib/stats/stats.c, lib/stats/tests/test_stats_query.c
- added and using now a common implementation of stat counter reset
- stats-query refactored
- removed local hash table cache, using the stat cluster/counter instances directly
- it uses now a single pass to process the given query
- Doc PR: https://github.com/axoflow/axosyslog-core-docs/pull/37
Fixes: #4696
=> stats: counter underflow after `query --reset`

lib/cfg-grammar.y, lib/cfg-lex.l, modules/afsmtp/afsmtp.c
This PR moves a warning disabling pragma to a private location and fixing the couple of warnings that result from the change. No NEWS file needed.
=> Switch default warning fixes

lib/msg-format.c, lib/tests/test_msgparse.c, lib/utf8utils.h, modules/syslogformat/syslog-format.c, news/bugfix-4744.md, news/other-4744.md
- ~SDATA fields are now sanitized when the `sanitize-utf8-sdata` flag is enabled for RFC5424 inputs~
- the message field is sanitized when no utf-8 BOM is present and `sanitize-utf8` is enabled for RFC5424 inputs
- `sanitize-utf8` and `validate-utf8` now works with `flags(no-parse)`
=> UTF-8 sanitization/validation improvements

news/feature-4476.md, tests/loggen/loggen.c, tests/loggen/loggen_plugin.c, tests/loggen/loggen_plugin.h, tests/loggen/logline_generator.c, tests/loggen/logline_generator.h
This is split off from #3966, I've discovered that loggen  was only capable of doing  ~250k msg/sec per thread, which is not enough for the latest round of scalability improvements in syslog-ng.
=> Loggen performance improvements

modules/metrics-probe/metrics-probe.c, news/bugfix-4750.md
The `label_buffers = g_array_set_size(label_buffers, label_idx + 1);` code cleans the array, but if there are not static labels it is not executed.
=> metrics-probe: fix not cleaning labels when only dynamic labels are set 

modules/grpc/bigquery/bigquery-worker.cpp, modules/grpc/bigquery/bigquery-worker.hpp
We cannot fail in a threaded workers init(), because of lib/cfg.c:344.
```
/*
* TLDR: A half-initialized pipeline turned out to be really hard to deinitialize
* correctly when dedicated source/destination threads are spawned (because we
* would have to wait for workers to stop and guarantee some internal
* task/timer/fdwatch ordering in ivykis during this action).
* See: https://github.com/syslog-ng/syslog-ng/pull/3176#issuecomment-638849597
*/
g_assert(cfg_tree_post_config_init(&cfg->tree));
```
No news file needed as it is not a released feature yet.
=> bigquery: move failable operations to connect() from init()

lib/cfg-lex.l
Added detection of unterminated quotes in the config lexer.
fixes #4746
=> Unterminated quotes in the config file can lead to partially parsed/included sub config files silently

modules/grpc/bigquery/bigquery-dest.cpp, modules/grpc/bigquery/bigquery-dest.h, modules/grpc/bigquery/bigquery-dest.hpp, modules/grpc/bigquery/bigquery-grammar.ym, modules/grpc/bigquery/bigquery-parser.c, modules/grpc/bigquery/bigquery-worker.cpp, modules/grpc/bigquery/bigquery-worker.hpp
BigQuery does not let us send a batch with more than 10 MB data: https://cloud.google.com/bigquery/quotas#write-api-limits
The new `batch-bytes()` option let's the user set an upper bytes size limit of the batch. By default it is 10 MB, and syslog-ng does not let the user set a larger value.
Please note that due to a framework limitation, the batch is possible to be at most 1 message larger than the set limit. You can set this limit to a lower value, but BigQuery never dropped a batch because of this in my manual E2E tests. _This might be because maybe Google meant 10 MiB as the limit not 10 MB, but we are following what the doc says._
---
```
bigquery(
project("syslog-ng-bigquery-project")
dataset("syslog_ng_bigquery_dataset")
table("syslog-ng-bigquery-table")
schema( …
```
=> `bigquery()`: add `batch-bytes()`

modules/cloud-auth/CMakeLists.txt, modules/cloud-auth/Makefile.am, modules/cloud-auth/cloud-auth-grammar.ym, modules/cloud-auth/cloud-auth-parser.c, modules/cloud-auth/google-auth.cpp, modules/cloud-auth/google-auth.h, modules/cloud-auth/google-auth.hpp, news/feature-4755.md, scl/CMakeLists.txt
This authentication method can be used on VMs in GCP to use the linked service.
Example minimal config, which tries to use the "default" service account:
```
cloud-auth(
gcp(
user-managed-service-account()
)
)
```
Full config:
```
cloud-auth(
gcp(
user-managed-service-account(
name("alltilla@syslog-ng-test-project.iam.gserviceaccount.com")
metadata-url("my-custom-metadata-server:8080")
)
)
)
```
This authentication method is extremely useful with syslog-ng's `google-pubsub()` destination,
when it is running on VMs in GCP, for example:
```
destination {
google-pubsub(
project("syslog-ng-test-project")
topic("syslog-ng-test-topic")
auth(user-managed-service-account())
);
};
```
For more info about this GCP authentication method, see:
* …
=> cloud-auth: implement gcp(user-managed-service-account()) 

modules/grpc/bigquery/bigquery-dest.cpp, modules/grpc/otel/otel-dest-worker.cpp, modules/grpc/otel/otel-dest.cpp, modules/grpc/otel/otel-dest.h, modules/grpc/otel/otel-dest.hpp, modules/grpc/otel/otel-grammar.ym, modules/grpc/otel/otel-parser.c, news/feature-4765.md
This patch adds a new compression(yes/no) option to syslog-ng-otlp() and opentelemetry() destinations.
While gRPC could support various compression methods, right now it only supports gzip or deflate, which are basically the same. This patch picks deflate if compression(yes) is specified.
=> OTLP compression support

dbld/Makefile.am, dbld/README.md, dbld/builddeps, dbld/images/README.md, dbld/images/centos-7.dockerfile, dbld/images/debian-bookworm.dockerfile, dbld/images/debian-bullseye.dockerfile, dbld/images/debian-buster.dockerfile, dbld/images/debian-sid.dockerfile, dbld/images/debian-testing.dockerfile, dbld/images/entrypoint.sh, dbld/images/fedora-39.dockerfile, dbld/images/ubuntu-focal.dockerfile, dbld/images/ubuntu-jammy.dockerfile, dbld/images/ubuntu-lunar.dockerfile, dbld/images/ubuntu-mantic.dockerfile, dbld/packages.manifest, dbld/rules
Instead of having to exec into the container as root to install extra packages make it possible to use sudo, without a password.
We can do this as our containers are meant to be used for development purposes only (e.g. building syslog-ng), the production container is separate.
No NEWS file is needed.
=> dbld: get rid of gosu and the fake-sudo commands

packaging/debian/control
Fixes packaging on `debian-sid`:
```
Runnign build as:  env DEB_BUILD_PROFILES=sng-python3 nojava  dpkg-buildpackage -rfakeroot -d
dpkg-buildpackage: error: fakeroot not found, either install the fakeroot
package, specify a command with the -r option, or run this as root
```
=> packaging: add fakeroot as a debian build dependency

dbld/images/entrypoint.sh
This commit fixes packaging on debian buster, which broke with the removal of gosu.
While creating a python venv, some cache files are to be written to the $HOME dir, which is /root, and the current user does not have a write permission to it.
With the gosu method the $HOME dir was still /root, but python did not try to use /root/.cache for some reason. I tried to pinpoint the cause, but could not find it. I also do not know why it only affects buster, but I wasted too much time to investigate.
Example run: https://github.com/alltilla/syslog-ng/actions/runs/7387771879
=> dbld: use home dir of the container user

modules/basicfuncs/Makefile.am, modules/basicfuncs/basic-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c, modules/basicfuncs/tf-tag.c, news/feature-4766.md, tests/copyright/policy
Syntax: 
```
$(tag <name-of-the-tag> <value-if-set> <value-if-unset>)
```
Unless the value-if-set/unset arguments are specified $(tag) results in a
boolean type, expanding to "0" or "1" depending on whether the message has
the specified tag set.
If value-if-set/unset are present, $(tag) would return a string, picking the
second argument <value-if-set> if the message has <tag> and picking the
third argument <value-if-unset> if the message does not have <tag>
=> `$(tag)` template function

modules/grpc/bigquery/bigquery-dest.cpp, modules/grpc/otel/otel-dest-worker.cpp, modules/grpc/otel/otel-dest-worker.hpp, modules/grpc/otel/otel-dest.cpp, modules/grpc/otel/otel-dest.h, modules/grpc/otel/otel-dest.hpp, modules/grpc/otel/otel-grammar.ym, modules/grpc/otel/otel-parser.c, modules/grpc/otel/syslog-ng-otlp-dest-worker.cpp, news/feature-4772.md
`opentelemetry()`, `syslog-ng-otlp()` destinations: Added a new `batch-bytes()` option.
This option lets the user limit the bytes size of a batch. As there is a default 4 MiB batch limit by OTLP, it is necessary to keep the batch size smaller, but it would be hard to configure without this option.
Please note that the batch can be at most 1 message larger than the set limit, so consider this when setting this value.
The default value is 4 MB, which is a bit below 4 MiB.
The calculation of the batch size is done before compression, which is the same as the limit is calculated on the server.
```
syslog-ng-otlp(
url("localhost:12345")
workers(16)
log-fifo-size(1000000)
batch-timeout(5000) # ms
batch-lines(1000000) # Huge limit, batch-bytes() will limit us sooner …
```
=> `opentelemetry()`, `syslog-ng-otlp()` destinations: add `batch-bytes()` option

news/feature-4760-1.md, news/feature-4760-2.md, scl/CMakeLists.txt, scl/Makefile.am, scl/pihole/pihole.conf, scl/qbittorrent/qbittorrent.conf, tests/copyright/policy
=> scl: add `qbittorrent()` and `pihole-ftl()` sources

lib/filter/filter-cmp.c, lib/logmsg/tests/test_type_hints.c, lib/logmsg/type-hinting.c, lib/logmsg/type-hinting.h, modules/afmongodb/afmongodb-worker.c, modules/afsql/afsql.c, modules/correlation/pdbtool/pdbtool.c, modules/csvparser/csvparser.c, modules/grpc/bigquery/bigquery-worker.cpp, modules/grpc/otel/otel-protobuf-formatter.cpp, modules/json/format-json.c, modules/python/python-types.c, modules/python/python-value-pairs.c, modules/riemann/riemann-worker.c, modules/timestamp/tf-format-date.c
Sometimes we are casting strings with an explicit length value, but the type hinting code simply assumed that everything was NUL terminated, which is not the case for indirect values.
No NEWS needed.
=> type-hinting: support explicit value length

lib/cfg-grammar.y, lib/logthrsource/logthrfetcherdrv.c, lib/logthrsource/logthrsourcedrv.c, lib/logthrsource/logthrsourcedrv.h, lib/logthrsource/tests/test_logthrfetcherdrv.c, lib/logthrsource/tests/test_logthrsourcedrv.c, modules/examples/sources/random-choice-generator/random-choice-generator-grammar.ym, modules/examples/sources/random-choice-generator/random-choice-generator.cpp, modules/examples/sources/random-choice-generator/random-choice-generator.hpp, modules/examples/sources/threaded-random-generator/threaded-random-generator-grammar.ym, modules/examples/sources/threaded-random-generator/threaded-random-generator.c, modules/grpc/otel/otel-grammar.ym, modules/grpc/otel/otel-source-services.hpp, modules/grpc/otel/otel-source.cpp, modules/grpc/otel/otel-source.h, modules/grpc/otel/otel-source.hpp, modules/python/python-fetcher.c, modules/python/python-source.c, news/developer-note-4774.md, news/feature-4774.md
This PR:
* Changes the API to work on a Worker instead of a Driver.
* Follows up the API changes at the users of the API.
* Adds a new `workers()` option, which is opt-in for threaded source based drivers.
* Starts multiple workers if set by the `self->num_workers` field.
Where it was easily applicable, I have implemented the multi worker support:
* `opentelemetry()`
* `random-choice-generator()`
* `example-random-generator()`
Where it would have needed more work, I have added an assert and a comment to point out that although those drivers are using the multi-worker API, they are not prepared to work with multiple workers:
* `python-source()`
* `LogThreadedFetcher`
This is a breaking API change, but if I remember correctly, we do not have any threaded source driver based drivers in PE, …
=> threaded source: multi-worker support

modules/grpc/bigquery/CMakeLists.txt
Yes, I know, i do not like it either, i would like to bring back in an upcoming round all the module switches for all the C++ modules (regardless if it is a GRPC-dependent or simple C++ one), but in a separate run.
Also, please NOTE that we do not have per-module switches now in any of the GRPC C++ modules, as we removed them earlier based on an agreement.
Also, we still/again have none matching settings in the cmake and autotools config files, I'd like to sync them too again in the above mentioned upcoming C++/GRPC module switch re-introduction round.
=> bigquery:  Fixed missing check of the dependent C++ switch in cmake config

lib/logmatcher.c, lib/tests/test_matcher.c, news/bugfix-4759.md
Example config for reproduction:
```
@version: 4.5
source s_local {
example-msg-generator(template("foo bar baz"));
};
destination d_local {
stdout(template("$A_foobar $MESSAGE $Z_barbaz"));
};
log {
source(s_local);
parser {
regexp-parser(
patterns("(?<A_foobar>[a-z]+) (?<MESSAGE>[a-z]+) (?<Z_barbaz>[a-z]+)")
);
};
destination(d_local);
};
```
=> logmatcher: fix storing matches if source handle changes

lib/logmatcher.c, lib/multi-line/multi-line-pattern.c, modules/basicfuncs/list-funcs.c, modules/correlation/radix.c
This is coming from a syslog-ng mailing list message. I don't think this warrants a NEWS entry.
=> pcre2: don't warn on JIT unavailability

lib/cfg-grammar.y, lib/logthrdest/logthrdestdrv.c, lib/logthrdest/logthrdestdrv.h, lib/logwriter.c, lib/logwriter.h, modules/afsql/afsql-grammar.ym, modules/afsql/afsql.c, modules/afsql/afsql.h, news/feature-4745.md
This branch adds a "seqnum-all" flag and a "no-seqnum-all" flags to all output drivers. 
With that flag set $SEQNUM would always be set  a sequence number that is related to the output connection, thereby incrementing an output sequence numbering.
This was requested by here: 
* https://github.com/syslog-ng/syslog-ng/discussions/4363
* https://github.com/syslog-ng/syslog-ng/discussions/4721
and I remember it came up before.
=> Hop by hop sequence number

modules/darwinosl/darwinosl-source.m, news/feature-4423.md
If the user has a single system() source it can be a huge, surprising change to read such a big amount of logs at next startup, keep the old behavior, as the earlier file source started to read from the end always.
=> darwinosl: Set `read-old-records` option to FALSE by default

lib/apphook.c, lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logmsg/tags.c, lib/logmsg/tags.h, lib/logmsg/tests/test_tags.c, lib/logsource.c, lib/msg-format.c, modules/basicfuncs/basic-funcs.c, modules/basicfuncs/tests/test_basicfuncs.c, modules/basicfuncs/tf-tag.c, modules/correlation/tests/test_patternize.c, modules/diskq/dqtool.c, modules/kafka/tests/test_kafka-props.c, modules/syslogformat/syslog-format.c
This PR makes it possible to report syslog parsing problems as builtin tags (e.g. named bit-like properties of the message).
These are the builtin tags:
/* means that the message is not valid utf8 */
LM_T_MSG_UTF8_SANITIZED,
/* msg-format parsing failed, "Error parsing ..." */
LM_T_MSG_PARSE_ERROR,
/* missing <pri> value */
LM_T_SYSLOG_MISSING_PRI,
/* no timestamp present in the original message */
LM_T_SYSLOG_MISSING_TIMESTAMP,
/* hostname field does not seem valid, check-hostname(yes) failed */
LM_T_SYSLOG_INVALID_HOSTNAME,
/* we seem to have found an octet count in front of the message */
LM_T_SYSLOG_UNEXPECTED_FRAMING,
/* no date & host information in the syslog message */
LM_T_SYSLOG_RFC3164_MISSING_HEADER,
/* incorrectly quoted RFC5424 SDATA */ …
=> Use tags for incorrect input reporting

modules/http/http-worker.c, modules/http/http-worker.h, news/feature-4805.md
```
syslogng_output_http_requests_total{url="http://localhost:8888/bar",response_code="200",driver="http",id="#anon-destination0#0"} 16
syslogng_output_http_requests_total{url="http://localhost:8888/bar",response_code="401",driver="http",id="#anon-destination0#0"} 2
syslogng_output_http_requests_total{url="http://localhost:8888/bar",response_code="502",driver="http",id="#anon-destination0#0"} 1
syslogng_output_http_requests_total{url="http://localhost:8888/foo",response_code="200",driver="http",id="#anon-destination0#0"} 24
```
=> http: add `syslogng_output_http_request_status_codes_total` metric

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, modules/affile/affile-source.c, modules/affile/affile-source.h, modules/affile/named-pipe.c, modules/affile/stdin.c, modules/afprog/afprog.c, modules/afsocket/tests/test-transport-mapper-unix.c, modules/afsocket/transport-mapper-unix.c, modules/afstreams/afstreams.c, modules/darwinosl/darwinosl-source.m, modules/mqtt/source/mqtt-source.c, modules/openbsd/openbsd-driver.c, modules/systemd-journal/journal-reader.c, modules/systemd-journal/tests/test_systemd_journal.c, scl/darwinosl/plugin.conf
This rounds up the setting of the $TRANSPORT macro for local log transport mechanisms.
The convention used is: local+<whatever we used to get the message>
* local+unix-stream, local+unix-dgram
* local+file
* local+pipe
* local+program
* local+devkmsg
* local+journal
* local+afstreams
* local+openbsd
+1 mqtt now sets $TRANSPORT to mqtt
=> Set transport macro for local mechanisms

lib/logthrdest/logthrdestdrv.c, lib/logthrdest/logthrdestdrv.h, news/feature-4807.md
```
syslogng_output_event_retries_total{driver="http",url="http://localhost:8888/${path}",id="#anon-destination0#0"} 5
```
=> logthrdest: add syslogng_output_event_retries_total metric 

lib/gsockaddr.c, lib/gsockaddr.h, modules/grpc/otel/otel-protobuf-formatter.cpp, modules/grpc/otel/otel-protobuf-formatter.hpp, modules/grpc/otel/otel-protobuf-parser.cpp, modules/grpc/otel/otel-protobuf-parser.hpp
This PR causes the syslog-ng-otlp() driver to also send the source address and the destination address associated with the log message, so that $SOURCEIP and $DESTIP will be properly expanded on the server as if it was received from those IPs (irrespectively of the syslog-ng-otlp() transport that happened in the middle).
=> syslog-ng-otlp(): send source and destination addresses to the peer

modules/grpc/loki/loki-dest.cpp, modules/grpc/loki/loki-dest.h, modules/grpc/loki/loki-dest.hpp, modules/grpc/loki/loki-grammar.ym, modules/grpc/loki/loki-parser.c, modules/grpc/loki/loki-worker.cpp, news/feature-4812.md
For example:
```
loki(
url("localhost:9096")
labels(
"app" => "$PROGRAM",
"host" => "$HOST",
)
workers(16)
batch-timeout(10000)
batch-lines(1000)
tenant-id("testTenant")
);
```
Questions: template support?
=> loki: add tenant-id() option

modules/secure-logging/slog.c, modules/secure-logging/slogkey/slogkey.c, modules/secure-logging/tests/test_secure_logging.c
This PR fixes the two errors in fedora rawhide:
```
modules/secure-logging/slog.c:937:63: error: passing argument 4 of 'g_io_channel_write_chars' from incompatible pointer type [-Wincompatible-pointer-types]
937 |   status = g_io_channel_write_chars(keyfile, key, KEY_LENGTH, &outlen, &error);
|                                                               ^~~~~~~
|                                                               |
|                                                               guint64 * {aka long long unsigned int *}
In file included from /usr/include/glib-2.0/glib.h:56,
from modules/secure-logging/slog.c:28:
/usr/include/glib-2.0/glib/giochannel.h:282:58: note: expected 'gsize *' {aka 'unsigned int *'} but argument is of type 'guint64 *' {aka 'long long unsigned int *'}
282 …
```
=> Fix fedora rawhide i686 compilation

modules/grpc/CMakeLists.txt, modules/grpc/Makefile.am, modules/grpc/bigquery/CMakeLists.txt, modules/grpc/bigquery/Makefile.am, modules/grpc/bigquery/bigquery-dest.cpp, modules/grpc/bigquery/bigquery-dest.hpp, modules/grpc/bigquery/bigquery-worker.cpp, modules/grpc/loki/CMakeLists.txt, modules/grpc/loki/Makefile.am, modules/grpc/loki/loki-dest.cpp, modules/grpc/loki/loki-dest.hpp, modules/grpc/loki/loki-worker.cpp, modules/grpc/metrics/CMakeLists.txt, modules/grpc/metrics/Makefile.am, modules/grpc/metrics/grpc-metrics.cpp, modules/grpc/metrics/grpc-metrics.hpp, modules/grpc/otel/CMakeLists.txt, modules/grpc/otel/Makefile.am, modules/grpc/otel/otel-dest-worker.cpp, modules/grpc/otel/otel-dest-worker.hpp, modules/grpc/otel/otel-dest.cpp, modules/grpc/otel/otel-dest.hpp, news/feature-4811.md, tests/copyright/policy
Implementing this with composition in each gRPC related dest driver is suboptimal.
The clean thing would be to have a common gRPC related dest driver, which already does handle metrics, and the otel, bigquery and loki drivers should descend from it. Unfortunately doing that would be a huge task right now.
IMO this should suffice for now, but we should really clean up the class hierarchy sometime later.
---
Affected drivers:
* `opentelemetry()`
* `syslog-ng-otlp()`
* `bigquery()`
* `loki()`
```
syslogng_output_grpc_requests_total{driver="syslog-ng-otlp",url="localhost:12345",response_code="ok"} 49
syslogng_output_grpc_requests_total{driver="syslog-ng-otlp",url="localhost:12345",response_code="unavailable"} 11
```
=> grpc: add request related metrics

modules/grpc/otel/otel-source.cpp
Shutdown() waits for all the working threads to finish, but they only finish, when _worker_wakeup() is called, but that only gets called after Shutdown(), so we have a deadlock.
Giving a deadline solves the issue:
> If all pending calls complete (and all their operations are
> retrieved by Next) before \a deadline expires, this finishes
> gracefully. Otherwise, forcefully cancel all pending calls associated
> with the server after \a deadline expires.
I have also removed the null-ing, as that frees the Server, which we still want to use in the worker threads for submitting the response.
Calling Shutdown() seems to be idempotent.
=> otel: add deadline to shutdown

lib/logqueue-fifo.c, news/other-4831.md
Shows the capacity (maximum possible size) of each queue.
Note that this metric publishes `log-fifo-size()`, which only limits non-flow-controlled messages.
Messages coming from flow-controlled paths are not limited by `log-fifo-size()`, their corresponding source `log-iw-size()` is the upper limit.
=> metrics: add syslogng_memory_queue_capacity

lib/filterx/object-string.c, lib/filterx/object-string.h, modules/grpc/otel/filterx/otel-logrecord.cpp, modules/grpc/otel/filterx/otel-logrecord.hpp, modules/grpc/otel/tests/CMakeLists.txt, modules/grpc/otel/tests/Makefile.am, modules/grpc/otel/tests/test-otel-filterx.cpp, tests/copyright/policy
=> otel: add support for `otel_logrecord($protobuf_value)` filterx fn

lib/cfg-lexer.c
This causes a crash later. Still waiting for confirmation if this is what resolves the issue.
https://splunk-usergroups.slack.com/archives/C4SL594CS/p1704465488078239
=> cfg-lexer: assume glob() returning success and zero files to be an error

lib/filterx/filterx-object.c, lib/filterx/filterx-object.h
Fixes a problem found in our nightly package build: https://github.com/syslog-ng/syslog-ng/actions/runs/8041425542
---
For some reason certain C++ compiler versions do not seem to be able to find the function pointers in the struct.
E.g. on debian-bullseye:
```
In file included from ../../modules/grpc/otel/filterx/otel-resource.hpp:29,
from ../../modules/grpc/otel/filterx/otel-resource.cpp:23:
../../lib/filterx/filterx-object.h:67:5: error: too many initializers for ‘FilterXType’ {aka ‘_FilterXType’}
67 |     }
|     ^
```
I did not investigate why certain compilers can and certain cannot handle this. We can do that, but I tried to save some time by just making the struct simpler and it seems to work.
=> filterx: make storing virtual methods simpler

modules/grpc/otel/filterx/CMakeLists.txt, modules/grpc/otel/filterx/Makefile.am, modules/grpc/otel/filterx/object-otel-array.cpp, modules/grpc/otel/filterx/object-otel-array.hpp, modules/grpc/otel/filterx/object-otel-kvlist.cpp, modules/grpc/otel/filterx/object-otel-kvlist.hpp, modules/grpc/otel/filterx/object-otel-logrecord.cpp, modules/grpc/otel/filterx/object-otel-resource.cpp, modules/grpc/otel/filterx/object-otel-scope.cpp, modules/grpc/otel/filterx/otel-field.cpp, modules/grpc/otel/filterx/otel-field.hpp, modules/grpc/otel/filterx/protobuf-field.cpp, modules/grpc/otel/filterx/protobuf-field.hpp, modules/grpc/otel/otel-plugin.c, modules/grpc/otel/tests/test-otel-filterx.cpp
#4842 made it possible to create `Array` and `KVList`, but it had a big problem: the created instances' inner values were completely separate from the encapsulating object, e.g. `LogRecord`, so they are not suitable for real-life use.
When we `get()` an `ArrayValue` of a `Message`, the respective created `FilterXObject` should operate on the `ArrayValue`. The current code creates a new `ArrayValue` every time, which is incorrect. The same is true for `KeyValueList`.
=> otel: support manipulating array and kvlist through logrecord

lib/cfg-grammar.y, lib/cfg-lexer.c, lib/filterx/filterx-grammar.ym, lib/filterx/filterx-parser.c, lib/filterx/object-primitive.c, lib/filterx/object-primitive.h, modules/grpc/otel/filterx/object-otel.h, modules/grpc/otel/filterx/otel-field.cpp, modules/grpc/otel/otel-plugin.c
Example code:
```
$otel_log = otel_logrecord();
$otel_log.severity_number = enum(otel.SEVERITY_NUMBER_INFO4);
```
=> filterx, otel: add severity_number enum support

lib/filterx/filterx-parser.c
=> filterx: do not parse global keywords

lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/expr-condition.c, lib/filterx/expr-condition.h, lib/filterx/filterx-grammar.ym, lib/filterx/filterx-parser.c, lib/filterx/tests/CMakeLists.txt, lib/filterx/tests/Makefile.am, lib/filterx/tests/test_expr_condition.c, tests/light/functional_tests/filterx/test_filterx.py
Filterx language is now able to handle conditionals, like 'if' and 'tenary'.
```
filterx{
#tenary
$baz = (("foo" eq "foo") ? "tenary-foo" : "tenary-not-foo");
#if,elif,else
if (false) {
$foo = "bar";
$bar = $foo;
} elif (false) {
expressions...
} else {
expressions...
};
}
```
=> Filterx condition introduced

modules/http/compression.c, modules/http/compression.h, modules/http/http-grammar.ym, modules/http/http-worker.c, modules/http/http.c, modules/http/http.h, modules/http/tests/test_compression.c
So far the compilation of http_dd with compression options only detected the presence of Zlib. This caused a compilation error when Zlib was found, but cURL on the system has been compiled without it.
=> http: Bugfix: http dd does not detect cURL compression support

lib/filterx/expr-dict.c, lib/filterx/expr-list.c, lib/filterx/expr-set-subscript.c, lib/filterx/expr-setattr.c, lib/filterx/filterx-expr.h, lib/filterx/object-json.c, modules/grpc/otel/filterx/object-otel-array.cpp, modules/grpc/otel/filterx/object-otel-kvlist.cpp, modules/grpc/otel/tests/test-otel-filterx.cpp
When we will write filterx based parsers, these functions will be used extensively. A recurring pattern is creating a dict or list, storing it as a kv pair in a parent dict with set_subscript() then wanting to add elements to it.
The current interface puts the responsibility to the Object's implementation to clone the value in the setter functions, and it always happens there.
For our internal parser codes, these clone() calls just waste resources, and makes it awkward to set the mutable value, and get the stored value immediately so it can modify it.
I have tried 3-4 different ways to solve this, but eventually came to this solution, which is the simplest and most performant: The Object interface now requires the implementation to accept the new value, and modify it, so that it …
=> [1/6] filterx: rework setattr() and set_subscript() virtual fns

lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/expr-comparison.c, lib/filterx/expr-dict.c, lib/filterx/expr-list.c, lib/filterx/expr-set-subscript.c, lib/filterx/expr-setattr.c, lib/filterx/filterx-expr.h, lib/filterx/filterx-globals.c, lib/filterx/filterx-object.c, lib/filterx/filterx-object.h, lib/filterx/object-dict-interface.c, lib/filterx/object-dict-interface.h, lib/filterx/object-json-array.c, lib/filterx/object-json-internal.h, lib/filterx/object-json-object.c, lib/filterx/object-json.c, lib/filterx/object-list-interface.c, lib/filterx/object-list-interface.h, lib/filterx/object-message-value.c, lib/filterx/tests/test_object_json.c, modules/grpc/otel/filterx/object-otel-array.cpp, modules/grpc/otel/filterx/object-otel-array.hpp, modules/grpc/otel/filterx/object-otel-kvlist.cpp, modules/grpc/otel/filterx/object-otel-kvlist.hpp, modules/grpc/otel/filterx/otel-field.cpp, modules/grpc/otel/filterx/protobuf-field.cpp, modules/grpc/otel/tests/test-otel-filterx.cpp
We do not want to have generic lists and dicts in filterx, as converting to and from that intermediate layer wastes resources.
Instead we will have an interface for them, and we will write our parser codes by using that interface. We will also have multiple implementations (json and otel). After all these we just have to connect the two somehow.
Depends on #4860
=> [2/6] filterx: dict and list interfaces with json and otel

modules/syslogformat/tests/test_syslog_format.c
Followup for: 7c3ea883339cea04d9165aa01e3597e29b79068d
=> syslogformat: fix crash in unit tests

lib/logthrdest/logthrdestdrv.c, lib/logthrdest/logthrdestdrv.h, modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-dest.h, news/other-4876.md
This bool-like metric shows whether a destination is reachable or not.
`sum()` can be used to count all unreachable outputs, hence the negated name.
For example:
```
syslogng_output_unreachable{driver="http",url="http://localhost",id="d_http#2",worker="0"} 0
syslogng_output_unreachable{id="d_network#0",driver="afsocket",transport="tcp",address="localhost:5555"} 1
```
=> threaded-dests/afsocket: add new metric `syslogng_output_unreachable`

lib/template/macros.c
With ipv6 disabled, there are linking errors currently. This fixes it by not using the symbols when IPv6 is disabled.
Solves #4810 with my config options
https://github.com/openembedded/meta-openembedded/blob/2487e65ee3842b6ae0c7a2628985be6189ed9ebf/meta-oe/recipes-support/syslog-ng/syslog-ng_4.6.0.bb
=> macros: guard ipv6 code with SYSLOG_NG_ENABLE_IPV6

modules/python-modules/syslogng/modules/s3/s3_destination.py, modules/python-modules/syslogng/modules/s3/scl/s3.conf
Making access_key and secret_key optional let the boto3 to execute the official credential chain process and use every supported authentication mechanism.
If the access_key and secret_key are set then those will be used as passing credentials in the parameter has the highest priority.
Please read [this](https://boto3.amazonaws.com/v1/documentation/api/latest/guide/credentials.html) page about the credential order.
This solves issue #4858.
=> s3: make access_key and secret_key optional

lib/filterx/expr-message-ref.c, lib/filterx/filterx-expr.h, lib/filterx/filterx-grammar.ym, lib/filterx/filterx-object.h, lib/filterx/filterx-scope.c, lib/filterx/filterx-scope.h
This is a refactor on FilterXScope and how we represent filterx variables. This depends on #4882.
Also, this was extracted from #4885 as a separate PR, because:
* #4885 is still work-in-progress 
* this code is becoming a dependency of #4879 as well.
=> Filterx scope variables refactor

lib/filterx/filterx-object.c, lib/filterx/object-json-array.c, libtest/filterx.c, libtest/filterx.h, modules/json/filterx-format-json.c, modules/json/tests/test_filterx_format_json.c
=> filterx: `format_json()`: use repr() instead of marshal()

lib/filterx/expr-assign.c, lib/filterx/expr-set-subscript.c, lib/filterx/expr-setattr.c, lib/filterx/filterx-grammar.ym, lib/filterx/tests/CMakeLists.txt, lib/filterx/tests/Makefile.am, lib/filterx/tests/test_filterx_expr.c
truthy check on filterx assign caused the falsey values to turn statements evaluation to unmatched.
- expr-assign
- expr-setttr
- expr-set-subscipt 
are no longer return the value of their expression. they return TRUE on success, NULL on error.
=> filterx: fix expr eval truthy check on assign

lib/filterx/expr-condition.c, lib/filterx/expr-dict.c, lib/filterx/expr-get-subscript.c, lib/filterx/expr-getattr.c, lib/filterx/expr-list.c, lib/filterx/expr-literal.c, lib/filterx/expr-message-ref.c, lib/filterx/expr-set-subscript.c, lib/filterx/expr-setattr.c, lib/filterx/expr-template.c, lib/filterx/filterx-expr.c, lib/filterx/tests/Makefile.am
This branch fixes up the Makefile.am version of the filterx unit tests as well as fix a memory leak caused by the missing filterx_expr_free_method() calls in derived classes.
=> Filterx fix memory leak and unit tests

lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/filterx-globals.c, lib/filterx/filterx-globals.h, lib/filterx/filterx-object.c, lib/filterx/filterx-object.h, lib/filterx/filterx-private.c, lib/filterx/filterx-private.h, lib/filterx/tests/CMakeLists.txt, lib/filterx/tests/Makefile.am, lib/filterx/tests/test_builtin_functions.c, lib/filterx/tests/test_filterx_object.c, lib/filterx/tests/test_type_registry.c
`istype` required to match to super types as well, this way the type check must be recursive/iterative. matching the type name strings with the type_str arguments could be a really slow operation. however filterx already has it's own effective recursive type matcher function, the `filterx_object_is_type(FilterXObject*, FilterXType*)`. to get the proper FilterXType parameter for this function we introduce the type registry in filterx-globals, which is able to lookup for a type name and returns a FilterXType for it.
usage example:
```
filterx {
$j = json();
if (istype($j, "dict")) {
do things...
};
}
```
=> inrduce Filterx istype builtin function

lib/filterx/expr-function.c, lib/filterx/tests/CMakeLists.txt, lib/filterx/tests/Makefile.am, lib/filterx/tests/test_expr_function.c, lib/filterx/tests/test_object_datetime.c
Add missing filterx function unit tests and fixes memory leak issue discovered by unit tests.
Add extended unit test for one of the most complex, existing filterx builtin function to check the new memory leak issue fix (strptime).
=> Filterx function memleak fix + unit tests

lib/filterx/object-datetime.c, lib/filterx/tests/test_object_datetime.c, tests/light/functional_tests/filterx/test_filterx.py
strptime now returns filterx-null on fail. NULL kept for hard errors
=> filterx: strptime fix

lib/cfg-grammar.y, lib/filterx/expr-condition.c, lib/filterx/filterx-grammar.ym, lib/filterx/tests/test_expr_condition.c, tests/light/functional_tests/filterx/test_filterx.py
ternary operator changes
- ternary operator is now able to return condition-expression's value when no expressions presented in true branch
i.e.:
```
filterx {
$res = "my expression" ? : "bad";
}
// res will be 'my expression'. it's useful to handle default-value like issues
```
- ternary operator now returns hard NULL (error) on condition-expression evaluation errors, this way interrupts the filterx block's running
- ternary now can be used without brackets
- 'tenary' naming typo fixed
=> Filterx fix tenary

lib/filterx/object-datetime.c, lib/filterx/object-datetime.h, lib/filterx/object-message-value.c, lib/filterx/object-null.c, lib/filterx/object-null.h, lib/filterx/object-primitive.c, lib/filterx/object-primitive.h, lib/filterx/tests/test_object_message.c
- repr method implemented for message-value type, this way string() typecast is able to handle message-value types
- add unit tests
=> Filterx message_value repr

lib/filterx/filterx-grammar.ym, tests/light/functional_tests/filterx/test_filterx.py
```
$list = json_array(["foo", "bar", "baz"]);
$MSG = json({
"key": "value",
"list": $list,
});
```
```
$MSG = json();
$MSG.foo = json({"answer": 42, "leet": 1337});
$MSG["bar"] = json({"answer+1": 43, "leet+1": 1338});
$MSG.list = json_array(["will be replaced"]);
$MSG.list[0] = json_array([1, 2, 3]);
$MSG.list[] = json_array([4, 5, 6]);
```
---
It is implemented as a shorthand. The cast function must support being called without any arguments.
This:
```
$foo = json({...});
```
Becomes this:
```
$foo = json();
$foo += {...};
```
Depends on #4899
=> filterx: add casted generator grammar

modules/mqtt/destination/mqtt-worker.c, modules/mqtt/destination/mqtt-worker.h
The current MQTT destination implementation does not answer to MQTT ping requests in time when only a low volume of messages are send to the MQTT broker.
MQTT broker might close the connection because of the missing responses, causing error messages in syslog-ng and even lost messages. One example is the broker operated by AWS as part of their "IoT Core Broker" service.
This patch adds regular calls to MQTTClient_yield every 0.5 seconds. These calls allow the MQTT client library to answer the ping requests.
The requirement for these calls is documented in the Paho MQTT C Client Library documentation in the comparision between synchronous and asynchronous clients:
"Client applications must call either MQTTClient_receive() or MQTTClient_yield() relatively frequently in order to allow …
=> Fix MQTT destination module loosing its connection to the broker regulary.

.github/workflows/macos.yml, lib/filterx/CMakeLists.txt, lib/filterx/Makefile.am, lib/filterx/expr-assign.c, lib/filterx/expr-set-subscript.c, lib/filterx/expr-setattr.c, lib/filterx/expr-variable.c, lib/filterx/expr-variable.h, lib/filterx/filterx-eval.c, lib/filterx/filterx-expr.h, lib/filterx/filterx-grammar.ym, lib/filterx/filterx-parser.c, lib/filterx/filterx-pipe.c, lib/filterx/filterx-scope.c, lib/filterx/filterx-scope.h, lib/filterx/tests/Makefile.am, lib/filterx/tests/test_builtin_functions.c, lib/filterx/tests/test_expr_condition.c, lib/filterx/tests/test_expr_function.c, lib/filterx/tests/test_filterx_expr.c, lib/logmpx.c, lib/logpipe.c, lib/logpipe.h, tests/copyright/policy, tests/light/functional_tests/filterx/test_filterx_scope.py
This PR adds the "declare" keyword to filterx to indicate that a floating value is kept all along the pipeline.
With this patch we are going to have 3 different kinds of variables:
* message-tied ($MSG): values that are extracted from the message and synced back if they are changed.
* locals (foo, wihout the '$'): values that get assigned in a filterx block and destroyed once the block exits
* pipeline variables (declare foo): same as locals but kept around for the entire input pipeline.
This branch also integrates filterx more with  the syslog-ng pipeline, as I made an effort to clone/sync the FilterXScore only when absolutely necessary, which needed integration with LogMultiplexer and LogPipe.
A FilterXScope:
* has a dirty state in which case it needs to be synced with the message
* can …
=> Filterx add "declare"-d variables

lib/stats/stats-prometheus.c, news/other-4921.md
As the `stats prometheus` command is intended to be used to forward metrics to Prometheus or any other time-series database, displaying orphaned metrics should be avoided in order not to insert new data points when a given metric is no longer alive.
In case you are interested in the last known value of orphaned counters, use the `stats` or `query` subcommands.
=> stats: do not show orphan metrics for `stats prometheus`

lib/filterx/expr-boolalg.c, lib/filterx/expr-function.c, lib/filterx/expr-get-subscript.c, lib/filterx/expr-getattr.c, lib/filterx/expr-set-subscript.c, lib/filterx/expr-setattr.c, lib/filterx/expr-template.c, lib/filterx/expr-template.h, lib/filterx/expr-variable.c, lib/filterx/filterx-eval.c, lib/filterx/filterx-eval.h, lib/filterx/filterx-expr.c, lib/filterx/filterx-expr.h, lib/filterx/filterx-object.c, lib/filterx/filterx-object.h, lib/filterx/object-dict-interface.c, lib/filterx/tests/test_expr_condition.c, lib/filterx/tests/test_filterx_expr.c, modules/grpc/otel/filterx/object-otel-logrecord.cpp, modules/grpc/otel/filterx/object-otel-resource.cpp, modules/grpc/otel/filterx/object-otel-scope.cpp, modules/grpc/otel/tests/test-otel-filterx.cpp
This PR implements an error handling for filterx expressions, so the key "error" cases are reported as statements
are evaluated.
It just covers variables/setattr/getattr/set-subscript/get-subscript
Functions are not covered yet.
This sits on top of #4885
=> Filterx error handling

modules/python-modules/syslogng/modules/s3/s3_destination.py, modules/python-modules/syslogng/modules/s3/scl/s3.conf
By setting role() option syslog-ng will assume the given role and use that to interact with the S3. This is a common pattern for running in AWS and accessing a bucket in another account.
NOTE: If you use only S3 calls then you might avoid this by setting a policy on the bucket but it is also common that you want to use SSE-KMS which requires an access to a KMS key. Syslog-ng does not support it, yet, but that could easily change soon.
The session will be automatically refreshed when needed.
For example:
```
destination d_s3 {
s3(
bucket( "mycompany-log-archive" )
role( "arn:aws:iam::1234567890:role/log-archiver-XXXXXXXX" )
object-key( "logs/${HOST}/year=${YEAR}/month=${MONTH}/day=${DAY}/syslog" )
object-key-timestamp( "${YEAR}-${MONTH}-${DAY}" )
);
};
```
The documentation also should be …
=> s3: add role() option to assume role

modules/python-modules/syslogng/modules/s3/s3_destination.py
A regression happened with the introduction of role support in the s3 destination: you can't use it with Minio anymore. This PR makes an attempt to fix that.
Calling sts.get_caller_identity() will fail with endpoints that are advertised as S3 compatible but provide no other AWS services, for example Minio:
> syslog-ng[80]: Exception while calling a Python function; caller='minio#0', class='syslogng.modules.s3.S3Destination', function='open', exception='ClientError: An error occurred (InvalidClientTokenId) when calling the GetCallerIdentity operation: The security token included in the request is invalid.'
This patch moves the call that's not used for anything but for displaying a log message about the assumed identity, inside the condition checking for a `role` option.
However, we can …
=> Fix s3 destination compatibility with services like MinIO

.github/workflows/github-pages.yml
CI: Simple redirection from https://syslog-ng.github.io to https://syslog-ng.github.io/doc/
Please remove the branch created by the GitHub UI "github-pages-redirect" I do not have the right to delete it.
=> CI: Create github-pages.yml workflow file

lib/stats/stats-cluster.c, lib/stats/stats-counter.h
The "unregister" path was not properly calling the cleanup function of StatsCounter, added it now.
PS: our stats subsystem is still a mess. This is not trying to remedy that.
=> stats: fix a memory leak of StatsCounter->name

lib/driver.c, lib/filter/filter-pipe.c, lib/filterx/filterx-eval.c, lib/filterx/filterx-eval.h, lib/filterx/filterx-object.h, lib/filterx/filterx-pipe.c, lib/filterx/filterx-scope.c, lib/filterx/filterx-scope.h, lib/filterx/filterx-weakrefs.c, lib/filterx/object-json.c, lib/logmpx.c, lib/logpipe.c, lib/logpipe.h, lib/parser/parser-expr.c, lib/rewrite/rewrite-expr.c, tests/light/functional_tests/filterx/test_filterx_scope.py
This PR is  a fix for a crash I introduced when I fixed a filterx memory leak in #4927  by using weakrefs in our object-json implementations. This branch starts with a light testcase to reproduce the issue.
The trigger for the crash is that when filterx_scope_clone() is called, it now adds weakrefs, but the clone will happen outside of the main filterx evaluation loop. Outside of that loop we don't have a scope, and without the scope we don't have weakrefs.
The solution implemented in this branch are:
* I moved the weakref tracking data structure from FilterXScope to FilterXEvalContext
* all filterx blocks (e.g. all filterx-pipe instances), share the weakref array (previously all of them had their own)
To make all of the above possible and simple, I made a  few refactors:
* I split the …
=> Filterx refactor eval context management

lib/filterx/expr-assign.c, lib/filterx/expr-condition.c, lib/filterx/expr-generator.c, lib/filterx/expr-generator.h, lib/filterx/expr-literal-generator.c, lib/filterx/expr-regexp.c, lib/filterx/expr-set-subscript.c, lib/filterx/expr-setattr.c, lib/filterx/expr-shorthand.c, lib/filterx/filterx-eval.c, lib/filterx/filterx-expr.c, lib/filterx/filterx-expr.h, lib/filterx/tests/test_expr_regexp.c, lib/filterx/tests/test_filterx_expr.c, modules/grpc/otel/filterx/object-otel-array.cpp, modules/grpc/otel/filterx/object-otel-kvlist.cpp, modules/grpc/otel/filterx/otel-field.cpp, modules/grpc/otel/filterx/protobuf-field.cpp, modules/grpc/otel/filterx/protobuf-field.hpp
This PR consolidates the evaluation loop for expression lists and then introduces a new property "ignore_falsy_return" for expressions. If this is set, then the expression evaluation continues _even_ if the current one returns a falsy result.
This would make it possible to bring assignments back to normal expressions and would also allow chaining. That is not added back though.
=> Filterx expr list eval

lib/cfg-block-generator.c
No news file needed as the bug was introduced recently in #4929.
=> cfg-block-generator: fix generating multi-line args

lib/scanner/csv-scanner/csv-scanner.c, news/bugfix-4947.md
=> csv-scanner: fix escape-backslash-with-sequences on ARM

lib/filterx/expr-template.c, lib/filterx/filterx-eval.c, lib/filterx/filterx-eval.h, lib/filterx/tests/test_filterx_expr.c, libtest/filterx-lib.c
FilterXEvalContext->template_eval_options was stored on an unrolled stack location.
=> filterx: fix template evaluation

Makefile.am, lib/compat/cpp-start.h, modules/cloud-auth/Makefile.am, modules/examples/Makefile.am, modules/grpc/bigquery/Makefile.am, modules/grpc/loki/Makefile.am, modules/grpc/otel/Makefile.am, modules/grpc/protos/Makefile.am, news/other-4933.md
libtool should follow transitive dependencies and link against the appropriate C++ standard lib (libc++ or libstdc++) automatically.
Fixes #4932, but let's wait for @alltilla's review because something doesn't seem right here.
=> C++ modules: remove direct libstdc++ linkage

lib/debugger/debugger.c, lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/template/macros.c, modules/correlation/pdbtool/pdbtool.c, modules/grpc/otel/otel-protobuf-formatter.cpp, modules/grpc/otel/otel-protobuf-parser.cpp, modules/grpc/otel/tests/test-otel-protobuf-parser.cpp
This branch starts to differentiate between global tags and local tags. Local tags start with a '.' and all previous built-in use of tags will be considered local).
The $TAGS macro would continue to expand to everything, so we would remain compatible, but the syslog-ng-otlp() driver is changed so that only global tags are transmitted to the peer.
This also contains a change to the $PRI value which is becoming a simple integer instead of a string representation of the same.
=> syslog-ng-otlp(): only send tags that have global relevance (e.g. not starting with a dot)

modules/python-modules/syslogng/modules/s3/s3_object.py
Google Cloud Storage's implementation of the S3 API responds the following error to requests like
`GET /bucket?uploads&prefix=p&key-marker=&upload-id-marker=`:
```xml
<Error>
<Code>InvalidArgument</Code>
<Message>Invalid argument.</Message>
<Details>Invalid upload ID marker: </Details>
</Error>
```
The changed code specifies these query parameters only in subsequent requests after we get a truncated response.
The boto3 `Client.list_multipart_uploads()` method doesn't accept None arguments, so this was the most readable solution that I could come up with.
=> s3: GCS compatibility

lib/cfg-lex.l, tests/light/functional_tests/filterx/test_filterx_scope.py
Message-tied variables in braces were not processed properly in filterx expressions as the lexer regexp was incorrect.
This branch fixes that.
=> filterx: fix ${variable} references in lexer

lib/filterx/filterx-object.c, lib/filterx/filterx-object.h, lib/filterx/object-json.c
Fixes
```
log "cache-json-file" {
source { example-msg-generator(); };
filterx {
js = cache_json_file("/tmp/test.json");
js.foo;
};
destination { stdout(template("$MSG\n")); };
};
```
=> filterx: `cached_json_file()` refcount fix

lib/filterx/expr-function.c, lib/filterx/expr-function.h, lib/filterx/filterx-grammar.ym, lib/filterx/filterx-private.h, lib/filterx/func-istype.c, lib/filterx/func-istype.h, lib/filterx/object-datetime.c, lib/filterx/object-datetime.h, lib/filterx/tests/test_builtin_functions.c, lib/filterx/tests/test_expr_condition.c, lib/filterx/tests/test_expr_function.c, lib/filterx/tests/test_func_istype.c, lib/filterx/tests/test_object_datetime.c, modules/json/filterx-cache-json-file.c, modules/json/filterx-cache-json-file.h, modules/kvformat/filterx-func-format-kv.c, modules/kvformat/filterx-func-format-kv.h, modules/kvformat/filterx-func-parse-kv.c, modules/kvformat/filterx-func-parse-kv.h, modules/kvformat/tests/test_filterx_func_format_kv.c, modules/kvformat/tests/test_filterx_func_parse_kv.c, tests/light/functional_tests/filterx/test_filterx.py
Functional changes:
```
format_kv(kvs_dict, value_separator="=", pair_separator=", ")
parse_kv(msg, value_separator="=", pair_separator=", ", stray_words_key="stray_words")
```
Function arguments are really similar to our existing driver level options:
* An argument is either positional or named.
* Positional arguments are always set before named arguments.
* Positional arguments are always mandatory.
* Named arguments can be set in any order.
* Usually named arguments are optional.
=> filterx: named function arguments

configure.ac
This allows us to easily run perf to get meaningful execution profiles.
=> configure.ac: add -fno-omit-frame-pointer when compiling with gcc

modules/grpc/otel/otel-grammar.ym, modules/grpc/otel/otel-parser.c, modules/grpc/otel/otel-protobuf-parser.cpp, modules/grpc/otel/otel-protobuf-parser.h, modules/grpc/otel/otel-protobuf-parser.hpp, modules/grpc/otel/otel-source.cpp, modules/grpc/otel/tests/test-otel-protobuf-parser.cpp
`keep-hostname(yes/no)` won't work in `opentelemetry()`/`syslog-ng-otlp()`, because
- we want to allow the same port (driver) to be used for `syslog-ng-otlp()` and `opentelemetry()`
- we always want to store the original hostname in `syslog-ng-otlp()`
- we don't want to parse anything in `opentelemetry()`, we have a separate parser for that
Instead of implementing `keep-hostname(yes/no)` scenarios for these 2 sources, we ignore this flag. `syslog-ng-otlp()` keeps the original hostname, `opentelemetry()` doesn't do anything, so it falls back to using the peer address (saddr) as HOST. 
(The code forces `keep-hostname(yes)` on both sources, but in practice the above is done due to the fallback mechanism.)
For the `opentelemetry()` parser, the `set-hostname(yes/no)` option is introduced, …
=> otel: hostname handling

modules/json/filterx-cache-json-file.c
This fixes a potential NULL deref in the error path.
=> json: fix crash in case cache_json_file() can't load the file

contrib/syslog-ng-helm-chart/templates/compress-job.yaml, contrib/syslog-ng-helm-chart/templates/deployment.yaml, contrib/syslog-ng-helm-chart/templates/service.yaml, contrib/syslog-ng-helm-chart/values.yaml
Multiple fixes in the `contrib/syslog-ng-helm-chart` helm chart
- updated the `apiVersion: batch/v1beta1` to `apiVersion: batch/v1` of the CronJob that was deprecated in 1.21 and removed in 1.25 k8s versions
- upgraded syslog-ng image tag and config @version from `3.27.1` to `4.7.1` in values.yaml
- fixed the tcp and udp ports that were mixed up in `service.yaml` and `deployment.yaml`
=> helm: multiple fixes

lib/cfg-grammar.y, lib/filter/filter-expr-grammar.ym, tests/copyright/policy, tests/light/functional_tests/Makefile.am, tests/light/functional_tests/filters/test_multiple_filters.py
In https://github.com/syslog-ng/syslog-ng/commit/6d74e60c4b2b51e9842ccab23902803b9ff8de2b, the precedence of ';' has implicitly changed for filter rules, changing the meaning of filter expressions:
The expression not program("a"); message("b"); should have the following interpretation: (not program("a")) and message("b").
Due to the accidentally changed precedence of ';', currently it is interpreted as not (message("a") and message("b")).
This patch recovers the original precedence, but also introduces precedence and left associativity for other semicolon-separated rules.
All the other (non-filter) uses of the ';' token is unambiguous, so this declaration won't interfere with those rules.
Resolves: #4980
Backport: [#122](https://github.com/axoflow/axosyslog/pull/122)
=> Fix the precedence of ';' in filters

lib/cfg-grammar.y
The log context was missing in the embedded block in the source/destination/parser/rewrite block that prevented using e.g. "block log" elements in these contexts.
Backport: [#141](https://github.com/axoflow/axosyslog/pull/141)
=> cfg-grammar: add context for looking up blocks

modules/diskq/qdisk.c
In case of NFS, flock() is emulated via fcntl() locks that only works in case we have write access as well.
Reported-by: Arpad Kunszt
Signed-off-by: Balazs Scheidler <balazs.scheidler@axoflow.com>
Backport: [#124](https://github.com/axoflow/axosyslog/pull/124)
=> diskq: open the dirlock file in read-write mode

modules/python-modules/syslogng/modules/s3/s3_destination.py, modules/python-modules/syslogng/modules/s3/s3_object.py, modules/python-modules/syslogng/modules/s3/scl/s3.conf, news/feature-4993.md
This PR enables to use the server side encryption on the s3() destination. It is a common pattern that data stored on the S3 bucket is encrypted at the rest.
S3 supports multiple server side encryption possibilities. This is only for the `aws:kms` method. In theory `aws:kms:dsse` should also work but as it uses the same arguments but I didn't test it so I disabled that intentionally.
Check the [s3api](https://docs.aws.amazon.com/cli/latest/reference/s3api/create-multipart-upload.html) documentation for the details.
This means that the server-side-encryption() option accepts only `aws:kms` or an empty string, which is the default.
The kms-key() should be:
* an ID of a key
* an alias of a key, but in that case you have to add the `alias/` prefix
* an ARN of a key
For example:
``` …
```
=> S3 server side encryption

lib/driver.c, lib/logthrdest/logthrdestdrv.c, news/bugfix-4994.md
This fixes a crash when init() fails on a disk-buffered destination:
modules/diskq/logqueue-disk.c:127:log_queue_disk_free_method:
assertion failed: (!qdisk_started(self->qdisk))
Backport: [#128](https://github.com/axoflow/axosyslog/pull/128)
=> driver: release the queues of half-initialized pipes 

lib/stats/stats-query.c, lib/stats/stats-registry.c, news/bugfix-4995-2.md, news/bugfix-4995.md
- All new counters should have their names filled.
- `g_pattern_spec_match_string: assertion 'string != NULL' failed`
Backport: [#129](https://github.com/axoflow/axosyslog/pull/129)
=> stats-query: fix assert and showing timestamps

modules/grpc/otel/filterx/object-otel-kvlist.cpp
otel: filterx kv-list get_subscript now returns hard NULL on missing key
Backport: [#150](https://github.com/axoflow/axosyslog/pull/150)
=> fix: otel kvlist get_subscript

modules/affile/affile-grammar.ym
The actual implementation. and validations restrict only the value to be higher than the `follow-freq` (ideally multiplication of it). As the `follow-freq` can be much smaller than one second it makes sense to allow this value to be a non-integer value as well.
=> multiline-options: Allow multi_line_timeout  set to a none integer value

.github/workflows/packages.yml, dbld/builddeps, dbld/images/centos-stream9.dockerfile, dbld/images/debian-testing.dockerfile, dbld/images/fedora-rawhide.dockerfile
This build failure was caused by wget linking to a different version library than what it was built with. This was fixed by transitioning duilddeps to use curl.
This PR also adds a package update to the testing images to ensure they are up-to-date and provide better early warning capabilities for breaking changes in their respective OS family.
=> Fixed Fedora Rawhide not Building in DBLD

lib/template/macros.c, news/bugfix-162.md
`MESSAGE` in particular can contain not just string data, but for example JSON as well.
This is necessary for the `$(format-json)` function to work properly with a json type `MESSAGE`.
Kudos to b1oodborne from Discord for finding this issue.
Signed-off-by: Attila Szakacs [attila.szakacs@axoflow.com](mailto:attila.szakacs@axoflow.com)
Backport: [#162](https://github.com/axoflow/axosyslog/pull/162)
=> macros: extract type information from MESSAGE, PROGRAM and HOST

.github/workflows/test-apt-packages.yml
Backport: [#207](https://github.com/axoflow/axosyslog/pull/207)
=> ci: re-enable debian-testing package update test

dbld/images/entrypoint.sh
Original issue:
- While going through the local dbld dev environment creation with:
- dbld/rules image
- dbld/rules bootstrap
- I've got the following error:
```
...
sudo: unknown user micek
sudo: error initializing audit plugin sudoers_audit
make: *** [dbld/rules:101: bootstrap-ubuntu-noble] Error 1
```
Root cause:
- After ubuntu:kinetic general "ubuntu" user was added to the base image with USER_ID: 1000
```
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:jammy bash -c "grep 1000 /etc/passwd"
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:kinetic bash -c "grep 1000 /etc/passwd"
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:lunar bash -c "grep 1000 /etc/passwd"
ubuntu:x:1000:1000:Ubuntu:/home/ubuntu:/bin/bash
micek@DESKTOP-0E9OKG3:~$ docker run -it ubuntu:mantic bash -c "grep 1000 …
```
=> dbld: Handle already exist USER_ID in docker environment

lib/scanner/csv-scanner/csv-scanner.c, lib/str-utils.h, lib/tests/test_str-utils.c, modules/afsnmp/afsnmpdest.c
Signed-off-by: László Várady <laszlo.varady@anno.io>
Backport: [#211](https://github.com/axoflow/axosyslog/pull/211)
=>  lib,modules: fix gcc warnings about discarded const qualifiers

lib/cfg.c, news/other-5030.md
This change allows syslog-ng to start even if the `@version` information is not present in the configuration file and treats the version as the latest in that case.
**NOTE:** syslog-ng will still raise a warning if `@version` is not present. Please use `@version: current` to confirm the intention of always using the latest version and silence the warning.
Modified backport: [#212](https://github.com/axoflow/axosyslog/pull/212)
=> cfg: Allow usage of `current` in config @version by default if it is not presented

modules/rate-limit-filter/rate-limit-parser.c, news/bugfix-169.md
`rate-limit()`: Fixed a crash which occured on a config parse failure.
Thanks to @nivelus for signaling this!
Fixes: #5001
Backport: [#169](https://github.com/axoflow/axosyslog/pull/169)
=> Rate limit parse error segfault fix

.github/workflows/macos.yml
=> CI: Use the internal (latest) ivykis libraries in the macOS CI builds

Makefile.am, cmake/Makefile.am, modules/afmongodb/Makefile.am
This fix addresses multiple CMake build issues from the release tar.gz file.
Thanks to @Schamschula and @czanik for reporting the issues.
NOTE: The release tar.gz file still cannot be built on case-insensitive file systems with `ivykis=internal` that is an [ivykis issue](https://github.com/buytenh/ivykis/issues/36) that hopefully will be fixed shortly, so I did not add a workaround for that at the end.
Fixes #4779
=> Fix release targz build issues

dbld/packages.manifest
I accidentally forgot the libbpf and docbook from the devshell in PR  #5052, this pr will re-add it
=> Add missing libbpd and docbook to devshell

Makefile.am, dbld/pkg-tarball
The real fix of the VERSION file cleanup.
Thanks for @MrAnno for [finding this](https://github.com/axoflow/axosyslog/pull/228)
=> dist: removed workaround of VERSION file cleanup and added the real fix

lib/CMakeLists.txt, lib/Makefile.am, lib/cfg-helpers.c, lib/cfg-helpers.h, lib/tests/CMakeLists.txt, lib/tests/Makefile.am, lib/tests/test_cfg_helpers.c, modules/afamqp/afamqp-grammar.ym, modules/afsmtp/afsmtp-grammar.ym, modules/afsnmp/afsnmp-grammar.ym, modules/afsocket/afsocket-grammar.ym, modules/afsql/afsql-grammar.ym, modules/afsql/afsql.c, modules/afsql/afsql.h, modules/afstomp/afstomp-grammar.ym, modules/grpc/otel/otel-grammar.ym, modules/redis/redis-grammar.ym, modules/riemann/riemann-grammar.ym
There was no port number validity check in the config file, numbers larger than 65535 or smaller than 0 were accepted and could cause incorrect port number usage without any warning or error.
=> cfg: Fix overflow of config port number definitions

docker/Dockerfile, news/other-5056.md
This will change the created docker image from debian-testing to debian-bookworm, resolves #5055
=> docker: change the official docker image to debian:bookworm

.github/workflows/test-apt-packages.yml
Reverts syslog-ng/syslog-ng#5060 as syslog-ng is back on debian-testing
=> Revert "github-actions: temp remove debian-testing official test"

modules/affile/file-reader.c, news/bugfix-5058.md
Resolves the error messages from #5057 as some fds lseek should not be called.
=> affile: Check if EOF checking is possible with lseek before adding checker

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logmsg/tests/test_log_message.c, lib/msg-format.c, lib/msg-format.h, lib/tests/test_msgparse.c, modules/syslogformat/syslog-format.c, news/feature-5063.md
Backport of [#245](https://github.com/axoflow/axosyslog/pull/245) by @bazsi
=> Add no-piggyback-errors flag to syslog-parser() and syslog related source drivers.

.github/workflows/macos.yml, configure.ac, contrib/Brewfile, modules/grpc/otel/tests/Makefile.am
Turned on GRPC modules for macOS builds, but because of various CMake issues only for autotools builds currently.
=> CI: enable grpc in macOS CI builds

lib/transport/tls-session.c, lib/transport/tls-session.h, lib/transport/transport-tls.c, news/feature-136.md
`tls()`: expose the key fingerprint of the peer in ${.tls.x509_fp} if trusted-keys() is used to retain the actual peer identity in received messages.
Backport of [#136](https://github.com/axoflow/axosyslog/pull/136/commits) by @bazsi
=> tls: Add support for ssl peer fingerprint

news/feature-178.md, scl/elasticsearch/elastic-datastream.conf, tests/copyright/policy
The `elasticsearch-datastream()` destination can be used to feed Elasticsearch [data streams](https://www.elastic.co/guide/en/elasticsearch/reference/current/data-streams.html).
Backport of [#178](https://github.com/axoflow/axosyslog/pull/178) by @OverOrion
=> elasticsearch: Add elasticsearch datastream destination

lib/cfg-lex.l, tests/light/functional_tests/filterx/test_filterx.py
- lexer was unable to handle escaped slashes in slash strings ( i.e: \foo/\bar\ ) this lesser refinement of lexer rule for slash strings allows the lexer to recognize escaped slashes
- gnu awk feaure set applie to slash strings as well
- light tests for slash string
Backport of [#181](https://github.com/axoflow/axosyslog/pull/181) by @bshifter
=> lib: lexer fix for slash strings

lib/metrics/CMakeLists.txt, lib/metrics/Makefile.am, lib/metrics/metrics-cache.c, lib/metrics/metrics-cache.h, lib/metrics/metrics-template.c, lib/metrics/metrics-tls-cache.c, lib/metrics/metrics-tls-cache.h, modules/http/http-worker.c, modules/http/http-worker.h, tests/copyright/policy
Depends on #5071
We do not show the orphaned metrics in the prometheus stats output. Registering, incrementing then unregistering the counter makes it orphaned.
This can be solved with binding the lifecycle of the counters to the worker.
No news file entry is needed, the counters disappeared after 4.7 was released.
Backport of [#180](https://github.com/axoflow/axosyslog/pull/180) by @alltilla
=> http: bind output_http_requests_total counter lifecycle to worker's 

lib/metrics/metrics-cache.c, lib/metrics/metrics-cache.h, modules/diskq/diskq-global-metrics.c
Depends on #5072
We do not show the orphaned metrics in the prometheus stats output. Registering, incrementing then unregistering
the counter makes it orphaned.
This can be solved with binding the lifecycle of the counters to the diskq_global_metrics instance.
No news file entry is needed, the counters disappeared after 4.7 was released.
Backport of [#182](https://github.com/axoflow/axosyslog/pull/182) by @alltilla
=> diskq/diskq-global-metrics: use metrics cache to keep counters alive

.github/workflows/publish-docker-image.yml
https://github.com/aquasecurity/trivy/discussions/1571
=> CI: replace deprecated template usage in trivy scan

lib/template/compiler.c, modules/json/tests/test_format_json.c, news/other-5080.md
Spaces around `=` in `$(format-json)` template function could cause a [crash](https://github.com/syslog-ng/syslog-ng/issues/5065).
The fix of the issue also introduced an enhancement, from now on spaces are allowed around the `=` operator, so the following `$(format-json)` template function calls are all valid:
```
$(format-json foo =alma)
$(format-json foo= alma)
$(format-json foo = alma)
$(format-json foo=\" alma \")
$(format-json foo= \" alma \")
$(format-json foo1= alma foo2 =korte foo3 = szilva foo4 = \" meggy \" foo5=\"\")
```
Please note the usage of the escaped strings like `\" meggy \"`, and the (escaped and) quoted form that used for an empty value `\"\"`, the latter is a breaking change as earlier an expression like `key= ` led to a json key-value pair with an empty value …
=> Segmentation fault in format json with a space before the = 5065

lib/cfg.c, lib/driver.c, lib/driver.h, lib/logpipe.c, lib/mainloop.c, lib/signal-slot-connector/signal-slot-connector.c, lib/signal-slot-connector/signal-slot-connector.h, lib/signal-slot-connector/tests/test_signal_slots.c, modules/afsocket/afinet-dest.c, modules/azure-auth-header/azure-auth-header.c, modules/cloud-auth/cloud-auth.c, modules/ebpf/ebpf-reuseport.c, modules/examples/inner-destinations/http-test-slots/http-test-slots.c, modules/examples/inner-destinations/tls-test-validation/tls-test-validation.c, modules/python/python-http-header.c
=> Syslog ng service crashes in g hash table lookup function after syslog ng ctl reload 5018

lib/cfg-lexer.c
In case an error happens during glob(), glibc returns GLOB_NOMATCH while musl returns GLOB_ABORTED. Handle both properly.
Backport of [#261](https://github.com/axoflow/axosyslog/pull/261) by @bazsi
=> cfg-lexer: fix handling of glob return values on musl

lib/compat/CMakeLists.txt, lib/compat/Makefile.am, lib/compat/inttypes.h, modules/geoip2/maxminddb-helper.c, modules/grpc/otel/otel-protobuf-formatter.cpp, modules/grpc/otel/otel-protobuf-parser.cpp, packaging/debian/copyright
Some platforms need inttypes.h and __STDC_FORMAT_MACROS defined prior to including it in order for macros like PRIu64 to work. Fix that.
Signed-off-by: Sergey Fedorov <barracuda@macos-powerpc.org>
=> Add missing inttypes.h and define __STDC_FORMAT_MACROS if undefined

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/msg-format.c, modules/syslogformat/syslog-format.c, modules/syslogformat/tests/test_syslog_format.c
The only case we had a hard error in RFC3164 when the incoming data had an opening angle bracket ("<") without a closing one. Actually this does not happen very often, but our piggy-backed error handling is a lot less user friendly than setting the right error tags. So let's do that.
Backport of [#285](https://github.com/axoflow/axosyslog/pull/285) by @bazsi
=> syslog-format: get rid off RFC3164 error case in favour of setting error

modules/python-modules/Makefile.am, modules/python-modules/syslogng/debuggercli/tests/test_langcompleter.py
=> python venv: disable `too-many-positional-arguments` as well for pylint

lib/logsource.c
The value of free_window was not updated properly as the counter was deregistered in deinit(), but AckTrackers propagate acknowledgments even after the source is deinitialized.
Backport of [#296](https://github.com/axoflow/axosyslog/pull/296) by @MrAnno
=> logsource: fix free_window counters

lib/driver.c, lib/logqueue-fifo.c, lib/logqueue-fifo.h
I was investigating a log source hang, and it occurred to me in this context that it's time to part ways with the legacy force-suspend functionality.
In the average configurations we have seen, the possible memory usage would have been doubled or tripled. We needed to avoid that scenario with this compatibility warning.
Backport of [#295](https://github.com/axoflow/axosyslog/pull/295) by @MrAnno
=> logqueue-fifo: remove legacy flow-control+log-fifo-size() coupling

lib/logsource.c, lib/logthrdest/logthrdestdrv.c, lib/metrics/dyn-metrics-template.c, lib/pragma-grammar.ym, modules/metrics-probe/metrics-probe.c
Fixes the following memory leaks:
==95913== 230 (104 direct, 126 indirect) bytes in 1 blocks are definitely lost in loss record 1,519 of 1,829
==95913==    at 0x48489F3: calloc (in /usr/libexec/valgrind/vgpreload_memcheck-amd64-linux.so)
==95913==    by 0x4A87BD9: g_malloc0 (gmem.c:133)
==95913==    by 0x49645EA: stats_cluster_key_builder_build_single (stats-cluster-key-builder.c:386)
==95913==    by 0x48C8ACE: _set_metric_options (logsource.c:738)
==95913==    by 0x48C8B62: log_source_set_options (logsource.c:756)
==95913==    by 0x48C43FD: log_reader_set_options (logreader.c:79)
==95913==    by 0x9C8E319: afsocket_sc_init (afsocket-source.c:186)
==95913==    by 0x9C8DC87: log_pipe_init (logpipe.h:387)
==95913==    by 0x9C8ED3A: afsocket_sd_process_connection (afsocket-source.c:480) …
=> Various memory leak fixes

modules/affile/wildcard-source.c
Related also #5086
Backport of [293](https://github.com/axoflow/axosyslog/pull/293) by @MrAnno
=> wildcard-source(): stop directory monitors at wildcard-source shutdown as soon as possible

lib/logreader.c
Backport of [@299](https://github.com/axoflow/axosyslog/pull/299) by @MrAnno
=> logreader: fix spurious wakeups by updating the suspended flag on I/O poll

tests/light/functional_tests/conftest.py, tests/light/src/syslog_ng/syslog_ng_cli.py
These minor fixes helps to run light more comfortable.
fix 1: add fix for a deprecated API call (psutil.Process().connections())
fix 2: handle syslog-ng crash when no core file has been detected
Backport of [#302](https://github.com/axoflow/axosyslog/pull/302) by @mitzkia
=> Light fixes

dbld/build.manifest
Reverts syslog-ng/syslog-ng#5054
libesmtp is back on debian-testing
=> dbld: re-enable smtp on debian-testing

modules/affile/logproto-file-writer.c, news/bugfix-303.md
If a partial write occurs, the written messages must be acknowledged.
It is important to note that a message may be written partially.
In that case, the message will be acknowledged once the complete write is successful. If write errors occur during this process, the partially written message may be duplicated.
Backport of [#303](https://github.com/axoflow/axosyslog/pull/303) by @MrAnno
=> file(), stdout(): fix log sources getting stuck

dbld/rules
For example in CI, like GitHub Actions.
Backport of [#305](https://github.com/axoflow/axosyslog/pull/305) by @alltilla
=> dbld: do not try to get pseudo terminal when TTY is not available

tests/light/CMakeLists.txt
The make light-check command appends the EXTRA_ARGS environment variable to the command line arguments. Its primary purpose is to filter light tests during execution, but by not enforcing the -k argument, its use becomes more versatile.
example: `make light-check EXTRA_ARGS="-k test_unset_empties"`
Backport of [#308](https://github.com/axoflow/axosyslog/pull/308) by @bshifter
=> light test: add EXTRA_ARGS processing on light tests

lib/logthrsource/logthrsourcedrv.c, lib/logthrsource/logthrsourcedrv.h, modules/grpc/otel/otel-source.cpp, news/bugfix-310.md
init_window_size was always 0 when workers() was set to >1, because it was placed too early in the init() method: -1 / num_workers .
Backport of [#310](https://github.com/axoflow/axosyslog/pull/310) by @MrAnno
=> otel: fix multi-worker window and fetch-limit calculation

lib/cfg-lexer.c, lib/cfg-lexer.h, lib/cfg.c, news/bugfix-5145.md
Template functions, for example, are constructed right when syslog-ng parses the configuration, so the @version directive must be placed at the top of the config file to make it consistent.
This patch fixes the implicit "current version" mechanism (when no @version is specified) by moving it back to the lexer, and warns the user about misplaced or redefined @version directives.
Reproducer: Place a template("$(format-json asd=asd)" anywhere in the configuration without an explicit @version declaration or place the @version declaration after the config block containing the mentioned template. A compatibility warning will be produced and syslog-ng will operate in half-"compat mode".
Backport of [#312](https://github.com/axoflow/axosyslog/pull/312) by @MrAnno
=> cfg: fix config-version incosistencies

packaging/package-indexer/cdn/azure_cdn.py, packaging/package-indexer/index-packages.py, packaging/package-indexer/indexer/indexer.py
That's the new object to handle AFD endpoints instead of the old CDN endpoint we upgraded from.
=> package-indexer: use afd_endpoints instead of endpoints in CDN purge call

modules/python-modules/syslogng/modules/s3/s3_destination.py, news/bugfix-5149.md
[syslog-ng](https://github.com/axoflow/axosyslog/issues/317) leaks an amount of memory every time it's reloaded if an s3 destination is configured. As a quick workaround we partially revert the patch introducing the use of boto3.Session when no role() is set.
Backport of [318](https://github.com/axoflow/axosyslog/pull/318) by @orymate
=> s3: workaround on-reload memleak when no role is set

modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-dest.h
caused by an unregister attempt of a key that might have no matching registered element pair as the address label in the registered key might have changed if not a fixed port is used.
=> afsocket-dest: fixed the stats_cluster_untrack_counter assertation

lib/cfg-block-generator.c, news/bugfix-5163.md
Certain SCL drivers have options without default values. This could (and in certain cases does) result in `_report_generator_args` trying to iterate  on a nullpointer, and crashing syslog-ng in the process.
=> Fixed crash on startup caused by missing cfg options in certain scl drivers

modules/affile/file-reader.c
Fixes: https://github.com/syslog-ng/syslog-ng/issues/5159
Signed-off-by: Hofi hofione@gmail.com
=> file-reader: added a more detailed, direct check if seek can be called on the file descriptor

README.md
The command provided to add an entry to the Ubuntu 22.04 sources list actually does add an entry for Ubuntu 24.04.
=> README: Fixed incorrect command for adding entry to sources.list in Ubuntu 22.04

dbld/builddeps
Base images of any RHEL/Fedora derived distros don't come with sudo in the base image, which will break the build later.
Signed-off-by: Tamas Pal <folti@balabit.com>
=> dbld: install sudo pacakge into RHEL based docker images

.github/workflows/macos.yml
=> CI: (temporally?!) removed the usage of the silently disappearing --preinstall option from the brew update command

doc/man/syslog-ng.8.xml
According to cap_from_text(3):
> A textual representation of capability sets consists of one or more whitespace-separated clauses.
> [...]
> Each clause consists of a list of comma-separated capability names [...], followed by an action-list.  An action-list consists of a sequence of operator flag pairs.  Legal operators are: '=', '+', and '-'.  Legal flags are: 'e', 'i', and 'p'.
The spaces before the coma is therefore unexpected, and will cause startup error, e.g.:
```
syslog-ng: Error parsing capabilities: cap_net_bind_service, cap_net_broadcast, cap_net_raw, cap_dac_read_search, cap_dac_override, cap_chown, cap_fowner=p cap_syslog=ep
```
Remove them so that the example can be copied-pasted from the man page to the cli.
=> Fix space in capabilities documentation

.github/workflows/macos.yml
--preinstall is renamed to --auto-update 
https://github.com/orgs/Homebrew/discussions/5896#discussioncomment-11937286
=> CI: corrected the renamed --preinstall option in the brew update command

modules/systemd-journal/journal-reader.c
Fixes: https://github.com/syslog-ng/syslog-ng/issues/5169
=> journal-reader: do not use a NULL ptr journal cursor and log a warning if the cursor cannot be get

lib/scanner/xml-scanner/xml-scanner.c, lib/transport/tls-context.c, lib/transport/tls-session.c, modules/affile/collection-comparator.c, modules/afsocket/afsocket-grammar.ym, modules/http/http-grammar.ym, modules/http/http.c, modules/xml/xml-grammar.ym
The first run of reviewing the config grammars and parsing.
Main issues we still have to address:
- further search for leaks like this, this run focused on string_list values only
- use common allocation/deallocation solutions for all types
- use common ownership agreements as currently
- sometimes the callee, sometimes the caller makes the cleanup of the arguments passed towards from the grammar, we should make this common as well
- when the caller takes over the ownership of the passed-toward argument it must be done consistently, now it is sometimes cloned/copied (like the string), but sometimes simply just assigned (like the string_list), I guess the copy/clone version is preferred to avoid possible allocator issues
Fixes: https://github.com/syslog-ng/syslog-ng/issues/5194 …
=> cfg: fix memory leaks when parsing config file

.github/workflows/comment-cfg-grammar-changes.yml
The owner is only needed if it's coming from a fork
BackPort of [#322](https://github.com/axoflow/axosyslog/pull/322) by @OverOrion
=> ci: fix cfg-grammar's PR ID query

lib/messages.h
So far if we were to use evt_tag_error() in debug or trace messages we got a compilation error. Fix that.
Signed-off-by: Balazs Scheidler <balazs.scheidler@axoflow.com>
Backport of [#325](https://github.com/axoflow/axosyslog/pull/325) by @bazsi
=> messages: capture errno in debug & trace messages as well

dbld/rules
No command was passed to /dbld/shell in these cases, causing these shells to exit.
Backport of [#335](https://github.com/axoflow/axosyslog/pull/335/commits) by @bazsi
=> dbld/rules: fix login and root-login targets

lib/multi-line/multi-line-pattern.c
Backport of [#347](https://github.com/axoflow/axosyslog/pull/347) by @bazsi
=> Fix glib warning in case multi line regexp error

modules/http/http.c
There are use-cases where the user wants to maintain ordering for certain categories of messages. In that case, closing the batch early is not necessary.
flush_on_worker_key_change can be changed from the HTTP destination's config, we should only force-set it to TRUE when templated URLs are used together with batches and multiple workers.
Backport of [#353](https://github.com/axoflow/axosyslog/pull/353) by @MrAnno
=> http: set flush_on_worker_key_change only when templateURL+batches are used

modules/syslogformat/syslog-format.c
Backport of [362](https://github.com/axoflow/axosyslog/pull/362) by @bazsi
=> syslog-format: fix debug message in case framing is found in front of the message

lib/logsource.c
`log_pipe_forward_msg()` frees msg.
Backport of [363](https://github.com/axoflow/axosyslog/pull/363) by @alltilla
=> logsource: fix use after free in message processing debug log

lib/gsockaddr.c, lib/gsockaddr.h, modules/grpc/otel/otel-protobuf-formatter.cpp
Messages originated from unix-stream or unix-dgram sockets made otlp crash.
Since it is unnecessary to forward local unix-based addresses, the fix is to skip non-inet addresses (instead of extending the implementation of g_sockaddr_get_address()).
Backport of [#328](https://github.com/axoflow/axosyslog/pull/328) by @MrAnno 
Depend on https://github.com/syslog-ng/syslog-ng/pull/5174
=> Otlp fix addr

lib/console.c, lib/console.h, lib/control/control-command-thread.c, lib/control/control-command-thread.h, lib/control/control-connection.c, lib/control/control-connection.h, lib/control/control-server-unix.c, lib/control/control-server.c, lib/control/control-server.h, lib/mainloop-control.c, lib/mainloop.c, lib/scratch-buffers.c, syslog-ng-ctl/CMakeLists.txt, syslog-ng-ctl/Makefile.am, syslog-ng-ctl/commands/attach.c, syslog-ng-ctl/commands/attach.h, syslog-ng-ctl/commands/commands.c, syslog-ng-ctl/commands/commands.h, syslog-ng-ctl/control-client-unix.c, syslog-ng-ctl/syslog-ng-ctl.c, tests/copyright/policy
This PR allows syslog-ng-ctl to connect back to syslog-ng's original stdin/out/err fds and re-acqiure the output on those fds.
There are three subcommands:
```
$ syslog-ng-ctl attach stdio --seconds 10
```
The other allows you to steal the log messages:
```
$ syslog-ng-ctl attach logs --seconds 10 --level trace
```
The other allows you to start the debugger on the new console:
```
$ syslog-ng-ctl attach debugger
```
There can only be one such attached process at any time.
Backport of [326](https://github.com/axoflow/axosyslog/pull/326) by @bazsi
Depends on: https://github.com/syslog-ng/syslog-ng/pull/5237
=> Syslog ng ctl attach command

lib/debugger/debugger-main.c, lib/debugger/debugger-main.h, lib/debugger/debugger.c, lib/debugger/debugger.h, lib/debugger/tracer.c, lib/debugger/tracer.h, lib/mainloop-control.c, syslog-ng-ctl/commands/attach.c
This is a continuation of https://github.com/syslog-ng/syslog-ng/pull/5238 to add interactive debugger functionality over syslog-ng-ctl
Backport of [327](https://github.com/axoflow/axosyslog/pull/327) by @bazsi
Depends on: https://github.com/syslog-ng/syslog-ng/pull/5238
=> Syslog ng ctl attach debugger

lib/debugger/debugger.c, lib/debugger/tracer.c, lib/debugger/tracer.h, lib/mainloop.c
This is a continuation of https://github.com/syslog-ng/syslog-ng/pull/5239 to add interrupt handling to the debugger. At the moment it only works on the original console, syslog-ng-ctl attach debugger does not propagate ctrl+c signals yet.
Backport of [339](https://github.com/axoflow/axosyslog/pull/339) by @bazsi
Depends on: https://github.com/syslog-ng/syslog-ng/pull/5239
=> Debugger interrupt handling

lib/console.c, lib/console.h, lib/mainloop-control.c, syslog-ng-ctl/commands/attach.c, syslog-ng-ctl/commands/attach.h, syslog-ng-ctl/commands/commands.h, syslog-ng-ctl/syslog-ng-ctl.c
console: add support for restoring the original console io handlers after an attached control client has finished its work
Signed-off-by: Hofi hofione@gmail.com
Depends on: https://github.com/syslog-ng/syslog-ng/pull/5240
=> Console io backup restore

CMakeLists.txt
=> cmake: fixed not existing LINUX var usage

modules/syslogformat/syslog-format.c, news/bugfix-5254.md
**A bug found by fuzzing with AFL++**
Backtrace:
```
* thread #2, name = 'syslog-ng', stop reason = signal SIGILL: illegal instruction operand
* frame #0: 0x00007ffff3f1b923 libsyslogformat.so`log_msg_parse_pri(self=<unavailable>, data=<unavailable>, length=<unavailable>, flags=<unavailable>, default_pri=<unavailable>) at syslog-format.c:55:23
frame #1: 0x00007ffff3f14068 libsyslogformat.so`log_msg_parse_legacy(parse_options=<unavailable>, data=<unavailable>, length=<unavailable>, self=<unavailable>, position=<unavailable>) at syslog-format.c:757:8
frame #2: 0x00007ffff3f0e584 libsyslogformat.so`syslog_format_handler(parse_options=<unavailable>, data=<unavailable>, length=23, self=<unavailable>) at syslog-format.c:1012:15
frame #3: 0x00007ffff7b460fe …
```
=> syslog-format: Fix integer overflow on set pri

.github/workflows/publish-docker-image.yml, scripts/syslog-ng-update-virtualenv.in
1.
By default it also checks for secrets in compiled Python binary files (/var/lib/syslog-ng-venv/lib/python3.12/site-packages/google/auth/crypt/__pycache__/_python_rsa.cpython-312.pyc)
See pip docs for more details
https://pip.pypa.io/en/stable/cli/pip_install/
Signed-off-by: Szilard Parrag <szilard.parrag@axoflow.com>
2.
Use the most reliable and quicker [AWS ECR location for trivy DBs](https://github.com/aquasecurity/trivy-java-db/issues/35)
Backport of:
[331](https://github.com/axoflow/axosyslog/pull/331) by @OverOrion 
[366](https://github.com/axoflow/axosyslog/pull/366/files) by @MrAnno
=> ci: fix trivy action

lib/stats/stats-cluster.c, news/bugfix-5261.md
syslog-mg now has a lot of gauge metrics, which should not be reset. Instead of implementing metric typing support and filtering based on that, this patch disallows the reset mechanism for all new metrics, since resetting anything sent to Prometheus does not make sense.
(The patch keeps the original behavior for legacy stats counters.)
Backport of [370](https://github.com/axoflow/axosyslog/pull/370) of @MrAnno
=> stats: do not reset new metrics

lib/cfg-grammar.y, lib/cfg-parser.c, lib/cfg.h, lib/logmsg/logmsg.c, lib/logmsg/logmsg.h, lib/logreader.c, lib/logreader.h, lib/msg-format.c, lib/msg-format.h, modules/syslogformat/syslog-format.c, modules/syslogformat/syslog-parser-grammar.ym, modules/syslogformat/tests/test_syslog_format.c, news/feature-5264.md
The check-program flag was added to validate the program field in syslog format. It verifies that the program field contains only the allowed characters '[a-zA-Z0-9].-_/()' and requires at least one alphabetical character in the program name. If these conditions are not met, it treats the program field and the remaining fields as part of the log message. This approach avoids using regular expressions to improve performance.
examples:
```
log {
source { tcp(port(2000) flags(check-hostname, check-program, dont-store-legacy-msghdr)); };
...
```
Backport of [380](https://github.com/axoflow/axosyslog/pull/380) by @bshifter
=> Check program name for rfc3164

modules/http/http.c
In case only batch-bytes() is set, the logthrdestdrv core will flush the batch, as it
will deduce that no batching is needed. Fix that.
PS: we might need a similar fix in gRPC related drivers.
Backport of [403](https://github.com/axoflow/axosyslog/pull/403) by @bazsi
=> http: fix batch-lines() in case only batch-bytes() is set

lib/stats/stats-csv.c, lib/stats/stats-csv.h, lib/stats/stats-query-commands.c, lib/stats/stats-query.c, lib/stats/stats-query.h, lib/stats/tests/test_stats_query.c, news/feature-5248.md, syslog-ng-ctl/commands/attach.c, syslog-ng-ctl/commands/commands.h, syslog-ng-ctl/commands/credentials.c, syslog-ng-ctl/commands/ctl-stats.c, syslog-ng-ctl/commands/query.c, syslog-ng-ctl/commands/query.h, syslog-ng-ctl/syslog-ng-ctl.c
`syslog-ng-ctl`: Formatting the output of the `syslog-ng-ctl stats` and `syslog-ng-ctl query` commands is unified.
Both commands got a new `--format` (`-m`) argument that can control the output format of the given stat or query. The following formats are supported:
- `kv` - the legacy key-value-pairs e.g. `center.queued.processed=0` (only for the `query` command yet)
- `csv` - comma separated values e.g. `center;;queued;a;processed;0`
- `prometheus` - the prometheus scraper ready format e.g. `syslogng_center_processed{stat_instance="queued"} 0`
=> Prometheus stats query support

lib/transport/transport-tls.c, news/bugfix-5271.md
`log_transport_free()` is responsible for the shutdown, which requires an open fd.
Backport of [420](https://github.com/axoflow/axosyslog/pull/420) by @MrAnno
=> transport-stack: fix shutdown 

lib/cfg-source.c
Sometimes (especially with location tracking bugs) a grammar location may be outside of the dimensions of the source text. Make sure we never index outside of the dimensions of the "lines" array.
This is not an exploitable problem, as the index that can overflow cannot be controlled externally. It will cause a segfault if there's a location tracking issue or if the source location we are extracting the source text from is incorrect.
Backport of [427](https://github.com/axoflow/axosyslog/pull/427) by @bazsi
=> cfg-source: avoid indexing over the end of the lines array

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h
Backport of [442](https://github.com/axoflow/axosyslog/pull/442) by @bazsi
=> logmsg: move log_msg_is_handle_*() to be inline

modules/systemd-journal/journal-reader.c
```
.../modules/systemd-journal/journal-reader.c: In function '_get_value_from_message.constprop.isra': .../modules/systemd-journal/journal-reader.c:218:7: warning: '__builtin___strncpy_chk' output truncated before terminating nul copying as many bytes from a string as its length [-Wstringop-truncation]
218 |       strncpy(buf + cont, key, key_len);
|       ^
In function '_format_value_name_with_prefix',
inlined from '_get_value_from_message.constprop.isra' at /source/modules/systemd-journal/journal-reader.c:243:3:
.../modules/systemd-journal/journal-reader.c:211:15: note: length computed here
211 |     key_len = strlen(key);
|               ^~~~~~~~~~~
```
This wasn't an actual issue as we were explicitly terminating the string with NUL in this case, so missing the NUL character was …
=> systemd-journal: fix spurious warning about about incorrect size passed to strncpy()

modules/http/http.c, news/bugfix-5281.md
When the URL is templated and batching is enabled it does not matter how many workers we have, we
need to close the batch when the partition key changes.
The condition for the if statement was wrong for a long time, however since 819001c6 it not only resulted in a missing error log and missing init fail, but we ran with `flush-on-worker-key-change(no)`, messing up the batching.
Signed-off-by: Attila Szakacs attila.szakacs@axoflow.com
Backport of [464](https://github.com/axoflow/axosyslog/pull/464) by @alltilla
=> http: enable flush-on-worker-key-change for 1 worker

lib/timeutils/tests/test_wallclocktime.c, lib/timeutils/wallclocktime.c
Backport of [478](https://github.com/axoflow/axosyslog/pull/478) and [487](https://github.com/axoflow/axosyslog/pull/487) by @bazsi
=> wallclocktime: make %f completely optional / optionally skip the leading dot in strptime(%f) parsing

lib/serialize.h
=> dqtool: Fixed segmentation fault when loading 16 bit buffer

packaging/rhel/syslog-ng.spec
Make sure that syslog-ng rpm also compiles on RHEL 10 and compatibles, only using dependencies available in RHEL 10 and EPEL 10. MQTT support is disabled, will be most likely available soon.
=> packaging: Update syslog-ng.spec to support RHEL 10 and compatibles

.gitmodules
This version is a simple replacement of the original https://github.com/buytenh/ivykis with our https://github.com/balabit/ivykis
The sub-module head still points to the latest master.
Resolves: https://github.com/syslog-ng/syslog-ng/issues/5193
Resolves: buytenh/ivykis#38
=> ivykis: Use our own ivykis fork (in the internal ivykis builds)

modules/cloud-auth/CMakeLists.txt, modules/cloud-auth/Makefile.am, modules/cloud-auth/azure-auth.cpp, modules/cloud-auth/azure-auth.h, modules/cloud-auth/azure-auth.hpp, modules/cloud-auth/cloud-auth-grammar.ym, modules/cloud-auth/cloud-auth-parser.c, news/feature-5293.md, scl/CMakeLists.txt, scl/Makefile.am, scl/azure/azure-monitor.conf, tests/copyright/policy
`cloud-auth`: Added `azure-monitor()` destination
Added oauth2 authentication for Azure Monitor destinations.
Example usage:
``` config
azure-monitor(
dcr-id("dcr id")
dce-uri("dce uri")
stream_name("stream name")
auth(
tenant-id("tenant id")
app-id("app id")
app-secret("app secret")
)
)
```
Backport of
- [457](https://github.com/axoflow/axosyslog/pull/457) by @sodomelle
- [531](https://github.com/axoflow/axosyslog/pull/531) by @jszigetvari
=> Azure sentinel destination

lib/logmsg/logmsg.c, lib/logmsg/logmsg.h
This adds a counter to LogMessage to track changes made to the NVTable. Any set_value() would increment that counter.
Any other fields (timestamps, etc) are not yet tracked, but probably should...
Backport of [447](https://github.com/axoflow/axosyslog/pull/447) by @bazsi
Depends on https://github.com/syslog-ng/syslog-ng/pull/5274
=> logmsg: add generation counter

modules/cloud-auth/azure-auth.hpp, modules/cloud-auth/google-auth.hpp
There is a macro that modifies the number parsing behavior of picojson (PICOJSON_USE_INT64).
When jwt-cpp/jwt.h includes picojson.h it explicitly enables PICOJSON_USE_INT64. I did not check the code thoroughly, but it is possible that they explicitly build on some int64_t related functionality.
However if we directly include picojson.h without setting PICOJSON_USE_INT64, picojson will not have int64_t support. This resulted in a strange behavior of having int64_t type hinted value in a json object, but the type checker not recognizing it as a number.
Backport of [481](https://github.com/axoflow/axosyslog/pull/481) by @alltilla
Depends on https://github.com/syslog-ng/syslog-ng/pull/5275
=> cloud-auth: do no directly include picojson/picojson.h

modules/grpc/otel/syslog-ng-otlp-dest-worker.cpp, news/bugfix-5267.md
Missing from:
[340532c3ac0c3c5979bc5cf3090d39384c4f45fa](https://github.com/syslog-ng/syslog-ng/pull/5184/commits/340532c3ac0c3c5979bc5cf3090d39384c4f45fa)
Backport of [384](https://github.com/axoflow/axosyslog/pull/384) by @alltilla
Depends on https://github.com/syslog-ng/syslog-ng/pull/5266
=> grpc/otel: add missing client context creation to syslog-ng-otlp()

modules/grpc/common/grpc-dest.cpp
Continuation of https://github.com/syslog-ng/syslog-ng/pull/5265
Backport of [404](https://github.com/axoflow/axosyslog/pull/404) by @alltilla
Depends on https://github.com/syslog-ng/syslog-ng/pull/5287
=> grpc: fix batch-lines() in case only batch-bytes() is set

modules/grpc/common/credentials/grpc-credentials-builder.cpp, modules/grpc/common/credentials/grpc-credentials-builder.h, modules/grpc/common/credentials/grpc-credentials-builder.hpp, modules/grpc/common/grpc-grammar.ym, modules/grpc/common/grpc-parser.h, news/feature-5270.md
It seems like gRPC sets the audience and scope options based on the gRPC service name, so they can't be set in the config.
Example usage:
```
destination {
google-pubsub-grpc(
project("test")
topic("test")
auth(service-account(key ("path_to_service_account_key.json")))
);
};
```
Backport of [412](https://github.com/axoflow/axosyslog/pull/412) by @sodomelle
Depends on https://github.com/syslog-ng/syslog-ng/pull/5269
=> grpc: add service accounts

lib/logpipe.h, lib/poll-events.h, lib/poll-fd-events.c, lib/poll-fd-events.h, modules/affile/directory-monitor-inotify.c, modules/affile/directory-monitor.c, modules/affile/directory-monitor.h, modules/affile/file-reader.c, modules/affile/file-reader.h, modules/affile/tests/test_wildcard_file_reader.c, modules/affile/wildcard-file-reader.c, modules/affile/wildcard-file-reader.h, modules/affile/wildcard-source.c, news/feature-5307.md, news/feature-5312.md, news/feature-5315.md
`wildcard-file`: Added inotify-based regular file change detection using the existing inotify-based directory monitor.
This improves efficiency on OSes like Linux, where only polling was available before, significantly reducing CPU usage while enhancing change detection accuracy.
To enable this feature, inotify kernel support is required, along with `monitor-method()` set to `inotify` or `auto`, and `follow-freq()` set to 0.
This PR will have a follow-up pair as we have to fix the full-path handling in the file-reader and the directory monitor which is really messy. FIXME notes will be removed in the [next round](https://github.com/syslog-ng/syslog-ng/pull/5317).
Resolves: https://github.com/syslog-ng/syslog-ng/issues/5019
=> Wildcard file inotify

lib/pathutils.c, lib/pathutils.h, modules/affile/directory-monitor-content-comparator.c, modules/affile/directory-monitor-inotify.c, modules/affile/directory-monitor-kqueue.c, modules/affile/directory-monitor-poll.c, modules/affile/directory-monitor.c, modules/affile/directory-monitor.h, modules/affile/tests/test_directory_monitor.c, modules/affile/wildcard-source.c
Using now the full path everywhere
Depends on https://github.com/syslog-ng/syslog-ng/pull/5315
=> Fix directory monitor path chaos

lib/logproto/logproto-buffered-server.h, lib/logproto/logproto-client.h, lib/logproto/logproto-server.h, lib/logproto/logproto-text-server.c, lib/logproto/tests/test-proxy-proto.c, lib/logreader.c, lib/logreader.h, lib/logwriter.c, modules/affile/file-reader.c, modules/affile/poll-file-changes.c
The branch itself simplifies the LogProto handshake API and adds a unit test for the LogProtoAutoServer class (rfc6587)
Backport of [155](https://github.com/axoflow/axosyslog/pull/155) and its fix [407](https://github.com/axoflow/axosyslog/pull/407/commits) by @bazsi
Depends on https://github.com/syslog-ng/syslog-ng/pull/5318
=> Logproto remove handshake in progress

lib/logreader.c, modules/affile/stdin.c, modules/affile/stdout.c
Backport of [557](https://github.com/axoflow/axosyslog/pull/557) by @OverOrion
=> modules/affile/std{in|out}: register stdin/stdout with proper name instead of dash

dev-requirements.txt
Removes the no longer needed python 2 dep (logilib-common)
=> dev-requirements: remove logilab dep for old drone.io

modules/grpc/bigquery/bigquery-worker.cpp, modules/grpc/clickhouse/clickhouse-dest-worker.cpp, modules/grpc/common/grpc-dest.cpp, modules/grpc/common/grpc-dest.h, modules/grpc/common/grpc-dest.hpp, modules/grpc/common/grpc-grammar.ym, modules/grpc/common/grpc-parser.h, modules/grpc/loki/loki-worker.cpp, modules/grpc/otel/otel-dest-worker.cpp, modules/grpc/pubsub/pubsub-dest-worker.cpp, news/feature-561.md
With this option, it is possible to fine tune how AxoSyslog behaves in case of different gRPC results.
Supported by the following destination drivers:
- opentelemetry()
- loki()
- bigquery()
- clickhouse()
- google-pubsub-grpc()
Supported gRPC results:
- ok
- unavailable
- cancelled
- deadline-exceeded
- aborted
- out-of-range
- data-loss
- unknown
- invalid-argument
- not-found
- already-exists
- permission-denied
- unauthenticated
- failed-precondition
- unimplemented
- internal
- resource-exhausted
Supported actions:
- disconnect
- drop
- retry
- success
Usage:
```
google-pubsub-grpc(
project("my-project")
topic("my-topic")
response-action(
not-found => disconnect
unavailable => drop
)
);
```
Depends on  https://github.com/syslog-ng/syslog-ng/pull/5324
Backport of …
=> grpc: response-action()

modules/grpc/clickhouse/clickhouse-dest.cpp
Constructing a map with FieldDescriptorProto::TYPE_* produces symbols for enum values:
U _ZN6google8protobuf20FieldDescriptorProto11TYPE_DOUBLEE
This causes a linkage issue with CMake, which I couldn't resolve, but in the end, these values should not appear in the symbol table, so a static_cast is applied as a workaround.
Backport of [610](https://github.com/axoflow/axosyslog/pull/610) by @MrAnno
=> clickhouse: avoid creating symbols for enum values

.github/workflows/draft-release.yml
Otherwise, it'd use the default branch, which now develop
=> github: draft-release action target master branch when creating a release

lib/Makefile.am, lib/logpipe.h, lib/logproto/logproto-text-server.c, lib/logreader.c, lib/logreader.h, lib/notified-fd-events.h, lib/poll-events.h, lib/poll-fd-events.c, modules/affile/CMakeLists.txt, modules/affile/Makefile.am, modules/affile/affile-grammar.ym, modules/affile/affile-parser.c, modules/affile/file-monitor-factory.c, modules/affile/file-monitor-factory.h, modules/affile/file-reader.c, modules/affile/file-reader.h, modules/affile/poll-file-changes.c, modules/affile/poll-multiline-file-changes.c, modules/affile/tests/test_wildcard_file_reader.c, modules/affile/wildcard-file-reader.c, modules/affile/wildcard-file-reader.h, modules/affile/wildcard-source.c, news/feature-5338.md
This PR 
- fixes issues of the new inotify-driven `file()` and `wildcard-file()` monitoring, even though inotify sends file change notifications correctly, but not fully processed changes (e.g. when there are more changes than a fetch cycle (fetch-limit) can handle) will not be notified again till there are no new changes that could lead to delayed or lost change processing
- adds `follow-method()` option to `file()` and `wildcard-file()` sources
Doc PR: https://github.com/syslog-ng/syslog-ng.github.io/pull/192
Signed-off-by: Hofi hofione@gmail.com
=> Fix wildcard file regression

modules/python-modules/syslogng/modules/webhook/source.py, tests/copyright/policy
In python 3.9 the event must be created inside the event loop that will await on it or else the await will fail
=> python-modules/webhook: fix issue when stopping the server on rhel9

modules/python-modules/syslogng/modules/webhook/source.py, tests/copyright/policy
>webhook: add missing copyright header
>>The feature was developed by me during working hours, on behalf of
Axoflow.
Backport of [630](https://github.com/axoflow/axosyslog/pull/630) by @MrAnno
=> webhook: add missing copyright header

contrib/get-github-actions-status.py
report the proper response in case a call to the GitHub API failed.
=> get-github-actions-status: verbose reporting of API errors.

news/feature-5383.md, scl/CMakeLists.txt, scl/Makefile.am, scl/freebsd-audit/plugin.conf
`freebsd-audit()`: added a simple source SCL to collect FreeBSD audit logs using the built-in praudit program
https://www.syslog-ng.com/community/b/blog/posts/freebsd-audit-source-for-syslog-ng
Resolves https://github.com/syslog-ng/syslog-ng/issues/5373
Related https://github.com/syslog-ng/syslog-ng/discussions/5150
=> freebsd-audit-source: add the source scl

modules/python-modules/syslogng/modules/s3/s3_destination.py, modules/python-modules/syslogng/modules/s3/s3_object_buffer.py, modules/python-modules/syslogng/modules/s3/s3_session_handler.py, modules/python-modules/syslogng/modules/s3/scl/s3.conf, news/feature-5286.md
This pull request introduces two new options for `s3`:
* `content-type()`: users now can change the displayed content type of their logs.
* `use_compression()`: in version 1.36 botocore developers changed the default integrity check settings (see https://github.com/boto/boto3/issues/4392). This option allows the users to change the default `when_supported` value to `when_required` for S3 compatible solutions that don't support checksums.
Usage:
```
s3(
url("http://localhost:9000")
bucket("testbucket")
object_key("testobject")
access_key("<ACCESS_KEY_ID>")
secret_key("<SECRET_ACCESS_KEY>")
content_type("text/plain")
use_checksum("when_required")
);
```
Based on [408](https://github.com/axoflow/axosyslog/pull/408), [486](https://github.com/axoflow/axosyslog/pull/486) and …
=> S3 updates

lib/logproto/logproto-client.h, lib/logproto/logproto-text-client.c, lib/logproto/logproto-text-client.h, lib/logwriter.c, lib/logwriter.h, lib/transport/logtransport.c, lib/transport/logtransport.h, lib/transport/transport-stack.h, lib/transport/transport-tls.c, modules/affile/logproto-file-writer.c, modules/affile/named-pipe.c, modules/afprog/afprog.c, modules/afsocket/afinet-dest.c, modules/afsocket/afsocket-dest.c, modules/afsocket/afsocket-dest.h, modules/afsocket/afsocket-grammar.ym, news/bugfix-5390-1.md, news/bugfix-5390-2.md
Fixes the collectd() destination (we never read the server's response).
Fixes possible starvation issue on the destination side when reading server responses
Fixes: [604](https://github.com/axoflow/axosyslog/issues/604) and workarounds TLS-related state handling issues
Backport of [609](https://github.com/axoflow/axosyslog/pull/609) and [665](https://github.com/axoflow/axosyslog/pull/665) by @MrAnno and @bazsi
Depends on https://github.com/syslog-ng/syslog-ng/pull/5262
=> Move EOF detection and close-on-input to the proto, fix tls key update

modules/affile/affile-grammar.ym, modules/affile/affile-parser.c, modules/affile/wildcard-source.c, modules/affile/wildcard-source.h, news/feature-5416.md, tests/functional/func_test.py, tests/functional/test_file_source_exclude.py
Add ability to refine `wildcard-file( filename-pattern() )` option with `exclude-pattern()` to exclude some matching files. Example: match all `*.log` but exclude `*.?.log`.
A new option for the wildcard-file source is added and a new functional test that ensures `exclude-pattern()` works is included in `tests/functional`. The new test is a separate test file, because `exclude-pattern` doesn't need to be tested with the same `poll/auto` configuration variants that the rest of the `affile` tests need to be exercised with.
The implementation is just a new option in the module's config parser and one new logic test in `modules/affile/wildcard-source.c:_handle_file_created()`.
=> affile: add exclude-pattern() option to wildcard-file()

scripts/style-checker.sh
The script check the output of astlye(1) for messages in English, but
when the user locale is different, it will not successfully detect files
with style issues.  Ensure we have the default C locale before checking
style.
While here, make the script more portable by not requiring bash (which
might not be available as /bin/bash).  Rely on plain sh (which is known
to be at /bin/sh) and remove bashisms.
Signed-off-by: Romain Tartière <romain@blogreen.org>
=> Fix locale-dependent behavior and improve portability

modules/python-modules/syslogng/modules/s3/s3_destination.py, news/bugfix-5447.md
S3 destination did not trigger uploading files if the number of ready buffers was higher than the maximum parallel uploads.
=> S3: Fix missing upload trigger

modules/afprog/afprog.c, news/bugfix-5444.md
Reloading syslog-ng after a config change caused syslog-ng to crash. During the `main_loop_reload_config_apply` the cfg is de-initialized and freed, however in `afprogram_dd_deinit` the log writer is stored `afprogram_dd_store_reload_store_item` before the cfg is freed. The log writer is then restored and the cfg it points to no longer exists. When `log_pipe_init` or `log_pipe_deinit` calls `cfg_tree_register_initialized_pipe` for the log_writer this results in an invalid read, causing a seg fault crashing syslog-ng. 
See here: https://github.com/syslog-ng/syslog-ng/issues/5444
To prevent the crash, when the log-writer is stored before the reload takes place the stored log-writer's pointer to the cfg is released. When the log-writer is restored, the cfg is set to the new cfg.
Alternative …
=> Fix invalid access of freed log-writer cfg

lib/logwriter.c, modules/affile/affile-dest.c
the original affile_dw_reopen impl in affile_dw_init treated the open result as an error only if the error was permanent; rollback that behavior, otherwise the pipe is closed and reopen attempt will never happen again (as its timer is destroyed)
=> Fix logrotate

.github/workflows/create-packages.yml
temp, quick workaround of no more sudo in app armoure protected (now just in arm64, but I guess soon in all) rhel derivated images
=> Disable app armor in package creations

CMakeLists.txt, configure.ac, modules/affile/CMakeLists.txt, modules/affile/Makefile.am
- prefer kqueue always as inotify is just a wrapper around it if both are presented
- like it is implemented in ivykis
- make sure the current logic in our directory and file monitors will not hurt if both are presented (do not change the current source logic)
=> Detect and use either kqueue or inotify, but never both.

packaging/package-indexer/Dockerfile, packaging/package-indexer/indexer/indexer.py
Because the backend doesn't support dynamic index files, we have to generate static index.html's during the indexing process, to make the repositories browsable.
=> package-indexer: generate static index.html files

packaging/package-indexer/remote_storage_synchronizer/azure_container_synchronizer.py
Collection of fixes found during testing:
Set proper content-type for uploaded files.
Container synchronizer handles properly, when the blob's checksum field is empty. 
Container synchronizer sets the proper mtime on the downloaded files, so the static html files contain the proper last modified information too.
=> further fixes for the static html support for the package indexer

.github/workflows/macos.yml, .github/workflows/publish-docker-image.yml, contrib/Brewfile
- brew dropped macOS13, so we are
- added all the GitHub supported versions for testing (though 26 arm64 is still excluded, as that is the main dev platform, only 1 intel version test remained)
Depend on: https://github.com/syslog-ng/syslog-ng/pull/5513
=> Ci shift supported macos versions
